metadata:
  gen_time: 8.02263617515564
  timestamp: '2025-04-18T22:59:20.905508'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#       # #b#             l   #   # #             # # # #                # # # # #### #    t          t   ##   ##        #
# # ### # # # # # ##### ##### # ### ### ### # # ### # # ###f# # # # #        t                           #    #   c#     #
# # #       # # #   # # #   # #     #   #  b# # #   #   #         # #  #  b              #        t                 #    #
# ### # ### # ####### ### # # # ######### # # ### # # # ### # # ### ####          r       # #       #               #    #
#l#   #t#t  #         # # #     t   #   # #       # # #   #     #      #       b     g       # c     # #            a#   #
# ###t### # # ### # # # # ####### ### ### ### ### # ### # ### ### # ####    t                #          #     #      #   #
#       # #     # # #l#       #     #     # # #t  # #   #       # #    #                      #    f       #   # rt #    #
#f# # ### ### #####l# #   ### ### # #b# # # # ### # #f### ### # # ###  #         t         #      c         #  #         #
# #f  #     #                b    #   # #       # #       #     # #f#  #   g           b    #   #l          #   #        #
# #   ### ##### ### ### ######### # ######  # # ### ##### ##### # # #  #                        c#     #    c#           #
# # #       #   # # #b#        bf # #     #   # #       # #       #    #               f         #    #      c  #        #
# ### # ####### # # #   ######### ##### ### # # ### ### ##### ##### ####                          #   #        #  f #    #
#   # # #         # # # # #     #     # #   # # #A# # #     #   # # #  #             gf      # a      t#       #     #   #
# # # ### # # # # # # # # ##### ##### # ### # ### # # ####### # # ###  #   r      c      #  #     #    #        # c    cg#
# #   #   # # # # # # #     #     t   # # # # # #     #    t# # #   #  #               l#   #      #    #g  r            #
# # ### ### ### ##### ### ### # # # ### # # # # ### # ### ### ### ###  #   b            b    #      t   #       #     c  #
# #   t b     #   #   # #   # # #         # # #     #  t      #     #  #      t              #           #    cc # g     #
##### ### ####### ### # # ######### ### ##### # ### ####### # ##### # f#       g  r        c  #   #      #           #   #
#       #   #   # #   #     #   #   #       #   # #       # # #        #           f        c      ##     #  c a      #  #
# ##### ####### # # # # ####### ### # ### # # # # ### ###f##### # ######         t            #c c c ##         #     #  #
#         l #l#    b  # #   #     # #   # # # # # #   #     # # # #    t                       #       ## c      #     # #
# ###   # #   ###   # #b# ### #b# # # #A# #t# ### ### # # ### # # ###    ###############   # c # c       ##   c          #
#   # # #   #     # #           #   # # #     #   r     #       #           A             #     #          #       #     #
#   # # #  t#     # # g       # #   # # #     #         #       #        ############### g#     #    c  c     # #   #    #
# ##   ####   ##   ##b     ######r ######  ##############     ####                         #     #  c   #    #   #     # #
#        l    ##   ##  ##  ######t ######            l    r   ####       ###############    A #    t   #     #  g   c #  #
#             ##       ##  ######  ######      f                                             #r        #      #     fg#f #
###t  ##        b             bb                              l        #                     #    c     #  #     #     # #
###b  ##         l          f                           ###  ##########        f         c    #   #         #   #     a  #
#     ##     ##########   ##########################f   ###  ###########                   #     # c  #     #   #        #
#     ##  b  ##########   ##########################    ###  ##########      g            #c   c #   #    t  #   #c      #
####  ##                      f    l                              A      ###############  #       #  #     f     #       #
####  ##       t              g                    l            t   t                      #      #   #  c        #      #
####  ##  #######################################################      #           c         f     #              #      #
####      #######################################################     g# r                    c    #         #     #    ##
####    b #######################################################    ###   t              c     #   # #  a  #c  #        #
####   g                           b               g                 ###    b         l          # a   #    #  #   #    ##
####           r                         f                           ##                          # c c     #   #    #  a #
#### g   ###t  #####  ###############         r  l  b                    # # # # # #r# ##  f    #    #   f     c#   #    #
####     ###   #####  ###############  r r  ######      g ####           # # # # # # # #              ##             #   #
####    t###          ###############       ######       c####  ####     # # # # # # # #       b  #     #       b    #   #
####     ###    b     ###############      b              ####  ####     # # # # # # # #  t   #    #    c            a#  #
#                  f  ###############  r      b      ###  ####  ####b    # # # # # # # #       #   #b   #  g t           #
#  t                  ###############  ###########   ###  ####           # # # # # # # #        c #b     #               #
####### t    ##f ###  ###############  ###########   ###  ####           # # # # # # #t# c f #        c         g        #
####### g    ##  ###  ############### g###########       gbt    ####     # # # # # # # #      #     #    #          c    #
#     f      ##  ###  ###############  ###########              ####     # # # # # # # #      #    #      #  #  t   #    #
#            ##          b             ###########     #######           # # # # # # # #       #   #      #   ##     ## f#
#  ######                              ###########     #######           # # # # # # # #    #  fc   #    #      # #    ###
#  ######                                                 g              # # # # #l# # #   c #c     #   c#  #      #     #
#  ######b                    ##t                             A  t   ## g# # #r# # # # #         g   #  #  cc#  c  #     #
#t ###   A   ####   ####    ####  ####     ##    #  #        c          ##t## #                           ##   ## ##     #
#  ##         ## g ####   f  ###    #  l   ##   ######    ##        l   ## fr ##r     t      r            ####    ##     #
#bg    #      ##    ##       ####      ##       ######    ##    g       b      #   g                      ####           #
##    ####c     A           ######    ####c       ##al             r      #### #            t     ##           r        b#
###  a#### g f c ##    g    #####      ##                           r     #l   #                  ##       ##      g     #
####    #f       ##           #g       l          ##        ##   f   ##   #                       ##       ##      g     #
###        ## g         # b         ##          ######     ###       ##   #   ###       r       l                        #
###       #####       ####         #####    c   #######     ##       b    ### ###                   ####    t###l  t     #
##   ##    ####       ######        ####l        # b##                 ##     ###     l      r      #  #     ### g       #
#   #####  #####  #     ####          #   ## g               f         ##                           #  #####             #
#    ####   ########     ##   ##  #      ###  f     g              l   ##   l    g                  #      ####    ##  f #
#  f  ####  ########         ########     ####        ##        b   ## rr   b        g              #   ##    #    ##    #
#     ####r   #  #            #########    ##       r ##   ##      r##      f                  t    #g  ##    ####    r###
#A      #            ##         #  #####                   ##       ####     g  f                   #   ##   l   ##### ###
#  ##    c ##        ###            ####  b##      ##cg             ####                            ###        #       ###
#  ##     #####     ####    c         #   ####    ####         r                g            g        #        #         #
#          ####  c  #####    ##  ##     g  #####   ####   ##         ##     r              g          #####  lg#       b #
#           ####   c  ##    #######        ######  ###  c####        ##    l                  l   t       #    #####     #
# b         ####     c       #######      ######    ##    ##     ##  ##  b             lb                b#        #     #
#     r      ##       c      ##  ##  l     ####      t        g  ##  ## r                                 #        #     #
#  b         ##  ##     ##                  ###        ##        ##  ##            g t                    #        #     #
#        ##      ##    ####   l b   ##  ## b##       #####           ##                f              tg  #        #     #
#      t#### b          ##   ##     ##  ##           ####            ##                  l                #        #     #
#        ###                ###                ##      ##       c #####        r         b             b  #    f   #     #
#   l     ###g  f            ###       f     ####    c ###        #####                   ##   bl   ###g  ###      ###   #
#         ##             ##  #####           #####    r##                   t      ###### ##        ###     # t      #   #
#    f      b            ##   ####     ##      ##          ##   g                  #      ##       a    ##  #        ### #
#                   g          #   l   ##    f     ##      ###    # ##        f    #                g   ##  #  c  g    # #
#  f                  ##          f        gb  ##b ##     ####    #  #             #####    l               ###        ###
#            ##    f ####        ##            ##         ####    #  #   t           gl#    l                 #          #
# g         ####      ##        ####            b           ##ll  ####   b             #######     t          #          #
#    ##      ##            ##    ##   ##                        b g     b                  b #                #          #
#   ####  r        ##     #####      #### g         ##           l ##             #####      #    ###         #    ##    #
#    ####        ####      ####       ##           #####  ##       ##             #####      #   g###r  l     #### ##   ##
#    l##     f   #####     #####                 b f#########         g              ##      ####b                r##   ##
#   a   f         #####   ######     f        ##      #######  g            b        ##         ####           ##       ##
##    ##  la      #####c   ######l           ##### t r  #  #f       ###############f ##       ######           ##        #
##  #####           #      #####            f #####       c   ##### ###############  ####     ######           ######### #
#   ####   t                 ###     #    ##   ##### f       #      #####  ########  ####      t     ##        ######### #
#    #         c      ##      ###  ####   ##    ###   ##     # rt       # ##   ####                  ##     t  ###  #### #
#                     ##     f##   ####         ##   #####           ##      ###      ##      #########        ###  #### #
#      ##f                   ###    #           b c   #####          ##      #####    ##  r  r#############         ######
#      ##                 c   ###          ##        a#####  #          ##########     g ####     #########     ###l  ####
#     f                       ##          ####         b## g            ##############   ####     ####  ###   l ###   ####
#              ##                  ##     f## g g                       ######  ######          ######  ###     #####    #
#             ####     r         c###      ##   ##     t                ######  #########       ####tb  ###r    #####    #
#          r   ###                 ###    ####  ##       ##   tg     ######### ##########l#####    ####           ###    #
###     b       ###                ##   #####           #####        #####  ## ###  #####     ####    ####b       ###    #
###g      ##    ###      ##             ####             ####      r r   # ##    # ## tt   ##   r####t   #              t#
## r      ##     #       ## r            ###         a     #          ##      ##   r  ##   ##  #    #    ###l      t  l  #
##     l                #### c      g     ###        g           r    ##      ##      ##   ##  #    #      #     t       #
###                    #####              #####    ##    b       t    ##                   ##  #    #      #   a ###     #
##              c       #####     f      #######  ###             t   ##        ######  ##     #    #####  ##### ### #####
#             g           ###    ##  A l ######    ###        g       ##          t  #  ##     #        #        ###r    #
#             c      ##    ###  ### g   g  ##     b##                 ##        #    #t ##     ###      #     g       ## #
##    #t            ####   ##    ###                      f#          ##   gt   #b   #  ##       #   l  ###          g## #
##  ####      c      ####    g   ##      c ##            ####         ##        #    #          b###    t #   ##         #
#l  ##### g    c      ##   c               ###    l  b   ####  g                # f  #    ###      #      ### ##         #
#    ###   ##                 a       c   #####    c##    #         g      g ####  t #    ###      #    r     ##       l #
#   g## f ###g        ##                 #####r    #####    b  b             #       ###g     # ##        f       ####   #
#       f  ###       ###           # g   r####c     ####    c       r        #         #   ####  ####             ####   #
#          ##         ###       l####       #l   g  b#        #### t t       ###       ### ########## l####       ########
#          f   ## ##  ##    #    ####         t       f  g    ####             #         l ######## l  #### r       ######
#g   b         ## ##      ####    ##   ##         ##      f   #                #        #    ######  ######l ###    ## b #
#         g        c      #####       b##        f##      r ##  #              #       r#     ###    ####    ###    ##   #
#                         g####   ##        l          l  ####  #   #####      ###      ####l   ####    ####             #
# c                g   ## g  #   ##### c  ##              ####  ### #####        #    g    ####    ####    # ##      f  l#
##           ##       ####    l   #####   ##   f          g#        #####      b #       #    ####    ####    #          #
####        #####      #####      ####                b       ##       ##    #####       #  #    ####   r#    #g         #
##########################################################################################################################
