metadata:
  gen_time: 6.989092826843262
  timestamp: '2025-04-11T22:31:27.840772'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
######################################################################################################
####   ##  ##    ####             #####   ##  #######         ##    ###    ##  ##    ##  ####   ######
####   ##        ####             #####   ##            ##    ##    ###    ##  ##        ####   ######
####                              #####   ##            ##          ###        ##        ####   ######
#                                 #####   ##                        ###                  ####   ######
#         ##########              #####   ##                        ###                         ######
#  #####  ##########  ####        #####   ##      #####                                              #
#  #####  ##########  ####  ##    #####           #####  ########            ###                     #
#  #####                    ##                           ########  ######    ###  ######             #
#  #####                    ##                           ########  ######    ###  ######   ####      #
#  #####        ###  ###    ##               #########   ########  ######    ###  ######   ####      #
#               ###  ###        ##   #####   #########             ######    ###  ######   ####   ## #
#           ##  ###             ##   #####                         ######    ###  ######          ## #
#####   ##  ##  ###             ##                                           ###  ######             #
#####   ##  ##        #######   ##              #####                        ###  ######             #
#####       ##        #######                   #####     #######    ######  ###  ######   ###   #####
#           ##                                            #######    ######  ###           ###   #####
#           ##                  #########                 #######    ######  ###           ###   #####
#           ##    ####   ###    #########  ##             #######            ###      ##   ###   #####
#                 ####   ###    #########  ##  ##         #######            ###      ##   ###       #
#    ####                ###               ##  ##                                     ##   ###       #
#    ####                ###               ##  ##                       ##                 ###       #
##   ####                ###  ##    ####   ##                           ##                           #
##                            ##    ####                        ######  ##      ##                 ###
##             ##  ####       ##    ####            ##########  ######  ##      ##  ############   ###
#   ##         ##  ####  ###  ##                    ##########  ######  ##      ##  ############   ###
#   ##         ##        ###              ######    ##########          ##  ##  ##  ############   ###
#   ##         ##                         ######                        ##  ##  ##  ############   ###
#   ##    ###      ####                                                     ##  ##                 ###
#   ##    ###      ####        #######                  #####  ##  ##       ##  ##                   #
#   ##             ####        #######  ##  ##   ##     #####  ##  ##       ##  ##                   #
#   ##                    ##   #######  ##  ##   ##     #####      ##       ##           ####       ##
#   ##                    ##   #######      ##   ##                ##  ##   ##           ####       ##
#   ##                    ##   #######           ##                ##  ##                ####        #
#   ##                                           ##   ########         ##         ###    ####        #
#   ##           #####                       ##       ########                    ###    ####        #
#   ##           #####      ###   ###        ##                                          ####        #
#                           ###   ###  ##    ##                          ###                    ######
#           ##              ###        ##                  ####  ##      ###      ##            ######
#####       ##  ####        ###                   ######   ####  ##      ###  ##  ##                 #
#####  ###  ##  ####                              ######   ####  ##  ##  ###  ##  ##                 #
#####  ###            ###                         ######   ####  ##  ##  ###      ##    ##########   #
#                     ###               ######    ######   ####      ##  ###            ##########   #
#                     ###   #####       ######    ######   ####                         ##########  ##
#     ##  #####       ###   #####  ###  ######    ######                          ##                ##
#     ##  #####                    ###                                            ##                 #
#     ##                                                   ##            ######       #####          #
####  ##         #####                      #######        ##  ##        ######       #####          #
####  ##         #####          ##          #######        ##  ##                     #####     #### #
#     ##                        ##  ###     #######        ##  ##   ##                #####     #### #
#                                   ###                    ##  ##   ##       ####     #####     #### #
#         ######                                           ##  ##            ####     #####     #### #
###       ######    #########            ##  ###           ##  ##                     #####     #### #
###                 #########  #####     ##  ###           ##                         #####     #### #
###  ##             #########  #####         ###           ##         ##  ####  ####  #####          #
#    ##   ####                                             ##         ##  ####  ####  #####          #
#         ####                         ##                  ##         ##        ####  #####  ####### #
#                ##     ######         ##         ####     ##         ##              #####  ####### #
# ####           ##     ######   ####  ##         ####     ##         ##   ##         #####  ####### #
# ####  ###                      ####  ##         ####                ##   ##         #####  ####### #
#       ###                      ####             ####         #####  ##   ##         #####  ####### #
#                     ######               #####  ####     ##  #####  ##              #####  ####### #
#                     ######               #####  ####     ##  #####             ##          ####### #
##            ##               #########          ####     ##                    ##                  #
##   ###      ##               #########                   ##               ##   ##                  #
#    ###      ##    #########              ##              ##               ##                  ######
#    ###      ##    #########              ##   ###   ###  ##  ##                       #####   ######
#    ###  ##  ##    #########       ##     ##   ###   ###  ##  ##       ##        ##    #####        #
#         ##                        ##                ###  ##  ##   ##  ##        ##    #####        #
##                                                    ###  ##  ##   ##            ##    #####        #
##                                           #######  ###      ##   ##            ##           #######
#     ####                             ####  #######           ##   ##                         #######
#     ####   ##         ###   ######   ####                         ##  #####                  #######
###   ####   ##         ###   ######                                ##  #####        ##        #######
###          ##  #####        ######            ############        ##  #####        ##        #######
###              #####        ######            ############  ##    ##  #####  ##                    #
#                             ######                          ##    ##  #####  ##                    #
#                             ######       ###                      ##  #####  ##       #######  #####
# #####  ##                   ######       ###  ###    ###              #####  ##  ##   #######  #####
# #####  ##     ##  ######    ######       ###  ###    ###   ##         #####  ##  ##   #######  #####
#               ##  ######            ##   ###               ##  ##     #####  ##  ##   #######  #####
#                                     ##   ###                   ##     #####      ##   #######  #####
###                                   ##                                #####           #######      #
###   ##                        ###   ##                 ###            #####           #######      #
#     ##                    ##  ###               #####  ###            #####    ##     #######    ###
#         ##       ##       ##                    #####  ###  ##        #####    ##     #######    ###
##        ##   ##  ##                             #####       ##        #####    ##                  #
##        ##   ##                 ###  ########   #####       ##        #####                        #
##  ##    ##   ##      ##         ###  ########                                                      #
##  ##                 ##  ####        ########                    ##               ########    ######
#   ##                     ####        ########      ###  ###      ##               ########    ######
#             #####        ####        ########      ###  ###  ##       ##  ###     ########         #
#        ###  #####                    ########      ###  ###  ##       ##  ###                      #
###      ###  #####               ##   ########      ###  ###               ###                     ##
###                  #########    ##   ########      ###  ###      ###                      ##      ##
#    ##              #########         ########                    ###                 ##   ##       #
#    ##                                                            ###  #######        ##   ##       #
#    ##    ##                   ##                     #####  ###  ###  #######  ##         ##    ####
#          ##            ##     ##                     #####  ###  ###  #######  ##               ####
#          ##    ####    ##     ##                     #####  ###                ##  ##           ####
#          ##    ####    ##               ###  #####   #####  ###                ##  ##       ##  ####
######################################################################################################
