metadata:
  gen_time: 16.887719869613647
  timestamp: '2025-04-18T22:47:11.174167'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#        ##    ############       #   #   #   #    ###  ##g ###  #   f     c       l     b  a      ####  ##           ## #
###     ####    ###########    # ##  ###  #  ### ####   # # ##   # #                g             t####  ##   #  #       #
####   ######    #########      #   #   #   #    #    ##     c ##  #l          b                   ##    ##   #  #       #
#####  #######                 ### ## g### ### ###    #f# #    #g# ### ###     g################ b ##    ## f ####  ##   #
#####  ########                                #        ##     c #   # #        ################   f                     #
##### f########    ############# ###     ### # # ###    # ###    #   ###        ################      r    g             #
####    #######   #############  #       #   #     #      #      ### ###          r                         f##  ##  ##  #
###   r  #####    ################       # ### ### ###    # ###  l #  #                l                     ##      ##  #
#          r   g  ##############           #  t   t  #f     #      ### #### g                       ##   ##         l    #
#  f    b         ############ # ####      #c        #      # ###    #   t                       g       ##              #
#             g   ###########f  ###    b   #         #  #     #g  f  ###   l              b     t         f              #
#  ##       ###    #########   # ####                   #     #l      t                            ##            ####### #
# ####     #####               #    # b              #        #      # #                           ##            ####### #
#######    #####r  f           #   A###       ###    #        #      # #  #                 r         g                  #
#######     ###                ###    #       #       f # c   ###         #    r          r              ##     r        #
#######          f       l            ###     #  t      #       #                             t     ##   ##              #
######                       t # ###    #                       ###   l  c#    b    g                   g    ##      ##  #
#####           l              c    l   #                         #       #              l                   ##  ##  ##  #
####  g  l  t  #########    ###   g     ### ###                g  ###           ################     t               t   #
###    ###  t ###########  ####           #  #          #          c      ###   ################        t                #
#     #####   ###########  ####  l        ### ###       #         # #       #   ################   ##    ##r  ####  ## t #
#     ###### t########## r ####          f               f # #    # #  g  ###                      ##   b##   #  #       #
##    ######  #########    ####cg                          # #   t                                 ####  ##   #  #       #
###    ####b  ########      ###       f  ###                   f                           r       ####  ##           ## #
#### f         ######                  b      #                        ##       #  b###  ##  ################ #####   c  #
#####            f                       # #  #             #l          c             #        ##  g ##  #### #####      #
######     b           ####             t# #    l           #      cl                 #   a a  ##    ##  ##   l  ##      #
#######               ######    # ##          #f   g       c          ##                       ##        ##      ##      #
#######f    ######    #######b ##             #     A       #     lc                           g     ##  ##      ##      #
#######    ########    #######  #      g    g       t       #   #            #    ##   ####          ##  ##      ##      #
#######  l #########    ####### ### ### ###  g### ###           #   # #      #         ####         c##   l        cg    #
#######     #########    #######  #  #        #  #      t          c# #                       ##     ##  ##      ##      #
#######      ######## f   ####### ###g### ### # ### ### ## g    #    c  g    t                ##     ##  ##      ##      #
#######       ######     b ###              #         #      c  #             ##                   t     ##c             #
######f                                     #         # ##f    t   c               b        f     r  ##          ##t     #
#####     f      l             b  #g#t      # ##                                  f   ########     c ##  ##      ##      #
####   b  r                t  b   # #                                                 ######## l     ##  ##      ##      #
###    ##     t b     ###                                #    # #       ###c  ###       g##      ##c ##  ##              #
##    ####           #####                               # t  # #       # l l #          ##      ##cf    ##      ##c     #
#     #####          ######            ####                             #     #               l  ##  ##  ##              #
#   bg #####          ###### A            # f   f  b     #  l           # l   ###  ##   a    r ####  ##  ##      ##     t#
#       ####     ##    ######     f       #       r   g t#          ### #    l b   ##      ##  ####  ##  ##      ##  l   #
#  ## r  ##     ####    ######            #              #       r  #                      ##       b##          ##     g#
# ####          ####   t #####            ###l  fg                  #        #         ######            ##             c#
######           ##       ###   g   g       #            ###                ##         ######g       ##  ##   gg ##      #
#####     ##  g  b                g         #            #    cb    f       ####    #####a          f##t ##      ##    cc#
#        ####          l                  l # t   ###  ### ### ### ### ###    r     #####           c##    c             #
#        ####   t            ##                   #    #  #     #   #   #   g          ##        r   ##  ##    c ##      #
##       r##    t           #### ###            ### #### ### ##  ### ### ###          g##  ##        ##  ## c    ##    c #
###    t     f              ####                             f #  #       #      ##    ## r##a ##  c c   ##      ##  c   #
###f  g               ###    ##### ###       t                 ### ### ### ##    ##  ########  ##   l##  ##     g##      #
##              ##   #####       #   #             f             # l                 ########  gb    ##  #### #####      #
#            r ####  ######  g # # # ### ### # # ##              #            gl        ##        a########## #####    f #
# #  # #  # ## #   ########  # # ####          #    ## #  #   #   ##   #       c  #                r          #    #c    #
# #### #### ## ## #########  #   ###### #   ## #  # ## #  # ######### ##    c #  #              c    c         #  #  c   #
#         f ##          g               #   ## r  #  ###  #    ###    #          #             c  c            #       t #
#  ## ##### ##  ### #######  # # ###A # #    #    #l ###  # #  # #  ###         #      cc    c   cbg      l     #        #
## ## ##### ##  ### #######  # # ###rf  #    #    #  #    ###  # #  ###   c  f  #                       g       #        #
#  #c ##  #       #   ##  #    #  ##    #   g#    #  # #  ###  # #  # #       t  #          l                  #   c     #
#l                     t       g      # #   l#    #  #      #  # #  # #t         #                t            #     l   #
## #  ##  #       #   ##  #    #  ####  ##   ###  #### #  # #### #### ##r     c   #      c                    #          #
## ######## ##  ### #######  # # ###                                      c      #       A g   b    c  c       #  g      #
#                    g              ### ##  ###   #### #  ###    ## # ##       br#                cc b         # A       #
## #######   # #### ##### #  # # ###    f#    #    #      #   #   # #  #        #        l   l                  #        #
## ######    #  ### ##  # #  # #  ##     #    #    # #    #  #    # #  #        #                               #        #
#       r                           ### ##  ###    # #    #  #    # #  #         #      c                      #    t    #
## ######lg  #  ### ##  # #  # #  ##    #         ## ###  ###     ###  # a   l#  #                             #  #t     #
## ########  # #### ##### #  # # #### # ##   ##        #         ####        #    #            bb             #   r#     #
#      t            bl         b    # #  #   t#   ######  ##             ##   #  r## f#   #  #  # #   ##### # # #####   ##
#  # #### #  #  ###  #### #  # # ## # # l#    #    ###    #  #   ### ###  # # # #b#  ## # ###   # # #     # # #     # #  #
#     ##     #   ##   ##         #  # #  #    #    # # f  #  #    #       # # #   # #   #   #   # # # # # # # # # # #    #
#l    ##     #   ##   ##         #  #    #    #    # #    ####    # #  #      #         #         # #   #         #   #  #
#  # #### #  #  ###  #### #  # # ## ##   #  t #    # #g   ##      # #  # # #     # # #       # #         #         #  g# #
#       c t              r          #   ##  ###   ## ###  ####    ###t #   #       #         # #b       t#       # #     #
## ######## ## #### #######  # #  ### #           #       #  ##   ###  ## #   #     # # #     #   # # # #   # #   #   # ##
##  ####### ## #### #######  # #   ## # ##   ###  ###     #  #  ### ########  ##################### # ####################
#        l   b                      # #      #     #      #f #   ## ##   ###  ##r### ### ###f### ##    # ### ###g### ### #
##  ## ####### ## #    ###   # #   ##        #     #      #  #  ### #### f  t     g  #    b# #   #   g a # a #b    #     #
## # # #        # #     ##     # # ## #  #   ###  ## #                                              ###      b  #####    #
#  #   #          #      #   # # b    #  #    ##       #  ## ##    a      #      #                # ###         #####    #
#  #   # #  #     #   ##     # # ####    #    #   ###       ##     t t        #       #        ## #   #      g  #####    #
## # # # #  #   # # # ##t #  #   b##        ###   ##   #    ##        l                   t     # #  r######    #####    #
## # # # #  #   # # #  ###     # #   ## ##   ##t  ##   #  ####                                  ###   ######       b     #
## # # #  b     # # # #   t      #####  ##   ##   ##   #     #           #  #             #       #   #    ###   r    r###
## #   #   b      #   #      # # g##     #    #   ### #   ###                             t    lr # ###    ###         ###
## #   # #  #     #          # # # # #   #    ##  ###     ####                                              f            #
## # # # #b #   # #  b ####         #    #    ##  # l #   ##                #         #                  ##     #######  #
## #r# # # t#   # #     #    # #  ##     #  ####      ##   f##                    #                 #### ## ### ##    #  #
## # # # #  #   # #      ##  # #  ## #  #         ### ##  ###                                  ###  ##   ##     ##    #  #
## # #t  #  #   # #  ## ###    #   #    ##  ####  ###                         #             g       ##   l          ###  #
## # #   #  #   # #  ##  r#    # f #    t#   #    b       ####     t      #         #                #              #   r#
##   # # #  #   #      ###   #   ###  # #     #a     ##         t                      t             #   f  ##      #    #
##   # # #  #  b#   ##   ##  # #  ## #       b#                                                      ###### ##r     #### #
## # #   #  #t  # #    a ##  # #  #  #        #           ####      #         #                r       #    ##        ## #
## # #   #  #   # #  t###    #   ##t##      ###        a  ##                                  t      g ###       r    ## #
##   # # #  # # #r     ###   #   ##     ##  ###   #  #     #                                   ####    ###       ####### #
##   # # #  # # #      ###   #   ## #       ##       #     ###              #            t    r#       ###  l    ####    #
## # #   #  #   # #    ##      # ## #        # #   # #    ###a      a           f           a    ## ##           ####   ##
## # #   #  #   # # #  ##l   #   ###          ##   # ##      #             f          t     #  ###   ####f       ####   ##
## # #   #  #   # # #   #    # # ####       ####  ## ##    t #                                 ###   ####        ####   ##
## # #   #  #  g# # # f ###       ####   #  ##r   #  #    ####                             t     ## ##           ####   ##
##   # # #  # # #      a##   # # # ##        #    #       ###       a                 t  #     #       ###       ####    #
##  l# # #  #b# #     ###    #     #    #    ###       #  ##                                   ####    ###       ####### #
## # #   #  #   # #      ##        #    #b   ###   #####    ##                 A              f        ###            ## #
## # #   #  #   # # #######        #     #    ## # ##    #  ##        #                 g #            #    ##   rl   ## #
##   # # #  # # #    ###### ##     r# # ##    ## # f#    #  ##             # b                       ######f##      #### #
## r # # #  # # # g   ##    ##     ##        ##  #  #### #  ##                            a          #      ##      #    #
## # #   #  #   # #   ##    ## # ###    #      # #  #### #####                            #          #          f   #    #
## # #   #  #   # #    ###  #  a ###  b #   # ## #  ##                  r       #     f             ##              ### l#
## # # # #  # # # # #    l# #    #    # #   # #  #  ##                   g  #                  ###  ##   ##     ##    #  #
## # # # #  # # # #   #  ## #       ###  #  ##   #  ##b       #         g  r               A        #### ##l### ##    #  #
## #g# # #  # # # #   #  #  #    t ##       ###  #  ##                                                   ##     #######  #
## #   # #  # #   # #    #  #     ### #  #  ####   l##             #    #                A        f                      #
## #   #  r  t#   # #  ###  #      t##           #####   #####                               #    # ###    ###         ###
## # # #      # # # #   ###      #  ###     ####                #                  #              #   #    ###         ###
## # # # #  # # # # # #   # ## # ######  #   ### ###                          #                 ###   ######    f        #
## # # # #  # # # #  ## b # #     ##               l  ## #####                        #         # #   ######    #####    #
#  #   # #  # #   #       #       ##  #  #   ### ###      ##         #                  b#r    ## #A  #         #####    #
#  #   #      # t #  # #### ## # ###  #   ##  l# #   #    ##      #       b              g        #####         #####    #
## # # #    r # # # ##     ##   ##### #b#  ####  # # # #######                                     ####         #####    #
##########################################################################################################################
