metadata:
  gen_time: 13.057098865509033
  timestamp: '2025-04-18T22:56:51.377951'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#####  ###r   ########     ##########  b           #  ##b##  #   #  ##         ##                                        #
#####  ###     ########### ##########  ######    ###  #  ## ##  b#  ##   ##     ######### ### ####### ###c####### ########
# c##  ######  ###########  #      ##  ## #t     ##  ##  ## #  r##  ###  ##   ########### ### ####### ### ####### ########
#   #  ######      ######## #      ##       ## ####  ##  #  #   ##           ##  ######## ### ####### ### ####### ########
##  #  l  rg#       ####### #  #######      ##  #   ##  ##      ##      ##   ###      ###                     ###        #
##  ##         ##  c####  # #   ########### ##  ##  ##  ##   b  ##                ####### ### ### ### ####### ### ########
##  #### ###    #  #####    ##  ###########  #  #    #c      #   #          ##    ####### ### ###g###g####### ### ########
#     ## ####      ######## ## ##### r   #   ##    ####    ####       #   ####   l####### ### ### ### ####### ### ########
#  ##  # ####         ##### ## #####     #   ##       #       #       #  ###   f                            A            #
######     ##l   #  r ##### ## #####  ##     #  r       #b       ##   ## # ##    #### ### #  ########### #### ### ###    #
#######  # ##  # #  ####### ## ###    ###       ##      ### # t        #t        #### ### ##  ########## #### ### ###    #
########            ####### ##      f ####            g## ########## ###  l  ######## ### ### ########## #### ### ###    #
#########           ####### ## r    ##########   l      #  l ## #r ####b ######## ### ### ###       f ##      ### ###    #
####           ####  ###t # ## c##t #####  ##    #####  #                ####     ### ### ### ####### ########### ########
####         #  ####            ##  #####        ##     ##  ##    ##     #        ###c###b### ####### ########### ########
####  #####  #  g####     t    ### ag    ##   ## l##   ##   ##   ##      #l ###   ### ### ###b####### ########### ########
####   ####  ##  ####  #### r######      ###  ##             ##  ##           ##      ### ###     ###         ### ###    #
#  #t c####              l#  #########  ## #  ##    ##       r              l     ####### ### ####### ###l####### ###    #
#   l ######     #     #     #########         #            ##  #####  ##    #### ####### ### ####### ### ####### ###f c #
##  c ############   r##       ########      #######    #  ###  ##         ### ## #######             ### ####### ###    #
##  ########              #    ##########        r##   b## # #   ##  ## b      b  ###            l### ###     b   b      #
#   ####     #####  #######  ###############  ##l       ##     a #    ########### ### ### ######  ### ### ####### # ######
#   ####   ###   #l #######  #########   ## t  ####     a#   f       ####  #  ### ### ### ####### ### ###A####### # ######
# ######c ####  c       ###       #### l       A ## ###f   t##b      #   l       a### ### ####### ### ### #######   ######
# ###### r#####       rr ###   b  #####   ##     ## ###     ##  ###         ## b        b    f    ### ###     ###    f   #
#   ##    #####  #  ###  ###  #  ########          f#       ##  ###    ###       f### ### ### ########### ####### #### ###
### ##   ######  #####   ###  #######    ##                 #        ### ###      ### ### ### ########### ####### #### ###
### ###  #####   #####  ####           r      l          ######  #####         ## ### ### ### ########### ####### #### ###
### #### #####  ### r#  ####          ##          #####  ##                 f     ### ### ###   b   l  fc                #
# r #### #####  ###     ####  ##  ######             ## ###       #####    ##### ######## ### ### ### ####### ### ###    #
#    ### #####  ###     ####   #  ##########        ##  #  #    ####  ##  ###### ######## ### ### ### ####### ### ###    #
##    ## #####   ###  #######  #c ##############     #  #r    ###                ######## ### ### ### ####### ### ###    #
####  ## #####   ###  ##########       ##            ##      ##               ###             ### ### ###         ###    #
####  #  ##########   ##########  t    ##  ####      ##       #     #      #  ## ######## ### ### ### ########### #### ###
#  #  #   #########  ############  #  ###  ##     r     ####       #####f  # ### ######## ### ### ### ########### #### ###
#     #   ######     ############  ######  ## ###  ##   ##           ###   # # # ######## ### ### ### ########### #### ###
##    ##  ######     ####  ### c#r ###### ### ### ##    r##   #              #   t        ###r###     ###  l             #
##    ## ########  ######   ##  #   ##### #   #  b###    l   t#     #####       lba  A    ### ###  f  ###   f            #
####  ## ######### #######  ##  ##  ####### ###              ##    t##### ##        b  ct ### ###  l  ###        b       #
####  #  #####     c        ##     c######  ### ##   b # #    ##  ###   # ##   b#    b   t### ###     ###      f         #
##    t     l  ####    ####             #   ##f  ####  ###     #     ##          ##   g##     ###         r #####       ##
#  ##          #          #          ## c ####  ##### ##      ##   g t#          ##    ##    ####f   b      ##### g   r ##
####       t   # ######## #      t    ####    ###lb  ##       #        #         #     ##    ####  #######  #####       ##
#       c    c## # #### # ##           # # #####     ##  t        #### ##        ##  ####  b ####  #######rg#####       ##
# ##       #####     r    #####       ##   ##        ## r  r       ### ##        ##  ####  ######  #######r #####   ######
#  # ##     ##g##    f   ## ##     ## #   ##         ##               ##       # ## l####  ###### f#######  #####   ######
#g ###     ##      t         ##     ###   ##       #  ##    b    #    ## l  #  ##      b       r  r                      #
#  ##          t ######## fc         ##   ##       ##  #         ##   ## f  ##  #        f                               #
##  g  t     ##  ##    ##  ##           ##  ####    #         #  b##  #     f##                  fl            r###     r#
## ##        ##  #      #  ##      t ## ##  #####             ##   ##        ##   #######################       ### f#####
#l #         #              #         #      ###              ##    #       ##a   #######################       ###  #####
#####        ###  ##  ##  ###        ####f    #       #g      ##b         r #     #######################  ###b      #####
###    #          ##  ##   t      #   g##             ##       ##      #          ################         ###    f  #####
#   ####          #    # c     c  ####                #        ##      ##         ################       r ###f      f   #
##  ## ##A    ##  ##  ##  ##     ## ##  #            ## ######## l      #    l#   ################         ###           #
##     #       #  ###### c#       #     ###     g##  ## ##          l   ##    ##  ################         ###   ##      #
#   ##     ##  #  # ## #  #  ## t   ##    ##      ###  ##  r          l  #     ## ################   #########   ## g    #
#    ###    #  ## f      ##  #l   ###      # ###   ##  ##            g b ##     #b################ g #########    #    l #
#         t##   #       l#   ##          ##b ####   #  #  #######         ##   r  ################  l#########   ##     ##
#  c ## ##  ##    # ## #    ##  ## ##     ##  ###   #  #####    ##    ##   ##    l################   ######### l ##     ##
#    ## ##  ## g t# ## #   r## b## ##      ###   ####b ####     ##     ##         ################   #########  t#########
#        f ##   #        #   ##        f    ##   ###    ##  g#   #      ##        ################        ####   #########
#    ###    #f ##        ##b #    ###        #    #  r       ##     t#  ## f      ################  r     ####   #########
#   ##     ##  #  # ## #  #  ##     ## t                      ##     ##  #  ##    ################  ##########   #########
##     #       #  ######  #       #     #  #            #     ##     ##      ##   ################ f##########   #########
##  ## ##     ##  ##  ## g##     ## ##  #  ##      ##   ##     #    ##        ##               r    ##########   #########
#t  ####          #    #          ####     ##      g##   ##    #   r##         #                    ##########           #
###    #          ##  ##          #l   ##   #        ##  ##   ##    ##                            l ##########           #
#####        ###  ##  ##  ###        ####       #    r   #    ##     ##   #                         ##########  f      r #
#  #    t  l #              #        c#        t####    ##    ##         ##        f  ### f   ####  ##########     A     #
## ##        ##  #      #  ##        ##g#        ####  ##      #         #            ###     ####  ######################
##           ##  ##    ##  ##  t        #         ##   #        b                     ###   ###### r######################
#  ##A    f      ########            ##       f       ##                     #   ##         ######  ######################
#  ###     ##        r       ##     ###  t ##  b     ## t     r          #   ##  ##  l   r    b     ######################
#  # ##    g## ##        ## ##     ## #   ##  t      #   #         #     ##   ## ##  ##         ff  ######################
# ##    r  #####          #####       ## ### ##     ##   ####  #   ##    ##  l   ##  ##    ###############################
# #           ## # #### # ##           #    ##      #l    ##t g##  ##    #   t             ###############################
####  l        # ######## #    l   c  ###g  # l                ##   ##        #    c                                     #
#  ##      r   #          #          ##  #     b  l    #      ##     #       ##      g                                   #
## ##          ####    ####        l ## ##             ###   ##      #       #   lg g             b  #####   ##       ## #
## gl      g       ##                   #   ####################         ######### ##  t        ###    ###           ##  #
##         tc      ##                   #    ###################    ##   ######### #            ##  ##g ##            ####
##                b##                   #     #################    ####   ########           #  #   ##   #  #       g   ##
###### ## ### ############## ## ## ## ### g                 c      ####              g  ## # #g ##      ##  # # ##     t #
###### ## ### ############## ## ## ## ###             g             ##af          b      ##### ## b ##   ## #####      A #
#        g      ##  ##            g        #####      ###  lr            ####fl          ##    ##        ##    ##t       #
#               ##l ##          t         #######    #####              ######     ## #  #  ##              ##  #  # ##  #
#     r       r                           #######    ######    #####    ######        #     #   ## #  # ##   #     #  f  #
#               ##t ##                     #####     #######  #######    ####    ##  ##    ## ###  ####  ###r##    ##  ###
#     b      t  ##l ##                                ######a ########          ###  r     #  ##    ##    ##fg#        ###
### ## ###### ############# ### ## ### ##              ####    #######   b     ##   ##    ##f##    ####    ## ##    ##   #
### ## ###### ############# ### ## ### ###               f      #####       f  ##   g  # ##   #     ##     #   ## #      #
#                      ##                #       l              r               #      ###      #  ####  #      ###      #
#     b b      f   ##  ##                t   ##### g   t  ag              ###   b    #      ##  #     #  # b##      #   t#
####### ## ################# #### ## ###    #######    ####      ####    #####     #####  ### r   ##  ##     ###  #####  #
####### ## ################# #### ##c###f   ####### t ######    ######   ######  ####     ##     b ####    g t##     #####
#  ##  r    t##         ##   t               #####   ########   #######  ######  ## ##          ## #  # ##          ## ###
#  ##        ##  ##    t##               #      t    #########  #######   ####   #        ##                  ##   r    ##
#           A##t ##     ##  t            ##      f   #########f  #####                ## ### ##            ## ###f #     #
#  ##       f##  ##     ##            f  ##    ### a c#######               l   ##  t #  # #l##            ## # #l #    ##
#  ##        ##  #############g## #########    ###    #######    b  b       b l ####  ##b    #              #     ##  ####
#  ##            ############# ## #########          #########   #####            #              g    t  g               #
#  ##        ##  ##  ##   ##         ##  #           #########  #######   ####   ## ###      ####        ####      ### ###
## ##     f  ##  ##  ##   ##  b      ##      #####   ########   #######  ######  ## ##   # ###  #  ####  #  ### #   ## ###
## ##        ##                l f          #######   ######    ###### a ######   #     ##  #       ##    r  #  ##f   t# #
#l ##        ##  ##  ## la##      l  ##  r  #######    ####b     ####    #####   b  #  ###      ### ## ###      ###  #   #
#  ##      c ##b ##  ##   ##         ##    b #####                        ###       # l# ##   ####      ####   ## # b#   #
###################  ##   ##      g      #          gt        b               t # f ##   #    ##          ##    #   ##   #
###################       ##   g   l ##t #   l                f #####          ##       b#   ##   ##  ##   ##   #        #
##  ## c    ##   ##  ##            f ##                ####    #######         ## #      ##  #              #  ##   b  # #
##  ##     c##   ##  ##   ##     f                   b######  ########  a     t #### #            ######            # ## #
#                   l##   ##         ##    #####     ####### b#######   g####      ###  #g   ##     ##     ##    #  ###  #
##  ##      ##   ##  ##f  ##         ##   #######fg  ######    #####    ######   #  ##    b  ##            ##f   #  ##  ##
##  ##      ##   ##  ##   ##         ##  t#######   f#####            b ######   ####  ##  br    t               ##  #####
##  ##      ## ######## ######g##########  #####b     ###                ####  t        ## #                  # ##       #
##  ##      ## ######## ###### ##########               lr      t   ##    g      g  ### #### t       f        #### ###   #
##  ## A    ## f   ##    ##             b                    t     ####           #  ##   ## # # ## ## ## # # ##   ##  # #
## ###      ##     ##    ##                   #################    ####   ####### ####  ###g #####  ##  ### #  ###  ######
## ###      ## c   ##    ##             l    ###################    ##g  ########  #     #      ##  ### ##      #        #
#f  #### ##################g                ####################    r    ######### ####b     ##  ##   ###  ## f    #### ##
##########################################################################################################################
