metadata:
  gen_time: 9.225592851638794
  timestamp: '2025-04-18T22:53:27.402658'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#     f              g     #                                                          #########     r   l           ###  #
#                          # g             g                                         ##########                ###  ###  #
# l                     ####                                           f                 ####################  ###  ###  #
#####         t#####t   #                  ### ## ## ## ######## ##l## ## ###        ####g###################  ###  ###  #
##  #          #   #    #                  ### ##t## ## ########b## ## ## ####t#### #### ####r###############       ###  #
#   #          #   # f g#                     a   g a                                     ####l##############            #
## g#          #   #    #              f            g                l  g g                  ##                         r#
##  #b         #   #    #          #####   ########## ## ##### ### ### ####        #####  #   #                t   #######
##  #  t    t  ## ##    #####      #   #   ########## ## ##### ### ### ####            ##     # ###       ####     #######
##  ####                 f  #      #  r#   #      ##  ##  ####  ##  ##  ##          ## #### # # ###  ff   ####  g  #######
#      #                    #      ## ##   #  ##  ##  ##  ####  ##  ##  ##    #     ##   ##   l ###       ####   g #######
##     #                t   #             b#  ############################      ##  ###a ###    ###       ####     #######
##     ## ##                #              #  ############################   ## ###    # ##### f###    r  ####     #######
##         #              r ####      ## ###  ##           ##  ##t      ##      ##t###   ####f# ###       ####     #######
## ##      #                   #     A#   ##  ##       ## f##  ##       ##  #     ###### #####t ###       ####     #######
#f  #      #######             #      #   #   ##     b ##     f##       ##  A##  #b####t####### ###   ##  ####     #######
#  f#            #             #      ######           ##  ##  ##           ####  #############       ##  ####     #######
#####                          #           #  ##       ##  ##  ##       ## a#####  ############            r             #
##               #      t  b####           #  ##       ##  ##  ##       ##  ######  ###############                 b    #
##      ######   #########  #              #           ##  ##  ##           ##     ################   ####################
##      #   r#           #  #                 ##       ##g a   ##  ff   ##     # g#################   ####################
##    c #f                  #           l  #  ##       ##  ##  ##      b##   #   #l###  ###########   ####################
#########    #           #  #       ## ##  #  ##     g ##  ##f ##       ##     ## #    # ##### ####   ####################
#            ########    ####      l#   #  #  ## ### #####################    ###        ###   ####   ####################
#   g               #     g         #   #t #  ## ### #####################   ###     ##        ####   ####################
#                                   ##g##  #  ##  ##  ##  ####f ##  ##  ##   # #             r##### r ####################
#          t #####  #      g               #f ##  ##  ##f ####  ##  ## g##        #  #     ###f        b                 #
#            #   #  ##########             ############## ##### ## ### #####         #        #          r               #
#     rg         #           #             ############## ##### ## ### #####   #           # ##  #########          b  g #
#            #   #                                 r                                         ##  #########      g   ######
#   f  b   t #####         b #     t                      bg        f        A           ######  #########     ###  ######
#                            #####    f    ### ## ## ## ########l## ## ## ##############  ####l     f         f###  ######
#                                #         ### ## ## ## ######## ## ## ## ####g#### #### ###  #                ###  ######
# ###         #######      l  A                 g     r                                                             ######
#   #         #l    #            #                                         f ######## ##b######                          #
#   # g   r   #g    #            ###### f                             t              ##########                      r   #
#  r## #    ## ##  ##     # ## ### ##  ### #    t    #   ## #          #  ## ######   ######### # ##  ## ###    # ##     #
# #  # # #     #   ##          #       #   # ##     ####  # ### ### # ##  ## #   #####      ### # ##l # ########  ########
# ##     #a   b##     ##      ##b##   ##g### #        ## #### # # #####    r # # ###b# ####  # #  ####  #    #### #  ### #
#  ## ##   ## ##   ####       #  #    ## #   ######    ###      # #  ###   ### #   # # #l      ##g##### #    ##  ##  ##  #
#   # ##    #  #     #   ###  f  ##   #  ## ## ## #   ###   ##    ##   #  ##                                     ##  ##  #
### ###  ####            ##   ##      ##  #g#         #           ####    ## # # # # #f# # # #   # #r#############  ###  #
# ###     ##  ##     ###  ##   # r ##     ###           ## #   ##   #                                           #   #### #
#      ####   ##       #  ##     ###     r## b gf     ###  #     c   b ##  r    #     # # # # ######     ## ####   #     #
# ### c ##       ###     ##   #  ##       #         ####     #   ##        ### # # # # # # # # ############ t      # ### #
#  #     a      b##    ###    ##         ## ##      ## # ##  ###r ###A## ### # # # # # # # # #  ##   ##  f# #####        #
#  ##    ####    #    ## #    ##r  ##    ## #      ##    ##  grc    #  #  #t #   # b # # #   # g#    ## l#  ##    ## ### #
#  ### # #c #    #             ## ###    #  #    ###      # #    ##### ## #  # ### ###     ###    ####  #   # #      #   #
#  cb  #            b ###  r   #  # ## #    ##   #       ## ###   ##    #    #l           #####   ##    #  #  #      #   #
###    ##   ##   ###  ##             ###   r     ## #  ####   ##   #### ## ##### ######  ##               ### # #  l # # #
# ## #c #        # #  #        ###     ## ##   f  ###   #   # ##  g bb### r##### t#  r                  #     # # ## # # #
# ## #         bt           # ##        #     ######   ## # ###  ## ####   #   # ## ####    ###    #      #     #  # #   #
#   g        #   ##  ##     ###       ###     ## #  c   ###  ##  ## ## ##    # #      ## #         #      #     # #  # # #
#      ### # # #  ## ##                #  ##  #        ###          #  ##r ### # #   ##     ##  # #    f  #     # #  # # #
#      #r# ### # ###    #  ##  ##         ## ##f     r #    ##   #####      ## # ### ##                   #     # #  # # #
#          ##  ### #   b## #   # t r###    fr#      ##   ##  #  g##  #  ##  #  # #######            #     #r    #    #   #
#          #   ##    ##    t  ##  ###        ##      #   #          ##  ##c f###     ###              ####    # # ## # # #
#          ##  ### #    ## #   #   b###  c   #     g##   ##  #   ##c #  ##  ##### ####f                   #  A  #    #   #
#      # # ###g# ###    #  ##  ##         ## ##        #    ##  r### #    br#     #### #            ##g c #       #b # # #
#      ### # #    ## ##         g      # b##t #  g f   ###         g   ##  #### ####   # #   #######r#    #       #  # # #
#            #b  ##  ##     ###       ###     ##g#      ###  ##  ##  # ##    ##                      #    #g      #  # # #
# ## #         r           t# ##    c   #     ###### r ## # ###  ##  ###   # ## # ### ## #### ## # #  f   #        # #   #
# ## #  #        # #  #        ### c   ## ##  g   ###   #   # ##      ###  ###  #     ## ##      # # #####    # # ## # # #
###    ##   ##   ###  ##             ###    b    ## #tb####   ##bb # ## ## #### ### #### ##        #    ####  # #    # # #
#      #              ###      #  # ## #    ##b         c## ###   ##         ## b   # ######  # # ##    ####  #      #   #
#  ### # # t#    #             ## ###    #  #    ###      # #    ##### ####  #####     g ###    #    #####    #      # l #
#tc##    ####    #  g ## #    ##r  ##    ## #   r  ##    ##c   b    #  #  #      #  ###  #   ## #    ##  # l      ## # # #
#g    c          ##b   ###c   ##         ## ##      ## ####  ###  ### ## ### ###### #   ## # ## #    ##l   #  ### #g     #
# ###   ## r     ###     ##g g#  ## f     #         ####     #   ##        ##              #  ### ###### # f       # # # #
#      ####   ##       #  ##     ###      ##          ###r #    r       #r  ## ## ### l##### #### ##   g #    ##  ##     #
# # #     ##  ## b   ###  ##   #   ##     ###           ##g#   ##   #   g    # ##   #  #####             # #  rr#    # # #
### ###  ####            ##   ##g     ##    #   l     #   b       ###  f  ## #  # # ####  ## #     # ### # #  ### r# #   #
#  b# ##    #  #     #   ###     ##   #  ## ## ## #   ###   ##  c ##  t#  ## ###### # ##  ## # ### ##  #      #   #  #   #
#  ## ##   ## ##  c#### c     #  #    ## #   ######   r###      # #  ### g ##  l  # #    g##   ## ### #       #   #  #   #
# ###    #  r  ##     ##     g## ##   ## ### #     g  ## #### # #r#####       ## #### # #### ###  ###         ###    #   #
# # ## #b# t   #   ##          #       #   #b##     ####  # ### ### #f## c## ##  f  # #   l  ## # ##l    # #  ##  ## #   #
#   ## #    ## ##  ##     # ## ### ##  ### #         #   ## #    f     #  ## ## ## f#    # # ## # ##  ## # #    # ##     #
# ########  ########  ######## ###     #####  ####     ##            ##                  a          t      ##            #
# ######## g########  ######## ####    #####l   #   f ###            ##              r           A         ##            #
# ########     c  a  c########g###       #          ##### #### #### #### ## ## ## #### #### #### ## ## ## #### #### #### #
# a            a   t  a    f g #             ##  f#######r#### #### #### ## ## ## #### #### #### ## ## ## #### #### #### #
#                  g      l           ##g    ##   #######  ##   a                  ##        ##        b     r       ##  #
###     a  ##########  ac    ##  ## ####           ###  #g ##    l    l  l    t    ##  t  t  ##            t         ##  #
### a      ##########        ##  ## #####  g g   f ##       g                     l##r       ##            c   r    g    #
###  a     ##########     c  ##      #####    ##  ###      ##                                                        ##  #
###       aaf           a g  ##      #####   ###   ###     ##   f                  ##        ##                      ##  #
#         ac                     ##    ####   ###l ####   #### ## ############################################## ## ####t#
#    ######################a c   ##  r  ####  ##   r###   #### ## ############################################## ## #### #
###  ######################  ##          ##         ####  ##          ##  ##        ##      ##      r ##  ##          ## #
###  ###################### c##     ##        ##     ##                                      b                   A       #
###  ######################  ##     ## l     ### g   ## g ##      t   ##  ## l      ##      ##        ##  ##       r  ## #
###f ######################ca##               ###        ##### ################ ################## ################ ######
#a   ######################         ##        ####   ##  #####l################ ################## ################ ######
#       g    cc          c        l ##         ## t  ##  ##      ##   r              ##    ##         f        ##      ###
#               c        a       f      ##                                                                               #
###############  ############## l   t   ##     ##        ##      ##       l          ##    ##     g            ## tt   ###
###############  ##############        ####    ##    ##  ##### ####### #### ########################## #### ####### ######
###############  ##############      ######          ##  ##### ####### #### ##########################f#### ####### ######
#      a   g  bf   a    a     a      #######                            ##     ##                ##     ##   a           #
#    g        ba   l       t cc       #####       r                     ##                              ##               #
###########    ##    ##########         #                               ##     ## f  l           ##     ##               #
###########    ##   t##########                      ##    r           l       ##                ##                      #
###########    ##  a ##########    ##               #####               ##     ### #### ##r#### ###     ##      r        #
###########    ##    ###########   ##                ############# ########## #### #### ## #### #### ##########c##########
###########  A ##    ##########      g       ##        # ######### ########## ### f ##      ##   ### ########## ##########
###########    ##    ###########            ###       b     ##       ##  ##    ##   ##      ##   ##    ##  ##      t##   #
###########   c## c  ############            ###         ##############        g             ###   #      t              #
#    f  b                      ###   t       ##                 c                                  #                     #
#a          ag   c       a  r  ##         f              ##############                      ###   #   t                 #
#####      l  ####     a   #####   ##            f                t      A                       r #                     #
#####  #####  ####  #####c ####b   ##      l             ##############                      ###   #   t l               #
##### g#####        #####  ####   ####  ##                                 r  c      t  f          #               t     #
#####  #####t    t a#####  ####    ########     ##       ##############                      ###   #    c                #
#####  f             a faf ####    ########    ####      ##############                      ###   #                     #
#####   af              a b####     #  ##       ###               t                                #                  l  #
#  l   b                                  g     ####     ##############             g    f   ###   #                   f #
#     c  c############      l        l   f#    l ##           r                                    #                     #
#a a    c ############ a                ####     ##       #############            l         ###   #                     #
#     aa  ############             ##   ####    ####    #        r         r         f             #                     #
#   t          c             a # #####f   #      ##    ################r                     ###  b#                     #
##########################################################################################################################
