metadata:
  gen_time: 9.249836921691895
  timestamp: '2025-04-18T22:54:12.990244'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#### ## #######    c##########l# ### ##        #     ## ### ####### ##  ##### ###    ### ##   #     ##   #        ##     #
#    ##                        # # g b    ###  # # l g    # #                    b##        # ###                  r     #
# ##                                   #### #### ####         ## #####  ################### #   #                        #
# #  r           ## # #r######### #  ####          ####  # ## #l ###########  ######l###### # # ###                      #
# # ####### ###l# # #  c##        #   # ## ##l ## ##t#   #  #    r                            ##  #                      #
# # #       # # # # # #### #l# ##   ###    ##  ## l  ###   ## #  ###########  ############# # #   ###                  t #
#   # # # # # #     # ###### #g##   # ### ##    ##  ## #  g## ###############################   ##  #        rc   t      #
##### # # # # # ###t#r                 # r#      #  #       #                              g#   # # ###                  #
#     # # #   # # # # # # #### # ##    #         A ##    ## ############ #### #### #### ###   l   #   #                  #
####### # # ### #      c# ##g  # ##   tl#    l     #     ## #########  # #  # # t# #  #r#  ##     #   ###t###       #    #
#    ####  l      ###     ######c   ##  # ###  ### # g##    #              rg              #            #        A  #    #
# ##                              g  ##   #      #   ##    l ########  # #  # #  # #c # #   ###   #     ###      l     bb#
# #               ##      #a# #     t     ########           ########### #### #### #### ### #r   b#               g      #
# # #### ################ ### # # ###      #    #      ### #c f                   r        ##           # #             c#
# #t                          # #   ##    ## ## ##  b ##   #  #############################             # #              #
# # #### # ########## #########         #### ## ####    l    #### g##  ###################                               #
# #      #   ######## # #######  ##  ##  #        #  ##  ##g            #   f              r                             #
#r                                  ## r ##      ##   ##     # ##  ##  ## ## ##                                t         #
#   ## ##### ############# #######  #        ## l      #  #### ########## #   ##   ##   # #      b                #      #
###### ##    ##t                 #        b  ##      l    # ## ########## #   ##tbb##   # #    b      t   l       #      #
#                                ##        r             ## ##            ## ####                              #     #   #
#### # ######## #                   ##      ####      ##    ## ## ## ## #      r  l     r #                    #     #   #
#    # ## fb    ##### # # # ## ##    #  l ###  ### g  #    ### ## #  l# ##################### ### #### ###  ## ###       #
###### ## ##### ##### # #    # #    ## ## ##    ## ## ##    #  ## #   # ####################   #  #     #        #       #
#      ##       ##    # # ####c##   ## ##          ## ##l  ### ## ##t##  #      l  f         ## ###  ### ### ### ###     #
####g  ##r# ###### #### # # ##c   # #   #          #   # # #   ## ## ## ##b## #### #### ###     #          #    #  #     #
#    # #### #  b          # ##### #       ##    ##       # ### ## ## ## ## #   ##   ##   ##     # c        ###b### ###   #
####                               t ###  ##t   ##r ###               # ## #  t##  r##r  ##     ### ###   g  t       #   #
#    # # #### ##       #    ######   ##      ##      ##   ###  b# #   # ## ## #### #### ###   b   #   #              ### #
######## ####### #### ## #######  g ##  g ##l## ##    ##    ## ## ## ## ##                      g ### ### ###  b       # #
###########  r         r     ###   t##    ## ## ##    ##    ## ## ## ## ##    l                   ### ### ###          # #
#    g##### ######################   ##      ##      ##  A###  l# #   # ## ## #### ####c###       #   #              ### #
####                                 ###  ##    ##  ###     b   # #   # ## #   ##   ## b ##     ### ###              #   #
######## ######c#####c# ## g   ## #    g  ##    ##       # ### ## ## ## ## #   ## A ##   ##     #          ### ### ###   #
# ##     c    #       #### ###  # # #   #          #   # # #   ## ## ## ## ## #### #### ###     #f         #    #  #     #
# ###########        ##### #   ##   ## ##          ## ##   ### ##l## ##  # g      l         ### ###  ### ### ###  ##     #
# #############            # # #    ## ## ##    ## ## ##    #  ## #   # ####################   #  #     #     #  #       #
# ##            #### #### ## # ##    #    ###  ###    #    ### ## #   # ##################### ### #### ### ### ###       #
#  #r# ##### #  #          #b# #    ##      ####      ##    ##l## ##b## #                 #                    #     #   #
##   # #        # ##    # ## # # ##                   l  ## ##     r    # ## #### #### ## #                    #     #   #
#      # # ##             ## #c# #      t    ##           # ## ########## #   ##   ## c # #                       #      #
###                       ## # ###  #        ##    r r #  #### ########## #   ##   ##   # #              r        #      #
#                         ##        ##   ##      ##   ##     #     ##  ## ##  ### #### ## # g                      r g   #
############# # # # # # # ## #   ## l##  #        #  ##  ##      bt    r#   g   t                               f l      #
############### # #l# # # ## ##      r  #### ## #### l  a    ###   ##  ####################                 b            #
#      ## ##    # #   #c# ## ## #   ##    ## ## ##    ##   # ######## ##################### g           # #              #
##                      t    #g # ###  c   #    #      ### #     g     l                   ##   r       # #           t  #
#                       #### #    r     f ########           ######## ## #### #### #### ### #     #                      #
#### ## # ## ##########      #       ##   #      #l  ##      ########  # #  # #  # #b # #r  ###   #  f  ###              #
#    ## # ## # #        ###### #    ##  # ###  ### #  ##    #l                             #t           #   l       # g  #
####### # ##   # ##     # #### # ##     #   r      #     ## #########  # #  # #  # #  # #  ##     #   ### ###       #    #
#b   ## # ## ###          ##   # ##    ##          ##    ## ############ ####r#### #### ###    t  #   #       r          #
#### ## #f##   # ####  ##### # #       #  #      #  # b                 l                   # g # # ###     bAb          #
#       # ## # # ####        # ##   # ### ##    ## ### #   ## ###############################   ##  #                    #
#######a# ####t# ##   # #### # ##   ###   b##  ##    # #   ##A#l ###########  ############# # # #l###   f      t         #
## # ## # #    # ##r# # # ## # #  #   # ## ##  ## ## #   #  #                        a        #   #            gr   t    #
## # ##   # #######   # # ##c# ## #  ####          ####  # ## #  ###########  ###### ###### # # ###                      #
## # #### # #######b#   # ##  l        #### # ##t####        r########  ################### ##  #                 b   A  #
#  # ##      #      #  ## ## #####     l  ###  ###      g ###       #             ##        # ###                t       #
# ## ######   ##### ##         # ### ##     #  #     ## ### # ##### ##t ##### ###b## ### ##   #     ##   #        ##     #
# # A    ##             f##         #   # #  ## #    f         ##  ##        r     ##      ###  ##            ##     #####
#                          b   g####    # #     # g         #  ##a ##  a          c##      ###t ##                   #####
# #      ##      t ##    ##       t       #     # #            ##  ######  ##########  #######  ###########          #####
# ## ################ #########   #  #  g       # #            ##  ######  ##########  ####     ###########  #############
# ## ###############  #########   #  #      g    #             ##g  g  ##                    r  ###########  #############
#    #   ##  ##  ##   ##     #                      #   #      ##     b##                  ########  t               lt  #
#                    r         #########            #   #  #   ######  ##  ######  ######  ########            t         #
#    #   ##  ##  ##   ##   b ##         f g       f #   #   #  ######  ##  ######  ######  #                    ##########
# ## ########################## #   #    #  #        #  #      ##        f ##      ##  ##  #  r               f ##########
# ## ########################## #   #    #  #           #      ##          ##      ##  ##  #   r     #####################
#  #  ff ## f##     ##f ##     #    #                   #      ############## a##  ##  ## l#    c    #####################
#               b          f          c ######          #      ############## g## t##  ##  #   ##    ##############      #
#  #     ##  ##     ##  ##  ##    #          b#          #         ##  ##b     ## c##  ##  #a  ##    ##############  r   #
# ##   ################ #######    # ##        #       g #         ##  ##      ## l##  ##  #   ##    ##############      #
# ##   ################ #######     #  #        #     #  #     ##  ##  ##########f ##  #####f  ##    ##############   ## #
# ##   ##  ##   ##  ##   ##             #        ###  #  #b    ##  ## l##########r ##  ####    ##                   r ## #
#             l                   #              f    #   #    ##      ##  ##                  ##                     ## #
# ##   ##  ##   ##  ##   ##       #g  #############        #   ##      ##  ##        f   a ###### lt       ###        ## #
# ## #### ### #################  #    t            ######   #####  ##  ##  ##  ##  ##############       c  ###   ####### #
# ## #### ### ################# #   ####                 #   ####  ##  ##  ##  ##  ########           ###  ###  r####### #
# ##  ##  ##  ##   t ##   ##   #   #       ### #          ###      ##  ##  ##  ##             f       ###  ###   #########
#  c a   bc     l       b         #   #   #   t     ####           ##  ##  ##l ##     a      A        ###  ###   #########
# ##  ##  ##  ##     ##   ## t  t#    #                 #    ######## r##  ##  ##  ##########    ##   ###        r     ###
############################### #                    #   #   ########  ##  ##a ##  ##########    ##   ###              ###
############################### #  ############      t#   #                ##  ##  ##     r      ##   ###    ###  ###  ###
###  ##  ##    ##  ## l  ## r # #      f              t   #           fb   ##  ##  ##f  f        ##   ###    ###  ###  ###
#                               # ###   #    #  #       l  #   ##  ######  ######  ##  ## l r######   ###           t  ###
### b##  ##    ##  ##    ##   # #  b    #    #  #          #   ##  ######  ######  ##  ##   t######   ###              ###
###############################    #    #    #             #   ##  ##      l           ##    ######         #####      ###
###############################    #    f#   #     tfg   g#    ##  ##     f         f  ##    ######        b#####   ######
# ##r  ##  ## t##   g ##  ##  #    #      #  g#            #   ##  ## l                ##r                          ######
#                                g  #      #   #            #f ##  ##  c   g  gc       ##l                        t ######
# ##   ## l##  ##     ##  ##  #  #   ####  #  #     #          ##  ######a ######a ##  ##  ####            ###############
###############################   #      # #    g#   #         ##  ######  ######  ##  ##  ####   r      g ###############
###############################       #    #     #    #    f     f r      l##  ##  ## a    ####  ######  #####           #
#                       c      #      #    #    #      #  tt           t   ##  ## t##            ###### r#####           #
#           A           b       #           #   #      # #   ########  ##  ##  ##  ########      ### l t #####  r        #
#   f      g              b     #        #             # #   ########  ##  ##  ##  ########    #####      a              #
#l                b        r    # #       #             #          ##  ##  ##  ##              #####             c       #
#                         t     # #       #                        ## f##  ## f##l           #######          ########   #
#   b            b               #     g   #         r       ####  ##  ##  ##  ##  ########  #######          ########   #
#                                   #      #             t   ####  ##  ## a##  ##  ########  ####### r t      ########   #
# t   b     f  c               #    #      #                   ##      ##  ##           g    #####       ###  ########   #
#                 r  t   r      ## #       # #    #    t      f##r     ##  ##       r    g   #####       ### r########  ##
#t         c        b             #   #   t#  #### #      t    ##  ##  ##########  ##  ####  #####   #######  ########  ##
#           f      f                  #    #        ######     ##  ##  ##########  ##  ####  #####   #######  ############
#                     t               r#   #        t     #        ##  ##      ##  ##  ##    #####   #######  ############
# t                               ##   #  t#  g      #     ##      ##  ##      ##  ##  ##    #####   #######    t    #####
### ###########################     #   #       #    #f        ##############  ##  ##  ##    #####                   #####
### ###########################      #   #######f     #        ##############  ##  ##  ##    #####  t             ########
##  ##  ##   ##  ##   ##   ## b       #t              #      l ## f  g     ##l     ##  ##a   #####                ########
#                                 g       #   #    #           ##          ##      ##l ##    #####     ########   ########
##  ##  ##   ##  ##   ##                  #   #     #########  ######  ##  ######  ######    #####     ########       r  #
### ######################   ##           #  #               f ######  ##  ######  ######    #####r   b########       l  #
### ######################  ##                #  #      b#    a##      ##            a      l#####     ########          #
###  ##  t##  ##  ##  ##       #   l           # #  # g   #    ##      ##        g           #####     ########      ##  #
#        b                      # f    ##      # #  # #  f #   ##c ######a ##########  ####  #####     ########      ##  #
###  ##   ##  ##  ##  ##r ##    f#  #    #     # r# #  #    #  ##  ######  ##########  ####  #####     ########  ######  #
###############################  #  # ###     #   # # g ##b #  ## t##  c           ##g               ##########  ######t #
###############################  #  #        f#  #  #          ##  ##              ##                ##########          #
##########################################################################################################################
