metadata:
  gen_time: 8.694464921951294
  timestamp: '2025-04-18T22:52:36.059621'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#            ###          ###      rr  f  ##      #####           #        ### ## # #  #       #  # #  #t#  # #  # #  # ##
#            ###          ###   r        ##g     ##          ##  g#            #  # #  ## ### #   # #  # #  # #  # # b# ##
#  ########  ###          ###  ########  #    c  #    ##     ##   ### g    r g   ## # ### # ### ### # ## ## # # ##   ## ##
#  ########  ###     f    ### t########      g   #    g#     #     ##  l t                             c                 #
#  ######## l###       g  ###  ########       ####     #     #      #########                                            #
#  ###    g                       f ###      ## ###    ## ####      ##      ## #                              b          #
#  ###                              ###      #  ### ##### ##### #####      l##   #### ### ### # # ### ### # # # # # # ####
################          ###############    #    ####     ##  A ##t       ##    #  # # # # ### ### # # ### # # ### ### ##
################          ###############    #     ###     #      ##       ####  # b      b                   t          #
################       l  ###############   ##  t###       # g    ### ###### ##                     f                    #
#        l                g    A            #    ###       ##          ####      #                                       #
#               g  g     g   b        r   ###      ## ##   r##         #  ## ##  ## # # ### ### ### ### ### ### ### ### ##
#  ###  ##########################  ###  ###           ##   t#     #####      ####### ### ### ### ### ### ### ### ### ####
#  ###  ##########################  ###    ##          ###   ##    #####      ###                                        #
#  ###gr##########################  ###     ###        ###   ### ###   #### ###                                          #
#  ###       ###          ###       ###   ####### ###   ##   ###b##    b##   ##  # ### ### ### ### ### ### ### ### ### ###
#  ###       ###          ###     t ###  ##  ###   ##   ##    ## ##          ### ### ###g### ### ### ### ### ### ### ### #
######  ###  ###          ###  ###  ######    ##    ##  ##    #   ##    ##  ##               b                   b       #
######  ###  ###          ###  ###  ######  f #     ##   ## ###    #######  ##   t       g   f             g            f#
######  ###  ###  g       ###  ###r #####     ##    ##       ### ######     ###      f      t     b                    r #
#       ###  ### r        ###  ###          ####     ##    lt#    ###       ####g### ### ###g### ### ### ### ### ### ### #
#       ###  ###      g   ###  ### l f   ####  ##    #########    #         ##   # ### ### ### # # ### ### ### ### ### # #
#  ########  ###    g   r ###  ########  ##     #    ###    ### ###          ##    t                                     #
#  ########  ###        tg###  ########  #t   r #     ##    t    ##           #                  b                       #
#  ########  ###          ###  ########  ###    ##    ##        g r         ###   g                  tf  A               #
#       ###               gg r ###     l  ##     ### ##   g                 ##      t                         g          #
#  g   r###                    ###        #      ##             ## ###  gb ###   # #### # ## #### #### # ##t# ## # ## # ##
#       ###      l             ###       ## f g  ##            t##   #######     #    # #  # #gA     # #  # #  # #  #b#  #
#       ###    r               ### t     #   #####           t  #       ###      # # t# # t# #  #f#  # #  # #  # #  # #l #
#       ###                    ###           #######  ####   ####         ##     # #### #### #### #### #### #### #### ####
#       ### b              g   ###   b  g#   ##   ##### ##   ##### ###     #####  f     f                       t       r#
#r      ###    l l             ###       #   ##              ##     ## g   ####g                                         #
#       ###     l              ### l       r###       l      ##    r##     ##                                            #
#       ###   f                ###       #  ###               ## #####     #     # ## # ## #### # ## #### #### # ## #### #
#       ###    r    l          ###       #####  g   l        #####   ##    #     #  #t#  #    # #  #    #    # #  #    # #
#  ########  ###         g###  ########   ####       ##      #        ######     #  # #  # #f # #  # #  # #  #f#  # #  # #
#  ########  ###          ###l ########   ##        r#####   #       r   ##      #### #### #### #### #### #### #### ####a#
#  ########  ###   l    r ###  ########   #        ###   #####    ##                                                     #
#       ###  ###   b      ###  ###       ##        ###   ####     ###                                    t  t            #
#       ###  ###          ###  ###       ### ####  ##     ##      #### #### ##                              r            #
######  ###  ###          ###  ###  #####     ###   #     ##     g      ##   ### ## ### ### ### ### ### ### ### ### ### ##
######  ###  ###  f      g###  ###  #####      ##   ##    #             ##   #### ### ### ### ### ### ### ### ### ### ####
######  ###  ###   g      ###  ###  #####       ## ###    #    r      t ##   ## #                                        #
#  ###     r ### r        ###       ###              ## ###   g     ######          t                                    #
#  ###       ###r         ###       ###                  ##         ##   ## c## #                                        #
#  ###  ##########################  ###      ##  b            #### ##   g ####  g# ###b### ### ### ### ### ###t### ### ###
#  ###  ##########################  ###      ## t             ###         ####   ### ### ### ### ### ### ### ###t### ### #
#  ###  ##########################  ###       ##                         ###       t                                     #
#     f r               ll                     #    l                    ###               t                       t     #
# g                            f               #   g               #######    ##     r        tbf                        #
################          ###############      ##  g      ##########          ## ## #### # ## #### #### # ## # ## #### ###
################          ###############       #         ##     ##           ##  #    # #  #    #    # #  # #  #    # #f#
################          ###############       ##      ###       #            #  # #  #b#  # #  # #  # #  # #r # #  #   #
#  ###          f              g f  ###    ######## #####         ##           #### #### #### #### #### #### #### #### ###
# b###                  r           ###  ###         ##        #####           ###             b                       t #
#  ########  ###          ###  ########   ##          #        ###             ##           t          r                 #
#  ########  ###          ###  ########   #           #        ##              ###                                       #
#  ######## l###          ###  ########   #           ##    ####      l         ### ### ### ### ### ### ### ### ### ### ##
#            ###          ###            ##r          ##    ####                ##### ### ### ### ### ### ### ### ### ####
#            ###           ##   l        ###    ## ####  r  ##r           g t   ##                     r   b             #
## # # # # # # # # # # # # # # # # # # #         ##        ##   ##      b ##        ####  #####    ##l   #     ##b     ###
## # # # # # # # # # # # # # # # # # # # l       ##        ##   ##        ##    f ###  ####   ##  ###    ##  l #        ##
## # # # # # # # #t# # # # # # # # # # #         ##     t  ##   ##        ##      ##        g  #######b   #   ##       l #
## # # # # # # # # # # # # # # # # # # #    ##   ####### f ##   ##l  #######   b  ##           ### ###    ##  #          #
## # # # # # # # # # # # # # # # # # # #    ## c #######   ##   ##   #######     ##                       ## ##         ##
## # # # # # # # # # # # # # # # # # # #    ##                t        t       g        b      ### ###   l#  ### ### #####
## # # # # # # # # # # # # # # # # # # #    ##   b                              b##           b##   ### ###  #    ##     #
## # # # # # # # # # # # # # # # # # # #    ##  c                b                ######### ####    #    ##  #    ##     #
## # # # # # # # # # # # #t# # # # # # # ##############################   ##        ######   ##     ##   ##  #     #     #
## # # # # # # # # # # #l#   # # # # # # ##############################   ##         ##  ## ##       #####   #     ##    #
## # # # # # # # # # # # #t# #l# # # # #              ##   ##   g         ##   l   ###    ### A      ##      ##   g## b  #
#                                      t     c        ##   ##             ##    b###      ##         #      b##     ## ###
#    g      t                                         ##   ##             ##              #          ###l    #          ##
#                                           ############   ##   ##   #######              #           ##     #      ## ###
#     l                              l     b############   ##   ##b  #######          # ###    ###   ##      ##     #### #
#########################################        ## a      ##   ##   ##             ### ##     ###   #    ###### ######  #
#                                 r        t     ##        ##   ## f ##             ## l ##    ##    ###  ###     ####   #
#                                              gl##        ##   ##   ##             ##    #######     #####    b         #
# # # # # # # # # # # # # # # # # # # # #   ############   ##   #######   ##        ###                 ###    l  #     ##
# # # # # # # # # # # # # # # # # # # # #   ############   ##   #######   ##         b##        r        ##       #     ##
#   t                         t                 l##l  ##   ##   ##        ##         g # b  ########## ###        ##    ##
# l                                              ##   ##   ##   ##        ##           ## A ###    ##   ##    t   ###   ##
#                              g     g           ##  b##   ##   ##  b     ##       ##########       ## ##    #########   #
#               r                        #####   ##   ##   ############   ##     # ##     ##                 ###     #   #
#   g                                    #####   ##   ##   ############   ##     ###   f   #                 ##      ##l #
#               l      l                    ##   b         ##             ##b     ##     ###                 ##        ###
#             g             a              b##      t      ##             ##      #    ###### #######   ######    ####   #
#########################################   ##l            ##   r         ##     ##    ####    ##  ##   ##  ##    ###    #
#                                 t         ## b ############b  ##   #######    f#l            #    ## ###     l A##     #
#        t                                b ##   ############   ##   #######     #     ####    #             b     ###   #
#    l                  l       l           ##   ##         lb  ##       f##     #     ####    #         b         ###b  #
#               r                           ##   ##             ##l       ##     #             #    ## ###        ##b    #
#                 r                         ##   ##             ##        ##     ## b r####    ##f ##   ##  ##    ###   b#
#    l                                      ##   ##   ##########################  #    ###### #######   ######    ####   #
#                                      l    ##   ##   ########################### ##     ###  r            l ##f    r#####
#                       t               l   ##   ##           c                  ###       #  g              ##      ##  #
#t                                          ##  t##                b c           # ##     ##      A          ###         #
#        t                             t    ##   ##                            t   ##########       ## ##    #########   #
#       r   l                           l l ## b ##   ##   ######################      ##   ###f   ##   ##b       ###   ##
#                                           ##   ##   ##   ######################      #    ########## ###l       ##    ##
#                                           ##   ##   ##             ##      f bf     ##b            f   ##       #     ##
# # # # # # # # # # # # # # # # # # # # #   ## t ##   ##             ## l g  f      ###                 ###       #     ##
# # #g# # # # # # # # # # # # # # # # # #   ##   ## ll## f  a        ##  bf         ##    ####### g   #####       #      #
# # # # # # # # # # # # # # # # # # # # #   ##   ############t  #######  t#######   ##   ## g  ##    ###  ###     ####   #
# # # # # # # # # # # # # # # # # # # # #   ##   ############   #######   #######   ### ##     ###        ###### ######  #
# # # # # # # # # # # # # # # # # # # # #                             l   ##          #####    ###   ##    r ##     #### #
# # # # # # # # # # # # # # # # # # # # #              l       f          ##     b        # l         ##f    #      ## ###
# # # # # # # # # # # # # # # # # # # # #                               f ##              #          ###     #          ##
#                                           ##   ############   ##f  ##   ##     ###      ##         #       ## g   ## ###
#                 t         b      t        ##   ############   ##   ##l  ##   t   ###    ###        ##      ##    ##    #
#                                       l l ##        ##   ##   ##  f##  f##         ##  ## ##       #####   #     ##    #
#                   l                     g ##        ##   ## g ##l  ##   ##   l   l######   ##     ##   ##  #r    #    g#
#              f                a          t##        ##  l##   ##   ## f ##      ######### ####Af  #    ##  #    ##     #
#                       t              f ##########   ##   #################     ##            ##   ### ###  #    ##     #
#         t                              ##########   ##   #################                 b ### ###r   #  ### #########
#                       t                                b        l            r ##                       #####         ##
#      A         l    t                                 l                         ##           ### ### t  ##             #
#                                                                  l   g          ##    b       ######    #   ##         #
#           t                                               g                f    ###   ###   #   ###    ##    #        ##
#                             g    g                                b               ###  b###   f  ##    #     ##      ###
##########################################################################################################################
