metadata:
  gen_time: 13.347458839416504
  timestamp: '2025-04-18T22:48:17.124514'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#      c    l    ##  r   r    ##           ##                   t                                           c            #
#                #  l   #     ##     #t     #  b                               r  r     ##         r         ##          #
#             f ##          #    #          ##  t           t                           ##                   ##          #
#   t #         #           #    #           #        r#              f                        ###           ##          #
#       ##                         f                ##              t              r           ###           ##          #
#  #    ##          l        ####  r                ##    #          #################### c  b   c        g  b           #
#      ##  ##                #### l              ##  ##              ##  ##  ##   ##  t##       c                        #
# b   b##  ##              b #  #                ##  ##       #########  ##l ##   ##t  ##                                #
##     ##   ##           ##  f     ##  A f r    ##   ##     # ##    l    ##  ##  l##   ##        r r                     #
##     ##   ##           ##        ##       br  ##   ##     ####         ##       ##   ######################### #########
#      ##f  ## l    #f    ##      ## g   #  t   ##  l##                           ##       ##   ##  ##  ##    ##  ## b   #
#      ##   ##   #       b###    ###        #   ##   ##           c               ##       ##   ##  ##  ## r  ##  ##  c  #
#      ##    ## l             t         t    l ##    ##                           ##       ##   ##  ##        ##         #
#      ##    ##   ##    ##          ##    ##   ##    ##    r #######  g           ##       ##   ##  ##        ##         #
#       ##    #      #  ###  #f #  ###  #      #    ##           r##              ##            ##t ##        ############
#       ##       #        #t #  #  #     t  #       ##            ##              ##           g##  ##            ##   ###
#   ###   c                   ##                       ###        ##     l  t   c ##         g  ##  ##            ## r ###
##  ###  #     ##                          b ##     #g ###  ########              ##   g            ##    c       ##     #
###      ##    ##        #    ##    # f      ##    ##      ####    g             bt     t        c  ## l    b     ##     #
# # t    ##    ##             ##             ##    ##t     # ##      b                 fb           ## lr     b   ##  ####
# ##     ##                               r    l   ##     ## c              bc                      ##            ##  ## #
#  ##    ##    #                              #    ##    ##    l              rt                    ##         t  ##  ## #
# l## b         #                   r     g  #        t r##        ## ### ############################            ##     #
# f ##                ##    l   r     ##           l    ##     a   ##  ##  ## l r  ##       c   ##f              l##     #
#   ##   g               r                             f##       b ##  ##  ##      ##           ##r               ## b   #
#   ##       r              g                           ##         ##  ##  ##    r              ##g            g  ##     #
#  l ## ##   ##            t   g               ##   ##a##    t     ##########          r        ##        ##             #
#    ##  ##  ##    t   g   b       g           ##  ##  ##                                       ##      t ##             #
#      lb #  ##      #        g         #      ##  #                 t             b tb         b         ##             #
#         ##  #      #                 b#      #  ##                  b       b    l                      ##      b     ##
#    bg    #                #    #                #                          c  l          b###           ##            ##
#            #             l##  ##              #             t t                           ###                       t ##
##            t             ######                        r #     t          l    c           #               l         ##
##                           ####      l   gt               #  l     #########                #                         ##
##          r     ##                   f  ##          f     #r       #########               g#                         ##
#  ### A          ##                 t  tA##            ###          #         c              ###  t                     #
#   ###      ##    ##        f           ##    ##   r  ###           #      l       b         ###     c                  #
#           ##                                  ##           t      l# a        b             #                       ####
#  #  lb        f            ####  b                      #    b     #     ########l          #                       ## #
#   #           l                               b        #           #     ##    ##           #    g   g              ## #
#        ##  f                                     ##   r tl #       ###   ##    ##           #    ##################### #
#        ###       g  b                           ###        #    l  ###t  ##    ##   r       ###  ##  l r ##     ##     #
#         #####f                 b             #####         ###              t  #########    ###  ##      ## t   ##     #
#            ###    # t    ###  ###      #    ###f           ###      c  b     t    l   ##    t #        l ##   c ##     #
#        #     t #   ## l  ##    ##    ##   #       #          #        b     c      l  ##      #                        #
#        #       #     #  ##      ##  #     #       #          #                        ##      #                        #
#  t           f b#    r ###  l   ###      #g          g       #        t               ##      #########                #
#                                       g                      #                        ##  ##  #########                #
#          #      A  #                 b#         #l         ###                       c##  ##t        r            c    #
####       ##        ##f               ##  t   b ##    g  ######                b       ##  ##          r                #
# ##       ###       ###              ###       ###       ## #                            bt##             c             #
#  ##                  # ##b    g  ## #                  ##  #    ra          l             ##         b                 #
# l           ###  t  f         g        g f ### A           #############################################################
#   #      t  f####     r                  ####   b  fb  #      ##       ##   r##      ##b     t##           ##  ##  ##  #
#                 ##                     t##         f          ## r     ##    ##      ##       ##           ##  ##  ##  #
# ##   ##             l                       f      ##   ##    ##  b          ##      ######       g  t     ##  ##  ##  #
##     ###             ##   ######   ##             ###    b# l ##b          t ##          ## b              ## b##  ##  #
#       ##     #            ##  ##      r     #     ##          ##     r       ##          ##          b     ##  ##  ##  #
#   #          ##          ##    ##          ##          #      ##  t          ##    r     ##  ##     t      ##  ##  ## g#
#   #          ##   lr               r       ##          #    A ##  f          ##   A      ##  ##   ######   ##  ##  ##  #
##      #####    ####    g      #    ###    ##                           ###  ### t                  ###  ###            #
#         # ####  #      f   f# #   l  #   ##  ##          ##            ###  ###b   r               ###  ###    f b     #
#    ###      ##  ###b      t #    ## ##   ##  ##      ##  ##  ########  ###  ###  ################  ###b ###  ########  #
#    #         #    #    ##A  ###     ##         f#        #   ########  ###  ###  ################  ###  ###  ######## t#
#    ## ### #  # ##      ###    ##    #  ### ##   # ##         ########  ###  ###  ################  ### t###  ########  #
#    #### # #    #   ##  # ##  ###       ##  #   gb ##   #  g  ###  ###                                       l###  ###  #
#      ## #   ##           #   # #             b#####   ##     ###  ###            t                       b   ###  ###  #
#    ###  ##  ##c       ##          ## ##  ##    ##      l l######t ########  ###  ###          ###  ###  ########  ######
#   t #  b        ##  f    b   ##   ##      #   ##  ####  ########  ########  ###  ###          ###  ###  ########  ######
#         ##### ####  #    ###      #  ###  #  ##   ##     # #####  ########  ###  ###   t      ###  ###  ########  ######
#  ###      ##  #    ##  ### #   ## # f#    ##       ## #  l             ###  ###  ###        la###  ###  ###f     g   l #
# ## # #     ##   ## ##l       #  # ##       ##### #### #   #  t         ###  ###  ###          ###  ###a ###            #
# #    # A ###### ## l  #   ## ####      ##   #l   ##       ###########  ###  ########   t      ########  ###a ###########
# # l  ##       ###     #   ##  #    t#   # # ## #           ##########  ###  ########          ########  ###  ###########
# ##   #####  ####   ##           ### ### ### ####   # #f ##l##########  ###  ########          ########l ###  ###########
#  #     # ## #     ### ##lt  ##  A##   # ##  # ##  g# #   ##       ###       ###  ###          ###  ###       ###       #
#  ## #    ##     # l        ##   ##       ##       ##   # ##   b   ###       ###  ###    c     ###  ###       ###    t  #
#     ##   #      #           # ###   ##            ##   ###l  ##################  ###          ###  ##################  #
##    ##f      ##                #   ##    ##       #    ##    ##################  ###          ###  ##################  #
##    #  ###  ##               ###  ##        ##       a## t   ##################  ###      b   ###  ##################  #
#f    ## ##             ##  b   #    #c       ##       ##        tb           ###                    ###       b         #
##  # ## #               ###   ##      ## ##  #  #     #                      ###            g       ###                 #
#   ###      ##          # #  ##     ###  #   ####          # b########  ###  ########          ########  ### t########t #
##  ##        # # ## ## ## ##  # ## ## #  ##   #      ## b  #  ########  ###  ########          ########g ###  ########  #
#        g####### ## #  #  #######  #  #      f##           #  ########  ###  ########t         ########  ###  ########  #
#   ##    ## #    #  ##l        ##l##  ##      ##  ##    #  #  ###   t   ###          t    t              ###     b ###  #
##  ##  #    ##   ##  #   ## ####   ##     ###    ##  #  ##    ###    tb ###                        r     ###gg     ###  #
##  #  ##   ##    ##    # ##    b    #   #   #     #  #  ####  ###      a###                              ###       ###  #
#   ## ##   #####     ###     ## ##    ###      ####    ## #   ###       ###            a   t             ###       ###  #
#    #         ##         ##  ## #   ####  ##  ## #     ## ##  ###       ###            t    b            ###    b  ###t #
#        ##     # #r##    ###    ##  ##    ###  #        #  #  ###    g  ###             b                ###     f ###  #
#   ##   #     ## #      ## ### f##  # g## # #  ##l   ## #  #  ###       ###                 b     g      ###       ###  #
###             ###   l ##  # #         ##f      t     ### ##  ###       ###   l                          ###       ### l#
# ### ##    ### ##          # #         #  ##     f# #g#   ## l###       ###                          b   ###       ###  #
#  #  ##    ##      #   ##      ##          #   #  ###    ##   ###l      ###                b             ###       ###  #
#  ##       #     ###   #   ##    g  ##   # #    ###   ####    ########  ###  ########     b    ########  ###  ########  #
# ##   ###         #        #     #      ##   ## #   ### #     ########  ###  ########          ########  ###  ########  #
# #    # #     ##  ##   ###       ###  f ##    #   ###       t ########  ###  ########f         ########  ###  ########  #
#      # ## #   #         ###      #   #    ## #   # # ##                    t###                t   ###       f   l     #
#  ##    #####  #    ##   l f   ## ##  ### l####        #  g a                ###            t       ###                 #
# ##     l  l#      ## t  #   b         #  ## ## #        #    ##################  ###          ### t##################  #
#     ##       #     #     #      ## ## ## #     ## ###   #    ##################  ###          ###  ##################  #
##          ## ##   ## #          ## ##         ##  #     ##  a##################t ###          ###  ##################  #
##  #              ##  #   ### # ##  #       ## #   ## ## ##       t###       ###  ###  a       ###  ###       ###       #
#  ##  ###               ####  #      g                ## l##      a###       ###  ###  f       ###  ###       ###   gl  #
#####  #              ## #       ####  ##  ##  ##  #####  #############  ###  ########          ######## t###  ###########
##           ##### #   #   ##t     ###      f  #   ##        ##########  ###f ########          ########  ###  ###########
###  ###  ##  ## ###  ##    ##   ### #   ##    ##       ###  ##########  ###  ########          ########  ###  ###########
#g     #####l##   ##   ## # #     #           ##   # ## ##            g  ###  ###  ###          ###  ###  ###      a     #
#        #   t     #  #####      ##   ##    #### ### l  ft    f          ###  ###  ###          ###  ###  ###  f         #
#      #      #    #      ##  # ##     ## #  #    #  # ###   #####  ########  ### l###         g### l###  ########  ######
##    l###  f ##       ## #   ###   #   ###  ##   gf # ##    #####  ########  ###  ###     t    ###  ### l########  ######
#       #         ##  ###       fr ###   ## ##      ##  ##   #####t ########  ###  ###        g ###  ###  ########  ######
# ##    ##     #   #     f g  #      #      #        ## ##    l###  ###              a                         ###  ###  #
#   c #   l   ###### ###    ###   l        ## ##     ####      ###  ###t                                       ###  ###  #
##  ###         # #  # #  ### ## ##   ### ### ##   g # ### t   ########  ###  ###  ################  ###  ###  ########  #
##  # ##       ## ##   ##        #     ## #      ##            ########  ###  ### b################  ###  ###  ########t #
##    #     ####       ####      # # ###  ## ######  ##  #     ########  ###  ###  ################  ###  ###  ########  #
## #          #        # #         ###    ##   ## #  #   #               ###  ###                    ###  ###            #
## ##                    ###        ## ##      l    ## b   ##            ###  ###                  t ###  ###        t   #
##########################################################################################################################
