metadata:
  gen_time: 9.049577951431274
  timestamp: '2025-04-18T22:47:48.257346'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#            t   tr        r         ##       a            a  a                                                         ##
##  ####             ###        ###  ##    g    a   a ra  l                                                            #t#
#    ##            #####        ###  ##  ######        g b     f                                                         #
##   ###             ###  g     ###  ##  ######g          f     f###   ##########     # # # #   # # ## # #   # #f# #   t #
#  f ##              ###        ###      ##   #  f      r                                                           # b ##
#    ##              ###   l    ###     l##   ## rr                                                                #     #
#    ##              ###   g    ###  ######   ####   a        l                             A                         #b##
#  l ##    ####    t ###        ###  ######   ######### #### ##   #                                                  # # #
# #  ## #   ##       ###        ###           ######### #### ##          #                                    #   # #    #
# #  ## #   ###      ###        ###             ######   ###           #                        # #      #     # # #   # #
#    ##    b##g                    ########   t   ####a  ###           #                      #              #b# # # # # #
#    ##     ###                    ########       #####  ### a                                     #          # #        #
##   ##     ##       t                           ###### g## a    #                      #   # # # # ## # # # #   # #   # #
#    ## #   ###    a                          b r######  ##   g ###r                   f                                 #
#    ## #   ###      #####    #########  ##     ######   ###     ##                                                      #
##  l##     ##    g  #####    #########  ##     ###### a ###           #                 b                           r   #
#    ##     ###f     #####    #####      ##     ######    ###  ### ### ##     #                                          #
#    ##     ##    b  #####    #####      ##     #######t  ### g### ###                    # # # # # ## # # # # # # # # # #
# #  ## #   ###      #####    #########  #####l########   ###  ### #####   a        g          #   #  #   #   #          #
# #  ## #   ## b     #        f   #####  ##### ##############f ### ######   l  #        # #   # #    # #   #   #       # #
#    ##    ###       #            #      ##          ########f ### ###########          # # #r# # # ## #   # # #   #   # #
#    ##    f    r                  r     ##                   b ##    ############       # #                           l #
#    ##                              ######  l f## f  b#####  a ##      ###al ###t#     #   #       ##         # # #   # #
#    ##                     ft     b ######                                            #                  #              #
##   ###           l        b                  l#############   ##  ar  ###    ### # #                   t#              #
#    ##            ##                                                          ##f#t# # # # # #   # ##   #   #   # #   # #
##  ####                    r      #### b##            r ######### b   ###     ### #                                     #
# b                      t         ####  ##     #####      a ######    ####  l#### #  l                   #              #
# t   ##  ##         ######  ###### f    ##                  ######   ###########     # #   # #   # ## #     # # # #     #
#     ##  ##    ##   ######  ######      ##                                  ####     r           l                      #
#     ##  ##    ##   ######################      ##################f  ###   a  ##   # # # # #   # # ## #     #   # #     #
# f   ##  ##   t##   ######################     a##################l   ##      a            b                      t     #
# ##################                        t   ###################    ###        #       # #   #        #   # #       # #
# ##################                g    l    # ##########################                f                            f #
#        ##            r           ####  ###### ####   ################### #  ### #       # # # #      b # # # #     l # #
####     ##  ##f    b              ####  ######    l   a  ##    ########## ######                      l  #              #
####l    ######                          ##  l### a    a       f g###  ### ###### #       # # # #            # #A      # #
# ##     ######l                     f   ##                       ###      g ##b                          #              #
# #########  ###### #                ######   ####g              ####         #   # # # # #   # #          # # # # # # # #
# ######### f###### #  f             ######  f####  g#######  a  ####      r ##                                          #
#   ##   ##  ##   l    ##########             #######################       a###   #    A                 #              #
#   ##r  ##  ## g      ##########              ####a###r ############# t     ###      #   #     #      t #   #   #   #   #
#r  ##     A ##        ##########           b a#     ##  ############# ### #####                         t#          l   #
#   ##   ##          ###### l###### t       f           ##########  ## ### ####r  #       # #   #        #t#   #       # #
#   g    ##  ##      ######  ######      b  c  ##t   ############# r## ### #   l                          #              #
#  #                #  #     #  #   #  #     # ###  a############# ### ### #   t          #     #        # # # #   r   # #
# ##                ## #     #  # # #  #     # ###   ############# ### ### ##                     f  b                   #
#  #                #  #     #t #   #  #     #####  a ##    ###### ### #   ## g   #       # #   #        #   # #       # #
#  #   f #    #     #  # ##  ## #   # ##  ## ######t  ##     ##### ### #   ###                t                    f     #
#  #  #  # ## #  #  #  #  #     #   #     #  ####### ###     ##### ###  ab ###    # # # # # # # # # ## # # # # # # # # # #
#  #  # ##    ## #  #c #  #     #   #     #b #ra ### ###     #####  b#      ##                b           #      b    A  #
#     #  #    #  #     #  #     #   #     #  #           b   ##      # #    #  a        # # # #     ##   #t#   # # # # # #
# r   #          #     ####     #####     ####   l    #########    a## #    ##                            #      f       #
#                      b                      g a     ##########    ## ### ###a    #                t     #              #
#          ##  c           b                          ############ ### ### ###                #   # #        # # # #   # #
# ##### A        ##### #######  #####  #######        ############ ### ### ### a   #                      #              #
# #                  #       #      #  #              ####a ###### ##      ##t                            #              #
#         #  #      l   #    # t#   #  #    # a        ##    bt##  r   f   ##         # # # # #   #            # # #     #
# ##      ####      ##  ######  #   # A###### ##       ##       #        b ##  g                          #              #
#    l    #  #                  #   #         # #    #        ## r###   t  ###      #   # # #   # # #  # #   # # # # #   #
#f     ## #  # ##        f     t#   #           ##  ##   #  ###    # r##          # # # # # # # # # #  # #   # # # # #   #
#      #  #  #  #       ######  #   #r ######   ##     ###            ##  ###  ###                  f     #              #
#####l #        #  #### #    #  #   #  #    #  ##  ##  r#      ##     #     #     # # # #   #     # #  #     #   #       #
#      #        #            #  #   #  #            ##  ##      g        #r##  ##           b             t              #
##     #        #     ########f #####  ########  ## # ###      ##### #   ###  b                                        b #
# t ## #  ####  # ##  c                       ##  #           ## ##  ##    #  ###            f                   b      r#
#                                             l   fb##    t       ##     f   a  #                          a             #
# c  #            #    ####    f#####     #### ##   ###     f # # ####### ##        #   # # # #     ## # # # #   # # # # #
###### ########## ######  #     #   #     #  # #  b       # ### #r  ## ##  #  # #                   b              l     #
#          c  f        #  #     #   #     #  # ##   ##    ### # #  ##   #     f # # # # # # # # # # ## # # # # # # # # # #
# #    #   f    #    # #  # f   #t  #     #  #       ###r ##  ### ##       ### ##b# # # #   # # # # ##   # # #   # # #   #
# #   r#        #    # # ##  ## #   # ##  ## ##  ### # #  #        # ##    ##  # # # # #   #          # #     # #  f     #
# ##   #        #   ## #     #  #   #  #     ##   a#             #####   rt             # # # # #b# ## # #r# # # # # # # #
# #       t          # #b    #  # # #  #     ###         b    b   #        # ##  # #           #  f       #         # # ##
# #        c      f  # #     #  #   #  #     #t#  l### # #           #### ##  #t        # # # # #        #   #        f  #
#       #      #     #  r       ## ####      t### ##   ###  #  ##   ##r##  ## ## #   #                              #   ##
#l l    #      #           r     #            #   #  ###   ##           #####  ##     # # # #   # #  # # #   # # #       #
### ##  #      #  ## ##  r       #     r        #    #   ###  #  # #     #f  t ###   #           # #  # #           # # ##
#   #   #      #   #              l    ###       ##  ##  ##   ######  ## ##       # #       f   #    #     #    f  #     #
##    r               # t   t    #  ###### f   a #    #   ##   #b     #   #    # # # #f    l   # # #  # # #         #   ##
##### #####  ##### ####t#     t     ## ###    ##c##     a ###  ####            ##                            #        #  #
#     #  #    #  #      # # ##         ##     ####       r       #       r## f         l                                 #
# l              t         r##   #     ##       ###      #    #### a## # ##l     ##########################              #
# # t             t  #l    ###  ###     #     ### #  ## ##      #    #f#### ## # ######l############g######              #
# # ##  #  ## c#  ##r#     ###  # #   f##             # #   ### ##a ##      ## #  r      ##t     ##                      #
# #  #  #      #  #  #                ##        a       #    ##    t#  ##   #   t        ##      ##          #        #  #
#    # ##      ## #   t               ##        ## ##   ##  ##      #a ##   ###          ##      ##                      #
#        l      l                   f #  ###   ##  #     #            ## r ## #          ##      ##                r     #
#  t # #        # #       #  ##    ## #  ### b  # ## ###l# #  ## # #   #    # #         g##      ##                    r #
#    # #        # #          ##    ####    #  ### #    ###l##  ### ### ##  r  ##         ##      ## l  g                 #
#    # #        # #    #####  #    ######  #                #   ## # ###      ##         ## b    ##                    t #
###### ##      ## ##### #     # c  ##   # a     ##               ### #                   ##      ##              a       #
#       #      #        #  ##   #     b##   g   ##       ##     ###  ## ###    ##      g ##      ##                      #
###### ##      ## #####         #      ##       #  ## ## #      #    ## ##                #t                       f     #
#    # #        # #           ###      #### ##   t ##     bt      f   #      #           ##      ##     c   l    l       #
#    # #  t     # #    ##     # #g    ## ##   ##   #                    ### a##         g##########   r                  #
#r   # #        # #                   #       ##      #### # #  ###   ### #   ## ##########################t       f     #
#    # #        # #    #     #  #t    #r####t r##  ##   #### #   ##   #   ##   # ##########      ##########              #
#    ###        ###         b    b        #    #          ##  r   #a     ##  r      ##   ##      ##   ##  #     #  #     #
#                      ##     # #     ## ##    # ####  ##  ###           #   #   #  ##   #     t  #   ##  #              #
#                             ###  l   #### ##   #  #   # t       ###    #  ###  #  ##   ##      ##   ## r#              #
#                               #b     ## g            ## ###  a  ##     ## #    #  ##   ##  A   ##   ##  #b             #
#                       #b ##   #      ##        ####  ## ##   ##       ##       #  ##    #      #    ##  #   #g     #   #
#                       #   r #    ##   #   b    ## ##     t     tl  # ##    ####   ##   ##      ##   ##             r   #
#                     r#####  #    #### #  #    b        ####  ###   #      ## ###  ##   ##      ##   ##  #              #
#          r                 ##    ####  l #    ##         ##    ## ## a ## ##  ####### ###      ### ######              #
#     r                  g#  ##    ## #  ###  #  #         l#       #    ## #    ###### ###      ### ######              #
#                                     #  ###  ####   # # #  #    ####  l  #              ##      ##                      #
# a            f           l          ##g      # ## #### ##       ##     ##    ## t               #         #   #  #b  # #
#    ###    t   ###A       g          ##            #     #      ##       ##   ##        ##      ##        b             #
#      #        # #        ###  # #    ##       ## t   ## # ## ###       ####   #         #      #          l        l   #
#   t# #        # #        ###  ###     #      ###    ##    #  #  t                      ##      ##         t  r         #
#    # #        # #         ##   #     ##            ###  b # ## ### # ##    ##bb        ### ## ###                      #
#    # #        # #     # #r##         ##         ## # ##  ## #  #   # ##     ### f      ##########   r                  #
# #### ##      ## ##### #           ## ###        ##   ### #     #####    #   # #                ## l                    #
#  a    #      #                 #A ######   t #  #  ### #         ##     #     #        ##      ##             #  #     #
# #### ##      ## #####                ###     ## ## ##    ### ## ##   ##   ###          ##      ##         #          # #
#    # #        # # r  b      f  #           b ## b###     # #    #   ##    ##           ##      ##              f       #
#a   # #        # #              #    r           ###          c      ## a           c   ##      ##                  g   #
#    # #        # #             ## ####           #          t    ###           ####### ###      ### ######              #
##########################################################################################################################
