metadata:
  gen_time: 4.9296629428863525
  timestamp: '2025-04-18T22:47:53.266469'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  ##  ##  ## f##f    ##  ##  ##     ##   ##   ########### g         ###########                                     f   #
#       t                                     r###########           ###########                                     g   #
# a##g     ##  # a    ##  ##  ##     ##   ##    ########## g ## ##   ###########                                      b  #
#########   #### ## ##########################b         r    ## ##               ########                                #
########### ####      #######################      a         ## ##               ##    ##                     f          #
###  ##  ## c##  #    ##   ##   f##  ##       b             b## ##               ##    ######## ####### ################ #
# a                        r                  # ###########  ## ##  #############            ##  ##  ##       ##  ## t## #
# #  ##  ##  ##  #     #   ##    ##  ##    ## # ###########    l    #############l#     f    ##  ##  ##       ##  ##  ## #
# ######### ###### ### # ###################### ########### a       ###############          ######  ##       ##  ##  ## #
# ######### ###### ### # #####################  ###########         ###############   g   g         r###########  ##  ## #
# #       a ##     #     #   ##  ##r    ##  #  ############ r       ###############                       ##      ##  ## #
# t                                b    r     #############         #############                         ##      ##  ## #
# #    f    ##           #   ## b##     ##  ###############     l   ############# #                     r ##      ##  ####
# ######### #########  # # ######### ######################     a   ############# #######                         ##     #
# ######### #########  # # ######### ######################   b     ############# #######                   g     ##     #
# #      ##  ##  ##    g #     ##  #   ##     #############         ############# #            f                  ##    ##
#                                          a  #############     l   ############# #           g                   ##  t ##
# #      ##  ##  ##  #   #     ##  #   ##     #############     a   ############# #                               ##    ##
# #############   #### # #  ########  #####################      b g###############                            t  ##    ##
# ###############    # # #  ########  #####################        r###############                                b   g##
#  ##    ##  ##r  ##   #    ##  ##        ##  #############   b     ######################## ##### #######              ##
#                        l                                   l          t             ##  ##    ##      ##              ##
#  ##    ##  ##   ##  ## a  ##  ## a      ##       c              r    b             r##  ##    ##      ##               #
# ##############################################       ################# b     ##     ##  ################               #
# ############################################## b     #################       ##     ##            ## g                 #
#  ## c ##  ##  ##    ##    ##   ##A  ##a   ##l  f   r #################             r## r   b      ##                   #
#           t      f                          brb      #################              ## g          g        b           #
#  ##   ##  ##  ##    ##    ## b ##   ##    #########               t     #######c    ##                 f          A    #
# ### ##### ###### ########################### a       #################              ##   g   r                         #
# ### ##### ###### ###########################         #################   ll         ##    r    Af                      #
#  ##  ##ba # c##   ##   ##r ##  ##  ##   ##  ##       #################       ##   g ##                        r     t g#
#                                             ##l      #################       ##     ##f                                #
# r##  ##  ##  ##   ##   ##  ## f##  ##   ##                        a     a t                               t     ########
# ### ################################# #### #                                         f                          ##   ###
# ### ################################# #### ##############        l#############                                 ##   ###
#  ##  ##  ##  ##      ##   a##     ##   ##b  #############         #############           r                   f ##   ###
#          g                          l    t r#############f     b  #############                      t                 #
#  ##  ##  ##  ##      ## br ##     ##b  ##   ############# rb      #############                        rf         f    #
# ###  ####### ############################################         #############  r                        ##############
# ###  ####### ############################################      a l#############    f                      ##  ##    ## #
#  #      t  #           #  l    ##           #############         #############       f                   ##  ##  g ## #
#  #                      t      #  r         #############         #############               f                        #
#  #           #              ####     #      #############f        #############                                        #
#  #       #         #                 f      #############         #############                                  ##   g#
#A   ## #         l    t#              b f    #############     t   #############              t                   ##   b#
#    ####           l                         ############# r   a   #############      r               b             f   #
#   f##                       l               #############  b  f  r#############                  ######                #
#   ###   #  #    ##      ##         l        #############         #############    r       A     ##  ##                #
# # ###   #  #  # ##   # ###       ##         #############  ## ##r #############                  ##  ##                #
### # # r       #l       ######         ##    l            a ##b##                   g                 ##                #
### b #         #        ####         ###                    ## ##           f           t      r           t            #
#     ##  #              ###  f      ####  #                 ## ##         r                 g r                  g      #
#f   b      ##l          ######            #  a###########   ## ##   ###########        g              g                 #
#            #                ## f             ###########           ###########         t   f      ##################   #
# ## t                              ##       t ###########           ###########           r        ##  r##   ##    ##   #
# ##       #   #  c                        #     #               l                          ########           l         #
# #   ###            #####     l       #   #     #               ##   t                     ##  ##     g            l    #
# #   ###    t #     #           #   f   # #  ####  r            ##              g          ##  ##                       #
#     ####          b#                 f##    ####               ##   l          c          ## l                       l #
#     ###       #   ##         ###   ##  ##                          ######## ################             l          ## #
#              ##   ##         #    ###    l #        l              ##    ##  ##    g                                ## #
#     #      #  b #           ##   #### #        ######## #############    ##c ##            f  t   t                 ## #
#     #  t ct###               #        #        ##    ##  ##   ## a       ##  ##              l                      ## #
#    ##        #           t  ##     ## ##### #####  c ##  ##   ##         ################ ####                ###  g## #
#      f    #  #              ##      #                ## l##   t                   ##   ##   ##      r l       ###   ## #
#           gl   ###   # ##   ###     ##               ##  ##         f             ##   ##  r##  tt              #   ####
########   ##  ####    #    ####  ##   #######         ######   ######################   #######             t  A #      #
# ######r  ##  ####   ###   ####  ##   ######                   ##      ##     l##                       ## ####  #  t   #
#  f##          ##   #####   ##          ##    ###              ##      ##      ##  r     f              ##   ##  ####   #
#               ##   #####   ##                ###                  l   ##      ##      ###################   ##  ####   #
#        ##            #            ##g          #          l                   ##      ##   ##  ##           ##  #  #   #
#      #####    r    f             #####    b    #                    t t       ## t    ##   ## f##           ##  #  #   #
##r    #####   r## r         ##    #####     #   #                  ####        ##   l  ##   ## l###############  #  #  t#
####  tg##    #####         #####  r ##    #######           t      #### a  c   ##      ##   ##    t     ##       #  ### #
####          #####   ###   #####          #######                  #                   ##   ##          ##       #  ### #
###        c   ##   c ###     ##            ##   #                  #                   ##               ##       #  c   #
#       ##r            #         l   ##          #                  #                   ##       b       ##       #      #
#  g    ##   b                   f   ##    g    c####        t      #          c        ##               ##       #      #
# ##          ##  b            ##        g ##    ####              l###      t          ##               ##       #    f #
##### l   r ####       #       ####       ####      #       c       ###                 ##               ##       #      #
#####   ##  #####g   #####  g #####  ##   ####      #g        l       #                 ##                        #    t #
# ####  ##g  ####  #########  ####   ##  ####       #    c  f l     l #                 ##      r       g         #      #
# ####       ###   #########   ###       ####       #                 #                 ##             t          #      #
#  ##         ##t   ##   ##    ##         ##    t   #               ###        ###########   tc          l        #      #
#g  f    ##              f b        ##          #####               ###        ##              f                  ###    #
#   A    ##                  t      ##          #####  ####                    ##        f              ####      ###    #
# ##        t     ## g     ##  b           ##          ####           c        ##                       ####c       # g  #
#####         b   ##   #   ##             ####      l     #                    ##      ct               #  #        #  ###
#####          b  A   ###                 ####       tt#  #                l  t##                       #  #        #  ###
###          ##       ###       ##          ##  fa##    ###t  ###    #r ## f t              #          ##         # f   ##
#          #####  ##   #   ##  #####            c       ##    ####  #######   ##   a               #     a       ###     #
#   r    ####### g## f #   ##   ######         g    a  ab      ##   #######  ####    #            ###   f  ##    ### b   #
##   ##  ######       ### b   t ######  ##   #    r        a   ##l   #  ##   ####f ####  ##  a    ###a   #####g ###      #
##   ##   ##### r     ###     l #####   ##   #    a  ##  ##   ####       r   t##   ####  ##      ###     ##### a ##   c  #
#     ####  ######   ###     ###########    ##     #########  ####            ##    ##f       c   ##      ## r          ##
##     ##    ####   #####  l############   #### b  #########   ##a          a####            ##    a                   ###
###       g l       #####  ############# l######    ##  ##     g            b ##            c##r   a  ##    a     a  ar ##
####                 ###   ############   ######          b a      ##    a       a          c      c  ###           #    #
####   ###    ###l  g       ##########    #####        a    a    #####   g        a##  ##  c  a      ### f   ##   ####   #
####  #####  #####           ######## gl  ####  l        #ra    #####     ##    a#########         g  ## c c####b ####  ##
###   #####  ######    ##     ######g      ###        a####      ##     #####    ########          a f      ####   ##   ##
#   r  ###   #######  ####                  ##t  c    l####       c   c ####      ##        a     ##   a      #    ##  g #
#            g######  ####         l     r        ##   f #   g      c    #         a  c     ##    ##           af   l  g #
#####          ###  lg ##    ###                  ##  ag    f     #  b         c    a f     ###        a##               #
######      l      b        #####      ##      lc####        #   #####           ##  g##  g###  c       ##  a    ##      #
#######    ##               ######    ####       ####g   t ####   #####   ##     ##c  ##    ##     ## a        a ##b    r#
########  ####       ##t    #######  ######   #   ##r  a  a####  a  ##   #####  ####         a   f###  r                 #
# ######  #####     ####    #######  #######   c            ##           l####t ####               ###   a         aA##  #
#  ####   ######    #####   f######  ########     t   ##   a          g   a #     #  c##   ##     f##              ##### #
#         #######   ######    ####    ########    a ######    a ##a  ##         b     ##bt ##  ##    f     a  ##   ##### #
#          #######  #######       b    ########   a #######  r#####  ##c r               c     ##         ##  ##    ##   #
##    ##    ######  ########            #######         ##    #####        t c c#  g        l      ##     ##    a   t    #
## t ####  t ####    #######             #######      gf       ##             ####   c## a##  g    ##a         t         #
##   #####            #####   b####     A     ##  r            c      ##  #a c####afa ##  ##  ##ca     r ff     ##a      #
##    #### l             lr   ######     b    #          ## ag  r   ########   ##   c       g ##        ##    ###### f ###
##  g  ##       ##            #######         a a   a    ##    ##   ######## c ##                     #####   #######  ###
##             ####            #######               a      g#####   ##  #    ####    #c    a      b  #####    # c##     #
##             #####   ###      ######           ##          #####   c        ###   ####   r     ##   b##         aa     #
##             #####  #####      ####          ######          # c       a     ##   ####         ##    r               ###
##              ###   ###### g                 #######  r  b                        c##   ##                 g##  ##  ####
##########################################################################################################################
