metadata:
  gen_time: 10.116580724716187
  timestamp: '2025-04-18T22:55:01.257688'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#               ##      ##                       c            a    f       a g     ###        f         r            A   #
#     #         #        #         #          a                                                                    a     #
#    #    #                    #    #             l          gb         t                                             r  #
# g        # #   t  ##      # #                  b                                       #######       ## ##   f         #
#    ####    #              #    ####                            #########            g        #       #   #             #
#      b     #  #        #  #               r                    # g g   #               #     #  g    #   #      # ###  #
#    #       t   #      #           #                            #       #               #     #       #   #  r   #   #  #
# #   #                            #   #                   g     ######  ## ## a         ####### t ## ##   #  f   #   #g #
####               #  #               ###                             #      # r      a         a r#       #    b #####l #
# #         #    b  ##       #         #       g                      #      #                     #      g#             #
#            #     t        #                                         ########    b     ## ##      #       #             #
# f                 ##           t   t                 c              r                 #   #      #       #####         #
#      ###                      ###          c                  a                      t#   #  #####           #         #
#             #  l         #t      r f                     #######                  ## ##   #  #     bf   a    #    a    #
#      #   t  #  # #  # #  #      #                t       #     #     r   f        #   b   #  #         a     #         #
#       #  #     #  ##  #     #  #            g          f #                a       #       #  #               #         #
#    #      #    #t     #    #t     #                      #### a#             tr   ####   t#  #   fa          #####   t #
#     #     r                    t #    t                   A #  #####    t    ag      #    #  #                   #     #
#   rr   #  ####          ####  #                             #      #                 #    #  #t           a c    #     #
#      t # f                    #           l         r     r #      #         c       ######  #t                  #     #
#      # #     #    ##    # r   # #      a      ## ##         #      #      b                  ########      a     #     #
#     ######    #   ##   #    ######     # ##   #   #       g ##g##  #         b b         r          #            ####  #
#     b # #     r   ##         # #          #   #   #a            #  #           ##### t r            #               #  #
#       #           ##     g     #          #   #   #             #  ######      #   #             c  #               #b #
#       #      #        f #      #   r      #   #   #             #       #  r   #   #              t #  b      r     ## #
#               #        #        t         #####g  #####      ####       #      #   #         l b    #                  #
##   #             #  #             #   # r             # g    #          #      #   # a    #####     #  ## ##      a    #
###   #       #     ##     #     r #  b##             c #      #   a      ########   #      #   #  a  #  #   #     t     #
##       #     #     r    #     #       #               #      # b                   #      #   #     #  #   #           #
#         #                    #        t########       # ra   #                     #     r#   #######  #   #           #
#g                                       b      #    t  #      #                     #      #            ## ##           #
#           t    r                        r             #      #   g      r         t#      #                            #
#         #                    #                #       #      #                     #      ######## f         a##########
##       #     # t        #     #       ### ##  ####    ########                   cb#             #            #t       #
###   #       #     ##r    #       #   ###   #     #             c                   #       a                  #        #
##   #          f  #  #             #   ##   #     #            t     #####        b #             # f          #####   a#
#               #       b# b                 ####  #           f      #   #          #####         #####    af      #    #
#       #      #          #      #       # r    #  # g      a         #   #   a          #             #    g       A    #
#       #           ##           #       #  g   #  #   g     b    f   #   #            a # t           #            #    #
#       # #         ##         # #      t## ##  #  #     f  b        g#   ## ##   g      #       f t  a#     a t    ######
#     ######    #   ## g #    ######         #  #  ## ##              #       #          #####       b #####         t   #
#      # #     # t  ##    #     # #          #  #  a   #              #       #             a#             #       rl    #
#        #           f          #            #  #      #              #  l    #       r      #   a         #            a#
#        #  ####          ####  #            #  ## ##  #              #       #  g t         ## ##         ####      c   #
#     #                            #         #      #  #              #       #rl    g           #   fA       #          #
#    #      #    #   t  #    #      #     r  #      #t #r             ####    ######c            #                       #
#       #  #     #  ##  #     #  #     f     ## ##  #  #                 #         #            r#    t     a #          #
#      #      #  # #  # #  #      #   r          #  ####      b     r              # t  l        #####        ############
#             #            #b               rt   #r              l       #         ########c        r#                   #
#      ###                      ###        g     #        a       b      ######           #          #  g                #
#                   ##     l                t    #                     t      #                      #   bc   r     f    #
#            #              #                    #   r                        #           #          #                  f#
# #         #       ##  f   t#         # ## ##   ####       g              ####           #####      #      g     f      #
####              r#  # r             ####   #      #                      #                g #   a  #####               #
# #   #         f       f          #   # #   #   t  #         gb           #     t                       #       a       #
#    #   t       #      #b  r      l#    b   ####   #                      #             a    #           g  c           #
#    g       #  #        #  #                   #r  #                g     ## ##              ####       #f              #
#    ####    #              #    ####f         t#   #      r    t  t           #   b        t   t#     g #######         #
#          # #      ## t    # #f  t    g       l#####             r            #                 #             #         #
#r   #    #       t            #    #                            t             #      l         r#   f     a         a   #
#     #         #        #         #          r   g    f      b                #####             ## ##     b   #      g  #
#               ##      ##                             ra                 tt       #              g  #  a      ####      #
#     #  ##          ###     ##  ##           #              #####     ### ##             b      ## ###     #####  b     #
# #c  ##  ##          ##   r##  ##            #l  f ##       #   # # # ##         t ##  ##           ## # # #   #a      ##
###    ##  ##         ##   ##  ##  ####################      ### # # ###t    ##     ######     ##  a  ### # # ###   bb ###
##      ##  ##     #  ##   #  ###  ###  #   #   #   # # #  a b#    # #        #          b     #        # #    # r   #   #
#  ##    ## t#######  ##   #  #    ### r##          # #### l     b #####  ### ##    ##  ##    ## ###  #####         #### #
#  r##       #######  ##   #  #  #       #b  ##          #      ## ##  ## #l###  b  #    #     ### # ##  ## ##          a#
##          ##       #######  #  ##   A#######  #####   ##      ##          #   t   # ## #       #          ##      ##   #
##          #         ######  ##  ##   ####### l####    b## #        ## ##b ##                  ##  ## ##        #f##    #
##     b  #####        #     l ##  ##  #######    #   ##### #           ##          ##  ##       a  ##           # ##### #
##     b  #####    #####     #  ##  ## l  ######  ######      ##        #     ## ##  ####  ## ##     #        ##      ####
##   ######  ##  ###   #  t  ##      b    ####f##  ##         ##        a    ##  #   ####   #  ##             ##         #
##    #r      #  ###      c  #f   #    #######  ##  #        ##  # ####      #       #  #     b #  l   #### #  ##       b#
##         #####        ####   #####    #f       #         att#  #   ##  ###     ##        ##      ## l##   #  #         #
##      #   #   t       ####    #########        #         ## ## #####t  ##    #              #  l ##   ##### ## ##      #
##   a  ##      ############l   b#      #        #l        ##       #     ##  ## #          # ##  ##     #       ##     a#
##      ###      ###  #                 #  ##    #    # ## #  ###  ## ##  ##  ## ##        ## ##  ##  ## ##  ###  # ## # #
##      ####  f   #         ##   r   #  #   ##  ##t c #  #    ##    ####   l      l   ##             g####    ##    #  # #
###     l    ######    ###  ##  ##   # ###   ##  #       #  f         l    ######  ##    ##  # ####      #          #    #
# ##          #   #     ##      t##  # r     ###     g  ## #    ## ##a##     ##              b ##     ## ## ##    # ## b #
#  ##   #######        l ##   ##c #####      ##  l ##   #  #   ##  #  ##  ##  ###  ##    ##  ###  ## a##  #  ##   # l#a  #
#   #   #######      tt   ##  ##   ######    ##  # t#      l   # b # ##    #   ##  #      #  ##   #    ####   # r     l  #
#       #######            ##       #   #######  ## f   ##           #     # ###      ##      ### #     #           ##   #
#    ##         #       #   ##         l####### t#    # ##   #       r  #  ### # #    ##    # # ###  #          #   ## # #
#     ##       ##    ####    ##  f #    ###     ##  ###     ##      #  ##  ##    ##        ##    ##  ##  #b     ##   l ###
#      #  f   ###     ###f    ##   ##   ###     #  ###    ###   #  ##  ##  #     ##      l ##b    #  ##  ##  #   ###    ##
#   ###########       ####     ##   ########    #  #            ## ##  #   ###                  ###a  #  ## ##b          #
#    ##########  ##             ##   ########   #  # ###     a         ##           ######        t  ##               ####
#     #           ##b            ###  ####  #####  # # #    ##  # ## #        l      b##       l   ag b # ## #  ##    # ##
# l ###t           ##            ###   ###  #####  #     a# #  ####  # b   #             t    rr  #     #  ####  # #     #
#  b###        r    ##         r ###   ###  #  c  ##      # #  #### g#     #                   lb #     #  ####  # #     #
#   ##############   ##          ###   ###  #      # #a#    ##  # ## #              r ##  t          a r# ## #  ##    # ##
#       #  #######    ##           ##l      # #    #####               ##   g       ######           ##               ####
#t      #   ####      ###   ###    ###   t#####    ##          a## ##  #  l###                  ###   #  ## ##           #
##   ####    ###  t  #####   ## t  ########   #    ###    ###   #  ##l ##  #     ##        ##     #  ##  ##  #   ###    ##
###  ####     ##            at#  A ########     b  ####     ## bl   #  ##  ##    ##        ##l b ##  ##  #      ##  l  ###
####           #    b  r  ######      #               # ##   #     b    #  ### # #    ##    # # ### b#l         #   ## # #
#         ####### r       ###    ## t #       #         ## a l     a #       ###      ## a    # # #     #           ##   #
#      ####        ####   ###     ##  ##########               #   ####    #  a##  #      #  ##   #  gl####   #        b #
# #     ###        #### r #  f     ##  ######     c##   #  #   ##  #  ##  ##  ### a##    ##  ###  ##f ##    A##  b#  #bt #
# ##     ##        #             #  ##  #  ##   ####    ## #    ## ## ##   f ##  bb            ##   a ## ## ## l  # ##   #
#  ##b    #       f#       ####  ## b##    ##    #       #          #      #### #  ##    ##  ######   a  #b         #    #
#   #####         t#        ###  ###  ##  ###    t t  #t #    ##    ####              ##l       a     ####    ##    #a #l#
#  t ####   #   ######       ## r##  f###         # c # ## #  ###  ## ##  ##  ## ##        ## ##  ##  ## ##  ###  #a## # #
#     ########t #    ##    #r #####  #####        #   a    ##       #     ##  ## #        a # ##  ##  a  #      t##      #
#l     ########      ###  ##          #####  ####  ##l     ## ## #####   ##    #   b          #    ##a  #####a##l##      #
#       ########    t####  #       #   ###    ###   #   g     #  #   ##  ###     ##        ##     ###  ##  a# a#f        #
#       #########    #       ########  ###    ###            ##  # ####f     #       #  #       #    b ## # #  ##        #
#    t  ####    #######  ##   #       ## f ######             ##             ##b #   ####   #  ##    t        ##         #
#       ####   l #######  ##  #             #####    ###      ##        #     ## ##  ####  ## ##     #c   l   ##      ## #
#     r           #####    #### r     f        t      ##### #           ##          ##  ##      g   ##  a        # ## ## #
#f         #####   ####     ###   ############g     #    ## #        ## ##  ##                  ##  ## ##       f# ##   a#
#      b     l#     #        ##    #         #          ##      ##   r      #       # ## #       # a      r ##      ##   #
# #        #  #     f      f  #            b ##tg        #      ## ##  ## # ###    A#   b#     ### # ##  ##l##      #    #
###        #  ######       #######       #   ###      ####bl       #####  ### ##    ##  ##    ## ###  #####         #### #
###        #   #####        #   #  t     ##    #      # #    a#      #a       #l               #A   t   #      #  A  # # #
###        #    ####  #     #            #    #########      ### # # ###    g## ba  ######     ##    r### # # ###   b  ###
### ########r    ###  ##    #    #  #### ###     ##### g     #   # ### ##           ##  ## a            ### #   #       ##
#          #  # f      #######b  ##  ###   ##     ###l       #####     ### ##                 a  ## ###  ga #####        #
##########################################################################################################################
