metadata:
  gen_time: 9.280349969863892
  timestamp: '2025-04-18T22:49:04.254499'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# #                f                                      #    #  ### r ### b# t ########  #########       ####   a  #####
# #      # ###    ##                     ##    ### #  t   #   ###           ##   #######   #########      ####  l g   ####
#     ## #####  #    ##     #   #     ##    #  #####g##         # A  ###    # l   #####    #########     ####          ###
#     ##             ## ### f     ### ##  l       f  ##  f  ##                  #  ### g    #######     ####  a          #
#      #      ##    f         f b            ##      #       ###  # # c # #  ##                        ####              #
#      # ##   ### #           t           # ###   ## #        #   ###   ###  r#        a##            ####  g ######     #
#c     #    #     #    t #         #      #     #t   #       ##               ##       ####          ####    ########    #
# ##        #t    #     ##   # #   ##     #     #        ##  #   ##       ##   # ##    ####         ####     ######### g #
#                 # # ###    # #    ### # # t               ###     ## ##     #####    ####        ####       #########  #
#               t   #      g ###    A   #       f             ##             ##        ####       ####A  b     ########  #
#         #######       l    ###            #######         #  #      #      #  ####   ####      ####     ##    ######   #
#     ## #####b   l      b   ###               ##### ##     #### l           #######    ###     ####     ####            #
#   ####    #    #       ##  ### f##       #    #c   ####    #   # ### ### #   # ##     ###    ####      #####           #
#  l####      ##         ##       ##         ##      ####        #r  ###   #         f  ##  g ####       ######    a##   #
#l  #                    ###  l  ###                    #  t     ### ###b###        f        ####         #####b   ####  #
#   #    #c##       ##   #         #   ##   g   ## #    # l        #     #           f      ####     l     ###    #####  #
#   # l  # ##g      #    #  g      #l   #    l  ## #    #   # g  ###     ###    ##         ####    ###            ####  b#
#   #   ##  ###     ##   #         #c  ##     ###  ##   #       ##         ##  r #        ####b   #####     f      ##    #
#    f ###    #                           tt  #    ###             #     #        b      ####     #####    ##            #
#   ##                  ##         ## g l              ##    ###   #     #   ###        ####    b  ###    ####b     b    #
###               r    t #         #                      #####      # #      ####g     ###           f   #####   a###   #
###     ####          ## #         ####          ####     ##       ### ###       #    # ##a  f            ######  #####  #
#       ####t ##      ## #  f      ####      ##  ####       ##      #   #      ## A  ## #      l   ##      #####  #####  #
##      ####   l  #          g    t       # r    ####      # ##               ## #    # ##            g   ######  #####  #
# ######             ###    r       #####  ######    ####### #    ## f#  ##    # #   f  ###               #####    ###   #
# #####      ###    #### #           ####  ######   ######## ##   #       #   ##        ####       ###    ####           #
#   ##      #####  ##### #     ## l   ##    ####   #########          #                  ####a    #####    ##          a #
#f  #      ######  ##### #    ####               t ########     r                #        ####    #####  a  l      ##g t #
# l    f   ##### r ##### #    ##### f               ######       ###     ###     #         ####g   ###            ####   #
#   l       ###     #### #    #####       ###   rg   ####    ### #         # ###            ####           ###    #####  #
#                    ### #    #### t     #####     r  ##     #l# ## ##### ## # #f    f       ####         #####    ####  #
# l    ###        f   ##       ##      t #####               #   ## ## ## ##   #        ##r  g####       ######     ##   #
#     #####                               ###                ##  #  #   #  #  ## ##     ###    ####   b  #####           #
#     #####               g   r    ####         ##     ## f      ##     r ##     ###    ###     ####     ####         a  #
#     #####   ###      r    ##r   ######       ####  t####        # ##### #      ####   ###      ####     ##    ######   #
#     #####       b                ####         ##l    ##        ## ## ## ##     #### b ###  b    ####  b  g   ########  #
#     #####                           g t ###   l               ## l#   #  ##    ###    ###        ####       #########  #
#   t  ### f          ##       ##        #####                   # ##   ## #  l  ##   b ###         ####    b#########  l#
#               l t  ### #r   ####       #####        ##       ### #     # ###     g    ###        g ####    ########    #
# f         ###     #### # l  #####r      ###        ####   # ##   # ### #   ## #       ##      b    A####    ######     #
#      g   #####   ##### #    #####    f           l######  ######     #  t######                      ####              #
#   #      ######  ##### #    ####    g          l ######## # f       ##    r   #  ###      #######     #### l   gga     #
# # ##      #####l ##### #     ##  l  ##    #### f #########  ##    #  ##    ##   #####    #########     ####          ###
# # ###  t   ###    #### #  f        ####  ######   ########  ##             ##  ######    #########    f ####        ####
# # ####             ###            #####  ######    #######   #   ## #l##   #   ###### #  #########       ####      #####
##  # ### ## ### ##   a# #####      #######b   ## ###l##g### ## #  #  # #   # # # g#r   # #    # #    #  # # #   # #  #r #
#   # ###b## ### #   l # ##################     # ### ## ### ##   ###   #f### # # ### # # # ## # ### ### # # ###b# # ### #
##  # ### ##    l##a   # ##################    ## lrf ## ### ## # # #  ## ### # # # # # # # ## # ### # # # # ### ### # # #
##  # ### ##  #  ### ##                    ## ### ##  ## ### ## # # #  #t   # # # # #   f    b b   # # # # # #         # #
##    ### ##    f######b ## ####b #### ##  ## ### ##g ## ###    # # # ### # # # #   #t  # ###### # # #   # # # # # # # # #
##  f ###     ##      a  ## ####  #### ##         ##     ###b   # #   # # # # # # # #   #        # # # ### # # # #     # #
##  # ###   # ##     ##     ##      ##   ####   f ## ### ### ##g#  #  # # #     # # # # # # ## #t# # # ###     # #    #  #
##  #l### ### ##     ##     ##      ##   ####     ## ### ### ## # ### #  f# # #b#         # ## # #   #   #  ## #   # ### #
##  #  l  ### #### ##    ## ## #### ## ##     # #### ###     ## # # #   ### # # # #   # # # ##   # ### # #  f# ### # # # #
#f  # ##  ### #### ##    ## ## #### ## ##     # #### ###  ## ##   # # #g### # # # # #   ### #   ## ### # # # # ### # # # #
#b  # ##         l ##    ##  b         ##     #        l  ## ##  ## # # #   #     #             #  #   #     #  b# # # # #
##    ### ##          r         ##     b             r## ###   ###    # # # # # ### # # ### ## ### # # ### ### # # #     #
###   ### ###b###r#####  ##### #### ######### ##a### ### ###   #### # # # # # #f### # #   # ## #r# # # ### ### # # ##  # #
###   ### #############  #################### ########## ###   ## # # # # # #     # # # # # l  # # #g# #     # # #     # #
### l        f                             t                 r ## # #   # # # # # # # # #b# ## # # #r# # # # # # #   #   #
#r  # ##  # ## a### ###  #  r###  ###   ####   ###  ## #  #####b  #   #f# # # # # # # # # #t## # # # # # # # # # # #     #
#   # ##  # ##  ### ###  #   ########   ####   ###  ## # ######   ##  # # # # # # ### # # #    # # # ### # # # # #   ### #
##        r ##  ### ##    l  ########          ###  ##      l  ## a#  #     # #  bf#  #   # ## #   #  #    # #        #  #
###    ## a ##      ##   ####        #####    b     ##t  ##    ## ##  ### ### ### ### # ### ## ###t# ### # # ### #   ### #
### ## ## #### ###  ##   ####  ####  #####      ### #### ## ## ##     ### ### ###   # # ### ## ### # # # # # ### # # # # #
### ## ## #### ###  ##   ####  ####  #####a     ### #### ## ##r## # # ### ### ### # # # ### ## ### # # #b# # ### # #   # #
###    ##   ##      ##   ####        #####          ##   ##    ## ### ### ### ### ### # ### ## ### # # # # #r### #   ### #
###  f l    ##  ###b##       # ######          ###  ## l    f  ##f    #     # #    #  #   # ## #   #         #        #  #
#   ####### ##  ### ###  # l # ######   ####   ###  ## # ######   ### # # # # # # ### # # #    #   # ### # # # # #  f    #
#  ##### ## ##  ### ###  #   # #  ###   ####   ### b## #  #####b    # # #t# # # #g# # # # #A## # # # # # # # # # # #t  #t#
###         g  a            a        r                    b    ## # #   # # # # # # # # # # ## # # # # # # # # #g#    g# #
###   ########### #####  ##### #############  ########## ###   ## # ### # # #     # # # # #    # # # # #   t # # #       #
### f ####### ### #####  ##### #### ########  ## ### ### ### g #### ### # # ### ### # # #r# ## #b# # # ### ### # # ### ###
###   ######       b         g  ##  l   l            c## ###   ###    # # # ### ### # # ### ## ### # # ### ### # #      ##
# b## ##           ##    ##            ##    ##           ## ##  ## # # #   #     #   #  #  ##  #  #   #     #   #   # ###
#  ## ##  ### #### ##    ## ## #### ## ##f  c## #### ###  ## ##   # # # ### # # # # ### ### ## ### ###t#g# # # ### # # # #
## ##    r### #### ##    ## ## #### ## ##A   ## #### ###     ## # # # #t### # # # #l### # # ## #   ### # # # # ### # # # #
## ## ### ### ##     ####   ##    a ##   ####     ##l### ### ## # ### #   # ### # a #   # # ## # #       # ### #   # ### #
## ## ### ### ##     ####   ##      ##a b####     ## ### ### ## #  #  # # #  #  ### # #f# # ## #b# # # ###  #  # # #  #  #
##    ###  l  ##         ## ####  #### A#         ##     ###    # ### # # # ### ### # # #        # # # ### ### # # #g### #
## r  ### ##  ## ######  ## ####  ####l##  ###### ##  ## ###r   # #   ### # # # #   # # #r######f# # #   # # # # #     # #
## ## ### ##  ## ### ## b                  ## ### ##  ## ### ## # # #  #    # # # # # #       t  b # # # # # #r      # # #
## ## ### ## a   ##  c ####################    ##     ## ### ## # # # ### ### # # #t# ### # ##   ### # #t# # ### ### #f# #
#  ## ### ## ### #     ####################     # ### ## ### ##   ### # # ### # # ### ### # ## # ### ### # # ###   # ### #
## ## ### ## ### ##  a #######      #######    ## ### ## ### ## #  #  # #   # # #  #    # #  f #f# b b#  # # #   #t#  #  #
###    r   #            ##      #      l      l       ##       ###                   ####    b       ##      t  #####   ##
######             t    #                             ##      ###     #            #######    ##      ##        ##  ######
#   ###    ##    b #   ##          b  b               ##     ###      #b          ## r   #     ##     ###   g  ##    ### #
#   t##    ### t   ##  #               #  ##          ##           r           ##r         #   ##       ##      t      b #
# b   #     ###    ##               ##    ###   b     ##          f  ##        ##          #         #   ####            #
#             ##                    ##      #         ##     t       ##   r    ##  ##                #b    ###   g    ## #
#              #     ##             ##                ##     ##       #b  b     #                     #     ###  t    ## #
#   b          ##    ##     l       ##                        ## #                          b   ##     f    t          ###
#        ##  #  ##  ##          ##   ##         ##               ###     ##  #  f A                                 b  ###
#b       ##     r#  ##          ##   ##  #      ##                ###      ##                       r    #  f   #       ##
##       ##         ##     #         ##  ##     ##         ##      ###          c          c  r##    g    #           c  #
###      ##          #     ##     #   ##  ###   ##          ##       #     #                   ##         #    b    r  r #
####     ##       t  ##    ##     #   ##   ###   ##         ##    #        #                    #  l  f    #             #
# ###     #          ##                     ##   ##          #    #   ##    #   b         #         #               ##   #
#   ##              ##     #               b  b   ## b   b   ##       ##    #       #     #         ##         ##  ##   ##
#                        r ##             ##      ##         ##       ##      #     ##      c        ##                 ##
#     ###                   ##   #  #      ###    ##          ##      #             ###             b #      f          ##
#      #### b    ##    g    ##      ##       ##    ##         ##   ##                #####     #  t   ##                ##
#         ##     ##            ##    ##                        ##  ##                  ####    #       ####             ##
#  ##      #    ##  #          ##    ##                gf               #       #         ##   r#        ###         ##  #
####                ##          ##   ##  b   ##           ##                   r##         ##   # b       t####      ##  #
##                  ##  c       ##   ##      ###          #####       ##        ##          ##              ##  r    ##  #
#          c        ##           #   ##    g                 ##        ##        #          ##      b                 ## #
#        b        g ##           ##  ##     g        f        ##        #        ##  b      ##        r      b##       # #
#      #     b      ##      A  g ##g ##                 f     ##        g        ###        ##      ###        ###c    ###
#     g                          ##  g#                                           ####      #       ###   ##    ##   #  ##
#                     b           #                    #                            ##    #                ##           ##
#             ###      c          ##b                   ##        r          #       ##      ##             ##    #   #  #
#   ##         ##    ##           ###          c##                           ##      ###r    ##             ### g     #  #
#    ##   b     #   ##                           ##       ##         ##       ##      ###     ##             f##         #
#                   ##                                      #  f##     ##     ##        ##    ##                     ##  #
#   g     ##g     g  #                    ##   ##               ###      ##   ##         # cg  ##                  c  ####
#            b                            ##   ##                ##        #             ##    ##                      ###
# #                                #      #                      g#             #         ##b   #             #        b##
# # #                              ##                  #          ##            #         ##    ##            ##        ##
##########################################################################################################################
