metadata:
  gen_time: 6.167025804519653
  timestamp: '2025-04-11T22:28:33.362805'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '

---
######################################################################################################
# ###    ###   ##     #####        ######       ###   #####          ###    ##     #####      #####  #
#                    ######        ######      ####  ######                        ######    ######  #
#                    ######         ####      #####  ######     ##                 #######   ######  #
#   ##        ##     ######                   #####  ######    ####                 ######   ######  #
#  ####      ####    ######                   #####  #####    ######                 #####   ######  #
# #####     #####    ######   #############   #####  ####    #######    #######       ###    ######  #
# #####    ######    ######  ###############  #####   ##    ########   #########             ######  #
#  ###    #######    ######  ###############  #####        #########   #########             #####   #
#        ########     ####   ##############   ####        #########    ########      ####     ###    #
#       #########             ############     ##        #########     #######      ######          ##
#       #########                                       #########      ######      ########         ##
#       #########                                      #########       #####      ##########        ##
#       #########    ##      ###           #####       ########         ###      ###########        ##
# ###    #######    ####    #####         #######      #######                   ###########        ##
######             #####    ######        #######      ######                     #########         ##
######            #####      ######       #######       ####       ###                               #
######            ####        ######      ######                  #####                              #
######             ##          ######      ####                  ######                    ##        #
######                  ##      ######                 ##       ######                    ####       #
# ####        ###      ####      ######               ####     ######                     #####      #
#  ##        #####    #####       ######              #####   ######             ###      ######     #
#            ######   #####        #####      ##      ######  #####    ###      #####     #######    #
#             ######  #####         ###      ####     ######  ####    #####     #####      ######   ##
#              #####  ####                   #####    ######   ##    ######     #####       ####    ##
#  ####         ####   ##                    ######    #####        #######      ###                 #
# ######   ##    ##           ############   #######    ###         #######            ###           #
########  ####               ##############  ########          ##   #######           #####          #
########  #####              ##############  ########         ####   #####           #######     #####
########   #####             ##############  ########        #####                  #########   ######
########    #####       ##    #############  #######        #####                  ###########  ######
########     #####     ####    ###########   ######        #####                  ############   #####
########      #####    #####    #########    #####        #####         ##        ############       #
#######        #####   #####     #######      ###        #####         ####       ############       #
######          #####   ###       #####                 #####          #####      ###########        #
#                ####              ###                 #####           #####       #########    ###  #
#                 ##                     ##           #####            #####        #######    ##### #
#                              ##       ####         #####    #####    #####                  ########
#                             ####     ######       #####    #######    ###     ##           #########
##                            #####   #######      #####    #########          ####          #########
##              ########      #####  ########     #####    ###########         #####          ########
##             ##########      ###   #######     #####    ############         ######                #
##            ###########            ######     #####    #############         #######               #
##   ####     ###########            #####     #####    ##############    ##   #######     ##     ####
#   ######     #########             ####     #####     #############    ####  #######    ####   #####
#   #######                #######    ##     #####      ############    #####   #####    #####   #####
##  ########              #########         #####       ###########    ######           ######   #####
##  #########             #########         ####         #########     #####           #######   #####
#   ##########             ########          ##           #######       ###     ##    ########    ####
#   ###########             #######                        #####               ####   ########       #
#   ############             ######    ##                   ###    ###        #####   ########       #
#   #############     ####    #####   ####                        #####      ######   ########   #####
#   #############    ######    ####   ####                       #######     #####    ########  ######
#   ############    #######     ##    ####       ########       #########    ####     ########  ######
##  ###########    ########           ####      ##########     ##########     ##       #######  ######
##  ##########    #########            ##       ###########   ###########               ######  ######
##  #########    ##########      ###            ###########  ############                #####  #### #
##  ########     ##########     #####            #########   ############       ####      ####   ##  #
##  #######      ##########     ######                       ############      ######      ##        #
##  ######        #########     #######     ###               ###########      ######                #
#   #####          ########     #######    #####       ####    #########        #####           ##   #
#   ####            ######      #######    #####      ######    #######          ####     ##   ####  #
#    ##     ####                ######      ####      ######     #####     ##     ##     ####  ####  #
##         ######               #####        ##        #####      ###     ####          #####  ####  #
###       ########   #######    ####                    ####              #####        ######  ####  #
###       ########  #########    ##    ####              ##               #####        ######  ####  #
##         ######   ##########        ######                              #####        #####    ##   #
#                   ###########       ######    ###              ######   ####         ####          #
#                   ###########       #####    #####            ########   ##           ##           #
# ######    ####    ###########       ####    #######           ########        ##                   #
#########  ######   ##########         ##     ########          #######        ####         ######   #
#########  ######   #########                 #########          #####         ####        ########  #
# #######  ######   ########                  ##########          ###    ###    ##         ######### #
#  ######  ######   #######    #####          ###########               #####               ##########
#   #####   #####   ######    #######         ############    ##       ######       ####     #########
#    ####    ###    #####     ########         ############  ####     #######      ######     ###### #
#     ##            ####       ########         ###########  ####    #######       ######      ####  #
#                    ##         #######   ##     ##########   ##    #######        ######            #
#                                #####   ####     #########         ######         ######            #
#   ###                           ###    ####      ########         #####          #####       ###   #
#  #####         ####                     ##        #######         ####           ####       #####  #
#  #####        ######   #######                     #####           ##             ##       ####### #
#   ###        #######  #########              ###                                           #########
#             ########  ##########            #####            ###       ######              #########
#             ########   ##########          #######          #####     ########              ###### #
##    ###     ########    ##########         ########    ##   #####    #########      ##             #
###  #####     ######      ##########        #########  ####   ###    #########      ####            #
###  ######     ####        ##########       #########  ####         #########       ####            #
###   ######                 ##########      #########  ####        #########         ##             #
###    ######                 #########      #########  ####       #########                         #
###     #####         #####    ########      ########   ####       ########                       ## #
###      ####        #######    ######       #######    ####       #######                       #####
###       ##        ########     ####        ######     ####        #####     ###############    #####
##                  ########                 #####       ##    ##    ###     #################    ####
#                   ########                 ####             ####           ##################    ###
#                   ########     ####         ##             #####           ###################    ##
############        ########    ######                       ####             ###################    #
#############        #######    ######                        ##               ##################    #
#############         #####     ######           #########               ###    #################    #
############     ##    ###      ######     ##   ###########             #####    ################    #
###########     ####            ######    ####  ###########             ######    ##############     #
######################################################################################################
