metadata:
  gen_time: 3.6970207691192627
  timestamp: '2025-04-18T22:59:36.369824'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#                    #     #  #  #  #  #      l    #                    ##      ##           ##      ##             g    #
#    g               #     #  #  #  # f#           #                    ## c    ##          g##    l ##          l       #
##########  ##########  ####  #  #l #  ####  #### t#  ####  ##############  ######  #######  ######  ############## b#####
#  #         g     g #        #        #     #  #     ####  ##############  ######  #######  ######  ##############  #####
#  #                 #        #        #     #  #         f ##  ##f             ##           ##              ##  ##a     #
#l #######  #  #  #  ####  ####  ####  ####  #  ####        ##  ##              ##           ##       c      ##  ##      #
#     #     #  #  #     #  #  #  #     b    a#  #  r    ######  ##########  ##  ##A #######  ## f##  ##########  ######  #
#     # l   #  #f #     #  #  #  #           #  #      b######  ##########  ##  ##  #######  ##  ##  ##########  ######  #
#  #  #  # ##############  #  ################  ####        ##  ##c         ##  ##           ##  ##          ##  ##      #
#  #     #  #     #  #  #     #     #       f               ##  ##          ##  ##           ##  ##          ##  ##      #
#  #  c  #  #     #  #  #     #     #                   ######  ##  ##############  ##   ##  ##############  ##  ######  #
#  #######  #  #  #  #  #  #######  ####  ##########    ######  ##  ##############  ##   ##  ##############  ##  ######  #
#        #     #              #           #                 ##                  ##  ##   ##  ##           c      ##  c   #
#        # l   #      t       #  g        #        Alb      ## t            c   ##  ##   ##  ##                  ##      #
#  ################  ##########  #######r ##########    ##########  ##  ###### f###### g ######  ######  ##  ##########  #
#           #    b               #        #  #          ########## g##  ######  ######   ######  ######  ##  ########## l#
#           #                    #    t b #  #          ## l##  ##  ##      ##  ##     a     ##  ##      ##  ##  ##  ##  #
####  #  #     ####  ####  #  #######  ####  #  #  ###  ##  ##  ##  ##      ## l## g      c  ##  ##      ##  ##f ##  ##  #
#     #  #    r#  #     #  #  # l         #  r  #       ##  ##  ##  ##########  ##  #######  ## f##########t ##  ##  ## b#
#c    #        #  #  f  #  #  #           #     #       ##  ##  ##  ##########  ##A #######  ##  ##########c ##  ## l## g#
#  #  ###   #  #  #  ####  #############  #  #########  ##f         ##     f        ##   ##              ##      f   ##  #
#  #              #  #                 #  #  l          ##          ##              ##   ##    c   l     ##          ## l#
#  #              #b #        b        #  #             ##  ##########  ######  ######   ######  ######  ##########  ##  #
#  # l            #  #                 #  #         l   ##  ##########  ######  ######   ######  ######  ##########  ##  #
######    #######       ###  ###  ###     # #####   #r         l    ##  ##  g             l    f     ##  ##     c        #
#t####   ###            ###  ###  ###  #  # #####                   ##  ##                           ##  ##          c   #
##a##   ###            ####  ###  ###     # ##### # ##  b           ##  ##                           ##  ##              #
######g                ####  ###  ###  #    ##########c             ##  ##       c       g           ##g ##              #
####### #         f  # ####  ###  ###  ##   ##########              ##  ## f                         ##  ##              #
############# l# ## ##  ###  ###  ###  #r   #####                   ##  ##  ct       c   c       t   ## t##             c#
####c########       ## ####  ###  ###  ##   ######t###            tl##  ##     f        l            ##  ##        b     #
#####a########    # ## ####  ###  ##t  ### ######r####              ##  ##  f l       l             g##  ##              #
###  #### #####  #  ## ####  ###  ###  ###########      t           ##  ##                           ##  ##            c #
###   ###  ###     #g# ####  ###  ###  ############     ##  ##########  ######  ######   ######  ######  ##########  ##  #
#   ##  #   ###  ####a ##### ###  ###  ###########      ##  ##########  ######  ######   ######  ######  ##########  ##  #
##    # #   ##  ####g# ####l ###  #### ############     ##  l       ##           g  ##f  ##              ##          ##  #
##   #a #   ###a#####  ##### #### ##################    ##b         ##A     l       ##   ##              ##      f   ##  #
##  ### #   a# ####### ######a##r###########a#a####a##  ##  ##  ##  ##########  ##f #######  ##  ##########  ##  ##  ##  #
##  ##t     ##  #####c ####  #### ##################a#  ##  ##  ##  ##########  ##  #######  ##l ########## f##  ##  ##  #
##  # #     ##   ###l# #### ####  ####a############   g ##  ##  ##  ##    c ##  ##           ##  ##l     ##  ##  ##  ##  #
#g  # l     ## g ####g ####  ###  ### ############      ##  ##  ##  ##      ##  ##           ##  ##      ##  ##  ##  ##  #
##    ##    ## # ### # ####  ###  ###  ############     ##########  ##  ######  ######   ###### l######c ##  ##########  #
##    ###   ##   ##  # ####  ###  ###  ###########b###  ##########  ##  ######  ######   ######  ######  ##  ##########g #
##    ###   ## # ##  # #### ####  #    ### ######           ##b  g     g        ##  ##   ##  ##                  ##      #
##    ###   #b # ##  # #### ####  # #  ##   ######          ##                  ##  ##   ## t##               c  ##      #
##    ###   ## # ##  #  ### ####  # #  #    #####r####  ######  ##  ##############  ## c ##  ##############  ##  ######g #
##    #c#      # #   # #### ####  # #  #    ##########  ######  ## g##############r ##   ##  ##############  ##  ######  #
##   #       # # #     #### ####  # #  #    ##########      ##  ##          ##c ##           ##  ##          ##  ##      #
##   t#      # # #   # #### ####  # #       #####c#         ##  ##          ##  ##          r##  ##          ##  ##      #
#t     #     # # #   # l### b###  # #       ###### # #  ######  ##########c ##  ##  #######  ##  ##  ##########  ######  #
##    #l     # # #   # #### ####  # #       ###### # b  ######  ##########  ##  ##  #######  ##  ##  ##########  ###### l#
##   ###     f #              ##    #                       ##  ##       l      ##           ##          g   ##g ##      #
#   #####      a    ##    a        # t t                    ##  ##             g##           ##              ##  ##      #
#     ##            ##   ##       #                   ####  ##############  ###### c#######  ######  ##############  #####
##                   a   ##     ##                    ####  ##############  ######  #######  ######g ##############  #####
#### l    a  ##                 ##     r                 a              ##      ##           ##lg    ##  c     c         #
####    g  ######  ##            #         t                     l   l  ##      ##           ##   r  ##     b           g#
###       #############   f      #     ##        l A   #  g l   b      ### ####### # ########    ##  ##  #   ##    ##    #
#  f     ####  #########     ##      b  #       r ##  ##             t ##          #       ##    ##   #A ##  #     #     #
#        ###     ## c####    ##         #          #  ##           g   ##  t       #       #     ##  ##  ##  ##    ##    #
### t  l####         r### r          l  ##         #   #               ##     t          l ##    ##  ##   #  ##    ##    #
####  #######t         ###       t   g  #          #  ##               ##          #             ##  ##  ##  ##    ##    #
####  #######   ##     ###              #  #    g  # ###### #####  ## ############ #####  ### #  ######  ##  ## #  ## #  #
###    ####     ##      ###    f        #######  r #  ##### #####  ############### ##### #### #  ######  ##  ## #  ## #  #
###     ##              #####                 #    ####  ##  ##               ##    ##    ##  #    ##     #     #   #    #
##   a                   ######  #                       #   ##t l     tr     ##     #    ##  #     #     #     #   #    #
#       r          ##      #######  f   f             #  ##  ##               ##    ##     #  # l  ##    f#     #   # c  #
#              b ####        #####  #             f   #  ##   #            A   #    ##    ##  #    ##     #     #   #    #
#   ##     ##    #####      f  ##  ##   g# ##### ##   #  ##  ##      r     r b##    ##    ##  #    ##     #     #   #    #
#  a##    #####   ####           t#      #  #  #  # A ############ ##### ############### ###### #######  ## ### #  ## ## #
#         #####  l#####   ##fg           # #    # #  b############ ############## ############# # #####  ## ### #  ## ## #
# r        ###   ######a  ##  ##         ##      ##         ##  ##  ##                              ##   ##  ##     g ## #
# ##       ##    #####        ##         #        #   #t        ##t ##                              ##   ## a##       ## #
#####g    ###      ##                    #        ## l## ## ############### ######### ######### #######  ########  ## ####
#####f  ######  g        ##              #            ##### ############### ## ################ ## ####  ########  ## ####
####   ######## f      ##### a  ##      b# #                      ##    ##        ##     ##        t ##     ##     ##    #
####   ########   ## a ######   ##       #  #               ##    ##    ##      t ##     ##          ##    r##   l ##g   #
##g     ########  ##   f#####         t  #########    ## ###### #### ###### #######  ######## ##########  ####     ##    #
#    r   f######         ##      f        f   #  #    ############## ###### ###     ###############t##### ######## #######
#           ##            f    ##             b t#        ##           ##       #        ##     ##          #### # #######
#                            #####  #           ##        ##           ##    t  #        ##    l##        t ##t    #    ##
#  ##       f     g        ##########            #    # #### ####### #####  ## ## #########     ##          ##     #    ##
# #####   t##      r       ####  ##  t           ##          ###         g                  a   ###       ###            #
# #######  ##         ##    ##           t           t      r###r    g                          ###     r ###t           #
#  ######           #####   ##        g  l        r     ###  ###  #############  ### #### a#############  ###  ###  ###  #
#    ## a       ## g#####  ####        ##               ###  ###  ############# r### ####  ############# f###  ### g###  #
#          ##   ##  t##    ####         #      #  l   g ###  ###  #############  ### ####  #############  ###  ###  ###  #
#    r     ##          f    ####   l    #    b ####     ###     g     f###    g       ###   b                g ###  ### t#
### f                       ####r      r##   f    #     ###            ###       b  b ###    r                 ###  ###  #
###    ##      ##          ####         #               ###r ######### ### g###  #############  #############  ### ####  #
####  ###     #####      #####          #  #      g     ###  ######### ###  ###  #############gf#############  ### ####  #
##########    #####  ##  ##### a #      ####### ##      ###  ######### ###  ###  #############  #############  ### ####  #
##########      ##   ##   #####  #     f   fg #  #f   g ###  ###            ###  ### f          ###            ###       #
#  ##  ####       a        ####    f           # #     l###  ###        t   ###  ###     r      ###            ###       #
#       #####               ##      f           ##      #############  ########  ###  ##################r ########  ######
#        ######  ##                 r  g         #      #############  ########  ###  ##################  ########  ######
##  ##   r ##########         l ##               #      #############  ########  ###  ##################  ########  ######
##  ##       #########     a a####               ##     ### g###  ###       ###       ###       ###g           ###    t  #
#             a##  #####    l ######               #  f ###  ###  ###  ###bt###       ### r  t  ###t  t        ###       #
#        ##         ####  ##    ## #             #  #   ###  ###  ###  ###gb########  ###  ###  ########  ########  ######
#  r ##  ##      a  ##    ##     # ## ##         #####  ###  ###  ###  ###  ########  ###  ###  ########  ########  ######
###r ## a       ##       f          r  #           t    ### b###  ###  ###  ########  ###  ###  ########  ########  ######
###    f      ####    r                ##               ###        t        ###  ###b      ###g ###       ###            #
#     g   ##  #####      ##     g     f#    g           ### r               ###  ###  t    ###  ###       ###           t#
#         ##   ####    #####           #  #             ##################  ###  ###  ###  ########  ############# #######
#g   ##        ##g     #####           #######     ### f##################  ###  ###  ###  ########  ############# #######
#  #####                ##     ##            #     #    ##################r ###  ###  ###  ########  ############# #######
#  #####   ##      ##  f      ####  g c            # #t               b          ###  ### A###  ###t ###       ###  t    #
#   #####  ##    #####      ######                 ##    f    t     t            ###  ###  ###  ###  ###       ###  l    #
#   #####       a#####     #####                   #    ###  ########  ########  #############  ###  ###  #############g #
#  #####          ###     ##### r f   ##           #    ###  ########  ########  #############  ###  ###  #############A #
#r#####           ##     ####         #  r         ##   ###  ########  ########  #############  ###  ###  #############  #
# #####    ##    ###   #####          #            # #  ###  ### l          ###  ###  ### t###       ###  ###  ###       #
#   ##   ######  ####  ####           ##   r       #    ###  ###            ###g ###  ###  ###       ###  ###  ###       #
#       t######   ###    ##      r                 ###  ##################  ###  ###  ###  ########  ### l###  ###  ######
#       r ####    ##             a                      ##################  ###  ###  ###  ########  ###  ###  ###  ######
#  ##     ####       f                                  ################## b###  ###  ###t ########  ###  ###  ###  ######
# ####     ##r         ##      ##                         t         f  ###  ###       b    ###                           #
########t  ##   ## g  #####  #### g                     g         g    ###  ###  g         ###            t    g         #
########    r  ####   #####  #############      g                     r###t ###            ###                           #
##########################################################################################################################
