metadata:
  gen_time: 7.802355051040649
  timestamp: '2025-04-18T22:52:43.941174'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#                                                            ##  #####  ##  #####   ##############   #####  ##  ##### t###
#                                                   t        #    ###       #### f  ##############  l ####       ###    ##
#        b                                                                   ##f    ##############     ##                #
## # # # # # # # # # # # # # # # # # # # # # # #b# # # # # #                  l      ############  f               f     #
#############################################################                                                            #
#############################################################              ###   f                      ###          a  a#
## # # # # #t# # # # # # # # # # # # # # # # # # # # #   # # #######     l#####   ########  ########   #####      ########
#                                              t        b    ########    f#####  ####################  #####     #########
#                     b   b                                   #######      ####  ####################  ####   r  ####### #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  #####        ##    ########  ########    ##        #####  #
####################### ######### ###########################     t    ##      A   ######    ######          ##          #
####################### ######### ###########################         ####        f ####      ####          ####         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # ###       ####    l      ##        ##     f     ####  f    ###
#                       r        l                           ###l      ##                 ##    l    l       ##       ####
#     b                  l     g                             ###                         ####                 a       ####
#                                                   g        ##         b       ###      ####      ###                 ###
# # #t# # # # # # # # # # # # # # # # # # # # # # # # # # # #b     ###         #####     ####     #####t       r###   b  #
#############################################################    t#####       ####### l  ####    #######       #####     #
######################################################            ######      ########    ##    ########      ######     #
## # # # # # # # # # # # # # # # #A# #g# # # # # # # # # # # #    #######     #########        #########   r #######    ##
#                          b                          g      ##   ########    ##########      ##########    ########   ###
#                   f        t                 g            t###  #########   ###########    ###########   #########  ####
#          b          l                      b          t    ###  ##########   ##########    ##########   ##########  ####
#  b                                                         ###  a#########    ########      ########    #########   ####
#             b                                              ###    #######     l                          #######    ####
## # # # # # # # # # #g# # # # # # # # # # # # # # # # # # # ##                                l                       ###
############## ############################# #################        f t f             ##l ##              r           ##
############## ############################# ################            ##      ##  rl########    ##  f   ##            #
## # # #r#f# # #t# #f# # # # # # # #l# # # #   # # # # # # #            ####  f ####   ########   ####    ####           #
#                            g       l        g              #          #####  #####   ########   #####  #####          ##
#      ##  a l  ###   ##         a ###   ##    ####      ####     ##  ###            ##  b     ##  g         ###  ##     #
#                ##               ### a #####  ##        l###    ##   ####           ##        ##           ####r  ##  b #
# ##           a                 ####   #####              ##   ###      ###      t  ##        ##      a  ###      ###   #
#####          b      ##     ##  ### a    ##   b    ## t    #   ##   #     ##   #    ##        ##    #   ##     #   ##   #
#####      ##     ##  ##     ##   ##       g      #####     #   #                 r  ##        ##       fg          g#   #
# ##     #####    ##             a               ######    ##              #         r#        #          #   r          #
#     f#######                     a   ##    ##  #####   #####   ##                                                ##   ##
#      ######          ## a  ##  ## b#####   ##   ##    a####    ###        #               a            #        ###  t #
#  ##   ##### b        ##    ##  ##  #####                ###     ####                         r                ####   g #
# ###     ##             l             ##    A    f     b ###        ####                                    ####        #
######             ##    b  g           t g         ## l ###        g  ##          r           b             ##          #
######             ##    a##  ##                  #####  ### ####  t                                                 #####
# ##    ##        ####  ##########a      ##   ##  #####   ## ###             A             a               A          ####
#       ##  l     ##################     ##   ##    ## b  ###                                           b         g      #
#                  #######  ##  ######         r t       ####                ##               lr       ##                #
# ##      r          ####         ####                   ###l                ##                  g     ##                #
#####         ##t      ##        a ##            ##     ####                                                             #
######       ###           ##            ##    #####  ##### g###                                                      ####
# ####     ######          ##l   f b   #####  ######  ####   ####            t                                       #####
#  ##     #########       b       ##  g#####  ####      ##             ##                        t           ##   t    g #
#       #####  ######  ##         ##    ##     ##         t          ####                                    ####        #
#     l ####l    ##########  ##        l       ##           # g   ####                r                         ####g    #
#   ##    ##    a  ############       b      l####  g       #    ###        #                r    b      #        ###    #
#   ##               ##  #######  ##   ##  l  #####       a f#   ##                                             g  ##   ##
#                          #####  ##   ##      #### b##                    #          #    g   #          #              #
#   l         l              ##            g    ##   ##        t#           l        ##        ##                    #   #
#  ##        ##     ##                               l     ##   ##   #     ##   #    ##l       ##    #r  ##     #   ##   #
#  ##   ##   ##   #####  l                ##             ####   ###      ###         ##        ##         ###      ###   #
#      a##        ##### g                 ###      b##  #####    ##   ####           ##        ##       t   ####  A##    #
#             g    ##    ##  ##          ####     ########        ##  ###            ##        ##            ###  ##     #
# ####   ##############    ###   ####   ########   ######l ## #g#   #b  # # #   #   # #   ##   # #   #   # #l#  b#   # # #
# ##### g##############     ##  ##### g  ######   ######## ##  r# #r#   # # # # # # # # # ## # #A# # # # # #b#   # # #   #
# #####  #####################    b        g g   ######### ##   # # # # # # # # # # # # # ##b# # # # # # # # #r# # # #   #
#  ##########    #############gf          b     ############# # # # # # # # # # r # # #   ##   # # #   # # # # # # # # # #
#   #########    #############  #   ###  ####   ######     ## # #   # #   # # #   #r# #   ##   # #r#   # # # b # #   # # #
##   ##### g     ##########     ##  ##    ###   #######  #### # # c # #   #   # # #r  # # ## # #   # # #  l#   # #  f# # #
###g l####       ##########     ### ######### ####   rrc ####g# # # # # # #   # # #   # # ## #t#   # # #   # # # # # # # #
#      ###  #### ##########  ################ ####    f  #### # # # # # #r#f# #g# # # # # ## # # # # # # # # # # # # # # #
##########   ##############   ############### #######    #### #   # # # # # # #   # # #b# ##b# # # #   # # #t# # # #   # #
#########     #############    ####        ## ######   ###### #   # # # # # # #   # # #   ##   # # #   # # # # # # #   #b#
####           #####  g         ###  cc    ##         ####### # # # # # # # # # # #  b# lf##   #   # # # # # # # # # # # #
######g         #####  g ##########  ########      b          # # #r# #   # #l# # #   # # ## # #b  # # # # #   # # # # # #
#######l t       #####    #########  ##### ##   ###  r  ##    #l# #   #   #   # # # # # # ## # # # # # #   #   #   # # # #
########          ##### bg ##### ## c##### ##  #####    ##    #  r#   # # #   # # # # # # ## #c# # # #b#   # # #   #  c# #
########  ######                 ##                      #    #   # # # # # # # # #t  #t# ## #     # # # # # # # # #   # #
########   ######  l#####    c c ##        ######     ####### # # # # # # # # # # #   # # ## #r#   # # # # # # # #b# # # #
#######     # ####f ######    #####b      #######      ###### # # # #   # # # #t# # # #   ##   # #t# # # # # #   # # # # #
#     g  ####  #### #######  ######                l    ##### # # # #   #   # # # # # #   ##   # # # # # #   #   # # # # #
###     f####   ### #######                         ######### # # # # # #   # # f # # # # ## # # # #   # #   # # # # # # #
###              ##             g   #########        ########   #b  #l# # # # #   # # # # ## # # # #   #r# # # #r#   #   #
###    ####   #####      ########  ##########  #### #########   #r  # # # # # # # # #   # ## #   # # # # # # #   #   #   #
##      ####  #####     ######### f     r      #### ######### # # # # # # #   # # # #   #    #   # # # #   # # # # #f# # #
# f g     c   #####     #########       b       ### #### #### # # #b# #   #   # # # # #t#    # # # # # #   #   # # # # # #
# #####   #########  #        ###  f#####   #######b###  #### # # #   #   # # # # # # # # ## # # # #f# # # #   #b  # # # #
# ######r ######### ##     ## ###  ######  ########      ####r#   #   # # # # # #t  #   # ## #g  #   # # # # # #   #   # #
# ####### ## f #######     ## ###                   ######### #   # # # # # # # #   #  g# ## #   # b # # # # # # # #   # #
# ### ###### # ##g g## f##### ###     b########    ########## # # # # # # # # t # # # # # ## # # # # #   # # # # # # #l# #
#     ###### # ###  ##  ##### ###  ##  ########   ########### #l# # # # # l #   # # # # #r## # # # # #   #   # # # # # # #
#     ###           ############# c##  #######    #######   # # # # #   #   # # # # #   # ## #   # # # # #   #   # # # #b#
#  #   ##      #### #############  ##  ####       #######   # # #   #   # # # # #   # rl# ## #   #   # # # # #   #   #   #
# ####     #  ##  # b  #  #  ############  #  #  # g##             ##  #       ##          la        f             ##   ##
# ########## #### ### ## ## ############# ## ## ## ##########    ###   #r       ###################a     A t     ####   ##
#        g                    t    g   ff    t      b        #####     #                          ################       #
#              f    l         g  b        l   c      f     l           ##                           ##    ##  ##         #
### ## ## ## ## ## ## ## ## #  ## ## ## ##l## ## ## ## ## ##         b  ##           ##   l         ##    ##  ##        ##
##  #  # t#  #a #  #  # t#  # g#  #  #  #  #  #  #  #  #b #  r           #   l       ##                           ##   r##
##  #  #  #  #  #  #  #  #  #  #  #  # b#  #  #  #  #  #  #              ###                                      ##     #
### ## ## ## ## ## ## ## ##a## ## ## ## ## ## ## ## ## ## ## #           ###       a    b     g      a                 b #
#                        l              f            t       #         a #                    b                 gf b     #
#         t        A     b               g                   #           #    r   l    # ################ ##### ##### ####
#          f         f                       a        l      #      f    #            ##  ##         b ##    b           #
## ## ## #  ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #       g    #        f   #   ##    f      ##b               #
#  #  #  #  #  #  #  #  #  # r#  #  #  #  #  #    b#  #  #  #    g       #            #        f###########         r    #
#  # l#  #  #  #  #  # g#  #  #  #  #  #b #  #  #  #  #  #  #    g   t   #       l##g ##        ##        ##### ##### ####
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##g## ## ## ##      ##    #        ##   ###########          ##b    ##   ##
#b## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ####    ##    #                             r    ##     ##   ##
# #  #  #  #  #  #  #  #  #  #    t#  #  #  #  #  #l #  #f # ##          ##          a     ##      A   ###################
# #b #  #  # g#l #  #  # l#  #  #  #  #  #  #  #  # g#  #  #            l ################ #############     fr a        #
# ## ## ##b## ## ## ## ## ## ## ## ## ## ## ## ## #  ## ## ##a      t   g   t    ##     b                   b            #
#  f                b             t    l        b           g###      f          ##l     b           f            t t#####
#f        t                   f    t   l                       ######################    #             a    f       ##   #
## #### ### #####  ##### ## ### #####  ######################      f       ##       ##  a#           b  ##   t      #    #
#        b                   ##            ########  #######        r      ##        # g       t        ##          #    #
## #### ### ##### ###### #  t    #### ## ll                            r             #            t           b     #    #
#        g  #####  ##    ## ######### #######################                   t   ##       r     b    l          ##    #
##  t## ##     l                               g                                    #      #########################     #
#######  #  #  ######### ## ######### ###################  ##   ######            ###    #              t    f  l       ##
#         l ######   ###  f         t      ##       #############    ###         f###    # t      l                     ##
##  ######              a  ##########  ##       ##                     ###        #    ###  f       ##a        lg        #
#########################################################  ##           f##       #    ###          ##   l      ######   #
##########################################################################################################################
