metadata:
  gen_time: 8.50538420677185
  timestamp: '2025-04-18T22:49:29.088946'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  ###             g        # r          a                   ########             l##############      c #####    # ######
# ######  t     r           #      #                         ######### g   ##     #########    ##        #####rl  #      #
# ######           l        #      #    g b                 b##########   ####   ##########    ##                        #
# ###     tl                ###      b  # #           g   ##############  ####  ###########     #    ##############      #
#   ###        f ####f         #   #    # #   f       r   #  ###########  ####  ##########      #    ##############      #
#f#   #   f      ####b       g #   #  f            f      # # #########    ##    ######### #### ###################      #
# #   #        t          #####l                                                           #### ###################      #
# #g  #     f    g##      ######      #    g         ##  r                                r   # c############ c t##   g  #
#     ###         ##      ######      #          r           f         ##     b##    tb       #  ##    ######            #
#### b  #                 #####                                       ####   b####   l    l   #####    c             b c #
####   b#        g        #####                 ### ##       ##       #####  #####       ##   #####r   c      f g        #
#       ###  A                  ###  ### ####   #            ###      ############ t    ###   #####              ## l    #
#   ###   #             r            #   #     l#            ####     ############     ####  t#####            g ##      #
#   ###   #                a b ## #### # #           l       f####     ####  ####     ####  #######  g         c ##      #
#r        #      a             #  #    ##     g         b      ####                  ####  #   l  l    r          #      #
#    ###  ###           t       ###    # ###b###  b         #   ####                ####t  #   r ######           #      #
#    ###    #b  ###  #####b     #        #  #               #  b ####       gg   t ####    # c   ##########       #      #
#           ### ###  #####     ## #    # # ### ###                ####  t  ##r    ####     #   c ##########       #      #
#     ###       ###  #####       ##r   #      #   r    A           ####   #### tr####      # ######         l  c  #      #
#  a  ###  ###     g    ####      # ## # ### ### ### ### ###        ####  ####  ####    g  # ######  l## ####  ####      #
#     ###  ###          ####    # # ## # ### ### ### ### ###        ####  ####  ####       # ######   ##   ########      #
#     ###       ###  #####       ##    #      #b                t  ####   ####   ####    r # ####    ###   ########c  r  #
#           ### ###  #####     ## #r   # # ### ###            f   ####     ##     ####   t # ####    ###  ######         #
#    ###    #   ###f #####      #        #  #               #    ####              ####    # ####    ###  ######         #
#    ###  ###                   ### g  # ### ###            #   ####                ####   # ####    ### r######         #
#         #     a                 #    ##                      ####    lr            ####b #         ##########          #
#   ###   #              f  t  ##a#### #r#                    ####     ####  ####    t#### #         ########## r        #
#   ### r #     b                #   # t        #       l   f####     ############     ####          #######   c   #######
#    g  ###t         r          ###  ###l####   #            ###      ############      ###          ##       A  #########
####    # t       f       #####                f### ##       ## gg   g#####  #####       ##  l ###       #################
####    #             t   #####                                       ####    ####             ###########################
#     ###         ##      ###### g    #                       r        ##      ##  l           #####      r              #
# #   #           ##      ######      #         l    ##       g                          l     #####               ##### #
#r#   #                  t#####           b     l     r                                    c   ####        c       ##### #
# #   #          ####   t      #   #                      # # #########    ##    #########      ###  l                ## #
#   ###     b    ####        f #   #    # #               #  ###########  ####  ############    ###                 f ## #
# ###               r    g  ###         # #        f      ##############  ####  ############c   ###        ############# #
# ######              b     #      #                         ##########l  ####   ##########     ###        ######  r######
# ######                    #r     #                         #########   t ##  b  #########     ##         ######   ##   #
#  ###         g            #b             l               r ########              ########     ##         ######   ##   #
############################### #  #                 # # #     b  ##           #   ##    #     ########        ####     r#
############################### #  #  #      #       # # #  #    ##  ######  f #  ##   # #     #######    ##    ##b      #
#                               #  #  #  ##  #  ###  # # #  #   ##        ##   # ##  f # #      #####    #### t          #
############################### #  #                        f#t##  b     ###  f# ###   # ##             ######     g     #
###############################                              ###         #     # # ##  #  #        r    ######f  f   ### #
#                                     # # # #  #  #  #  #### # #        r# #   # #  ## #     ######      ####       ######
##   ######## ######################  # # # #  #  #  #       # #         ###   # #   ##     ########                ######
##   ######## #################      b                       # #l         ##   # #    ##   ##########           g    ### #
#       f                           a           b       #  # # #  #########    ###     ##  ###########    r              #
### ######### ###################  ##  ##  ###  #  ###g #  #   # ##             ##  b   ###############       ##       g #
##  ######### #################                 #       #      # ###   # ### ####          ############      ####    b  ##
#           b      r            #  ##  ##  ###  #  ###  #     ##b#    ##      b            ###########      ######     ###
### ###########################       r              fg    ####  # #  ###    ## ########   ##########       #######    ###
### ###########################                              #   # #l   #  #     ##    ##  #########   b     #######    ##
#                 r             # #  # # #  # #  # #  # # f    f ###  #b#  # #          ##  #######           ######     #
############################### # #  # # #  # #  # #  # #  ##     ##  #b## # ##          ##            ### t   ####  bt b#
###############################                               #####   #f## #  #############           #####        r     #
#                  t                                         ###      A #  #  l#            r### r    #####       l      #
###### ##################### ### #  ##  #####  ##  ####  ##    ##     # #A #  ############# #####      ###   bb          #
###### ##################### ### #                        b  #  # b   ### ## ##            #######            r          #
#        b g        l          #b#   r                       #  #    ## # ##r###   # ##### ########        t           ###
###### ### # ################### #  ##  #####  ##  ####  ##  ## #   ##  # #  # ## ##    ############   r   ####       ####
###### ### # ##################                     g    t     #        #g#  #  ###    ##   #########    b######      ####
#                  b f                         g             # ##   #   # #  #  #      #  #  ########     #######      ###
#####   ## # ####### ########## # #  # # #  # #  # #  # #  ##   #   #  ## # ##  # #    #  #   ######      ########       #
#####   ## # ####### ########## # # b# #f#  # #  # #  # #   rg  #  ##  ## # #   # #  b #  #                ########      #
#                                                           b  ##  #   #        #f##   # ##                 ########     #
###### ########################        t                   ## ## f #   #  # #   # ##   # ##          ####    ########   ##
###### ##########################  ##  ##  ###  #  ###  #    ##    #  ##  # #   #      #  ##        ######    #######  ###
#             f                         g       #      t#    #     #  #   # #  ##f#   ##  ##       ########    #####   ###
#################################  ##  ##c ###  #  ###  #  # r     ## #   # #  # t#  ##   #        ######## t           ##
###############################                  l      #  #        ##    # ## #     ###  #    b    ######               #
#r                                             b             ####### ##   #  ##   #    #  # ###      r                   #
####################################  # # # # t#  #  #               b##r##   ##  #  # #  ######                     r   #
###############################       # #b# #  #  #  #  ####           ###     ## #  # # #######     ##     ##l          #
#                                 l                          ############       ###  # ###  ####    ####   ####      ##  #
############################### #  #                                             ##  # #     ##     #####  #####    #### #
############################### #  #  #  ##  #  ###  # # #  #  ###################  f# # #     b    #####   #####  #######
#  r                            #  #  #      #       # # #  # ###          ##        ### ##          ###     ####  #######
# ############################# #  #        g r      # # #   ## ##                    ## #     ###  r         ##   #######
#             ####      t               ###       #### #    #f   l            ### ## ## ############   ######A  ##########
#  a f        ####    t        ##   ##t   #            #       ##     ##     l  g          #########   f        ##########
#t g     ###  ####  ###        ##   ####   f f #          ##   ##     ##                   #########            ##########
#        ###  #### l###  l       c t# #  lf    # #bg                                ### ############  ##    ##  ##########
# ####   ###        ###   #### #    #       r  ####    b##                          ##   ###########  ##    ##  ##########
# #### f ###g       ### t #### ##   #      #  ##l #   ########b#### #### ###   ### ###   ###########r ##r   ##  ##########
# ####      l  ##rf    l  ####  #   ##     #   #  l ####   #    ##   ##   ##   ##b b       #########  ##   a##  ##########
# ####         ##         ####     ##      #   #    ## ##       ##   ##   ### ###t                f   ##    ##           #
# #### l#####  ##g #####  ####      #r  #  # # ## r ## r           g               ##  ##                                #
# ####  #####      #####  ####   ####   # ## ###  r #         g                    ##  ##    ###                   b###  #
# ####  #####      #####  ####    ###  ## ##  ##    #      b# f                      b       ### t ####      ####   ###  #
# ####  #####      #####  ####         ##     ##   ##       # ##        ### ### t          f       ####      ####        #
# ####                  g ####A    ##### g         #g   ##  tf##        ##   ##                    ####      ####    f   #
# ####                    ####    g         #     ##         #### #### ###   ### #### ###       t                        #
#                t    A   t    ######    #######   ##    f ##      ## l    f      ##   ##   ##r                       ## #
#  b                           ###      ###   ##           ##      ##    l        ##   ###g ##     #####    #####  f  ## #
#        g g       t                a   # ##      ##r      #  ### #### #### ### b           ##     #####    #####     ## #
# g###### bl           ######     ##  #     l t ###     ##### ##  f     ##   ##        b    ##     #####    #####     ## #
# l###### b##      ##  ######   # ##  #        ####   # ## lt###        ##   ### #### ###   ##     #####    #####     ## #
#  ######  ##  ##  ##  ######   # ##           #  #  #####          ##  f         ##   ##   ##     #####  t #####     ## #
#  ######  ##  ##  ##  ######  ##  ##       #  #     # A        t   ##   l        ##   ###  ##   b #####   l#####     ## #
# b######  ##  ## g##  ######   #####  #  ###  ##    #       ###           ##           g   ##     #####    #####     ## #
#  ######  ##  ##  ##  ######  r# #    # r##   ## ####     ## ##           ##              g##     #####    #####     ## #
#   t      ##  ##  ##           #      #   ##  ## ## ##t    b ###a###     t            b    ##ll   ##### lr #####     ## #
#                               l     g## b#      ## f    r        ##            t   b      ##  b  #####    #####     ## #
#       l        t     l         t    ## b ##      l             l ### #### #### ###        ##           g            ## #
########  ############  ##########     # t  #   ##    ##     #          ##   ##   ##                                     #
########  ############  #######  ##  ###    #   ##      t ######        ##   ##   ### ####         ####   tt ####     f  #
########  ############  #######  ##  ###   l##f ##         #####                       ##          ####      ####        #
########               b####### ###        ##   ##     ##    #                         ## g  ###f  ####      ####   ### b#
########   r            ####### # ##              g  #### ## l               ##  t           ###                    ###  #
########  ############  ####### #     f#  ##     ##      g## #          ##   ##                  f    t       b         t#
########  ############  ####### ########  t###b b         ## ###    ##  ##   t   ##  ##              g##    ##b          #
#         ############             #####        ##           ###    ##           ##  ##    #########  ##    ##  ##########
#         ############   t   l  ##  bg  b#########     ####  #                          a###########  ##  lg## t##########
#                               #   ###  ##    # #   r  ### #                   f        ###########  ##    ##b ##########
#               b  r           ##  ##            ###  ###  a##   ###A#### ###   ## t  g  t #########  ##    ##  ##########
#  #########   g   b#########  #   ### r         l#   ####   #   ##   ##   ##   ##         #########f           ##########
#  #########   a    ######### l#           ##     # ###      ## ###g  ##   ### #### ### f###########t           ##########
#  #########      c #########  #    ##### t## #   # ####        r                    ##   ##########   ######   ##########
##########################################################################################################################
