metadata:
  gen_time: 9.603230953216553
  timestamp: '2025-04-18T22:58:50.628408'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# ###       #   #     tl            r   # #####   ###             f  ###   #####     b                 ##   f    a ##  a #
# #         ### ##      r f    b    r  ##  ##      ## b   ##  ##     ##      ##                c             a      g  a #
# #           #         l   g            r         ###   ###  ###   ###           a                    ##         g##    #
# #     l     #         g   #t                    ####   ### ####   ####                 t gr  r       ##   t      ##    #
# ###         ###  g        #              ##    g#####l  ## ###   ##### r   ##       b a       b   b  ## a              #
#   #           #                   #      ####    ####   ##  ##c  ####    ####   a                g   ##       g  ##    #
#   ### ####    ### ###             #     ######   r##   ###  ###b  ##    ######                       ##          ##    #
#       #t        #        l             #######       r ########r        #######f      c       ta                 ##    #
# t # ###         ###               f    ######           ######           ######       b              ##      b   ##   a#
#   # #                 g         g       ##### a    ##a  ######   ##   l  ##### a  c                 r##g         ##    #
#   ###           # #g                     f##     #####   ####  l#####     ##                      g  #### ## ###########
### ##            # #                              #####          #####                      g         #### ## ###########
# #  # r     ###       f     r                      ###f           ###           # ## ### ## ### ## #####   aa   a     g##
# ### ###    #              g      A     t    ##    ##l    r        ##    ##    b#b## ### ## ### ## #####       b   ##t ##
#   #   r    #t### ###         l              ##                          ##  l         b     r  a     ##      a    ##f ##
#   #   t      t #  #         l   r      a  a          aa ## g##                    t a     a    c b   ##      a t      ##
#   #            ###  ## #### ###      l          g##    ###  ###    ##            f        a          ## f  t      ##  ##
# t #           f  #  f# # r#  #    g    ##  ##    ##g  ##########   ##  r ##  ## l           fa     l ##           ##  ##
#            l     #   ###  ##  ###     #######         ##########    a    ####### ####g#### ####### ###### ### ##########
#       #      r   ### ###    #  #      ######## b        ##  ##          ######## #### #### ####### ###### ### ##########
# ##    #     t      #        ### ###    #  ######                l    c######  #               ##        g   g    ##  ###
# #  g               ### ###    #   #         ######      g           ######           t        ##   a             ##  ###
##  ## f      ###      #  #   g #   ###  r     g######  ##      ##  ######     r             r  ##  t              ## g###
##            #        ### ###  #     #  a##      ########      ########   f a##      a        t             ac   f##  ###
## #  ## ##r# #          #            ### ##ga      #######  a #######        #     t  b f      ##            r        ###
#  #   #    ##           #t l             a   a       #####    #####   c      f a               ##                g##  ###
#  #   #l   # #### ### ###  #         # #    f         ##        ## l          g                ##              f c##  ###
#  #   #      #    #  #     #        r# #   ##      r         a          r  ##                f            c   c   #######
####   #      #    # ### ####             #####        f            a      ##### aa  c          ##                 #######
##     #             ###                  ######  ##   ##        ##   ##  ######  t             ##      a         a##    #
## ###t#               #          g   t  #######r ##  ####      ####  ##  #######  a        g   ## c  t  c              b#
# #g                 #r### ###      #    ######       #####    #####       ####### ###### ##### ####### #### #### ### f  #
# ##  f   f ###      rt  #          #     ####       b ############         #### # ###### ##### ####### #### #### ###    #
#           #     g r    ### ###     t #    ##           ########           ##              b##   ##           ##  ## aft#
## ###### # # ###          #  #        # l         ##      ####      ##                      ##   ##          a##  #######
##   ##   ##   #           ### ###        b     r######            ######          b         ######### ###b###############
## ###### # ### ###  g    g  #  #          ##   #########        #########   ##        t    a######### ### ##########  ###
#         g #   #    r       # #  ## ###   ##   ###  ######    ######  ###   ##    ar     b  ##     ta       a##   ##  ###
# ##        # # #              # r#  #   l g   ###     ############     ###                  ##                        ###
# #           #  r             ### ### ##      ###  r    ########       ###      # ##### ######## ## ## ########  #### ###
## ### ###    #                  #        ##  #####  fg    ####    g   #####  ## # ##### ########c## ## ######### ####  ##
#     #       #                  #        ## l######                  ######  ##                        a      ##    ## f#
## # ### ###      g     # # #  ###              #####               f#####       f b  t         f t a   r  ##a ##    ##  #
###      #        ###   # # #  #                 g#####l ##   r##  #####                 f                 ##  ##    ##  #
##  ## # # ###    #      l     #              r    ########    ########         a          g              a##  ##    ##  #
#  #   #   #      #         l  #f       r ##b ##a    #######  #######     ##a ##f             a       a                 ##
####   ### # #### ###                #t   ##  ## l     #####  #####  r    ##  ## # ## ### ### ########### ### ######### ##
##                                   #       r           ##  f ##        a  a  l # ## ### ### ########### ###       ##a ##
##   l #                                      a    ##                ##               a                ##  ##       ##  ##
#      #      #t                               ##  ##              r ##  ##            c         ##    ##  ##   a   ##   #
##           g#    ###                   b     ##  gg                    ##             a      a ## f  ##  ##     a a   ##
#      ###                               ##  lf        ##        ##    g gg    ##r c  a          ## c  ##  ##  b    ##r ##
#      #A t    f   # #         t A       ####    a t  ###  g     ###         ###### ## ### ##################   g r ##t ##
#      #       f   # #        t          ####    ##g  ####   f  ####   ##    ###### ## ### #################### ##########
#  l ###   l  r                          ##     ###    ###      ###  r ###    a##   aa      a  c           #### ##########
#    #                        t          lg   f#####   ####    ####   #####b                cc        ## f ##          ba#
# ## # ###              ### ### ###          #######  #####  g #####a ####### a            g     g                       #
# ##                    #   #   #          ########   ######  ######   ########            g                             #
#### ### #  g f  f###   # ###   #     f    #######     ############    g#######t ####### ### ## ## ##   ####  ### ### ## #
#r   #   #        #      l#     #         #######      ############  g   ####### ####### ### ##a## ## # ##### ###t###b## #
##   #            r  ##     ##       ##    a    ###                    ###             ##       ##  # #    ##     ##  #  #
###  ##              #       #       #b  r      ###               a    ###         ## ##     #   #   ##     ####  #   #  #
###  ##              ##     ##  c l  ##    ###a ########          ########  ###    ####      #   f ###       ##       ## #
####### # # # ## #  #### ## ##### #######  ###  ########          ########  ###    # ##     ##     ##### #####         ###
######  # # # f# #  #### ## ##### #######  ###  ########          ########  ###  # #  ##r  ##    #    g                ###
#           #    #    ##  #   ##    ##     ###    l  ###          ###       ###  ###   #   #    ##           r b  ###    #
#           #    #    #   # g ##    ##  #  ###     r ###a      r  ###       ###  ##        #    #  b ####  ########     g#
# r         #    #    ##  ##  #####################  ###  g       ###  ###########     #    b   #        g  ##      tr   #
#    b      #    #    ##  ##  #####################  ###       g  ###  ##########g    ##   #    #   #    ##  ##          #
#           #    #     #  #   ## f##     ########## r###          ###  ###########    #    #    #   # f ## ## ## ##### ###
#  ## # # # #    # c  ##  ##  ##          g          ###          ###            ##   #   ##    ## t##  #  ##            #
# ##### # # #  # # ######################            ###  b       ###             ##  #g  #     g#   ## #  ## g          #
# ##        # ## # ###########################  ########     f    ########  #####  #  #   #      #    ###  ##l   bt    ###
# ##        #    #            ##    ##  ######  ########     a    ########  #####     #   # #### #     ##  ###b#######   #
# #         #    #             #   g# b ######  ########          ########  #####  #  #       t###   b  ##          ## ###
# ##      r #    r           l##    #       l              a A             ga  rr###  ##        ##       # #       ##  t##
# ## c      #    #            ##    ##  #                            l        f  ##    ##  # ## ### ###### #      ##     #
# ##  A     #    #        b   ##     ####  ####################################   ### ####  ####           # b    #     ##
# ####  # # #### ###### ######### ##  ###r ####################################    ##    ####  ##          ##           ##
# ###   # # #### ########## #########   #  ####################################     ##          ##          ## f       ###
#A##    f    ##r ##                     #                                           ###          ##     ## ####        # #
# ##         ##  ##          ##         #                r   c   g    r           r## ############## ####     #    #     #
# #  ## # # ###################   b ##  #  ####################################   ###     #######    f     t       #    ##
#   ### # # ######### #########     ##  #  ####################################  ##      ##     ##   t        # g  #    ##
#  #      #   ##                           ####################################  #  #   ##     #### r         #    ##    #
#r #      #   ##  ##r    ##  ##     ##  #            ###  g       ###        f      ##  #     ##  #           # #   #    #
#  ##   # ##########     ################  l         ###        f ###      A  b l     #g#     #          # # ##        # #
# ### #A# ##########  c  ################  ########  ###     l    ###  ########  #### ###t    #   #   # ##  t   #    ##  #
# ##        ##                             ########  ### lt g     ###  ########  #### ##      #   # t##         ##  ##   #
# #   #     ##    ##     ##                ########  ###     g    ###  ########               #b ##  #    b  b           #
# #   # # ################## ####### ####  ###                             g###     ## #      #a #   #    ##### ##### ####
# #   # # ###### #####                     ###                              ###  ## #  # #### #  #   #   ##  ##        ###
#l         ##       ba  ##      ##     #######  ########     a    ########  #####      ###  ###      #   #    ##   r  ## #
#  #  ##   ##           ##      ##     ####### b########   f      ########  #####   b  ##  # ##  # b##        ###    ### #
######### ######## ###########################  ########          ########  ######### ###  #  #  #  #    #   ## #    #   #
############################# ###########       ###  ###    f     ###  ###        ##       #     ## #    #  ##  #    #   #
##                                              ###  ###          ###  ###l g   l ##    #  #  #   ###    #  #   #    #   #
##    ##    b                            ##########  ###          ###  ########## ###   #  #  #  b##     #     b#    #   #
##f   ##      ##         ##              ##########  ###          ###  ############ ## t#  ## #g ###    ##  #   ##   # # #
##    ##      ##         ##           ## ##########g ###          ###  ############  ##     ###  # ## ###   #    ## ##   #
##    ##      ##         ##           ##   a f  ###        r           ###       ##   ###    ##  #         r##     g   # #
#########################################       ###c    b    a       r ###       ##    ##     ## #   b b     ##        ###
### ############################# #######  ###a ###  ################  ###g ###  ##     ##      ##    ## ######## ##    ##
##      ##        ##    ##   ##      ##    ###  ###  ################  ###  ###  ##      ## ### ##   ##            ##   r#
## f                                       ###b ###  ################  ### a###    #         ##  #   #              ##   #
#### ########## ####    ##   ##      ##  r ###    l  ###       bl ###  a r  ###  # ##     t t##  #        ############# ##
####################    ##   ##      ##    ### g     ###          ###       ###  # ### #### ####b#   #   ##    ##  A     #
##                                         ###  ########          ########  ###  ##            ### t ##  #  gg  ##       #
##  l #                                    ###  ########          ########  ###   ##            ##    ## #b      ## ### ##
##    ##    ##    ##                       ###  ########          ########  ###    #   t         ##   A###        t  ##  #
##    ##    ##    ##  ##      ##     ##t   ###l           g           l     ###                   ##lr  ##         g  ## #
########  r #     ##c ##      ##### #####  ###   l                   f    fl###    #               ##    ##   r        ###
#### ###   r##    ######      ################  ###  ################  ##   ##### ##    #### ###############            ##
###   ##    ##    ######      ##        f#####  ###  ################  ###  #######    ##                  ## #### #######
#                                        #####  ###  ################  ###  #######    #     r                         g #
###   ##r   ##    ##  ##      ##   rr           ### a      b    g      ### b      ## b #                           b     #
###   ##    ##    #######################     g ### g               f  ###         ##  ##            #### #### ### ## ####
###  r##    ############### #############       ###                    ###       ##### ##         ####       # ###  b   ##
##                                        b     ###                 g  ###      g    #    #      ##         ##   b##     #
###   ##    ##                            r     ### r     b       a  l ###            ### ########b        ##    ####    #
##########################################################################################################################
