metadata:
  gen_time: 7.484993934631348
  timestamp: '2025-04-18T22:47:18.741307'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
######## ##  # #l#  ###r# # #      ######                          #    #  #     # # # # #     #g#     g# #   # # # # # ##
# ######  #     ###            # # #####r       g  c     c   r  g  #    #  ###   # #     # #   # # # r# # #b  # # #   # ##
#  #####      b#### l               ### #   f c    l               #f   #  ###   # #   #   # # # # #  # # #l# #   #   # ##
#            #  ###                                 t       c      ## ###        # # # #   # # # # #  # # # #     # # # ##
#                #      #               #             t            ## ###          # # # # #   # # #  # # #   # # # #f#  #
#            #  #  # #                        c                              f     # #t#b# #   # # #  # # #   # # #   #  #
#                    ##                   f       c           c         c        #f# # # # # # # # #  # # # #a# # # # # ##
#                t##                      ########################### ############ # #     # # #   #  #   # # # #   # # ##
#              ###                         ##   ##      ##    ## l##     ##t ##  # # #   # # # #   #  #   #r# # #   # # ##
#                 #                        ##   ##      ##    ##  ##     ##  ##  # # # # # # # # # #f # #   # # # # # # ##
#                ###                            ##  gg  ##  t           t##c ##  # #g# # # # # # #l#  # # #b# # # # #r# ##
#               ##########                      ##      ##               ##  ##    # # #l# # # # #l#  # # #t# # # # # # ##
#                ########                               ##r              ##  ##  #   #t  # # # # #      #   # # #   #   ##
#                 ######                    f           ##            c  ## g##  #   #f  # #f# # #     r# #f# # #   #   ##
#               l     # #    ####f#######r              ##   ###        l##  ##  # # # # # #   # # #  # # #   # # # # # ##
#             # #   ##   #     # #######t       r       ##   ###         ##  ##  # # # # # #   # # #  # # #   # # # # # ##
#                   ###    ###   ######             f   ##     #         ##  ##  # #   # # #g# #   #  #   #f# #g# #   # ##
# t                 ##      ##    ####    r       t   c ##     #             ## t f#   # r # # #   #  #   # # #  f#   #  #
#                      #                                ##     #######       ####  # # #   # # # # #  # # # # # b # # #  #
#                   ##  #       #           c   f    l  ##     #######           # # # # # # # # # # g# # # # # # #g# # ##
#                  ###  #              l                ##           #     rf    # #   # # #   #   #  #   #   # # #   # ##
#                 ####                                  ##         l #             #b  #g# #   #   #  #   #   # # #   #  #
#                 #####                      g ct##     ##           ####          # # #   # # # # #  # # # # #   # # #  #
#       b         #####                       r  ##     ## b         #### g      # # # #   # # # # #  # # # # #   # # # ##
#   r  g       # #    #   #       rf      c      ##b    ##g t            l      l# # # # # #   #b# #  # # #   # # # # # ##
##                  ##        r   f     #        ##   t ##    tf     #    g f    #   # # # #r  # # #  # # #   # # # #   ##
###l t             #  #    #       r   ##        ##     ##   l       ######    A #   # # # # # #   # f#   # # # # # #   ##
####      r          ##    #          ### b               t         c######  r   # # # # #g# # #g  #  #   # # # # #f# # ##
#####         l  ###### #    t       ####              g            g            # # #   #   # # # #  # # # # b #   # # ##
######           ###### ##      l   #####  A         c       r           f   t   # # #   #   # # # #  # # # #   # l # # ##
#######     f b  ###### #          ######         #######       ########## ####### # #   #   # # # # f# # # #   #   # # ##
########          #####   r       #######   c     ##   ##       ##      ##    ##l# # #   #   # # # #  # # # #   #   # # ##
########           ####    t  g  ######## ##########   ##       ##      ##    ## # # # # # #l# #   #  #   # # # #b# #b# ##
#######   t    f t  ##g         ######### ##  ##     r ##               ######## #   # # # # # #   #  #   #g# # # # #   ##
####### #               rA  f t#############  ##       ##                        #   # # # #   # # #  # # #   # # # #   ##
######       f r              ###########  l  ##                  c          t   # # # # # #   # # #  # # #   # # # # # ##
####                        f############  b  ##    fc             f             # #f# #   # # # # #  # # # #t#   # # # ##
#             l   t    t    ###########       ##################################   # # #   # # # # #  # # # # #   # # #  #
##            #r           ############ #           ##      ##   ##  r##  ##  ## t #   # # #l  #   #  #   #   # # #   #  #
###              b     b  ############b##     t     ##t gc  ##   ##   ##  ##  ## # #   # # #   #   #  #   #   #f# #   # ##
####                     ############             c                   ##  ##  ## # #f# # # # # # # #  # #r# # # # # # # ##
####                   l############                    f       l     ##  ##  ##   # # #   # # # # #  #r# # # #   # # #r #
#### #                 ############       t ###############f         f    ##  ##   #   #   # # #   #  #   # # #   #  r#  #
#### g                ############          ##  ##   ##  ##    b          ## c## # # r # # # # #   #  #   # # # # #   # ##
####                  ###########       #   ##  ##   ##  ##              b##  ## # # #l# # #g  #A# #  # # #   # # # # # ##
##                    ########## #      #   ##       ##  ##               ##  ## # # # # # #   # # #  # # #   # # # # # ##
#  #                     ######             ##       ##  ###################  ## #   #   # #b# # #      # #r# # #   #   ##
#   #                 ##  ####          f   ##       ##r   f ##c ##   ##      ## #   #   # # # # # g   l# # # # #   #   ##
#  t   # #                #            c   l##       ##      ##  ##t  ##    r ## # # # # # # #f# #l#  # # # # # # # # # ##
#  #                  ###        ###     g  ##     c ##      ##       ##     r## # # # # # # # # # #  # # # # # # # # # ##
# ##                   ##   # # ###    #    ##  t   g##     r##       ##      l  # #g# # # # # # # #r # # # # # # # # #b##
###  #                     #  t#### #####   ##       ## f    ##       ##         # # #   # # # #   #  #   # # # #  l# # ##
### ##     #            #                  r## f     ##c     ##                  # # #   # # # #   #  #  r# # # #   # # ##
### ##                  c# #                ##  f    ##      ##     g     c      # # # # # # # # # # b#g  # # # # # # # ##
##  #            #        ###             g ##    f  ##      ####################  # #g# # #   # # #  # # #   # # # # #  #
## #           ##  #     #####  #           ##       ##            ##    ##     #  # # # # #   #b# #  # # #   # # # # #  #
#     # #    #####    # #####l              ##       ##            ##    ##     ## # # #  r#f# # # #  # # # # #   # #r# ##
##      #     #####   l#####  gf ######  r        c  ##         r c     b       ## #   #f  # # # # #  # # # # #l  #  f# ##
#     #        ####   #####                          ##     g      b    f       ## #     # #   # # #  # #r#g  #   #   # ##
##r#    ###    t###    ###     ###    #                            f      ######## # # # # #   # #      #A#   # # # # # ##
######r #### ##       ######     ###  ## #### ########### ####      ##      ##   r   ##  ####  #          # f####  ##    #
#t   r   ##   ## ### ##    ##   ## t   ####     t##         ##    g ## ###  ##       ##  ## ##     r tl f   ## ##  ## f  #
# a            ####         ## ##       ###      ##         ##### #### ###         ######## ##  ###f  f###  ## ########  #
# ###############                                ##         ##### ####  ##  ##     ####  g      ###    ###  l      ####  #
#        ##        # ####  ##             # t    ##         ##      ##  ##  ##r     #g        #####    #####        c#   #
#                 l   #            ### #### l    ## r l     ##    b ##t ##  ##     b##         f             c      ##   #
#  ######################    ###  ##   g### ### ###### ## ###### ################         l    #          # r           c#
# ## r       ##           #      f      a## ### ###### ## ###### ################    f    t##  #b    rg   #  ##          #
# #               #######  ############## t  ##   ##g      g  g            ##   ## ## r   ##t  #  #    #  #   ##  c  ##l##
#             r  ##            ##     ##    f##   ##                   ##  ##                  #          #              #
#               ## t fg                      ##   ##  f           t    ##  ##   #   gc lf ##   ###      ###   ##       t #
#    ############       ##               t   ## t ##                   ##  ##   ### ####       ###      ###    c  #### ###
# # ## l          t #   ###### ##  ######   r##   ##                g  ##  ## g ###    l  lrl g###  c   ### b   c      ###
# ###                ll     ####          ############ ## ### ### ###############       b       lt                       #
#  ##### ###### t ##       ## #### #      ############ ## ### ### ############### #     l                              # #
#      ###  t###  #  r     #       ## ######  ##                g   ##      ##  tr##        f####        ####         ## #
#     ###   ## ## #     A  #        ####  ##  ##                 r  ##  ##g ##      c   cr ####  r  c      #### r       g#
#     # ##  #   # #        #     # ### ## ##  ##     b    f         ##  #########        r r      ##  ##    A            #
#     #  ## #     #    ##       ##      # ##                            ######### g         l     ##  ##            c    #
# #   #   #     #     ##       ##         ## r##                    ## r##     ##                                        #
# ##  #     #   ###                     #     ##f                   ##  ## c   ##  #    #      #f       f # c r l#    #  #
#  ##       ##  # ##  #                 # ##t #### ### ##### ### #########     ##  ##         ###  f   c ###         ##l #
#   ##       ## #  ## # #      ##   t   # ##  #### ### ##### ### ######### ######           ##### l# f#c #####           #
#    #        # #   # ###      f##     c#    g##            t       c  g## ###### b         ####          ####        c  #
# t    # ## ###     # # #   #### # ###  # ##  ##       b     t          ##  ##         #    ###            ###    #      #
#  r   # ##         # # #  ##       #   # ##                            ##  ##         #r                l        #      #
#  ### #  #        ## # #  # a     ## ### ##  ##      c                 ##       b  c          ##  ####  ##              #
# ##        # # ####  # ## #       # g# #     ##    r                   ##  ##                    ######                 #
# #         # #       #  ##      r #      ##t ##          fg  g   g         ##     #              ######              #  #
# #### #  # #         #   ##r      ## #   ##                            ##      t                 ######  c  c           #
#                    ##    ##       ###   ##  ##                        ##  ##             t  c   ######                 #
#  ### #  # # # ######      ##########    ##  ##      r   t             ##  ##     #              ######        r     #  #
# ##      #                   a           ######### #### ##### ### #############                  ######                 #
# #                 ### ################# ######### #### ##### ### #############               ##  ####  ##           c  #
#               ######r   ##l  ##            ##  ##   ##  ##          ##        b      #   g             c        #      #
# #         # # # t                          ##  ##   ##  ##          ##   r           #    ###            ###    #      #
# ## # #  # # a a                   A        ##  ############## ## ##############           ####         l####   r       #
#  ###               a  t  a r  #########    ##  ############## ## ##############       f   #####  #  #  #####           #
#   ##############################  ##           ##      ##           ##     ##    ##       c ### f      ###         ##  #
#r                 ##  l ##                  ##  ##      ##       b  g##     ##    #  c #      #   l    g #      #    #  #
#     c  lg          t                 A     ##          ##  g               ##                           r        l   f #
#       t     ##                                 ##      ##      t    ##             c            ##  ##                 #
# c # # # #  ###  ###  ##################    ##  ##       t   r       ##     ##                 f ##  ##       f c       #
# # # c   #            r           #         ##  ##    g ##           ##     ##t           ####            ####          #
# # ##         a            ######## ###### #######      ##     t     ##     g    ##         ####        ####   bc    ## #
#   f##      ###  ###      ###       t   ## #######      #### ##### ####     ##   #      g                         g   # #
#     #   ## ##        #   # ##l         ##      ## r    #### ##### ####     ##     f             g       r        r     #
#       #           #  ##  #  ##         ##      ##      ##      ##   ##   c     ##            ###      ###            ###
# #   # #    f      # g ## #t  ## #########      ##      ##      ##   ##     ##  ## ####       ###     t###       #### ###
# ##r # #     r     #    ##     ###    a ############# ####      ##r  ##   g ##           ##   ###      ###   ## c       #
#  ## # t           #     ##             ############# ################### ######   r          #          #              #
#  ## #    b        ## ###       ##       ##  ##  ##     ################# ####### ##     ##   #  #    #  #   ##     ## ##
##  # # #         f  ###    # #   ##    # ##  ## g##     ##  ##  g##           ##          ## r#          #  ## g        #
##  # # #    #### #####     # #    ##  ##     ##         ##  ##   ##           ##              # g        #     c        #
#   # # #    #    a   f     # #   ###  ## ##  ##  ##         ##   ##          a##   ##     f                   l    ##   #
#   # # #  #      g         # #  ##   a#  ##      ##  g r##  ##b               ##   #         #####    #####     c   #   #
#  t# # # ## #             l###  #  #  #  ##  ##  ##  t  ##r ##   ##r          ##  ####         ###    ###         ####  #
#   # # # #  #  # ###        ##  #  # ##      ##  ##     ##       ##            b  #### ### ##  ###    ###  ## ## #####  #
#   # # # #  # ##   ## #######   ## # #   ## r               ##   ##f          ##    ##  ## #               ## ##  ##    #
#   # # # # ## #     ###          ### # f ##  ##  ##     ##  ##           tg   ## A  ##  #### r#          #  ####  ##    #
##########################################################################################################################
