metadata:
  gen_time: 9.62797474861145
  timestamp: '2025-04-18T22:56:28.760905'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# ##  ##  ### #########      ##  #b ###  #  ## ## t           ## ## ##g##                                              ###
#  ##  ## ##          ##      #  #       #  #   # # ######### ## ## ##                                        ## ## ## ###
##  #   #       t      ## a # #  ##      ##                         ## ## ## ## ## ## ## ## ##t## ## ##g## ## ## ## ## ###
#       ## ### ########### t#  # ##      ##     r     g    ## ## ##b## ## ##                   ## ## ## ## ## ## ## ##r###
# t ### ## ##        ##  #     #         ##   ##### ########  ## ## ## ## ##                                           ###
##  # #    ##       ##          # #  ##  ### ##  ##   ##      ## ## ## ## ## ##r## ## ## ## ## ## ## ## ## ##b## ## ## ###
###      #  #     b##    #  ##  #      t          ##   ##     ## ## ##t## ##                                  ## ## ## ###
#           #      #g   ##a  #   ##                #### ##   c## ## ##          ## ## ## ##f## ## ## ## ## ## ## ## ## ###
## ##       ##    r#   ##    t  ##          ##########  ###   ##g## ## ##g##                ## ## ## ## ## ## ## ## ## ###
##  #        ##    ##  #        ######### ###             ## g## ## ## ##    ## ## ## ## ## ## ## ## ## ## ## ## ## ## ###
##   ##  # #####    ## #     #                  b       ## ##       ## ## ## ## ##g## ## ## ## ## ## ## ## ## ## ## ## ###
#     #  #     ##    ###     #         b         t      ##  # ## ## ## ## ##       ## ## ##b## ## ##t## ## ##t## ## ## ###
#               ##   ##      #            a           l  ##   ## ## ## ## ##                                  ## ## ## ###
# a  f   # ######## ##    f  ##                           ##  ## ##c## ## ##                   ## ## ## ## ## ##b## ## ###
#        # ###           r    ##     t ### ########### ###### ## ## ## ## ## ## ## ##t## ## ## ## ## ## ## ## ## ## ## ###
#######  #   ##           ####### ######                    # ## ## ## ## ##          ## ## ## ## ## ## ## ## ## ## ## ###
#  ##    a    ##      #####               r                   ## ## ##b## ## ##g##b## ## ## ## ## ## ## ## ## ## ## ## ###
#              ##g# ###   a               A    #### ######### ## ## ## ## ##       ## ## ## ## ## ## ## ## ##b## ## ## ###
#    ##                            #############  bta##t      ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##b## ## ##t###
#  b ###    f        c        ######                  ##      ## ## ## ## ##                                  ## ## ## ###
#   ## ##   t ######### #### ##        r               ## ### ## ## ## ## ##                         ## ## ##g## ## ## ###
#  ##  ###   ##     fb   ##                      b  b     r   ## ## ## ##g## ## ## ## ## ##f## ## ## ## ## ##t## ## ## ###
# ##   #t##  #           ##                                  b## ## ## ##b##                ##t## ## ## ## ## ## ## ## ###
###  b #     #          ###        a############ ### ## ##### ## ## ## ## ## ## ## ## ## ## ## ## ##b## ##g## ## ## ## ###
# b    #  # ##          # ##a      ##     a         t         ## ## ## ## ##                         ## ## ## ## ## ## ###
#      #  ###           #  #      ##                          ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ###
###r b ## ##           ##  #  g   #             t             ## ## ## ## ## ## ## ##r## ## ## ##g## ## ## ## ## ## ## ###
# ## b  ###ra       ####   #     f#               g           ## ## ## ## ## ## ## ## ## ##l## ## ## ## ## ## ## ## ## ###
#  ##      ##########f     ##    b#r c         a  b         b ## ## ## ## ## ## ## ## ## ##g## ## ## ## ## ## ## ## ## ###
#   ## ### ####             ##   ##     g       ## ###### ### ## ## ## ## ##                ## ## ## ## ## ## ## ## ## ###
#       ####    b ####  ##           ## f       ## #       ##      A         a##         ##l b     ##      ra ##        ##
#       ####       #    ####     t  ####t     g  #         ## a     a f                                       ##        ##
#   t l####            ######    r   ###               t  r            f   f  ##         ##a    a  ##b r  fa  ##       a##
#    ######          ########         #            ##        ### ########                             a       ##        ##
#    #######     r   #######    b         ## b   t ##     ##r###  ###  ############      ##        #   b      #         ##
#     ######   l      ######       ##   ####   r         #####             #########   ######################### #####A###
#t    ##  #             #####      ##   #####             ####            g   r      #       ################### ##### ###
#            ##   b       ##b            ###        t       ##                       ##        l                         #
##          ####       b                  #          ##      #  g    a   b           #   l                               #
##    r#     ####                a##           t t ####      ##############################     r  r ########### ##### ###
#  f  ###     ##        ##        ##               #####     ################################################### ##### ###
#    ####              ####   #  bg                 ####                 f       a           ##  ##            l         #
#     #### ##    ##     ##   ###          ##   ##   #####  ##         ##     a         a   f ##  ##     g                #
#     #### ##   #####       #####        a##   ##    ########              a  t              #   #   a         t         #
#      #         ####   ##r  ######    a      #### r  #######  ## ### #  ###################### #######       a          #
#  ##             #     ##     #####    f  r  #### b  ##  #### ##  ## ## ## a##  ##  ########## ############ ### ##### ###
######                           ##             #          ### ##  ## t  ##  ##  ##g   g  g  a           ##  ### ##### ###
#######                                ##                     a##  ##  a ##  ## a##    r     a  #        ##            # #
#######        ##  a  r r        ##    ##                   r  ##  ## g a##  ##  #          a   #    a   ##            # #
########  b    ##  t     ##      ##                    t    #  ##  ##    ##  ##f #         l    #        ##            # #
########  b         ##   ##                          t    ###  ##  ##a   ##  ##a ##      b      #        ##         b  # #
##  #####  a   ##  ####                       t           ###  ##  ##    ##a ##  ##     a       #g       ##   a  a     # #
#b    ##    r ###   ##      ##            ## b             ##  r#  #     #   #   #     t        #   f    #             # #
#              ###      ##  ##     ##     ##    ##           ############### ##  ######## ##### ##### ###### ### ##### # #
#     ##       ##       ##         ###         ####      a  r ############## ##  #######a ##  # ##### ###### ### ##### # #
#  a#####ba b                   r ###           ###    ## ##    g     bla    r            ##                 t           #
#   ####                   ##    ####tr          ###   ## ##                t             ##          l      f           #
#    #        ##           ##     ####           ##l            ba                  f   b ##### ##### ###### ### ####    #
#        ##   ##     ##  A        #### r                        a   b               l    b##b## #####  #####  ## b#### # #
#      ####          ##    t       #      ## b                a       b  r   b   a        ##a            g    ##       # #
#    #  ## # ######       t  #       t#   #     #  # ########   #        #         # #      l  #     #   #     # l  #  g #
#    #  #  #           #######f       #   #     ## #             #      #b        #   #         # c #    #t   #    #     #
#    #f # ##           #           a  #   #        #              #    #   f     #    #          #   #   #   #    f#     #
####b#  #                #      #######  b#  #######  #######    #  f #      b    #   #         #   #   #   #     #      #
#  # ## #        # ####### b    #    f    #  #        #           #   #      #     #   #      b#     # r#    #   #      ##
## #  b #        #  g           #  #      ## # ##     #     #    #     #   #  #    #    #      #  l #   #   #     #      #
#  #    #        # ##         gf#g #         #  #  ####     #  ##     #   # a  #    #   t#    #b    #   #    #     #  #  #
# ##    ######## #  #f          #  #  ########  #  #     r    #      #          #    #    #   #     #    #   #    #   #  #
#              # ##r#          t####  #         #a #         #      #     #      #    #    #a  #    #   #   #    #    #  #
#              #   a# ####### f      r# ##      #b #      ###       #     #   r #   r#     #    #   # b # t #   #      # #
#  #########   ###### #     #       a #  #      ####      #          #r   #    #     #    #     #   #   #  #    #      # #
#  # l     #          # ##  #  ###### #  #   b          f #    f t  #    f#   #     #     # l  #    #  #    #   #  tr #  #
#          #          #  #  #  #    # ## #t##   tg####### #       ##     #    # r  #  t   #    #   #    #f   #  #    #   #
#### ##    #      gtb #  # ##  # ## #    #  #     #     # ###    #    f #    #      #     #    #    #    #   #  #     #  #
#  g  #    #          # b#     #  # ######  #     #  ## #   b   #       #    #      #     #t    #l #     #  #    #   #   #
#  ## #    # ##       #  #     #  #    b    #     #  #  #     f #       #    # f    # r   #     #  #   f #  #    #   #   #
#  #  #    #  #  ######  #     ## #         #  ## #  #  #        #  t r #    #   l  #     #    #    #    #   #  #     #  #
#  #  # ####  #  #       #        #   b######  #  #  ####         ##     #    #    #      #    #   #    #    #  #    #   #
#  #### #     ## # ##    # ########  b #       #  #      f          #     #   #     #     #   f#    #  #    #   #     #  #
#       #        #  #    # #           # ##    ####                  #    #   t#     #    #     #   #   #  #    #      # #
#       #  #######  # ## #      #      #  #   b                     #     #     #    #t    #    #   #   #   #   #      # #
# ####### A#        #  # #####  ########  #                         #     #      #b   #   A#   #    #   #   #    #    #  #
# t        #  #     #  #     #            #      # ########## #      #     #    #    #    #   #     # b  #   # r  #   #  #
###a     f #f #     #  #     #  b    #    #      #          #  ##     #   #    #    #    #    #     # t #t   #     #  #  #
#        t #  # f f #  #######       ######      #   b      #    #     #  f#f #    #    #      #    #   #   #     #    # #
# #   # ## #  #     #                            #          #     #   #     ##     #   #       #     #f #    #   #    t ##
# #   #  # ####    t#      a   b                   ##########    #    #           #   #      b  #   #   #   #     #      #
# #   #f #          #    a   # # ####    # ####### #g    t    r  b#    #   r     #    #        t #   #   #   #     #     #
# #   ####   # ##   #        #    g #    #           ##     A   r#      #         #   #    t        #    #    #    #    r#
# #        r #  #   # ##  ## #g#    #  b # ##      #  #         #b    l l#         # #       f #     #   #     # A  #    #
### ###   ####### ### ##  ## ### #### ## ####################    ##  #########c    ######### f    ##    ##  g    r   ##  #
#                                     r       b                 ##     #     #################     #     ##  g      c#####
### ###   ####### ### ##  ## ### #### ## ####################  ##c #  ##c       c     ###    ##    ##     ##       b #####
### ###   ####### ### ##  ## ### #### ## ####################  #   ##  # c g    t     ##   gc ##   ###     ##g     #    ##
#t    c      b     A                       r                       ###               c#  t g       ##       ##t   ##     #
### #### ######## ### ##  ## ### #### ## ####################                ##########   ###########     r  #    #  ### #
### #### ######## ### ##  ## ### #### ## ####################          #   ###        #    ##########                ### #
#                              t                                       ##  ##         ####  #    # c  #######       #### #
### #### ######## ### ##  ## ### #### ## ##################    c##     #   #          ####            #######c       ### #
### #### ######## ###  #  ## ### #### ##  ##############    #          #   #      #   ####       c#  ########c #     ### #
#               r      l       b   r    b    t                #   ##   ##  ## tg  ##   r     b#####            ##    ### #
### #### ######## ### ##  ## ######## ########################     ##  #    #      ##      ####   #            # g   #   #
### #### ######## ### ##  ## ######## ######################        ##   #########          #          ##### ###     #   #
#      g                                b     A              #  #    ##   #   #  ##    #    #   #       #  #   #     #c ##
### ############# ### ##  ## ######## ########################  ##    ###     #  ####  ##   ##  #######    ##  ##### #####
### ############# ### ##  ## ######## ########################  ####  ###     #  ####   #r   #  #######    ###  ###      #
#                                  l         r                   ###  ###   ###  ##g  #########   #c    #  ##    #       #
### ############# ### ##  ## ######## #########################             ###  ##   ######     ##c    ## ##            #
### ############# ### ##  ## ######## ################                    #####  ##   #####      #      #####     ## #####
#              c    l           l       l                            ######           #####c #####  #   ##         #   # #
### ############# ### ## ### ######## ############### #######   ###########    ##     #       #  #  ######      r  #   # #
### ############# ### ## ### ######## #############   #######    #          #   ##    #    ####     ######         #  ## #
#l           c      g                        t                ####          ##   #    #    ###      ######         ##  # #
### #################### ### #######  ####################### ### c         #  ########    ##   ##########          #    #
### #################### ### ######  ########################  ##           #  ######## t ##    ##########r r    c#####  #
#                         r       t g                           #  ######   #  ########   #    ###########        #####  #
### #################### #############################                         ########  l#  #a ##########        #####  #
### #################### ############################  #####      r         # ######      #  ##  #########            #  #
#                    g                        t              ##     ###  ##   ######  b#####  ##  #                   #  #
###############################################################  ####   c     #       ##       ##     gr  #############gg#
##########################################################################################################################
