metadata:
  gen_time: 6.3269431591033936
  timestamp: '2025-04-11T22:27:59.821653'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '

---
######################################################################################################
################    #####               ####   ######           ####    ###          #####           #
################    #####                       ####            ####    ####        #####            #
###############      ###    ##     ##            ##     ###     ####    #####      #####            ##
##############             ####   ####                 #####     ##     #####     #####             ##
#                         #####   #####      ##       ######             ###     #####              ##
#               ##       ######   #####     ####     #######                    #####          ##    #
##             ####     #######   #####    #####    ########       ###         #####          ####   #
##            #####    ########    ###    #####    #########      #####       #####          #####   #
##            ####    #########          #####    ##########     #######     #####          ######   #
#              ##    ##########         #####    ###########    ########    #####          ######    #
#   ######          ###########        #####     ##########    #########   #####          ######     #
#  ########        ############       #####      #########    ##########   ####           #####      #
#  #########       ############      #####        #######    ###########    ##            ####       #
#   ########       ############     #####          #####     ###########         ####      ##        #
#    #######        ###########    #####    ##      ###      ###########        ######               #
#     ######         #########     ####    ####               ##########        #######           ####
#      #####                        ##    #####                ########          ######          #####
#       ###                              ######    #######      ######    ##      ####          ######
#                             ###       #######   #########      ####    ####                   ######
#                            #####     ########   ##########            ######                  ######
#                           ######    ########    ###########           ######   ######         #### #
#  ################         ######   ########      ###########          ######  ########         ##  #
# ##################        ######  ########        ###########         #####   ########   ###       #
####################        ######  #######          ###########         ###    ########  #####      #
####################         #####   #####    ####    ###########               #######   ######    ##
###################           ####    ###    ######    ##########               ######    ######   ###
#                      ####    ##           ########    #########               #####      ####    ###
#                     ######               #########     #######    #####        ###               ###
#                     #######             ##########               #######                         ###
####        ####      #######            ##########                ########            ###         ###
#####      ######     #######   ##       #########                 #########          #####         ##
#####     ########     ######  ####       #######     ###          #########          ######         #
#####    ##########     #####  ####                  #####         #########           ######        #
####     ##########      ####   ##                   ######         ########            ######       #
#         ########        ##                          ######         ######              ######    ###
#                                   #############      ######         ####    ##          ######  ####
# ##                               ###############      ######               ####          #####  ####
#####            ####              ###############       ######              #####          ###   ####
#####           ######   #######   ###############        ######             ######               ####
#####          #######  #########  ###############         ######             ######               ###
#####          #######  #########  ###############          ######             ######               ##
#####           #####    ########  ###############           ######             #####                #
#####   ##                #######  ###############            ######             ###                 #
# ##   ####                #####   ###############             ######                                #
#      ####   ###    ###    ###    ##############     #####     ######                 ####          #
#      ####  #####  #####          #############     #######     ######               ######     ##  #
####   ####  #####  #####          ############     #########     ######        ###   ######    #### #
#####  ####   ####  #####    ###   ###########     ##########      ######      #####  #####    ##### #
#####  ####    ##    ###    #####   #########      ##########       ######     #####  ####    #####  #
#####   ##                 ######    #######        ########         ######    ####    ##     ####   #
####                      #######     #####    ##                     ######    ##             ##    #
###                      ########      ###    ####            ##       ######                        #
##      #############   #########            #####           ####       #####           ####       ###
#      ###############  #########           ######          #####        ###           ######     ####
#      ###############  ########     ##     ######         ######                      ######     ####
#      ##############   #######     ####    ######        #######                       #####     ####
#       ############     #####     ######    #####       ########    ###     #######     ####      ###
#        ##########       ###      #######    ####      #########   #####   #########     ##         #
######    ########                 ########    ##      ##########   ######  #########                #
#######    ######                  #########           ##########   ######   #######          ###### #
########    ####                    ########           ##########   ######                   #########
#########               ######       #######     ##     ########     ####                   ##########
# #######              ########       ######    ####     ######             ###            ######### #
#  ######     ###     #########        #####    #####     ####             #####          #########  #
#   #####    #####    #########         ####    ######           #####     ######        #########   #
#    ###     #####    #########          ##     ######          #######    #######       ########    #
##           #####     #######                  ######         ########    ########      #######     #
###           ###                               ######   ##   ########     ########       #####     ##
###                                      ####   ######  ####  #######      ########        ###      ##
##                                      ######  ######  ####  ######       #######    ##             #
#                        #######       #######  ######  ####  #####         #####    ####            #
#                       #########     ########  ######  ####   ###                   #####       ##  #
###                     #########     ########  ######  ####          ####           ######     #### #
####                    #########     ########  #####   ####         ######          ######    ##### #
####       ##           #########     ########  ####    ####         #######         ######   ###### #
####      ####           ########     ########   ##     ####         ########        ######   #####  #
###       ####            #######     ########          ####          ########        ####     ###   #
#         ####             ######     ########          ####           #######                       #
#         ####              ####      ########          ####            #####                        #
#         ####     ####                #######          ####     ####                    #############
#          ##     ######                ######          ####    ######         ####     ##############
#                ########        ####    #####           ##     ######        ######    ##############
#               ##########      ######    ####                   #####       #######     #############
######         ###########     #######     ##                     ####      ########                 #
#######       ############     #######            ############     ##      ########                  #
# ######      ###########      #######           ##############            #######    ###          ###
#  ######     ##########       #######    ###    ###############           ######    #####        ####
#   ######     ########         #####    #####   ################           ####     ######       ####
#    ######     ######    ##             ######  ################   ####             ######        ###
#     ######             ####            ######   ##############   ######            ######          #
###    ######            #####    ###    ######                    #######           #####           #
####    ######           #####   #####   #####                     ########           ###            #
#####    ######     ##   #####   #####   ####    ###        ##     ########    ##                    #
######    #####    ####  #####   #####    ##    #####      ####     #######   ####           ##     ##
#######    ###    #####  #####    ####          #####      ####      ######   #####         ####    ##
#######          ######  #####     ##           ####        ##        ####     ####         #####    #
#######         #######  #####                   ##              ##    ##       ##          ######   #
######          #######   ####                                  ####                        #######  #
#####           #######    ##     ##                 ##        #####                  ##    ######## #
####      ##     ######          ####               ####       ####         ######   ####   ##########
######################################################################################################
