metadata:
  gen_time: 9.735871076583862
  timestamp: '2025-04-18T22:45:25.445843'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
### #####           #        #      g     # #  b#####   t  l          g r       t           r                            #
#   #         #     #        #            # #  ##      g               Ar                                                #
# ###         #     #        #    ##  b   #    ## ###  g                          f                 f                 l  #
#             #                  t    ### #    ## #                                                                      #
###           # r  fb           f     #       l## #                           b                   g                  tt  #
# #           #    #        ###       #  t     ## # lg    ###                                       g   r                #
# ### # g #####    #        t         # b   ## ##                                               l              b   g     #
#   # #   #  b     # #                          ###     ###                                   f                          #
#   # # ### ######## #   g               g     c        #          t                           g                         #
#           #      l #     b  t  #####                  # ### gt                  t                      f               #
#         ### ####   #           #            c         # #   r   r   r           f                             l        #
## ### #      #l    t#           #                 t    # # ############################## ###################### ########
##     #      # ######              g  b    l             g  ############################# ###################### ########
####   #      # #                    #  #####             l                      g     f                                 #
#  ##l #      # # #### l             #      #        g## f #                                                             #
## ##  ###    # # #                        A#    # t       #    b                   b                                    #
## ##    #    # # # ###### ######f          #    #                       f                             f           f  g  #
## ##  # ####c# # # #      #       t         r            f b                 c                                          #
## ##  #          # #      #b############     t  #### # #####  l                                                         #
## ##  #  g       # #      # #       g t    b    #    # #  g     f                                           t           #
## ##        #      #        #   ##### #######   # ####b#           f                                                    #
## ##        #      #        #   #                 #    #l                             b          g                      #
## ## #      #           #####   # ##     ####lt   # ####                      rg       g                 g      l       #
## ## #      #   g                 g         g   t   # c                                 f    l r                        #
## ## #      #              t                        #    r        r                                                     #
## ##  l #tl #       l                  l      #   g #                                   g          a              g     #
##  ###  #           #                ###      #     #        f          r                                      g        #
##    #              #        ###### #####     #     #                        f                         g                #
#     ####    ###             t      #   #                   ################################################ ############
#      ####                #####     #   #              ##################################################### ############
# g   t   #         l          ##        # # ####       #      g        t       l                       gr               #
#####     #  #######           ##    ##### # #  bf      #                                                    f           #
###### #  #  #     #           ##    #  l l# #          #                                                    g f         #
#    # #  #### l g #           ##    #     # #        ###                         a   t                                  #
#    # #           #     b######     #   g   #   t c     l                                        l           r          #
#    # #  ####   tt#                         #                          g g                                   g    f     #
#      #     #     #   b      #####f ####    #        t             r A                                                  #
#      #     #     #                 #    t l#                    r              b                       f        A    b #
#   ## # #####     #            ######  ###  #         ####                            l                                 #
#        #                      #         #         #                                             r   r                  #
###  t        ### ####r   #######        ####t l  ## ##    r    t   #          #        # #           # ### # b## #   ## #
### ############# #### t  ##   t         ####     ## t# t####       # ##                # #  ######   #     #  ###    ## #
#   ############# ####    ##t            #### t    #  #  ####   l ll# ##                # #           #######  ##     ## #
# # ###           ####    ## r           #### l    #  ########      # ##   l     ##     # c                    ##        #
# # ###       t   ###     ## r             c       #  #########     #         #         #  c  c       ######   ###  ######
### ###     #########     ##                      ##  ##            #    l  ###         # #                  b ## # ######
###  ##     #########     ## #####                ##      ######    #     c l    g # g  #A#    ##############  ##  ###   #
###  ##   r          g    ## #####               r##t     ###       # # #   ###l   ##   # #                    ##   ## ###
#######                   ## #####           g    ###     ##        # # #               # #    ##         l         ## ###
#######               g   ## #####    #####   r   ###    ###        # # #    ########  ## #    #      #  ##  #### b ## ###
#######                r  ##  ##      #####       ###  r ####           ##   #                 #      #                  #
#######   l               ##  ##      #####   ###############                   #####        l #    # #       ###  ### # #
#                         ##  ##      #####   ###############   ##  ######                 g   #    # ##      ###  ### # #
#                         ##       t  ######  ###############   #           #            #    l##   #                  #t#
########           #########            ####  ##   ##########   #    ##     #   ###      # #        #####  ############# #
################# ##########             t## ###   ##########   ##   #     ## c          # #######    c                  #
#################   r   ####    g        r## ###   ##########        # l       ####     ##          ##    c    ######### #
#################      r####                 #          r  #######   #     g                ######      ####       l     #
############################                 #             ##        #            l  #####  #       ##l       l          #
#     g               ######  c            ###             ##           ##                  # ##             t     #     #
#####     #########            ##########  ###             ##          g c   ##     ####### # #l   ###      ########     #
#####     ###############################  ###gt   t       ##  #####       c ## #   ####### # #                          #
#####     ###############################  ###   b     ######              # ## #   ##      b                            #
##                ##                      t###         ##        c       ### ## ##  ## ##   b    ##        #   ##  l    ##
# b #  l  # f     ##      g      ######    ###    t rg ##      ###       t   ##     ## #   ##  l ##      ###    #        #
#   #######         gr       r   ######    ### ##                #  c    ########## ## #    #    ##             #   a  ###
#   #######           #################A   ### ##############           t########## ##           ## ##          ##       #
#    #######   t      #########    #### A  ### #####   ######          # ##  #  #           t  # ## ##         b         #
#    #######      r   ##        t  ####    ###        g##             ## ##      #     f      #  ##             ##    ####
#    ###################        g  ####    ###         ##                ###      #   ################          b c      #
#     ##################           ####             g        ##############        #  ################    #              #
#     #### l                                          g  l   ##############     l   # ##                 c#  ##########  #
#t    ####   ####            g                        #######   #    t#  l   ##      ### ##     #        ##              #
#   #############          g g                        #######        #                ## ## #######           ###        #
#   #############b####     g   r  t   t    ################## ##########              ## ## #######   #####            l #
#   ##      #####t########              #######  t########### ##########  #####       ##    ##               #############
#   ##      ##### ##################    #####                 ##              #  #  # ######## ##    ####### #############
#   ##     g##### ##################  g                      ### ##              #  # ######## #     ####### ##    ##    #
#   ##      #####     ############         r        r        ### ##                 #  l  r    #    ###  #  c## ## ## ####
#   ##      #####       g                g                       ##  # ######       #    #######  l# ## #    #  ## ## ####
###### ######  #####  ##  ###    ###  ##  #####  ############           ## #  ###   f    ##  r  ##          r    ##c#  # #
#      t                           a      b                          ###   # ###     lr ####    ###       t     ####     #
# ##  ## b##########################################  ##  ##          ###   ###         c        ##                      #
#                                                     r         t        r                        # t     ###            #
###############  #########  ######  #########  ##############    ###  ###   ###     r###b                ###             #
#                                                        tr     ###    ###   ### #    ###                     t        ###
##  #######  ######  ####################  ######  #######  #  ###            ## ##    ###               ###            ##
#       gb     b             t                                         ###     # ###    ###             A ###    ###     #
#######################  ###  ##  ###  ######################           ###    t  ###                      f      ###   ##
#                                                              ###          Ab                       ###          b###   #
#########  ####  ##  ####################  ##f ####  ########   ###         r         c   t           ###             c  #
#                                b                 l r  f   b   b###  ###      ##                      ###      #      f #
#  ##  ##################  ########  ##################  ## t#         ###    ####   c    ####             r    ##      ##
#                                  b                             ###    ###                ##                   ##     ###
##########  ## l###  ####################  ###  ##  #########t    ###    ##t             t       ###         c  #   t  ###
#  l             g                            b             b      ###    #    # #   #          ###    ###              ##
# #  ####################################################  ##  f              ## ## ##         ###     A###              #
#       l         r          b            b  l                  #             ## ## ##  ###              ###  t          #
##########  ############  ##  ##  ##  ##### ######  #########   ##      ###    # #   #   ###                 tt       ####
#                                           b                   #        ###    bc        ### #                t       ###
##  ##  ######## t##  ##################  ##  ########  ##  #   # ###     ###              ## ##                 ###    ##
#                           l     b          l                   ###        r        ###    # ###  ###          ###      #
# ## ############### ### r##  ##  ## a#######################                         ###      ##   ###                  #
# br               r bf          t        l                                 ###        ###      #    ###        ###   #  #
# ####  ####  ###  ########################  ###  ####  ####r# #   #       ###                                   ###  ## #
#  b                  f        r                l    f       # ## ##   #          ###                     ###  c  t   ## #
######################## r###    ###  ######################## ## ##   ##  ###     ###  t         ####     ###         # #
#gf                     l                                    # #   #   ##   ###     ###  c ###    b##   b   ###    l     #
###  ####  ####  ##  ####################  ## b####  #### f##          # b   ###     ###    ###c                         #
#                                 b      b         t                                         ###   ##   #  b         r   #
##########################  ##  ##  ############################    #              t ###          ####  ##      # #      #
#                         t                                   ###   ##  ###           ###               ###       ##     #
###  ### a##  ###### #  ##############a ########  ##  ###  ##  ###  ##   ###  ###             l          ###   ## ##     #
#       l          r r                           r                  #          ###       c    ###              ###     # #
# ##############  #########  ####  #########  ###############  ###       ###    ###      #     ###       l      ###   ## #
#          a             t       b                            ###         ###       t    ##    t         ###          ## #
###  ################  ################  ################l ## ##    ##     ###           ###   ###      ###  g  c     f# #
#     r                   a                       bb          # c  ####     ###           ###   ###            #     c   #
#######  ##  ##############  ####  ##############  ##  ######                      gc            ###    ###    ##        #
#g         r                a                  l  r    a                                          ###    ###   ##       ##
##########################################################################################################################
