metadata:
  gen_time: 18.617643117904663
  timestamp: '2025-04-18T22:48:54.891487'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#   ### f ##### ##   ### ####        ##  ##      # ### ### ### ### ### ### ###           #     ##   #  ##     #  ##  #   #
#   ##      ##  ###  #    ####   ##     #   #g## g  #   #   #   #  #   #     #              # # # # #   ##  ##  # ##  #  #
#  ###     g #   ##         ##    c    ##   ###  # # #    ## ##  #   # # ### ###    #    #   ##   #  ##     #  ##  #     #
#   ###  #   #   #       ##  ## ###   ##    ###  #     #  #              #g    #r   #   r#  # # # # # # ### # # # ###   ##
#g  ##   #           ##      ## #    ###  al  ## #     # #  ## # # ### # # ### ###     ###  #   #  ##   #     #   #     ##
#  ####   ## r#    # ###             l###  ##    ###     # g#  ##  #   #   #  #  #        a # # # # # # # ### # # # ### ##
#   ##    ### #  ### ##     ###   ##  ##  #####r   #     # # ### # # ### ### ### ###r         #   #   #   #     #  ##    #
#       #   #    A   ##    #####  ##   # r ## ## # ###        #  ##  #             #        ### ###r### ### ### ### #    #
# c##    #   ### ##   ##  ### b#  ###             #        ### # # ###    f        ###                            #      #
####  tc ##  ######       ##    ##  #l     ##    ###g###                               b                 b        ###    #
####  r    ##  ###   ##    #    ##   ##    ####   b #  #     ### ###         g     # #  g        #     b            #    #
## ##  # rl      #  #####  #   l     ####  ## ####  #  ###                         # #           #            l     #    #
#      ###    g     ##     ##  ### ##  ####              #                ##                          r    #        ###  #
#  ##         ##r  ##            # ##   ##    ##  ##b### ###                      f             c          #b        f   #
#       #     #### r    ##    ##   ##    #   #### #r   ##  #    b               ##                                  # #  #
## ##  ##   ##  ####   #####   g  ####   #   ##  # ### #   ### ### ### ### ###      g     #   #    l                # #  #
## ####     #    ###  ###      ##   ##              #    #   #  #   #   #    #            #   #     b       r            #
#   ##      #       # ##   t   ####   #     ##   ### ### ###b##  ##  ###  ## ###                          # #            #
#   ##    ##    ### #  #   ##  ## ### # l # ###  #   #         #  #  a#        #                g         # #            #
#  ###   ###      #        ####       ##  # ##  g# # # ### ### ### ### ### ### ### ### ### # #           g       ###   g #
# ###     ###      ###    ##      ##    ##  r#     #  b#     #b     #      #       r#      # #f                    #     #
#  ###    ##   #   ####           ## ## ## c #   # ### #     ### ### ### ### ### ###  ## ### ### ### ###  ##     #g### ###
#   ##  ## c   #     ##  ##    #  ##    ###     ##       b         #  #     #     #   #   #f      #l    #  #   b #  b#   #
#  ####       ##  ##     #    ####  ##   #      #### ###           # # ### ### ### ### ### ### ##  # # ### ### ###   ### #
#####      ##     ####l ###    ##    #       #     # #          b                       #   #   #  #  #  ##  #g    #   #g#
####      #####    ##    ##  # ##  #l#  #  ### A#  ###           f                   ### # # ### ### ### #   # #b# # # ###
#l#   ##   ## ###  ###   ##  #  ## #    #       #### #             # # ####          b       #   #  #  #   # A ###   #   #
#    r#       l     ##t  ##     ## ##  #          #      g         ### #        #    # # # # # # # ## g# ### ###   # # # #
#  t      ##  ##    #   l ##         ###       ### ###             # ###        #    ###g  #   #       b #    #   ##   ###
# ##     ###       ###    ###  ###        ##       #         #   ### # #             # # ### ### ### ### # ### ### # #   #
#   ##    ###   b####   ##  #  #     t  g  ###  #### #       #   #           f         a           #  f    #   b #   ##  #
#    #    ##    ####        l##    ## t #  ####  #   #      r    #                             g   ##  ### #     ### # # #
###  #  ##      #t # b ## t  ##  ###   ####   #l #b# #                 t g           f               # #           #   # #
# #     ##    ##    ##      ####r###    ## l   ##  #  r                    r                         ###           ### ###
# #  t  ###  ### r  ####  l #  #   ##  ###     ### # #         b                   r              g  # #                 #
# ##  ##  #   #   ##  ####cr r  ##       ##  ##  #   #                            b             g                        #
#  # r#    #      ##   ##       ####             ### #         f   #        ### ## ##                                    #
#          ##     ###  ##  ##   ## ###  ###                        #r       #           ###                   ### ## ##  #
#            ##     # r ## #  ##          #   #### ###          #           #           #         f           #        f #
# #   ## l## ###   l  r ##     r   ##        #####  #      g    #                     t #                     #   b      #
# #   #   #  ##  ##      ##        ####      ##  # ###          #                                             # f        #
# g       #   #   ###      ##      ## ###  ##     ##   r        #                                              r    r    #
#       ##        ##       ###   ##   l   r      # #b#   t      ###        ##  #   b                                     #
###  t ###         #  ##    ####               # #   #               a         #     r             r                     #
#    ####        r #  ####  ## ###  #    ##   ## ### #        ab# #       g          # #  ### ### ### ### ### ###        #
#       # A ##  ###    #####      ### ##   ##        b          # #              r   # #  #  #r #      #   #  #          #
# ##       ########      ###   ## ##g #    ####    b       ##  g                          # ### ### ##  ### ###          #
#####        ###  ##  ##       ##  # ###  #r ###   f                                              #  #  #                #
###  ##   ##        ##    ##      g# ##   #   ##                                r                 ### ###                #
#    ####          t##        ###    ##  ##    ##  ###A###b### ### ### ### ###   #       r                               #
#   ### #### ##      ##  ##     #   #### #     ## b#        #    #  #          ###              r  b      r              #
##  ##     ######  g ### ####    #  ##   #   #   # # ### ### ### ##  ### ### ###                   #        g      l     #
#    #       ## ###   ## ## #    ###        ##   #   #   #   #     #b      #  #  r  #### ##        #         b           #
#    l##   l          ##     ##             ##   # ### ### # #     ### ### ### ###  #    f       b                       #
# #   ####  ###     ##       ###      ##   #### t  #   #  ##         # #         #  #              #                     #
# #  #  #########  ### ##r    ##    ##    ###  ### # # # # ###  b    ###     g   #           a     #   #                b#
#  ###    ### ##   ##  ####  ###  #### r  ##  b####  ##  #  #    #   # #       ###           l         #        t        #
#  ####        #    #   ##  ###   # #      #  ## # # # # # ###   #             f          ##         g                   #
# ##  #       ###   #  ##    ##         t  #  ##   ##f #             ###  # #                                           ##
# ##    ####        ####  #### g  ###        ####               l## ##      ##      ####            ## # ##        ##    #
#        ##    ##    ##    ##      ###                     t        a####                          ##     ## #     ##  ###
# ##      ##   ###    ##  #### g      g   g  ####                    a##    ##      ####           ##    t## ##   ##    ##
#  ##  ##  #     ####  ####  ###  g###ga  r   ##                ##   ####  ####      ##      g     t##     #t##   ##     #
#   #  #       t  ##    ##a   ###   ###   b  ####              ####                     t   t        ##     g ##   ##    #
#          #  #  ####  ####        ####   b  ####              ####  ####  ####     b                 ##      ##    ## # #
#   #  #  ##  ####  ####  ##  ###  ###b       ##    ##    ##    ##     #     #    ##  ##  ##           ###     ##    ### #
# ###   ###    ##          #####    ###      ####  #### g ###    ##  # ##  # ##  ####### ####    ##     ###    ##    ### #
# ##     #    ####  ####    ##        ##     A  #    t# #   #  #  # ##  ####  #     ##   #  ##  #####           ##  ## # #
#  ##  # ##      ####  ##              ##  ##     #     #           #    ##     #            #  #  ###  ###      ####    #
#   #  #  ##      ##    ##     r      b ####    # ##  # ##  #  #  # ##  ####  # ##   b                 l ####     ##     #
#          #     ####    ##  ##    ##    ##   b##  ####  ####  ####  ####  #### b##  ##  ##  #  #  ###     ####  ####    #
#   #  #  ##    ##  ##    # ####  ####  ####  ##b   ##    ##    ##    ##    ##    ###### #####  #####        #####  ##t  #
# ###  ####   ###    ##     #  #     #     ####    ####  ####  ####  ####          ##      ##    ##           g## l  ## t#
# ##    ##    ##  r  ##          #          ##    ##  # ##  #  #  ####  ##                 g           g  l          ##  #
# ###  ####   ###t    ##       # ##  #  #  #### t##     #          ##    ##                                           ## #
#   #  #  ##    ###gf ##    #g##  ####  ####  ####    # ##  #  #  ####  f##   # # ## ## ## ##    ## ## ## ## ## ##    ## #
#          #     ###   ## # ###    ##    ##    ##     # ##  #  #          ## ## ##############  ###################    # #
#   #  #  ##    b      ## # ###   ####  ####  ####      #         ####    ## ## ##############  ###################      #
#                ###    # # ##    ####                          t  ##      # #   ## ## ## ## #  ## ## ## ## ## ##a##     #
#   #  #  ##     f###              ##   ####  ####                     f             t  b    t ba                  ###   #
#          #     ####             ####   ##    ##                    g                                              ###  #
#                ###    ##        ####  ####    b   #t# # # #   ## # # ## # #t# #               l   a           g  ####  #
#                 ###t ##          ##   ####       ## # # ###  ##### ###### ### ## g a  t                     l    ###   #
#          #      b ####  #              ##        ## # # ###  ##### ###### ### ##                                  ###  #
#   #  #  ##  #   g g##     # #                     # # # # #   ## # # ##a# # # #                              ##        #
# ###  ####   ###   ####    ###  #                 tf                                                  b      ####  ###  #
# ##    ##     ###  ####    ###  #            ##                                g                  t  A ##    ####   ### #
# ###  ####          ##     # #             #####       ##                                             ####    ##   #### #
# ###  ####    ###  ####  #                ###  ### g   ###    ##   t # # # # #  ## ##   b ##     ##         g####  ###  #
# ##    ##      #####  ####               a    A ###    ###t   ###   ## ### ### #######   ####   ####  ####   ####   ### #
# ###  ####       ##    ##         A       ###          ##           ## ### ### #######                 ##     ##   #### #
#      ####            ####                 ###  ###    ###    ###    # # # # #  ## ## t  ####   ####  ####   ####  ###  #
# ###   ##    ##      ##  # #        #  #         ###t  ###    ##     l                    ##     ##r       b        ### #
# ##   ####   ###    ##     ##       #  #   ###         ##     ###           f    f      g####   ####  #### b ####  #### #
# ###  ####   ###    ##   t                  ###  ###          ###g  ##       #           ####   ####   ##     ##  g###  #
#       ##    ##      ##    ##     t #  #r  ####   ###         ##   ####     ## #          ##     ##                 ### #
# ###  ####g  ###     ##    ###   g  #  #   ###a  ####         ###  ####     ## #         ####   ####     t   t  g     # #
# ##          ###     c##           a        ###  ###                ##       #                  ####         ##         #
#          l   ###                   ##   #          ##    #        #########   #   ##   #####      #  ###       ### # # #
#                      g  l               #           #    #        t                #f   ####      #   t        #   ### #
#              l         c          r                   #  #               #     t       ##  # ######t  #             ## #
# #    #####  #  clf                    ### ####    ##  ####    ##     #####  # ##########      ## f    ##    #########  #
# ###  #  #   ##########     ### ###### #     r######    ##      #  ####      # ###  ##l        ##      ##   ###         #
#   #     #     ##       ## ##       ##     #     #      ##         #     l   #      ##         #        #  ##           #
#   #     ##    ##      b## ## g     ##    ##     #      ##      #  ##t      ##      ##                    l##      l  # #
#   #      #   ###########   ### ######    #     ##      ##     ##  ##       ##  t   ## l      ################ ######## #
#          #   #              b            #     #       ##         ##    ####    ###### ####   ####             ##t     #
#          #   #                    t      #  g  #       ##         ##   ##       #       ##               #   t ##      #
# ###  ###### ####                   ## ##############   ####       ##  ##        ##      ##               ##   r##      #
# ###  ###### ####                   ## ##############   # ##       ##  ##        ##      #    #           ##     #      #
#        t #g  #f            g                   #       #     ##   ##   #       l ##          #           ##            #
#          #   #   l           g       #   #     #       #     ######    #         ## b  ##### ## ##      #### ######### #
#   #  a   #   ######### #   ### #######   #     ##      #       ###     #          ######         #     ##     ##       #
#  b#     ##    ##       ## ##       ##    ##     #      #      ##       ##############                 b##    r##       #
#   #     #     ##       ## ##       ##     #     #      ##     ###       ####        ##     # ############# ####        #
# ### ##  #   ############   ############   #  ######t    #### ## ##   ####            ##    #  ###           ## t  ######
###    ########              g          ########    ##  #####  t  ##  ##            t  ## ## #    ##          ##   ##  A##
# t         #                             #                 ##     #  ##         #############f   ##    ######### ##     #
#    f      #         b                   #            #t    ## ####   ## ########               ##    ##   t            #
##          #  ###     t     g       ###  #          # ##     ###          ##                    ##    ##               l#
##########################################################################################################################
