metadata:
  gen_time: 7.530925989151001
  timestamp: '2025-04-18T22:52:27.284241'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##            #              g          #           #             f  #           ######f # #    # #f        ##   #     ###
##            # # #          g        rb# #        a#    #           #         ########  #   ####     ######## #   #######
##         f  # # #                   t ###         #    # r         #      r                                            #
##            # # #                       #         #    #           #    b    #### # #        ##      # ## ##        #  #
##            # # #                     # #         #    #           #              #            #       ##   #        # #
##            ### #       t          b  ###         #    #          a#         ## # ###  ### #         #       #####  ####
###########   #     r   f         t    rt           #    #           #          # #   #      # #           # #     #  A ##
#  b      #   # # #                 b               #  t #          r#          ###   #      ### b  ##     ###     # #r ##
#f                                 rb      ##########t   # c         #         ## #########     ### ##    ########## #####
#       b # g # #                          #             #           #                    ##  b t##   #           #   #  #
#   ###  f#   # # #   b                    #             # f         #     f    # ##### ##### ###### ##### ##### ####### #
#   #                                      #   f         #           #          # #   # #   # #    # #   #f#   # #       #
#   #t#   #   # # #  b                     #           b #      b  f #          ##    ###   ###          ###   ##       ##
#   #                    g                 #             #      g    #   f     ### #####  ####  #  #######   ##   ##### ##
#   # #   # b # # #                      gl#             #           #                                            ###    #
#   ###   #   # # #                        #             ########    #        f                   #       g     f # #t   #
#   #                b                     #         r          ######         ##### ############ ################# ##  ##
#   # #  ##   ### #           b            # r                                   ##        ##  #   t      ##            ##
#r  # #  #    #            b               #                         r    b    ####### ###### ###### ####### #########  ##
#   # #  #    # # #        b     f         #b    t                                                                ##    l#
#   # #  #    # # #                    b   #bt                                 #### #       ##   ################### #  ##
#   # #  #    # ###           ###          #g                               l    ##   # #    #       ###  ###  ###   #   #
#   ###  #f  g# #             #       g    #       ###                             #  # #  # #  # #  # #t # #  # #       #
#        ##   # # #           # #        a##b        # l                r        # #b # #r # #  # #  #A#  # #  # #       #
#  b      #   # # #    r      # #         #     r  # #              # ######     # #  #b#  # #  # #  # #  # #  # #       #
#        a#   # # #    ####   ### l       #        # #              #      #            #  # #  # #  # #  # #f # #       #
#         #  g# ###       #     #         #        # #              #      #     ###  ###  ###  ###  # #  # #  # #       #
# r       #   # ###    #  #   # #         #        # #              #      #   ####################### ## # ## # # #    ##
#         # r # #      ####   ###       t # f f    # #      gb      #      #   ##b                 b   t         t       #
#         #   # # #           #           #        # #              ########                     f     f                 #
#        ##   # # #           # # f    b  ##       # #    t         A fl        ###################### #  # ## # # #    ##
#   ###  #    # # #           # #          #       ###             r      r    f##    #    b  ##    t  t  #      #      ##
#   #                         ###          #  tb                                #### #  #### ### ####  #  # ## # # #    ##
#   # #  #t   # #                          #                                   t#  # #   ###     ##    #  f ##           #
#   #a#  #    # # #                        #              g                  f     #            #r#          #           #
#   #                                      #                                f   #  # ##### ###### # #     #  #   # #    ##
#   # #  ##   ### #                     g  #             b              f A    ##r #          b           #              #
#   #f#   #   #                            #                    ######          #### ############ #       #  #   # #    ##
#   ###   #   # # #    g                   #             ########    #                       ###  #       l  #          ##
#   #                       A              #             #           #         t# ##      #  # #  #                      #
#   # #   #   # # #                    f   #     f       #          r#         ##  # ####f#### #  #              # #     #
#   # #   #   # # #     g                  #             #           #   rg     #  #      ##   #f #                      #
#   # #   #   # # #                        #             #     a     #          #  # #### ## # #  #              # #    ##
#   ###   #   # # #                        #            l#           #  l       #  #l#  # #  # #  #              # #     #
#         #   # # #    r       b           #             #   r      g#   r     ##  ###  ###  # #  #              # #     #
#         #   # ###                        ##########  f #          f#         ####### ####  # #  #              # #    ##
#   g     #   # # #                        r        #  g # c         #                                                  ##
###########   # # #                f                #    #           #                             f                   f##
##   gtf      ### #b                    ###         #    #           # b       ### ## # #  #       #   #  # #  #    ## ###
##            #                           #         #    #      b    #         ###  # #    #       #      #    #    #b  ##
##     f     b# # #                a    # #         #    #b   t      #   b     # #  # #    #       #      #    #    #    #
##            # # #                     ###         #    #           #   t       #  # #    #       #      #    #    #    #
##  f  g      # # #                     # # t g g   #    #           #         # #  # #    #       #      #    #   ##    #
##  r         # # #                    r# #         #   f#           #b        ###  #f#   ##       ##    ##    #   ##f  ##
#  ##       #  cc #     ######gc   ###  #      c         ### ####       c       r#  ###c    #          #             #   #
#   #   g   #  cc #######     c     #   ##   t                  #  r            ##   #             ##  # r           #   #
#   #####  c#   t #            t t  #g   #              ##      ##     c        #    #                 #           ###   #
#b  #r  #####              l        #    ## #   ###     #        #  l  # #   ## #    #                 #       ##    #   #
#                                   ##c  #l       # #   #        # ##  #        #   ##                 #       #     #   #
#         ##      # ## #   ##  r     #   #  t     g #   #        #              #   # t             #  #       #     #   #
####      #            #    # #   g  #   #          #     ## #####                  #      ##       b  # g     ##    # ###
#           #  ###     #      #   #  #   ####   ### #   #    #   #     # #   ## # ####### ##       c   # ##     #    #   #
# g  cc     ####       #                            #   #        #                                     #  # #  c#    #   #
#   #    c  ###        ##                       t   #   ##   c  ## c#                                  #  # #        #   #
#  #        #   ###     #  c      f                     r#      #   #                                  # ##              #
# ##   #    #  ####     #        #                g      ##   c##   #                 r #           c  # ##       #    # #
# #    #    #  #    ## ##        #         c              #    #   ##              g  r #     c    ##  #  #       #c c # #
# #   #     #  #       cg  ##    #          c             #    #   #                c   #     #    #      #       ##   # #
# # l   c  ##r         f    # #  ##                     ###    ### #                 #### ###      #      #   # g  #   # #
# #c            #                    #   ##         r     #    #   #r    c      #### #    #        #     ## c #    #   # #
# #        #    #   c                     ###   ### ##   c#    #   ##  # #   ##   c#    c #        #     #   r#    #   # #
### c#     ##   #t   c #g                   #   #         #    #   #     #   #     #     ##        #     #   ##    ##  ###
###  #      #   #      #               #    #   #       #### ##### #b    #   #f   ##     #             c #   #      #  ###
#   #   a   #   #      #               #     #  #                  # t   #   ##   #    t #               #   #      ## # #
#g        b #   #      #         #   c #   g    #                  #     #       ##     ##  c            #   #      #    #
#   c#      #   ##   r #   c     #     # #      #          # ##    #     #   c   ##     #               ##   #      #    #
#    #      ##   #     #         ##  # #   ###  ### ##  ####  ## # ### # #   ##   #######           g   #   ##      #    #
#    #  a    # r ##    #         #          b#    #     f              #             b  #           c  ##   #      c#    #
#    #      c##   #  # ##  ##    #       b   #    #        f           #          A    g#  r# # #  ##  #    #  cc   #    #
#    ##       #   # ##        #  ##  # # # ###  ### ##  # ## ### #  ## # #   ##    ##########   #   #  #           ##    #
#     #     r #   # ##     c  c        #        #f   #  #  #  #g # ##c   #    #           # c   #   #  #  f        #     #
#    g# c    f##  # r####              #   #    #    #  # c#  #  # ##    #    #   #       #     ## ##  #  #        #c    #
#     ##       #  #           #        #   # c  #    #  ####  #### r#  c ##   #   #     g ##    #r c   #  #       ##     #
##     #       ###            #        #  ## r      b#  ####  ####  #     #   #   ##       # g  #c     ####       #     ##
##     ###### r###    ###  #  #           #   #     f## #  #  #  # ##     #        #    c  #  # ## #   ####  #### #     ##
##     #   c####    ###    ## # #         #   #      #     #  #     #              #     ######    ### #  # ##  a #     ##
##     #      rl            c c ###  # ## #####  r   #  c  #  #     #        ## ## #######    c        f          #     ##
####c c#   g            c        r#     #   cr# b#####    t####     ####         #     #                     c    #    ###
#  ################ #####  ##  c  #     #     # ##g  #    r ##      #    ##   c  #     #   c ##### ### #### ##### ####   #
#      c #      #       #   # ###### # #### c # ##   #      ##      #    ##     ##############   #  tc   #      #       c#
# c      #      # g    c#      c     #    #####  #   #      ## c r  #       ###     #            #       #      #        #
#  ###          #   b      #                       #                #     c                   #  #                  b   ##
#  #            ##         ##           t        l  # # ###          # #             r        #r##                       #
#               g          #               b       #      #           ## l                    ## #                    #  #
#                t   r     #                ##      # #       l        #                      #     #                  # #
#      r            tb     ##                #       #                 #             t##      #    g## #  b             ##
#                g                           ##          ##   g    #   #              #r      ##    #   #              #l#
# #####               l            l     ##  #    l      #             # #            #  r          #    #          l   ##
#  #  #                 #  ##             #     # # #   ## g     #   r    #           ##    t    r  ##    # #            #
# #                         #  r          #      # # #   #         r              #                 # # g   #            #
####                    # g              ##   g l     #                     #     g#        g          #    #            #
#                     l  #    #   a# #                                       #  #   #     l             #   #            #
#     l                 #          #          #  ##   # A       ##          #    # #                     #  #   b        #
#         ##### #        #  # l    #   #     r#   # l ##   ##  b #       #   #    #         ## ##      g  # #          ###
#         #  #  #       #    #     #    #     #   #      #  #    #            #             #   #       A    l         # #
#                        #   b# # ##     #    # b ##      # #    #     #                   ##   ##        # #            #
#              ##         #    # # #      #       # #    g ##    # #            #r                        #  #g      g   #
#      t        #          #               #  a      #      #    #  #       b    #         r  g           #   #          #
#   l           #        g  #               # #       # #   #    ####### ##       # #    ##  ##           #    #   # #   #
#   ##    ##    ##           # ##### #       ##        # # ##  tb      #  #        # #   #   #g           #     # # #l#  #
#   #      #    # #         #   #  #          #           # #           # #          a# ##   #      g     # #          # #
#   #      #       #         # #    #    g    #         t                ##            # #   ##       t   #  #          ##
#   ##     # #      #       #   #    #        #      ##            g      #      #          l        l    ####### ##     #
#   # # #  #  #  rl  #       # #            t # #     #          t   ##   #       #               # #           #  #     #
#     a##  #######    # #   b #      l #       l #    ##             #    #       #        ##### #  A#          r# #l    #
#       #      a #     # #              #        f#                  #    # #f             #  #   # #   al        ##     #
#       #            g    #              #    b    #      g          ##   #  # l               # #   #  b          #     #
#       ##b#g              # # #          #         # #                   ###### ##   #         #     #       g    ##    #
#       # # #l   g    ##    # # #   #      #         ##     ## ##      t       #  #   # #       l      #A                #
#            #         #         #  ## #    #   b     #     #   #               #b#   #  #       b   g  #                #
##########################################################################################################################
