metadata:
  gen_time: 11.660584926605225
  timestamp: '2025-04-18T22:53:39.209284'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# g      t  g###  ######      #########    ###########    ##   ####   #  ##    ####     ####### ###       ##    ###  ## A#
#            #    ########### #########   r###########  r ##    ###      ## ## #####    ####### ###  #  ####   ####  ##  #
#            # ############## #########      #########    ## # g ##     f## ## ######   ####### ### g# #####  #####  ##  #
# r   f    ##  ##############   #######      #######      ## ##   #   #####    #######          ###  # #  l          ##  #
####f  r   ## #################    ####  t   #######      ## ###       #### l  ########   ## l  ##  f# # cl          #  ##
####                     ########            #######      ## ###    #########             ##  ##### ##   #   #   ##### ###
#######     #         t  ########          r #######      ##   r f   ########             ##  ####f ## ####  ##f ####  ###
#######                  #####         #############  f ####  ## #########f    ###   ###     r####     ##### ### ##      #
#######      g      ##########       f #############    #### ### #########   t####  ##### l   ####   t###### ### #    ####
#######    f        ############         ###########f        ###  #######     ####fl    g  #######                     ###
#######b                   #####       r ###########         ###   ###############        ########  ####c   #### ## ######
#######     r       t      #####           r ############    ##### ########## ####        r  tt     ####    #### ## ######
#####              g                         ############    ##### #########   ###  #   ####    ########    ##   ##     ##
#####                    g                   #####  #####      f # ##    l     ###  ##  ######   #######    ##   ##     ##
#####     t              ################ ########  ########     # ##  ###          ### #######   ######  ######### ##  ##
####### #####    b      f################ ########  ######## #         ###  # ####    ######l      #####  #########t### ##
####### #####            ##     #########    #####  ######## ##t       ### ## ### g #   #####  r f  ####  ####      ######
####### ############     ##     #########    ##### ######### ###   ####### ##       ###        ###############    r ######
####### ############     ##     #########    ###   ##############   ###### ##       ###       ################   tf ######
####### ############    g##     #########      r ############          f   ## #########   #  ####        ##     ##  ##   #
####### ##############              #####        ############       ##     ## #########  ##  #####   #######    ##  ###  #
#####   ##############              ########b   r##############  #  ##  #####         g  ##  ##     #########   ##       #
#####   ##############  #######     ########        ######## ##  #  ##   ####   l  f     ##  ## f f ##########  ##       #
#####   ##############  #######     ########        ######## #   #        ###  ############  ##     ########### ## #######
#  ## r ##############     #### r   ########        ########     #             ############  ####     ############ #######
#  ##     ############     ######   ########      b ######## #####    l ###################  ####     ### ######## ## f  #
#   b     ######    r  rb  ######   ###         l   ######## #####      r##################   ###  #  ###   ###### ##    #
# f     ########   b       ######   ###g  ####  g   ########   ###   b#######                  ##l ## ### f        ## ####
#    l  ######## b f     b ######   ###   ####               #####     #######   ####### rl ##### l## ### g  f    f## ####
# r     ########  f        ######   ###   ####      ##  r    ##### ############ r ######     ####   # ### #      ####    #
#  #############t       f  ######   ##########      ##       ##### ############    ##### ##           #####   g  ####   l#
#g #############r          ###################  f   ##############                  #### ##   f       #####      ####  ###
#                          ###################   r  ###############  l   g         A ###  #  ###########     ########  ###
#          b          b    ############    b  r         ####### ####   ####r  g#########     ############     #######    #
#    g ############        ############        b        ######l #####  #####b   ########     ######        #####   ##    #
#      ############      ##############          g      #####   ###### #         ###      ##########      #######  ##    #
#    f ############      ##############       b      ########   ##########        ###      ######           l          ###
#    f ############      ######             fl  f    ######## # ##########   r#######  ################  f     b       ###
#      ############      ######fr r                  ########## #########      ######   ################ A######  ### ####
#      ############    ########                    g     ######   g        ##   #####    #########     t  ######   ## ####
#    b            t    ##            #######     ##   ##  #####r    #  #####  ##    ## #####   ##  ###    ##      ##t ## #
#      c################# lf f        b          ##   ##  #####r#       ## #####         # ## ###   ## ## ### ##   ## ## #
######  ################# c    ####              ##    #     #  ## ##  ##    # ##    ##    f#   #  ##   ### ###    ####  #
######  #################      #### g            ##   ##        ##     ##          #####    #f  #  #             c # ## ##
# tg        g                          g      b####   ## f###                    ###   #    ###               ###     # ##
#                g                       f    g####   ##  ### c ##       ###      #  ###     ## ###  ##         ###      #
#     ###########        l  ##       ############## f ##  ###    #   #     #  c      # ##     c ##  r ##          #      #
# r   ###########        b  ##     g ##############   ##            ##   ###           #     ##  ##   #   ## # #       ###
#     ###########        #####         t###########   ##   ff    ## #  ####  #     ##  ##    ## c##        # #####b    ###
#  A  ###########  a##   #####    g     ###########       l # ##  ###  ##    #               #  f#  ###   ##    ##     # #
##     a            ##           l      ###########      b  # #    ##     ## ##  ##  ## a    ##     # ## ###   t # ##    #
##  a   l                  t      ##  l ###########  ##     #g##    ##    ##  # t #           #          #       # ####  #
#t       ##   t                   ##    ###########  ##    c###   ####            ##    ## ## ## ###    ## ### ###       #
#    b   ##    b   ######  #########  #############tg##       # ###           ##  ##       ####  ##     #  #   # c ##   ##
## t     ##  ##    ######  #########  #############  ##     ### ##     ## ## ##       #      ## ##      # ### ## ###    ##
## f   ####  ##    ######  #########     f l             #####  #       ###  #b       #   ##  # #       ###b  #  ##      #
##     ####  ##    ######  #########                     ######    ##   ##   #### ##    #  ####     ##  ##    ##     ### #
##     ####   #    ######  #######f    ########     #############   ## ##      ##     # # f  #b     #  ##      #   ###   #
##     ####  ##    ######  #######  g  ########  f  #########      a   ###      #  #### c               #f##b###         #
##  #######  ##    ######  #######     ########     ############    ##   #      ## ## #b####   g  ##   ## ####  b  ##b ###
#   ###########    ###### t           f########             ## ## # ##  ##       f         ##      #b  ##     f #  #    ##
##  ###########    ######    t         ########             ##    #      ## ##  ### ##  #######c####  g         ##    # ##
##  ###########    ######   ####   ############ g   f       ##a   ## ########     #       #    a##             ##    ## ##
#    l             ######   ####   ############ f##        c##  c       #  ## #       ##    ## ##              #   ###   #
#                  ######          ############  ##            ##    #### ##  ##  ###     ###b #               ##   #    #
#          g       ###  g          #########   ct##          # ##     ##   #  ##   ##   ###    ##          ##  ##        #
##   #################             #########     lr  r       # #       g   a   ##        #              ## ##  #    ###  #
## f #################       ###############                 # r  f        ##    rg     ##         r     c  ## ##   r##  #
##   #################       ###############   t       ######  ###    r  # #   ##        ##         ##  #   #   #   ##   #
#                            ###############     ##    ######  ##      a ### ####       a#          ###l#         # ## # #
#                            ###############f    ##    ######a                     ###      # #### ## ###  #      # #  # #
#  t##########   ##########  ###############     ##    #######  ######         ##  c #      #### # #  ##  ##        ##   #
#   ##########   ##########  ###############      g r  ######     ##           ##r       a         ##         ##    ##   #
#   ##########   ##########  ###############      r             ###   #### ## ##            ##     ## # ##  t  #   g#  ###
#l  ##########   ##########  ###############    ####             #    ##a###  #        ####  ###   #  #a      ##    ## ###
#   ########## g ##########b ####      t        ####         ##  ##                      ##    ### # ##    #####     #   #
#       f  ###t  ##########  ####               ####       ##       ###    ### a## # ##      #   ### ##     ## #    ##   #
#          ###   ##########  ####    ########   ####       ##  ###  ##       #   # #     ### #  ###  #     ##b           #
######    l###          ###  ####    ########   ####       ##### #      ##     # ###   ####     #                #    ####
######                  ###  ####    ####       ####          c  #  ##   #   #####      #          ###    ###### ## #   ##
# g ###         ###       f ###               ###   ###               f             ## ##    ## ##                    b  #
#   ###      l  ### g   l   ###  g            ###   ###     b                      ##            ## l           l    l   #
#   ###         ###         ###               ###   ###  c      f                  #   b      t   #                      #
#   ###   #########  r###############   #########fb ###                      #                          #                #
#   ###   ######### b ###############   #########   ###b t                     l f               l                       #
#   ###   #########   ############### l #########   ###g        l##         A##   f                    ## b  t     ##    #
#   ### b  r    ###             g b                 ###  c    ######f        ##  l         f           ##         ###### #
#   ###         ###        r  c   l                c###        ##  ###        ##                      ##A       ###  ##  #
#   ###         ###  c                             t###              ##       ##          ##          ##       ##        #
# b ###   ###  g###############   #########   #########      ##               ##   f                  ##         g     ###
#   ###   ###   ###############   #########  c#########     b###              # l                      #              ####
#   ###   ###   ###############r l#########  f#########    t  ##                                      b               ## #
#         ###  A                        ###   l g              ##       ## l          #        #            ##       ##  #
#         ###       f        g     l    ###               c    ##        ##   f      t##  f   ##           ##        ##  #
#         ###g      l               c   ###   c    c       c   ##        ###          ###    ###          ###        ##  #
#         ###   g  l              b     ###           t        ##      #  ###     b    ### l###    r     ###  #      ##  #
#     t   ###   g t                     ###              l      # f      f ##        l  ######           ##          #  r#
#       b ###               gt          ###                                 #  l          ##             #               #
#         ###                     b    g###                   t       g             t     l                              #
#         ###                 l         ### g                      ##          l                                 ## A    #
#       b ### b                         ###            a           ##          l   a                             ##      #
#         ###   b g                     ###                   f                                 t                        #
#         ###f                f b      l### t              gl l             #      l      ##             #               #
#         ###                           ###g            f       #          ##           ######           ##         g#   #
#         ###                           ###              t     ##      #  ###          ###  ###   t      ### g#      ##t #
#         ###                    b      ###b   c               ##        ###          ###    ###          ###        ##  #
#         ###       g b         b       ###            l       ##        ##           ##      ##           ##        ##  #
#       r ###     b                     ###  b                t##       ##       l    #        #            ##       ##  #
#   ###  b###   ###############   #########   #########       ##  g                    a      a                       ## #
#   ###   ###   ###############   #########g  ######### g    ###              #            f           #              ####
#   ###   ###  l###############   #########   #########     l##               ##                      ##     f         ###
#   ###    l    ###                             f   ###              ##       ##     b    ##          ##    t  ##        #
#   ###    l    ###                                 ###      g ##  ###        ##         g            ##        ###  ##t #
#   ###         ### A      r                      g ###       ######         ##                        ##         ###### #
#   ###   #########   ###############   #########   ###          ## r  f     ##                        ##          ##   f#
#   ###   #########   ###############   #########   ###           a   f      t   a                                       #
#   ###f  #########   ###############   #########   ###t l    t   f          # l     l  l     g         #          f     #
#   ###    cl   ###       t ###               ###   ###   b                        #              #                      #
#   ###         ###         ###            f  ###   ###      a                     ##         c  ##     A                #
#   ###    a l  ###      c  ###               ###   ###         b c       t         ## ##    ##b##   g                   #
##########################################################################################################################
