metadata:
  gen_time: 11.304439783096313
  timestamp: '2025-04-18T22:53:05.244048'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# ### # ############ # ###  ###      ###    #      ##        #    #                    b  f          #     #t#### #     ##
#                      f   #####    ####    #    #### f     ## ## #       ############## ## ##########     # #  # #    f##
# # # # # ######## # # # # ######   ####b      ###g     #   #  ##       g                            ##    #  b   #    ###
# r              c         #######   ##        ####  ## #####       #     ###########################        tf          #
# # # ### ## ## ## ### # # #######         t   # f c ##  # #       ##  ## ###########################            t       #
#     #   ##    ##   # g   #######       ##   ##     ## ##          #  ##       b                      #  ##      ##  #  #
# ### #g# ## ## ## # # ### #######      ####r    f   #  #      #   ##   ############### ### #########  #   ### ####   #  #
# ### # # ## ## ## # # ###  ######      #######   ####  #    ####  ##                 b   f          b # b ###  ###   #  #
#     # # ## ## ## # #       ####       #####   r ###   #    ##        ## ###########################  #   ########   #  #
# # # # # ##b   ## # # # #         r    ########        ##   ##  ##  ###  ###########################  #  t ######    #  #
# # # # # ## ## ## # # # #         ##   #########  b t###   ##   ##                                    ##   ######   ##  #
# #   g   ## ## ##       # ####   ####  #####         ###   ##           # ################### #######    #        #    ##
# ### ### ## ##r## ### ### #####  ####   ##### ########     ## #         #                   r     a   ##   ######   ##  #
#     #      ##      #     #####   ##        ### ## #a   ####  #####     g###########################  #    ######    #  #
# # # # # ## ## ## # # # # ####            l     ##     ######## ###b     ###########################  #   ########   #  #
#                c         ###l            ##    ##          r          #         t   g a            b #   ###  ###   #  #
# ### # #### ## #### # ### ##  l    ## r g###    ##   #              g ## ######### ### # ###########  #   ### ####   #  #
# ### #   c  ##      # ###     g   ####   ###  #####  # #              ##                              #  ##      ##  #  #
#     # # ######## # #            l#####   ##        g######   ####    ## ###########################                    #
# ### # #          # # ### rg##    #####    ##   ##  ##  ####    ##    ## ##########################                     #
# #     # # #### # # l   #  ####    ###          ##  ##      t    r     #                 l        b ##    #      #   a###
# # # # # # #### # #l# # # t#####      lb    ###### ###    ###      r  ## ################# ########## l   # #  # #   c ##
#     # #          # #  A   ######           ###    # #          #      ##            g              #     # #### #     ##
# # ### # ######## # ### #  ######                        ###  #######       #####        ########b  ####      ###     ###
#   #g                 #   l ####                                     t    t            r#########    ## b  f    at   ####
# # # # # # #### # # # # #    r               ######  t  ##  ### ######  #     l        #########     g  A    l      #####
#       #          #               ##    ##  ## #      ####    ###  ##   ##     A       ########    g   lg   ##     ######
### # # # ######## # # # ##  ##   ####g ####  #  a  t                   ####     ####   #######fg         t ####    ######
### # # # #      # # # # ## #### g####  #######     # ###  ####    t      ###   ######   #####    b         #####    #####
#     # # # #### # # #     #####   ##    #### ##  # ####   ###   ######   ##     ####   #######            a####   r######
# # # #   # #  # #r  # # # #####          ###     ###             ####    #    r        ########             ##     ######
#   # ### # #  # # ### #   #####          b##    ##    ##     #####  ##      f          #########             f      #####
# # #    lg #  #       # # #####                 ##    ##    t###       f                #########    ##              ####
# # # # # # #  # # # # # # #####               t       ##  #  #             b#####       r########   ####      # #       #
# #    l                 # #####           ##   ##   # #   #g ##          #     ### # ## ####### ## ##### ### ## ### ### #
### ### # # #### # # ### #######    ##    ###g ###  ## #   ## ##  c    #  # # # # # #            ## ##         l   g   # #
#       #c         #       ####    ####  ####  #    ##     ##  #       #  # # # #   #   ##  ###  ##  #r## ### ###### ### #
# # # # # ######## # # # # ###     ####  #### ## ## ##      #####   ## c  # # # ## ##   ##  ###  ##    ##         ##    l#
#   #       A          #   ##t      ##    ### #  ##      ######     ##    # # #### ## # ##       ######## # # ###### #####
# # # ### ######## ### # #                   t## ##  ##            ##    #  # #### ##   ##  ###  ########## #  tt        #
#    c  #          #    g                      #g    ##           t##    ####b##   ## # ##g  ##     ##      # ############
# # # # # # #### # # # # # #####    ##     ##  #  r     #    f ##  ##  ###### #### #### #######  ##### ######    b   #####
#           #  #           ######  ####   ### ##        # c  ###   ## ###          #### ##     l    ## ############ ###r #
# # ### ### #t # ### ### # ######  #####  ### #        ##    ###  ##  #   ###########   ## # ######### ##   #            #
#                          #####   #####t ### #         ##      gt##  ##  ################## #t# ##### #### #t# #   ##  ##
### # # # # #  # # # # # ######     ###    ####  #####  #              #  ##           g     # # ##  #   r  # # #       ##
# #     #  b       #     #  ##               #   ####      ### ###     ## ## #######f##### # # # ## l#f# #  # #     ######
# # ### # ###  ### # ### # c        bt       #               ####    g ## ##         ##    # #      f# # #  # # ###   f  #
# # ### # ### r### # ### #  r    ##   b   g   t             l     f ## ## ## # ########## l#   # ## #  #t## #     # ### ##
#                               ####       a ## t   #  #  t ####    ####  #### #   b         # #      t  ##    #### ### ##
### # ### ###  ### ##### # #    #####        ## ##  ## ##   ###   ### ######## ### #### # #### ##### ## ###  r      ##   #
#   #   #          #   # # ##   ######   ### ## ##  ##  #  ##             ##   ### ## l                  c     #b        #
# # #   ############   # # ###l ######  ##### #  #   a  ## ##  ##      f# ## # ###     # ##         # #                  #
### #                  # #####   ####   ##### # ## ##    #     ##     ### ## # ###  ## # ##        ## ##                 #
#   #g t        g      #   ###   l      g###    #  ##  ###    g##     ###### # ###  ##  ###r               # #     # #   #
#####      g           #######                     ##   #      ##    ##   ##  l### ###  ###        ## ##  ## ##   ## ##  #
##                        ####   ##t      g      f ##             f  t             ### #### g       # #       b          #
##                        ####  ####g   ###  #######     r #####          ##   ##      #### #             ## ##   ## ##  #
##                        ####  ####   ##### #   #          ##                     ##       ##             #f#     # #   #
#                   b      ###   ##    ########  ##              #   ###  ### ####r## #####    f b                       #
#                     r    ###        A###### #  ##           ## ##t   ##t### #### ## #####c##                           #
#g       c          l      ##           ####     #       f##  ##  #       ### #### ##  #### #   g        r          c    #
###                      ###           r  t      #  #  #####  ## ## ###   #### ### #### ###         g                    #
# #                      #       f           # ###  #  ###    #  #  ##    #### ### #### ###           # #     # #    # # #
# #   c                  #t    r      r##    # ##             #                ###      ###g         ## ##   ## ##  ##t###
#   #####    ################     ####### ## #   ########## ##  ## ## #######b      ##             r  # #     # #    # # #
#   #####   #################  ########## ## #   ########## ##            ### ####      ###           g                  #
# ##############rb      #####  #########  ##  ###           ############ ####       ##      #                            #
# #############         ##     ##          #  ### t## ##t   ############ #     ###f     ### ##g f                        #
#########         ###  ###   g###         ##  ###c ## ## ###############l #### ###  ### ###   c                          #
#######   ######  ###  ###  ######  ##b # ####   #    ## ###############  #### ### #### ### ##             # #     # #   #
#######   ##########        ######  ##  ######   ##   ##      g           ### ####t###f#### #             ## ##   ## ##  #
###       ########## r  a    ### c b   l####   #### #### ##  ###  ######  ### #### ## #####         # #                  #
##      ############  ##  #  ###     r #####   #### #### ##  ### #######  ### #### ## #####        ## ##  ## ##A  ## ##  #
##  ################  ##  ## ###  ###  ###  ##               ### #######           ##                      # #  A  # #   #
##ll######            ##  ## ###  ###  ###  ## g      ###### ### #######  ## t ##      ####        ## ##              r  #
##r ####    ###       ##  ## ###       ###  ##t       ###### ### #######f          ### #### b       # #  g  r            #
#            ## #     ## b   ####  a  #####   ## #### ######           g####   ### ### ####                    #b        #
# b    ###   ## #     ###         t###### ##  ## #### ###### ##       bf#### # ###  ##  ###### l        a ### g###########
#  ##  ####  ##    #  #####        ###### ##  ## ####g###### ## ##### ###### # #### #### ##           #######  ###########
####   ###        #   #####  #  ######### ##  ##      ##     ## ##### ###### # #####  ## ##           #######  ###########
###          r  ### # #####  ############     ##      ##  ## ## ##c   ### ## # ######    ##r   r          ###  #####     #
### ##         ###    #####  #########  # ##  ##  g   ##  ## ## ##        ####   ##f                  f   ###  #####g    #
##  #      ####### #   ####b #########    ##           #  ## ##   ## #############   g                    ###  #####    b#
#  #  #   ####   f    f#     ####   #  ## ## ##### ###  #### ##t  ## #####      t               l         fg     ###     #
# ##               #  ##            #  ## ## ##### ###  #### #       #####   b       g                           ###gt   #
# #   #    #          #    f   #r   #  ##           #r     # #########  ###                #  ########        f  ###     #
### # #    #        # #       ##   b# ####         b######## ########   ####               #  ########                  b#
#   ###          f            ##    ###             #####    ########    ####             g#  ########f     b            #
#    ##g          ###  ##      # r  ##               ###    l ########   #####     ##  t   #  ####                       #
#  a## b   #  f  ##     ##     #     ##        b     ###      ###  ###    #####     ###### #######r                     l#
#          #####r###     # # ###l     #               ##  t   ##    ##       r  #   ###### #######  g      ###### ########
#    #      ######    ## ### ##    r ##    # #        ##     ###    ###  #     ###  ###### #######  g      ###### ########
#   ##l  ####  b    # #       ####   ##   ## ##### r ###t    ###    ######  #######      f   #####         ###### ########
#  g##   # b          #    r     # g ##   ## ##### ######   ####    ###### ##  #####         #####l        ######  #######
## ##    #     l      #          # b  ###### ##### ######t  ####    ###### #   ######                      ######  #######
#  ### ###     ###    ######   l ########    #####     ##   ###     ####  ##  #############               a######  f     #
###           ##           #         b  ##    ###       #    ## g    ##   ##   ########################    ####          #
###           ##           #           ###    ###       #    ###     ##   ##   b# c        ############   f####          #
#   #   l  ###### #   ###### ###  b   ##     #####      ##  ####    l##    ###      ##     ############    ####   l      #
#  ## #### #          t      gb# #### ##   t #####      #########           ##    b ###################    ####          #
#  ##  ##  #                   #  ## r##f    ##### A    #########     #      #      #######                ######       l#
#  ##  ##  #       ## ######   #  ##  ##     #####    r ##########  r##                   #                ######  #######
#  ##  #   ##  #      ##   #  ##   #  ##   r #####      ##########   ##        #####         ##### r  a   g######l #######
#   #  #           ## ##   #  ##   # l#      #####      #########     #t        ####   ###   #####         ###############
#  ##  ### #       #   #   #   ##### r##     #####      #########     #   r      #      ##t#######     r   ###############
####   ### ##      #   #   # #######   ###   #####      ##  ####  b  ##      #####   ##  # #######         ###############
#      #           #   #           #          ###   a   #    ###     ##   #c  #  #   l##   #######           t           #
#                  #c  #                      ###       #b   ##      ##   ##  f       ###  #  ####              r   r   g#
######## # #   #####   ##### #############   #####     ##   ###     ####   ##   r ##########  ########            g  l   #
#              ##         ##    ###    f     ############   #### r  ######  #     ##########  ########       r           #
# r    #       ##         ##      ##      ###############   ####g   ######  #     #######  #  ########         f ### r  A#
#  #####      ##g         g##      #####  #########r ###     ###    ###### ##     #######            b           ###     #
#### ###    f ##           ##  f  #### ### ###        ##   g ###    ###  ###      ##            l                ###  g  #
#    f    ######   ##    ##########                                       #       ##     #                ###  #####     #
#        ###          ##     #####                   ###      ###  ###       ########    ##t            f ###  #####     #
#       ##   ##    ## ##    ##   ##      f   r       ###      ########   #    ########   #     g        r ###  #####     #
#### ####r    ##   ## ##   ##     ####                                   #   g ########  #       l    ####### g###########
####          ##   ## ##f  ##      A   ###          #################b  ####c   #        #            #######  ###########
#          ####    ##t##  fb####    g ##            #                   ###              # ###            ###  ###########
##########################################################################################################################
