metadata:
  gen_time: 5.148013114929199
  timestamp: '2025-04-18T22:50:37.028240'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#      ##               ### r       #####   ###########    ####a   ###########   ##  # #  # ###  #  ##  #  ### #  # #  ###
##                      ###         #####      f     af  l ####                  #           ##  # #t # #  ##  #    # # ##
##     f   g         c l###   ####  ##### ######### ##  ########### ###### #######   ###   #  #    #  # #  #   #   ## # ##
##  ##########          ###   ####  #####                       a            b     # ##          #r#  # # ##   # # #  #  #
##  ##########    ##    ###   ####  ##### ######### ## #### r  #### ######  ## ##                # #  #   #      # # ##  #
##           A    ##          ####  ##### #########    ####  b ####    ###  ## ### #   #       ##    #   ## #      # ##  #
##c               ##     f          #####  ########t   ####  aa####a  f### ###   #    ##    # ####  #   ###        # #   #
##      ###      l##  ####           g t   ########    ####  a ####    ###       #    A       #    #  #         #    #   #
##      ###       ##  ####   ####        ######      b ####    ####         ### ##            #                 #    #   #
##      ###       ##  #### c ####        ######  f   a ############        #### ##          #           ##  #   #        #
##            ##  ##  ####g  ####        ####          ############             #                   #    ## #   #     #  #
##            ##  ##  ####   ####       #####           a                   f#####  #     ##        #    ## #    # #  #  #
##            ##  ##  ####              #####  a ##        t           ##    #####                       ##        #     #
##  ##                          l        ####    ####        a       ####    #####                     #### #   ## #  #  #
##  ## f                                       r ########### ### # ######                            ####   #      #  #  #
##       ###################         ####       c########### ### # ######    tl  #                    ##r#r #      # r#  #
##       ################### l   ##  ########    ########### ### # #####     ###     ##     ##  #  #  #  #  #      #  #  #
##       f                       ##  ######## ############## ### # #####  ######     #r      ####  #  #  ## #   ##       #
##                                   ####             a  r##  ##    r            #             ##  ####  ##     ##       #
##  #######       ###              t ###################  ##  ##   #####  ###### #  ##  ##     ##   ##   ##     ##    #  #
##  #######  c    ###        ####        ###############  ##  ##   ##     ###### #   ######### #####    ### #   ## # #   #
##  #######      c###        ####                         ##  ##aa at f c      f # #       ###   #####  #   #         #  #
##  #######       ###   ##   #### b      #### ########################### ######## ########   ###        #      ## # ##  #
#   #######  ##   ###   ##   ####t        ###    ########################    #####   ####### #########  ##  #   ## #     #
#   #######  ##   ###   ##   ####  ######  a a   ########################a  a    # ## ##     #    ####      #      #  #  #
#   #######       ###   ##   ####  ###### b      ########################         ##   #     #  ##a###  ##  #         #  #
#                 ###        ####  ##########    #### a  t        f  #### t  #### ##   ### #   ####     ##  #   ##    #  #
#                            ####  ##########   g##   t  g     f      c##  a ##### #   ##      #######  ##       #    #  #
###                    ####  ####  ##########   a       f    ac           A  ####   # ##   #   ##  ###   #  #   #  # #   #
###    c       l       ####  ####  ##########          ############          #### ###   ##         ###   #      #    ##  #
###  ######        f   ####  ####  ############        ############f   a r ######  ## ####       ###    ##      ## # ##  #
###  ######  ########  ####  ####        ######        ####    ####        ######  #  #  #    ## ###    #   #   #  #  #  #
###c ######  ########        ####          ########    ####    ####    ########    #  #  #        ##            #  #  #  #
###  ######  ########        ####   ####   ########    ####    ####    ########         ##    #### #    ##  #   ##       #
###  ######  ########        ####   #### ##########    ####    #### ffa######## #  #A               #                ##  #
###  ######  ########    ##  ####   #### ##################    ################ # ###   ##      #####   ##      ## # ##  #
###  ######   t          ##  ####   ####g         f         a    b    c           #     ##    ###        #  #   ##       #
###                      ##  ####   ####  ################ ######### ###### ### #  ##   ##   ####        #  #   ##   ##  #
#  f          t             f####                       a  ####      f    t       ###   ##      #       f#  #   ##   ##  #
#                   gf f     ####           ###########    ####    # #### ####   ####   ##   #  ######  ##  #r  ##l  ##  #
#       ##      ##    ##    ##### #####  ##   ## #### ######### #### #### ##   ###           l c   ###   ##  t       ##  #
##### ##############  ##    ##       ##  ##      g                             ##    lc   t##     ####        ##         #
##### ##############  ##    ##     A ####                 r                              ######  ####        ####        #
###               ##  ## l  ##     g ####                t               f       #l    #############       ########      #
###               ##  ## b  ##       ##  # #### ###   ##          ##   ### #### ##     ####  ###### l      ########  ##  #
###   r   g      f          ##       ##     ##  A##   ##          ##   ##   ##   ##     ##    ###           ##  ##   ##  #
###               ##  ##    ##       ##     ##   ### #### ###### #### ###   ##   ##     ##    ##           a             #
### b             ##  ##    ##       ##                    ####                  #g    ####  ###                         #
#                l##  ##   a##       ##  #   g             ####  t              ##t  ######  ####            t ##        #
###             lg##  ####################  ##   ##                    ##   ##  #    #####  b ###    ##  ##    ##        #
###               ##  ####################  ##   ##  ##      g     ##  ##   ##  #    a###     ####  ########  ####       #
###      r       b##  ##      ##     ##          g   ##            ##                  ##    ###############  ######  ## #
###              f    ##      ##     ##  #           l                         r###          #########  ##      ##########
###               ##  ##      ##     ## A#                                      #####         ##  ##              ########
###               ##         l##     ##l ## #### #### #### #### #### #### ####t######  f                        a   ##  ##
#                 ##  ##  r   g      ##g     ##   ##   ##   ##   ##   ##   ##  b ##      ##          f ##     ##         #
###  b  f         ##  ##      ##     ## g    ##   ##   ##g  ##   ##   ##   ##            ##    ##  ##  ##   ######       #
###               ##  ##      ##     ##  ##                               r    ##    ##        ##  ##       ######b ##   #
###          r    ##  ##    f ##     ##  ##    l                t r            ##  ####                      ####   ##   #
#                 ##  ##      ##     ##  ### ###   ### ###      ### ###   ### ###  #####                     ###     b   #
#   b           r ##  ##      ##     ##       ##   ##   ##      ##  t##   ##       b######  ##  ##  ##  ##  ###          #
###               ##  ##      ##     ##       ### ###   ### ##g###   ###t###          #########################    ##f   #
###               ##l ##      ##   f ##         b      g              l       t g       ######################    ####  ##
###r              ##  ##      ##     ##   t                                      a        ##  ##  ##  ##  ##      ########
#             A   ##  ##   g         ##b  ##            ##   t r## t        r ## #      t                          #######
###b    l    g    ##          ##     ##   ## f   ##     ##      ##     ##     ## ##                a                ##f ##
###              a##  ##  l   ##     ##          ##                    ## c      ##  ##      ##   ##  ## ll##            #
###        r          ##      ##     ##                                          #   ##      ##   ##  ##   ##  ##t       #
###               ##  ##      ##     ##   ##             ##    ##         t   ##         ##                    ##  ##    #
###               ##  ################### ##             ##    ##             ##         ##               r t      ##    #
###            g  ##  ####################### #### ###              ### #### ####             ##  ##  ##  ##t           b#
#       g         ##  ##    ##       ##        ##   ##              ##   ##                   ##  ##  ##  ##  t##      ###
###               ##  ##    ##       ##        ##   ### ####  #### ###   ##       ##    ##       l a    rl     ####  #####
###             b ##  ##  b ##       ##   ##             ##    ##           l ## ####   ##                    #####  #####
###            f            ##    l  ##   ##             ##    ##             ## ####         ##  ##  ##  ##  ####    ## #
###   b           ##  ##    ##    r  ##                 l                        l##     t   b##  ##  ##ct##   ##        #
###l      fg      ##  ##    ##       ####                                                ##                    ##        #
##### ##############  ##    ##       #####t#### #### #### ###### #### #### #### #      #####    t             ####       #
##### ##############  ##   r##  g    ##     ##   ##   ##   ####   ##   ##   ##  r  ##t #####            l     ######   t##
#       ##      ##  t ##    ##### #####    t##   ##   ##   ####   ##   ##   ##     ##   ##         ##           #####   ##
#       tg  #  l          #   #        l#            ##      ##  ##    #####              ###                      t  b  #
#   # #     #           f # # # #  r  g #       #   ##### t #########    ##               ###          l  c            fc#
#   # #     #             # # # #       #     ####   ####   #########                     ###                            #
#   # #     #             # # # #       ##    ####     #      ##  ##         g   c  #########   ###############   ###  f #
#   # #   r #             # # # #       ###    ##        l                          #########   ###############   ###    #
#   # #     #             # # # # r     ###A                       g        #t      #########   ###############   ###    #
#   # #     #     r       # # # #       ####              ##     ##  ##   ####                 l      ###     cl  ###  b #
#   # #     #             # # # # r     ###t         t   ###     ##  ##   ####  t                     ###         ###    #
# g # #     #             # # # #       #                 ###        r     #                l   l     ###         ###    #
#  l# #     #   t        t# # # #       #l   l       ##   ##     c               ######   ###########################    #
#   # #     #          r g# #r# #       #          #####l          ##            ######   ###########################c   #
#   # #     #  f g        # # # # f     #t    ##   ####           #####    ##b   ######   ###########################    #
#   # #     #             # # # # r     ##    ##     ##t   ##      #### t ####  #               f     ###   ###   ###    #
#   #f#     #   t  g      # # #t#    l  ####             ######      #     ##   #                     ###   ###   ###    #
#                                        ###        b    #######              b             A         ###   ###   ###    #
###     ###   ###########         #####  ##    ##         #  ##         b         c ############### rc###   ### f ########
#   a                        t           ##    ##                    ##  ##  t      ###############   ###   ###   ########
#   # #     #             # # # #       ####                        #########       ###############   ###   ###   ########
#f  #g#     #   t     l   #g# # #      r####             ##   ##     #########            ###         ###   ###          #
#                                       g ###          l ##  #####     ##  ##             ###         ###   ###         r#
# #     # #   # # # # # #     a   #####   ###      ##         #####             #         ###         ###   ###          #
# #     # # f # # # # # # t   r       l    #      ##### b       ##              #######   ###############   #########    #
# #f    # #   # # # # # #         #####            ###### a#            ##   c   ######g  ###############   #########    #
# #   l # #   # #l# # # #    f                 #     ########   t     ######     ###### f ###############   #########    #
#b#     # #   # #   # # #         #####  #   ####    r ######  ## l ##########               t  ###               ###  l #
#    r  # #   # # # # # #              f ##  ####        ##    ##   ####  #####         b       ###          c    ###  b #
# # r   # #   # # # # # #         #####  #    ##      l              #     c##       f f  c    c###   l           ###    #
# #     # #   # # # # # #                     b                                     #########f  ###  r#########   ###    #
# #     # #   # #g# # # #         #####       t      ##     ##             l        #########   ###   #########lr ###    #
# #     # #g  # #   # # #            g    t##      #####   ####                     #########   ###   #########   ###r l #
# #     # #   # # # # # #         #####    ##   b  #####   ####          t      #f        ###   ###         ###          #
# #     # #   # # # # # #                           ##      #       c           #         ###   ###         ###          #
# #    b# #   #t# # # # #       r #####   l               g                l              ###   ###        c###     t    #
# #     # #     # # # # #                #     ##            l    l#    ##          ###############   ####################
# #     # #   # # # # # #         #####  #   ######       ##     ####  #####        ###############   ####################
# #     # #   # # # # # #                ##  #######    #####  ######   #####       ###############   ####################
# # f   # #  l# # # # # #         #####b ##   #  ##     #####  ####       ##                                     c       #
# #     # #   # # # # # #           l   g#              t##     #                    f             t           c  b      #
# # r   # #   # # # # # #         #####                l                                                                 #
# #     # # t # # # # # #                            b               ## t  ##g                 c     b                 fc#
##########################################################################################################################
