metadata:
  gen_time: 16.46637797355652
  timestamp: '2025-04-18T22:59:12.800745'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#####   ###r# #          ##    ##     ####      ####a                   #   l## ##   ### #   # b    ## #       ##  ##    #
###         # # a        ## b  #### ###  ###         ###             ####   ###       #t ## ##         #          ##     #
##   ##   ###               ##r     ##  ###                #   ####  ###   r# ####    ##        ## ## ##   #### ####  ## #
#  b#### ## # ##     ###    ## ##  ##   #   ###           ##          ##        ##     #### ###    #  ##     ##  # #   # #
# #    # ## #######   ##    #  ##  ##   ##ll    l         ## f   #  ####         ## #   ##  ##    r#          #### ##    #
# #b     #      t ##        ##     #       #         r           #             # #  #    ##  ##  r   #  ##    r#    ###  #
# ##          r## ##  ##    ## ##       ## #  #      #        ####   ##  ## ####      #########    ###   #     ####   #  #
# ###          ##             l ##  g    #      ##                    # ##  #    ###r # #          ##  ###        #  r  ##
### #   #      #  ##  ##         #       #      ##       ##       ##  #     ##  g ##     f ##          #         ##     ##
### # ###      #####  ##             ###   #             ##  #                       #     #  g        ## ###  f  ## #   #
#     ##         #           t##  ##   #   #         ###  ####            b # a   #  #    ##  ##      ##  ##       # ##  #
# ##  #   ## ##     ##  ###   ##                      ##      b##           ##  # #    #   ## ## # ##g # ##          ### #
#  ## b  ##  #t    f t  #   # #  ##  ##               ##  #### ##        ## ### ###  ####  ##    #  A    #        ##     #
# #####   # ###    # r ## ###   b##  ##     b                   b         # # #       #         ##           ## #c     ###
#     #  ## #     ##      ##  r ##    b ####        ### ###     g     r  ##     #   # ####             #   f  ###  ##### #
#  ##  b #  # ##  #  ##   b                #                #        ##g  ##    ##  ### ## A   #  ##   #   ## #      ##  #
#   #   ##    ##b    ##  ##   r   ### t ## ####   ###    ## #  #     ##  ####            # r #######        # ###  ###   #
#  ##    ##   #     f#    #    ## ## t  ####      #   ####     #      #     # ##  ##   ###   ##            ##   #  #     #
# b   #   #          ##       g   r       ##           l #    ### #   # #     #  ##     #     ###   ## #  ##      t   r  #
#  ## #  ##         ##      ##       ######        #          ##  b     #     #####  ## ##  g  #   ##  ##  #  a  ###  l  #
####            A# ##   b   #       r ## #     # #     #      ##b     b         #              ## l     #  ##    ##   ## #
#       ## #### #### r      ##    A      ##l  ####                            ### #    ## ####  #    ## ## ## #        # #
##       # # ## #            ##       ## t    ####    #      ###       tr      #  #     # # ##       #   #    #     ## ###
#  # ### #            ##              ##       ###        #####    ###  #  ### ##    #  #         # ##   #    ##    r    #
#  ####       ##l      #       ## ## ##       ##            ###    ### g    ##  # #####      l    # #    ##  b### #      #
#                        # # ###  ## b#                     ###          r###r ## #   #           ### ##  tg      ##     #
##      ### #      ##    # ####      ##    #          l  ######           ##      # ###       # # ##  ##  f #   ###      #
#    b  #   ### ## b#   ##   t    #      ###          #########       ## ##    ##   #   # ##  #####       b #        ## ##
#  ## t ## ## # r#  ## ##    ##########   b       #   #  #   l       ##  #          ### ###  ##  ## ### ##r        ###  ##
#   #   ####    ##   #t##t #   ##     ##              #              ##  ##    ### ## ###     # ##  ##  #                #
##     r# ## ## #   ##     #    ## ## ##   #          # #        ##         g  # #### #   ### # #       ## l    b  a  ## #
##   ##g   b ## ##  #  ##l ##  ### ####    #        # #     #    #      ######   #    # ####    ## r     ##         #### #
#            #   #  ## #   ##      #  #         f   #                   # ## ###   ##   ##              ###          #   #
#               r    #      ##  ##  r ##   #       g        ###                    ##   #  ## ##  ###  ##       ###  ## ##
# a          ####t    r  #       #    b    #     #       #  ### ##       ##             ## ##  ##   ## #  ##   r  #  #####
#              ##       ###     t  ##            ##           #b #       #         ##g          #          ## ##    ## ###
########    l   ##        #    #      ## ##          #g   #              ##         #    r## #### #  r        ## ## #    #
## ## ##  ## ## #       ###   ### ### #  # t       l     ##        l  r  ###       ## ##     # #  # ## f       # ####    #
#         ## ##          # l    ### # ##       #       ####            #   #    b#  ###  r        ###        r     ##    #
#b       ##     #### ##                #         l        b            ##    ### #####    ## g    ##         l ##   #    #
### ######        ##  ##     t#        b               l #   ##     #  ##      #      r #   f        r##    #   ##       #
###   ## t       ct  ###     ###       ####       # f        ##     #  #  ###    #    #f###  ##   ##        ## g#     ## #
#         ## ###t    #   b   #  g    ####         #           #     #   ####   ###    ### #  ##   #   #### ##            #
######       ##  ##     ###           # ## #                  #               ###    ##         b## ### ## #    ### ##  g#
#  ##  #####      #   ###    ###  l  ##    #     #       ##        g ### ## # #    #### ##   ##   ###    ###  ### # #    #
#   ## ## #### ## ## ## # #### ## #       ########                       #  # # ## ## t ##l      ###       ##r# # ####   #
#    # #    # b####  #  #l# #  ####     ###   #   f    # b   g              # ####  r   #    ##  #      #            #   #
#   ##g        # ##  ##   # ##   ##      #    #      #######                ###        ## # ##       # ###       f ###  ##
#  ##       ## b  # ##      ##       ##       #g           #          g           #### A###  #       # #      ###### ##  #
#          ##        # ###  #l  t #           #### g  #    #        #  ## #    ####  #####  ##      g    ###a### ##      #
#    ##    #      ## ### #    g  ##  ####     # #    ## #      ##      ####      #    ## ## #     #  ##  ##  #       g  ##
## # ##    ##  ####    # ##     ##    ##   #      ##f                  ###     #     ##r          #  b#      ## ## ##   ##
## #        b    #  f    ###    ###  ##              b            #    #    ###### a  #  # ##        ##  ##  ## ##  ##   #
#  ### ###      ##  ##   # #   ## ##     ##     #       l         #           #  # ## ######      b c#   ## f   #   ###  #
####g#  ##    #  ## t             #   ####    #         #         #         ### ## #      ##    ###            ## r## #  #
##       ## b #        ##     # #l   ## #     ##        ##       ##   ###        ###   ##  ##   ##   ###   ##  #        ##
## ##  # #      #      #    b ###   ##       g      ##g  #       ##     #####    ##             #r  ##     #   ##    ## ##
#  ##  #####    #         g  ##     ##               #   #             # ##     ##     ###   ##     #  ###  r  ########  #
#### t ##  #          ##   #### ### #  #   #  #   ##                         ##          ##  #   l  ####     r   # ##   ##
###                    ###      # # ##r#  ##    l ##                    ##        ## ##              #   r##        ##   #
#       ##   ##  t###   #   ## ##   ####       c       # lg #          ###        ## ##              # r  ##        ##   #
#  t  # ##       ###   ##    ###         ##     ##    ##  #  b               ##       g  ##  #      ####      b  # ##   ##
#     ###        #        #            ####   #    l      #  #      #    ##     ##     ###  r##   A #  ###     ########  #
####  ##        r  ####   ###  ## #     #         g       #  #        gf#####    ##             #   ##     #   ##    ## ##
##    #            # ##     # ##t #   ### ##  t                      ####     bf ###   ##  ##   ##   ###   ##  #        ##
#t ##     ##          #l  ### ## ### ###            t #                     ###  # #      ##    ###            ##  ## #  #
#  ## ###     #  #      #     #  #   #                              ####      #  # ## ######         #  l##   r # r ###  #
#    g##      #####   ###   ####   ### ###   ##                ##  b ###    ######    # ## ##  r f   ##  ##  ## ##  ##   #
# ##   ##      #  # t b   f ##     #   # #                           ## ##     #     ##        g  #  g#      ## ## ##   ##
# ###  #### ## ## ## ###      t      ###                              # ###      #    ## ##r#     #  ##  ##  #          ##
#      b    #      t ##  r   ## #  ####  gr#     ##       #  ##    l    # #    ####  #####  ##           ### ### ##      #
# #     ## ## ##     #  t## ##  #  ##A    ##  #  ##          ##    #              ####  ###  #       # #  a   ###### ##  #
#### ####  ## #             ###   ##      #      #####             #####    # #        ## # ##       # ###         ###  ##
##  t##b# ##  ##     ## #  l# #   #  t       l #         #         ##       # ####      #    ##  #      # l  a       #   #
#  ###    ## ##   #     ###              b## #         ###               #  # # ## ##   ##       ###       ## # # ####   #
#  #      #  #    #f # ## #     ##  ## ##  # #      A    # #             ## ###    #### ##   ##   ###    ###  ### # #    #
# ####        t     ## #       ##g     #   #               # #    # #         ###  g ##          ## ### ## #  a ### ##   #
#    #    ###    ## ##     ## ### ##                #      ###  ### #g  ####   ###   f### #  ##  r#   #### ##   l   A    #
# ####     ##               # # # ##  ##            #        #  ###       ###    #    # ###  ##   ##        ##  #     ## #
#   #     ##     # ##                ##    #        #                   #      #    a   #        r    ##    #   ##       #
#   #   ######## #    c    # ########l  #      #    ##           ## ##  #    ### #####    ##      ##c b        ##   #    #
#   # g   ##     #   # #   #t    ##    a#   # ####  ###  ##                #     #  ###           ###t             ##    #
#   #     ##     # c # #   #   b ##b    #     ########   ##l             ###       ## ##     # #  #r##         # ####b   #
#   #     ##  t      # # c       ##     # f   ###         #         l    ##         #   c ## #### #   b      t## ## #    #
#   #     ##         # #  ca     ## t   #      ###     c       g t       #a        ##r          #    g     ## ##    ## ###
#   #     ##    c    # #c  c     ##     #     ###   l  f     # ###  #    ##             ## ##  ##   ## #g ##  a   #  #####
#   ############# #### #### #############   ##########  #    #      #              ##   #  ## ##  ###  ##       ###  ## ##
#               #      a    #         a     #              #### g # #   # ## ###   ##   ##       a      ###     g    #   #
# #####   c     #         r #         #######           f  ####     ##  ######   #    # #### g  ##       ##         #### #
# ##          ba  l                      ## #    #         ####                # #### #   ### # #       ##            ## #
# ##        r   #   a  ac  a#      c     ## #               ###          ##    ### ## ###     # ##  ##  #       a        #
# ##            #           #            ## #  ###  ###         #    ### #   r  l   ### ### r##  ## ### ##        f###  ##
# ##          a #        a  #   g        ##         #             ###### ##    ##   #   # ##  #####         #        ## ##
# ##  a      b  # c b     c #    f a     ##r       ####          r   ###  ##      # ###       # # ##  ##    #   ###      #
# ##  a            c  a               a  ##          b          #     ##  ###r ## #   #           ### ##          ##     #
# ##       a  a             a            ##         ##          ###         ##  # #####           # #    ##   ### #      #
#### #### ##### ##c####### ###### ##########        ##   g  ###         #  ### ##    #  #         # ##  r#    ##         #
#      ##    ##      ###      ##t c ##ac                  # ###g   #           #  #     # # ##       #   #    #     ## ###
#      ##    ##      ###      ##    ##     a   ##           ###   ##          ### #    ## ####  #    ## ## ## #        # #
############################################   #####      # #                   #a      c      ##       #  ##g   ##   ## #
#   l  a     a   ##       ## a      r          ####    ##  g            #     #####  ##r##     #   ##  ##  #    r###     #
#        ####    ##       ##    ####       c  ####                #     #     #  ##     #     ###   ##b#  ##l     t r    #
# ##### t#  #    ##      c##    #  #  ######  ####        ###     #         # ##  ##   ###   ##       f    ##   #        #
#     #  #g #    ##   a   ##  c #b #c # cb    ######         r           ####            #   #######        # ###  ###   #
# b   #     #  #### ##########  #b    #  c     g   ##      ####           ##    ##  ### ##l    #  ##   #   ## #      ##  #
#     #    a     a          c a       #          # ##               g  # ##    a#     ####   b c       #     b###  ##### #
# b   #a#####                   ##### #                    #              # # #      r#         ##           ## # g    ###
#       t              c   fa   a    a      l  # g  l   # ##   #       g ## ### ###  ####  ##b   #  r    #        ##     #
#   b a          c  l   a c                      #  #  l#    # l   b        ##  # #    #   ## ## # ##  # ##          ###g#
## a     a         l                 a     #  ####        #  #             l#     #  #r  a##  ##      ##  ##       # ##g #
#             b   ba   t              a       ###  #      #  #       ##       r      #     #           ## ### r   ## #   #
##  a aar          c       t           c   # #######  #   #  #        #     ##  A ## r     ##          #         ##     ##
#   c     a              c    c    r       a #######  #   # r           ##  #    ###  # #        g ##  ###        #     ##
#       g                    b                 ####   #   # f   #    ##  ## ####     r##### ###    ###   #  r  #### # #  #
#a l            a    a   a    ca                ###  bg   ##       #           # #  #    ##  ##      #  ## l   #    ###  #
## ############ ### ########################     ### #    ##                     ## #   ##  ##     #          #### ##    #
## ############ ### ########################     # #   b  ##                    ##     #### ###    #  ##     ##  # #   # #
#     c      b#   #       #  r# c      t       ### #      ##                # ####    ##  #g    ## ## ##   #### ####  ## #
#        a  t #   # t a   #             r      ##                #  #   #g  ###          ### #         #          ##     #
#        a    #   #       #c  #     bb         ##             g  #      #    ## ##  b### #   #      ## #g      ##  ##    #
##########################################################################################################################
