metadata:
  gen_time: 7.7114479541778564
  timestamp: '2025-04-18T22:56:05.012140'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#        #        #   #  #       ####  ##################  l   ######  ####                                            ###
#        #     f            #    #     ###################      #####   ## r                                        ######
#       ###       #   #  #r #    #    b##       ###########  t   ###         l      #  r ## ###### # ###### ##   c#     ##
#   #   ###   #   #   #  #  #    #     ##        ###########                                         ###  # ## ### #######
#   ##  ###  ##       #  #  #    #     #####     l##########        b  t  t   ###### #   ## # ##   # r ## # ##   # #######
#   ##  ###  ##       ####  #    #     #####       ########     ##            #    #                   ##          #    ##
#  g  ### ### #       ####  ######     ##### f #  t            #### l ###     # # ##### ## ##    ##### ## # ### ##### ####
#    ##     # #   ######     #####    b#     f ##       l     #####  #####                                               #
#t   ##     #     ######     #####     #       ##             #####  ######    #    #  ###      ### #####    #### ##   # #
#    #  # #  #    ######  ########             #      ####   l#####  #######     ##  l ### ####  ##     #### ###   ### # #
#  #A  ## ##   #  ######    A ##l      #     r       ######   #####  ########                        ######l   ######  # #
## # Al## ##   ###        #   ##       #             #######   ####  ########                             #### #### ## # #
##   ##  #t ##   #     f  #   ##########       #     #######    ##   ######## ## ##l  ##  # ## ## ### ## ## #  ##   ## ###
# b  ##  #  ##            #######################     #####          #######                                ##### # ## # #
#     ##   ##                  ###        ########     g             ######                                       #### # #
#     ##   ##                  ###        ##   ####                   ####                             ####### #l   #### #
#     ##   ##                  ### #########   ####   ##      ####           #   ## ## #         ##g##      r  #l## ##   #
#   #  ## ##  #                #               ####  ####    ######   t      #####  #  ### ## ### ### ### ## ###  #  # # #
#   ###      ##                #  f            ###   #####   #######    ##                        ### ###### ##  #####   #
#    ##     ## f               #    #########  ##    ######  #######   ####                      t###  # ###  # ######  ##
#     ##   ##   g            f # rt #########        ######   ##### r  ####                       ### ##   #    #r  #r  ##
#      #####       g t ### #####     t          g   r ####              ##    ##### ###b#### #### ### #### # ## ### ##  ##
#       ###         ####  t  ###         r       ##                      A    ## ##        # # #####  ## # #        ##  ##
#b                  #        ###                ####       t      ##         ### ## # #### # # ##f    ## # # ## # # ##  ##
#     f             #  g     ###               #####    #####    ####       ##   ####a       # ## # # ## #        ####   #
#        f          #                 # ###### ####    #######   ####l     #####                  # # #  # # #    lt##  ##
#                   #          r  #####   ####         ########   ##l     ####                   #      #         # ##   #
#       ###    f  ###             #####   ####       l ########           #### # ## # ## ## #######    ###   #  # # ##   #
#      #####                   f  #####   ####          ######             ##### l  # ##    #######   ####      # #      #
#f    ##   ##                     #############                    r  ##            #### #    # l # #   #    #  ### #    #
#    ##     ##    ###########################  #                     ####     ### ####   # #### #     # ## # #   ####t  ##
#   ##      ###   ##########          ##    #  ##   ##         ##    ####   ##    ## ##                f        ##t##    #
#l  #  ## ##      ##########          ##    #  ##  ####       ####  l ##   ### ##### ## ##########   ##### # ## ## ###   #
#     ##   ##t    #######           ##### ###  ##  ####     g ####         ### #        #   #   #     #    l  # ##   b   #
#     ##   ##      ######           #####      #t   ##         ##l         ### # ###### # ### ### # # ###  #  #    ###   #
#     ##   ##      #                #####            g     t               ### #    ### # # # # #     # #     #  ##  #   #
#    ##  #  ##     #         ##     #   ######           ####       ##      ##   # ##   # #   #         #     #   ## #   #
##    #  #  ## t # #         ##     #        ###   ##   ######    t####        ### ## ### # ### ##   ## ##    # # ## #   #
#####  ## ##  #### #  l      ##              ###  ####  ######    ######     g # # ######                     # #### #   #
#  ##  ## ##  ##  ##         ##     #     g  ###  ####   ####  g  #######           ## ##a####           # #  #  ###     #
#   ##  # #  ##   r     r    ##     #        ##    ##     ##    f  ######    ### ##    ######### ## ## ### # ##    ###   #
#t  ###     ###              ##     #     f            t            ####     #   #######l#  f    ## ##       #f ######   #
#   ###     ###   r          ##     #                                               #### # ## ##### #####  # #f ### ##  ##
#     ### ###      a                    #####g   ## r  ####   l               #####t##   # ##### ## ## ### #A#t  #  ##  ##
#  A##b ###  ##   #######           #   #   #   ####t ###### t    ##     ###       #          ## ## ## ##          #t   ##
#   ##  ###  ##   #######           #   #   #  #####  #######  g ####   ##### ##a###### ## ####  ## ##  ## # ## ## ##   ##
# t #   ###   #                     #   #      ####   ########  ###### l#####     ##### ## ##### ## ## ### # ## ## ##   ##
#       ###                         #   #   #  ###    t#######  ######   ###  ## ## f##                             #   ##
#        #                          #####   #  ##       #####    ####         ##g##  ## ### ### ####### ### ### ## ##   ##
#      l #b       # ##### ###       #####   #                          l      ###### ## ##  #   #  #  #   #  ## ## ##   ##
#     ##        #####                    # #          ###############  ####      ##   ####        ##         ###    #   ##
#     ## ##   # #####          #         # #   l      #     f   #####  ####       g   ####  ### t ####     ######## #   ##
## r ###  #    g            ####a        # #          #              l ####   r       ####  ###   ## #######     ##      #
##   ##   #                 #### # ##    # #          #                ####   ##      ####  ###   ##   ##       l        #
##   ###       #      #     #    l  #    # #      g   #                ####   ##  ##  ####  ###      r                   #
##   #   ##t         ###  ###     t #    # #          #        #       ####   ##  ##t ####  ###               #   l      #
#   l     # #  #   ###### ###      l#r  r# #          #        #       ####l b##  ##  ####  ###  ###          #    f   # #
# #       #    #  #####             #    ###g         #    r   # ###   ####   ##  ##t ####       ### a        #        # #
# #       #    # #####   #      t   # f    t  #####  t#        # ###  l####        t        g                 #        # #
# #       #  # #   l #   f     #    #         #   #####        #                                               l         #
#     ##     # #           ##       ##   r    #             t  #     r          #####    ###  ###     g     rg           #
#      #       ##       #  ##        #      f #   f        l   # #####          #####g   ###  ###                  #   ###
#        ###                         # l      #     # #        # #####   ####   #####    ###                  #    #     #
#                               #    #l  l    #     # #    ##### #####r g####   #####    ###            f     #   l#     #
#                 ##            #    #   ###### f   #l#    # t   #####   ####  l#####                    l            ####
#                            ####   r#   #          #      #     #####   ####   #####    g                       t       #
###    #         #    # r #    a#    #   #          # #    ##    #####   ####   #####     l           ####################
#   f  #   ##         #  ##          #   #          ###    f#    #####          #####   ########### ###  ##          #####
###                       t  ####    #   # tt         #  f  #                 l #####   ########### #      b ######### f##
#       ##        ##          # #    #  g#f         # #     #      l    ###     #####   ###########               #### ###
##                   #    #   # #    #   #  f       # #     #   #       ###r          b ########### #        ######     ##
#          #l             #  r#    l #####          ###     #####       ###             ###########       t              #
####       #            #            g       t                  #  ##   ###   #####  g  ###########             A     ####
# l     ####            #       t                               #  ##t  ###   #####            b            # # #        #
#   #                 # # ##     #### ############### ###### ####  ##   ###                         l##     # # #        #
# ###    ##  #  r  #r     ##bt      #     g   #     b      #    #  ##   ###            ##################   # ####       #
# ###                     #      ########## ### #################  ##        l   ##    #############        # ## #tf     #
###  t                    #                                    #                 ##   b##############       #g## ##f  #  #
###   ### # ##      b   #        ###############################       t   ##    ##                 #         #       #  #
#         l                                               rr    ###   ##   ##              b        #       # #  b##A #  #
#             t  g## r #  ##              r                     ### f ##                            #g      # ##  ##  #  #
#        #   #    #                                g                  ##        ################    f       # ##  ##  #  #
#           l#    # ## f                                  # ####          ####  ################  ##        # ##  ##  #  #
#   ##       #    ####     #f  #    l                     #     ## A      #### t################  ##        ####  #   #  #
#   #f               # ##   f                             #     ##  ####  ####  ################  ##           #  #   #  #
#   #          ##  r   ###  #                        fl   #     ## g####  ####  ################ b##         # ## #l l#  #
#  g          #  g#                                       #     ##        ####  ################  ##   #     # ## #   #  #
#      #        t           t                             ###### t        ####  ################ g##   #     # ## #      #
# rt   ##     t                                              f        ##        ################    l        #### #      #
#   #      ##  #A #     ####  ###                               ###   ##      l         r    b               ## # #      #
#     #        #### f ######  ###        t r f   f  l           ###   ##   ##         l  t  b             b  ## ###     g#
#     #             l   ##       ################## ############           ##    ##               t          #   ##      #
#  #                           #                t#f            #  g              ##    #############         #   ##  #   #
#  #     ##   t    l          ## #### ######### #################  ##            ##    #############         #   #   #   #
#         #                #  ##    #         #            #f   #  ##   ###            #############  g          #   #   #
#        ######      #   l #  ## ############################ ###  ##   ###                     lg               ##  #   #
##      ######    a  #   ###                           g        #  ##b  ###   #####     l           ##            #  #   #
##    # ##             # #  t   t      r                        #  ##   ###   #####     ###########  ###   lf     #  # t #
#                               #    #####         t### lt  #####g      ###             ###########               #  #   #
#         #               b     #    #   #            #     #   #       ###       r     ########### ####                 #
#    ######      #     t   ###     l #   #          # #     #    g    g ###     #####   ########### ########           g #
#       ###                 l        #   #          # #     #               f   #####   ###########      #################
###   #   #    #                     #   #          ###     #    #####         l#####   ###########   ####   ###    #### #
# ###   # # c ##     t ###           #   #          #     r##    #####   ####   #####   gg          ###                  #
#  ##   #t#             #            # l #          # #    #     #####   ####r  ##### l     t         ####              b#
#  ##   #        # #    #            #   ######     # #    #   t #####   ####   #####    l r      r r   #######          #
#       #                            #        #     # #    ##### #####   ####t c#####    ###   g   a    l          r   t #
#     #                  rg      t   #   f    #  l  ###        # #####   ####t  #####    ###                    b        #
#               f            a       #        #                # #####          #####    ###  ###g           # #f# #     #
#   #                  #            ##        # r              #    l       g   #####    ###  ###g  ###      # # # #  g  #
#             a        #     ##   r #         #   #####r       #                          l            f                 #
#           #    #    ##       b    #         #####   #        # ###  b####      g  r            t      l                #
#     #     #  ###    ## r          #    ###          #        # ###l  ####   ##  ##  ####       ###    g                #
# #         #   #    c        f     #      #   f      #        #       ####   ##  ##  ####bb###  ###               # r  ##
### #  ######   #  #        #       #    #r#        f #        #       ####   ##  ##  ####  ###      f  #          #   t##
##        ###   #  #  f     g   f tg#    #            #                ####l  ##  ##l ####  ### r       #       f  #    ##
#                  #            #####    # #r       l #      r         ####   ##      #### g###   ##               ##   ##
#    f   t  ##     #        #            # #          #          g     ####           #### r### r ##f             l##   ##
###      #   #  ####     #t #            # #          #         #####  ####           ####  ###   ##         #     ##   ##
#        #   # l#### #   #               # #    f     ###############  ####   r  ##   ####        ##         #     #     #
##########################################################################################################################
