metadata:
  gen_time: 12.996023178100586
  timestamp: '2025-04-18T22:46:04.285919'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#             ##          ##      ############################                            # b ##c         ## ### ### #  ##
##            #         r  #   ###############################        ############        #    #   ##     #    # ##  # ###
#                                   g        # #  # #b       #       ##l         ##       #    ##    ##  ###     ##    ###
#                 ##                   #     # r  #          #g     ##            ##        ## ##    ##  ##   ##      ####
#b       #    a    #  #        ###     #     # #  # #        ##    ##        r     ##    #   #  ##  ##    #            # #
#  ##    ##   ##      ##     ##        #######   ## ######### ######          g l   ######        ####    #  ##    ##    #
#   #          #              #        ######   ### #########                       g      ##   c ##  #  ##    ##        #
#g           f                    b    #   t# # #f  #         ######       b  bg    ###### ### b##    ## ###t  ###       #
#                      g          l    #    #   #   #        ##    ##   g  ##  f   ##g  g## ##  #    ### ##    ##   ##  ##
# g ##    ##            #              #    # # #   #      g#       ##  g ####    ##         t       ##   #    ##       ##
#    #r    #           ##     #f       #    # #r#   #       # #      ######  ######      ##  ##     ###      ##  ##     ##
#                             #        #    # # # r #         ##                        ## #### ##   ###   b #        ## #
#                                      #    #   #   #       #  ##   t######  ######    ##   ##  #    ##   #     ##   ##  #
# #                    ##              #  b #   #   #       # f ######   b####  r ######    b#  t  ##     ##    ####     #
# ##              ##    #     #        #   b  r     #       #                       b       ###          ###   #  ####   #
#        ##        #g         #       l    f        #########                              ####      l    ##   #   ##    #
#   rr b  #  ##                           f# ### f  #########   ######    ####    ######   t #   ##    # ###  ##   ##    #
#   ##       #       t         ########    #   #    #        l ##    ######  ######    ##         ##  ## ##   #   ##     #
#    #             #        ##r  ##   #    #   #    #         ##                        ## a      ### #   #  ###      g  #
#                  ##       #    ###  #       t#    #        ##     b######  ######    l ##      #  # #       ###  ##  ###
# #                    #         ##            ######               ##    ####c   ##         r## #  t    #      # r####  #
# ##     #      b      ##  l     ##                    b     ##    ##t     ##     t##    ## ##   ##      # ##t      ##   #
#        ##r           l   b     ##  ##################       ######       t        ######    t    ##      ##    # ###   #
#   t                            ##  #       ##                l                                ## ####          # ##   ##
#                       ##   ##  ##  #       ##            f  ######                ###### r ## ##  ##    ###   #  ###   #
#           ##           #   #   ##  #    f  ##    g         ##    ##              ##    ####   ### ###   b ### #   # b  #
#  ##        #       g        l  ##  #       ##   t  b       #      ##            ##      ###   g##  ####      r##      ##
# b #b                         #######     A ##            g #       ##          ##   l   ###    ### ## ##       #     ###
#     l  ##    r     ##    b       l      b  ##              #        ############        # ##  #  #        ##    ##  ####
#        #           #                t      ##       l     r#                    l       # #####   ##b ###       ### ## #
#r   ###  ##    r              ##   ##   ##  l         f    # f       ##  l######   c ##     f                           #
#   #### ###                   ###  ##   ##     l     #######         ##   ##  ###   ###               g                 #
#   #### #### b   b    rl    f ###  ##   ##         g ####            ##  ##    #######                                  #
# b ####  ######   f           #### ##   ##   ############            ##       r  ##                  g                  #
#    ##    ######### b         #### ##        ############            ##                 l     b                         #
#    ##  g ######### ##########     ## l      ########            # #  ##          #   c                                 #
#    ###  #######     #########     ##        ########  #####     #    ##              f                     r           #
#    ###########       g ######     ##    b f ########  #####   #       ##   ######                  c               b   #
#     ########## l       t###       ##        ########  #####           ### #########      ###############################
#     ##########          ##        ##        ########  #####             #        ###                   b               #
#   f  ###  #### t        ## l ###  ##    g             ####       # #      f l     ##     ############### ###############
#             ##         ####  ###  ######f  lt        b####                  f      ##                 b                #
#  l  ###      #         #### b###########     ###      ####                ##   f                          f            #
#  ## ###      #        ######    l   ###  r b #######  ####      #                       #           fc                 #
# ### ### f    ##       ###### ##    b###  g   #######  #####  l  ##                                 f                   #
# ### ###      ##   g   ###### ##     ###      #######  #####     ##t  #        b              r               c         #
#  ## ###   r  #        ######        ### g    #######  ####    #  ##  #                                                 #
#     ###      #     b   ####r ###########     ###      ####t#     ##c         #      l                                  #
#      ##    g## b       ####  ###  ######              ####  ##   #    t      #               l            c          c #
#      ###  ####          ##   ###  ##t           l     ####       b            #          ###############################
#     ##########          ##        ##        ########  #####     #          b   t                    A                  #
#     ##########          ###  g    ##        ########  ##### b    #             ##       ################################
#       ########         ######     ##  t   f ########r #####       f              ##g   ##                  c           #
#     #   #######     ######### b   ##        ########   ######                   f  ##  ##               a   r          #
#     #    ####################     ##        ######## f     ##                           #    b             b           #
#     #g   ######### g          ### ##  b     ############  b ##                            f                            #
#t  # ##  ######   g           #### ##   ##t f############ f   ##            t   ## l A                           b      #
#   #  ######  f   f l         ###  ##   ##           #### f   ##                        c                               #
#   #    ###           l     b ###  ##   ##           #######   ##                   #        b                          #
#     ##  ##       t       r   ## t ##   ##      g          #   ###      l     #                                         #
## ##   ##   ##    #  #  ###  #        ##  ## #######  ######  ##        ##  ###   ### b   ##                 g     ##   #
#### t ##   ### #   ##    #####        ##  ##    t ##                  #########   ##  l  #               t b       ##   #
####  ##      ### ######  #####         #  ##      ##                ##########          ##                         ######
## # ### f #############   ##          ##  ##   ########      ##     ####  ##           ###                        l     #
#  # # ##   ##   ### ##    ######      ##  ##   ########     ####b    ##           ##   ###                 ####         #
#    # ###    #       #### ######          #######  ##    ########                 ##f    #        g        ####         #
# ###   ###  ######  f ### ##f#            #######  ##    #########       ##                 f              #            #
#  #  # #     ##### #  ##                     ##    ##    ## #  #### f    ##   ##b           l           l l#      l     #
#     #       ## ## ##  # ##      t           ##          ##   g ###           ##     ##            t       #            #
#       ###  ###        #####                 ##          ##     ##                   ##            t       #            #
#   #   ##    # #### ## ##       ###############l     ###### #                 la                           ### A       g#
# # ##  ###     #  ###  ####  b  ###############      ###### #        ##                                t   ###b  gb     #
# ####  # ###  l    ##  #### ##  ##    t              ##  ##    ##   ####              ##               g     #   t      #
#  #### # ####    ###     l####  ##    ##             ##  ##    ##   #####       ##  #####                    #          #
#  ## # #       # ###    f#####  #     ## ##              ##        ######   ##  ##  #####    ##            b #          #
#           ###### ## #  ## ##   ##  #### ##              ##        ####     ##       ###     ##              ###        #
#       ##  #####  ## ## ##  ## l##  ####                 #t #       ##               ###     ##       g      ###        #
#    #  #     ##      #####   #  ##  ##                   ## ###               f ##  #####                              t#
# ## ## #    ##    t  ####  ###  ##  ##    ###            ## ###            ##   ##  #####                               #
#  #### ##  ##    ##    ## ####  ##  ##    ###        ##   # ##       t     ##      f ##l     A    g    ## ######## ######
#   ###  ## ##   ###   ###  #     #  ##f              ##  ## ##   ##    ##                      A     b ##  ##   ##    ###
##        #####    ##            ##  ##                #  ##l    l##    ##l       ##     l   r          ##  ##   ##    ###
######    ##      #     ###      ##   #       ##      ## l##                      ##                    ##b ##   #########
# #### #   ##    ###  # ##   ######  ##       ##      ##                              t                 ##      f        #
#   #####  ####   ##  #############  ##       ##    ##########   ##      ##             ##           t  ##               #
#    l##     ##b  ### #########  ##                 ###########  ##    ####    ##      ####  g          ##################
##      ##       ## # ##         ##                    ##    ##      b #####   ##  ##  ####                 ##  ##  ##  ##
####   ##  b#### ##   ###   ###  ##                    ##               #####f     ##   ##           b  l   ##  ##  ##  ##
###   ##   ##### ##   ### #####  ##   l##### #### #### ##  ##f   ##     #####                   l      #######  ##  ##  ##
##### #### ###   ## # ## ### ##  ##    ########## #### ##  ##   #### f #####   ##                      ##       ##  ##  ##
#               ##  #    r       ##  ##  ###  #############                  ##     ###                                  #
#               ##   #####        #  ##  ###  ######   l###  l##        t    ##f   ####   f         l                    #
#               ##  #####   ####  #r  f       #####      ##  #### b    ##          ###   #######  ################  ######
#        f     t## g#       ####  ##         ######   #  ##  ####    ######         ##   #######  ################  ######
#         l    ### t###### ##         #####  ##########  ##   ## l ##########  ##         ######  ################  ######
# #### ## #         ##     ######     #####  ##########  ####      ####  ########            ###  ###          ###  ###  #
#      ## # # # #   ##b       b#####  #        ##                   ##     #######           ###  ###  g       ###  ###  #
#   l       # # #   ##r      lr#####  #        ##              ##            #####           ###  ###          ###  ### f#
#      b    #   ### ####  ##########  ##b #### ###  ## ###  # #### f        l #####    ##    ###  ###          ###  ###  #
#A        # ##    # #### b            ######## #######  ##  # #####     ##    #####    ## b  ###  ###          ### l###  #
#   t     #  ## ###    #      #  ###g       ## #######f ##  #  ######   ##     #####              b            c         #
#         #  ## ######## #    #  r #   g   f##  t#####  #####    ####          A####                  r                  #
#         #  ##    ##    #    ##      ########A  ############     ##            ###     ## #####  ###          ### r######
#       # #  ##    ##    ##   ##  ##A ########  ##############         l  b##  ####   ##########  ###          ###  ######
#       # #####   ##### ###   #   ##  ###  g    ##############             ##  ###    ##########  ###          ###  ######
#      ##     #   #    ## #####  ###r ###      ########### l    l   ##          ##     ####l     g###    fl    ###f      #
#      ##     #  ##l                   ###########                  ###                  ##       ###          ###       #
#t     ##    #   #             #### #    ######### r  ####t ##     ######            l  f    ########         f########  #
#       # l b#  ##             ###  # ##   #######l         ###  ##########                  ########          ########  #
#      ##   ##  #                     ###   ###################  ####  ######    b ##        ########c         ########  #
# b     #   #   ##########        g## ###   ##  #############     ##     ######  ####             ###          ###       #
#       #g  ##  ##  #     ###  ## ##  ###  ###   ##########                ###########            ###l l       ###       #
#       #   #   ##      r     ###    ####        ###                         #########       ##########################  #
#       #   #   #                  ######      #####  ##     #    ##           ##  ## b g    ##########################  #
#       ##  ##  #     t          ########  #########  ## #  ###   ##     ##                  ##########################  #
#       #   ##  ###              ########   #####    t   #  ####    f  ######          ##                    c        a  #
#l     ##   ##   ######### ###   ########   #### l   f  ##   ###      #########  ##    ##                                #
#    t #    ### ## #######        #######  #####  ####  ###t ##    b#####  #### ###  f                l       r  r       #
#     ##    ###    ##          #  #######  #####  #  #  ###  ##     ####    ### ####   g                 c               #
#     #  l  #      ##   #      ##########         #                         ##  ####    ##f            l                 #
##########################################################################################################################
