metadata:
  gen_time: 10.440923929214478
  timestamp: '2025-04-18T22:50:31.798255'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  ###        #########  t                                      A    #        ###      cl####             l####### b  ####
#  ###        ###   ### g                                      t     #        ### g      ###    ######### ########     ###
# ####     b ###      #                 t                                     ###              #####################     #
# #####  r   ###          #########   ###          ###   #########            ###              #####################     #
#           #####   r g   #########   ###          ###f  #########   #######  ###  #######     #####################     #
#  ##           l    l    #########   ###          ###   #########   #######  lf   ########   t#####################    ##
########      b           ###         ###       t  ###     b   ###   #######       ########     ###################     ##
##################  t     ### t       ###          ###         ###   #######       #######     lt#################       #
###        ######        t###b        ### t        ###         ###           l###b  t             ###############   r    #
#           #####         ### t ############################   ###        r   ###                  ###### ######         #
#    g     b#####         ###   ############################   ###   ####     ###     ####r##           r      l  l   ## #
#       l  b######        ###   ############################   ###   ####     ###  f f########         t             #####
##       b  #      g  l  l###   ###                      ###  l###               l  r     #####b      #######       ######
#                    l    ###   ###                      ###   ###                l       ######     #########     #######
#      r                  ###   ### t           l        ###   ###         #########      #######   ###########   ########
#     #######################   ###   ################   ###   ######      #########      ########  ###########  #########
###################    ###### t ###   ################   ###   ########    #########  f ##########  ########### t#########
########       ##      ######   ###   ################   ###t  ########                 ## ######    #########    ###### #
#####                                 ###          ###              f##                 ##     f                         #
###           b                       ###          ###    f                    f                    b                    #
#               r   g t            g  ### g      b ###           b       ###   g   ###   c     r  ##         g ##        #
###################################   ###          ###   ############    ###   #   ###           ####    b    ####    t  #
##############    ##  #############   ###l         ###   ############    g     #  t       #     ######       ###### t  t##
##        b  t       t ############   ###          ###   ############   g   f  #      t   ##    #######     #######    ###
#     ####   t g                    f             t  l               ###               #####     #######   #######t    ###
#      #####    #######          t      b    t                       ###  c        t   ####       ######   ######       ##
#      ################        b                                     ###  r  #####  t  ###         ####     ####    a r  #
#      #             ## l                     f     A           g    ###     #####     ### l ##                     ##   #
#               A                          l                                                #### l                 #### l#
#                   b                                                 t       c            #####        ###        ##### #
#  g#################             t  t                               ########c    ######## #####r   A  #####       ##### #
#    ##################        b    f       f         f              ########  l  ########l ###  t     #####b  b    ###  #
#    #############     ############   ###          ###A  ####################     ########              ###    g  r      #
#    #####             ############   ###b b       ###   #################### b   ########  bg l   ##         ##         #
#  b###      gl      # ############   ###          ###  t####################     ##########     t####       ####     g###
#             #  g   ##               ###          ###               ########     ###########     ####       ####    f####
#      f  #####      ##               ###          ### l    t                f       f    ####     ##         ##     #####
#          ####     ###      c        ###          ###         f                           ####    l                #### #
#          ####        ######   ###   ################   ###   ########## l       t   ####  ####       ## ##    l  ####  #
#    r    #####   ###########   ###   ################ a ###   ##########             ####   ####     #######     ####   #
##     #########   ##########f  ###   ################   ###   ######   l                     ####    #######    ####   f#
#       ######## g ###    ###   ###             l        ###   ###     l   f          c g      ####    #####    ####     #
#       #####  #   ###    ###   ###            b r       ###  t###   #####################      #### f  ###    ####   f l#
#       # r        ####   ###   ###                    f ###   ###   ########################    ####         ####    ####
#                  #      ###   ############################   ###   #########################    ####       ####    #####
#    t     g              ###   ############################   ###   #########################t lr ####     ####     #####
#    ############   g   b ###   ############################   ###            c   f    l  ###   gb  ####   ####    t  ####
#     ######   ########  t###         ###          ###         ###    c  t A          l   ##         #### ####     g   ###
#     ###f         ####   ###         ###          ###         ###b       t  ##### c      b           #######            #
#     ##     t            ###         ###          ###     l   ### t         #####   r        ###      #####      ###    #
#     ##               t  #########   ###t         ###   #########           #####         r #####      ###      #####   #
#     ###r                #########   ###          ###   #########   ####    #####    #### b ######      #      ######   #
#     #################   #########   ###          ###   #########   #### g  #####    #####b ######           t ######  ##
#     #f        ##                                   t               ####             #####  ######    l        ######g ##
#       t   b       t                                                ####             ####   ######    # # #    ######   #
##  t                         l                                      ####  ##    # #  ####    ##      ## # ##   #####    #
###             #   #         ##        ## ##### ##       g## ############ ##    # #  f#       #    # ## # ##   ##### # ##
#    # # # #                  ##      ####  ###  ####l     ## ############ ##    # #   ###          # ## # ##   ##### # ##
##            # # # #         ##       ##  l###   ##       ## ############ #f    # #   ### #  ##    # ## # ##   ##### # ##
#    # # # #  r               ##g  tt ####  ###  ####    g ## ############ ##    # #  ####    ### # # #f t ##   ####  # ##
##            # #           ###         ##  ###  ##         ############## ##    # #  ####    ##### # ## # ##   ###   # ##
#    # # # # #               ##   #   ####### #######   #   ############## ##    #    ####  # ####  # ## # #    ###   # ##
###                       # ##### ## ###  ##   ##  ### ## #######  ####### ##    #    #### ## ###g  # ## # #    ##    # ##
#    #   r               #    ##   #   #   #   #  f#   #   ##       #######r#    #    #### ## ####  # #t r      ##  # # ##
###          a          #g# #   r f        #   #              ######b#f#####f#   #     ### ## ###   #    # ##    #    # ##
#    #   #   #     #   #      r   ##   ## g## ##  ##   ##   t           ######   # #   ### ## ##b   #    ####     #   # ##
##            # # #l# A       # #####  #          l#  ##### #            #####   # #  #### ## ### # #    ####  ####   # ##
#    # #   # # # # #   # #    #  ##    #    # #    #    ##  ###### ######a####  ## #  #### ##  #### ###  ####  ####   # ##
#                   # #          #     ##   ###   ##     #               #####  ##    #### ##  #### ###  ####  #### # # ##
# g#   # #   #     #                                       b####   #####  ####  ##    #t#  ##   #   ###  #### ######  # ##
###                b# # # # ##g  ##                     ##          ######t###  ## #   #   ### # #t##### ###  ####  ### ##
#    # # # # #    r# #           #   ##    lgf      ##   #                ##### ## ######  ##a## #####  #####b####   # ###
##      #                 #      #   ##r            ##   #                 ### ### ####### #a##  ###   # ###f##### ##  ###
#  #A      # #     #     #       ##                     ##   ###t# ######## ## t## #######  ### #### #   ## ###### #b# ###
###       # #             #  ##                  bg         ##      ######  ## #### ######   ## ###f     ##  ##### b## r##
#        f   # # #               #     ##   ###  r##     #                  ##  ##  ######   ## #### #   ##  ##### ### # #
##  # # #                 # ###  ##    #    # #    #b   ##  ##  #########  ###   # #######   ## ####    ###  ##### ### a #
#  #                          #b#####  #   f    g  #  ##### # ##b##########a##      ### ##   ## ###    ####  ##### ### # #
###   # #b# #    g      #   #     ##   ##  ## ##  ##   ##           #    ####    ## ##       #   ##    ##    #   # ### t #
#                                        l #   #    f         #  #  #   #  b#           ##   ## ###    ## #  ### #  f    #
##                          # ## f #   #   # g #   #   #   ##  ###  #   #  f#    ####   #    ##   #    ##    ### #      ##
#                             ##  ##l##   ##   ##  ### ## ####   ####      ##     ####       #  #g#   ##  #   ## b   #  ##
##                            #   #   # #  ##  ######   #   ####   ##    ##     ## ####  #   #  # #  ##   #  # # #  ##  ##
#                        #    #      fr ##  ##   ##            # ##f# ## ####   #   #### #   #r #    #           #  ##   #
###                         # ##      #### t###  ####      ##  ##     ## #  #     ## ###      # # #       #  ### #   #  ##
##                          # ##       ##   ###   ##  r  l ## g##     ##  # #      r  ##      t #         #  ##b   ##  ###
#                             ##      ####  ###  ####      ##r  #     ##  # r         ##      # # #  ##   #   #  b ### ###
##  #r#                   # # ##        ## ##### ##gt      ## # # ### ## ## #    ## ###          ## ####      #### ### ###
#t ####      f  #   ##    c   ### ###    ###   ##  ##    ## #            ## #    t    ###      ###    ### #     #  #    ##
## ####     ####          #f##    ##            ## ###   #   #      g  ####     g      ##        ###   ##      ##     # ##
## ####  #######   #### # #l####b   #### ##     ##  ##   #  ###  ##   ####     ###     ###  ##              l ####    #  #
##l###  ######## ###### # #r#### ######a####    ### ###     ###     ####    #    ##     ######  ###       ##  ##         #
###    t####### ####### # # ####  #### #####  ##  # ##        ##     ##     #       #  ### ##   #    ##   ####     ##    #
#### ###    ### ####### # # ### # #### ####   #      #  #  ##    ##       ##    ## ### ##   #  #     ###   ### g  ##   ###
#### #### #   # #######t# # ### # ###  ####        g #  #  #   g    ##  ####    #  ##t ##  ### #   ##  #    #   # ##  ####
####  ### ### # bbt   #     ###   ##   ####     #                      ###  #       # #### ##  ##g ##   ##      #  ##  ###
#####            ###        gt  # #    ####  ## #            ##  ##     #   #  #  # #  ##  ## #####   g ###    t         #
#####                               f        ##    ##   ##   #   ###  # ##     # ##    ##     ##        ##   f ### ## ## #
#      ### #####t####### # ### ####   #####   ##g      ##   g#A ##  ###  #       ###    ##  ##        ##     ##  #########
###### ###b#####   gr   t  ### #### # ######    ##    ###            ### #        ##    ##  #    ##   ##     ##    #  ## #
###### ###                          # #######   ###   ##       ###   ##  ##   ##    ##                  #b    ##   g     #
# f  rbt    ####  f        ##     rb       #     #  r#      #  #    ##     ##                 ##     ## #     ###    ##  #
# ##    ## bg     #####        ###      ####  # ##  ##    g #       ##     ####        #   ##      # #  ##    ##    ######
#                                  r  f    ## # ### ###   ##         ## f   ##     #   ##  #       # #   #  ##        ## #
##     ####    ## #                 # #######    ##  ##  ###   ##  g   ### ###   ###     ##    # ##     ### #    ##      #
#    # #       ## #                 # ######     ### ##    ##      c## ### ##    ##   ## ##  # # ##    ###  # #      ##  #
#                      #           ##  #####   ##  #               ###  #   #    ##    g ### # g ##   ###     ##     ### #
#   #                         #   #### #### #       ####  ##   ##   #   ##  #  ##  ##  ##  # ##   ##  ##        ##   ##  #
# # # # ##                        #### #### ##f ##  #########  #    ## ###     ##      #      #t    ##     ##   ###      #
#   # # ## #         #     ## #   #### ####  #    ##   ###     #   ### ##       ##           ###    ##           ##  ### #
#   ##  #  #           #  ### # # #### ####  #    ##    #t   ##    ##   #t#     ##  #   #  #####  ##  ##             #####
##  #           #   ####  ###     #####        a  ##    ##   ##     #   # ##  ## a###  ######   ####   ##b   ##         ##
### # #   ### #f#  ##### ###   # #######         ##    ####g  ##    #  ##   ##    ##   t####    ##     ###   #   ##      #
###   ## #### #   ###### ### ### #######r###  ##        ##      ##     #   t      ##       #  ##      ###   ###  #   ##  #
#### ### ###r### ####### ### ### #######        b    #    f      ##     rf ##   ##g     ##             #    ##       ##  #
#### ### ###t### ####### ### ### ####     ###     ##A#     #     ##   ###   ##         ######    g  #  ##    g     ##    #
#####                                          ## #  ##   ###   ####  ####           #   ##      ## #      ## b##  #     #
##### ### ### ## ###### ###   ### # #### ####     #    ## ##    ##  ##  ###    ##   ####   g    ###c##  ##             # #
#r##l####   # ### #### ### ###### # #### ###            #  #  ##         ##   #####  ##     ##   #   #  ######    #   ####
##                                                 #   ### #       ##    ###g###            #   ##        #####  ###  ####
##########################################################################################################################
