metadata:
  gen_time: 4.703205108642578
  timestamp: '2025-04-18T22:58:07.693286'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  #r       #     g        #  #  ##   ##  #  #     # # ##f     # ##  ## ##     ## #r#  ####    l###  #   ##   # ##    ## #
#  #        #              #  #   #   #   #  #     # #  # ###     #c ## ## ### ## # # ##t         ## # #    ###     #  f #
#  #######  #  # g#####   #  #  l          # r#    # #r       ##  #  ## ##     ## # # ###l#     #      ####  ### #  #### #
#  #     #     #          #  #    #c  #    #  #      # ## ###  #     ## ## ###### # # #f#   # ###  ### #  ####   #       #
#l #  c  #  t  #           #  #   ## ##   #  #       # #         #   ##      t  # # #  a#  ##   ####   # ###   # ###  #  #
#  ####  #  #  #  ######  r#   #   # #   #   #       # # # # # #     ## #   # # # # # ###  #   ###   ###   # ###   ##### #
# c   #  #  #  #       #    #   #       #   #      # # # #       #   ## #   # # #   #  t  ## # # # #  ###    #   r###    #
#     #  #  #  #       #    #   #  # #  #   #    # # #   #   #    #  ##     # #     #   #  ### #   ## #   #  # #  # #   ##
####  #  #######  #    #   #   #  ## ## g#   #   #t  # ###   # #   # ## ## l  ###       #####  # ####  r###  #   r#   # ##
#           #  #  #  f #  #r  #   #   #   #   #  ## ## ####              # #  ####  #       #f #    ##  l##### #### ###  #
#           #  #  #    #  #   #         r #g  #                      #   #       #    ##  l # ## ##    ### l   #     ###f#
####  #  ####  #  ######  #   # f #   #t  #   #   #####   #   #      #   # #   # #  #    ##   #   #fa   ##  #    ### #   #
#     #  t  #     #    #  #   #   ## ##   #   #   #####   #   #t# #  #   # #   # #  #  # r  ### # # # ###   ###   #    ###
#l    #     #l    #     #  #  #    ###    #  #  #     #       # #    #   # #     #     #f ###   #   #  ###  #   #l# ##  ##
####  #  ####  #  #     #l #   #             #  # ####### #              l a  ######## #  #   # #####  #   ##   ###b #  ##
#  g g#        #         #  #   #       #   #     ####### ##  ##     #   # #  ######## ## # ###   b##### #    ####   # t##
#     # b b    #         #   #   ##   ##          a r                                       #   g ##     ####    #  ##  ##
#  #######  #  #########  #   #    # #    #   #  #  ####### ### #### ###   ##############  ## ###    ##  #    ## #l ######
#     #  #  #     #    #   #t #     #     #      # l    a  A                         g  #  #  #r  ##    ##  ###       #  #
#     #   cc#     #    #   #  #   t       #        # ############### ### # ###########  #  #    ###     #   #   # ###    #
#  #### c ###  #  #     #  #   #         #    t #        b             t               t#########   ###   #    ##   # ## #
#     #r       #  #      #  #  #        r#  #        ############### ### # ########### ##         # #    ##  # #    #  r #
#     #        #  #      #  #   #       #   #       ################ ### # ###########  # # #   # #  ft# # f ### #### ## #
############  ##  #    #  # t#  #      f#  #      ################   ### # ############   # ### # a ###    ####  #f    ###
#    g#        #       #  #   #  # r#  #  #              g     f   tA      f           # ##   ### ###t  ##    #    #######
#     #                l#  #  #  #  #  #  #  #             ######### ### # ########### # #   ###  #   ###  ## # ##      ##
#  #  #  #  #                                   #           t    fa    l                   # # #    # a     ### #  ## # ##
#  #     #  #   b      #    #  #  #   #  #  #            ##### ######### # ###A ### # # ####   # ###### ######  #r    #  #
#  #   gt#  # b        #    #  #  #   #  #  #                        c l l  g  l      #    ## ## b#        #   #####  ####
#  #  ##########  #    #   #   # t#   #  #   #g   ############  ####   ###############  ## #  #   #   ### t  #     #  #  #
#  #     #        # t   #  #   #  #   # g#   #  # #########               b c############    ## #######  l####   # #    ##
#  #     #        #     #   #  #   # #   #  #c  #     #   # #   # #c #g# #   #t  #       l##  #       # ###  #####a   ####
#######  ####r ######## #    #at#   #   #  #    # ##### # # #   # #  # # #   # # ######   #   #   ##  #     ###  ####    #
#  #        #           #    #   #l #  #  l#    # ##### # # #   # #  # # #   # # #####  ### # ###    ##l    # # ###a   ###
#  #        #          #      #   #   #   #           #         # #  # # #       #  f # #   #   ###  #   ##   #   # #   ##
#  ############# f######       #  #              ########## ##           #   ###  # #     ###      r## ###   #### # ###  #
#     #                 #      #   # #   #      #    #####  f#  #### #####   t###      #b      ##   #  #   #      #     ##
#     #    r             #      #r # #  #      #   # #   # # #   ##  ##      r#     # a#r## #r #### # ## #####    # #t####
####  #t #  ###########  #       #             #   # # # # # # # ## g## #     # # # #t## #  ####  ### #  #   l ##      # #
#     #  #f     b         #      #  #  #      #    # # # # # # # ##  ## #     #c# # # #  #  #    ###  # ## # ###  # #  # #
#r f g# r#r      c      f #      #  #  #  A   #    #g# #       g ##  ## g       # # # # ###   #b # #### #  #     ## ## # #
#  ##########  ########   #     #  # #  #     #   c# # ############  ## ##    ### # #   t   ######      # ##b#   #  #  # #
#   r                    #    f#   # #   #g    #  g# # ##     ## ##  ## ##     ## # # # ##   a #    #   #    #####  # g  #
#          t        c    #    #    # #   b#r   #   # # ## ### ## ##  ## ## ### ##b# # # #  #   # #### ###a####  ### ### ##
#             f        #  #   #    # #    #   #  # # # ##     ## ##  ## ##   b ## # #   # ###### #  a #  f#  # ##   #   ##
#   # #   #   # #   # #        #r#   #f#   # f   #                         ###                  ###              b       #
### # ### #g### ### # ###    ###             ### # ##     #####               l     ##  ##     f   b           #####r    #
# #           # # #     #    #   f #l# #r  f      r# ###                #        #  #a rg#  #        #            b l ####
# # ######### # # ##### #   r# ##### # # #########A#  #              ############## #    # ##############            t # #
#   # #   #   # # # r         r    # # #   #   # #          #  #     #      #r      #    #       #      #     #  #  r    #
# ### # ####### # # ### #    # ###   # # ##### # ### f      ## ##                      f                     ## ##       #
# #     # #   #                            # #   b #   ##   #  #                 #   f      #                 #  #   ##  #
# ### ### # ##### ##### ###### ###   ##### # ### # # # #    #  c     ####        #          #        ####        #    #g##
#         b # b     #    b       # g     #                                   #  a    ####       #                        #
#####   ### # ### ### ###    ### ### ### # ##### ####  ##  ## #   #  l      ##       #  #       ##         #   # ##  ##  #
# b #           #r  #   #    #   #   #       #   #   # #   #  # ###  ###     #                  #     ###  ### #  #   # ##
# # #    #### ##### ### #    # ### #####  #### ### ##  # a #         #  t                               #         #   #l #
#         g   g     # # #    # # #   #     f   #           #    #                   #    #                   #    #      #
# # #   # ######  # # ###   g### # # #### ## # # # ## ###  #    #  #######         ## ## ##         #######  #    #  ### #
# # #   #     # #   # # #    # # # # # #   b #f  # #                        ##                  ##                       #
# # # ### ##### ##  # # ###### # # ### ##### ##### #  #     a       #               #  l #     t   A     #             # #
#  f#   #     f #     #    A   #     #       #b  #   l#   #####     ##     c       ##   l##      l      ##     #####   # #
# ### # # # ### ### # # ###### # # ### ###f# #  ####  #                             #l   #                             # #
#       # # #   #          tf    #   #   # # #        #                   ##        #    #        ##                   # #
#       # # # r   l #          b #   #  g# # #      b #                   ##        # l  #        ##                   # #
# ### # # # # #r  # # # # #### # # ### ### # # #####  #l                            #    #                             # #
#   #   #             #        #  r  #      g#  g#    #   #####     ##           l ##    ##        f  g ##     #####   # #
# # # ### ### # # # # # # #### # # #   #####c##### #  #f            #               #    #               #r            # #
# # #  g#     # #   # # #    # # # # # # b   #   # #                        ##                  ##     r                 #
# # # # # ### ###   # ###    ### # # # # ### # # # ## ###  #    #  #######         ## ## ##     a   #######  #    #  ### #
#     #         #     # #   r# # #             #           #    #                   #    #                  c# c  #   r  #
# # # # ##### #####  ## #g   # ### #### a##### ### ##  #g  #         #                                  #         #   #  #
#   # # #       #       #    #   #  r#f      # # #   # #   #  # ###  ###  g  #                  #     ###  ### #  #   # ##
# ### ##### # ### ### ###    ### ### ### # ##### ####  ##  ## #   #         ## r     #  #       ##        l#   # ##  ##  #
#      r    #       #      f     #       #        f                          #       ####       #         g              #
# ### ### # # ### ##### ###### #####f##### #b### ### # #    #        ####  A     #          #        ####        #    # ##
# #    l# #   #     b   #    #         #   # #     #   ## f #  #   c             #          #           f     #  #   ##  #
# ###   ##### # # ##### #    # ##### # ###   # # ###        ## ## r              l                     r  r  ## ##       #
#   # #   #   # # #                # # #   #b  # # c        #  #     #      # g     #    #       # l    #     #  #       #
# # ######### # # # ### #   g# ##### # # ######### #  #              ############## #    # ##############              # #
# #           # # #  r  #    #     # # #         f # ###                #        #  #    # l#        #                ####
###f# ### # ###r### # ###  f ###f# ### ### # ### # ##     #####               l     ##  ##             g       #####     #
#   # #   #     #   # #        #    c# #   #   # #                  g      ###                  ###                      #
##             ##  ##           ##  ####  ##   a       ##  ##       l     #               ### g                          #
######### ## ############## ## ############## ## ############## ##g########           f   ###        r  r                #
######### ## ############## ## ############## ## ##############t## ########               ###             l              #
#  ##           ##               ##      ##               ##     b     ##A ############   ###   #########   ######### f  #
#b     b                          l                l           g           ############   ###   #########   #########    #
#a ##r          ## ba       A    ##      ##   a           ##           ##  ############   ###   #########   #########    #
####### ## ######### ### ########################## ### ######### ## ######               ###   ###      b        ###g   #
####### ##a######### ### ########################## ### ######### ## ######               ###   ###     b     f   ###  r #
###                         ##       ##       ##          a         a    ##       f       ###   ###        g b    ###    #
#          a               g    a          b                      a        ############   ### t #####################l   #
###         a  c       b    ##l  l   ##       ##r                        ##############   ###   #####################    #
##### ###### ##### ## ### ####       ##       #### ### ## ##### ###### ################   ###   #####################    #
##### ###### ##### ## ### ####                #### ### ##r##### ###### ####   ###  l                        l     ###    #
#    b                      ##     a ##       ##          g                   ###             l                   ###    #
#                   c          a     ##    b  g                               ###                                 ###    #
#             a    t  b     ##       ##       ##                a   a         ###   #################################    #
#             g          r  ##                ## b     bl                   t ###   #################################    #
#      g                    ##       ##    a  ##                              ###   ################################# c  #
#    a    b                          ##                          g   g                 b      l             ###   ###    #
#                           ##      b##       ##                                                            ###   ###    #
#                           ##                ##b          b            a            r    g    f t          ###   ###    #
#                           ##       ##    l  ##                     rb       ###############   ###   #########   ###    #
#                                 a  ##                            a          ###############   ###   #########   ###    #
#       c                f  ##       ##  g    ##                              ###############   ###   #########   ###    #
##### ###### ##### ## ### ####                #### ### ## ##### ###### ####   ###t    g g ###   ###   ###   ###         g#
##### ###### ##### ## ### ####   r   ##    t  #### ### ## ##### ###### ####   ###         ###   ###   ###f  ###          #
###         f     bt        ##       ##       ##   b              b      ##   ###         ### b ###   ### g ###        l #
#                 a l         l                            r  g               ###   ###   #########   ###   ###   ### l  #
###      t                  ##       ##       ##        b                ## t ###   ###  c#########  g###   ###   ###    #
####### ## ######### ### ########################## ### ######### ## ######   ###   ###   #########   ###   ###   ###l   #
#######a## ######### ### ########################## ### ######### ## ######         ###         ###   ###         ###g g #
#  ##           ##l         l    ##  g   ##    g          ## a         ##           ###     g   ###   ###     b   ###    #
#                                                                                   ###        b###   ###         ###    #
#  ##r          ##               ##     a## a             ##           ##           ###        b###   ###         ###    #
######### ## ############## ## ############## ##r######## ##### ## ########        l###g        ###   ###         ###    #
######### ## ############## ## ############## ## ######## ##### ## ########         ###         ###   ###         ###    #
##                 ##               ####               ##  ##    l        # l       ### t       ###   ###         ###    #
##########################################################################################################################
