metadata:
  gen_time: 7.506222724914551
  timestamp: '2025-04-18T22:55:33.113720'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# b##        ##   a##   ##     # ##       ##   ##       a   #              #     #  #        #  #     #     #     # b#   #
#  ##   ##              #      #   c      c    #    ##c # b #              #     #  # r l    #  #    r#     #     #  #   #
#                c   ## #        ###   ##   ####   c## ###  ####  ####  ####  ####  #######  #  #### t####  #  #g #  #   #
###       b##   ###   ###  ###    ##        ###  #  ## #       f  #              #t    #     #    b            #  #  #   #
#c## c ##  ## g##    ###     ###  ## #   ####    ##    # ###      #        t     #     #    t# t             f #  #  #   #
#       t###   ##    #  l    b       #####       ##      ## A######  # ##  # t####  #  ####  ##########  ####### g#  #   #
###             # c  ##     r  ###   ###     ######      ##       #  #  #  #        #  #    A   #b    #        #         #
### ######    ### c   #    #   ##             ##   g###     # f   #  #  #  #        #  #        #     #        #         #
#   ## ##      # a  ###   ##c  ##  ###        ##    ###     #  ####  #  #  #  #######  #  ####r #  #  #######  #  #  #####
#   ##            #####    ### #   A ######   b     #                 f #  #        #  #  #     #  #  #        #  #f    t#
#   ##  ###### b           ######      ####      l ##                  l#  # f      #  #  #b    #  #  #        #f #   r  #
##  ##  ##          g####                  c        #   # r    #  #######  #############f #######  ####  ##########  #####
#   #   ##     ##               c     ###  ###l       # ##  #  #  #  #  #           #        #           #     #         #
# ########            ###### ######   ###  ## c  ##   #  #  #  #  #  #  #           #     r  #           #     #         #
# c  #       ##       ######  ##           ##    ##t  #### ########  #  #######  #######t #######  ####l ####  ###########
#    #  f    ##       ######c ## #         ##   a## c #### ##  #        #    t            #  #     #           #         #
# ########    b       #############   ###  ##c   ##   #  #b #  #        #         t       #  #    r# b         #         #
#   #c  ##     ##                     ###  ###   f    # ##  #  ####  # b#  ##########  #  #  ####  ####  ##########  #   #
##  ##  ##           ####          c         b  t   #   #            #  #  #   t # t   #  # t   #     #        # f   #a  #
#r  ##  ######c      a   l ######      ####    c  c##                #  #  #     #     #  #     #     #      bb#     #   #
#   ##            #####    ### #     ######      l b#        #########  #  #  ##########  #  #######  #  ####  #  ########
#   ## ##      # a  ###   ##   ##  ###        ##    ###     #  #     #     #                l         #  #     #         #
##########  a ###     #    #   ##A        b   ##    ###     #  #     #     #                          #  #     #         #
###             #    ## t      ###   ###     ######      ##    ####  ##########  ##########  #############  ####  #  #####
#        ### t ##    #              b#####       ##      ## r        #  #        #  #           #  #  #       f   #      #
# ##   ### ##  ##    ###     ###  ## #   ####    ##    # ###     t   #  #        #  #           #  #  #           #      #
###        ##   ###   ###  ###    ##        ###  #c ##g# r     ####  #  #######  #  #######  ####  #  #  #  #######  #####
#t   l               ## #     c  ###   ##   ####    ## ###  #  #                   r      #    r  l   #  #        #      #
#  ##   ##              #      # #             #    ##  #   #  #             a            #          a#  #        #      #
#  ##c       ##  t ##  c##     # ##       ##   ##   #       #  #                          #           #  #        #      #
#   ###         g                  # #   #                             r     ####c                #  ##           ##   ###
#                    # #      r    #            t ##         ##            ##  ##                 #                ## ## #
##g                                   # g#       b#r #        ###   l          f##               # b     #    #       #  #
#                                #                   #          ##               #     ###               ##   ##         #
#      c       r         #    #  g                  ########                           ####               ##  ######g    #
#        a       ##  l      g           t       ##        ##                #             #       l        ##   #####    #
#                #               t       g#           r   ##       #     r  ##         f           r                ##   #
#               ###            g    ##    #          ##   #                  #             ##                  #         #
#   l  #        ###                  ###    #                #f  f    ###    ##            ##                  #    #    #
#  #  ##             #            #  #     l# a #          ###        ##  ##  #            ##                   # l      #
#                  A    l       ###         ##        l        fb           l         f  f ##              #   a         #
##          c    ##             # #         ##                                  t          ##                      l     #
#g    ###           r   #     # # # ##            #          r   b                     #    ##           ##             g#
#     ##    t             l                         b r ####      r           ##       ##   ##   l       ##  #          ##
#      ####ll   r      ##                        ##     ####                  ###       ##     r f       ##  ##          #
#a        #                  #  r      #         ##     ## b                  ###     l ##               ##  ##          #
#    l   r#             ##   c #  ###  #         ##     #t                    ##r      ##   ##           ##  #          ##
#       ####f   ##      ##     ## ##   #   # c                             r           #    ##   b       ##              #
##    # ####     #         r   g  t          #                                             ##          f                 #
#t    # ####   l        l #   ###     l      ##                                            ##              #b          f #
#     #                       ###       #    ###  r  r   #  ##        ##  ##  #           l##                   #       r#
#     #            #   ###  #     ###            ###l    #   #        ###    ##            ##          l       #    #    #
#  gr                  ###  ##  #       g   a    ###     ##                  #        l  r ##                  #         #
#      ##      r#          ###           #   f     #               #        ##     f     r                          ##   #
#   ####### t  g             #       # #              #       t        f    #             #       g        ##   #####    #
#  ##### ##  ### ###             c    c      r        #                      b         ####               ##  ######     #
########     ##### #  # g t   t#   #  ####                 ##   ##        g      #     ###       l       ##   ##         #
#########      t   #    l          #    ## b          ###     ###    b          ##    lrl        #      a#    #       #  #
#      #g #        t f#            #    ##            ##     ##            ##  ##                 #                ## ## #
# # #          l      r  g        g   #   r           ##                     ####   l             #  ##           ##   ###
##              ## ##                         #  ## ##  ## ##   # #     #    f ##          b        #     # #   ## ###   #
#                               b    t                   # #    # #  t  ##      ##        # #      ##     # #    # #    ##
#   # #         ## ##                    # #    r## ##    t    ## ##             b   ##  ## ##    ##    b## ##           #
#  ## ##         # #             # #    ## ##     # #                                 #  #   #              tg           #
#                  c            ## ##                                    ##   ## ##  f                #        g         #
#  ## ##   # #           # #            ## ##                  ##   ##    ##   # #               ##  ##  l##       ##    #
#   # #   ## ##         ## ##   ## ##    # #         f        f #    ##        # #   #     b      #        ##       ##g  #
#                                # #                                  #     r ##r##  ##   ##         ##                  #
#         ## ##   b     ## ##                   lb                                   b   ##    b      ##g  ##            #
#          # #    # #    #r#            b      t            c# #                                ##f    #   #       ##    #
#                ## ##                                       # ##  ## g          f  ##       f  b##            ##f##  A  #
#                                          f    # #       # #       #     ##         ## ##   # g                # #    # #
#   # #          ## ##            c     # #    ## ##   r ## ## ##     g    ##       b # #   ## b     ## #       # # g ## #
#  ## ##b         # #                  ## ##f                # #       g      f  ##   # # g          g# ## ##  ## ## ##  #
#                           b                  ## ##     ## ## #       ##  ##   t ## ## ##  ##           # #       # #   #
#  ## ##                         # #   ## ##    # #       # ## ##   #   ####       # #   #   ##          # #       # #   #
#   # #                   t     ## ##   # #                        ##        t               l##   ##   ## ##     ## ##  #
#                 c                           b              # ##       ####                        #     b            l #
#                    b      A   ## ##                        # #       ##  #     # #                              ## ##  #
#         # # b          l       # #                         # # g              ## ##    #  ## ##              #   # #   #
#        ## ##   g                                      # #  # ##  ##  r         f      ##   # #    ##     g  ##         #
#                                               # #    ## ## t     #f  t#    #               # #     #   ##a           r #
#        ## ##                                 ## ##         # ##       ##  ##              ## ##         #           #  #
##        # #          # #     # #                   b ## ## # #                 #   # #                         #    ## #
#    r       lt       ##f##   ## ##            ## ##    # #  # # g  g   ## g##   ## ## ##          ## ##       b ##    # #
#       t   b                                   # #          # ##    #  #   #     # #        # #    # #  f # ##          #
#   # #      t# #     ## ##  r## ##       # #                       ## l    A l             ## ##   # #   ## #           #
#  ## ##     ## ##     # #     # #       ## ##                     ##   b                       #  ## ##  #              #
#                                                      g      #                        ##         f     f          ##    #
#  ## ##     ## ##                b      ## ##     b # #    # ##l        r  #           ##     g                    #    #
# ####          ##  a####  f####     a##    ## l     ####  ##                       r           b          b         t   #
#  ####   g   g  #########   ##### a#####  ###     f a##   ######  ###### ##################  ########  ##################
#a #### #       la########      #############        a    ###           t              g                                 #
##  ##  ####  a   ########               ####    #   a    ## ########  #################  #######b #######################
##   #  a######   ##### a##  ### f##     #####   ##   la#  #           l                  r                              #
# a   a     ####  #####   # ####   ##### ####### ####   #   l####  ###########  ##  ########  #########  ##  #####  ### l#
#     ###      ##  ####         #   #### ## ###########g##  #          r  f                    b         b     g     b   #
#     t ####       a######   f  ##  #### #  # #####  ###### #  ########  #######################  ######### ####### ######
#####     #####     ####### ##   #   ### a    ##       #  g #                             l               f       g rb   #
###### g  ######    ####### ###  g    ###  #            a    ############################  ######### t################# f#
#######    A ####   ####### ###r  #     ## #r #### #  #aa  a  t         t                    l                           #
#####   #  #   f#   ####    ###  t#        ##b#### a  ##   # ##  ## g######  ########  #################  ###  ###  ######
######     ####a#   #####    ##   ##        #######  ###  a#              g  l                                   b     b #
##      #  ######   ## t##    ##  ##        ###      #### a############ b########  #########  ##  ####################   #
###   # #  ######   ##           ##         ###   af #a    ##g       b         r                    l  b      b   g      #
### f # ## ######   ##   ###     ##t        ###      #g    ##  #########################  ##########  ######  ##r ########
##   ## ## ###### r ##  ##    ##  #              a   ####a ##                             g                              #
######  #    ## #   #####    ##   #        a#######  ### l # #####  ######### b#####r ######  #######################  ###
#####   #  #    #   ####    ###l  # a     a## ####    ##   #      a    r     g                r      r    l r            #
#######   ## ####   ###########   #a a  ## #  ######  #        ####### l ########################  ####  ##  #############
######    ######a   ###########       ###  #              l  l   g                                                   g   #
#####a    #####     ##########   #   ###         a     #  a ######################  ####### l######################  # ###
#       ####   a  g ######      ##g ######  # #####  ###### #                        ll           g      g               #
#     ###      ##  ####         #   ####### ########### ## a###  #############  ###################   #  ##  ##  ### #####
#          g####  #####  a#######  #####a####### #### a #                gb      g                  t b           lr     #
##l  #   ######    ####t ## f###  ##     #####   ##     #  # ######  #####  ##########  ##   ##  ####################g ###
##  ## t####a      #######    g  a             a # l      ##        t              f       f l               f    tg     #
#a ######  l a  a  #######      #############             ### ####### # ########  #################  #########  ##########
#  ####  f       # #######  g#####g #####  ###        ##f  ##    A r  r  l       rf                                      #
# ####       a  ##   ####t  ####               t    t####  ###  ##  ###  ##  ##################  ######  ##########  #####
##########################################################################################################################
