metadata:
  gen_time: 3.3785128593444824
  timestamp: '2025-04-18T22:57:42.534778'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  ##A ## b        ##    ##       ##    ##    ##     ##  ##                                             ### ###   ### ####
#  ##  ## r  g     ##    ##       ##    ##    ##f   g##  ##                                                            ###
#  ##  ##          ##    ##       ##    ##    ##     ##  ##                                                  ### ###   ###
#  ##  ##      g  b##    ##    b  ##    ##    ##     ##  ##     ##   ##f  ##   ##   ##   ##   ### ###   ##   ##g  ##   ###
#  ##  ##          ##    ##       ##    ##    ##     ##  ##     ##   ##   ##   ## f ##   ##   ### ###   ### ###rl ### ####
#  ## b##          ##    ##       ##    ##    ##    g##  ##     ### ###   ### ###   ### #### ###   ### #### ###   ### ####
#b ##  ##          ##  g ##    l  ##    ##    ##     ##  ##     ### #### #### ###   ###r####f###   ###c###   ##   ##   ###
#  ## b##          ##    ## l     ##    ##   f##     ##g ##        tb### ###   ### ###r r##l  ##   ##   ##g  ##   ##  t###
#  ##  ##l         ##    ##       ##    ##    ##     ##  ##  # ###   ##   ##   ### ###   ##   ##   ##   ##   ##   ### ####
# f##  ##          ##    ##       ##    ##    ##     ##  ##  # #### ###   ### ###   ### ###   ### #### #### ###   ### ####
#  ##  ##          ##    ##    f  ##    ##    ##     ##  ##     ### ###   ### ###   ### #### #### #### ####l###f  ##  b###
#  ##  ##         l##    ##       ##    ##    ##     ##  ##     ##   ##   ##  b### ###   ### ###   ##   ##   ##   ##   ###
#  ##  ##t    f    ##    ##f      ##    ##    ##     ##  ##    l##   ### ### t ### ###   ##l  ##   ##   ##  r##   ###l####
#  ##  ##          ##    ##       ##    ##    ##     ##  ##  # ###  r### ###   ##   ### ###   ##   ##   ##l  ### ####c####
# b##  ##          ##    ##       ##    ##    ##     ##  ##  # #### ###   ##   ##   ### #### ####f###   ### #### ###   ###
#  ##  ##      g   ##    ##       ##    ##    ##     ##  ##  # #### ###  b##t  ##   ### #### #### ###f  ### #### ###   ###
#  ##  ##          ##    ##     g ## g  ## f  ##     ##  ##b # ###   ### ###  f##g  ### ###   ##   ##   ##  t### #### ####
#  ##  ##          ##   l##f      ##    ##    ##     ##  ##                                 g ##   ##  t##f  ##   ### ####
#  ## l##          ##f   ##       ##    ##    ##     ##  ##               ##  f### ###   ### ###   ##   ##   ##f  ##   ###
#  ##  ##  f       ##    ##    l  ##    ##    ##     ##  ##         ###   ### ###   ### #### #### #### #### ###   ##   ###
#  ##  ##          ##    ##       ## l  ##    ##  g  ##  ##  # #### ###   ### ###   ### ###  r### #### #### ###   ### ####
#  ##  ##          ##    ##       ##    ##    ##     ##f ##  #l### b ## r ##l  ### ###   ##b  ##   ##   ##   ##   ### ####
#  ##  ##          ##    ##       ##    ##    ##     ##a ##          ### ###   ### ###   ##   ##a  ##   ##   ##   ##   ###
#  ##  ##   l      ##    ##       ##    ##    ##     ##  ##     ### #### #### ###   ### #### ###g  ##  ###   ##   ##   ###
#  ##  ##          ##    ##l      ##    ##g b ##     ##  ##  g  ### ###   ### ###   ### #### ###   ## g#### ###   ## r####
#  ##  ##          ##    ##f      ##    ##    ##     ##  ##     ##   ##   ##   ##   ##   ##   ### ###   ### ###b  ##  ####
#  ##g ##          ##   l##   t a ##  l ##   b##     ##  ##    f##   ##   ##  f##   ##   ##   ### #     ##   ##   ##   ###
# g##  ##          ##    ##       ##    ##    ##     ##  ## f   ##   ### #### ###   ##   ##   ##g    # ###   ### #     ###
#  ##  ##      f   ##    ##       ##   g##    ##     ##  ##    l### #### #### #### #### #### ##    ###r#### ####   #t  ###
#  ##   #       b  ##t   ##       ##    ##    ##     ##   #     ### ###   ##   ### #### #          ##   ### ###   ### ####
#    ##  l   r       ##a    ####             l  ####  ###                 ### #### ###  #  l       r        ##   ###    g#
#           b      c         ##   b  ##  g       ##    ##g  ##r   ###  f  ### #### ### ##  ##   ## l l                   #
#           ##  ##                  ####                   ###    ###r    ### #      #          ##g  l    b              #
###   ##  ##########    g #         ####           r       ###    ########### #             #   #       r    f         f #
####  ##  ##########    ####  f##     #       #             ##    ########### ###          ##   # ### #####              #
####       #  #  ##     ####  ####          ####  ##         #     br ####### ###      ######     ### #####   #          #
###                      ##    ##           ####  ##   r     #        ####### ###      ####         # ##     ##   l   bf #
#            g           ##              l   ##       ##  ## #        ####### ###f    #####       t   ##                f#
#f     l       ##                      #             r##  ## #            ### ####    #####r         ###             ##  #
##        ##   ##   ##        ##  r  ####                    #            ### ####    #####     l  f       ##### f   ##  #
###   #   ##       #####      ##a   #####                    #           bb     ##   #####  b         #### #####     ##  #
###  ###            ######           ##            ##                        r  ##                         #####     ##  #
## g ###       ##     #####                 ##    ####          r     f      b  ##   ########    ###############     #####
#     ###     ####      ##      ##          ###    ##    ##                  r  ##       ####    #########################
#   A ##       ##             ######  ##g  ####    ##    ###                    ##   ##  ####    #########################
#     ##       ##    g        ######r ##   ####    ##    ###                                                             #
#   g ###c    ####      ##      ##          ###    ##    ##   f  #######             ########                 #########  #
##   ###       ##     #####         g       ##    ####           #######  A          ########                 #########  #
###  ###      b     ######           ##          t ##            #######    g        ########### f      l#################
###   #   ##l     b#####      ##    #####                      #########             ###########         #################
##        ##  l##   ##      a ##   r ####           g          #########                                              ####
#              ##            r         #              ##  ##   #################### ###### #  #####  ##  ############ ####
#                        ##                  ##       ##r ## ###################### #####     #####  ##  ############ ####
###                      ##    ##     g     ####  ##         ######################  ####        ##  ##  ############    #
####       #  #t ##     ####  ####          ####  ##              #################  ##          ##  ##  ############    #
####  ##  ##########    ####   ##     #       #       g     #     #################  ##          ##  ##  ############    #
###   ##  ##########      #         ####    r              ##  f  #################  ##                  #################
#           ##  ##                  ####        t l        ##     #####################                  ####     ########
#       a                    ##      ##l         ##rl  ##   #     #####################     # ##         ####     ########
#    ##              ##     #### l              ####  ###    ###  ##########       g###     # ##         ####          ###
#   #### ####   ###  ##     ######     ##  ###   #### ####        a  ##       #### ###  ##  #   ### ####       ##        #
#    ##        ####   #    f ####      #   ####        ##            #        ##########################        #        #
##   ###  ##   ## ##  #f      ##g      #  ## ##   ##  ###   #        ##       ##  l ##############    ##       ##      a #
## f   # r    ##         ###      ###         ##      #     #        ##       #     ##    ##    ##     #       ## t      #
#   ##    f   ##  ##       ##    ##       ##  ##     #  ##           ##       ##    #     ##     #    ##  f    ##        #
#   #   ###    ##     ##      r       ##     ##    ###   #       b   ##       #     ##    #     ##    ##      l##        #
#  ###   ###   ####                   b    ####   ###   ###  ###  ####### ## #  #####  ###  ###### ######b## ####### #####
#####    ##   ### ###       #    #       ### ###g  ##    ################### # ###### #### ####### #######################
### l        ###        ##  #    #  ##        ###          ### b                                     ##lt   r           ##
#       ##  ###    ##b  #   ##  ##   #   ##    ###  ##                        a##                    ##                  #
#    ##     ##         ###    ##    ###      ll ##     ##    #     l                                                    ##
#l #         #  ##  ##  ###   ##   ###  ##  ##  #         #  ##### ## ### ######### ### ####  #### ############# ## ## ###
# ####  ##       a      ##          ##              ##a #### ############ ## ########## #####     ####### ## #########  ##
#  ######   ###    ###   #  #    #  #   ###    ###r  ###### b ##                     ##        ##              f      #  #
#     ###     ###  #    ### # f  # ###    #  ###     ###      ##           l          #        # r     f         t    ## #
#  #  ###     ###  #    ### #    # ###    #  ###     ###  #   ##                      #    l   #       t              ## #
#  ###### b ###    ###  b#  #    #  #   ###    ###   ######   ## t             t  l t##        ##                     ## #
# ####  ##              ##          ##              ##  #### ############ ## ############################ ## #############
#  #         #  ##  ##  ###   ##   ###  ##  ##  #         #  ##### ## #############g############## ############# ## ######
#    ##     ##      A  ###    ##  f ###         ##     ##    #                                                          ##
#       ##  ###    ##   #   ##  ##   #   ##    ###  ##  b  g                b  ##         l          ##                  #
###          ###    b   ##  #    #  ##        ###          ###                                                          ##
#####    ##   ###c###       #    #       ### ###   ##    ################ ###### ###  ## ######## ####   ###### ##########
#t ###   ###   ####                        ####   ###   ###  #### ####### ## ### ####  # ########  #####  ## ## #### #####
#   #   ###    ##     ##              ##     ##    ###   #           ##       ##    #           ##    ##                t#
#   ##  #     ##f ##       ##    ##       ##  ##     #  ##           ##       ##    #     ##    l#    ##       ##        #
##     #      ##f        ###      ###r        ##      #     #        ##       #     ##    ##    ##  l  #       ##        #
##   ###  ##   ## ##  #       ##       #  ## ##   ##l ###   #        ##       ##    #### #########  A ##     t ##        #
#    ##        ####   #      ####      #   ####       r##            #        ##########  ##############    b   # a      #
#   #### ####   ###  ##     ###### l   ##  ###   #### ####        t           #### ###  #   ##  ### ####     t ##        #
####### l #######g                c        c #######   ###### ##    ## ## ##    ##       ##    ##       ##    ## ##    r #
#######   #######  #########      #########  #######   ###### ## ## ##g## ## ##### ## ########l## ######## ##### ## ######
#                  #########      #########                   ## ## ## ##c## ##### ## ######## ## ######## ##### ## ######
#              b   #########      #########     g             ##f##    ## ##       ## t  ## ## ##         g  f   ##      #
####a             A#########      #########               ### ##### ##### ## ##### ## ## ## ## ## #######   #  # ## ## l #
####               #########  ##  #########               ### ##### ##### ## ##### ## ## ## ## ## ###         ##g## ##   #
####         l    g#########g ##  ######### g             ### b           ##    ## ## ## ## ##             ## ##    ##   #
#        ######    #########b ##  #########f   ######        r##l## ############## ## ## ## ###    #A #### ## ############
#        ######    #########  ##  #########    ######       l ## ## ##############       ## ###   ## ##### ## ############
#b                 #########  ##  #########          g        ## ##                                                      #
#         r        #########  ##  #########             g    ### ##### ##### ## ######## ## ## ## ## ######## ##### ##   #
#      ##########   b         ##    f        ##########      ### ##### ##### ## ######## ## ## ## ## ######## ##### ##   #
# ##   ##########            g##             ##########   ##        ## ##                                           ##  b#
# ##   ##########         g       A       lf ########## cg## ###### ##### ## ### # ## ###         ##### ######   #####   #
# ##   ##########         f                  ##########   ## ###### ##### ## ### # ##g#####   ##  #####r#######  #####   #
# ##b  ##########                            ##########   ## f##    ##                  r##                 g      br    #
# ##   ##########                            ##########   ##  ######## ####  ########### ## ####   ########## ## #  ##  b#
# ##f  ##########             ##          f  ##########   ##  ######## ##### ########### ## ######  #########f## ##t##   #
#a b   ##########             ##    f        ##########            fg       f##          ##   r  ft        ## ##    ##   #
#       A          #########  ##  #########                   ######## ##### ## ##############  ############# ############
#  gf              #########  ##  #########                   ######## ##### ## ##############  ############# ############
#     g  ######   b#########t ##  #########    ######         ##                                                         #
#        ######    #########  ##  #########    ######  g     ### ######## ## #   # #######  ## #     ######## ## #####   #
####   f    l      #########  ##  #########          g    ###### ######## ## ##     ####### ## ## # l######## ## #####   #
####b              #########g ##  #########               ###   b##          ##   r       b ## ## c     ##      f##     t#
####               #########      #########             b ### ############    #### ##### ## ##### ## #################   #
#                  #########      #########                   ##############    ## ##### ## ##### ## #################   #
#           f      #########      #########   a         g           ## f     ##    ## f  ##   r   ##       ##            #
#######l  #######  #########      #########  #######   ######       ##       ##    ##    ##  t   l##  c    ##   b   l    #
#######  g####### l                          #######   ######      b##       ## A  ##    ##       ##       ##            #
##########################################################################################################################
