metadata:
  gen_time: 6.642100811004639
  timestamp: '2025-04-18T22:46:16.960914'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##             ##l## ## ## ## #g# ###### ####                       a##    ##   t##         #                            #
## ## ## ## ##    ## ## ## ## ### #      #                                                 g#           t  #        #    #
## ## ## ##l## ## ## ## ##             ###  #                    ###                ###     ##            ##   ##   ##   #
##g## ## ##g## ## ## ## ## ## #r# ###########f### ## ####a# #  #        A               #c       #                ####   #
##l## ## ##    ## ## ## ##                  a     #         r     ##                ##      ##   ######   ##    #    ## b#
## ## ## ##l## ## ## ## ## ## ### #### ######################     #                  #ff t #### ########     #  ##    ## #
## ## ## ## ## ## ## ## ##                ###  ###  ###a ### #    #  #            #  #   b###   #     ##   #  t ##    ## #
## ## ## ## ## ## ## ## ##           ###  #                #         #            #    a g #          ########  ### a ## #
## ## ## ## ## ## ## ## ##          a###  #b# g#a#  #      #       g r                     #    ##                 ##### #
## ## ## ## ## ## ## ## ##             #### ####t####f#### ## f     #              #           ####   ########   #   ##  #
## ## ## ## ## ## ## ## ## ## # ### a#   #a                            ##      ##    t         ##     ##  f##    #   ##  #
## ## ## ## ## ## ## ## ##        #  # ################### ##          ##  r   ##           f  ##    ##  b       ###### g#
## ## ## ## ## ## ## ## ##                ###  ### a###g    #  ####                  #### t     ##   #       b    ####   #
## ## ## ## ## ## ## ## ## ##l# ###  ###  # #    #  #       # ####        #  #        ####       #   #f  ##       #  #   #
## ## ## ## ## ## ## ## ## ## ###a######### ###  ## #a## ####   ##   l    # f#        ##   #   g     #######    b #  #   #
## ## ## ## ## ## ## ## ##              ##                    # ##        #  #        ## # #t##     ###   ######  # ##   #
## ## ##    ## ## ## ## ## ## ### ######################## ## ####        #  #        ####    ####    #             # f  #
## ## ##f## ## ## ## ## ##           ###  ###              #   ####     g            ####        #        ###     ###    #
##    ## ## ## ## ## ## ##             # a#l#t # #  #    ### t         ##      ##                         ##      ##     #
## ## ## ## ## ## ## ## ## ## # ###  #f#  #a#r #t#  # # r###           ##      ##           #          #####       #   ###
## ## ## ## ## ## ## ## ##        #### # ## #### #  ###  #          #              #       ##   f ##l######        #   # #
## ## ## ## ## ## ## ## ##       t##             # g###  # #t                              ###     #  ##          ##     #
##r## ## ## ## ## ## ## ##        ###### ####### #  # #  ###        g# b  r       #         ##         #         #### ## #
## ## ## ## ## ## ## ## ## ## # ###  ###A ###b # #  # #  ### #    #  #            #  #    # ##    ##   #  ## bf  ##  l#  #
## ## ## ## ## ## ## ## ## ## # # #  # #  # #  # #  # #  # ##     #c                 #     ##     #    ####     ##       #
## ## ## ## ## ## ## ## ## ## # # #  #    # #r # #g # #  #        ##            g   ##     ##     #     ##  t           g#
## ## ## ## ## ## ## ## ## ##   # #  ##   # #a # #  # #  # ##  #                        #   ###   ##  g####     l#  #   ##
## ## ## ## ## ##g## ## ## ##     # l##   # #  # #  # # g###     ###  g             ###     #### ###    a##  ##  ####  ###
## ## ## ## ## ##    ## ## ## ### # a#      #a # #    #  ###                t              ## ## b ##  ####  #    ##   ###
## ## ## ## ## ## ## ## ## ## #      #    # ## # ###  # ##           ##    ##    ##        ##  #   ##   ##   #g   ## f ###
##    g         ####            g######     ## # ###    ######  #   c             #   ##   ### ######## ####             #
#####   ##      ####t            #####   ##### # ###     #####  #           r     #   ##   ### ######## ###### #### ## ###
#####  #### b    ##              ####   g #### # ##       ###             ##      # ###    #      ##      #### #### ## ###
#  #    ##                    #   ##                 g     ### g               #### #      #      ##      ##             #
#                      #    ###             f               ##                c     #      #  f           ##             #
#           ##       ####   ###                            f  c  #### ####     ######  b   #   g  ##      ##             #
#         ######     ####    #                ##                      #  #     #               l  ##      ##             #
#         #######     #                      ####                 b   #  #     # ###########      ##  l   ##          f  #
#          #  ##     l                ##    ######g                   #  #     # #         #      ## lg   ##       g  f  #
# ##                         ####    ####  ########   l#### g         #r       g #         # r    ##       #     f       #
#####         t        ##f   #####  #####  #########  #####  fb       r          #         ############ ## ########### ###
#####  l          ##   ##   ######  ####   #########  #######   c  ####   #fr            ############## ##      ###### ###
# ##              ##  ####  ######   ##     #######    ######             #          b      ##      ##c      ##  ##      #
#       ##            ####   ##### t            g       #####         # c #     #####       ##      ##       ##  ##      #
#      #####            #  t #####                       ######       #         c     l     ##      ##f f    ##  ##      #
#      #####            #    #####    ##         t     f              #   #############             #### ##########      #
#       ##            ####   ##### l #### t #####            l####       ###############    ##      #### ##########      #
# ##              ##  ####  ######  b####  #######         r# #     c b  #             #    ## r    ##      c    ##      #
#####      g      ##   ##   ###### f  ##   #######         ## # ######   # #######     #    ##      ##        g  ##      #
#####              r   ##    #####          #####  f       ## # #        # #           #    ## f    ##     g r   ##      #
# ##      r                  #####                  ###     # # # ####   # # ######### #g   ##   f  ##      r    ##      #
#  f       #  ##   g           ##                  #####      # # #      # # #       c g  A##########  ###################
#        r#######     #             ##### b  ##    ######     # # #        # # #####     t ########## ####################
#         ######b    ####    #     #######  ####   A######    # # #        #            c     ##                         #
#           ##      f####   ###    #######  ####     ######   #   # #      #          g       ##      ##       ##  ##    #
# t f                  #    ###    ######    ##       ######  #  r# #  f   #             g            ##       ###########
# t#    ##                   r#    #####               #####  #  l      ## ###        c   rl  ##      ##       ###########
#####  ####      ##f               ####         l       ###                 ### #             ##      ##r     r##        #
#####   ##f    b####                ##     ##   f    tb      ##   l  fc   f  A# #   ###     t ##     r## r     ##        #
###             ####                  b   ####        l       #    g          # #             ##      #  # ######        #
#     #     #     #     #       ##   ##      g     l           ##              ##          ##           ## f            b#
#   t #   t #     #     #A      ##   ##                        ##              ##             t         ##     ##        #
####  #  ####f #  #  ####  #### ########################### #  ######  ##  ######  ##########r      bb  ##  t  ##  r  f  #
#     #     #  #  #     #      ############################## g######  ##  ######f ##########           ##   t ##     A  #
#   l #     #  #  #     #t                l   ##  ##          r        ##  ##c     ## ft   #### ############ #############
#  #  #  #  ####l #  #######                   #  #          l         ##  ##tg    ##      #### ############ #############
#  #     #      g #    r   r                  ##  ##         ########  ##########  ##  ##          ##                 ## #
#  # f   #        #                           ##  ##         ########  ########## l##  ##f     r   ##        r   c    ## #
#######  #  #  ####  #######                  ##  ######## ##      ##      ##      ##  ##  # ##### ##### ############### #
#  #     # t#           #   f                  #  ###########    l ##    t ##      ##  ##  # ##### ##### ##############  #
#  #     #  #           #      l              ##  ##        #####  ######  ##  ######  ##       ##  ##    f##     ##    ##
#  #  ##########f #  #######          b       ##  ##        #####  ######  ##  ######  ##       ##t ##b    ##    r#    ###
#  #  #     #  #  #  #                     b  ##            #  ##           f  ##      ##       ##  f     a     t #    ###
#  #  #     #  #  #  #                        ##  ##        #  ##              ##      ##       ## t##     ##         gl #
#  #  ####  #  #######  ####                  ##    b  f    #  ##  ##########  ###### r####   g ##  ##  g  ##     #      #
#     A  #              #                     ##  ##        #  ##  ##########  ###### t####     ##  ##     ##     #    ###
#r   g r #    t         #                  g   #  ###########      ##  ##A     ##      ##       ##  ##     ##   f #    ###
#  ####  #######  ####  #  #                  ##  ###########      ##  ##      ##      ##       ##  ##     ##     #    ###
#  #  #        #     #  #  #                  ##  ##           ######  ######  ## t######     r ##  ##     ##     #    ###
#  #  #        #     #  #  #                  ##  ##           ######  ######  ##  ######  ################### ####  #####
#### A# g#  ##########  #######   t       l   ##  ##g        l ##          ##           g  ################### #### ######
#     #  #        #  # g                       #b ##           ##          ##                 f             ##          l#
#     #  #     f  #  #  f                     ##  ##         ####  ##  ##############  ##                  g##      ##   #
#t #  #######  #  #  #  #######l        g g   #   ##      l  ####  ##  ##############  ##   t a             ##      ##f  #
#  #           #     #                   l    ##  ##  b            ##  ##  ##  ##      ##                  b##      ##   #
#  #           #     #g     r     t           ##  ##               ##rl##  ##  ## t    ##    r  t           ##      ######
#  #  ####  #  ####  ####  #                  ## g##   g       ###### f##  ##  ##  ########## ### ###### ######## ########
#  #  #     #  #        #  #  g        l       #  ##  t        ######  ##  ##  ##  ########## ### ###### ######## ####   #
#  #  #     #  #        #  #                  ##  #                ##f             t                   b     ##     ##   #
#  #  #   g #  #        #  #  l               ##  ##c              ##           g                          r ##     ##a  #
#        #  #        #   f      f            ###  ##  ##     ##  ##      #    #      ##  ##    #  #       #  g    #      #
#        #  #        #    l       ##r     a   #            a  ##  ##     #    #     ##  ##    #    #       #     l#      #
#######  #  #  ####  ####  #     ####             t        #####         #    #         ######     #    b   # g   #    # #
#     #     #  #  #  # b   #     ### b  ## t         ##  ####            ##  ##                   #         #    #    #  #
#     #   r #  #  #  #     #      ##   ####a         ##  #### f  ##   #### g  ####   ##          #         #  b #    #   #
#  #######  ####  #  # l####            ##     ##         ##  f  ##                  ##    #      #       #      #c  #   #
#  #    f   #     #        #            a r  ######  a b        ###       ####       ###    # #    #g      #    #   #   c#
#  #        #     #        #     c a         #######         ## #          ###         #t##  # #    #       ####   t#    #
#  #  #  #  #  #  ####  #  #    ##  a  ##   a #  ##           ####     ###   ####     ####      #    #               #tt #
#  l  # t#     #  #     #  # b #####   ##                ##            ##########                #   g#             #   ##
#     #  #t    #  #     #  #   #####                   b#### ## ####       ##   #   #### ##       #    #############     #
##########  ####  #  ####  #     #  g      ##      ## r  ##  ####      ##      ##      ####        #          g          #
#  #     #  #     #     #  #              ####   #####       # ###  b   #      #  g   ##  #         #                   ##
#  #l    #  #   lg#     #  # rf g          ###   #### b          t  ######    ######     g   #      #                  # #
#  ####  ####  ####f #  #######   r        ##     #     bf## ####     ##        ##     #### # #    #                     #
#  #        t  #     #  #  #      ##      f              ########     ##      c ##     #####   #  #t                     #
#  #           #     #  #  #      ##                     ####       ######   g######           #  #    ############# ##  #
#  #### l####  ####  ####f #     ####     ##         ##    ### ###      #      #      ### #   #   #   #       r     #    #
#  #f       #           #        ####  a  ##         ##      ####      ##t ff  ##      ####   #   #  #                g  #
#  #        #           #          #       b    ##          t## ####   #   ##   #   #### ##    #  #   #                  #
#  #  ####  ####  #######  ####               #####                    ##########      f      #   #    #  f  #  t####   l#
#     #   l    #     #                 a a    #####    ##     ####     ###   ####     ####   #     #    ##### ###    #   #
#     #      r #     #            a##          ##    #####   ##b#          ###         # ##   #t    #                 # ##
#  ####  #  #######  #  ####     #####               #####      ###       ####       ###       #     #f                  #
#  #     #  #  #        #        #####   fg      rg   ##         ##          b       ## bf     f#     ########           #
#  #     #  #  #  r     #         ##  b        t           a     ##  f####    #### b ##          #            #          #
#######  ####  #  ##########              ##  ##            #         g  ##  ##          b        #      t     #         #
#    f         #           #   #        #########         ### ##        f#    #         ###        #          f #       ##
#            r #           #   #t      l#########   l      ## ## t##b    #    # g   ##  ##    f     #            #######f#
#              #           #                 ##          f ####  ##      #    #b     ##  ####       #                    #
##########################################################################################################################
