metadata:
  gen_time: 6.652095079421997
  timestamp: '2025-04-18T22:56:11.810083'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#                   r                 r   tf         l       #                #                                       ## #
#    l             b                     g         l                               ##################################### #
#                                                 r                      f  b                  f##       ##              #
#              f                                             #                #                 ## l     ##              #
#  f b             l           f      l                     #    #        #    #     ############# ######## ############ #
#       l                     l                             #     #  ##  #     #    ##       t       ##                  #
#                        t                                   #    #t     #   b#    ##         l   f  ##                  #
# l                     g                            b             #    #l                  ##                           #
#                                                        #   #     #    #     #   #         ##   ##           l          #
#            r   r      f                                 # #       #  #       #l#         t     ##     g      ###########
#                                      t                       #            #      r  l              ########### l   g  ##
#                                        f                    b ##        ##               g         ##      t           #
#                                     r                 f         ##    ##       f ####################  g     t         #
#               r                                 f      ##         #  #         ##                                      #
#  t            r   r                             r        ##   #          #   ##        r                               #
# f                r                      f                  # #            # #              ################ ####   #####
#               r     f                   b                           f            ##      f ##            ##    #####   #
#              r              r          r   t             #                    #   ###########      t b   ##            #
#       f                                   b            ##          ##          ##   ##            ## ########          #
#                    b                                       ##      ##      ##       ##          l##         ############
#                                                     r     #  #            #  #  t                #     g               #
#              b   f                   b          l                                                #                     #
#                                                                         g f           r          #  b         g       ##
#                           t           b               t   #                  #  f                #l                   ##
#g    b                       l                 f        f##   #   #    #   #   ##b  t   t ##      ##     ################
#                                                        #g   #   #      #   #    #  t     ##       #######              #
#             r                                           l   #   #  ##  #   #          b                                #
#                                    l                     #  r# #   ##   # #   #  ##             g   t          # #######
#                                                           #g   l lb   g      #b   ##             ##   l       ##       #
#l           r  r                          l  b     b                                #             ##           #        #
#                                t                       ######      ##b     ######  #  g   t##   g             #        #
#                                                          l  ###### #########       # b  r  ##         t       ##    ####
#                    r                                            ##    ##g          ##g                         ######  #
#            a                          f               t      l  ##    ##  f         #                                  #
#            g       f             l     f   f           # ########################   ##      #     #  b                 #
#                             f l                        #           ##           #    ########     #  #                 #
#               g    t            A  b                   #                        #        ##                            #
#l   #  c  # # ###  a         ######   #####             #                       l#                                      #
#          #               r     #f#c      ####     #    #        ########      g # #                  #                 #
#### r     #           f r    #  #   g    ##  b c    #   ##########      ######## ###                  #                 #
#     #   f#     b ##f ###   g#  #      c  #         ra            l               ###       #                           #
#      #   #                  #  #      #         ####   l             a              #      ##     # ##                 #
#                t       #               #              # b      ##########          ###     ##    ## ###                #
#   r                     # #       #                     ########   ##   ########  #####       #  ## ###  #             #
#    #t   c####             #c     #       #         t                                   #   # ### ##  ## ###            #
# #   #                     #g         #   #   #   #  r#tbf                             ###   #####  ##  ####            #
#t#                      #      ####l  #  a#  r# t #   #                           # # ##### #####        ###            #
#####      ####          #     r       #A#     # # # # #r t     b   r                          ##          ##            #
## #                     # ###r #    ####################     f          a         ####  ###l# #     r      #            #
##         #      ####          c#    # # # # # # # # # #              r a                  ###              #           #
##t  t    l #                           #   #   #   #   #                          #   ##  ####              #           #
#        t           #     # l    t    g#   #   #   #   #      tf                               f    r       #           #
#c   l         #      #    #    #       #  g        #                              ##### ### # #            #t           #
#  ###    c     #          #     #r   A                r                                      ###          ###     #     #
#            g      #      #  #  g         #        ###    ##  ##          ##  ##  #   ##    ##### b  a   ####     #     #
#      # ########   #      # ###       #   #   r c         ##  ##    g     ##  ##           # ####   ##  ##### #   # #   #
# t    f      c         #     #   r    #   #        #      ##  ##          ##  ##  # ### #b#r  ### ##  #  ##    #  f##   #
#g   ft##########c  #      # ###A      #   #               ##  ##       l  ##  ##           #      #         ##  # ###   #
#              f    #      #  #            #        ###  ####f ##          ##  ####        ##  #   #        ### # # ##  ##
#  ###    g     #          #     #   c      r            #### r##   l      ##  ####     # ###                ##      # ###
#           c  #      #  r #A c #    b  #           #          ##          ##            #     #   A                  ####
#                 l  #     # c       c  #a  #   #   #   #      ##          ##      ## # # #     ##                   # ###
##          #    f   a                  #   #   #  l#   #  ######################  ##   #  #     #                   #  ##
##    l    #      ####g          #    # # # # # # #   # #  ######################  ##   #        #                   #  ##
## #     c  l   c      t # ###r #    ####################                           ## ##  #  #             #       ##  ##
#####      ####r  g      #  l          # # # # # # # # #                            ## ##  #  #  # r                #b  ##
#                  t     #      ####   #   #   #   #   #                           ##r  # ##  ####                      ##
#t#   #                  tg #          #   #   #   #   #                g                                           r#  ##
#    #   l ####             #      #       # g                                    g##   # ##  ####  ##     ##  ##   ##  ##
#                t        # #       #               f                               ## ##  #    r#                   #####
#       g  f             #             l # l       g    #                           #####  # ##r #               # #     #
#      #   #t c     r c       #  #      #         ####     g            b       b       #        # #    #g#      # #     #
#    g#  g #       ##r ###    #  #         #                                        #   #  # ##     ##### ########c#######
####       #                  #  #   l    ##         #                              #####  #  #  # # ##    ##  ##   ## g##
#    l     #                     # #       ####     #   t  ######################      #####  #  #    #    f#  #l    #  ##
#  g #t    # # ###       f    ######   #####               ######################         #####  #   ##        ## g #   ##
# #             #     #      b      #l###################      ##          ##      t   #  #  ##### f#####   ####   ## ####
# #     g  r      # #               #     g      #####         ##          ##      ##### g#  #  ####      #              #
# #  ############## ############ # g#            #####   ####  ##          ##  ##### r#####  #  #  #      #t       #c    #
# #  #                         r #  #         g#####     ####  ##          ##  #####     ##     #f ##     #### ##  #### ##
# #  # ##    #           #    ## #  #          #####    f  ##  ##     f    ##  ##     #  #   ####  ##                 # ##
# ## #  #   r#############    # f# ##  t r     #####       ##  ##     g    ## A##  #  ####     ## ###                 # ##
#r   #  #       r             #  #g     tr    l            ##  ##         l##  ##  #    r   #  #  ### ######## ######## ##
######  #  g     g            #  #####                     ##  ##r         ##  ##     ####  ####  # t                   t#
#       #       f             #         l  ####                                    #     #        #   g #  #c    #  #    #
# #     #        g            #     #l     ####     t                r             #  #  #  # ##  ##    #  ##   ##  ##   #
###     #   ####   #   ####   #     ## g   ####    t             A   ## ## ###        ####  #  #    # ######## ######## ##
#    l  #   #  #   #   #  #   #       t    ####     ##               ## # ###      #        #  #  ###             b g # ##
#########   #  #   #   #  #   ########   g          ##    #          #    ## t    f#  # ##  ####    # #      # #      #b##
##          ## #   #   # ##          #         l    ##  ###    #                   #  #  # g     r# # ######## ######## ##
## ##          #   #   #   a      ## #              ##  ###    ##                  ####  #  # ##  ##   ##  ##   ##  ##   #
## t# r        #       #          #  #              ##  ## c   ##       #            #####  #  #  g                      #
##  #  ######  #       #  ######  #  ###   ##b      ##  #      #  #    ##               #####  #  ##   ##  ##   ##  ##   #
##  #  #    #  #### ####  #    #  #  ###   ##       ##  #     t ####   ##            # t#  #####  #    #    #   #    #   #
## ##  # ## #     # #     # ## #  ## ###            ##  ####      g     #    #       ####     #####    ##  ##   ## r##   #
##     #  # ##### # # ##### #  #     ###            ##r   ###      l        ##             #  #  ###             #  #    #
########  #     # # # #  g  #  ###########       l      #  ###     ###      ##       # ##  ####  # b  b##  ##   ##  ##   #
#        g#       # #       #         ####t      f          ### r f ### #    #    #  #  #        #                g  #   #
#  f      #      t# #   g   #         ######              ## ###     ## ##       #####  #  # ##  ###   ##  ##   ##  ##   #
########f #     #   # #     #  ############# g         ## ##          # ##          #####  #  #         #  #     #  #   r#
##     #  # ##### # # ##### #  #     #####             ###   # #   fl    #       ## #  #####  #  ### b ##  ##   ##  ##   #
## ##  # ## #  gf # #     # ## #  ##    ##             ####  #                    ###     #####  #     #    #   #    #  a#
##  #  #    #  #### ####  #    #  #  #  ####           #####       ###       t         #  #  #####  c  ## c##   ##r ##   #
##  #  ######  #     g #  ######  #t #######               #        ###g   #    l  ##  ####     ####    #  #     #  #    #
##  #          #       #       g  #  #######             # #    #    ###   ##       #  g     #  #     r##  ##   ##  ##   #
## ##  l       #   #   #          ## #################   ##     ##  l      ##      ##  ####  ####    t #    #   #    #   #
##          ## #   #   # ## t   l    #################          ###        #      ###     #            ##  ##   ##b ##   #
## ######   #a #   #   #  #   #########    ###########   ##  A   ###             ## #  # f#  ####  r    #  #     #  #    #
#       #   #  #   #   #  #   #            ###########     #              A         #  ####     #      ##  ##   ##  ##   #
### f   # t ####   #   ####   #     #####  ###########    ##     ###              l##        #  #      #    #   #    # t #
# #     # a        r          #     # ###  ###########   ###     l###            #     # ##  ####      ##  ##   ##  ##   #
#       #                    a#       ###  ##    ##########  ##         ###     ## ##  #  #                           t  #
######  #                     #  ########  ##    ######### # #           ###    ##  #  #  #  ####   t  ## f##   ##  ##   #
#    #  #  g                  #f #    #######    ########g #              ###    #  #  ####     #      #    #   #    #c  #
# ## #  #    #############    #  # ## #######b             # ###           ###     ##        #  #      ##c ##   ##  ##   #
# #  # ##    #           #    ## #  #   #####            #  ###           l ### t  ##t # ##  ####   g   #  #     #  #r   #
# # g#t              l           #  #   #####  a           ###    ##    l           #  #  #            ##l ##   ##  ##   #
# #  ############## ##############  #            ####      ##    ####              ##  #  #  # ##      #    #   #    # g #
# #               # #              r#     f      ####      #                       #   ####  #  #      ##  ##   ##  ##   #
# #             #     #             #            ####                              ##        #  ####    #  #     #  #    #
##########################################################################################################################
