metadata:
  gen_time: 7.335336923599243
  timestamp: '2025-04-18T22:52:19.619613'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#         gt    #                   ######                g  #     c#c   #                 #        a  #    #      #     #
#              #   #                ####              ##      #                                                          #
# ##    t       # #            ###       ######       ##       #    #    #    r   ##    #    ##        #    #    #       #
#  b#           t#            #             l         ## #     #   #    #       r#             #     c  #    #   #     # #
#    #           #           #    ##          #  #    ###     #    #    #       #               # b  r  #    #   c#     ##
#     ##  g     #     tt   ##    #     ### #### ##          f #    #    #        #    #####    #        # r  #    #      #
# #     #       # #       #     # #    ########   t  #        #    #    #a   r   # c #     #   #        #    #    #      #
#  #   b #       #       #  r  #         ##  ##      #tl       #   # f  #       #   #       #   #       #   a#   #       #
# #  g    #      #      #       #    r   #    # # b  #  #       #  #    #      #     #     #     #  f   #    #  #       ##
## b    b  #### # # ####         #     ###    #b  ## # t #      #   #   c#   f#     #t  #   #     #    #    #   #      # #
##             #   #             #r             #  l #    #     #                                                        #
##          g                    ####           # #  # r  #     #         #g  #    #    #    #    #   #    #  g #     #  #
# #     t ##     b     ##       # #   #           #      #   r  #l  # cc #    #     #   #   # A   #    #g   #   #      # #
#  #######  ###########  #######                        #      r#  #    #  a   #     #     #     #      #  a #  #       ##
#                                                         r    #   #    #       #   #       #   #       #    # c # f     #
#                                   #####    tb       #       #    #    # f      #   #     #   #c    c  #  A #    #      #
##################################           ##  ### ##       #    #    #     a  #    #####    #      g #    #   c#      #
#                 t        b             l   ##    # #  #     #    #    #   c   #a     f        #       #    #    #     ##
#  r   t       r              g     #   #            ##  #     #   #    #        #ga           #        # r  #   #       #
#        l  ###########             #                 ###      #                                                        ##
#          #           #                              ##  l   # c  g #   #    l     # ## ## #          #   #      #      #
#            ##########b    g                    ###  ##     #           #               r #           #    #      #     #
#     f  r     r      b    r                   ######    ##     #################   #####  ###   ###  ##  ##########     #
#    b                           t   ##           ###           ##############      ###   ####   ###  ##  l         r lA #
##################################       #            ##        ##############          #####    ###  ##     g        l  #
#                     g        r              #       ##b            ######### g    ######### ##########                 #
#                                            ##     #      gr        ############## ######### ##########    rl           #
#  #######  ###########  #######   l     ##  ##       #     l        ############## ###       ##########         g       #
# # t     ##     t     ##       # #                   #     r        ############## ###      ###########                 #
##                               #                  l                ##   ######### ###g    ############   l##############
##                 #             #                             ##    ##   ######### ###     ############    ##############
##         #### # # ####         #              #      #      t##r l      #########      #########          ##############
#         #      #      #  t    #  g   t                   g          f   ######### ##############r         ##############
#  #     #       #       #     #   f            #              b          ######### ############### ###     ##############
# #     #       #  r      #     #        #  #                                   ### #############   ###     ##############
##    #  g      # #        ##    #       ##    ##     ##   b        l f        f### ###           ####################b  #
#    #           #      g    #           b#    #       # r               #### tb                                         #
#   #            #            #  l        #  l #  b    #                 ####  b  tc###l      ###  ##########     ########
# #             #              ###      #       l                        ####b   c##########  ###############t   f########
#              #   #  r     r    r                  #                      ##    g##########  ############    lg t########
# b             # #         b         #             #         c##          ##     ##########  ############ ###############
# # ### ###  #      ##  # # ######r ##  #  #     #  ####       ##          ##a                             ###############
# # ### ###t   ###  ##  # f  l####r  #     ####  #l ####       ##### ## #####                                    #########
# # #l  ###    r        #  g  ####   #     ####    r####    t  ##### ## #####  ## #  ######   #########   ####   #########
# #     ####   g     c  #  ########  ##  ######    ########  #   ### #   ##    ##  g                  #   #   #   #      #
# #      ### #####  ##  #  ########  ##########  #########    #  ##       #        ##                         ### # # #  #
# # #g   ### #####   #  #     #####          ##  ####   #        ##b    ###    #                    #   #   # #     # #  #
# #   # #### ##      t  ##   g####       t   ##  f b   t  #  ###  #g# b ###       # #  #   ##           # ### # ### ######
#   #   #### ## ##  a   #########        # t###       ##  ## #### ####  ##        #                         r # #        #
#   ##  #### f# ##  ### #########        #  ###  ####### ###       ##           #   # ##    ####    ##    # # #b# ########
#   ##  ###c  # ##  ### #######   #      #  ###  #########   ##  # ##   ###     #                         # #   # #      #
#   ##   ##  ## ##  ### ####gb# # #      #  ###   #######           ##  ###     #  ## # # #   ###           ##### #####  #
# # ###  ##  #  ##   ## ####      #      ######   ######  ## ## ###  ## ##        # # # #                         # #    #
# #   # ###     ##   ## ###  t##  #      ######  ###l                   ##        # # # # ##  ###   #  c#      ## # # #  #
# # # # ####    ##   ## ###  ###         #####  f###   ###      #      ###     ## #     # #     #   #   # #       #   #  #
# # # # ##   #####  ### #g   ####     g  #####  ####   # # #    # ##    ##     ## ### #   ##    ###  #  # ##    ### ###  #
# #     t  #######  ### #    ######   #  #####        ##   #A     b##    #     #                        # #         #r#  #
# #   f r  ######   ###    ########   #  #####  l    c    t#   t       # #     ##  ##  ##  #      # #   # #####     # ####
# #   b    ####   # ###    #######    #  ###### #  ##   ##    #   ##     ##         #         #         #     #          #
# # #   #######   # ###  ########     #       c #  #   #####       ## #  ##         #         ###   ##     ## ######  ####
#   #   ########### ### #########     b     t   #r #   #      ###  #### ###    ##   #     #     #       #   #     #   #  #
#   #   ########### ### ######           ####   #  ##  # ##     #    ##l #     ##   # #         ##  #t#g###   #r### #    #
# # # f ###########  ##   ####f   #   #  ####   #l #########        ###        #            #       #               #    #
# # #   ###########  r#   ####   ##   #  ####   #g #########    ##   #         ##  g# ###   ## ##   ####### ###  ## #   ##
# # #f  ###########   #          ##             #t ###### ##      f##    ##    tl   #                     #         # r  #
# # #       t######   # #l  r   ###   b       # #  ######         #####   #    ## # #   # #       # ### # # ####    ###  #
# # ##       ######  ## #####   ###   #  ###### # r  ###      #r  ######       ##   #           # #         #   # #      #
# c ###   ######     ## ##### #####  ##  ######      ###  t            ##         # #         # #   # # #  #### # #   #  #
#   ###   ######     ## ###   #####  ##  ######   ###### #    ###   ###        ##               #   # # #   #         #  #
#    ##   ######t ## ## ###   ####r A      ## b  r########       b #######     ## ###           ###   # ### # ### ## ##  #
# f   #   ###  #  ## ##   #  #####        g##   fb##         ##   ####  ##     ## #c#           # #   #   # # #       #  #
# #   # g ###   r ## ##   #  #####   ##  ####        ##  ### #     #     ##    ## # # #         # #  ## ###t# # # #####  #
# #  ##   ###    t##   t ##  ###     ##  ####   ######       #   ##      b#    ## #   #               #       # #     #  #
# #       ####  ####     ##c ###     ##  ####r  ####       #    ######  ###       # #    A      ##    # ### # ##### ###  #
# #  f   #####  #### t ####  ###rr#  ##  ###    #     ##  ##        ##   ##         #               # #   # #     #   #  #
# #  ##  #####  #### b ####  ###f    ##  ###    #  f  #        ###f      ##     # # # #  #            # ##### # # ### ####
# #   #         ####  #####  t##  #  ##  ####   #  #    ###   ########## ##       # #                 #     # # # # #    #
# #   # f      #####t ######  ##     ##  ###### #     #####    b######## ##    ## ### #    ## # #   #   ##### # # # ###  #
# #      ##### ######## # ## ## # #  ##  #l####  # #  ####          ##   ##    ## # g         #     #     # # # #   #    #
# b                       ## ##               r    f l        # #    ##        ## # #       # ####        # # ##### ###  #
# # ##   ### # ######## ######### #  ##  # #r## ## ####      ##    ###### #  A ## # #       #      r      #       # #   g#
#    ##  r   #       ##      f    #        #     ###    b     ##   #####  #    ###  #                     #       # #    #
# # ##  ## # # # ### ###### # #####  ##  # # #  ## #### ##    ###      # ##     #   # #     #   #         #       # #    #
#   r      # # #    c       #        b   # # #          ##          ##  b #         #       #   #         #       # #    #
# # ##   # # # # # # # ## # # # ##   #   # # #   # ## #      # #   ####   #               ###  #### # # #   # ##### ###  #
# # ##   # # # # # # # ## # #g# ##   #   # # #   # ## #         ## ####g ##      ##                 #   #   # #g#   #   f#
#       f# # # # # # #      #   f    #   #g# #               #      #          # ## #       #  ## ### #         # # ###  #
# # ###  # #   #A# # # ## ##### ##   #   #   #   ####     ## ###### ####       ###              #   # #     # # # # #    #
# #        ### # # # # ## ##### ##   #   # ###    c    #  ## ######  ##  f#    g###b  #          ## # # ## ## #c# ### ####
# # ### ##b### # # # #    #   #      #   # ###  ######   #   ## ##    ##       #         r         b# #     #     # a #  #
#            #f# # # # ## # # # ##   #   # #             ##  ##  ##    ##      ##   # # #      ##   # # ###a# ##### ###  #
# #  ## ## # #       # ## # # # ##       g # #  # ##t#           ## c#### #    #    g # #   #       # #       # #     #  #
# #  ## ## # # ### ### t    #        #   # # #  #r##              # #######         # ### #   #     ### ### # # # #####  #
#       b          ### #### # ####   #r      l      l     #     # # ###  ##    ###  #     #     #         # # #       #  #
# #  #  ## ### # # #       r         #   # ###  ####b# ##    #  #  ###    #    ### ##  #### # ### # # #     # ### #####  #
#   ##   ###   # # # # # ## # ## #   #   #   ##           ## # ### #####  #    #        # # #   #   # # #           # #  #
# #  ## ## ### # # # # # ## # ## #   #   # ###  #### # #####   ###    ##       ##   #     # # ### #c# # # ##    # # # #  #
#            c g # # #               #                  ##          ##              # #     #   #           #    g# #    #
# #  #  ## # # ### # ### ## # ## ##  #   # #g#  ## # # #   #        #####   #  #### #  #  A # ###   ### ### ####  #####  #
# #  #  ## # # ### # ### ## # ## ##  #   # # #  ## #   #   #   #   c  ##    #  #### #        c        #   #     #   #    #
#              r # # #               #                     #           ##   #   ##br#  # ##   ### #     ### ##### # # ####
# #  ##  # ### # # # # # ## # ## #   #   # ###  #### ####    #         ##g  #    ##                 #         #          #
#        ###   # # # # # ## #g##l#   #   #   ##      #       ##        ###     #### # #   #     ##  # # ### # # ###   # b#
# #  ## ## ### # # #                 #       #f #### ####    ##  #     ###l #  ##   # # # #           # #   #    g#   #  #
#                  ### #### # ####g  #       f                ## ##  #   ## #  #    # ### ###       ###    ## #######  ###
# #  ## ## # # ### ###      #        #  ## # #  #g## ##  #    ##  #     ### #  ##             #         #     #   #      #
# #  ## ## # #  f    # ## # # #f##   g     # #  # ## ##    #  ##    #   ###     ### # ##    ### #   # ###  #### #####   ##
#            # # # # # ## # # # ##   #   # # b            ##   ##   ### ##     ####             #             #     # #  #
# # ### ## ### # # # #    #   #      #   # ###  #######    # # ## # # #  ##  #   ## #   ### #   ###   # #   # # ### ###  #
# #        ### # # # # ## ###        #   # ###     r     f## ## # ### ## ##  f # #        #     #   # # # #       #  g#  #
# # ### l# #   # # # # ## ### # ##   #   #   #   ######      ##   ###   c##    ###  # #     # #   # # # # #    ## # # #  #
#        #l# # # # # # r    # b     b#   # # #                           ## #g ###  #       #     #     # # #     # #    #
# # ##  t# #r# # # # # ## # #f# ##   #   # # #   # ## # #          ###  ##  g   ## ##     #   ##      ### # ##    #####  #
# # ##   # # # # # #b# ## # # # #    #   # # #   # ## #     ####  ###g    #       #       g     # #     # # #     #      #
#          # #g#A         l #         l f# # #            # ###    # l   ##      ## #          ## # #   # # # # # ########
# # ##  ## # #f#b###r###### # ## # # ###r# # #  ## ###    ####    #    #     ##  ## #     #     # #           # #        #
#    ##  l   #       ##      t     #       #  f  ###   l   ###     ### ## # ### ##  ##### # # # ### ####  #   # #   ######
# #  #l##### # ######## ######  # ######## # ##### ###### #    g## g## ## ###   ##      #     c # # #       # #       #  #
#                         ##            f       r         ##     #####  ######  ##### ### #  #### # # #       ### # # #  #
#### # # ##### ######## # ## ##f# ######## #####l# # ###  #   ######    ####      #   #   #     r   # #   #      l#c     #
##########################################################################################################################
