metadata:
  gen_time: 3.4718542098999023
  timestamp: '2025-04-18T22:53:48.298812'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#                                        l                        #####   g###############  ###############    #####     #
#         g                                                     b  ###     ############### ################     ###      #
#    f    f      g                                  b                      ############### ################g          t  #
#          f                                                   ##    g    f ##############  ##############       f   ##  #
#b                            g   b                           ####    ##     f f         r            r       ##    #### #
############# ################################## ############ ####   ####      g                          f  ####   #### #
############# ################################## ############  ##l  ######                  r          t    ######  t##  #
#                             c f                                   #######                   t       t    #######      f#
# c                                                            r     ######                     g     r    ######        #
#                                                            ##  r    ####           t            l         ####  l    ###
#          f                    f                            ###      tb     t g    t##     b  ##           l         ####
#b    f                              f   l                   ###            ## A r  ####   g  ####      ##   g        ####
#                b                                  f        ##         f  ####   b######   b######    ####            ###
#     b        c                    f                              ###     #####  ########  ######## a#####     ###    l #
#                          b                                    g #####  b #####  ########  ########  #####  b #####     #
#              A                    b                            #######    ###    ######l  r######    ###    #######    #
#                                                              t ########   lt                               ########    #
#                                                            #g  #########                         l        #########   ##
#                                                        b  t##  #########     ###        ##        ###     ######### g###
#                                           f                ##t  ########    #####  tb  ####      #####    ########   ###
#                                                f           ##   ########    #####b     ####     f#####   t########   ###
#                                    b      a                ##  #########     ###        ##     g  ###   t #########  ###
#            a                                             c #   #########          b       t   r           #########   ##
#                                        l                    tf ########     l     f               g  g     ########  r #
#                                  f                   b         #######b   ###  b ######    ######   l### b  #######    #
####################### ############## ######################  r  #####    #####  ########  ########  #####b   #####     #
####################### ############## ######################   l  ###f  g #####  ########  ########  #####  b  ###   g  #
#               f            a       l                       ##     t   r  ####    ######    ######   r####            ###
#                               a         a                  ###            ##r     ####      ####      ## b          ####
# f  t                                                       ###      f            f ##        ##            f        ####
#        a                                                   ##       ####    g                             ####       ###
#                      l      A                                      ######            b               t   ######        #
#                 f                        f                        #######            g     f  b          #######  r    #
#                                                        c     ## r ######       c           g              ######   ##  #
#                                              r            c ####   ####     gb                  t          ####   ####r#
#                c  f                         f               ####    ##f  f                                  ##    #### #
#                                            f       b         ##  b     l  ##############  ##############           ##  #
#                                   l                           b          ################################        t     #
#     a      f  a                t                   b           gt###     ################################b    ###f     #
#            g                                                    #####    ###############  ###############    ####      #
#       ###  ###  ###   f   ###b   r  ###                    ####   ##        #####    ##    ##a   #####      a ##  #### #
#       ###  ###  ###    f  ###      t###        f    r      #####  ##  r     #####        g      g#####        ##  #### #
#  ###  ###  ### f###  ###  ########  ### t########  ###     #####  ##        #####                #####        ##  #### #
#  ###  ###  ###  ### r###  ########  ### g########l ###  r f#####  ##        ##### f              #####       f##  #### #
#  ###  ###  ###  ###  ###  ######## f###gf########r ###     #####  ##    a   ########     l   l########        ##  #### #
# t###  ###       ###  ###  ###                 ###  ### g   #########        ########r   b  la ########   f    ######## #
#  ###  ###       ###  ###  ###    g t  g       ###  ###     #########################  a####   ######## ######  ####### #
######  ###f #############  ###  ### b########  #################################a ###   ####   ###l ### ####### ####### #
######  ###  #############  ###  ###  ########  #################################  ###      a   ###  ### ####### ####### #
######  ###t #############  ###  ###t ########  ############################   ##  ###          ###  ##   ###### ####### #
# r###                 ###       ###  ###       ###        A ###############   ##  ###  l aa    ###  ##   ######  ###### #
#  ###           g     ###       ###b ###      t###          ###############   ##  ######  f ######  ##   ####### ###### #
#  ###  #############  ###g ################## f###  ######## ##############       ######    ######       #######  ##### #
#r ###  #############  ###  ##################  ###  ######## ##############     r ######    ######    a  ########  #### #
#f ###  #############  ###  ##################  ###  ######## ############a        ######    ###### a       #######  ### #
#  ###      l###  ###  ###       ###  ###       ###  ###      ############         ###### f  ######  l   l  ######## ### #
#  ###       ###  ###  ###   t   ### r###g      ###  ###      ############        ga                     a  ######## ### #
#  ###  ###  ###  #############  ###  ###  ########  ###  f   ##########a        g aa    a   g  aar   g       ###### ###g#
#r ###  ### t###  #############t ###t ###  ########  ###     b  a        l   r   g    ##########           a  ######     #
#  ###  ###  ###  #############  ###  ###  ########  ### t        ########## a    g   ##########      a   ##########r  f #
#       ### r###         r       ###         r  ###               ##########          ##########  l       ##########     #
#       ###  ###          t      ###    g       ###f         a f  ######f             ##########              ######     #
######  ########  #######################  ###  ########l     ##########a         a   r            a     ar   ########## #
######  ######## t#######################a ###  ########      ############l  a               tf            f############ #
######  ########  #######################  ###  ########    l ############         ######    ######      t  ############ #
#     g cr    t      af     g         ###  ###  ###  ###    t ############       a ######    ######  a      ############ #
# g                         t         ###r ###  ###  ###      ##############f      ######    ######   f   ############## #
#  #############  #############  #############  ###  ### g    ##############   f   ######    ######       ############## #
#  #############a #############  #############  ###  ###     ###############f  ## f######    ######  ##   ################
#  #############  #############  #############  ###  ###     ###############   ##  ###    a     ### f##   ################
#  ###    g            ###  ###  ###  ###            ###     ###############   ##  ###          ###  ##   ################
#  ###f l           ff ###  ###  ###  ###       t    ###     ####################  ###     fa   ###  ### #################
#  ###  ##################  ###  ###  ###f #############   r ####################  ###   ####   ###  ### #################
#  ###  ##################  ### a###  ###g #############     #########################a l####   ######## #################
#  ###  ##################  ###  ###  ###  #############     #########        ########       r  ########   f   r##########
#  ###       g              ###  ###          f              #####  ##        ########      r   ########        ## a######
#  ###                 t    ###  ###         r            g  #####  ##        #####                #####   rg   ##  ######
#  ###      r               ###  ###                         #####  ##  a     #####    t a       r ##### l     a## a######
#gg###                      ### g### r t                     #####  ##     t  #####    f       a   #####        ## l######
#A ###                   a  ###  ###         r     b   t     ##### a##        #####a a ##a   ##f  f####    ft a ##  ######
# f     a  ##                    f            ## r   #       #                      #    f        g  #   #               #
# t        ##        g                       b##     # r  g    #  #####         # #####              ##  t  b            #
#        b#####            bg r              ### #  ##                            #   #         r    # # #  f            #
#   t         # #####            f    r      #l  #   #       # #  #               #   #       g        #                 #
#    r    #         # # ##### b             ##   #   # ##### #        #   #           ### ###        # # # f          #  #
# ##      #           #     # ## # #####    #  g #   #     # #                 #        #   #        #   #      #     #  #
# A# # #  ###         #       ##       #    #    ##  #     # #  #     #                 ### ###    ### # #      #        #
#    #      ###       #       ## l          #     #  #     # g  #     #                   #   #  g #  ##                 #
#    #          ##### # ##### #### ##       ##    # ## #####                       bfg    #   #### # # #        #b       #
#    #           #               #  ####     # f  #    #       g            ###           #     ###  #          #        #
#    #    r      #   A          f#    #      #f   #    #     g              #         b       #### # # # #      #g####   #
# #  #           #         t   A##   f#      ##   #    #                    #                 #    #  g  #       ###    f#
# ## # #  ## f   #              #    ##       #  ##    #       ### ## ## ## # ###  #          #    #     #      # ####   #
# t    #   #### ##### # ##### ###    #        #  #     #       #            b #    #       g    g        #      #        #
#  t   #    f #  b #  #    #    #   b#        #  #     #  l  #       c        #       # #     #    #            # #      #
##     #   r  #t   #  #    #    ##   #        ## ## ## ###   #       c t              # #     #    # r   #        #      #
##     #  g r #    ## #    #r    #   ##       #          ### #                             f             #        ###   g#
##            # l  ## #    #     #    #     ###     f      # # #   ##                                b      #            #
##   #        ##   #  #    #     #    ##      #            #        #          #                            #     #t#    #
##   #  g  b   #   #g # ##### ######  ##      ## #     #####g  # #  ###        #  r         b     # #             # #    #
##   #  r      #   #  # ##### ######  ##      ## #     #####   # #             #              A   # #f            # #    #
##t  #       l##f  #  #    #r  t #    ##      #      f     #   # #  #      f   #      A  gb          g      #     # #    #
##            #    ## #    #     #    #   #  ##            # ### ####                                       #            #
##     #      #r   ## #    #     #   ##       #          #####  g           g     b                      #        ###    #
##     #      #    #  #    #    ##   #     #  ## ## ## ###   #             b          #g#     #    #     #        #      #
#      #    l #    #  #    #    #  r #    ##     #c    #     ### t            #       # #     #    #            # #      #
#      #   ########## ####### ###    #    #   #  #     #       #              #    #                     #      #        #
# ## # ## ##     #          t   #    ##   #   #  ##    #       ### ## #   # # ###  #               #     #      # ####   #
###  #           #          l   ##    #     t##   #    #                    #             b              #       ###     #
#    #  f#       #               #    #      #    #    #                    #               g #      # # #      # ####   #
#    #  ##       #               #  ####     #    #    #                    ###f          #     ##  g#         g#        #
#    #  #      ###### ####### #######       ##    # ## ######                         l   #   ####   # #        #        #
#    # t#   ####      #       ##            #     #  #     #   f#     #                   #   #    #  ##                 #
#  # ########         #       ##      b## ###    ##  #     # #  #     #   f    #        ### ###    ### # #      #        #
####      #          g#     ############f   #    #   #     # #t                #        #   #        #   #      #     #  #
#        g#         ######### l     f       ##   #   # #######  f     #   #           ### ###        #b  #            #  #
#    f    #r  #######     f                t #   #   #       ###  #  f#   #       #   #                                  #
#         #####           t      t           ### #####         #  #   #           #   #              #  ##               #
#t         ##         t g b              b    ##     # f   t   #  #####           #####       b      #                   #
#          ## f    l    l       r      t    l ##     #       # #    #           #   #                # # #               #
##########################################################################################################################
