metadata:
  gen_time: 10.7102792263031
  timestamp: '2025-04-18T22:51:29.519935'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##           ##    ##    ##   ##             #     ####   ### #### #### ###   ##  r##   ##   ### ####l#### ###   ##   ## #
## #          ##            #    #        ## # #  ###### ###   ### ###   ### #### ###   ### #### ###   ##   ### ###   ## #
## #        r###   g             #             #   #                                  l ### ###  b##   ##   ### #### ### #
#      #  l         ##                  b                                                    ##g  ### ###   ##g  ### ##  #
####             ##  c          b l       #############   ### #### ###   ##   ##   ### ###t  ##  g### ##         ##   # ##
####  a         ###        #      #        ############# #### #### #### #### ###   ###g#### #### ###        ## l###   # ##
####    #          a       #   b       #                                                ### #### ###            #### ##  #
#  #  #####                ###  #               #         ##   ##   ##   ## g ### ### f ## b ##   ### #    ###   ##  ##  #
#      #        ##         ###    ######        #                                      ###   ##   ###       ##  t#  b #  #
# #             ###         ##    ########   ## # ##           ### ###   ##   ##   ### ###  f##   ##   #    ##          ##
#               ######                  ##      # ###### ##  g ##   ##   ### ###   ##   ##   ### ###             ## g  ###
#  #             ####                             #####r  ## c ## l ### #### #### ### c ##  g### ###    ##    # #      # #
#  #                         A   ##  #            ## ##   ### #### #### ###   ### #### ###   ##   ###  ##       # #    # #
#        ##                  #         ##   # #      ##   ### #### ###b  ##   ##   ### #### ###   ### ###         ##     #
#  ## r     ##   #   #      g f        ##   # ##                    ##   ##   ##   ##   ### #### ###          gg ###   ###
#  ##    ## ###g###gg              #        # ##     ### ###   ##   ### #### ### g ## f ##   ### ###    #        ##   ####
#####   l##   ####  b                         ###    ##   ### ####t#### #### ###   ###       ##   ##       #  tg ##   ## #
# ###  ####   ###                  #   a            ###   ### #### ###   ##   ###b#### ###   ##b  ##   ##  # #   ##   ## #
#  r    ###    ##    ### ##      # # ##     ##      #### ###   ##g  ##   ##   ##  ###   ##   ##   ### ###    # t ##   ## #
#              ###       #       ### #           ##                              g ##   ##  ###   ### #      #       ### #
#g   #       # ##  ####           ##l             # f##g  ###c#### #### ###   ##   ##   ##  ### t ##g       ##   #   ### #
#   ##     # #     ##             ##              # ###   ### #### ###   ### #### #### ###   ###                         #
#   #####          ## #           #   ###      #               ##   ##   ### #### ####   #   ###t       #   ### #     ## #
#   #       #   #l ####        ##            r #    b### ###   ##  t##t  ##   ##   ##       ###   #        ###    #   ## #
#       #   #   ## ##         ###         ##         ##   ###b#### ###   ##  l##   ##   ##  ###t  ##       ###       ##  #
#           # l #####      ###### l ###         ###  ##   ### ####f#### ###   ### #### ###   ### ###   ##       #     # ##
#   b             ###b     ######    c#              ##   ##   ##   ### #### #### #### ###   ### ###   ##   ##          ##
#       #### #b    ###      #   g          ####  # # ##      t ## b ##   ### ###   ##   ##  ###   ### ###         #    # #
#            #       A                   l #######   ###  ### ###  ### f ##   ##   ##   ##   ##   ###      ###    #    # #
#    #       ###     # #    t #    #     ###        ####  ### ##   ###   ##   ##   ## b ## l ## g  #        ##   ###   # #
#    #     #####     #        #          ### ###  #####                b ### #### ###   ##   ### # #   ##       ###   #  #
#l     b#   ####         #           b##  ## ###   #b##   ##   ##   ### #### #### ###   ##   ### # ## ###    #   ## tg# ##
#     b    #####    ##              ####   ###       ### ###   ##   ### ###   ##   ###  ## l ##       ###    #   ##   #  #
#      ##           #          #    ##########  r  # ### #### #### ###f  ##l  ##   ###t      ##   ##   #  f          #   #
##### ###     #           ###  #r       ######      ###  t### #### ###   ### ###   ##   ##   ### ###               # #  ##
#     #      ###    g   #####        ##         #   ###   ##   ##   ##   ### #### ###   ##   ### ###         #  #      ###
#    g#     ####       ###  #        ##         #    ### ###   ##f  ### ###g  ### #### ###   ##   ##         #    #    # #
##    #           #     #   #   #             #      ### ###   #   #### ###   ##   ### ###   ## l ##    #      g       # #
#    ####                      b          ##     ### ##   ###    #b###   ### ###   ##   ##   ##   ###                    #
###   ## r        #             l       c ##     # # ##  b##   ##   ##  t### #### ###   ##   ### #### ###a  ### #### #####
#     ##   b   a  # ##        # ##     #           # ##   ## l      ### ###   ### ###   ##   ### ###  b##   ##   ##   ####
####  ##     l    # ######    #    #########   t     ### ###   ### #### ###   ##   ##   ##   ##                          #
#    ###   ##  #  # ######r             ###         #### #### #### ###  l#  t ##   ##  l##   ##g  ##   ##   ### ####t### #
# ######            ##          ##   a# #          ####   ### ###   ##   # # ###   ##   ##   ##   ##g b### #### #### ### #
#   #       ###     ###    r    ##    # #            ##   ##   ##   ##   # # ###   ### ### g ##   ##f            ##   ## #
#   #   l  r ##            ###     # b  #       g #  ### ###   ### ### gf     ### #### ###   ##   ##   ##   ##t  ##   ## #
#            ##                    ##      ##  #    #### ###   ### ###  # #  l### ###   ### #### ###t  ##   ##   ##   ####
#  #     #  l##                     # #     l    #  ###   ##   ##   ##  # #l  ##   ##   ### #### #### #### ###  b### #####
#  #   ###   ##       b             # #     ###      ##   ##   ## r ##    ## ###  b##           b ### #### ####l#### ### #
#  #         ##    r               ####      ##      ##   ### ####r###   ### ###   ### ###   ##   ##   ##   ### ###  b   #
#     c                            ##    b       cl  ##  f### #### #### ###   ### #### #### #### ###   ##   ##   ## r  ###
#      ###          ##  # #                 ##   #  g##   ##   ##   ### ### b ### ###gg ### #### #### ###   ##   ##   ####
#    c ###          #  l###        #    #   ##   #   ### ###   ##   ##   ## a ##   ##   ##   ## c ### ###   ### ###      #
#      ###      #  ##         l#  ##    #    #   #  #### #### #### ###  l##   ##   ##   ##   ##   ##   ##   ### ##    ##t#
#  #    #             a     g  #     ## #    ##  ## ###l  ### #### ### A ### #### ###   ##   ### ###   ##   ##           #
#         #      g# # r               #    # ##      ##   ##   ##   ##   ##  #### ####t ### #### #### ###   #    ### ###f#
# ### ##  r#  #  ##  #  ### #### ### ##### #  # ### ##    #     ##        l ##    #  #  ##   ##          # g         ## ##
# #    #      #    # # #    ##   #        ####   #        #  #t  #   ##   #  #  bt# ### #   r#  #   ##   #   # b#  b     #
# #    ##     #  #  ## #  # ##   #      # ####### c  ###    ##  ##    ##  #  ##  ## ### ##  ##  #f ##    ##  ##    ###   #
#       #  #      ####        #   #     # ##    #   ##  a   ##c  ##   #      ##t ##     ##  ##      # c ##   ##      ##  #
# #        #  #  ##  #    # ###   #     #   #  #r       ##   #   #    ##     #   #   #   #   #     ##    #       ##      #
# #     #  #A r      # #  #      ## #    #  #          ##    ##  b    ## #  ###      # r    ###  # ##       ##    ##     #
# r     #  #  #  ##### #  #  g   ## #    ####  #  # #   # c  ##       ## #    #  c      c   #    # ##       ##    #   # ##
#       #     #           # ###   # #  ## ###  #  #######   ###  ###g ## ##       ### ###      t##c##  ###  ###   ########
###      #   ##  ####  #  # #    l  #      ##  #g #   ###   # #       #  ##     # ### ### #     ##  #       # #   ###   ##
##         # ##  ##    #     ##  ## ## #### ###            ##     cg #####  ##### #     # #####  # ###      t ##         #
##      #    ##  ##f # #  # ###        #      ####      ## #           # b  ##### #     # #####    #           # ##   t  #
##      #  # ##  ##### #  #   #  ##### #         ############ b ##    ## c     r  ##t  ##          ##   t##   ############
##      #  # ##  ###   #      #       f    #### # #####           l   ##  ##      c#   #    f c##  ##               ######
##      ## # #   ##    #  # ### ##########                l         c          #           #    c                        #
#        # # #     ### #         ##                    ##   c###    c      b #####   #   #####             ###  b ##     #
#       r# # #      ## #  # ### #   #     ##  g# # ### ##    #####    a  c#  ##            l##  #        #####    ## ### #
#        # # #     g#     #  ## ##g##  #  ##  ##  ## ###  ##  f f## c     ##  ##           ##  ## c     ##     ## a### ###
##A     #  # ##     #g  A #  #    ## ###r ######       r  ## c   #         # b##    ###    ##  #         #     ##        #
##      ## # ##     #     #  #    ##  ##  #    #  #   ######           # ######     ###c    ###### #         t ### ##   ##
#          # #       # #  ####    ##  #####    ## ### ##          a##  ####       #  #  #     f ####  ##   f     c ## # ##
#        # #       ##  #   #########                ####l##       ######        t #  #  #c t       ######       ## ####  #
#       ## # ##       r#   ##  ##  #####                 ### c    #       ###                 ###      g#      ###   t   #
#       ##      ## # ##  ### #    #     ##         ### ### #     ##  f      ####       t   ####   a     ##       ### ### #
###        #    ## ##     ##    # #    #### ##  ## #####         # c   ##   #  #l  l       ## # l ## r   #   ct c  ##### #
###     #    ## g# ##     #####   #    #                f     ##       ##  ##c    c           ##c ##  t    ##            #
#       #l   ##  ## #########  #       #   #                # ## f cc   r  #         #      c  #           ## #          #
###     ###  ##  ## t  ##   #  #       #   #  ##      ##### ####   l###    #         #         #b   ###    ####t#####    #
#       ###  ## ###   # #    #  #    #     #####  ##    #####        ##  ###      ###  ##      ###  ##        #####  r ###
###        # ## #     # #   ###    # ## # ######## ###         #### c## c##         # #         ##  ##  ####     l   ### #
###     #  ## # #       # g #           #  r     #         ### ##   c##   ##     ## ###  #    g##t  ##    ## ###   lc    #
##r     #  ## # #  #                      ## ####   A      ### ##             ## ##  #  ##### c      c    ## ###         #
##         ## # #                                fl   ##   #   ##     r##   c###  #  #  #r####   c##      ##   #   ##    #
##      #  ##                                         ##   #   ##      ##    #### #  #  #  ###    ##      ##   #   ##    #
##      ##                                                 ### ##             #####  # c## ## t           ## ###         #
###                         ####       #    # ####t        ###l##    ##   ##     ##a### ##     ##   ##    ## ###    t c  #
#    f  r   ## #        #  ##         ##    #  ###  ##         ####  ##  ##         # #         ##  ##  ####         ### #
##      ##  #         #            ######   #  #  ##    #####        ##  ###      ##  ###      ###  ##        #####a   ###
###  #  #   #    #  # # g    ###   ###    # ##        ##### ####    ###    #         # g     l #    ###    #### #####    #
###     #   ###     f #   #  ###          ##   # #   cfl    # ##     c    f#f        # c   l   #      f    ## # c      c #
###  #  ## ####   ####    #  ##  #    ### ### #  #         r  ##      b##  ##               l ##g ##    f f##        l   #
#    #     #    ####   #  #  ##  #    ### #        #####      f  #     ##   # ##      c    ## #   ##  l  #         # ### #
###  #  ## # ######      ##  ##  ######    ####l # ### ### #     ##         ####         l ####         ##   f # ### ### #
#  A    #  ##       # ## ####### ##g    ##########       ###      #       ### f  l        l   ###       #      ###    r  #
### ##  #  ##                                       # ## ## c g l ######          #  # l#          ######   la  ## ####  #
##      # #### ###########   ##### ##            #### ##           ##  ####       #  # g#    A  ####  ##l       g  ## ####
#    f t##     #########   ####  # ##    ##  ######   ######     c     # ######     ### c  g###### #         b ###### b ##
# # ########## ##r ##   ####  #  ## #    ## g ####     b  ##  g b#     l   #g ## ag ###    ##    t a     #     ##       t#
### #      ###        # ##  #    ## #    ####   #### ###  ##     ##f      ##  ## l         ##  ##       ##   l ##  ### ###
##   #####  ####   #    ##   #   ##  ######## #    ### ##  f #####        #  ##             ##  #      t #####  f ## ### #
# ####f                                                ##    ###     r       #####a  #   #####       g     ###    ##     #
#                                                            f          g      # f         #t                            #
#######                                           # ###               ##  ##       #   #       ##  ##      b    f   ### ##
#####           ###                  #        #   # ### #####  b##    ##        c ##l  ##          ##    ## ft######### ##
##       ###                         #                  ## #       c   #   f##### #     # #####    #  c          ##      #
##   ## ####                       ### #            b l    ##     l  #####  ##### #     # #####  ##### r      ##         #
# #####                                       #   #   ###   # #          ## g   # ### ### #     ##  #     r # #  t###   ##
#           ##          #         #  #  ####      # #####   ###  ###  ## ##       ###t###       ## ## g###  ###   ##### ##
#      #    #       #   #   #                     # #   #    ## f     ## #    #             #    # ##       ##    #   # ##
#      #g  A      #              #     ##      ##  l   ##    ##       ## #  ###      # t    ###  # ##     g ##   f##b  f #
#       ## #   ## ##           #g   #  ####    #  b     ##   # g #    ##t    #   #   #g  #   #     ##    #   #   ##      #
# l            ###      r     ##   ########      #  ##g     ##   ##l  #      ##  ##     ##  ##      #   ##   ##   l  ##  #
#          #r  ###          # #    ######      r##   ###  b ##t ##t   ##  #  ##  ## ### ##  ##  #  ##    ##  ##t c ###  t#
####       ## ##   ##     # # # #####           ##     g  #  #t  #   ##   #  #    # ### #    #  #  l##f  #   #  #  l     #
###  ###   ###   ##   ##  # # #  ####   #  ######## ##    #    r##          ## a ##  #  ## t ##          ##b         ## ##
##########################################################################################################################
