metadata:
  gen_time: 14.91049599647522
  timestamp: '2025-04-18T22:57:57.528209'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#        ####     ####  f#   #####     ##  #     #c  t#           ##   #           ####       ##    ##    #  #####c#  #  #
##  ##   ####       ##       #####      # ####   #  # ##  ##  ##  ##r  ##       ####  #  # #####        #### #   ###     #
##  ##   ####      ### f #   #####                 ## ##   #       # #  #   ##        #A ###     ##  ####f #       #  l  #
##  ##   #### #     l    #   ##############   ##c  ## ## ###    #### #    #### ##   ###  #       ##   #    ## f# b     ###
##  ##   ####     ##   ####################        #  ##c###    ###  ##   ##   ##   ###          f#         #  #         #
##       ####  t    r   ##  l#               ##  c    ##r l  #      f##    ##  g   ##      ##    ##         #  ##f       #
##       #######        #    #             ###             t ###                   ##    ###     A##        ## #   ###t  #
#       f####    #           #      rf          r         #### ##  ##            ####            A     ##   ##     ##   ##
#        ####    # r         #   ##########  ##  r    r                #  ###  ###  t   ##      ########            ##   #
#       r####        #      ######        #  ######   #######        ######            ##           ## ll     ###   ##  ##
#  ##     b          #  #  ###t        l     ######   #######        ######         t  ##          l##        ###   ##  ##
#  ##            r   #  #  ###               ###          l    r       #  ###  ###      ##   l  ########  t         ##   #
#  ##  ######   ##t  #  #   ###############      r    c   ####t##  ##            ####                  ##   ##    f##  f##
#f ##  ############     #    #             ###      l       f###                   ##    ###   r  ##        ## #   ###   #
#            # ##   #   #   ######c          ##       ##     #    l  ##    ##      ##     t##    ##    t   t#  ##        #
#                  ##  #   ###   ########## t      #  ##f###    ###  ##   ##   ##   ###      g    #         # r#         #
#                      #   ###                ##   ## ## ###    ####l#    #### ##  g###  #       ##   #    ##  #       ###
###           ## r         ###    ########         ## ##   #     f # #  #   ##        #  ###     ##  ####l #       #   t #
###   #####   ##         #     ## ##     # ###   # ## ##  ##  ##   #   ##    c  ####  #  # #####     #  ######   ###     #
###   #####      #  l  t###   ### ###   ####     #   c#   #       ##   #   c       ####r      ##    ##    #  ##### #l #  #
###t  #####    f #   #  ###   #######   ###  # ##  ### ##       #  ########  #f  ##  r# ### ####  l    #####  ##   #   ###
###   #####   #      #   #     ## ## b   # r    #      ##  ###  #  a     l   #   ##  ## ##   # #     ### #    #         ##
###  a#####        # ##         b          # f  #      ##  ###  ##     t     ##  ##  #  ##     #  ####      ####r       ##
###g             f       a        t        #  a ### #            #  ##       ##  #   #  ##   f #  ##       r   #   t  a###
#                 #       ##           ##  # #### ######b    ##           ####   ##  #  #l   #    ## ##  ###f   f##      #
#                       r####   c#    ####   ##              ##      fa         b # a   ##   #    ## ##  ##      ##  f   #
# l  f                b  ####    #    ####    ##   ######### ##  # ##             #     #       # ##  # ###    # ## #  ###
#  ##  ###### # l##     t #   b         #     #    ##   ## ###  ####         ##   #       rl    #### ## #   ##r#    #  ###
#  ##b ######                        t             ##   ##    r #   f    l # ##   ###           #    #  #   ##      ##  ##
#  ##             g   #         g       l  ##    ###            #  ###     #       ####   ##    ##   #  #l ###      ##  ##
#  ##                 ##     ##     ##    f##   ##    ##                      ######t#    ## f  ##   ####  #       ### ###
#        ####    ###  ###    ##     ##    ###   ##    ## ###        ####     ## ##r             #    ####        # #   ###
#     t  ####         ####l        a     ##     ##    #  ##   ####  #### ##   #         ##          ##  t     #### #ff ###
#l       ####           ##      f        ####   ##  #######   ####  #    ##   #     ## t    #        # ###########    ## #
## l     ####   #             ##   ##      #     #     ##     #    ##     #   ##    ##     ###   ##    #### ##   t af  # #
##       ####   ###           ##r  ##      #  #####         ####l  #b    r  ###   ####   # #    ##     #           ##  # #
##  ##   ####   ###      l          f      ####       ##           ##      l####       #####    ##   ###  ###  ##        #
##  ##   ####             #        r    #  #### ####  ##  ###f #####  f   ###          ##t ###  ##   ##   ###  ###  f    #
##  ##   ####   g    f   ####      r  ####      ## l                            ##     ##l    g       ##             t  ##
##  ##   ####   b     #  ######     ###### #             #####      ##  ##     ###               ### ###   ####b  t  #####
# tb     ####  ##          #### l#  ####   ##         #######     # ##   ###   # #    ##      #  ##r # #  ##  ###   t    #
#                       t ####g ##  ## ##        ###    #   ##   ####    # #####   #      ##  #  ## ## r  r#    ### ##   #
# # # # # # # # # # # # # ##         #  ###  ##   ##             #       #    #   f#      ##  # b # ##     #    # ###    #
##########################    ##    ##       ##l  ###     ##    ###  ###     t    ##b# a   #t t   #             #      l #
##########################  ###    ##   #t  ##   #   #              ######b   ###    #                ##          l     ##
## #t# # # # # # # # # # #   #      # ###    ##     t####################     ###    #      f      t ####     r         ##
#                t        # g         # ##    ## b   ###################      ##     #    f         ######t             ##
#                     f   # ##   #      #      #######      ############  #####  # b r     l   ##   ######   ##       t  #
#                 r      g  #    #      ##      ######       ############ #####  #### t       ####  ######  ####  t      #
#    a                     ##      ##   ##     r #####        #      #######     #### g ##    ####  ######  ####   a##   #
#      f          t         ## #   ##bb           #    t        r# b b#   ##     ####  ####    ##    ####g   ##    ####  #
## # # # # # # # # # # #g#######    l  A  #       #   ##         ####   b ##     ####f #####  l                   #####  #
################## #######    ## a     # ##       #    ##  g #   b###     ###########  #####             r  t     #####  #
################## ######### ##  ## b  ####       #  #  ##  ##     ##     ###########   ###      ####    ####      ###   #
# # # # # # #f# #   #g# #    # g ##    ##      b  #  ##  ##  #c     #   #   # f                 ######l ######l          #
#                  f        r   ##  # ##          #t  ##  ##g          t##         r          b ######  ######       b   #
#                         ##     # b# #           #    ##  ##  ##   g   ### lg  #####  ######    #### r  ####    ######  #
#                     l       ## #  ####  b###########  ##  ##  ##         g#####     ########            f     ######## #
#     g           f       t         b  #         g   ##  #   ##  ##   r     #####     #########                ######### #
#       g                         #        # r #t     ##      #   #    r    ###        ########     r   f      ########  #
#                         ## ##   ## ##    ##  ### r   #   #########   a    ###  ####   ######                  ######   #
#      r                  ## #    ## ## r   ##  ##     t   t#        ########   ##             ga t###  ###       r   c  #
#                      b     ##    ###    #  ##  #       ####       ##c ###     #                 ##########             #
#                         ####          a###  ##      ##  ###    r      ###br   #  t   ######    ############    ######  #
#     r       f   A         #        t#######  ##     ##g  ##       #   ###     #     ########   ############   ######## #
#                     r   # ##      ### # # ##  # r#####    #       #   ###    ##    #########   ############   ##########
#     g             l     ###ra c    #    #  ##lc  #####         ######   #    t#    ########     ##########     #########
#    t                     ##l      ## ##     ##   ##### t  r     #####   ####     #########                      ########
#                r    f   ###        #    #    ## g#               ####  a####  a  ########    tg                  #######
#tt                      g# ##      ### # # g   #            b #   ####a  ##       c  ####     ###g   b     ###     ####l#
#                        f#       c   #####      ##  #######   ##  ##  tlg##g #####  t        #####   ##   #####         #
# # # # # # # # # # # # #  ###           ## r     #  #######   #   ##     ##   ####           ######  ##  ######         #
##########################   ##    ###    # a ########   lg    #   ##     ##    ###       l    #####      #####      g   #
############################ #   r## ##   # a ########     t#  ##  ##  #####     ##b  ####      ###        ###      #### #
## # # # # # # # # # # # ### ##   ## ##      #########      ##  ##     #####      #  ######           l      b     #######
#                         g       #         ##########       ##  ##   ######  #     #######              t         #######
#                             f    l   #   ##  a  #    ##  g      #  ##    g ##    b#######     ##r         ##     #######
#      g                      ## #  ####  t#            ##     #######        #     #######    ####        ####    #######
#         A               ##  f  # g# #             ###  ##    ######      ##  b t  ######     #####      #####     ######
#                       r       ##  # ##  f          ##   #    ######       ##      #####a     ######  g ######      #####
## # # # # # # # # # # #     #   ##    ##        #   ##   ##   #             #  r   ####       #######  ####### r     ####
############################ ## l##    ####      ##  ##    #r  #     t#################         ######  ######   t    t###
#########################  #  ##     l # ######  ###  a #####  ##      ################        b######  ######         ###
# # # # #l# # # # # # # # ######          #####    ##    #   f #  #     #   #####    ###       #######  #######r    l ####
#                       b   ## #   ## l       b     #   tt     #  ##   l    #####    ####      ######  g ######t     #####
#          #####  ######## ##     f##   ##  #  # #####    #    ##  ##    ######l   #######    r#####      #####     ######
#         g#####            #    #t   f ##  ####  #    ####     # g   ##  ####  g   #######    ####f       ####    #######
###  ####  #####        l # ##   #      #    ###  #   ##  #         b##   ####  ###  ######     ##          ##     #######
###  ####                 #    a      # ##    ##  #r ###  ######b ##### r ####   ##  ######A                       #######
###  ####             r      # b    # ###     t#  ## g##  ######   ####   #####  g#  ######f              f   c    #######
#           l  l            ###  b ## A #f      r  #   #       #   ##     #   ##      ####f t f ###        ###      #### #
#                        b    ##    ##t      #  #####         ######      #    ##   #     t    #####      #####  g       #
####   g    a             ##         #  ### ###  #####               ###  #     ##           r######  ##  ######         #
####                      #### g##  ## ##  #####  #####  t  ##     b ###  #      ## b        l#####   ##   #####         #
####                       r        #     #######  #   b     ##      #######   g  ### ####   g ###   r      ###     #### #
#### t   ###                  ## ##   ## ##  #  ##   t #####  ##     #  #####   t #########                 f      #######
####     ###           ###    ####    ##    ##   ## al r####   ##    #   #####  r #  #######b                 gb  ########
####     ###           ###      ##    #    ##    ###     #      ##   ###  ###     #  ########     ##########     #########
#### a                   l       ##   ##   #     #########       ##  ###   #  #####  #########   ############   ##########
####  bg        r          r## # #   ##      #   #########        #  ###       ####   ########   ############   ######## #
#### A###################b     # ##  b g    ##   #  l#a    #########       a# g #  t   ######    ############    ######  #
####  ################### ##  ##  ##   ##  ##  f #         ##########    #####     ##            r##########             #
####  ################### ##  a# ####  #   #    ##      ##############    #####tb   #g          f  ###  ###      f       #
####  ################### #     a#  #atg   g     #       ####  ######      #    ###     ######                  ######   #
####  ################### ##       ## #            #####  ###   #####            ##   f########   f        tb b########  #
#l    ################### #        ## #   #     #  #####  ####   #       at    a  ### #########                ######### #
#     ################### ## a        ##       ##  #      #           #### t       ## ########          A       ######## #
#  b                    f ##          ##  r    #   #     ##       l   ####          #  ######    ####    ####    ######  #
##        b  r            #        ## #   # r  #   ##    #       #########    tb        t       ######  ######    g      #
##          #######       ##       ## #        #    #    #     ###    #####    #####            ######  ######           #
##          #######  ######      #  #      ################  ###       #####   #####    ###      ####  f #### b b  ###  b#
##   ####   #######  #######   # ####  #     #        #b     ##    ###     t ###       #####                   c  #####  #
##   ####   #######  #######  ##  ##   ##   ##    b   #     ###    ###  ## g ###    #  #####    r                 #####  #
##          #######            ####        ##  #### ###     #  g####     ##  ### a     ####    ##    ####    ##f   ####  #
##  l                       ## # #   ##    #   #### a #     #   ####     ###   ###      ##    ####  ######  ####    ##   #
##                       r   r   ##   ##       ####   ##    #   #####    ##   l###            ####  ######  ####         #
#       ###########         l   ##    #      # ####    ##  g##           #    #######          ##   ######   ##  b       #
#   g   ###########           ####    ##    ##     a    ##   #        ######   #######     r     t  ######              ##
# ####  ###########           ## ##   ## ## ##     b   g####          ######    ######g              ####            t  ##
# ####  ###########  ####           #    ## ##   t t   #####  ###########        #####                ##    t    t      ##
##########################################################################################################################
