metadata:
  gen_time: 9.89945101737976
  timestamp: '2025-04-18T22:50:21.240667'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  ##                                                  #  #       t t     #####      t   #####           # #            ##
#  ## ####f ### ####### ##b## l       ##              ###   ## #            ####        ####          #    #  ######   ###
#   tlf           b          #### #####     b l        ##   ####    #        ###        ###        #  #         ##      ##
#  ####### ###     ##        #### ####    # #  t # #          ##  ####    b   ##       ###        ##     #     ######  ###
#f ####### ###     ##      t #### ####    #  #  #  #     # #        ##        ## ##  #####        ##      l    ######   ##
##       c c    cb ##        ## b ####    #        #    ######  ##  ###        # ########        ####  # #        ##   ###
#######  #  ###### ####  ######   ###     #        #    #   #   #   #####     c  ######        #####         #   ####   ##
#######   # ###### ####    ####   ### #   #   ##   #   #       ##    ######        ##        ######        #r    #### ####
#      #    ######   l         ###### ##  b           ## ##     ##     ######fg            ######   # #            #######
###             ##              #####f                   #               ######          ######           #  # #  ###### #
### ###                 A              #              #  ##  ###          #######      #######                           #
###l##                           f  c ### #        # #####    ####   ##   ########    ########  t##  ## # # # t t ####   #
###    ##   ####  f##      g###     a  #  #       g#  # ##   ## #   b     #######      #######                     ##    #
###   l## ra####   ##       ### #### #    #        #     #  ##           ######          ######         #g    # #A####   #
#  ######   ####            ### #### #    #  ####  #                   ######              ######      g   #       ##   ##
#  ###### ##    ############    ####              g        ##    #   ######        ##        ######        #t #   ####   #
## ###### ##    ############    ###     ###        ###g          #  #####        ######        #####   b  f    f  ####   #
## ## f   ##### ######      ### ##  ##                  ####   t    ###     a  ##########       c### #  #   l f # ##     #
#  ##     ##### ######  l   ### ##  ##         l        # ##       ###        #####  #####        ## #     # #  # ##### ##
## ##           ######      ###c       b#####    #####     # #     b##    l   ###      ###        ##   f      g   ########
## ##     ##    ###### ## #####   #                        # ## ##  #       r###        ###        #            #    #####
##        ##        ## ## ########  ##      #    #      ## ###  #           #### t      ####        ## # # t g      ###  #
## ###b###  ## ###  ## ## ########  ##  #    #  #    #   ###            l #####          #####               l   #   ### #
##c###A###  ## ###  ## ## ####    #### ###       b  ###  ##  ####          #### ######  t                  ##         ## #
##       t #      ##   ## ####    ####  #            #  ##   ## #           ###   ###   l    ###########   ##   ##    ## #
##         #      ## b ##     ### ####                  #b       t##   b    ##     ##    r   ## ########   ##   ##    ## #
##   f  f         ##          ### #### g                ##        #         ##     ##    r                 ##   ##       #
## ##### # #### ##  ####### ##    ####                  ### ## # ##        ### t   ###               b          ##     t #
## ##### # # ## ##   ###### ##    ####b #            #      #  # ##      l ###     ###    g              f      ##       #
#               ####                   ###          ###    ##             t##       ##    r b   b               ##  c    #
###### #   #### ####  ## l  ######      #   # ## #   #        #            ##       ## t       g b        ### g ##       #
###### # g #### ####  ### ######## ###      #    #         #######         ##       ##                b   ###   ##       #
#      # f ####     #  ## ######## ######   #    #   ###   g #  ##         ###     ###       #########    ###  r##     ###
## ll  #   ####     ## ## ######   ##       #    #             ##          ###  l  ###t  b   #########    ###    #     ###
##                  ## ## ######   ## #     #    #     #    f#####      b #####   #####   b                     ##   #####
#### ###   ###### ##      ######   ## #     #    #     # ##  #   #        #############   l        f            ##   #####
#######    ###### ##    b ###### ##t #      #    #           ##     r    ###############               ###    ####   #####
#    f         cr  f## ## ###### ##  #####  #    #  ####     ####  #   r ###############         ### r ###    ####   #####
#  ####             ## ## ###### ##  #              gg    A  # #         ###############     ##  ###   ###    ####r      #
#   ###         fb  ##              c           b                 #l     ###############     ##        ###  c         c  #
###        ### ##   ##   ### ###########   #      #   ###     ## g#      ###############     #                           #
###  f      ####### ##   ##############     #    #     ####   #          ###############     ##   rr           t         #
### #### ##                                              ##  ##   ##  f   #############      ##               #######    #
### #### ##lr##r## ###   ###   c  ## f    #  b     #      bg##    #       #####   #####      ##  r        r   #######    #
### #### ##  ##f## ###   ###     l##       #      #     ######  #          ###     ###       #######       ##########    #
#   ####    #     g g    ### ## ######                  ## #    #          ###     ###       #######      b##########    #
### ####   ##  ll   ##   ### ## #######              b ##    ##   #        ##       ##    l  #######f  ##############    #
### ####            ## ##    ##  ##    #    #    #    # # ## ##   ##    r  ##       ##                 ##############    #
### b   #####       ## ##    ##   #  #    t  #  #       ###      ##        ##       ##                 #####   f      g  #
###     #####      l    l    ##f ## ####              ##        ###        ###f    ###    f        f   #####      r      #
#   ### #####  a    #####    ## ### ##                           l         ###     ###    g   ##  f    #####          ####
#b #### #####       ##### ## ## ### ## #              #     ##   ##l        ##   l ##   f     ##  ##########   b      ####
###  ##             ##### ## ## ### ###           g    # #   ##             ##   l ##   r         ##########          ####
###  ##    #### ### ##   g## c      ##     #      #     #### #   #          ### t ###                                    #
###  ##b   #### ### ##              ###     #    #     ##  ### ###         #### # ####                                   #
#                   t ##    ## # #  # # # #  # # ##    ##            fc    #         ##    ##             ##    ##       #
# ##  ###             ##### ## ####         #### ## #####             ###  ##        #   f######### #########    #       #
####    #   ## #a         #       #      l  #       #          # ##   #    ###       #            ###      r#    #       #
##   #       #### ###       f r  f  #     #               ### #### f     #   #       #    #r b     #        #    #       #
## ### ##    ##   ##      # ## c    ### ###      # ##      ##   ##   f## ### #       ######      #####      ######       #
#  #   ###        #   r  g# t#     ## ### ##     #  #       #        ###   # l      r##  ##  ## ##   ## ##  ##  ##       #
#  ## ## ## #l ##    #    #####     # # # #     #####    #    ##  # ## ## ##         ##   ####           ####   ##       #
#   #       #f ####  ##       #    ##     ##    #       ##  ####  #     f #   ####   #     c                 t   #   ### #
# # #   #####  # # l      #     ##  ### ###  ##     #      l # #  #####   # #  ###   #           f  g            #   ### #
# # ##    ##        ###  #####  #          f  #  ## ##  ###        ##    ## # ##     #                           #     ###
###  #     ##        ##     ##    bc## # ##      ##  #  ##        ##     #  ###      #          b ###            # l    ##
##  ## ### #        ##   # ##          #          ## #   ##c     c # ### ##  #       ##           ###           ##       #
##  ## ##           #    ####f## c l  f#       ## ####    #           ## ##  #   ## ###           ###           ## ### t #
### #   ###    l               #    ##   ##    #  g                 ###   # ##   ##   ##  t       # #    r     ##   ##   #
#         ##t       ###    # # #     #####     # ###b b ###        ##            #     ##t        # #         ##     #   #
# ##    ####     #    ## ### # #       #       ### ### ##f   #     ####    ## b  #     ##                     ##   g #   #
#g  rr    ##        ###    ### #     #####     # # #    ###     c  ##           ##     #    ###   # #   ###    #     ##  #
### #  f###                f   #    ##   ##    #                    ###   # #####      #    ##### # # #####    #      ####
##  ## ##           #    ####f##       #       ##c####    # r         ## ##  #         ##   ## #### #### ##   ##         #
##  ## ### #        ##     ##          #A    f A  ##     ##        # ### ##  #     t    #####  ###   ###  #####          #
###  #     ##c       ##  #  ##      ## # ##      ##c #  ##        ##     #  ##        ####                   ####    a   #
#   ##    ##        ### c#####  #             #  #####  ###        ##    ##   #       ##              b        ##     b ##
### #   #####c #c#        #     ##  ### ###  ##     #        # #  #####   # ###########                        t##########
#   #      c#  #### t##       #    ##     ##    #     c ##  ####  #       #  r    ##           t                   ##    #
#  ##t## ## #  ##    #   f#####     # # # #     ##### c  #    ##  # ## ## ##   l              r                          #
#  #   ###        #          #   f ## ### ##l    #l #       #        ###   #                              t             l#
## ### ##    ##   ##      ####      ### ###    c ## #      ##   ##    ## ### #                       t      b     r b    #
##   #       #### ###               #r    #l    c    l    ### ####       #   #            ##     l         ##     b      #
####    #   ##f#   rb     #  b  g #    t    #     f #          # ##   #    ###t           ##      r        ##   r        #
# ##r ###             ##### ## ####c  f     #### ## #####             ###c ##             ##r              ##f          ##
#  #            t     ##    ## #    # # # #  # # ##    ##f  c              #  ####      ###      #####      ###      #####
#           ##  #               b               #  ##    t               ######       A ###         #####   #######   l  #
#    #                a   ##   f     ##                    #            ########  g           ###   ##### r#########     #
#  ####           a r  a#####       #####                b####         #########gl     g   t #####   ###   ##########    #
#  ####                 #####       #####                 ####    ##   #########      g      #####         ###########   #
# r #         r ##     c ##           ##       ## r         #    ####   ######## g  ##        ###f          ###########  #
#        ##   #####                       t   #####   ##  a     #####    ######    ####              ###     ########### #
#b     #####  #####          ##   ##          #####  #####      ####      f     f ######            #####  l  ############
#      #####   ##      f   ##### #####        a ##   #####  f   ###    b        f #######           #####      ###########
#       ##  r     t  ##    ####   ####    ##           ##       ##                 ######            ###g    rg ##########
#                  ######   #r l    #   ######            a     #f            l     #### r           b g         #########
###c  f        ##  ######               ######  ##            ##      t     r  c                  b            f         #
#####       r  ##   #  #        #  l  a  #  #   ##          ####                                                     l   #
#####                 t       #####                 f       ##############################################################
# ##    b   # a        l      #####                 #        ## ##########################################################
#         ####  ##      ## b   ###     ##      ##  ####         ##########################################################
#       f ####  ##    ######        f######  r ##  ####                                                               g  #
##f  ##    ##       ########   bg    ########    r  ##    ##   #           l   b                       b          b  b   #
##   ## b  ##       ########      c  ########       ##    ##   ##b           ######   f  #####     r          ##     ##  #
#         #### r##    ######ra  r    ###### l  ##  ####         ##f  f      ########    #######          f   ####r  #### #
#  c  lt  ####  ##      ##     ###     ##      ##  ####         ###   ##    ########A  #########   t         #####  #### #
# ##        #f                #####    t            #     f  ## ###  ####    ######   ###########     f      #####   ##b #
#####     t  t          a l   #####                         #######  #####          rb###########   ##        ###        #
#####          ##   #  #  f   b #    b   #  #   ##       r  #######  #####      g     ###########  ####                  #
###            ##  ######               ######  ##            #####  #####      ###    ##########  ####        bl  ##   ##
#                  ######   #       #   ######                  ##  A #### l   #####    ########    ##  f ####l   ####f ##
#       ##  a        ##    ####   #### l  ##     b     ##       #      ## br c ######    ######          ######   ####   #
#      #####   ## a t a    ##### #####          ##   #####                  t   #####                    ######    ##    #
#   b  #####  #####      l   ##   ##  a       #####  #####                 ##    ###      lt g     ##    #####           #
#aa      ##   #####            b            f #####   ##          #####   ####  f f  r    ####    ####  f ###            #
#   #        rr ##       ##           ##       ##           # t  #######  #####    b     ###### r #####   fb  b          #
#  ####t   b           a#####      t#####            f    ####  ########  ######        #######   ######         ####    #
#  ####    A  t         #####l      #####     b           ####  ########  ######   ##   #######   ######   ##   ######   #
#    #                    ##         ##      f           fa#    ########   ####   ####  ######    ######  #### b#######  #
#           ##  #   a     g                     #  ## bt        ########          ####r #####      ####t  ####  #######  #
##########################################################################################################################
