metadata:
  gen_time: 5.489146947860718
  timestamp: '2025-04-18T22:54:46.348121'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#               b        ### t   l###             t          ###   ##         ##    ##   ###      ##  l         #####    #
#   g      ##  ##     l ####      ####       ##  ##          ####   l    ##              ##      ####             ##     #
#      t  ########  ##  ###        ###  ##  ########          ###       ####            ###t    t####g     ##            #
#    #     ######   ##   ##        ##  g##   ######     #     ##   ##   #### b  t##   ######      ##      ####           #
#  ####      ##         f                   f  ##      #### l b    ##    ##      ##   #######           ######  ##     ###
#  ####           l          ####                      ####g                           ######     b  t  ####    ##   #####
#   #            l##         ####         ##   b         #  l#               ##    b   l ##             f##   r   r  #####
#             ##  ##   ##      f     ##   ##  ##             #   c  ##    b  ##               r##                     ####
##       ##   ## f     ###l         ###       ##   ##l      #     ######    ####      rb     #####   ##  t     ##       ##
##       ##           ###   ##  ##   ###  b        ##       #   ########   #######  f   ##   #####  t##  ##  ##### b     #
#                 #   ###   ##  ##   ###   #                    #######    #########  #####   ##         ##  #####  ##   #
#               ####   #              #   ####     b     t       ## r##     ##  ###########                   ##t   ##   #
#  ##A  r##     ####                      ####     ##f   ##               r       ########                              ##
# ####  ####     ##                    l  t##     ####  ####                        ##  ##   ##   b##    ##             ##
# ####  ####  A  ##      #        f #      ##     ####  ####      ##     ##  ##              ##   ###  f ##  ##        ###
#  #     l#     ####  l####        ####   ####    g# l    # b   #####  #########               t #####       ##       ####
#                ##    ####    t   ####    ##                  ######  #########   ## b        b ######            b######
#     ##         b      ##    ##b   ##                ## ff   #####     ##  ##     ##       ##     ######           #### #
#   #####    ##                                ##b   #####    ####                       b ####      #####     ##    ### #
#   #####  ######                            ######  #####     ##         t            ##  ####        ####  ##### Al##  #
#f   ##    ####### f    ## r        ##      ####### t  ##              ##    ##      t ##   ##       r  ##########       #
#        l  #  ##       ##          ##       ##  #                  b #####  ##    ##             b##    ########        #
#                         l ##f ## g                          ##      #####        ##       t      ##      ##  ##   t##  #
#  ##               ##      ##  ##      ##          b    ##  ####       ##     b     t   ##  ## t                    ##  #
# ####         ##  ####                ####  ## l g     #### ######       r  ##        ########                          #
# ####         ##   ##                  ##   ##         ####   ######        ##   ##   #########        b          A     #
#  ##    #          ##        ##        ##          #    ##    r ######  ##       ### A ##  ######  ##               ##  #
#       ####                  ##g                 ####             ####  ##      ####         ##########  ##       ##### #
#  t    ####              ##      ##              ####              ##      A  #####            ##############     ##### #
#  ##   b##   l         l ##      ##    l          ##    ##  ## g             t####   b  ##      b##  ##########  #####t #
# ####   ## b                      r  l     g      ##   #### ###       g        ##       ##             ##  ##########   #
#  ##   ####   ##             t     g        ##   ####   ##  ###     ##  g ##   ##                    b       ######    b#
#       ####   ##             ##             ##   ####       ####    ####  ##       t          ##  ##           ##       #
#         #                 ######                 #         ####   #####  rl          ##    ########     ##          t  #
#   ##        g  l  ##      ######      ##              ##   ##    #####     t        b###r  #########  ######           #
##  ##      l     #####      ####      #####            ##  #      ###        ##  ##  ####    ##  ##############  ##l ## #
##      ##        #####      ####      #####        ##      # t   ###       ###############         ######  ##############
#     A ##  g##    ##             l      ##    ##   ##       #b   ###     ##################     t    ##  b   ############
#           ###          ##  b    t##          ###           #   #####    ####  ##  ##  ######                  ##  ##  ##
##       g   ###       #####  ##  #####       ###           #    ######    ##f      r    #####                           #
#                           ###                 g    ###        ###################    l      ##########   #######  ######
#                           ###                      ###     #  ###################b          ##########   #######      b#
#  #############  #################################  ###     #  ###################           ##########                 #
#  #############  #################################  ###     #  ###################  #####    ##########                 #
# b#############  #################################  ###     #  ###################  #####    ##########  ########g    ###
#     g ###       ### g     ###                 ###        t #                tl              ##########  ########  r  ###
#  l    ###  t    ###       ###           t     ###          #  g                           b ##########  ########     ###
################  ########  ### g##################  #########    ######################                               ###
################  ########  ###  ##################  #########    ######################              l            g   ###
################  ########  ###  ##################  #########    ######################   ######      r   ##########  ###
#            ###        t             ###       ###          # r  ######################   ######    ###   ##########  ###
#            ###             g        ###       ###               ######################lg ######    ###   ##########  ###
#  ###  ##################  ###  ########  ########  ########             gg   g      r    ######          ##########    #
#  ###  ##################  ###  ########  ########  ########      rf   tr        g       r######           g            #
#t ###  ##################  ###  ########  ########  ########c               tc      r     ######                   t    #
#  ###            ###  ###  ###  ###         tt        g     ###              g         t     c    ###     #####         #
#  ###            ###  ###  ###  ###                         ###                                   ###     #####         #
######  #############  ########  ########  ###  ########     ###   #############c ############     ###     #####  ########
######  #############  ########  ########  ###  ########     ###   #############  ############   c ###     #####  ########
######  #############  ########  ########  ###  ########     ###   #############            c              #####  ########
#  ###            ###            f  g      ###       ###r    ###   #############          g  g                    ########
#  ###   t  a     ###                      ###       ###     ###   #############        l   #######               ########
#  ###  ###  #############  ###  ########  ########  ###########c  #############      ###   #######     ########         #
#  ###  ###  #############  ###  ########  ########  ###########r f#############      ###   #######     ########gb       #
#  ###  ###  #############  ###  ########  ########  ########   rr #############      ###   #######  f  ########  ##     #
#       ###  ###       ###  ###  ###b ###       ###      g       b #############      ###   #######   g ########  ##     #
#       ###  ###       ###  ###  ###  ###       ###          ###   #############      ###   #######  c  ########  ##     #
#  ###  ########  ###l #############  ###  #####################                            r   r     l   f       ##  r  #
#  ###  ########  ###  #############  ###  #####################                     c g                      g   ## g   #
#  ###  ########  ###  #############  ###  ##################  r    ##    ##   #######  #########   ########  r   ##     #
#  ###            ###  ###  ###            ###l   r             g   ##    ##   #######  #########g  ########      ##  ####
#  ###            ###  ###  ###            ###                                 #######  #########   ########      ##  ####
######  #############  ### l#############  ###  ############# t l              #######  ######### c ########      ## r####
######  #############  ###  #############  ###  ##########################     #######  #########                 ## f   #
######  #############  ###  #############  ###  ##########################     #######f #########           g     ## g l #
#  gt     l    t  ###                              g  g                        #######t #########  ###      r     ##     #
#           f     ### g   r          r      g                             gc   #######  #########  ###                   #
#           g     ###              f                         ##  l   c   f     #######  #########  ###r  #####           #
#                 ###              A         g           g   ##      #######   #######  #########c       #####  ##       #
#   l             ###     f                                  ##      ####### c #######  #########               ##       #
# #                     #  # # # # # ### # ## # ###b### # # #  g    ## ### ###  #    f      r      # # #### ### ##       #
# # ## ## # # #### ## # ## #     #   #        # #t                t           #  ##  g   t         ##  #                 #
### ## ## # # #### ## # ## # # # # ### #a# #### # # # # # ###          r   g  ### #                # ###                 #
#                         l       l      b      # #     # #                     #                    #                b  #
########### ########### #### ### ##### # ######## ### # # # #                   #        #  #        #                   #
########### ########### #        #a    #                t          f            #        #  #g   l   #                   #
#                       # ###### #  ## # # ### ## # # # # ####          #### ## # ##g             ## # ## ####          ##
## ## ## ###### #### #### ###### # ### # # #      #l    #    #          #  #               l              #  #           #
## ##a## #b   #      #            b    # # # # #### ### # # #           #  #       f       f              #  #         r #
#        # ## # # ## # ########### # # #        b            #             ### ## ##              ## ## ###        r    ##
## ##### # ## # #                    # # ### # # ###### ### ##               #      b       r          r#            g  ##
## #       ## # # #### # ### ## #### # # ### # # #      #          ## ##     #                    r     #     ##f##      #
##g# ##### ## # # #    # #   ## #         r      # #### # # #          g    b#     ###          ###    l#    a           #
## # #            # ## # # # ## # ## ###   # ### # #### # # ##              r###   #              #   ###               ##
## # # ######a# # # ## # # # ## # ## ### # #            t        g       f     #   #              #   # f          gr    #
##                  ## #   #b##      b   #a#######g###### ###### ###           ### ###    g     ### ###           ### ####
## # ######## # # # ## # #   ## ######## #       #        #    #  #                fr#          #g                 #     #
#  #            #b     # # #r## ######## #### ## #g# #### # ## ### #### # ###  f     ###      ###        ### ###### ### ##
#  ########## # # # ## # # #b                b## # #    b    ##  #   ## l #                    r           #   ##   #   ##
#           # # # # ## # # # ###### ######### ## # # # #### ## # # ###### # ####    g                 #### # ###### # # ##
#           #         bb # # #       t                 #       #        #  ###                    b     ###  #        #  #
#   ######  ### # # #### # # # ############ # #### ### # #######b###    ### ####  ### ### ## ### ###  #### ###    ### ####
#   ######    #              l   f     a       f                   c      #    #  #   #        #b  #  #    #             #
#             # ### # #### # # # ##### ## # # # ######## # ##           # ###  #### ### ###### ### ####  ### #           #
#   b         # #            # # ##### ## # # # ######## # ##        #  #   #         g                  #   #  #      r #
#        b    # # # ###### # #         a                             #  # f #            f               #   #  #        #
############### # # ###### # ### #a###### ### # # ### ## #### b        r### ### #####  g         ##### ### ###           #
#               # #            #        #     #       ##                  #   #  b  #            #     #   #         rf  #
## ## ###b####### ##### #### # ### # ## #####l### # # ## # ## l           ### #     ###        ###     # ###l            #
#  ## b #             b          #                #                # #      #         #        #         #      # #f     #
## ## # #### ######## # # ## # # # #### ######### ### #### #       # #      #         #        #     g   #   g  # #      #
#          #            # ## # # # #                #          #  A  b   ####         #        #b        ####      r  #  #
## ## #### # ## ####### #    # # #g# ## #### #### # # # ####   #         #            #    t   #            # r     t #  #
#        # # ## ####### #### # # # # ## #### #### # # #        l     #   #  f                            b  #  r#        #
## ##### #                                      A   # # # ######  c  #   #b           #        #            #   #b    ## #
#      # ### ###### ######## ### # ####### # # #### # # #     #    f            ###   #        #   ###     l           # #
####   #     #    # ######## #r  # #######b# #          # # ## ### ###   #      #     #        #f    #      #   ### ##  ##
##     ####### t  #          # # #           # ## # # # # # #     #      #      # ### #   g  g # ### #      # l    #     #
##                ## #### #### # # # # ##### # ##   # # #        ### #####        #               f#        ##### ### g  #
##                 g    #      #     #     # # ## ### # ### #    ###     g        #           g    #              ###    #
##########################################################################################################################
