metadata:
  gen_time: 6.44094705581665
  timestamp: '2025-04-18T22:50:47.718709'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#      r         #       t     #          #  #####     #              # t   c            ## l  #########  ##### ##########
#                #             #         ##   ###     ###b       #####  a## l            ##    ##    ##  c        ##   ###
#                 #        f    #     # ###    #     ##### r      ###    ##  b        c  ## c  ##    ##           ##   ###
#      r          #            t#    g   ##                        #     ##    tl     t  ##  f ##              c  ##   ###
# l #            r #  #        #          #    #        r     l      ############## ####### ###          ########### #####
#    ##    t       #   #       #   g l   f   b ##         #####      ############## ####### ##     ################# #####
##     ##           #           # #            ###         ###        ## r ##  g       ##ba #     ##        ##     #    ##
##   r   #b         #    #         #           ## #         #              ##          ##   #     ##    l   ##     #    ##
#                    #    #                 b  #  ##                   ######### ## #####         ##       l##     #    ##
# #      #           #    #        #  #####       ###       b          ######### ## #####         ##   cl   ##t          #
##   #    ##          #  #      # #    ###        ##        g   #      ##        r                ##        ##     #    ##
#   #       ##   g       #f    #     g  #         #    #####    ##     ## r  af   b            c  ##        ##    l# t  ##
#   # f       ## l    #   #g  b#         #####          ###     ###    ########### #### #   # #####  #### ##### t### #####
##  l#    #     #      #  #   #       t   ###            #   l  ##     ########### #### #  ## ##### #####f#####  ### #####
##         #           #   #     b   #     #        #  l        #         ##  ##      r       t ##   ##t             ##  #
#     r#   #      #     #     #         g  l       ###   #             #  ##  ##      t     ##  ##   ##              ##  #
#  #    #   #      ##          # #    l    #      #####  ##            #  ##  ##      a             ##### ## ## ## # ## ##
#   ##         #     ##  l        #        ##   a        ### #####     ###### ##            ###    ###### ## ## ## # #  ##
#     #   b   #        ##         #        ###   b b     ##   ###  f   ###### ###### ####  ###   ##                     ##
#             #          ##        #       ##   #####    #     #        l##   ###### ####  ###   #              af      ##
#     # l     g#       f   #       # l#    #     ###            #####  r ##   ##   c   t           ##b######### #### # ###
##     #       #    t# f          #   #           #              ###     ## b ##           r######### ######### #### # ###
##      b       #     #    #      #   #            ##### #####    #                   l                    c##  ##   r ###
#r#  l          #           #      #b               ###   ### l          ##   ##       fc   ##  ##b   f ##  ##  ##     ###
# #              #    #     #      #           #     #     #             ##   ## rc  b      ##t #### ########## #### # ###
#                      ##    #      #l        ###     #####     t        ##   ## ###################t########## #### # ###
##          b#      #    #   # t             #####     ###  b    #####   ##   ## #################       ##     #  #   ###
# #  #      #        #  r     #  t#      l              #         ###    ##   ## c##t                 c  ##     #  #   ###
#     #     #            #    #   r##                    #####     #     ## a ##  ##l ## f      #####b#####     # r#     #
#     #      #            #    #     #     #####          ###       #################### l  r  f#####b#####     #    c ###
#      #          g g #  r     #      #     ###         t  #         ###################                 ##   b #  # l ###
#      #     # g     g      #   #     ##     #     a        #####     #      ##    bf ##        ## t c   ##     #  #   ###
#       #     #              #        ###                    ###        ##   ##       ##       c##       ##     #r #   ###
#                # #         #     #  ## # b                  #        ######### ######### #################### ## # # ###
#               #   #    #    #r  #   #  ##                            ######### ######### #################### ## # # ###
#         #         #    t#  l    #      ### #####   #        #          ##   ##   t        b  ##  ##     l  ##        ###
#       b#   l       #    #   #    #r    ##   ###    ##       ##        r##   ##            t  ##  ##        ##    c   ###
#            ##########################   ###              ####l    r  #### ####       f           ##        ##  a     ###
#           a################################              ####               ######## # # ### # ###  ##     #### ## # # #
#   f a      ################################         a    ####         g            #     g # #   #   #        # ##     #
#            ################################           g  ####   #####              # # #g# # # # # #r#        # ## #b#b#
# l       a  ########################a  ########                  #####        # ##### # # # # # # # # ###      # ## # # #
## a      f  #########      #########   ########             g  ga#####        #  r          #           #      #        #
## a         #########      #########f  ##    ## r   #####        ##### ##   t # ####### # ### # ### # #  ###rg # ## # # #
##          g  #######        f###   t  ##l   ##   a ##### g   ll #####  #     # #             b   #    r   # t # ##     #
##    r      a #######         ###      ##    ##     #####   a    ###### ## #### # ####### # # # # # ### ## # ### ## # ###
##t   a        #######      la ###   a  ##      a      ################   g t    # #   rt  #           #        r t  b   #
##    ####          ## a       ###      ##   a         ########################### # ### # # # # # # #l###### ### #### ###
##  l ####        a ##   ar f  ###    #### f    l    a ###########                             #   #     g             # #
##    ########   a a##     a   ###    #### aa          ###########      #### ## #### # # # ### # # ### ####### ## # #### #
##   t########                 ###  l ####                 l            #            #   # #         #      A            #
##      ######         g         a    ####          l             l  arl# ##### # #### ### # # # # # # ### ######## # ## #
##      ######                a     rb####    a   aa ##       #########   ##### #                  # # ### ######## # ## #
##a        ##################### a    ########    a  ##a   gr ######### #       #t# ## # # # # # ### #                  g#
########## #####################      ########       ##                t# # ### # # ## # # # # # #   # # # # ## ##### ## #
########## ##################### r    ########   f#####       a         # # # b                  # # # #t    ##       ## #
#########a #####################  a g ########    #####               a## # # # # # #### # ### ### # # # # # ## ### # ## #
#########  #####################g   ##########        a       a  r        g     # #      # #        l        r           #
#########a #####################    ##########                         ## #t# # # #### #t# # # # # ### # # # ###### ######
############################            a######## ########### a         #            #               #                   #
############################      r  ar  ######## ###########           #r# # #b#### # # ### ### # # # # ### #### # # ## #
#  a  a ####################a      a  r     a####  ##########       a  ## # #      # # # ### ### # # # #        #      g #
#       ##############   ### a      l    ##  ####  ############           # # #### # #  t            # # # # ## # # ######
#    a  ##############a  ###  f    a  a A##  ####  ############   a   l # # # #### # # # ### #b# # # # # #          t    #
#       ##############g a###     fa    t ########  #################     b  #        # # #   #         # # ###### ##### ##
#       ###########   g  ########   l    ########a   a   ###########    ### # # ## ### # # # # # ### # # # ###### ##### ##
#   ############### r    ########        ########        ###########    #       f      #             # #             tl  #
#   ###############  lf  ########        ########        #####          # # # ######## ###l# # ####### ### # #### # ### ##
#  r                 ############ a##    ############## g#####   f     ## #r       f     # #g    r                 r#   ##
#            r       ########      ##    ##############  ########         # # #g###### # # # # ## ####g### # # #### # # ##
#           r   g    ########            ###########     ########  #### # # # # ###### # # # # ## g    #     # #         #
#    ##             r  ######a  g        ###########     #####a    ####               b        ## # #### # # # # #### # ##
#a   ##     l          ######  a         ########### a  t#####         ## ### # # ###### # # # ## # #      # #      l #  #
#   g##           f  ########            ###########  a  #####   g        #   l            # # ## # # #### # # ######## ##
#    ############    ###########  g ##########################  a       # # # # ######## # #            g         b      #
#    ############    ###########a   ##########################          # # # #        l # # #### # # # #### # ### #### ##
## #############################    ########  #####################     # #t# # ##### #### # #### # #   g    # t #      ##
## #############################    ########  ##################### a   #                  #        # # # ## # # # # #####
#  #    #  #  #  #l ####  #b         ###                # ##    #    #              #####  #                     ###     #
#  # #### ## ## ##  #### ##          ###         ####   # #       #  # ###  #          # # #    f        ####### ### #####
#                                   r# g   t            #           ## ###          # #   ##         # # ####### ### #####
#  #                     ######    #           l        #t   #         ###          ##     #         ##  ####### ### #####
#  #############################          #     #    ##       t            fg       #   r  #         #   ### ###t###     #
#     ########  ##                      #       #   ###      #                ##    #      ##        #   ### ####### #####
#  #          f       #######           ######  ###  ##      #       #    a         ##   A   a g     ## f### ####### #####
#  ############################ #  #             ##   ##            ##   # #        #                # # ### ####### #####
#                                                ## g      l                        #  #               b                 #
###############################    #              #r        #  #       l  ###       ##########           ########### ### #
#                              #        #      ########     t ##       #                  #  #    l   b  ########### ### #
#                              # l      #     c######   #######               l              #           ########### ### #
### ## ## ## ## ## ## ## ## ##             ###   t        ######         #    ###    r##    ##  b ####           ### ### #
##  #  #  #  #  #  #  #  #  # l             #           ######           #    #        #     #    #r #   ####### ###b### #
##  #  #  #  # l#  #  #  #  #      #   #    ##          ######              t   t    f #     ##          ####### ### ### #
#   #  #  # ## ## ##  #  ## # #    ### #    ##          ######f                        ##    # #   f     ####### ### ### #
##  #  #  # ## ## ##  #  ## # #    #        #           b        b         #          t  #      #        A   ###b        #
##  #  #  #  #  #  #  #  #  #      ##                                                   r #      #   a   ### ########### #
### #  #  #  #  #g #f #  #  #           #  # #     #  #                    t##  # b        #      #      ### ########### #
### ## ## ## ## ## ## ## ## ##    ##### #### ##   ##                 t      ##  #   f       #      #     ###g########### #
###                        A      #           #                   #### #    ##   #a        #   t  A # #  ###             #
# #      f   f                    #           #                   #### #    ##   #         #        # # ############ #####
#          g                      ##### #### ##   ##                        ##  #           #  r   #    ############ #####
# #############################         #  # #     #  #                a    ##  #       f  #      #     ############ #####
#####  ###########        #####    ##                            A                        #      #      r### ###         #
#                    ##            #        #                     c        #           # #     t#   a    ### ### #########
#########   ##################     ### #    ##          ######                         ##    # #         ### ###t#########
#####   #   #  ###        #####    #   #    ##   c      ######              t          #     ##         t### ###t#########
#                          r               A#           ######           #    #        #     #    #  #                   #
# #######   ##################             ###     f      ######      l  #    ###     ##    ##    ####   ####### ### ### #
#  ########################  # #        #      ######   #######                    r         #           ####### ### ###f#
#             f                #        #      ########       ##b      #                  #  #           ####### ### ### #
#######   ####    f##    #####  r  #     A        #         #  # t        ###       ##########               ### ###     #
# #############################                  ##    l   t l                         #             b   ### ### ### ### #
#                       t     b # l#             ##   ##            ##   # #        # #              # # ### ### ### ### #
# #                     b               ######  ###  ##      #       #              ##   f           ##  ### ### ### ###f#
###   f   g                             #      b#   ###      #                ##    #    r ##        #   ### ###         #
### ## ## ## ## ## ## ## ## ## #          #     #    ##        b           l        # f    #         #   ####### ### ### #
#   #  #  #  #  #  #  #  #  #      #                    #    #         ###          ##    b#       t ##  ####### ### ### #
# # #  #  #  #  # l#  #  #  #        #r       t         #           ## ###          #   Ac##       f # # ####### ### ### #
# # ## ## ## ## ## ## ## ## ##       ###         ####   # #       #  # ###  #       #  # #              f###         ### #
# #           f                      ###                # ##    #    # b            #####  # bl          ###     g   ### #
##########################################################################################################################
