metadata:
  gen_time: 7.165753126144409
  timestamp: '2025-04-18T22:56:19.054215'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#t##        ##### ####        #     ##            g           ##     b   ## # #### ######t#         #########   t        #
#        #####c## ####        # #######           #  g        ## ####### ## # #    ##   # #     #######  ####        b l #
###      ##           b #    ## #######    ##    ####   ##    ## ####### ## # # ####    # #     #######  ####   ###      #
#      b ##   g     ### ###  f#  ##  #g   ####   ####  ####r  ##                     #### #    r   ####r    r   ###  b   #
####     ##t #   #f   ### ##  #            ## l   ##    ##   r## #### ####### #           #      t ####                  #
#            # ###      #     #                    gl    g    ## #### ####### #### ########b                             #
## # ###   ### ### ##b  #     #       f     b                    ##     ##   r           r #####t                        #
## ###########     ##   # ##  b  ##        ##  a             ######   f ## ########### ##  #####r        l        b      #
#  ##        tc   t       ##     ###       ##         r##    ###### # #### ##   ##         ########          f           #
#  ## ###t     ###        #     ###      l      ##   #####     ##                         #########          ##########  #
# ### ##    ####       #####    ###       fg   ####  ####   ## ## ## ############# #     ##########          ##########  #
# #   ##l   ####  b  l ##     g  #             ####   #      # ## ## #        f    # ### ####                ##########  #
###   ###  t#       l  ##c####       ##         ##           #c## ## # #### ######## ### ####                #######     #
# ##     g        ##   #  ##   A    ####        ##             ## ## # #      ##              l    l      A f#######     #
#        ## t              ##      l ###    #                # ##  # # #  c   ##          b         b       l#######     #
#g  ##  ###      ##        ##   r    ##   ####      ##     ### ## #  # ############ ## ####       g             ####   g #
#       #   #  # ## ###c ###  #     ###   ####  tf######   ##  ## ## #                             b   ##       ####     #
#     b ##  #  #  # ##  b   g #     ####   ##     #######b  ##### ##r#### ##### ###########    #####   ##       ####     #
#       ##  r       ##    #####      ##    ##  f  A#  ##                  fl                   #####   ##    f  #######  #
##   #  #   cl     c   #     # ##    t                       ######################## #######  #####  r         #######  #
###########    r  ##   # ##    ###                l                l         l       b     ##  #####          #########  #
#                 #### ####    ##                    ##      ######## ##### ## ## ###### ###########          #########  #
#####   ##           ###                 ##        b ##            lf                      #########   r      #########  #
#####  ###   ####             #        #####    ## g    r   ##### ###### ## ###    ####  ###########            #######  #
#b  A  # #      r   ########  #    ##r ####   ##### r     ###             t                #########            ##########
##       ###  b   #####   ##       ##   #     ####   ##   ########## #######  ##      ##############               #######
####      #c  ##  ##  ##  ##   #               #     ##    # #####   ######## ### # #  #################           #######
# ##       c  ##b ##      ##   ##    g                             t        f              #############   ####  bf#######
#   r ###     #  c#            ##    ##                      ###################### # #############        ####      #####
#   ###       #   #  g  ##   l ###  #####     ##  #            #################### #      ########   rr   ####      #####
#   ###       #   #     ##     ###   #####  ########  ##b   ## ##                l  # #############r                    g#
# l   ### f   #   #f t         ##      ##   ########  ##    ## ## ######### ### ##### #############      r               #
# ##          ##  ##      ##   r      b      ##  ##          # r# ########## ## ## l  r    ###############               #
####t     #   ##  ##b ##  ##                    l            # #  ##            ##         ###############        ###g   #
##       ###  l   #####   ##            ##           f ##    # #  ## #### ############## ###    ##########        ###    #
#     r# #       b  ########  #         ###     ##   #####     ## ##b#l          t  r      #    ##      #############    #
#####  ###   ####     c       # ##     ####    ####  ####g   # ##                                    t  #############    #
#####   ##l          ###       ####    ###     ####   #      # ## #### #  f         t   b f#  f ##   b  ############# b  #
#                 #### ####    ####     ##       #          f# ## #    #c###################    ##  #################    #
###########       ##   # ##     #                              ## # #### ###################  ####  ######################
##   #  #   f     f    #  c  #              ##    g      ##  ####                          #  ############################
#       ## r        ##    #####       ##   f##    l     ####                                                 #######  ####
#       ##  #g #  #r##        #  t   ####  ####    ## f ###  # #### ### ##### ###### #######  #############  #######  ####
#       #   #  # ## ###  ###  #       ##   ####  #####rg ##  # #    l                  ##  #  #############           ####
#   ##  ###  c   ##    g c ##      l         #   #####       # #         g  r          ## ##  #############r r l      ####
#     g  ##         b      ##                     ##         #b#  f               c    ## ########################       #
# ##   b          ##   #  ##   r ##g  ##        b   g      ###           r      br     ## ########################       #
###   ###   #          ## ####  ####  ## r ##   f     ##   ### #b                     f## ###############  #########  f  #
#     ##    ####       ##      t####      ####b       ##     # #             l         #    #############  #########     #
#  ## ##    ####       ####      ##   b   ####       l  r    # #### ####### ##### ###    g f#############  #########    l#
#b ## ###      ###t       # t    ##    r   ##              ##gf      bt      r             ##############g #########     #
#            g c          ## l  ####     g        ##      l###########  #######    ### ### ##############  #########     #
## ## ## #####     ##   # ##    ####            ######                                     #####  #####    #######    ## #
## #  ##   ### ### ##cb #  r b#   #      l ##   ######  g t  ## ## ###### ## ##### ########   ##  #####    #######    ## #
#  #      c  # ###c     #  t  #          #####   #  #b     #### ## ###### ## #                ##  #####    #######    ## #
#  #     ## f#   #    ### ##  #      ##t #####             #### ##     ## ## # ###### #####       #####    #######    ####
# #      ##       l ### ###   #     l##   ##              l  ##b   ##  ##    # #         r          t     r#######   b####
###      ##             # c  ####  r        t   b       #    ################# # ####### #######           #######    ####
# #    r ##### #######      t ####          g         ####                                                          ######
# ## t      ##### ####        ####    ##            r ####   ###### #### ####### # #############     ##    ###############
#       ###    r  ###         a#        ##      ##  ###            r        f                     #                      #
#       ###       ### t        #     a  ##      ##  ##          ##                                              g        #
#  ###a ########  ###b #########        ##      ##  ##       ## ## ########################  g    #                      #
# f###r ########  ###  #########        #a      #   #         # ## ############################   #   ### ################
#  ###  ########  ###  ##########      ###### ##############  #    ##f ##  ##   ##  ##   ##           c l #       # b    #
#  ###       ###  ###  ###     ##   b  ###### ##############                    g                        t#       #      #
#  ###  t    ###  ###  ###     ##  A        #              #  #    ##  ##  ##   ##  ##   ##  g            #       #      #
###########  ###  ###  ###  a  ##      #    ##             # ## ## ########################   #############   ##### f    #
###########  ###a ### a###     ##     ##r   ##             # ## ## ########################   #               #   #      #
###########  ###r ###  ###     ##     ##     #             # ##  #   ## f##       ##l  ##  r  #        f      #   #t     #
#  ###  ###  ### a             ##     #     A# f           # f  g    b          A          b  #               # c #      #
#  ###  ###  ###    a  a   b   ##    #########             # ##  #   ##  ##       ##  g##     #########   #####   #    g #
#  ###  ###  #############     ##    #########             # #####  #######################                         b    #
#  ### a###  #############     ##            # g           # #####  #######################                         t    #
#b ###  ###  ############# f   #     #       #             #  ##    #  ##  ##  ## b##     #                             r#
#      f                       #    ##       ## b       b  #                               ####   #########   #####      #
# g      at               a    #    ##       ##            #  ##   ##  ##  ##  ##  ##     #       #       #   #          #
###########  ######                          #             # ##### ########################       #       #   #          #
###########  ###### # a###     # ## ###### ################# ##### ########################       #       # g #         A#
###########  #####  #  ###        # ######  ################ #     #  ##  ##       ##  ##b    #  f#   #   #########      #
#  ###l ### ar     ##a ###  a          r          f      #      g                             #       #   #    g  #  r   #
#  ###  ###  t    ###  ###a                              ##  #r    #  ##  ##  b c  ##r ##     #       #   #       # g    #
#  ###  ##################                               ##  ##### ########################   #       #   #       #      #
#  ### t##################    a       g               t  #    #### ################################   #   #   #c  ########
#  ###  #################      # ## ##### ##  ##  ##########       ##             ##  ##     b#       #       #   #     r#
#  ab      b       a      t    #       ##  ##  ##  ##  #####  r           g       r           #    r  #       #   #      #
#                      ###          #  ##  ##  ##  ##    t         ##        g    ##  ##      #       #       #   #      #
###########  ###  ###  ###  a          ##  #   ##  ##        #####     ####################   #########   #########      #
###########  ###  ###  ###          #b ##b #  g#   #         ##### ### ####################       tt            f        #
###########  ###r ###  ###   a      #       ############      ##   # f #g ##g f ##  ##  ##                   f           #
#            ###  ###    l A        #  ##    ###############                             g                               #
#            ###  ###   a           #  ##          #      ##  ##   #r ##  ##    ##  ##  ## ####   #####   #####   ########
######  ###  ###  ###  ########     #  ##   ##     ## b  r   ##### ########################       #       #   #   c      #
######  ###  ###  ###  ########        #    ##     ##        ##### ########################       #    t  #   #          #
######  ###  ### a###a ######### ## ##########     ## bf                       f          g       #       #   #A         #
#       ###  ###  ###  ###r    # ## ####### ##     #    g        l         r               ####   #   #   #   #####      #
#       ###  ### a###  ###                  ##     #  c                 r                     #   #   #       #g         #
###########  #############          g       ##     ##        l  g          r          r b     #   #   #       #         g#
###########  #############          b       #      ##     bb                                  #   #   #      g#          #
###########  #############      b           #      #          b                  f            # g #####   #########      #
#       ###        t                        ################                     f                #           #        r #
#       ###    r    a                l      ################                                      #           #          #
######  ###  ##################             r#                           b                        #         f #          #
######  ###  ##################              ##              #######  #####################f r#   ################# l    #
######  ###  ######################  ######  ##              ######## #####################   #           #   #          #
#             a       a    at  ##### #######################  ##    #   ##g   ##  ##  ##      #           #   #          #
#a           r                a    #       b     ##  #######        c               f     b   #           #   #          #
###########  ############# b       ## g     g    ##           ##    ##  ##    ##  ##  ##   ####   #########   #####      #
###########  #############         ##    l       #  g        ##############################                   #          #
###########  ############# a   ############################################################                   #          #
#                 ###    f     ##    tt########################   ##   ##  ##   ##  ##    #                 r #          #
#          r     a###a                            #                                          r#   #   #   ################
#  #############  #############                   ##         ##   ## gr##  ##   ##  ##    #   #   #   #       #          #
#  #############  #############                   ##         ##############################   #   #   # f     #          #
#  #############  #############                   ##         ##############################   #   #   #     f #          #
#  ###       a  a     a                  rb       ###########                 b               #################   #      #
#  ###                 t        f              g  ## ########                 f          g       r                #      #
#  ###              ta  r   a                l  b ##     g          r                                             #      #
#  ### t   b f     t         a    t               ##                                         t                    #    c #
#  ###                     a          r           ##         ##############################                       #      #
##########################################################################################################################
