metadata:
  gen_time: 1.4455301761627197
  timestamp: '2025-04-18T22:58:02.910352'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#   ##  ##  #  ## l##      ##        g   b #######   ###   #######    ##      ##       a              ##  ##             #
#   ##    f t     l##      ##         b    ########  ###  #########   ##      ##                 g   g##  ##f            #
##                     #   ##             #########  ###  #########   ######  ######  ##########  ##  ##  ##########     #
##      ##     ##t     #   #######  g      ####### r ###   #######    ######  ###### b##########  ##  ##  ##########     #
###    ##### #####    ##   #######      f    t  r    ###g     g g     ##  ##  ##g         ##      ##          ##         #
####   ###########   ###                              #               ##  ##  ##          ##      ##          ##   a     #
####    #########    ###      f          ######g  l    gr     ######  ##  ##  ##  ##  ##################  ######  ##     #
#t###    #######    ###                  #######         l   #######  ##  ##  ##  ##  ##################  ######  ##     #
# ###    ### ###    ### ##########       ########     b     ########              ##  ##          ##    g ##      ##     #
# ####    ## ##    ###############       #########         #########  g           ##  ##          ##  a   ##      ##    f#
# ####             #####                 ##########       ##############  ##  ##############g ######  ######  ##  ##l    #
#  ##               ##r   l              ###########   r ###############  ##  ##############  ######  ######  ##  ##     #
#         ## ##     r                    ############ t ############      ##  ##      ##  ##      ##  ##  ## g##  ##     #
#     f  #######  A     #####l  #####################   ############      ##  ##      ##  ##      ##  ##  ##  ##  ##     #
#  ##  ###########  ##  #####   #####################   ############  ######  ######  ##  ##  ##  ##  ##  ######  ########
#  ##  ###########  ##          g      b ############  r############  ######  ######  ##  ##  ##  ##  ##  ######  ########
#    r  #### ####                    r   ############   ############  ##  ##              ##  ##  ##      ##  ##         #
#        ##   ##     ta        l         ############   ############  ##  ##         a    ##  ##  ##      ##  ##   a     #
#        ##   ##           ##########################   ############l ##  ######  ##  ######  ##########g ##  ######     #
# ##       g     A   ##g   ##########################  b############  ##  ######  ##  ######  ##########  ##  ######     #
######g            #####     g           ############  b############  ##g     ##  ##      ##f g       ##          ##     #
######    ##g##    #####   t              ###########   ###########   ##      ##  ##      ##          ##          ##     #
# ###   ######### r ###                  g #########     #########  ########  ##################  ## b######  ##  ##     #
#  ##   #########   ## f#####   ##            b        g   r        ########  ##################g ##  ######  ##  ##     #
#        ## r ##        ##### g ##         f      b t                     ##          ##  ##  ##  ##       g  ##  ##     #
#        r              b       ##         ##     ###   ###     ##g       ##   l      ##  ##  ##  ## a   t    ##  ##     #
#            f                  ##       r####   ##### #####   #### ####  ##  ##########  ##  ##  ######  ##########     #
#     ##  ## ##  ##             ##       #####   ##### #####   #########lf##  ##########  ##  ##  ######  ##########  A  #
#   #################t          ##       #####    ###   ###    #####  ##      ##       a  ##  ##  ##      ##         a   #
#r  #################           ##       ####                   ####  ##      ## a        ##  ##  ##    f ##             #
#    ##  ##   ##  ##            ##    g  ###     f   r           ###  ##  ######  ##  ##  ##  ##  ##########  ######     #
#     r               f     bl  ##       ##b   l####     ####t    ##  ##  ######  ##  ##  ##  ##  ##########  ######     #
#  t                     fl     ##       ### r t  g              ###          ##  ##  ## a g      ##     a##      ##     #
###                   ##     l  ##       ####                  l####          ##  ##  ##      a   ## f    ## t    ##     #
####     ##   ##     ###        ##       #####    ###r  ###   b#########  ##  ##  ##########  ##########  ##  ############
######  #########  #####      b ##    r  #####   ##### ##### f #########  ##  ##  ##########  ##########  ##  ############
# ##################### f       ##        ####   ##### #####   ####       ##          ##             a                   #
#   ######  #  ######        l  ##      f  ##     ###   ### A   ##       l##          ##                 g               #
#     ##  r r    ##     #####   ##     r   b  g   t    l            ####  ##############  ##########a ##  ##  ######     #
#a a    l               #####   ##    t                g            ####  ##############  ##########  ##  ##  ######     #
#  t              g                      r #########     #########            ##   a          ##      ##  ##      ##     #
#      ##       ##a   gl   g             f###########   ###########           ##              ##      ##  ##      ##     #
#      ###     ###               b       ############   ############  ############## f##  ##  ##  ######  ##########     #
###   ####  #  ####   ##   ##########################   ############  ##############  ##  ##  ##  ######  ##########     #
###   ###  f#   ###   ##   ##########################   ############              ##  ##  ##  ##      ## g     f  ##     #
##   ###         ###f  #         g       ############ fg############              ##g ##  ## a##      ##          ##     #
#    ###         ###   g                 ############   ############             g##a ##  ##  ## g r  ##    f     ##     #
#t    ###  b    ###     r                ############   ############              ##  ##  ##  ##   fg ##          ## g   #
#     ####     ####     #####   #####################b  ############  #############  ###  ###  ####  ###t #############  #
#    #####     #####f   #####l b#####################   ############  #############  ###  #### ####  ### t#############  #
#    ####       ####    c                ############   ############  #############  ### g#### ####  ###  #############  #
##    ##         ##g   #                 ###########     ########### r#############  ###  ####g####  ###  #############  #
###                   ##           f   l ##########  rf   ##########  A        l     r                                   #
###       ## ##       ############       #########        t#########           b              bb                         #
##   ## g ## ##   ##f  ###########       ########        b  ######## ################################################### #
#    ##           ## g               br  #######b   rf      b####### ################################################### #
#   ####   g     ###    g                ######  b     b l    ###### ################################################### #
##  ####    #    ####  #                   f          #  t     b     ################################################### #
##   ##   #####   ##   #   #######                   ###          t  ################################################### #
#        f#####   f t      #######         #######   ###   #######   ################################################### #
#   r      ###             ##           f #########  ###  #########  ################################################### #
#   ##     ###     ##      ##             #########  ###  #########  ################################################### #
#l  #### t       ####    b ##              #######   ###   #######   ################################################### #
#       #  #  # r         c# l   #f #      r       g                 ###################################################b#
##      #######      #     #     #A #    ########################### ################################################### #
##            #      ####  ####  #r #b t ###########################      b                           r               f  #
###     #     #     ##     #  #   r    r                                                              g                  #
#       #######     #      #  #g  f             t                     t    g        r         l                          #
# #c l        #     #   ####  #  ####  f ###########################            ## f##  g              ##  ## t          #
# #     #     #t    #      #        #    ####################################   ##  ##  ##g     g  ##  ##  ## l ##########
### ####### ##########     #    l   #           b             f     #########   ##      ##    f    ##      ##   ##########
#         ###       A   ####  #  ####                           r   #########           ##         ##           ##########
#         ###                 #  #                          r       #########       g                       l g ##########
#  ######## ########  f      f#  #   l    f                         #########       l                           ##########
####               ###  ####  ####  ##### b                bt       #########        ###     ### f   ###        ##########
##         c    b    # g#  #  #        f        r                   #########      b ###     ###     ###        ##########
#              r        #  #  #   l      ###########################                      l  ###      g     b       g    #
#                   b ###  ####  ####    ###########################            t            b                           #
# ##  ##### ##########     #  #  #f                    l                       r    ###               ###                #
#         ###     #        #  #  #         blf                    g    #####    ##  ### f##       ##  ###  ##  t #####   #
#                f#     #### r####  #   l############################  #####    ##  ###  ##       ## t###  ##    #####b ##
#      r          #                 #    ############################ g#####    ##  ###  ##       ##  ###  ##    #####  ##
#    #    b      ##                 #  f                            #  #####             ##       ##             #####  ##
#    #           #  c ######  #  #  #####      bl                l  r  #####             ##       ##     l       #####   #
#    #    t      #t       c   #  #  #    ###########################   #####   #######g  ##r      ##   #######   #####   #
#  # ###############   r      #  #  #    ############################ b#####f  #######   ##      b##   #######   #####  ##
####   #           ###  #######  ####                a   t     r   t#  #####             ##    gb ##     f       #####  ##
#      #       #        #     #  #  #   l                            f          l                                        #
#      #       #   b    #     #  #  #          t            f   r  b f      f c          g                               #
# c    #########      ###  ####  #  #    ########################### ###                g          t  f       b      ### #
#      #                            #    ########################### ###         ###########################     b   ### #
#      #       #             A      #                       f                    ###########################            g#
#      #       #        ##########  #    ###########################             ###########################             #
#   t  #########      l # g#  #     #   g####################################    ########################### gc ##########
# c    #                #  #  #     #  l        a      ll       b   #########  f ###########################   t##########
#      # gr    #    c ###  #r #  ####             l  b              #########   f###########################    ##########
####   #       #   ###              #                tr      A      #########    ###########################b   ##########
#  #################          t     #  r ###########################                  g      b             g     b   g   #
#    #           #    ###  ##########    ###########################                                     f               #
#    #  t        #          l                  b    g          t    ########################   b #########################
#   ##           ##                                                 ########################   t #########################
#   #            f#     #  ####  ####   r###########################     t                                 bl   gt      r#
#   #       f     #   b #     #  #       ###########################                                g                    #
#   #     ###     #     #     #  #             l  c r               ######  ######     ####       ####r    ######  #######
# #### #### ###################  ####                     f         ######  ######     ####  ###  ####     ######  #######
#                       #          g#    #################################r ######    g l    ###    r      ######  #######
#           t           #           #    #################################  ######  l g      ###           ######  #######
##                   #  ####  ###########     b                     ######  ######  ###     r        b###  ######  #######
## #               ###     #  #   g          l           t          ######  ######  ###     g         ###  ######  #######
#  # #### # ########       #  #                            c        ######  lf  f                             t   r#######
#         ###         ### g#  #  #  #####                 t       f ######                     l                   #######
#         ###           #        #        t        t   r        l   ######     r  #########################        #######
## # #### # # # ######b #        #   g                       r      ######        #########################        #######
#       #     #     # g ####  #######    #################################        #########################     r  #######
# #     #     #     #   #           #    #################################b             f      f        f       l  #######
# #     # ### #     #   #           #                        b                    a                                      #
###     #     #     ##  #  #  ####  #####                 l                    l             g          g         l      #
##    t # A   #      # b   #     #     f ########################### ############                 f         ############ #
## b   r# ### #      #     #     #    c  ########################### ############  l###b              ###   ############ #
#       #  #  #       l    #     #f                              r   ############   ###           r   ###   ############ #
##########################################################################################################################
