metadata:
  gen_time: 7.809579849243164
  timestamp: '2025-04-18T22:54:40.779138'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##     br          #   t   # l        g   #      g #        #          ###        #    ####   #   ##  ###      ###   #####
#  ff##                   ##       #   ## #        #        #         l         l##       # g #   ##        ## ##  f #####
#l  ####   r ##         b #  ###########  #  f    ###       #          # #           r        #   ##                     #
# l  ##     ####    ##    #  ###########  #       ###       #          # #             ########   #   ##  a##   ## bg#   #
#           ####    ##  t #  #            #        #        #                    #      g g           ##t  #   f##   #   #
#            ##         #### r        l   #        #        #               #    #          # g  #######         #   #   #
###    ##   b          ##                 # #      #b    l# #               #    ###   ######    # ### ## ########   #   #
###   ####        ##  ##     #######   ## # #      #      # # ####   # #     t r   # f    ##     #         ##   g    ##  #
####   ##  g     #### #      #######    #####      #      ######     # #  ###  g   ####   ##     #         ##        ## ##
####         ##   ##     #########       # ##      #      ##f#####        #   b    r ######     t#  ########## ###########
# ###      ####        #  ########  r   f# ##    # # #    ## #  b#        #        # ##          ####           ## g     #
# ##  f    #####      ### r#######          #    # # #    #      #              #     l        g                      #  #
#            ##   ##       l#############  c##   # # #  r##      ###      ###   #     ######## ###   ##         ##   ##  #
#       t        g##        #############   ##   # # #   ##        #     b               f  ##  ###  ##      bb ##   ##  #
#        ##              c# ##   #   ##### ###   #l# #   ### #     #    r   #####           ##    #   ################   #
#  ## b  ##   ##         l####   ##   #  # # #   # # #   #r#f# b                #    t     b##   ##           ##f     a  #
#g####        ##    ##  a #       #      # # #           # # #              #   #    #     ##    ##        r  ##        ##
# ####              ##    #   ######## f                             c      #   #           ##   ##           ##     b   #
# r##    ##           gf  #    #     ##            #               # l      #####           ##    # t ################   #
#        ###              ###         #t       r b                 #                        ##  ###  ##         ##   ##  #
#       ###   ##           ##   ######### ###        A    ###    ###      ###   #     #############  ##        b##   ##  #
#   ##  ###   ###     r    f#   ###   b ### l  ### #####    ##  t#              #                               ##    #  #
#   ##   #   ####               ###     #        t   r           # f      #       f####     l    ####           ##       #
#            ###             #  ###     ###     b     b  r  ######        #          ######         ########## ###########
#             ##         ######         # ################### ##     # #  ###     l####   ##     #         ##        ## ##
#    g              ##  ##              #   ##           ##   ####   # #           #     b##     #         ##f       ##  #
#                  ###  #           b   #             r                     #    ### A ######    # ### ## ########   # f #
#  l   A     ##     ##  # l        #######                r  #              #    #         g#    #######     b   #   #   #
#     ##   ######      ##      #####  ####        t          #                   #                                       #
#   #####  #######   l##    ##  ####   ###     b             #         # #             ########   #   ##  g##   ##   #   #
#   #####   #  ##     #  #   ##  ###    ##                   #      r  # #                  a #   ##  ##   ##  ##b  f#   #
#    ##              f  ###   ##  ##     #                   # f    f            ##       #   #   ##  #     ## ##    #####
#         f       l   g#####  ###  #                                   # #        #    ####   #   ##  ###      ###  f#####
#              ##    #  ###  ###         #     f   r         ###  # #  # ##  #  # ##   # #g    #   ##    ## ##### # #  ###
#          ##  ##  ###   ##   ##    ######                   #    # #     #  #    ##   #      ##   ##                   f#
#  ##    g ##      ####   #   g#     # r ##             g   ##   ## l##   #     # ## # ###   ###  ###      ##   ##       #
# ###               ####    ##            #                 #   ### #### ##  #  b ## # ###   ###  ###      ###   ######  #
# #### t       ##      ##    ##  ####t    ##              t## # ##       ##  A #  ##   #       #   ##  #    ###      ## ##
#  ##    ## t  ##       ## l  ##  ###  ## ##               ## #  #          #  #   #    #t    #    #   ##     #      #  ##
#       ###  l         ##    ##  ####    ###               ####  #  t          #   #  # #       # g#          #      #l ##
#        ###          ##    ##             #            l    ## ##       ##    #  ##  ##       ##  ##        ##         ##
##       ###      ##  #  l#    #     #   # #         c     # #b#### #### ##  #    ## ###    ## ######      #   ## #####  #
##        ###   ######f  ##   ##    ########       b       ### ####  ##   #    ## ## ### #   # ###### ##            ####g#
#         ###   ######  ###  ###          #r                   #  # # #   #  # #  ##   #       #   ##  ### ##   # # #  # #
#          #     #  ## #####  ###  #      #   t      l      # ##  # # ##### ##  # ##  f# #   # #   ## #  # g##### # #  # #
#   ##         r  b     ###   ##  ##     ##      #   #      ###  #### ####   ##  t  f###### ######      ##   #########   #
##    ##  ###  ##  l ##  #   ##  ###    ###      #   #      ###    f     ######    ######## ########    ######           #
##  ###         ###  ###    ##  ####   ## #      #   #      # # ###   r     ########               ## #####      c  # ####
##      f    t       # ##      #####r ### ##     #   #     ##   ###  ### ####     ###################     # #########    #
##                  l#  #        f ######  #     #   #     #  ###         #       ###################     # #   c     ####
##   ##         ##  r#  #               #  #     #   #     #  ### #         #######  ##  ## ##  ##  #######     # ### ####
#          # l a        ##             g# ## # # ## ## # # ##              ########      ## ##      ####### ##### #g     #
# # t      #       ##    ######g        # ## # # ## ## # # ##      ## g####  #g  ##     ### ###     ##   #  ####  ##     #
###  tg    #      l ##       #  ###  rb # ## # # ## ## # # ##          ##       ##       ## ##       ##  r  g ##   #     #
#    #### g#  ####            t ###     # ## # # ## ## # # ##     ##  ###       ##   b####   #### c  ##       ###  ##  t #
###### ##     ## #####    fa# g ###  l  #  # # # #   # # # #       #  f##     t ##       ## ##      f##       ##   #     #
#         ###    t  #      ##   #########  ### # #   # # ###    a  ##  ####  #l  ##f    ### ###c    ##   #  ####r ##     #
###r      ###  a    ##    ### l       #     #   b#   #    #         ########### ###      ## ##      ### ### ##### #      #
#      ## ###l## f  #     #    #     ##     #    # lr#    # r ##### ### f   ### ###  ##  #  ##  ##  ### ### r   # ### ####
# #     #######     #     #   ########  r        #r  #        ###         ###     ## ##### ####### ##     # #         ####
# ##    ##   ##  l ##     #    r  #              #   #          #############   f ## ##### ####### ##     # # ### ### #  #
#g##  f           r##     ####   ##   #  A     # #   # #      #####       f ### ####        g  r   ## # ###         # # ##
#t     ##     ##   #      # ##   #   ####  #   # #   # #   #  #  l       ## ###    # #####  # #### #    ### #   f       ##
# ###      #      ###     a #############  #   # # b # #   #  #  ## ######   ##      ##### ## ####   g  ##  l  ## ###   ##
#          l        #   l   #############  #   # #   # #   #    #        #     #     #  #a #t      t ##                # #
###     #######     #####  #######         #   ###   ###b  #    #        #t    #     #  #  #         ##l#####   ##### ## #
##   #############   # #f ########   g     #   ##     ##   #    ####  #  ####  #  ####  #  ####  ### ## #####   ##### ## #
##             #     #   #########  r          ##     ##        #  #  #  #  #     #  #         r #         ##r  ##       #
##    f##     ##     ##      #######    #      #       #        #  #  #  #  # l   #l #           #  ### ## ##   ## ## ####
##      #  #  #      ###     #######   ##      #       #      g #  ####  #  ####  #  #  #  #  ####  ### ## ##   ## ## ####
##rt g ##     ##     # ##           t          #      t#  b              #           #  #  # r#      ## ## ##   ## ## ##t#
##  #   ####### f #  #  ####       r    l  r           b                 #           #  #  #  #      ########   ######## #
#   #   # ### #   #  a    #  #               r                 r#############  ####  # f# ##  ####   ########   ######## #
#   ##  #     #  ##       #  ###########   # #           # #      g   #     #  #  #  #  #  t  #            ##   ##    t  #
###  #r #     #  # g##    #l ###########   # #        tf # #   f      #     #  #  #  #a #  c  #      ##### ##   ## ##### #
###                 ##    ## r     #   ##  # #           # #    ########## t#  #  #  #  ####  #  ### ##### ##   ## ##### #
# ##               ##      #       # t  # ####           ####            f     #  #  #     #         ##    ##   ##       #
#         # #         ###               # ##l  ga          ###                 #  #  #     #         ## ## ##   ## ## ## #
# g     ### ###              l         ##  ##        A        ##################  #  #######  ####   ## ## ##   ## ## ## #
#   #  ##     ##  #              #     ##  ##     #           b #  #  #     #r       #  #     #      ## ## ##   ## ## ## #
##  #  ##  g  ##  #  #        #        ##  ##        #A         #  #  #     #        # f#     #      ##### ##l  ## ##### #
##  #  ##  #  ##  #  #                  ####                    #  #  ####  #  ####  #  #  #  #  ### ##### ##   ## ##### #
## ##  ##     ##  ## #   l              ####                   c# t       g    #  #  #     #  #         ##         ##    #
## ##  ##     ##  ## #               #  ####  #          l      #    gg        #  #  #     #  #   r ###### ####### #######
##  #  ##  #  ##  #  #    ##        c#        #       b ##      # g##########  # g#  ####  #  #  ######### ####### #######
## l#  ##     ##  #t #            ##     ##  a  ##                t   #        #  #  #t    #  #  #   ##   b##   ##    ## #
#   #  ##     ##  #               ##    #  #    ##                    #f       #  #  #     #  #g #   ## #####   ##### ## #
#       ### ###                   r##      tg b##               #  # l#######  #  ####  #######  #   ## #####   ##### ## #
#l g      ###                     r##          ##          b    #  #  #     #       b   #    g#  #         ##l  ##       #
#  #               ##    b###     ##       b    ##     ###      #  # t#a    #           #     #  #c  ##### ##  b## ##### #
###  r              ##    ##        A                   ##      #  #  ####  #a #######  ####  #  #   ##### ##   ## ##### #
###  #  #     #  #  ##    #             ####           b #      #  #        #        #      a #  c   ## ft            ##f#
#   ##  #   t # a##                     ####          g         #  #        #        #        #      ##        l      ## #
#   #   # ### #   #             #                  #               ## #    #  t t#    # ##           a #  #              #
##  #   # #####   #  #        l     #          #      l         r ###        ###        ###            #  #              #
##   r ##     #      ##             ##        ##             # ####          ###          #### ###  ####  #############  #
##      #  #  # g    #l    f        ##        ##     l         ####          ###          ####c     #  #  #     #  g     #
##     ##     ##    a#         #   t          r     #              b  ## ##       ## ##f  l         #  #  #     #    t   #
##  g  #       #  l  #         ##            g     ## b       ##       # ##### ##### #       ##  ####  #  #  #  #  ####  #
##   #############a  #         #    b               #         ##      #######   #######      ##t       #     #     #     #
###     #######     ##       l      ##        ##l   g    b    ####    ##### #   # #####    ####        #     #     #     #
#                   # #             ##        ##            g##   b     f   r     r           #  #  #  #######  #  #######
# ###      #      ###   l           #          #                  ##f   #     g   g #    ##      #  #        #  #        #
#  #   ##    a##   #          g #                  #            ###                       ###    #  #        #  #  f     #
# ##           f   ##                   ####                                       b           ###  #  #  ####  #  #  ####
# ##    ##   ##    ##a    #      l      ####        g    #    r                                     #  #        #  #     #
# #     #######   t #f g  ##                        t   ##       b       r         g                #f # A      #  #c    #
# #    ## ### ##      l   ###     ##        b   ##     ###                        t                 #  #        #  #    r#
###  r    ### r    b##    lt       ##          ##                b  l              f           ###  #  #  ####  #  #  ####
#         ###    t  #      g       ##   a      ##               ###                       ###    #  #        #  #        #
###### ##     ## #####            ##a   #  #  b ##                ##    #           #    ##      #  #        #  #r       #
#    ####  #  ####   g          g ##     ##     ##            #                               #  #  #  #######  #  #######
###        #        ##    ##         #        #b        ##    ####    ##### # r # #####    ####        #     #     #     #
# ##       #       ##                #  ####  #      g        ##      #######   #######      ##f       #     #     #     #
#          #                            ####          b       ##     r   ##### ##### #   f   ##  ####  #  #  #  #  ####  #
##   ##        g##   #                    ##                          ## ##       ## ##             #  #  #     #        #
##                   #        #      l ##  ##        #         ####          ###   f      ####      #  #  #     #        #
## t               f #           #     ##  ##     #     a      ####         l###          #### ###  ####  #############  #
##  ###r  f r   ###  #               b ##  ##                     ###        ###        ###            #  #         a    #
##    ##  ###t ##    ####               ####            g  ###    g## #l   #     #  A # ##             #  #             t#
##########################################################################################################################
