metadata:
  gen_time: 7.906261920928955
  timestamp: '2025-04-18T22:49:12.242381'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#                       ##  #     ### #   ## ################################### #####    #######################    #####
#    ####       ####     #r  l      g     #   #################################  t###  ########################## ########
##  #    #c    #    #  # #      r##  l ## r           A##   #####   ##  c                        #       #               #
# ##      #   #      ##         ## r    #          c   ##   #####   ##        c                 g#       #               #
#          # #                  #  f##  ##            ###  ### ###  ###                          #       #               #
#           #            #           #                ###  ### ###  ###   t                                     b        #
#                       ###    #  #  l f    t   t     ## t ### ###   ##           a                   rl        r        #
#            c     b    #      #  #  ### ##  ####     ##   ### ###   ##     ####    ### ####                   ## # ######
#             f       f   ### ##    ## #   ######## ####       ##    #### ######     r     #     rl         tf #         #
#                       ####  #     #  #c ########   ####   #####  g####   #####           #          r  f     #   f g   #
#       #########        # ##    ##    ##  #######   ####   #####   ####   #####        t  #g b         r      #        g#
########         #######   #c c   ### f    ##  ###   ####   #####   ####   ###             #####################         #
#                    g  ##f   ##          ###  ########    ####### ###########             #####################        f#
#                       ##                ###   #######      ###     ########      b   r  r#   #           #   #         #
#         g                ###        ## ####       ##        #g c     ##            c     #   #           #f  #         #
##        A    f r     # ####            #  #       ##                 ##                      #r          #        g   g#
# # #               # # ### ##    b###  f g ###### #      c            ## ######  ##########   #       b r #   ## ########
#  # #      f      # #  #   ##      ##      ###### #   r               ## ######     c  ##   rt                   #      #
#     #           #     ###    l#    ##r  f   ##     ##      ###      ###    ##         ##                        #      #
#      #    #    #       ## ##  #  # ###      ##l    ## #################    ##        r##    ###############     #t     #
#     #    # #    #      l# ##    #### # ##  ####       ################    ####      f ##    #             #   r #      #
#    #    #   #   f# l   ##         ##    #  #####    ####         ####    #####        ##### #  #########  # ### ## #####
#     #    #      #         ######     f f# ######    ###           ###   ######    f                     g        f    ##
#      #f   #    #       ## ## ##   # ## g  ###### # ####           #### #######  #r                                    ##
#       #   #            #     t##  ####    # a###     ##           ## t a ###    #      ####                 ###       ##
#        #  # c#                t#  ##   ##    ###     ##           ##     ###c   #     l                               ##
#       #   #   #    g     ##  ###       ##    ###     ##           ##    ####                                f      g g #
#       #   #   #          ##rl###rl     ##     ## #   ###  b #    ###   ####     #                                      #
#        #  #  #            g    #  ##   ##     ## # ######c##### #### # #### c   #                             r     g  #
#       #   #   #        #      ##  ####     ##### # ####    ###   t## # #######                       g             a   #
#      #f   #    #       ## ## ##   # ##g   ######            #   r        #####     grg      b  #########               #
#     #    # #              ######        # ###               #               ##                 #a      #               #
#    #    #              ##         ##    # ######            #            #####         f       #       #               #
#     #    # #    #       # ##    #### # ## A##### # ####    ###    ## # #######               b #       #     tg        #
#      #    # f  #       ## ##  #  # ###       t## # ###### ##### #### # ####     ################lg     ######## ## ### #
#                 #      ##     #    ##         ## #   ###    #    ###   ####                              b             #
#  # #             # #      ##      ##  g    c ###     ##        r  ##    ####      #### #####               ####  # ##f #
# # #       l       # #     ##     ###         ###     ##           ##     ###      #    #          b     f   g       #t #
##                     # # ##            #  #  ###     ##c          ##     ### l    #    #                           f#  #
#                          ###        ## ## ###### # ####           ## # #######    ############################# ## ##  #
#                       ##                # ######    ###           ##    ######    ############################# ## ##  #
#                       ##    ##          #  #####    ####         ###     #####    #   f    #       #      r#        #  #
########         ###  ##   #t     ###r       ####    ##### ########### #    ####    #  f l   #       #       #     f  #  #
#       #########        # ##     #    ##     ##     ####  ########### #     ##   t #    b   #     g #  t    #        #  #
#                       ####  #     #  #  #   ##     ##      ###       #     ##     # b          t   #       #        #  #
#  f                      ### ##    ## #    ###### # #                 #  ######    #         ############ ###        #c #
#                              #     ### ## ###### # #           t     # #######    #        ############# ###        #  #
#                        ##    #   A        #  t     #         c    b  #            #        # t #       #   #        #  #
#           #                      r #      #c       #        #        #  g         #        #   #       #   #       c#  #
#          # #                  #   ##  ##  #   ## # ###     ###     # #  ###     ###        #   #       #   #        ## #
# ##      #   #      ##        f##      #   #  ### # ### # #######g### #  ####    ###        #   #       #   #        ## #
##  #    #     #    #  #         #     ##   #  ### c        #####   ## #   ###    # #  l     #   #   #   #   #        #  #
#    ####       ####                      # ###### c ####   #####   ## #   #####            r#           #   #        #  #
#                       ##         ## #   # ######   ####   #####   ## #   #####    #        #   #########   #        #  #
### # ##         g  g    ##                 ####### ####    ## ##    # #  ######    #        #   #########   # f      #  #
###   ##b###############b##  ####  ########  ####          ### ###   #      ####  ###     r  #   #      f#   #        #  #
########    a            ##        ########      t    ##   ### ###   #                       #   #       #   #        a  #
###########                        A                  ###  ### ###  ##               t f     #   #  ###  #   #l          #
#                    l        b  #f########g          ###  ##  ###  ##                       #   #  # #  #   #           #
#############################                          ##   # ###   ##      g                    #  # #  #   #r          #
#                                # ########          g ##   # ###   ##                           #  # #  #   #           #
################################ #       l    ############### #### ### # ######               l  #  # #  #   #           #
#                                # ######### ################ #### ### # #######                 #    #  #   #           #
#########   ################                    ##      ##  # #      t # ##    #      g      #f  #       # l #           #
#                                ##########  r t#    ##  #  # #  #             #  ###        #   #       #   #        #  #
########### ###############################   #####            bt#       ##         #        #      ######   #  l  l  #  #
#               b            l                 ####     f#       #    ## ######     #        #     #######   #        #  #
##########  ######  ######## ##############       tf #   #    #     # ##   #####    #        #   #       #   #        #  #
##########  #######  #######  ##############         #           #         #####  # #            #   #   #   #        #  #
#            f     a                       #         ####      # ##  # ######     #              #       #   #g       #  #
########### ###### ##    #t## ############          ###     t  ####  #  #######   # #        #   #       #   #        #  #
#            b             ## #############     #   #####                 # ###                  #r      #   #        #  #
########### ########     #          l               #####     f #    # f###                              #   #     l  #  #
#                         l## #############      #########      #       l #         #        ############# # #        #  #
# ######### ############ ####                        ##   g     #   b     #   #  #  #        ############# # #        #  #
#    ###### ############ ##################               f         c     #         #        #r r    #       #        #  #
# ## ##                g                    f       t    #f         g  #            #        #       #       #        #  #
#t   ## # # # # # # #   # # # # # # # # # #              #     #       #            #        #       #  g    #        #  #
#### ## # # # # # # # # #l# # # # # # # # #   ###  ### t       #  f #       #       #        #       #     r #        #  #
#    ##            f                          ###  ##f        ##       t  # #    #  ########### ########## # ## # ## ##  #
########### ########## ####################   ###           #            f#         ########### ########## # ## # ## ##  #
#                                l                     # b    #b    #   g ##             #        rg                 t#  #
########### ###############################  # ###        ##   l    #     ##        #   b#   f                        #  #
########### ###############################b # ###  ##         t    #     #         #### #####               ## #  #  #  #
#        ##               ##                   ##   ###          #      # #    #       f                f                #
######## ## # # # # # # # ## # # # # # # # #  ###                        A    g   ############# ##       # # ## #  #  #  #
#        ## # # # # # #l# ## # # # # # # # #   ##  l   #A               # #        f             #       #               #
######## ## # # # # #   # ## # #t# # # # # #   ##    #   #       #   ##                 g        #       #c       g      #
#        ## # # # # # # # ##         # # # # t  #  ###           #   #### b                      #t      #          b    #
######## ## # # # # #l# # ############ # #b#g  ##  ###  ##########           #r   fg             #########               #
#        ## #     # #   # ############ # #     ##  ###  ######## # ###                                             l     #
#### ###### ####### ##### ##      l  # # #     #######             ###            #                  c                  ##
# g  r# #  ##     #      g       #  ##        ###        g          ##   t        #t                                    ##
#  r ## ##A##b   ##       ##     #  ##g###    # #     b       g f   ####     #gt#                   gb                   #
#    #   #       #        ##  ## ##      #      #     #      ##     #    ##     # #                     l  l         f  ##
#  g   ###    ##          #     f              ##l  ###   #          r    l   #b  #      ####                 ####      ##
# ###l f#     l          ## ### ##       ##t   #   #### ###                 #     #r      b               f             ##
# ##   ##  ##  f            # #### t     ##    #     ## #b      #       l         #                   f      c      A   ##
#               ##l# ##    ## #            ## ##        #   #              #    b ########### #  ######### f# ##### ######
### ##   ##        ###   ###      ## ##  ##b# ##  l         #   #        ####        g  ##  b #             #    ##      #
#   #  f ##      ###     ##      ##  ##  ##       ##       g#        #   ####           ##    ###############    ##   g  #
#   # #      ##  ##  g   #t f     #  #   #  #    b                     f ##      #r     ##                       ##      #
#  ## #       #  #            ### #  ##  #### #                      #   #      g       ##                    r  ##      #
#####     ### #    l            # ## l    # l # f       g          l##   # l      ##########   #           #   ###########
# #   ###   ###             b ###  ###### #   #  #              b   ###  #   ## t    b         #           # f    f      #
# ### # # # r   ## ##        b##l    ## #    ##                  t  ###                    #   #           #   #         #
#   f     #      ###  #   a a##    ###r   #          ####           ###         #  r r     #   #  r        #   #         #
# ##      ##    ###   ##                  #   f    ########           ##   g    ##         #####################         #
# #        # b  #     ##     ### #        #          #   ##     ###            r #    f    #####################         #
#    ####                      ####### ## #          #          ###    ########           f#                   #         #
#    b ##  ##      #  ##     ####   ##            ## #   #             #####               #          t        # A       #
#l ##   r   ##b   ##  ##   g  #   ###                    #                ##  b           f#      g            #         #
#  ##    ## #   ###   #    #       #                     g        #       ##  l   ##### ####     f   r         #### ######
#  #               f ## #####   ## ##                     l a              l          r b                          f     #
#  # r  ## ##g        ### #      #      ########         ### # #    l   ##       #                                 c     #
#g ##    r ##      #####        ##   ##  l#      l  gf #     # f f    #### llg  ##      g        #     f #   f           #
## ###  # ##   f####        ## ##  ####  g   #  #### b     r #    #   ###       #  r    rf       #       #         r     #
##   #bf# #    g  #  ##    ##  #   ##l##  #  l               #    #   ###    #  # t   c          #       #             l #
##     ##    ####     #                ##f        ##         #   ##   # #    ## # ##### ######################### ########
#      #       ## ### ## ## r##    ###f#     l  ####     g ###                  # ####    #######################    #####
##########################################################################################################################
