metadata:
  gen_time: 11.27221417427063
  timestamp: '2025-04-18T22:55:19.748930'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#      ###                   #####t  t     f          #  #          #               ###           #### ###               #
# b     #             ##      ##         ##        #                #  #      b #  ###       ########  ### #      ##  ## #
# ## f        #      ####                      #   ##    ###    #####  #         ####           ###        ## ## #########
#####       ####     ####                          ##   ####           #   f                 ####  f                   ###
#####      #####      #    ##    ##           #                        #  l   b              ###   b        ##     ##### #
# #         ##          t  ##   #####  ##     #      b             ##  ####    #             ##A      l## #### b   ##    #
#      #                    t   l####  ##           #     #    #    #                   ###  ##   ### ###   ###    #     #
#    ####f       ##   ##           #                        #        f      l    #      #######   ##   ## b   #    ##    #
##   ####  ##  #####  ##   #                                        ###  f b     #      ##  ####f###   ### ####     ## ###
###   #    ##  #####      ###         #       f       #     # #                  #      ##    l####    ##   ###r         #
##              ##        ### l##   t###      #  #    ###   ###     ###         ### ## ### b    ###     ## ## r     ######
##  l  b   g             ###   ##    ### tt   ####           ###   ##           ###r## ##       ##         ##  f    ######
#     ##  l               ##        ###        ###   f      ###############  r   ########  l c  ##                       #
#     ##         ##     l      f     ##    #   ##  #      ####           ##     ## ## ##         ## ### ####l  l  ## #####
#    ####        ##   ##                       ##        ####           ###     #      ##   fl #  ###                #####
#    ####             ##     ##  ##        ##   #  A       ## ##  ###    ## #    # ## ####  l  ## ##     #  b  ########  #
##    ##    ##       ####   ########    #  ##b  # ##       ## ##    f       # #     r    ##    #####     ##    ###r ##   #
###   ##    ##       ####    ######        #       ##  l   ##              ####    f      ### #### ## ####### ###    ##  #
##   ####              #       ##        #  f#     ###     t       #         ##                        #   ####    l  #  #
##   ###  b    g                     b   #                                       ##     b      ### ##f##     ##      ##  #
#     ##        #                    l   #                                 t     ######    #####    ###    ### f #####   #
# f        f  #####             ##       #t  #     ###             #         ##    ###  ## ####     ##    ###    ###     #
# ##          #####   cg g r#   ##         #       ##      ##           g  ####     ## ###  ## r          ##      #      #
# ###          ##         ####      ##  #  ##   # ##       ## ##            # #  b  ## ## f          ##          ##      #
#####     ##             t####      ##  #  ##   #          ## ##l ###    ## #       ####             ### # #     ##f     #
####    f ###        ##    ##                  ##        ####           ###     #######             l #### ####### ff  ###
# ## g   ### b ##  #####                 l #   ##  #      ####           ##     ####  ##     ##         ##  #####      ###
#        ### c ##  #####t         ##           ###        f ###############        #   ##    ####### ## ## l ##        # #
#         #         ##      ##    ###         ####           ###   ##           ####    ## ####       # ##    ###     ## #
#  ##               l       ##   ####         #  #    ###   ###     ###t        ####    ######     l  # ###   #### f  ## #
# #####   l         b             ##                  #     # #                 c ##     ##           ###### ### ### ##  #
#  ###### g   ##       f          ##                                ###           ###    ##   l   l      b## # b  ## ##  #
#    ####     ##       ##     t  ####                t      #                      ##     ## ####     #    # #   r    f  #
# f    #      b       #####  ##  ####               #     #  l #    #              ## b       ### l   #    # #    #      #
#    b                 ####  ##   #     #     #                    ##  ####    #  ###      f  ##      ## ### # ####      #
#            ##      t   #     g              #                 f      #           ###        ##f     #### a   ###       #
#     ## g   ###    #              b               ##a  ####           #            ##### ######      ###       #        #
#  b#####   ###   ####    t   t      ##        #   ##    ###l   #####  #   b        ##r#      ### ######     t  ##   # ###
#   #####    ##   ####  f ##       ##### ##  f    f#                #  #    f   #   ## #           ## ##  c     # a     ##
#    ##            ##     ##       ####               #  #          #   g l          # #      ### ##            #       ##
## #########          ####           ####      f   #                       ##       A        ###        g        ###     #
## #######          r g              ####  ##                              ##           a    ###                 ###     #
#  #######r             r g         b   #  ##    ##l    #                  #   a   ###  ########  ########  ###  ###     #
#              ###               ##  r#  r ##    ##     ##       #       #         ###  ########  ########  ###  ###     #
#              ###               ##   #    ##   ##      ###  ##  #     l l         ###  ########  ########  ### g###  gl #
#              ###      ###      ##   ###r  #   ##           ##    ##              ###       ###  ### g    g###          #
####                 ##f###             #       ##    f      #     ###       g     ###       ###  ###       ###   b      #
####            #    ## ######          ##       ##          b          r      #######g ######## f###  ############# l   #
#      rb       #       ######           #  l     #        ##  g  #              #####  ########  ### b#############     #
#               #                   r ##     ##   ##       ##     #          ##  #####  ########  ###  #############     #
#            f  ###              f    ##           ##      ##   #        r r  ##             ###  ###  ###  ###    g     #
#                 #A                  ##        r  r  ##              l l     ###       g    ###  ###  ###  ###          #
#            g    #r                                                            #  ###  ########  ########  ###  ###     #
#            g    #   #####                          g  #       g    l  r    #     ###  ########  ########  ###l ###     #
#       f         ### #####    r          #             ##    #             ##     ###  ########  ########  ###  ###     #
#                     #######  g          ##     ##     ##   ##  #    c     ##    l###       f    ###       g    ###     #
## r    ###  f           ####         c    # #t  ## c   ## g ##   ##         ##r   ###            ###            ###  f  #
## #### ###       ##     ####                    # g    ##   ##               #    ###            ###            ###   rf#
##      ###       ##  ##########                        ##    #          #    ##   ###       f    ###   b        ###     #
###         ##### r   ########## rc       t    l g                       ##    #   ###   l        ###            ###     #
# #g     ####   #####   #####     g                 t                    ###       ###            ###            ###b    #
# ###### ######     #####   ###     fg       ####    ##c       ###        ###      ###      g  r  ###            ###     #
# f      ######  ##       #   #               ###      ##      ####        ###     ###            ###    l       ###    f#
#          ##    ##       #   ###                  b#             #         ###    ###            ###    l       ###     #
####       ##    ##       #     #    ###            ###                    A ###   ###         b  ###    b       ###    g#
####        g    ##       #     #### ###             ####                     ###  ###  ########  ########  ###  ###     #
#######          ff       #          ###               ##c                   lb #  ###  ########  ########  ###b ###     #
#######                   #      ##              #   g  #               ##         ###  ########b ########  ###  ###     #
#    #####    A           ###    ##   #          ##                     ### b             t  ###  ###  ###  ###      l   #
#  rg#####          f       #       f #   f      ##    ##              l ##       gl f       ###  ###  ###  ###  r b     #
#    #########              ###       ###       r##   ##     ##           #      #####  ########  ###  #############     #
#    #########                #         #                  g ##      #    ##     #####  ########  ###  #############     #
#    #########  t             #         #             f               #   ### #  #####  ########  ###  #############r   r#
#      ###      b    #######  #  f  #####          t   l      #    l  #     #A     ###    g  ###  ###    l  ###        r #
#   c  ###      ##   #######  ####  #                     ##  #  ##                ### c     ###  ###g      ###          #
#          #### ##   #######     #  #                          b ##       l        ###  ########  ########  ###  ###     #
# r     ####    ##   #######     ####             l         ##   #    #            ###  ########  ########  ### b###     #
#       #    #       ###########                 l     ##   ##        ##    b      ###  ########  ########  ###  ###     #
#       #    #       ###########                f       ##  ##        ##    ##          r    ###                 ###    b#
#      g####   #####   ######              b  ##         ##  ##        #         A        l  ###                 ###     #
# ################# ## ###     # #   # ##########################################    #   b#  #          # # ### #   #    #
# # tb              ## ### ## ## ## ## ##                                                ## ##     #      #     #        #
### ## #### #### ## #   ##b            ##                                              a b#b #t    ##           #  ## ## #
### #   ##   ##   # #   #################                                                     c    #      l     #  #  #  #
### #   ##   ##   # ## ##########################################################                  #        ##  #  #    c#
### ## ####f####r##          t           ######################################## #    ######  ##  #    ##    l # t      #
### ## #### ####r## ## ## ## #### #### ##        r                            r   #             # ##    #             ## #
### #   ##   ##   # #   # #b  ##   ##   #  r       r                              #      g    g t  #    #b     t         #
### #   ##   ##b  # #   # #   ##   ##   ######################################### #          ####    l                  t#
### ## #### #### ## ## ## ## #### #### ########################################## #          #              #       r    #
###                 g              t          g    b                              #  #    #  t  # ########  #       b    #
### ##################################### r                                          #   ##  a  # r#        #          # #
### #####################################                      g                 ## ##                         g       ###
##   ##                            ##       b              r                      #                        a      # l  # #
##   ## ## #### ####b#### ## ## ## ## ##                              r           r        ##                  #  # ## # #
### ### #   ##   ##   ##   # #   # ## #  ###########################################            #####    ####  ## #      #
### ### #  a##   ##   ##   # #   # ## #c ########################################      # t    a                   t  #   #
##   ## ## #### #### #### ## ## ## ## ##c       ft                                #    #                   #      ## ## a#
##   ##                            ##   f        r                               ###  ##  #    b #     #f  # ##   #  #   #
### ############################## ######                                             b   #      #     #          #      #
################################## ######                          l                             # ##  ##    #r   #      #
###       f           t                                                   r            g r     f #     #   ###  t #   t ##
### ## ## # ############## ####r#########                     A     g            ##         #          #          #     ##
### #   # #  ## t######  # #  #    ######       gf   l           f                   ##  #### #######               l   a#
### #   #            r                                      g             c     g#    #                                  #
### ## ## # b##  ######  # #  # #  ################################################   #     f #    # b    ###   g#   g  ##
### ## ## ################ #### ##################################################    #f   ###########      # ####   #   #
##   #  #      t           t           t                 r                                                      g    #   #
##   # ##################################                  c  b                  ## a## #   #                 #r         #
### ## ##################################                             rfbf     l  #  #  #   ##      l######   #b#######  #
### ## #  ##  ##  ##  ##  ##l ##  ##  ##       r                                     #      #    a#     #     #   b #  t #
#   ##                                   ########################################    #      #     #           #  #    f  #
### ## # A##  ##  ##  ##  ##  ## b##  ## ######################################## # a##r #t ##                #  #     r##
# # ## ##################################                                         #    b ## #        a   #           #####
#        f                                    f                                   #      #  #            # ## ## ##      #
# #   ## ## ## # ## # # ### ## ### ## ##                 r                           #   #          r   ##  #    #  g  #t#
##   ### ## ## # ## # # ### #####   # #                       r               r   # ##            ##     #             ###
#   ##      ##                 ##   # #  ######################################## #     ## #      l                      #
# # ## # ## ## # ## #   # # ## ### ## ## ######################################## b     #  ##      g  #      ##          #
# # ## #  # ## #  # # r # #  # ### ##                                            ###  t #  #   #  ######  #              #
##########################################################################################################################
