metadata:
  gen_time: 3.690485954284668
  timestamp: '2025-04-18T22:59:24.674922'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#      #  ##   ##  # ##    ##  #  #r      #         #  ###      ###  #  g      #       #g #  ##  r ## #  ##   ##  #      #
#      #   ## ##  #           #   #r      #          #     #  #     #          #       #b   #          #  ## ##  b#      #
#    b#           #     ##       #         #         #     #### g   #     g   #       t #       ##     #       g   #     #
#    g#         g#    ##  ##    #           ##       #      ##      #       ##    t      #    ##  ##    #          #     #
# ##   #         #   #      #   # b           ##                    #     ##             #   #     b#   #         # t ## #
##  #   #        #  #   g  a     #  ########    #   #   ####  ####   #l  #    ######## g#   #        #  #        #   #   #
#    #   #       #  #         #   ##  g     ##   ###   #    ## r  #   # #   ##        ##          r  #  #       #   #    #
##  l#    #      #   #         #   g          #                    #       #           r  #         #   #      #    #  t #
###   #   #tg     #   #        #               ##                  #     ##               #       ##   #       #  t#   # #
# ##  #   #   ##   #    ####  #    #####         #   b #          #     #b        #####       ## #    #g  ##   #   #  ## #
#  #  #   #  #  #   ##      #     #     #    ##   ###    #      ##   ##    ##    #     #    ## b   b##   #  #  #   #  #  #
#     #  #  #    #    #          #       ####  #     #    ##  ##    #     #  ####       #      b  ##    #    #  #  #     #
#  #  #  #  #     #     #        #              #           ##     #     #              #        #     #     #  #  #  #  #
#  ##  #  # r#    #      ##       #      b       #     # #      ###     #   g          #       #       #    #  #  #  ##  #
#   #  #  #  #    #        ##      ##f     r     #        #    #     r  #          b ##      ##        #  t # l#  #  #   #
##     #   #  #  #    #       ###    #           #         #  #         #       b   #    ## # b   ##    #  #  #   #      #
##  #b #b  #  #  # g #  ##       #  f #######    #         #  #         #    #######    #        #  #   #  #  #   #  #   #
#  ##  #  # r #  #  #     #       ##  fl     #    #        b#               #    a    ##       #    b#  #  #   #  #  ##  #
#  #  #  #   #   #  #      #        #   r     ##   ###             ####   ##         #        #      #  # t #   #  #  #  #
#     #  #a  #   #   #      # ###    ##         #      #          #      # b       ##    ## ##   g A#   #   #   #  #  r  #
#  #  #   #   #  #  t #          # t   ###       ##      #### ####              ###     #          #    #  #   #   #  #  #
# ##  #g   #  #   #   r ###       ###     ####      ##              ###     ###      ###       # #     #b  #  # b  #r ## #
###   #    #   #   ##      #         ##       ###      #          ##     ### r     ##         # A    ##   #   #    #  b# #
##    #     #   #    ##     # #        ##      g #       #### ####               ##         ##     ##    #   #     #     #
#      #     #  #r      #      ##        ##    b  ###                ##         #        ##      #       #  #     #      #
#  ##   #    #b  #       ###     ###       #####       #          ###     ##### b     ###     ##            #    #   ##  #
# #g #  #     #   #####     #       #  ##       ##       ##    ###       #  r    ##  #       #     #####   #     #  #  # #
#     #r #     #        #     ###    ##  ##       ###      ## #      ##   b     #  ##    ## #    #   b    #     #  #     #
#     #   ###   ##       #       ##        #   g     #      r       #        l#        ##   b            #   ###   #  a  #
# #   # l    # l  ####    ###      ##       ##       r             # A   b  ##       ##      ###    ####    #      #   # #
#  #g #        #      #       ###    ##       ##                   #      ##       ##    ## #      #      ##       #  #  #
#   #     ##     #               ##    ##   g   ##     #  ### ##  #r  l  #       ##    ##                #    ##  #  #   #
#   #   ##  #    r##    ##         #     ##       ##t  g #      ##    #  a      #   t #          #    ##     #  ##   #   #
#    #   b   #      ##b   ##        ###    ###      ##              ##      ###    ###        ##    ##    ###       #    #
#     #         ##  A #     # ###   t  ##     ###      b           #     ###     ##      ## ##     #     #        ##     #
#       #####     ## g  ##       #       ##      ##    #         ##        g    #       #        #    ##     #####       #
# ###  A     #      #     ##      #####    ###     ##    ##    ##    ##     ###    ##### b    ##    ##    ###        #####
#    ##         ##    #  b l#      r   ##     ###    #     ## #    ##    ###     ##         ##   g #     #  r     ###    #
#       ####      ##t   ##    ##         ##r     ##    #         ##           t #         #      #    ##      ####       #
#  g        ##      #     ##    ##         ###     ##    ##    ##    ##     ###         ##    ##    ##    ####        g  #
#  ## ##        ##    #    c#     #######  t  #g     #     ## #    ##      #     #######r   ##     #    ##        ## ##  #
# ##   ## ##      ##    ##    ##         ##    ####    #         ##      ##     #         #      #    ##      ## ##   ## #
### t      ## ##    #     #     ##         ##    g ##    ##    ##    ##      ##         ##     #    ##    ## ##     g t###
##b            ##     #    #      ####       ##      #     ## # A  ##      ##    g  ####      #   ##     ##             ##
#        g      ##      #   # ##      #####    ####    #        r##      ##     ####      # ##  r#      ##r     l        #
#     b          ## t    #    b ##         ##      ##    ##    ##    ##    l ## b       ##      #      ##               t#
##                ##t     ##t     ####       ##      #     ## #    ##      ##   l   ####     a##   r  ##         b      ##
###             g  ##   g   # #b      ###      ####    #         ##g     ##     t###       ###       ##                ###
# ##   ## ##  g     ##b        ###       ##        ##    ##    ##    ##        ##       ###         ##b   g   ## ##  r## #
#  ## ##   ##        ## ##        ####     ####      #   g ## #    ##      ####     ####  g     ## ##        ##   ## ##b #
#           ## ##        ## ##        ##       ####  b #         ##    ####       ##        ## ##        ## ##           #
#               ##           ## ##      ###        #     ##    ##    ##        ###      ## ##           ##               #
#   ## ##        ##              ## ##     #         ##    ## #   g##    g    #     ## ##              ##        ## ##   #
#  ##   ##        ##                 ##   r #          #          #   b      #     ##      r          ##        ##   ##  #
#  #     ##       b## ##A      r      ##    #           ##  bb  ##           #r   ##              ## ##        ##     #  #
########    #########   ####  #######    #####################   l        ######## rf ###         r         #####      ###
########    #########  c####  #######    #####################      t##   ########  a ### r            ga   ##gt r     ###
########    #########c  ####  #######       tr  c        btf         ##   ######## a  #####   ##            ##     ##    #
# c         #########   ####  #######        c            g b        ## r ########   A#####   ##         rf ####t  ##    #
#      b    #########c  ####  #######       f   c                         ########  #######   ##            ####   ##### #
###      t c#########   ####                    c        ct         af        #### b#######g g## r    ##########   ##### #
###         #########   #### t      c    c ##       ########             t    ####  #######   #####   ####################
###   ##            c   b  A  f  c         ##     c ########            rg   t####       ##########     ##################
###   ##   t        c c t              rc  ##       ########                             ##########     ##################
#  t  ##  ########l #######           ##  g                          a                    g     ###   r ##################
#     ##  ########  ####### t ######  ##                           ######     ###               ###     ##################
#     ##  ########  #######   ######  ##  #################### f   ######     ### r  c          ###    c     #############
# t      c           c                ##  ####################   ########     #####         ##   g           #############
#       t         c               r      c####################   ########     #####         ##       ##      ######      #
# c####    ########       t        c                 c  f      ##########     #####      a  ##     a ##      ######      #
#c ####    ########                      g       c             ##########     #####                           t###       #
#  ####    ########r ####       #########     c     rc ##################     #####   b  b         t r             #######
#  ####   c########b ####       #########   ##  cc     ######### a#######                      ## g#####       ###########
#  ####    ########  ####                   ##         #########  #######  b        t          ##  #####       ###########
#  ####    ########  ####        c         f##    ###         c#  ##########     #######           #####  b    ###########
#  ####    ########t ####   #####    #####        ###      r   #    ########     #######     t     #####   c   ###########
#  ####  bc########  ####   #####    #####                     #    ##     g     #########         #####   g             #
#  ####     b   c    ####   #####    #####            c   f   c###  ##           #########         #####    a            #
#  ####         c           ##### c  #####   c ################### a       r     ######      f     ########t       #######
#  ####  ###                #####  l #####     ###################       f  a    ######            ########      bt#######
#  ####  ###f       ####    #####    #####c    #####################             ######           l####  ##        #######
#  ####  ###   b    ####    #####   b#####     #####################        f   g######a    ###    ####  ########  #######
#   f  c ###            c f      c                    r          ########   ###########   b ###    ####t ########  #######
#        ###   c                  t       c      t   fb          ########   #######         ###r   ####  ########r #######
# g      ###    f    #################################   c     ##########r  #######         ###    ####            ##### #
#  c     ###  c      #################################         ##################           ###                c    f    #
#     f              #################################  #####  ##################           ###       g       r     t ####
#  c        c               c                  g    c   #####t ##################           ######               a    ####
########     l      gc         b l        cct c      ccc       ##################           ###t                 f a  ####
########      c#######     cc ####        ####t                ##################f          ###             t            #
#              #######  ####  ####    c  f####   ########   f   #########   #######  f   t  ###    ####    c     g ##### #
#              #######  #### f#### c      ####   ########c   ##  ########  t#######  t r   f###    ####  ########  #######
#       ###  c #######  ####  ####       c   c   ########f   ##  ########g  ###########     ###    ####  ########  #######
# c     ###                   ####           c   ########f   #######             ######     ###    ####  ########  #######
######lc###                      c    ####c              l     #####t      t     ######f           ####  ##        #######
######     l ####   ####    c     t   ####                  c  ###       t   l   ######  a    a    ########t f     #######
######    c  ####   ####            g       #####  ###############               ######     f  a   ########  r     #######
#         b         c           r           #####  ###############  ##           #########         #####                 #
#      cc      c   t      #############   t #####  ############# g  ##           #########         #####    a            #
#  ##  f  b   #####       ############# f   ##### f  c     f  c#    ########     #######           #####  t    ###########
#  ##  ####   #####       c f   g               f            f #  ##########  g  #######           #####       ###########
#  ##c #### c       f                         c       f        #  #######    t                 ##  #####    r  ###########
#      ####       r     c     t c         ####  ################  #######       c rt r         ##  ##### b    c###########
# gc   ####  ########   ######     c      ####  #########################     #####          t                 ###########
##     ####  ########   ######c ########  ####  #########################     #####b         r     b  g               r  #
##     ####  ########   ######  ########  ####  #########################  r a#####      rg ## r     ##      ######     c#
#      ####  ########    c      ########  ####       c           ########     #####     f   ##       ##c   b ###### r r  #
# t      c   ########           ######## c####                 g ########    g#####  t      ##               #############
#      cf    ########    c      ########c            A c    ### a  ######     ###     tc        ###       t t#############
# #####      ######## c       c                   f         ###    ###### r   ###               ###     ##################
# #####      ########        f  l    l                      ###       g         f            a  ###     ##################
#c#####      ######## f         g    #######  #######       ###   l  t    r              ##########     ##################
# #####   f l########    ##########  #######  #######   c  f###         r     ####       ##########     ##################
# #####      ########    ##########  #######  ####### r##   ###         g     ####  #######  r#####   ####################
# #####   c              ##########  #######  ####### c##   ### g g           ####  #######   ##  g   ##########   ##### #
# #####c                 ##########  #######f #######  ##   ###       r   ########  #######   ##          r ####   ##### #
#          ##     #####  ##########        f  #######  ##   ###g     ## c ######## a  #####   ##         c  ####   ##    #
#          ##b  c #####c ##########    c      c                   g  ##   ########    #####   ##           t##     ##   f#
#  c c          c        ##########                     b     c      ##   ########    ###              b               ###
#  c              c                  ###  c####################           ########    ###                   #####      ###
##########################################################################################################################
