metadata:
  gen_time: 12.488540887832642
  timestamp: '2025-04-18T22:49:53.062980'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#       ##   ##     g   #       ## t          b                  ##    b                                         b ##  b #
#r      #     ##       ##      ##t       l                   ##         b                                              # #
#      ##     ##      ##       ##              r                            c                                     r      #
#   #  #      #    #  ##       ##     ##  # b ##    ### ###  l               b                            #    f   g     #
#   ##       ##     #  #        ##   ##   ##   ##    ## ####               ## c          f               ##              #
#   ##      ##   ## ## ##      b     ##   ###  ##      ####    fc          ##            r               ##      f      c#
#  ##  ##   #     #### ##            #    ##   #  # #  ###     ##    g f   ##       #  l        b#       ##          ##  #
# ##  ##f   #         ##                 ##    #### ##  #     ##           ##       ###f  A    ###      c##     l    g## #
###   ##   ##         ##    ##   #       ##  f #####         ###           A#        ###      ###        #      c     ####
#     ##   #      g   ##   ##    ####  #  ##l  r#### #       #    ##          ##      ###    ###      ##          ##    ##
#t     ##             ##   ##     ###  ##  ##       ##   f l        ##    l   ##       ##    ##       ##        ##      f#
#           t     ####  ###  ## #  ###  ##         f##                       ##g #      ##  ##      #f ##                #
#   f    ##      #####  ###  ## ##   ###          ##  ####                       ##            r  t##                    #
#   #     ##      ##     #   ### l##   ### f       # ##  ##      b                #                #                     #
#   ##     #   ##   ##       ### t##   ### c             ##           ##   g                      b           ##    f    #
#   ##          #####        ###  ##   ###  #          t ##           ##                        fl  r         ##         #
#   ##   f       ###l     ##  #   ##   ###  ##            ##                      #      f         #                     #
# #  ##  # t      #        ###  ##  ###   ## ##    ##     ##                     ##                ##                t  c#
# ## ##  ##                 ##  ##  ###   ##  #   ##    #  ##       g        ##  #      ## r##      #  ##                #
#  ##  ## ##     b           ##  #   ##    ##     #     ##  #       ##        ## c l   ##   c##       ##        ##       #
#   #  ##  #        #        ##    b  ##   ##    ##      ##  #f   ##          ##      ###    ###      ##          ##    ##
#       ##          ##      ##        ##   ##      ##    ##  ###        b   #        ###      ###   b    #            ####
#      l##          ## f               #   ##f   ###    ##    ##      r    ##  g    ### b      ###       ##           ## #
#b   ####           #  #               ##  ##    ###  f        ##          ##   g   #l        f  #       ##          ##  #
#  ###        r     #####    ##         ##  ##    #  ##           f    g   ##                       t    ##       f   c  #
# ##     f     #    #####     ##         #  ###     ##      f              ##                            ##              #
# ##           ##   ##  #     ###           ###     ##                     #                       b      #   c          #
# ##   f     #  ##  ###  ###  ###            #   #  ##                b                          f                       #
#c##     r#  ## ####f #  ##    #                 ##  ##   #  ##     r                                         c b      ###
# #       ##  #   ##     #       f       ##      ##   ##  ##     ##        l   b                           c    c  ##    #
#   g# #  ######g #  # #  # ## #  ##   # #  #################                     t     #          ###   ##  #           #
###### ############ ## #### ## ###### ## ############### ####   b           a   l l  r         b a ##    ##f             #
###                b##      ##     t  b      A                               l                 a  ##     ##              #
### ### #   ### ###### ## #### ## ######### ###### ##########    l                                  g    ##          #   #
### #   #   ### ###### ## #### ## ######### #################       ##            ##                     ##          ##  #
###                     l t     #      bg          ##                r             ##          a  ##a    ##          ##  #
### #   #  ## #  ####l##  # ## ## ## #### #  ##b## ## ## ####     ##          f                      t l  #          #   #
### ### # t # # t ##   #     # ## #   ##     #r  #g## #  t##      ###                               #   l                #
### ### #   # #   ##   #     # ## #   ##g b  #   # ## #   ##       ##                 t             ## f             t   #
### #   ## ## ##t#### ##  # ## ## ## #### #  ## ## ## ## ####    r                               f  ###                  #
##    f  g  l  b               ##                  ##   f            ##      g  a          #         ##     A         r  #
### #  ################## #### ############  ################       ##                  ####     #    #g                f#
### ##################### #### ##t######### ###### ##########                ###     r  ###      #                       #
###                     t    b     f      l g##                   ##         ##                          c       g g a   #
### ## ###### ## ## ################# ### ## ## ##l### ### ##   A           ##        ##                                 #
### ## ###### ## ## ################# ### ## ## ## ### ###g##t     #  ##          #####  ##    a                        t#
###b                tf       l               ##               ##      ##          ####   ####aga                         #
### ################## ########## ################ ############   ##  ##       a       a   ###    #         #   ##  #    #
### #  ############### ########## ########## #################    ##     g                   ######            r##  ##  ##
##      f l   g                ##   t              ##             ##           ###    g        ###   a ##       ##  ##  ##
### #  ##   #l## ####  # ## ## ## ## #### ## ## ## ## ## #### b    ##    # gf   ###              r              ##       #
### #####   # #  f##   #b#   # ## #   ##   # #   # ## #  t##       ###   ##      ###f     #   #       l         ##       #
### #####   # #   ##   #b#   # ## #   ##   # #   # ## #   ##g      r ##  ###      ##       #  ##             f   #       #
### #  ##   # ## ####f # ## ## ## ## #### ## ## ## ## ## ####    ##       ###     t   ##   #  ##  f             f     a ##
###     l          cf       g   #     f       l    ##         #  ##        ####t              ##a    a              r    #
### #  ##   ########## ####### ## ####### ## ##### ##########  #a   t        ###  ##  g#r     a## b    ##        a   f a #
### # ###  ########### ####### ## ####### ## ##### ##########  #              ##b ###  #g       #      ##      b   #  a  #
###               g ## lt   ##               t                f                    ##      ##   ##g    ##  ##       ##   #
###### ############ ## ## # ## ###### ## ############### ####                 #   f #    t b    ##      ##b  ##       g  #
#t   # #  ######  # ## #  #l## #  ##   # #  #################### l    ##     ##                 ##       #     ##        #
##                                      a                          ##         ## g###     ######   ##     ##   ###       #
##                                                         t #    #####            ##   b#######              ###       ##
##      r     g                                              #    ######     a     a    #######    f      t   ###     ####
#### # ## #### #### # ## #### # ## #### # ## # ## # ## # ## ###     #####g    ##  f    ####  ##           ##   ###  a#####
#    #  #    # #g   #  #    # #  #    # #  #b#  # #  # #  # ###      #####    ##     #####        ## g    ## f ####  #####
#  # #  # #t # #  # # b# #  # #  # #  # #  # #  # #  # #  # #### l   t ###           ##### a     ####       f #####   ####
#### #### #### #### #### #### #### #### #### #### ####b#### ###### b    ###           ##  f g   #####         ####   f  ##
##                                               t            ######    ###      ##         b  ####            ##        #
## b                   c                        f    g         #####   #####   ####b       ##  ### l     l               #
##                                             g        A      ####    #####   #####  ##   ## r ##    ##                 #
#      rt                                          g             ##      ####   #########         t   ###           ##   #
##                                                                t  g   a###    t#######            #####  ##      ##  ##
### #### # ## #### # ## # ## # ## # ## #### # ## #### # ## ##g            ##        ####     ##      ########### r      ##
#     l# #  #    # #  # #  # #  # #  #    # #  #    # #  # #             r a         ##   f#####    ##############       #
# # #  # #  # #  # #  # #  # #  # #  # #  # #  # # A# #  # #   r   ##       a   ##f        #####  ######  ##  ######     #
### #### #### #### #### #### #### #### #### #### #### #### ##    ######   a   #####        g###   #####        t######  ##
##           b                t                                  ######       #####          ##    ##             ########
#                                                             a    #####  ##   ##            g  a           ## a    ######
##           fl    t                                      r  ##     ####  ##         f ##           b     g ###      ##  #
##                                                           #### ag### f              ###  ##        a    ####          #
#                                      l     g               ####  f ##    a  ##a ##  ##########   a  ##   ###   f  r    #
##   c                    A  g     f                  r   f   ##        a   ######################  #####   ##  f     ## #
### ### ### ### ###g### ### ###g### ### ###b### ### ### ### #             ##############g ##  ###########   ###   l   ## #
##### ### ### ###l### ### ### ### # # ### ### ### ### ### ###     ##  ##  ####a ##  ##    a     ########   #####         #
#     g                                                      ##   ## b##   ##                     ## r##   ######        #
#                         t                                  ###                g r      g  ##     g       f ######  ##  #
#                                         rr         g       ###               ##         ####                 ###########
#                              f                             ##   ##         #####  ##    #####  ##  ##          #########
#      g                     b          g       fl                ###        ###########   ####b ##  ##   ##       ##  ###
# ## ### ######### ### ############## #### ############# ####    #### g      a##########   ###           #####  f   g    #
#  # ### ####### A  ## #################################    #  t##     l  ##   f                        ##  g##  g##     #
#           f     g##     t                           ###   #   ##   l    ##                        f   ##   ##   ##     #
# ## ### #### ######  r                 ############### #   #   ##        ##       t                    ##   ##   ##     #
#  #   # g      #            ############               #   #   #######   ##   ####### r ##rl #######   ##   ##   ##    r#
##################    l ######       g     t        r   ## ##   #######   ##   #######   ##   #######   ##   ##   ##a    #
#        t       ## ######                   #######  l  ###r    b   ##   g    ##   ##g  ##   ##                         #
#b                ###       r           #######   ##### ###          ## g b  g ##   ##   ##   ##        r       b     f  #
######## ###########    ##################           t       g    f  ##l       ##   ##   ##   ## b   l                   #
#                      ##  A     ##                          #####   ##   ##   ##   ##   #################   #######     #
##     # ###############                                ##########   ##   ##   ##   ##   #################   #######     #
###   ##        ttg           t       t        ##########          r      ## r ##   ## l ##                       ##     #
#                  r                   ##########                   b     ##   ##   ##   ##                 f     ##     #
#l ## #                   ##############  ## t       # # ###              ## l ##   ##g  ##                 f     ##  g  #
#                ##  ######                         ## g  ########   ##   #######  f##   #######  l#################     #
####      ############# l    r                    r ###  ## ######   ##   #######   ##   #######   #################    t#
#   t   g  #        g l                               #  #      ##  l##             ##   ##                  ##   ##   l #
#       #  ##    t                    g    l        # #  #    b ##   ## g           ##   ##     g    r g  ff ##   ##     #
####### #   ## #### ## #########                    ###  #      ##   ##             ##   ##                  ##   ##     #
#            ###              ## ###### ####         ##  #      ##   ############   #######   #######g f##   ##   ##     #
####### # #####                      ##   ############   #      ##   ############   #######   #######   ##   ##   ##     #
#                 # ## #########               ##t     g ##     ##             ##      l ##  f   g ##   ##   ##   ##     #
####### # #########  # t     g # ###### ####              ##    ##  f          ##        ##      l ##   ##   ##   ##   r #
#   ##      ##                             ############### ##   ##             ##        ##        ##   ##   ##   ##     #
#                                           #         ##    #   ##   ##  f############   ##b  #######   #######   ########
#                    # #########        g  ###### ##     g     f##   ##   ############   ##   #######  t#######   ########
#           t   ######   ##   b#     ## ####       ##########        ##             ##   ##  g     ##      l             #
#  #### #  #######   b   g       #####t   t         #    f           ##          b  ##   ##       t##       b            #
# ##    # #r  l                  #      #########  ## #######        ##             ##  f##     t  ##      f            r#
###    ## ##     r            ## #########      ####     ##        g ##             ##   ##        ##                    #
##     #   ##      ############   #                   r              ##             ##   ##   g    ##                    #
##########################################################################################################################
