metadata:
  gen_time: 4.2466840744018555
  timestamp: '2025-04-18T22:54:32.834382'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##### ## ## ## ## ## ####                    c                r        #        #          ####   ###   ###  #### c  #####
##### ## ## ## ## ## ####                                              #     ####     #    ####   ###   ###  a tg    #####
#                         t       r          r            l            #     ####     #    ####   ###   ###      b #######
#     ##    ##   r##    t          r      b  f           t             #              # ####### ##### #####        #######
#     ##    ##    ##   r ###############################################              # ####### ##### #####        #######
#     ##    ##    ##     ###############################################              #f#######              ##          #
#     ## g  ##   g##                              b            f       ##            ## #######              ##      l   #
#     ##  A ##    ##          f   b                 l     t  l          #            #  #######           r  ##         l#
#     ##    ##    ##   b      t            l                            #      b    b#  #######          a   ##         ##
#r    ##    ##  f ##         t       l                         r        #            #  #######              ##   ####  ##
#     ##    ##    ##                                             c      # f          #                t##    ##   ####  ##
#     ##    ##g l ##                              r        r            #            #                 ##    ##   ####  ##
#     ##    ##  ft##            b    l                           r   t  #            # ##########    t ##    ##   ####  ##
#     ##    ##    ##    r       b                                       #            # ##########r     ########   ####   #
#     ##    ##    ##f r                                                 #           b#            a    ########   ####   #
#r    ##    ##  l ##                                                    #            # a            ###########  r####   #
#     ##    ##    ##                     l                              #            # ##########   ###########   ####   #
# r   ##    ##r r ##b                        t                        l #            # ##########   #####a  ##########   #
#     ##    ##    ##            l                            c          #            # ########## f #####   ##########   #
#     ##    ##   b##                               b                    #            #    ###       #####  f##  ######   #
#     ##   b## l  ##     f                                              ##          ##  t ###       #####   ##  ######   #
#     ##  l ##    ##   b               f                                 #    ##    #     ###   #########   ##  ######   #
#     ##    ##    ##                                                     ###  ##  ###     ###   #########   ##           #
#     ##    ##f   ##                                        l  b       f ###      ###           #########   ##           #
# l g ##    ##  f ##               b                 t                     #      #       rf    #########              ###
#     ##    ##    ##                          f           l         fb     #      #      ###  ###########     f      t ###
#     ##    ##    ##                                                      ##      ##     ###t ###########       ##     ###
#    b##    ##    ##                                                   ####        ####  ###  #####   r         ##   #####
#     ##    ##t   ##                                                                     ###  #####  f      g   ##   #####
#     ##    ##fA  ##             r l                   tr       f                   l    ###                  ####   #####
#     ## t  ##    ##               l                         r f     lb         a        ###               a  #### t     #
#     ##    ##    ##                                                  b                  ###  g    #####      ####       #
#    b##    ##    ##                    r    b                          ##############b  ###   ##  #####      ####  ######
#     ##  g ##    ##          t   b      f                     g       ##            ##        ##        t########  ######
#     ##    ##    ##              c          r              r          #A             #        ##         ########  ######
#     ##    ##   g##                            t  l                                   ##      #          ########  ######
#     ## fg ##    ##             l                      l            f                 ##  r   ##  ###############  ######
#     ##    ##    ##         l                                                         ##      ##  #######################
#   b ##    ##    ##                                            r      ##            #### t######  #######################
#     ##    ##    ##      g                                             ##############     ######  #######################
# bg  ##    ##    ## r                                                 r    ##  ##  b   g  ######    t         ###########
#     ##    ##    ##                                                        ##  ##         ###### l            ###########
# g b ##    ##   t## f g                                                         g         ######a    ####  ##############
#     ##    ##    ##    r                                     b              f             ######     ####  ##############
#  t  ##    ##   l## f                                    b                              ########  #######  ####        ##
#     ##    ##t   ##                           t   l                         t           ########  #######  #### a      ##
#     ##    ##    ##                                                                     ########  #######l  t          ##
#  t  ##b   ##    ##    g                   b    l        t           f                  ########  #######              ##
#l    ##    ##    ##             r                                     # f            #  ########           r           ##
#     ##    ##    ##                             f                  f  #   g          # a######             g ####   #####
#     ##    ##    ##l   g                            b                 #              #  ######    #####      ####   #####
#     ##    ##    ##      b             t                              ###         g###  ######    #####    rb####      c#
#     ##    ##    ##                                        c            ############    ######           bl  ####       #
#     ##    ##    ##                                               r          ##         ######               ####  ######
#     ##  l ##    ##    A########## ################################### t                   a     ###    ###  ####  ######
#     ##    ##    ##     ########## ###################################                           ###    ###  ####  ######
#    g##    ##    ##l                                                  ################           ###    ###        ######
#     ##    ##    ##                    b                                   ##  ##     #####  #######              r######
#     ##    ##    ##         b                             r                ##l ##     #####  #######               ######
#  g  ##    ##    ##                              b                              g                 b             t  ######
#     ##    ##    ##l       r                           f                                  r                        ######
#     ##    ##    ##  l t                                                   ######           ######        ##     A ######
#     ##    ##    ##                  r  r        l                        ##    ##          ######        ##       ######
#     ## b  ##    ##                           b     b                     #      #      ##########  r     ##       ######
#  l  ##    ##    ##   t                            l                    ###      ###    ########## g    ####     ########
#     ##    ##    ##                                                     ###      ###    ########## g    ####     ########
#     ##    ##  tb##r   b              f          b     f                #          #    #######         ####     ####   #
#     ##    ##    ##t      t                        b      l       g     #          #b   #######         ####  #######   #
#     ##    ##   t##   b                       b                         #          #    ####################  #####    ##
#     ##  r ##t g ##g     r                     l   l                    #    g     #b   ####################  #####    ##
#     ## g  ##    ##           r                                     l ###          ###  ######         l ###  #####    ##
#t          l                                                    b     ###          ###  ######           ###  #####    ##
##### ## ## ## ## ## ####                 b           f                #     f g g    #a t   ##  a     ######            #
#####f## ## ## ## ## ####                        A                                           ##    b   ######      a     #
#                ##   ##  #t  ##        r       ##    ######      ####        l    ##                                    #
#           g    ##   ## ##   ##                ###    ####      ##### g    ##     ##              ##                   ##
# ########### ##################### ################       t    #####      ####     #              ##                   ##
# ########### ##################### #################t         #####      ######      ## ## ########### ########## ## ####
#    ##                      ##           ##    #####    ##    ####       #######     ## ## ########### ########## ## ####
#    ##           ##       f ##           ##b t a###    ####    ##     rg  ######              ##                      g #
######## ### #################### ##### #######   g     ##### t       ##   a####               ##                    g t #
######## ### #################### ##### ########    t    ####        ####                      ##                        #
# ##  ##  ##    ##             ##    ##  ##  ##   ####r   ##         #####         a           ##                        #
# ##  ##  ##    ##r        c   ##    ##  ##f ##  ######              r####  f l                ##                        #
#     ##  ##    ##             ##    ##  ##     ########               ##b      t              ##                        #
# ##  ##  ##    ##             ##    ##  ##  ## ######## t     l          a                    ##                        #
# ##  ##  ##    ##            t##    ##  ##  ##  ######     ####                t              ##                     g  #
# ################### ##### ###################            ######                              ##                        #
# ################### ##### ###################          a ######       b  r     t   #### ## ########### #### ### ########
#    ##           f       l               ##      ####     ######   ######l     ######### ## ########### ####f### ########
#    ##  lb                               ##b    ######     ####   ########    ########     f     ##                     #
#                                          f     #######           #########   ########           ##  t                  #
#    ##             r         t           ##t    ########     b     ########    #####             ##                     #
#    ##                                   ##     #########b      b   ###### f a      ##           ##      t              #
#    ##        f  t  t      l         g   ##     ########## g     l                  ##           ##                   f #
#    ##    f           gt                 ##c     ##########                         ##          g                  c    #
#    ##     g    f        t               ##       #########    ####   r     ##  t   ##           ##                     #
#                                                   #######    ######       ####    t##           ##                     #
#    ##                                   ##      t            #######      #####    ##     g     ## f                l  #
#    ##              c                 t  ##            gf     #######      ######        t c     ##     c               #
#######    f      g f        c       b   f######     g ##   t g #####        ######  ##           ##b    t   f  g  A     #
#      ##  ##                   r   ##  ##      #     ####                    ##### r##           ##        g            #
#  l   ##  ##                       ##  ##      ##ff ######g                  a###   ########## ####### ####### ##########
#####  ##  ##c ###################  ##  ##  #######g #######           #####a        ########## ####### ####### ##########
#####  ##  ## c###################  ##  ##  #######  #######          #######  g       ##  ##        ##  ##f      ##  g  #
#     b        ##          b    ##g             ###  g#####           #######b g t###  ##  ##        ##  ##       ##     #
#              ##               ##   b    l  l  ##                     #####     ####      ##        ##  ##       ##     #
#  ##########  ##  ###########  ##  ##########l #             b###   l          l#### g##  ##        ##  ##       ##     #
#  ##########  ##  ###########  ##  ##########         t      #####  b           ####  ##  #### ###########       ##     #
#      ## l    ##      A        ##t     ##             t      #####       a       ### g##l #### ###########              #
#      ##      ##               ##      ##       g########    ####                     ##  ##    A##   f ##   f   ##     #
#  ##  ######  ######   b   ######  ######  ##   ##########    ##    ###   f  a        ##  ##     ##    A## fb    ##     #
#  ##  ######  ######       ######  ######  ##  ###########         #####     #### ll      ##     ##     ##      t##     #
#  ##  ##b     ##               ##      ##  ##  ##########          ######   ######    ##  ##                     ##     #
#  ##  ##      ##         b     ##     l##  ## g             ##      #####   ######    ##  ##     ##     ##       ##f    #
#  ##########  ##  ##       ##  ##  ##########r   f    a    ####      ###     ####   ########     ##t    ## g     ##     #
#  ##########  ##  ##       ##  ##  ##########  f           #####                    ########     ##     ##       ## b   #
#    b     ##      ##       ##      ## g                   t ####   b       f              ########## ########## ##### ###
#          ##      ##b      ##      ##                ##      ##                           ########## ########## ##### ###
#   g      ##      ##       ##      ##          #    #### f    l   ## b  ###    l b #              ##         ##   ##   g#
##########################################################################################################################
