metadata:
  gen_time: 8.341062068939209
  timestamp: '2025-04-18T22:46:54.205577'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
####    l##          l       g#                    #              #  b   g           #     ##      a  ########         ###
######          ##     ##   r## l     #######  #######  a   a      #   #     lg #   #      ###         ######       f ####
#  ####       ######  ####  ###       #l    #  #     #                 #  #  #  #          ###    ##    ####    ##    ####
#l ######   ##############  ###       # t   ####     #          #      #   ##   #    g #   ### a ####          ####   ####
#  ######   ####  ######      ##      # #          ###      # l  #     #        #     #    ##    #####        #####    ###
#   ####     ##     ##    bb   #    b              #        #          #        #  b             #####        #####      #
#    ##    A   a                        ### #### ###          #        #        #        #        ###          ###       #
#          b          b      ##           #  ##  #           ###       #      b #       ###              ##              #
#       l ##  ##  g##  ##  ####           ###  ###            #   #    # ###### #    #   #    ##      r  ##         ##   #
##  ##  #########  ##  ##  ####                                   #                  #       ####                  ####  #
##  ##  #########           ##                 f                  #  #          l #  #      #####   t              ##### #
#        ##  ##         l  b               #    #                     #  #    #  #          ####   f f              #### #
#                      ##        b  #      #f   #    b #        #         #  #         #     ##        ##  ##        ##  #
#  ##         b   ##   ##           #                  #       ### #             g  # ###  bt         ########         r #
# ####      ##   ####        ##                                 #  #  #     g    #  #  #    r      g  ########           #
########    ##   ####        ##     ####            ####           #   #        #   #            ##    ######f   ##      #
########          ##       r###         t                                                 b     ####    ####    ####     #
## a##                 ##g  ####                            #   #    #     ##     #    #   #    #####    ##    #####    ##
#   a   t   ##        ###     #aa               t    f    t      #  #       l      #  #    ##   ######  f     ######   ###
#    a  ##  ##   ##  ##### f   g                     al      #          ########     r    ####  #######      #######  ####
#  ##   ## a     ##  #######           f       l                 ####              ####  g ###   ###### b    ###### a ####
#  ##          g       #####         l#              #                                     ##     ####  t     ####     ###
#     b                  ##       r   #  ###    ###  # bg   f  l                           #           g    r           ##
#      ##ff     ##        a              #        #                #                #              g                     #
#      ####    r##                       #        #        l        #    ######    #   g l           ####  ####          #
### a #####    ####      ##f       ##              b a ##        #     t              #  b    ###   ############   ###   #
####  ####   #######    a#### ff f     ###        ###            #               g    #   f  ##### f############ r#####  #
####   ##    #########  #####            # bt     #  a           #   #            #   #      #####   ####  ####   ##### b#
###    ##     ##  ############           ####  ####              #   ##   #  #   ##   #      #####                #####  #
###  a####         g###########            ######            #########    ####    #########  #####                #####  #
##    ######          ##  #####          ####  ####  l       #########    ####    #########  #####              f #####  #
#       ######              ### ###                      ###     #   ##   #  #   ##   #      #####              f #####  #
#         ######     b       ## #     b     a    l        l#     #   #    t       #   #      #####   ####  ####   ##### f#
# f         #####    l  ##     ## ### ###          ### ##  ##    #                    #      #####  ############  #####  #
# f ##b   g   ####   l####       #     #       l    #     #      #                    #       ###   ############   ###   #
# a ##  ##     ### a  #####     ### ### ###   a  ### ### ###        #    ######    #   g             ####  ####     a    #
#       ##     ##   lA ####    #  b#    #    b     #    #   #      #                #   bb                               #
#  g                   ###   #### ### ### # a    # ### ### ##                              #                         r  ##
#  ##                 ###    ##           #      #     a                                   ## l   ####        ####     ###
# a##      g  ##  l   ###        a      ### t  f ###             ####           g  ####    ###   ######      ######   ####
# ####      ####   a ###                #          #         #          ########          ####  #######    r #######  ####
# ######    #####    ###l   a #   ##    #   f      #   f##       # g#          f   #  # b  ##   ######        ######   ###
#  #####     ######   ###   ###                            A    #    #     ##     #    #   #    #####    ##r   #####    ##
#    ##       #####   ####  ###                    b                                            ####  f ####    #### f   #
#             ####   #####   ##t      a  #        #               g#   #        #   #            ##  t  #####  f ##      #
#    r    f  ####    ####     #          #    r   #             #  #  #          #  #  #       f      ########     b  f  #
###  ##      ####      ##    a#          b           a r       ### #                # ###           b ######## a      l  #
###  ##       ##blf                      #  t     #             #         #  #         #     ##        ##  ##       b##  #
#             ##   ##                    #        #a                  #  #    #  #      t   ####                    #### #
#f  g     ##  r    ##   b  ##  ## ### ##a#     f  # ## ### ##     #  #            #  #l     #####            b     ##### #
#     ##  ##       f   ##  ##   #f#                    t # #      #          f       #       ####             f    ####  #
###   ##               ##     t ###      a               ###  #   #    # ###### #   l#   #    ##         ##  t      ##  r#
### b          ##  f      f     ###                 b    ### ###       #        #       ###              ##              #
## f   r       ##g  g       l## # #               b     t# #  #        #        #        #        ###          ###       #
#      l              ##   ###### ### ###          ### ### ##          #        #                #####        #####      #
# f a  ##        l    ##   ####l    #  #     ##     #  #         #     #        #b    #    ##    #####        #####    ###
#    a ##       ##          ###  ## ###  ##      ###  ## ###    #      #   ##   #      #   ###   ####          ####b  ####
#     ####     #####         ## t#    #  #        #  #    #     g      #  #  # g#          ###    ##   r####    ##    ####
#     ####     #####   ##      ## ### ### ###  ##  ### ### ##      #   #        #   #      ###         ######         ####
#    a ####t    ###   ###               #  #   a#  # ta    f      #     f            #     ##         ########        f###
#           l              l                ###  ###         #              # #            f ##      f g   #####         #
#    c    l    r                           ####   ##         #  g           # #                            #####    ##   #
#                   c            ##         ##            ## #              # #             g     t ##       ##    ####  #
#        c    ####              ####                 A   ################A  # #            #a  ##   ##   a a        ##   #
#             #### c            ####       f    t ##  r   ###           #   # #            ##  ## t           f        A #
#  #    l                 lr#     #               ##     t  #           #   # #            #    f       ##               #
# r##          c           ##                    ####                   #   ###         #### f        r#####r    ##      #
#  ##t                     ##  #               g ####   ##      b       #             g   # f   ##      ####    ####    f#
# ##          t     l       ## #     t             #    ##              #l              # #     ##    a   #      ##      #
#                 gg              ##     #   ##        ####        r    #               # #    a              ff  g      #
##        c          l  c     #   ##   ####  ##     l  ####             #    g          ###   a       ## l   ##          #
###          ##  ##          ###       ####    t         #              #                 #  ##f    #####    ##        t##
####    ##            ##    ####        ## t             g              #               # #######g t####            t ####
#c###   ##            ##   ###          ##    ##    ## t                #               ##########   #                ####
#r  ##   # f r      t #   ##tc    ##      t   ##rt#####     #           #                  ##g ##g               ##    ###
#    #r         r l       #     #####             ####g                 #  g                   g           ##  b###      #
#    ##                  ##     #####              #                    #                             a    ###   ###     #
#f t ###                ###      ##           ##                        #########             ##     ##   ###    ###  l  #
#              l                             ###           ##     l             #             ## g #####  ###     #      #
# r                                          ####      t ####     g   g         #                  #####   #   r t       #
#                                ##           ##         ####             #######                   ##    a           #  #
#  #         c              #   ###     ##                ##    b  g      #                          a       g   f   #####
#  # ## t  ##      ##    ## #    ### c #####       g##           #####    #                      b      ##         A #####
#     ##    ##    ##    ##       ###    ######    #####          #   ######                a      ##    ##             # #
#   f ###  r##    ##   ###      ###       #####   #####          #                                ##       a      t      #
#     l##    ## r##    ##       ###         ##     ##            #                                          ##  ##       #
#  a         ######              #                               #               g          ##             #########     #
#             ####                    ##                ##       #             l        g # ###             ######### a###
#       f   g               f        #####              ##       #                    f   #####  f  g         ## g##   ###
#              ##     r          ##   ######     ##      r       ##                       ####                        t ##
#   #        l ##          #     ##     #### r #####             ##                       ####        b    t  t         ##
#   ##         ##         ##              #    #####   ##        #                        #####  b            ##  ##   ###
# b  ##     ##    ##   r ##                     ##     ##        #                        # ###      A      #########  ###
#         c ##    ##                                             #                          ##         A   #########     #
#  ##       ##    ##  t    ##   f ##       ##                    #  l                             a   t     ##  ##t      #
#  ##       #      # t     ##     ##       ##                    #                                ##  g         g r      #
# ##                        ##                       t   ##      #   ######                       ##    ##             # #
###             r    g       ##                          ##      #####    #                             ##           #####
###          a               ##         ##  ##   a  ##                    #  c                                       #####
# ##                  t     ##        #########   ##### t       l         #######              ft   ##  a             #  #
# ##        r b         cb  ##        ########   b#####     # g                 #                  ##### a #             #
# ##f    c    g   b         ## #  f    ##  #       ##    f  #                   #    a        ##   #####  ###     #      #
# ##            b    b      ## ###                                      #########             ##     ##   ###    ###     #
# ##    c                   ## ###             c         # r            #                                  ###   ###   t #
# ##   ##              ##   ##  ###    #               g####            #                  b          b    ## f ###     a#
#  ##                      ## c ###  ####   ##   r ##   #####           #        g         ##  ##                ## a a###
#   ###                  ###     #   ####  ##### A####    ##            #               # ########   #                ####
#     ##    ##    ##    ##   c        ##    ####  ####      g    g      #               # #######   #### a            ####
# t          ##  ##                           #    ## t                 #               # #  ##     #####    ##    a    ##
#    #  b  r            t #     r     f                   ##            #               ###       l  b##     ##     a f  #
#  c ##     #      #   t ##    ##     ##                  ##            #                 #                 l  b         #
#     #     #      #     #     ###   #####         ##                   #               # #     ##        #      ##     b#
#     ##                ##     ###   #####       #####                  #               # #     ##      #### f  #### g   #
#     ###   t          ###      #      ##   f    #####      f           #   # #         ####          a#####     ##  t   #
#r f c ####       c  ####                    #    ##                    #   # #     c      ##    ag  l  ##               #
#         ##  t     ##                     ####         ##              #   # #            ##  ##a        t              #
#          #      r #                      ####         ##   ############  f# #            #b a##   ##        a     ##   #
#      #   ##      ## f #      ##           #r     ##        #              # #             a       ##       ##    ####  #
# b    ##   ##    ##   ##      ####                ##       ##              # #                           g#####    ##  l#
#  ##  ##    ##  ##    ##  ##  ####   ##              r      #     l        # #              ##            #####         #
##########################################################################################################################
