metadata:
  gen_time: 9.74773383140564
  timestamp: '2025-04-18T22:52:53.854362'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
####   #   #         ### ## #       ####   ##          t                                               g                 #
###### # ### # #  # # ## ##   ###   ####           ##                         b              ####    f             ####  #
##           #  # # # ##  ### ####   ##           ###   t ##                          a r  l #  #                  #  #  #
### ########## ####   ### #######          g      ####  #####                  r             #  #           c      # r#  #
###   ##            ##### ##  # r   l    ##  ##    ##   #######                            l #  #######      #######  #  #
### # ## ####   ###### ##           t  #########         # r###                 r            #        #      #        # r#
#  ##      ## # ####       #  # #      #########                                             #       t#  f   #        #  #
#         ##  ###       ## ########     ##  ##                                               #        #      #   l    #  #
# #### ## ##   ###### #### ########        f              ##       f                  g  f ###        # l    #        ####
###    ##  ##### ##   #### ##  g##        b          ##  ###                                         t########           #
### ##### ###### ## ####   ##        ##             t##   ###                        a                       l        b  #
# c#         #   ## #b## # ####     #####        b        ###                                                       b    #
# ##### #### ##   #   cf # ### g     ######    ##          #                               g            bA g             #
#     #  #  c## #######    #   b      g####  #####   ##      ##############################                    f         #
##### # ## ####       # ## # ##          #   #####   ##      #                             ###       f                ####
###           ####### # #    ##                #           ###                         a     #                        #  #
### #####   # ##  #   ######### ## b     l               #####                               #   c                    #  #
###   ### ### ## ## #### ##     ###   ##   ##            #####                               ## ##    l          f## ##  #
### # ##   ##            ## ## #### f ##  ###    ##       ## #                                   #                #      #
#   # ##   ## #      ######c###            ###   ##          #                             c     #        c       #      #
#   # ##   ## #a     ###### ### ##         ###   ##    b     #                                   #        r  b    #b     #
### # ##   ##            ## ## ####  r##  ###    ##       ## #       f                           #       t        #   r  #
###   ### ### ## ## #### ##    ####   ##   ##      a    b#######   b                    r        #                #      #
### #####   # ##  #   ##### ### ##            A          #######              t                  #       t        #      #
###           ## #### # #    ##      t         #  a      b ##               f           ct       #         g      #      #
##### # ##c####   c   # ## # ##   g      #   #####   ##           A                              #####        #####      #
#     #  #   ## #######    #           ####  #####   ##                                           f  #        #          #
# ##### #### ##   #      # ###gr     ######    ##          #                                         #        #          #
#            #   ## # ## # ####     #####  c    b         ###             c                     f    #b  ##   #          #
### ##### ## ### ## ####   ## #   t  ##     r      r ##c  ###   a                                    #   ##   #          #
### #  ##  # ### ##   #######   ##  t                ##  ###      #########################          #   ##   #         g#
# #### ## ##   ######r#### ########f                      ##      ##   ##  a      a   At             ## #### ##          #
#         ## ####       ## ########     ##t ##    b          #######   ##                                                #
#  ##      #### ####       #b # # l    ######### b    l                ##                 f        b      f        r     #
##  # ## ####   ###### ##              #########         #  #t         ##         c                                      #
###   ##            ##### ##  #          ##  ##    ##   #####          ####################             # ##b    t       #
### ########## ## #   ###########                 ####  #####                                          A#  #     f       #
##           #  # # # ## ####b####   ##           ###     ##                       r t        b        b#  #             #
###### # ### # ## # # ## ##   ### b ####           ##                    a           a     ##           #  #       b   ###
####   #   #     # # ### ##c# #     ####   ##          t  f     f                   f       #   t       ####           # #
#   ##   ##  g##   #       ##         ################r     g         #### ##        b       ######           g    ##    #
#            ########    #####       ##################      #      ###  # ##                ######      r f       ##    #
#            ########   #####    l  #################### l   ##### ##       ##                  ###        f     t ##    #
##    ##       #######  #####     ######################## t   ##        # ###   A ########     ### l   ##         ##    #
###   ##         #####   ##    ##########          ##########  l         ### ## ####    ##      ######  ##         ## # ##
###        ##      ##          ########    b         ########   c      ####      ##             ######  ##    r ##### # ##
#         ####           b     ########       l g    ########          ## ## ## ##            g   ############# ##### #  #
#    ##  #####      f          #######               ########     #######     ###      f          ############# ####  ####
#   #########   ## r## b       ##    #A################    ##     #####                      r  f ############# r  #######
#   #########   ##  ##g   ##  ##b                    #    l #  cr ##          ### f               ########        ########
#     ######      b       ##  #  g    #################           # r         ###     c r     r      #####       ####  ###
#       ###                     b  ##                ####       ###          b##      t              ###            # ## #
# ##     ##r   ##    f##          ##### g            #####  l   ##            ##    #######          ###          #      #
#####       f  ##   #####   ##    #####   g ####     #####    c  ###         ##f    ##  ##f t                     #    t #
#####               #####  #### t #####    ######    #####        ##     #####      ##   #    g         #######          #
####     ##          ##    ####   #####    ######    #####  f   g ###    ##         ##   #         #### #######  ###     #
###      ###  ##   g         ##   #####     ####     #####b       ###    #      ######   ##        #  b #####    ###     #
#       #########                 #####      ##t     #####          ## r #     ##    ## ###    g  r#        ####         #
#       #########    ##           ####                ####   f gl    #   ## b  ##         #        #     ##    ####      #
#   ##    ##  ####  #####    f     ###       ##       ###    f  ##   ##  ###  ####                 #     ##  #    # ######
#   ##         ###########          ####################        ############     ##                #     ##  #    #r######
#        l      ##########    l             b                  ####    ##      fr ###### ##   l    #     ##    ####      #
#       f##       #######           ####################      ## ##     #     #   ##   ####        #        ####       b #
#   r lg#####      ##  ##         r               b   ##  l         l   ##    ### ##    ###        #    #####    ###     #
## l    #####           f    ##  r  ##                ##  l   ## ##     ##    ##l  ## ###          #### #######  ###  t  #
###    b  ##               #### l   ##      b         ##     ##  r###    ##   ## a     ###              #######   g      #
####              ##   ##  ####     ####################   t #     ###    #####        # ##          b          t #      #
#####             ###  ##   ###       ##################     # f   ###    ##              #          ###       r  #      #
# ###   ##  ##   ####       ### ### # r    ######  l  ## #####     ##     ##           # ##          ###       t    # ## #
# ##    ##  ##  ####         ##     #   t   ####    t  #     #    l#      ##           ###           #####      g####  # #
#               ###     ##    ##### ## bb c           ## #####     #  t   ##      ### ###    f    ########       ####### #
#                ##     ##          ##################             ## # #### c   c##l   #         #############      ### #
###              ###      r    #       g       t       g    ##  r  ####  ###   a  ## f            ############# ####  ## #
###  l   r      #####        l #    ########## #########    ### l  #  a   ### ######  l #         ############# #######  #
##      r r##   ######  ##     #   ###                ###   #      #      #    ##  ## ###       ######  ##      ##########
#    ##    ### f  ##########  ##   ###    g           ###   # #    #   ####            ###  b   ######  ##         #######
#   ####  ####      #################    b           l ###### ######   ####    ##r     #        ###     ##        r##    #
#  #####  #####       ##  ######      r        b     g  # g ####  ###g  ##    ##### ####        ###    t           ##    #
# #####  f #####            ##     #   ####### ######   #           #   ## t  ####   ###a    ######         f      ##    #
# #####l    ######        f       ######   l        ###  #          ##   ##l   ##   c##      ######    r           ##    #
#######   ##f ####   ##############  ### ##  # ####    #   ##     ###   ###f ###   ###    l   ####            #       t  #
# t  t    b          ##########l          ####  ###    # #        #########  #########  r      ###            # b l#    ##
#          A  t      ##########   #       ####  ###    # ####     #########  #########     # t ##    r        ##   ##   ##
# r  ###              #########   ###### ## c   ###    # ########   #####      #####   #####    #r            ##   #######
##  ##### b r  ####                ####     #   ########        ##### r ########   #####   ## l ## ## ####  t #    ###   #
##  ######   b######           ### ####     #       #         # l     #    ##    #       #  ## ###### ##### ###     ##   #
##   ######  ########      ##      ####     #       ###g      #       #    ##    #       #             ##    ##    l#    #
#     #####  ########     ####  #    c# b   #       ###     #   # ###   ########   #####    ## ###### ##      #  ####l   #
#      ###    ######      ####  #     #     #          l### ##### f #####      #####  r#### #####   ###       ## ###     #
#                          ##   #   ###     #        ####   #######    b  #  #   l   ######   ###             ####     # #
#               r               ### ###     ######## ####    ######       #  # a     ######    ##  g        f ###     ## #
#   ###     ##f b           a       ###     #    #   ####### ####  l ###  ####  ###    ####     #     ######  ##      ## #
#  #####   ####         ##              ##### ####        ##    # ## ###    br  ### ####   #  ###    ##   ##   ### ####  #
#  ######  #####       ####t            ###   ####        #####      ###   ##   ###      #### ##     #     #    ####     #
#   #####   ####  f    #####t   b       ###         t         #      b     ##    f       # ####      ##    ##   ###      #
#    ###     ##        ######  l          ####            c## #            ##            #            #    ##   ##       #
##    r           ##    #####          r  ####   c    b    ##       f      ##                   lf    ##   ### ##    a  r#
###           t  ####    ###            ######             #####         ######         ###  ##     ####                 #
#### g r##       #####         ######## ##             ###   ###         ######     t   ### ###     ##                 ###
##### l####   l  ######        #   #    ##c       #### ###        r  r   ######  b   b   r ####l  ###  ###             ###
#####  #####     #######       #   ###   b ###### # c  ######            ######       l    ####   ###  ###             ###
####l  ######  r  #######      #   ###     #g     #        #####f    b   ######         ###  ##     ## #               ###
###    #######     #######     #   ###     #         ## r  #####         ######   r A   ###l ##   l ####                 #
#      ########   b #######     r         c#     ### ## ####c              ##                         ##   ### ##        #
# t     #######r     ######                #     #   ## ####c #            ## l          #           t#    ##   ##       #
#  ##    #####        ####  b      #########     #  ###       #l           ##            #l## #      ##  r ##   ###      #
# ####                     b   c   #####       ###  #       l##      ###   ##   ###      #### ##     #     #    ####     #
# #####                           r#####       ###  #       #   ####b###        ### ####   #  ### r  ##   ##   ### # ##  #
# ######       b##    t          r #####      r  bll#### ## #####    ###  ####  ###    ####     #     ######  ##      #  #
# #######A     ####       #####    #####         g c   # c  #######       # b#       ######    ##           r ###     #  #
# ######## g   ####    l ###### ####   #               ###   ######       #  #   b   ######   ###             ####      ##
# #########     ##       ########    # ####              #   ####   #####      # ###   #######      # #       ## ###     #
# #########             t######   ####  b##        c     #      #####   ########   ### #    ## ###### ##         #### l  #
#  #######       t        ##### l #### c ##   ######   ###    #       #    ##    #   l g #   gl        ##    ##     #t   #
#         l                 tl       ### ##   ######   ###   l#      b#   r##    #       #  ## ###### #####t###     ##   #
#  b           a   l               #   g    ###    #   b        #####   # ######   ### #l  ##  f## ## ####    #    ###   #
#            r  g                 g#        ###    #  ###    ####   # ###      # ###   #####t   #             ##   #### ##
# #############################    #     c  ### ##    ###         ### #####  ### #####     #   ##             ##   ##   ##
####################################      ###    ####   #   #     ### #####  ### #####         ###            #  t #    ##
#################################     ###    r##    ####### #     ###   ###  ###   ###        ####            #    #r    #
##########################################################################################################################
