metadata:
  gen_time: 5.214750051498413
  timestamp: '2025-04-18T22:58:40.943854'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#            ###  ###  ###         ########   ##   bb b#          f##   ######## # ##  g#  ###   #     ### #### #### ### #
#       l    ###  ###  ###                                                                                               #
######  ########  ###  ###  #######                                                                              ##   ####
######  ########  ###  ### l#######      ##g  ##       #   # g     ##   ##l     #  #  ###    ########  ##   ##   ##   ####
######  ########  ###f ###  #######                                                              ###   ### ###   ### ### #
#       ###  ###                     t b                                                     #   # #   ### ###   ### ### #
#       ###  ###                                                                                ## ##f ##   ### ###   ## #
######  ###  #############  ###         ################# #################     #    #    #   #    l  ###  g### ###   #  #
######  ### f#############l ###        b############## ##### ##############     ##################### #### ### g ##   # ##
######  ###  #############  ###                                                                         ##f###   ##   # ##
#       f         ###t ###  ###    # #####    ##       ## ##       ##     ####  ## ##### ############       ##   ## t #  #
#r                ###  ###  ###    # ##### bl ##       ## ##       ##      ####        # #  ###  ###   ##   ##   ##   #  #
###########  ########  ###  ########    #     # l   b  #   #        #          #  # #  # #  # #  # #   ### ###   ### ## ##
###########  ########  ###  ########    #     #  b  g  #   #        #     #    #  # #  # #  # #  # # r#### #### #### ## ##
###########  ########  ###  ##############    ##       ##t##       ##    ########## #### #    # g  #  ###   ### ###   #  #
#                                  #######    ##       ## ##      t##    ######  #   #   #   ##   ##   ######## #### ##  #
#            l                                                                                   ###   #######  #### ##  #
################  #############                                                               #  # ##  #######  #### ##  #
################  #############  g      ################# #################    t  # #  # #  # #  # ##  #######  #### ##  #
################  #############                                                                  # ##  ####l      b# ##  #
#               b           ###   l                                                                  ######       t# ## ##
#                        rt ###   b      ##   ##       ## ##       ##   ##        # #  # #  # #  # # ######     r  # ## ##
#            f              ### b        ## g ##b        t #       ##   ##      ### #### #### #### ##  l      #    b     #
#        r                  ###  b g                                                           #              #          #
#                   fbb     ###                                                             #########   g     #       a a#
#                           ###    ########   ##       # g #       ##   ########         ##      ##      ba   #    g     #
#       l ###         ###                 ##g #######c       #   #     #      ################ ######         #       a  #
# ########### ####### ### ####### ###  #                                                         #    ######### #### ## t#
#r########### ####### ### ####### ###  #  ###       ######  ##   b####  r #  #                     a  ######### #### ## f#
# ########### ####### ### ####### ###  #  ##   ##  ### #####     ### ###  #  #       #      g  #      ######### #### ##  #
#                 ###     ###     ###     ###  ###b##     ##     ##               #   #   r   #   #   ######### #### ##  #
# ########### ####### ########### ###  f  ##  ###  ##  ##  ##t ##        #   b   ###    c        ###  ######### #### ##  #
# ########### ####### ########### ###f    ## f ##   ## #   #####      ## #   ##   #    c          #   ######### #### ##  #
# ########### ####### ########### ###  #       ###  ##    ### ##      #  ##      l                     lr     #          #
#r###             ###     ###     ###  #  f  ##  #   ##t ###   ##   ##      ###        #  #  #           a    #          #
# ###             ###     ###   c ###   ##           ##   ## l ##   ##        #   #    #     #   A#     b     #          #
# ###             ###   r ###     ###    #  ##  ###   ##  #t               ##     #    #     #   r#         g #          #
# ########### ####### ########### ###f  ###       #   ##  #   ##    b##   ######    r  # b#  #                #      l   #
# ########### ####### ########### ### t###     ##    ###      #     ####  #  ###               t     ######        # ## ##
# ###########t####### ###########t###  ##     ###### ##      ###  ##  ####    #   #b              #  ######        # ## ##
#                 ###     ###     ###  ##   f###l  # ##   #  ##   #     ##    ## ###             ###   ####t     a # ##  #
# ########### ####### ### ####### ###  #   # ##      ###  # t #  ###         ###  #   #       #   #    #######  #### ##  #
# ########### ####### ### ####### ###   f  #  #       ##      #  ##  r ##    ##      #      b  #       #######  #### ##  #
# ########### ####### ### ####### ###f   ##      ##  ###          #    ####  ###     t             l   #######  #### ##  #
#         ###         ###               ###f ###                  #  ##  ####r #   #             #     ######## #### ##  #
# ##    t  ##    ##      # # # #     # #r#     #g#  ## ## # # #  f# #    b# ## ######## ## #     # #   #g# # ## ##    #  #
# ## ##### ##### #####   # # # #  r  # # # # # # #b ## ## #b# ##### # ##### ## ######## ## ####### ##### # # ## ##t   # ##
# ## ##### ##### #####   # # # #     # # # # # # ## ## ## # #               ##     t    ##             f # # ## ###   # ##
#    ##    ff       ##   # # # #    g# # # # # #       ## # #########  ########## ## ########## ######## # # ## b     # ##
####g##### ## ##### ##   # # # #  a  # # # # # # ## ##### #                                     f          # ## ##    # ##
#### ##### ## #####r## r # # # #     # # # #   # ## #####b#### ###### ### ## ############ ## ##### ####  ### ## ##    #  #
#             ##A##      # # # #     # # # # # # ##f##                l   c              t      g      b        ##    # ##
# ########r##### ## #### # #g# # f r # # # # # #    ## ############## ########## #### ###### ###   ##### ####   ##    # ##
#f######## ##### ## ####                  a  # ####### ##b       ##           fc         r         ##        #  ###   # ##
#g##                ##           # #tf       #         ##        ##                       t        ##  t     ##         ##
# ## ######## ## #####           # #         ############# ########## ##### ############## # ####  ## ## ###### ###   # ##
# ## ######## ## #####       r tr# #   f             g                    t              c g    f                        #
#    ##       ## ## ## f t  f    # #  g       ##### ### ## #### ## ## ##l#########  ###### #  ###   #  # #####  ##    #  #
####### ## ## ## ## ##           #t#       a  #                r            c                                            #
####### ## ## ## ## ##    g     a             # ##########  ######### ###### ############  # ####  # ### ## ### ###      #
#       f  ##   r##     ########     ##### ## # #                     ###### ############  # ###     b   b  g            #
# ##### ######## ## ####                 f ft # #           g         ## t         b          ##                         #
# ##### ######## ## ############    b########f# #                     ##              t       ##    A                   l#
# ## ##    ## ##             b    a          t# #                     ##               b      ##         b               #
#### ## ##### ##### ############     ######## # # b                   ##     t      g b  l    ##                         #
#### ## ##### #####f####         br       t   # #            t   c    ##      t        f      ##                         #
#      f##      g  t##     b     ###        l # #                     ##       f              ##      tf    b t          #
#g####  ## ###### ####t                a      # #             t  t    ##### ### ###### ### # ###                         #
#r####  ## ###### ####   #t# # #     # # # #  # # f                r  ##    t                 ##                         #
#    #                     # # #     # # # #  # #                     ##  t            f      ##              c          #
# ## ## #    ###### ##   # # # #     # # # #  # #                     ##                      ##                         #
# ## ## ##    ##### ##   #f# # #     # # # #  # #         b           ## t             b      ##                         #
# ##             ## ##   # # # #     # # # #  # #                     ##                   b  ##                      b  #
#### ## ## ## ## ####### # # # #     # # # #  # #f                    ##                      ##                 c       #
####f## ## ## ## ####### # # # #     # # # #  # #   f                 ###### ############  # ###         b   t           #
#    ## ##  g ##    ##   # # # #     # # # #  # ########## ################# ############  # ####  ##### ##f### ###      #
# ##### ##### ## #####t  # # # #  g  # # # #  #  ga                       g                        t            c        #
# ##### ##### ## #####  b# # # #  a  # # # # b##### ### ####### ## ##### #########cf###### # t###   ## # #####  ##    #  #
#    ##       ## ##      # # # #     # # # #                         bt       t              tf        f    c            #
# ## ######## ##### #### # # # #     # # # # ############ # ############### ############## ######  ##### ###### ###   # ##
# ## ######## #####g#### # # # #     # # #l# #      b  ## c      ##              l       f         ##       A##         ##
# ##            l        # # # # A   #r# #A# # ####### ## g      ##    c                           ##        ## #######g##
########## ## ##### #### # # # #     # # # # # #    ## ##############f########## #### ########## ##### # ###### ##t   # ##
########## ## ##### ####            a        # # ## ##                                         A     t          ## ## # ##
#          ## ## ## ##           # #      a    # ## ##### #### ########## ## ############ ## ########## #### ##### ## #  #
####### ## ## ## #####  b        # #    r    # # ## ##### #                                                # ##### ## # ##
####    ## ## ## #####           # #         # #       ## # ########## ########## ## ########## ########## # ##       # ##
#    ## ## ##       ##           # #         # # ##### ## # #               ##          ##               # # ## ##### # ##
# ##### ## ##### ##r##           # #       c # # #  ## ## # # ##### ####### ## ######## ## # ##### # ### # # ## ##c # # ##
# ##### ## ##### ## ##           # #           # #  ## ## # #     # #     # ## ######## ## #     # #   # # # ## ##  # #  #
#   l   ##    ## ##          g   # #b      t #     ########   #####      l       lt  #############################       #
################ #######         # #         #       g b       g     ###  ##         ######## ####################  ######
################ #######         # #      g c#A             b      l ###lf##    l                l             t    ######
#    ##          ##                 t      f  l                      ###  ##             t                    t     ######
# ## ## ## ##### ## ##  ########     ########         ###  #############          t ##########                      ######
# ## ## ## ##### ## ##    f                  g        ###  #############      ###   ##########  b    r  l     l     ######
# ## ## ##t## ##    ##   #######     ####################  ############# l   g###   ########## b    ###### ######## ######
#### ##### ## ##### ####       l             ############                   A ###   ##########      ###### ######## ######
#### ##### ## ##### ############  l b########                     b           ###   ##########      ######               #
# ##    ##    ## ##     c        r                      t   r                 ###   c             ########c              #
# ##### ## ## ## ####### t       ###                       r       #####      ###        c  t    l########            ####
# ##### ## ## ## #######                     ### g############### g#####           b #########    ######        l   # ####
#          ##               c g  ###        f###  ###############  #####         r   #########    ######  t ###     #   ##
#### ######## ##########                   b ###      b   f  ###########     ##    ###########    ######   t###   #####  #
#### ######## ##########         ###   r        g            ###########     ##    ###########  ########          #####  #
#    ##          ##                     t                    ###########     ##    ###########  ########   r   g  #####  #
####### #####r## #####    l      ###         ###l            ###########     ##r   ###########b   ######    ###   #####  #
####### ##### ## #####         r       g    a###  ###############  #####             #########  l ######    ###    b######
# ##    ## ## ##  A ##           ###         ###  ###############  #####      b      #########   f######   tf   l b ######
# ## ##### ## ## #####    l a                               br    g#####      ###               f ########       gg ######
# ## ##### ## ## #####           ###          b    r  g                   l   ###                 ######## b           g #
# ## ##       ## ##       l                   g   t      t        f           ###   ##########      ######               #
# ## ##### ##### ## ####     r   ###         ############            r   b    ###   ##########     l######################
# ## ##### ##### ## ####  a  c               ############  #############      ###   ##########      ######################
# ## ##r##    ##                 ### f                ###  #############      ###   ##########             f f      ######
# ## ## ## ## ##########     r     l                  ###  #############     t    t ##########          rt          ######
# ## ## ## ## ##########         ###                         l       ###  ##                 gt t                   ######
#  t    ## ##      r                         #                       ###  ##            l             t t           ######
#       ## ##                    ###     l g #              f        ### b##         ######## ####################  ######
#       ##t##              r      b          #     ########   #####    f             #############################       #
##########################################################################################################################
