metadata:
  gen_time: 5.451585054397583
  timestamp: '2025-04-18T22:58:30.848868'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#       ###                 ###                 ###    t       #c            c #    #       # ################ #         #
#       ###                 ###                 ###                            #    # l     # #         c    # #         #
######  ###  ########  ###  ###  ########  ######## l##### l # #               Ar   ##    r #                # #    g    #
######  ###  ######## g###  ###  ########  ########  #####b  # #                c    # l    # #   r          # # g       #
######  ###  ########  ###  ###  ########  ########  #####   # #                     #      # #              # #         #
#                 ###  ###     t      ### t     ###  ###  r  # #       r       ## ####    r # #              # #         #
#  A    l         ###  ###t  l        ###       ###  ###     # # c           c              #                # #         #
######  ###  ##################  ########  ###  ###  ###f    # #   l     f                  #r      f        # #       a #
######  ###  ##################  ########  ###  ###  ###  #### ############### ## ###########   ############## # #########
###### t###  ##################  ########  ###  ###  ###                    #     #      #         #                # c ##
#b      ### t   l           ###       ###  ###       ###  ###  ##############   # # ######### # ############## # #### # ##
#       ###                 ###       ###  ###       ###     #a# f                        g # #              # #         #
#  ########  ########  ############################  ###  #### # # ##########   # # #####   # # ##############r# #### # ##
#  ########  ########  ############################  ###                  #       c           f                   #      #
#  ########  ########l ############################  ###  #### # # ######## #     # ##### ### # ############## # ## #   ##
#       ###  ###                 ### b       l               # #                            #                # #         #
#     l ###  ###         r    t  ###                                       f             g t# #     f     g  #r#         #
#       ###   ##                 ###            l                   l           c           ###              #           #
#   f     ### ###  r      ###    g      t    t       b###     gl                           l#                #f#         #
#   # ### ###g########### ### ##  ####### ####### ### ### ######     ra                     # #              # #         #
#   # ### ### ########### ###g### ####### ####### ### ### #    #      t          c          # #  c           # #c    a   #
#   # ### ### ########### ##  ### ####### ####### ### ### t   ##  #  ##  ##    ###           t   ###    ##  ##  #  ##    #
#   # ###b                    ###     ### ###     ###          # ##   #   #            #   #            #   #   ## #     #
#   # #### ## # #   #     # # ### ####### ###  ###### ####                       g  ## #   # ##                          #
#   # #### ## # #   #     # # ### ####### ###  ###### ####       #   ###                 b    Al  t        ###   # b     #
#   # #### ## # #   #     # # ### ####### ###g ###### ####   ######  #f              #  f    #        f b    #  ######   #
#     ###   g # #   #        b###                f###         #   f      g    ##     #f      #     ##               #    #
#   # #### ## # #   # # # # ########  ### ### ####### ###f                    #      ##     ##      #                    #
#   # #### ## # #   # # # # ######   b##  ### ####### ###         #       #   #   #             #   #   #       #        #
#   # #### ## # #   # # # # ###### ##     ### ####### ###      g              #      ##     ##      #                f   #
#           a # #   # b       ###  ## ### ###  g  ### ###     #               ##     #       #     ##               #    #
#   # #### ## # #   # # # # #####r### ####### ### ########   ######  #         t     #       #          l    #  ######   #
#   # #### ## # #   # # # # #####g### ####### ### ########       #   ###            f                  b   ###   #       #
#   # #### ## # #   # # # # ##### ### ####### ### ########  f                     l ## #   # ##     t       r            #
#          ## # #     # # # #     ### ###     ###              # ##   # l #            #   #       b    #   #   ## #     #
#   # #### ##   #   # # # # # ####### ####### ### ### ###     ##  #  ##  ##    ### f         gl  ###    ##  ##  # b##    #
#   # #### ##   #   # # # # # ####### ####### ### ### ### ##  ####  g####  ##     #  # r        f     # ## #   b         #
#   # #### ##   #   # # # # # ####### ####### ### ### ###                  ####   #  #   ########     # ## #     #########
#   # ###       f     t   # #             ### ###  a  ### ##  # ##   ####     #   ####                # ## #             #
#   # #### ## # #  ## # # # # ### ################### ###  #  #  #      #  #  #        g              g ##               #
#   # #### ## # #  ## # # # # ### ###################g###  #  #  #   #  #  ####  t####                  ##               #
#   # #### ## # #  ## # # # # ### ################### ### ##  ####r  ####            #                                   #
#   #              ##   r     ###     ### ###               t        f     # ##   #  ####          # ######## #   b      #
#   # #### ## # #  ## # # # ##### ### ### ### ### ####### ##  ## #   ####  #  #   #####            # #      # #          #
#   # #### ## # #  ## # # # ##### ### ### ### ### #######  #     ## ##     #  ## ###  #  #       # # #      # # #       ##
#   # #### ## # #  ## # # # ##### ### ### ### ### #######  ####  ## ##  #  #####   #  ####       #     b        #       ##
#     ###     # #  ## # #t# # ### ###t#                     t    #t  #  #      #   #             #              #A       #
#   # ###  ## # ## ## # # # # ### ### # # ### ### ### # #  ####  #  t####   #  #####  ###                                #
#   # ###  ## # ## ## # # # # ###r###   # ### ### ###   #     #  ## ###     #  ## ##  #  # #                          # ##
#   # ###f ## # ## ## # # # # ###t#    ## ### ###l      #a #  ## ##   #     ####   ####  # #         ###  ###   g     # ##
#          ##      ##         ### # #         ###     # #l #####  #                  g   # #         #      #         # ##
#     b    ##      ##   c     ### # # f       ###   g # #  #####  #     #                # #      l  #      #    g    # ##
#      r   ##      ##         ###   #        b###     # #     #####     b   ####   ####  # #         ###  ###        A# ##
#     g    #    g  ##    bt   ##   ##              t  # #  #  #  ## ##      #         #  # #                          # ##
# # #      #  # ## ## #      b        l   bf          g    ####  #   # ## b #  #####  ###                                #
# # #  ##  #  # ## ## # ### ### ####### ###    #  ### # #l       #   #    ###  #                 #              #        #
# # #  ##  #  # ## ## # ### ### #####   ### ####  ###   #  ####  #####g #  #####   #  ####       #              #       ##
# # #      #  # ## ## # ### ### ####  ##### ####       ##  #  #  ## ##  #  #          #  #       # # #g     # # #       ##
# # #      #  # ## ## # ### ###      ##     #     ###  ##  #  ####   ####  #  #   ## ##            # #      # #          #
# # #     ##f # ## ## # ### ### ###  ##c  ####### ### ####                 ####   #  ####          # ######## #          #
# # #  ## ##  # ## ## # ### ### ### ###   ####### ### ######   ###   ####         #r #                                   #
# # #  ## ##  # ## ## # ### ###g### ###   ####### ### #### #     #   #  #  ####   ####             b    ##              A#
# # #  ## ##  # ## ## # ###         ###  f###         ###  #  #  #   #                              b r ##  c            #
# # #  ## ##  # ## ## # ### ####### ###   ### ########### ##  ####   ####  #  #   ####                # ## #             #
# # #  ## ##  # ## ## # ### ####### ###   ### ###########                 t####   # r#   ########     #f## #     #########
# # #  ## ##  # ## ## # ### ####### ###   ### ########### ##  ####   ####  ##     #  #                # ## #             #
# # #  ## ##  # ## ## #   l ###      lg   b       ###       ######   ##  #########         r ##         ###  ##         ##
# # #  ## ##  # ## ## # ####### ################# ####### f  ######  ##   ########           ###       ######### r     ###
# # #  ## ##  # ## ## # #######l################# #######     ###### ##   t######   b      c  ###     ###########     ####
# # #  ## ##  # ## ## # #######f################# ####### ############# #   #####    #####    ####    ###########    #####
# # #  ## ##l # ## ## # ### ### ### ###   ### ### ### ### ################# #a       #####    #####    #########  al######
# # #  ## ##  # ## ## #b### ### ### ### l ### ### ### ### ####### ###   ### #####  A### ###   ######    #######    #######
# # #  ## ## ## ## ## # ### ###  ## ###   ### ### ###  ##r      a ####l ### ###### ##     ## # ###### c  #####    ###### #
# # #  ## ## ## ## ## # ### ###b                                            ###### #  ###  # # b######    ###    ######  #
# # #  ## ## ## ## ## #     ###  b  l                                       ######## ##r## ###   ######    #    ######t  #
# # # f## ## ## ## ## # ####### ### ### lf### ### ####### ###########   ### #####  # ## ## #      ######       ######    #
# # #  ## ## ## ## ## # ####### ### ###   ### ### ####### ############  ###     l ## ## ## ####    ######     ######    ##
# # #  ## ## ## ## ## # ####### ### ###f  ### ### ####### ###          a###        #       #  #     #####b    #####     ##
# # #  ## ## ## ## ## #         ### ###  f### ###      t  ### c###  #######  ####       a            ###   b   ###    l  #
# # #  ## ## ## ## ## #########                                              ####  #  ###  #t                 g          #
# # #  ## ## ## ##f## ######### ### ####  #    ## ##          r       #### ######  #########    ## c    c        f   ##  #
# ###   ###  ###  #### ######## ### #### #    ### ##    ##  ###    ###     ######  #########   ####b                #### #
# ###   ###g ###  ####  ###     ### ###    #  ###c    ###aa      # ### ### ###### ###     ### #####                 ######
# ###    f        ####  ### ### ######    ## ####    f###    a#  # ### ### ###### #         # #####                 ######
# ###         gc  ####  ### ### ###### A  ## ####  ## ### #####    #   ### ###a##   g  f     f####  b   ### ###      #####
# ###             ####  ### ### #####     ## ###   ## ### #####    # #af   ###    # r  #      ###      #########      ####
# ###             ####      ###    g  b    g      ###     ###    ### ##    ###    #  #####  ####       #########   f   ###
# ###             #### #### ### ############ #  #f### ####### # l### ###                 lf   ##    ########      ########
# ### rl      t   #### #### ###l############   ## ### ######  #  ### ####a          r    t    ##g   ########      ####a f#
# ###    c     t  ####t#### ###l############  ### ### #####      ##  ####  ###  #   # ### ##  ##### ########t     ####   #
# ###    ######   ####      ###         l         ###         ##           ### ## #    #   ######## ############  ####t  #
# ### c  ######   ####  ### ####### ###       ####### ### #   ##           ### l               f  t    #########  ####   #
# ###    ######   ####  ###f####### ###     # ####### ###   c ##     ##### ####                  r     #########         #
#b###             ####f ### ####### ###     # ####### ### c ####   ####### ####       f                #########f   f    #
# ###             ####  ###     #         ### ###     ###  #####  ######## #    #     l                #########         #
# ###   ########c #### #### ###      ##g  ### ####### ##########  ########   a    #    #f  ###         #########         #
# ###   ########  ####l#### ###  ## ###   ### ####### ####### l  ########  # c ##   # ### ##           #########a r   g###
# ###   ######## c#### #### ###  ## ###r  ### ####### #######    ##a          ###              g       #########       ###
# ###   ########t ####      ###  ## ###   ### ### ###     ###a  ####         ####   c l          t     ######### ###     #
#  r                   ######## ### ###   ### ### ##########     l          ##### #  ##### ########    ######### ###     #
#          c   c f     ######## ### ###l  ### ### #########           ##    ##### #    # l  # #####    ######### ### #####
#                      #######  ### ###   ### ### ########r  # ##           #####             #####           ## ### #####
##                  f #f###     ### ###   ###b### ### ###      ###       # ###### #         # #####   a       ## g   #####
##  c              g  # ### ### ### ######### ### ### ###   ####### l   ## ###### # #     ### #####           ##     #####
#                   b   ### ### ### ######### ### ### ###  ###          #  ######   ########  ##### ############ ### #####
#                       ### ### ### ######### ### ### ##        #####      ####     ########   #### ############ ### #####
# ### ################     c    ff                              #####    f  ### #     ###  #gf ####    lr  ##### ### #####
# ### ################ g########### ######### ##########               #     ## #              ####       l##### ##  f  l#
# ### ################lf###########b######### ##########  ###l r  A         g   #          #   ####              ##  t r #
#     c            l b  ########### ######### #########   ##         ####  #   ##    ## ## ### #### ###        f ##      #
# r      f       c              ###          b###         #   ##### #####  ##bfr   # ## ## #   #### ###r         ##      #
##### ################# ########### ######### #######     t            al  ###   ### ## ## ######## ###  b       ######  #
##### ################# ########### ######### ######  ### f # ##    ##     ####  # #  ###  # ######        ##### ######  #
# g         l           ########### ######### #####   ###     ##    ##     ####  # ##     ## # ####      f ##### #       #
#           cr ac       ###     ###     b     ###   f ###  ###### ######## ####     ### ###    #### #####  ##### #       #
##### f      l     ####f####### ### ###   ### ### ###      ##f### ###      ### c     #####       ## #####  ##### #r    t #
#####b  a     b    #### ####### ### ###   ### ### ### ### ## b### c   ###            #####       ##   A##  ##### #####   #
#    c                  ####### ### ###   ### ### ### ### #   ####c  #####   r ##                ##    ##  ##### ##### a #
#               b       ###         ###   ###     f   ###    a#####  ######f   ###     g  bg #   ##t   #########  ####   #
#   ######    ######    ###         ###   ###      b  ###   ######## #######     #           #   ##rr  #########  ####   #
##########################################################################################################################
