metadata:
  gen_time: 10.292940855026245
  timestamp: '2025-04-18T22:54:23.364843'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#     ##   c      #   ###   #####   ##       ##   #     ## l#### ####         ####            ###     #         ##     g##
###   #           # #      ## # # # #  g##    #   ##  #### ##### #          g    ###        ###    ## ###  #     ##     ##
###l  ##   #        #       #     ###  ###    ##  ##                      ####     #  ####    l    ##  ##g ###  ###     ##
###   ##  ##        ###     #  g t##   #      ##            ###    c ##  ## ##     ## ##      ###  g# ##    #   # #  #  ##
##  ####   #      # ###     ##    ##   ##   # ##    ###     ##      ##   ##      # ## ## ######       ###   ##      ######
##  ##     ##   #####    #  ## t####   ##   #### #  ##      ##  #         #  ##  #  #    #######     r      #       # l  #
##          #      ## ########              ## # # t##t #       #  ##            # ####  #         #                #    #
##   ###    ###    ####   ##   ## r ##########   #  ##  #         ##   #           #     ##        #           g    ##   #
#  # ##     ###    # ###       ##    ##   ##      #  ## # ##     g##   #  ####     #      # ##       ## r ####      ##   #
#  #  ##      #   ##           ##    ##           #####   ##      #    #  ## ##    ##   ### ##       ##         r ###    #
# ##      ##      ##    ##   #  #     #     ###    ##      #   ####f  ##           ##   ### ## #     #      ###  ##  r   #
#  #   ## ###   ####  ###    #  ##    ##   t##     ##    ###     #     # #######      r     ## # #        ###     #      #
#  #   ##      ### #            ##  ###     ##  ####     ##      ### #####  ## ####  ##        # ###            ###  #  ##
#  #               ##  ###     ###        l##    ###   ####       #####     ##           #   ###  #    ##     ####   #   #
#  ##       ##     ##  ##      #            #g ###     ## #               ####  #####  ########   ###         ##    ##   #
## ##   #   ###t   ##      ##l         #      f### ######               # ## #    ###      ## ##   ###         ##   #  ###
##  # ####### #  ###       ##        # #  f    #   ## # #           ### #    ##  ##                                 g  ###
##  # ##  #      ####                #     ######  ##   #g             r###  ##   #               ##      #     g #    ###
##    ## ##             f##        ###     ## #         #     ##  ####   #  c#  ##### ######      ##      #r  c ###  ### #
#        ##    ##              ##  ##  #                ##          #   ##  ##  ##  ###        #####      ##   ####      #
#   ###  ##    ##   ###      ########  #         ##     ##  ##   ## ##  ##  #   ##    # ###   r         ###   g     r   ##
# t  ##      ####   #####     #   #   ##  a  ##  #####  ## ###   ## #           ## ## ###     #######        #  t ####   #
#    ##   ####          ##   ##   ##  #              ##### # b   ## #            ####  ## ##  ###          ###### ##    ##
#  ###    ##    ####         #     #     ##                #      # ##  ##r r          ## ##A #    ###        ###       ##
#  ####c   ##     ##               ##    ##  #######       ##    ## ##      b      ### ##          ##        ##          #
####      ###   l       ##         #      #    #f### ###    #    ##    #        ###### #   c      c##        ##   b#######
#         #             ##            ##  ###        ##     ##   ##    ##  ###  ###    #      ###   ##  g    ##      #####
##      r ##  ##  ##  ###l #    #          #         ##      #    ##  ##        ###### #           ##        ##  t #######
###       ##  ##           #    ##        ##      #####      #    ##               ### ##     g    ##        ##    r     #
# #f      ##   ##         ## ####    #    #  ##     #       ##    ##    ##             ## ##  #    ###     c  ###       ##
# ##      #          #    #  ##    ####      ##        ###   ##       #g         # ##  ## ##  ###          ###### ##    ##
# #          ##  f#########  ##    l     t  ##          l        ##   f  g      ## ## ###     #######c       #    ####   #
# ###             ##   ####   #   ####   #                   b   ##     ##g #   ##c     ###             ###     A       ##
#  #     ####   ####  ##    ###    f ##  #    ###     ##  #  #######    ##  ##  ##  ###  c     #####      ##   ####      #
#  ##   ##            ##    ##                            # #####     #  #   #  ##### ######      ##      #     ###  ### #
##   ####      #  ## #####        ###     ## # ###### #    #####   ##   ###  ##   #             g ##      #       # g  ###
###r ## ###    ##  t    ##  #       ####     #r    #         #     ##   #  b ##  ## g                                  ###
#r## #    #    #### ###    ### #      ####  ##t  ###   ###  b   ##      # ## #    ###      ## ##   ###     l  r##   #  ###
#    c      l l  #  ##     #r  ##       ##  #        #   #       #        ####  #####  ########   ###         ##    ##   #
##                  # l ##    ##      ###         g# #####    #### ###      ##       c   #   ###  #    ##     ####   #   #
#  ##   g ## ## ##     ###   ##              r     #  ##   ## ##g###   ###  ## #### l##        # ###            ###  #  ##
## ##   # ####  ##  l  #    b   #      ##l ## ######r##  ###      ## ### #######        gg  ## # #      c ###     #      #
## #  ##### ##  #     t# ## ### #    #lt## #      ## #          ###  # #   g       ##   ### ## #     #      ###  ##      #
#  t   #           ## ## ## ##       ####### ###   #    ### ##r##      #  ## ##f   ##  l### ##       ##        l  ###    #
#   l  #        t  ## ## ## ##       ####### ###   #    ### ## ##      #  ####r    #      # ##      c##   ####      ##   #
####  ##### ## g#  b   #b###### #       ## #  # b ## #          ###  # # g         #     ##        #         f      ##   #
## ##   # ####  ##     #   g  # #     g##  ## # #### ##  ###      ## ##          # ####  #        r# t r         g  ##   #
#  ##     ## ## ##     ###   ##                  # #  ##   ## ## ###    r #  ##  #  #    #######   r        #r      #    #
##                  #   ##    ##      ###     r    #######    #### ###   ##      # ## ##c######g      ###  g##      ######
#                #  ##     #   ##g      ##  #        #   #       #       ## ##     ## ##      ###   # ##    #   # #  #Ac##
# ## #    #   r#### ###    ### #    r ####  ##   ###   ###      ##        ####     #  ####   r     ##  ##  ###  ###     ##
###  ## ###l   ##       ##  # rg    ####     #     #       # #   l ##    r    r  # #        ###    ## ###  #     ##     ##
##   ####      #  ## #####        ###     ## # ###### #   t#####   ##         #### #  g       ###     #         ##      ##
## ### ### # ###     b #### ### ## # # ## ### # #                        # # ### ## # # ## ### #### t    t### # ### ### ##
#  #     #   A #          #                a  # # # # # # ###### # # # # # #                   #          #     # b   #  #
#### # # # # # ###        # ######## #b## # # #     #     #    #     #     # # # ## # ######## #  b     ### # # # # # ####
#   r            #      ### ######## # ## # # # ### # # # # ## # # # # ### # # # ## # ######## ###      #                #
## # # # # # # # #####  #      A          t # # #       b                # # #        t          #  ##### # # # # # # # ##
##   #   # #         #  # # # ## ### ###### # # # # # ### # ## # ### # # # # # ###### ### ## # # #  #   b     # #   #f  ##
#### ### # ### # ### #### # # ## ### ###### #   # #      f# ## #       # #   # ###### ### ## # # #### ### # ### # ### ####
#              #                   b l      # #l# # # # # # ## # # #A# # # # #                            #   f f        #
#### ##### ### # # # # #### ########### ### # # # # # # # #f   # # # # # # # # ### ###########b#### # # # # ### ##### ####
#            # # #                    #       #           # ## #      t    #       #                    # # # f          #
## # ##### # # # # # # # ## # ### ### ####### # #t### ### # ## # ### ### # # ####### ###l### # ## # # #g#b# # # ##### # ##
#f   #                                              #b      ##    f  #               g                g       c     #    #
## ### ### # ### # # ### ## ##### ### # ## ##c# # # ##### ###### ##### # # # ## ## # ### ##### ## ### # # ### # ### ### ##
##       # f   #       #    #  t      #       #                            #     c #         #    #    c  #     # t     ##
## # # # ### # ### # # ###### ####### # ##### # # #t### # ###### # ### # # # ##### # #######t###### # # ### # ### # # # ##
#                  t                              #     #        #     #     t      f            c          f            #
## # ### # # # #b# ### ### ##### #### # # ##### ### # # # # ## # # # # ### #####t#b# #### ##### ### ### # # # # # ### # ##
#      #   # # # # ### #              #         #           t     b      #       l #              #f### # #c#f#   #      #
## # # # # # #   #     # # # ### ###### # #c### # #l# ### # ## # ### # # # ### # # ###### ### # # #     #   # # # # # #b##
#    # # # # ### ####### # #     f                      #        #                            # # ####### ### # # # #    #
##f# # # #                 # ### # # #### # # # ### # # ### ## ### #f# ### # # # ###### # ###a#      c          # # # # ##
##       #l#t### #### ## ### ### #b#    #   #       #     # ## #    b#       #        # # ### ### ## #### ### # #   l   ##
## # # # #          f      # ### # ###### # # # ### # # ### ## ### # # ### # # # ###### # ### #   c             # # # # ##
#    # # # # ### ####### # #t    b          f           #        #       c                    #b# ####### ### # # #t#    #
## # # # # # #   #   b # # # ### ###### #f# ### # # # ### # ## # ### # # # ### # # ######l###t# # #    c#   # # # #t# # ##
#f   l #   # # # # ### #              #        b#                t       #         #              # ### #c# # # t #l     #
## # ### # # # # # ### ### #####b#### # # ##### ### # # # # ## # # #c# ### ##### # # #### ##### ### ### # # # # # ### # ##
#                        f                        #    l#        #     #            b                     t              #
## # # # ### # ### # # ###### ####### # ##### # # # ### # ###### # ### # # # ##### # ####### ###### # # ### # ### # #l# ##
##    l  #     #    t  #  f #         #       # b    f           r         # l     #   b b   #    #       #b    #       ##
## ### ### # ### # # ### ## #####b### # ## ## # # # ##### ###### ##### # #t# ## ## # ### ##### ## ### #t#l### # ### ### ##
#  b #             b                       b        #       ## c     #                 c      l                     #b   #
## # ##### # # # # # # # ## # ### ### ####### # # ### ###b# ## # ### ### # # ####### ### ### # ## # # # # # # # ##### #t##
#            # # #      t             #     b # b  t      # ## #       b   #       #     b  l           # # #            #
# ## ##### ### #l# # # #### ########### ### # # # # # # # #    # # #l# # # # # ### ####### ### #### # # # # ### ##### ####
#   t          #                 l       f  # # #c# # # # # ## #b# # # # # # #       f                   b#              #
####c### # ### # ### #### # # ## ### ###### #   # #       # ## #       # #  t# ###### ### ## # # #### ### # ### # ### ####
##  c#c  # #         #  # # # ## ### ###### #f# # # # ### # ## # ### # # # # # ###### ### ## # # #  #         # #   #   ##
## # # # # # # # #####  #                   # # #                        # # #      a r      t   #  ##### # #l# # # #c# ##
#                #      ### ######## # ## # # # ### #b# # # ## # # # # ### # # # ## # ######## ###    b #             b  #
#### # # # # # ###        # ######## #c## # # #     #     #  c #  b  #     # # #b## # ######## #   t    ### # # # # # ####
#  #     #     #      b   #          a        # # # #l# # ###### #f# # # # #                l  #          #     #        #
## ### ### # ###       ####c### ## # # ## ### # #       l             a  # # ### ## # # ## ### ####       ### # ### ###t##
#   ###                     ###    t                            ###   ###   ###          A                               #
#   ###                     ###  l                              ###   ###  l###                                          #
#   ### t      t            ### b                               ###   ###   ###    g        b                       f    #
#   ###   ###########################   ###   ###   ###############   ###   ######### f ######### g #########   ###      #
#   ###   ###########################   ###t  ###   ###############   ###   #########   #########   #########   ###      #
#   ###l  ###########################   ###   ###l  ###############   ###   #########   #########   #########   ###      #
#   ###     l                A          ###   ###   ###       t ###   ###                    l###    f    ###   ###      #
#   ###                l         g      ###   ###   ###         ###   ###                     ###  l      ###   ###      #
#   ###            l                    ###   ###   ###l        ###   ###                     ###         ###   ###      #
#   ###   #########   #######################################   ###   ###   #########  g###   ###   #########g  ##########
#   ###   #########   #######################################   ###   ### g #########   ###a  ###  a#########   ##########
#   ###   #########   #######################################   ###   ###   #########   ###   ###   #########   ##########
#     g         ### A           g            A      ###         ###               ###   ###g  ###        g###  g       l #
#         l     ###           g            r        ###     g  f###            l  ###   ###   ###         ###            #
#    l          ###           r                     ###         ###  l            ###   ###   ###     g   ###            #
#   #########   ###############   ###   ######### g #########   ###############   ###########################   ##########
#   #########   ###############   ###   #########   #########   ###############   ###########################   ##########
#   #########   ###############   ###  g#########   #########   ###############   ###########################l  ##########
#   ###     l         ###       g ###   ###                                            t            ###                  #
#   ###    t          ###         ###   ###                     l                                   ###             tlg  #
#   ###               ###         ###f  ### l    l                                        g    l    ###                  #
#   ###               ###         ###   ###                  l                           l          ###  b               #
#   ###               ###        l###   ###                                                         ###          lg      #
#   ###            l  ###         ###   ###           b                                           g ###                  #
##########################################################################################################################
