metadata:
  gen_time: 7.062870025634766
  timestamp: '2025-04-18T22:55:08.398862'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  #    r g#    #  #   #   #   # ##       #           #######    ##     ##                               g               #
#     ###       #     ##   #   #  #     a f   #####  ########  t  ##   ##     ########  #####         b                  #
#      r                   g          #      c##  ###########      #   #      ###########  ##                            #
#           ### ##     # ####### #######          ################       ################         #   ############   #   #
#          r    #      #  #  b b #            #   ###########   ##  b#   ##   ###########g  #     #   #  a   r   #t  #   #
# #r                      b         f t  l##  #   ###########   ##       ##   ###########   #l    #  t#          #   #   #
# ##        ##     ##### ## # A        #      #############   ####       ####   #############     #   # t        #   #   #
#      #      a          #  #    ##   ##   #                  ####       ####b   #       l  #     #   #          #   #   #
#   r  ##    # ### #                       #  #          #   #####   #   #####   #          #  gt #                  #   #
#  #   #  b  #  #  #                         b#  l       #  ######   #   ######  #          #     #    t f           #   #
# ###                    g   #  #   ###### #  ######     ##  ######  #  ######   #     ######     #               c  #c  #
#  r      #                #### #    #     #  # l f##     ##  #  b##f  ##   #  #      ## c  #     ####################   #
#         #  f    a  #  #       #           ###     ##     ##      ## ##      ##           ####       t                  #
###      ##   f ##   #  #   #               #        #####  ##      # #      ##  #####b       #                      t   #
#  r            # b     #  f#  ## ##   #    #    #   #####   #################   #####   #    #                          #
# #f#### #   ## #   ### #   #  #  #    # b##     ##  #####    ###############    #####  ##t    ####   #          #   #####
# #      #   #  #  A       ##  #  #           t  #  ######     #           #     ######  #            #          #       #
# #      #  t#  #     #     #     #        #     #   #####                       #####   #f   f       #    t     #       #
#        #   #     ####           #    #####     #    #  # b   b #########       #  #    #            #          # g     #
# ##  #  #   #                    #    # g       #       ##      #########      ##       #        #   ############   #   #
#  # ##      #        b                          # l     ###     #########     ###       #  t     #   #          #   #   #
#            #   ###        ########  ## #  #   ##       ##    A #########  l   ##     t ##   #   #   #r   a     #  g#   #
# r  #       #    #g         #   r    #  #  # l ##       ##l     #########      ##       ##   #   #   #          #   #   #
#    #       ##           a                      #       ###   l #########     ###       #     ####   #          #   #####
#### #b  r         f       # ##   ##### ## #t  l # l  l  ##  f   #########      ##       #                               #
#                     f ##     b  ##   ##        #b   #  #       #########     l #  #    #                             A #
#                       ##     g  ##   ##        #   #####        t              #####   #                               #
#g                      ##        ##   ##     t  # t######     #           #     ######  #        #   #          #   #   #
######   #################   #######   ##        ##  #####    ###############    #####  ##        # t #          #   #   #
######   #################   #######   ##   #    #   #####   ################# c #####   #  l #   #   #          #   #   #
#                            ##   ##        #        #####  ##        #l     ##          l    #   #  b#  t       #   #   #
#             t              ##   ##        #### f  ##     ##      ## ##g     ##     ##    ####   #   #      b   #   #   #
#      t                     ##   ##     t  l #    ##  b  ##  #   ##   ##   #  ##   t ##    #     #   #   g      #   #   #
#   ##   ############   #######   #######     ######     ##  ######  #  ######  ##     # ####     #   #          # g #  g#
#   ##   ############   ####### b #######  b  #          #  ######   #   ###### l#          #     #   #         a#   #   #
# f ##   ##                      g     ##     #          #   #####l  #   #####   #          #     #####          #####   #
#   ##   ##         f r      r         ##     #   c      #    ####       ####    #    r     #         #        g #       #
#   ##   ##  f                         ##     #############   ####       ####   #############         #a         #       #
#   ##   #################   ##   ####### b       ###########   ##       ##   ###########             #          #       #
#   ##   #################   ##   #######    c#   ###########f  ##   #   ##   ###########   #  ####   #   t      #   #####
#   ##   ##            g     ##               #   ################       #### ###########   #         #          #    r  #
#   ##   ##                  ##          r    ##  ###########   l  #   #      ###########  ##         #          #       #
#   ##   ##                 b##             f #####  ########     ##   ##     ########  #####         #          #       #
#   ##  c##                  ##                       #######    ##     ##    #######                 #          #       #
#                                   g                         t             #     ###        ##   ## t ## ### ##a ###### #
#                                      ##                               g   #     ###             ##                 g # #
#                                     #### r   g             t              ##### #c r                     ca        b   #
#       ## ###               ##      ######l     ##                             #       ##   b   c                ##   # #
#        #  #            l  ####     ######     ####                            # #     ## b        t ##  ##      ##   ###
#       #    #r             ####      ####      ####                            # ###         ## a    ##  ##  ##       ###
#        #   l#      ##      ##   r    ##        ##                c            # ###         ##              ##    c   t#
#         #    #      #     A                                                   #l#    c a            c            ## t  #
#          #    #     #            ##    f ##       ##                 l                  c        ##           a  ##    #
#           #    # #  ##    #     ####    ####     #                              #   ##  ##  ##   ##  ##     ##         #
#            #    ##A   #   ##    #####r #####    ## #    c     t                ##   ##  ##  ##       ##     ##g        #
#             #    #  #  #  ###    ##########    ### #                           ##                     b         c ##   #
#        ##  l #   #  ##########    ########    ######g                               b      la   c        t        ##   #
#         #     # ##        #####     #####    #####          t                      ##    ##    ##       ##    ##       #
#         #      # #         #####  r ####    #####                              ##f ## a  ##  r ##  ##   ##    ##       #
#         # #                 ####   ll  A    ####                              ###                  ##          c    t###
# #      f#  #                 ## l            ##                               #                      l       cc    c ###
##     f  #######  t    r           ##    ##      l                                                      b               #
#               #           #      ####  ####      #                         g  ## #### ###             ##        c      #
#        g                  ##    ############    ##     t                      #   ##  b##             ##  c            #
#   ##     l         # #    ###   ############   ###     a                          ##   ###a#### #### #### ###   ## l   #
#    #       t       ## #   ###   ############   ###                                   c      ##   ##     c  ##c  ##     #
#    #            r  #   #  ##    ############    ##            a                #   A        ##   ## l      ### #### ####
#    ##              #    # #      ##########      #                     t       #   ##  ##    t                       ###
#      #   f         ##    #        ########                                       c ##  ##         t  ##    c      r  ###
# r  #  # r                          ######                                            t       ##  ##  ##    ##        t #
#    #######                  ###     ####     ###                                             ##  ## cc     ##  ##      #
#          # l               #####l    ##     ##### ####                         r ##  ##             l          ##b ##  #
#                  l         ######      l   ###### #  #          a               a##r ##  ##        c         t t   ##  #
#  l       r                f#######    l   #######             t         A      c l       ##  ##           b            #
#          ##       r      #r#######   ##   #######    #                                       ##       ##  ##   r  c    #
#  f        #     f       #   #####   ####   #####  ####                            ##                  ##  ##          c#
#           #            #  f    l    ####                        c              #  ##              ##                   #
#           ##   #        #            ##                                 b     c# c                ##   rb      ##  ##  #
# #              ## #   l  #       f     b          #####              a  #######           r                  rc##c ##l #
###             l#  f# b      ##                ##      #                 # ta   #   r         c  b           b          #
#        ####    #    #      ####    g         ####   A #          c      #      #       ##c  ##  ##           c        l#
# ##     #  #    ##    #     #####     ##     #####     #                 #      #       ##   ##  ##   ##  b## c         #
# #              # #    #    ###### r  ##    ######  b ###    ########   #####   ## ###                ## aa##  ##  ##   #
# #                 #    # # #######        #######    ###    ##    ##   #####       ## t        c   a          ##  ##   #
# ###    ##          #    ## ########      ########    ###    ##    ##   #####       ###  ### ###       cb               #
#         #           #    # #########    ######### #  ###          ##   ##### l ##     r ##   ##lr        t            b#
# #      #a      ###  # ###  #########    ######### #  #####       g     #####   ##  b    ##   ###a### t ##        b  ## #
##       ##      ####  #####  ########    ########  #  #####  r          ########            b    c ##   ##  l        ## #
### #    ##      ###  a ###   a######      ######   #  ###############   ########     ##        l   ### #### ###a        #
####     ##      ##      #f#          r       f     #  ###############        ###a    ##                      ##         #
###a     ##      # a     r###                      ##  ###############    t   ###c               r            ###b#### ###
##       ##               ####       g            ####################        ### ##                 a##  ##a      ##   ##
#        #           g   # ###l                   ####################        ### ##  l       ##     c##  ##  c    ## f ##
# ba             a    t ##  ##                    #####      #########        ###        ##r  ## c##  b      ra##        #
# g  a          #   a  ###  ##   ### g      ###   #####      #########       g###    b   ##       ##           ##     c  #
#   b    #      ##    ####       ###        ###     ###   c  #########    t   ### ##                  ##   ##   b    ### #
#  a     ##     ###  ##### ###    ### #### ###    ###        #########        ### ##                  ##   ##        ##  #
#    c   ##     ##           ##l                 ##          ######### c      ###l### #### #### #### #### #### #### ###  #
#        ##                   ## ## ###  ### ## ##  #        ###########      ##       ## l ##   ##          c  ##       #
# l      #       #t# ## # ##   ###   ######   ###  #r      ############    r  ##   r   ##   ##   ##     g       ## l   t #
#   #           ###  ###  r# #  ##            ##  ##r g    ############ ### r ### ### #### #### #### ###f  ## c       ## #
#        #a    #####c#### #  ##  ## ######## ##  ##    ###############  ###   ### ##    l           g ##   ## tc    l ## #
### #   ###   ##### # ## ### ### ## ######## ## ###    #############   ####   ######                  ### #### ###       #
####    #### #####           ### ## #     ## ##f###    #############   ####   ###             b                 ##lc     #
#####   ###  ####          # ##  f c  #####      ###  c###########     ####   ###               c  a    c       ### ###  #
###### # # #  ## ## #  t     ##      ######      ###b  ###########     ####   ###                           b        ##  #
####                          ## ##  ##  ##  ## ##     ####################   ##### #### ###   ##    t  ##           ### #
#### #####   # #### ###    ##     ####    ####     #   ###########################   ## c ##   ##    c  ##  c    a b     #
#           #   ## #####  # ###           f g    ###   ########   ################   ##   ### #### ###                  g#
##       ##     #    ## ##    ## l  b           ##           ##f  ###############  g      r        b##           c     b #
###                          ###          f     ####              #############  #               f  ### #### ###   ##    #
####                                   ##             #########   #############  #           ##          ##   ##   ##   ##
###   # ### #     #### ### #           ##             #########   ##########        ##       ##          ##   ### #### ###
#                                                     #########         b###     #  ##  ##       ##  ##             aa   #
#               ### # ## #     ##             l##  # ##########  r    f  ###     #      ##       ##  ##t            a t  #
##        #    ####   ###c# ##### ###      ##  ### # ####                ###     #                    a     ##           #
#     # # g# ## ### #a#### #####  ###      ###  ## #  ###            ###########            b        g      ##  ##       #
## #  #   ab###  # ### ###  ##    f###    ###         ###            ###########         g       ##  ##         ##    ## #
#     #                  #   #     ##########     #  r###            ######       ##             ## c##               ## #
#                                   ########      g #####        t   ######       ##  c### ### ba       c      r         #
##########################################################################################################################
