metadata:
  gen_time: 6.493857145309448
  timestamp: '2025-04-18T22:51:56.541588'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# g           b                 ##          ##   g        b     #       ##         #       ##   #  #   ##   l            #
#                     A                    ####              ## #     ##   #       #        #   # ##   #        #       ##
#      g   r           b        ##     r             #      #### t   ####  #b#######    g t   l                 ####### ##
#               r                     ##             ##        r           ###             ###        ###b            ####
#                                     #              #                      ##  #  r   ## ## ##      ## ## ##      #  ## #
#################################                r   # ###    ####          ##c ##  r c#      #      #      #     ##  ## #
###############################                #      ### #    ##            #  ##  ## #b            f      # ##  ##     #
#       l                     g   l f    t ###  # #f      #       g         ##f #   #  #    # ##### ####r   #  #   #  ## #
#              r                               ## ##     ##          t     ##   ##  #  #    #    ##    #    #  #  ##   ###
#      r                        ###         #  ## ###    #  r           r  #    ## l#  ##   #    ##    #   ## a# g##    ##
#                                 l     #     l#   ###              ###    #    ##  #   #####    ##  f # ###  b#  ##    ##
#                                    #  ### # #b   g                 ###  ##    ##  # r ####  g  ##   g  ###   #  ## b  ##
#         r                          # ########    ###           r         #     #  ##     ##    ##    ##     ##  # l   ##
# r  g    r                      # f #g###          ###      ###    c      #     #  ##  # b##    ##    ##  #  ##  #     ##
#                                    #####         c ###g     ###      ### #    ##  #   ####     ## l   ####   #  ##  g ##
#                    f           t                             ###    ### f#    ##f #   #####    ##    #####   #  ##    ##
#                       f                            ###                   #    ##  #  ##   #    ##g   #   ##  #l ## g  ##
#                  a                        t  ### b  ###l    r###    g    ##   ##  #  #    #    ##    #    #  #  ##   ###
#            b               b   #             ##          #    ###  c#     ##  #   #  #    ############    #  #t  #  ## #
#             r                #      ###ft      ##        ##    ###  ##     #  ##  ## #                 f  # ##  ##     #
#      b             r          b     ###    ## ##         ##         ##    ##  ##     #      # l    #      #     ##  ## #
####### ################ ######  #    #f    f   ## ###  b  #          #     ##g #      ## ## ##      ## ## ##      #  ## #
####### ################ ###### ## l     f     #  ###                      ###             ###        ###             ####
#                               #      #         ###g##                   b# ####### t                          ####### ##
#                               #                   ###  g###   l          #       #       g#   ####   #  g     #    r  ##
#                       l       #      ##        # ###     ###   r c               #       ##   #  #   ##     t #        #
#                         r     #      ##   r      ##    t            t               #             ##  ##  r     #   ## #
#                               #                          ###  a f           #   ##  ##      g     #   g                #
#               l                   #               t     ff###  ###          ##g #        g                             #
#                              #    #  # a           #            ###      b             b      ##               t       #
#                    A     rb       #           a   ##      ###    ##    r                       #      g                #
#           b                       #          #    ##       ###bl  #     f  t        ##           b        f     ##     #
#                                   t l       ###   c#   #                 b           #         b                #      #
#     r   c                     #####    #     ##  #a #                      ##                                t         #
#  b      r  f                    #                   #     ###  #####  ###  #                     g               b     #
#    c l           t           #  ####                #  #    a         b         #     #               r    ##          #
#                              #  ##      #   f# l##r # l#        f              ##     ##   #               #    t      #
#                                       #     ## c    #  #  #  # #f#  #  #    t l   g       ##                 g       ###
#                                       ##    ##  ##  #  # b#  # #    #  #    #        l          #            g        ##
#          c             r   b          #     #                # #b#          ##   ##             ##                     #
#                              #  ##      #l   #       b       # #               g  #     b             ##               #
#                              #  ####         #  ###  ##  ##  # #r#  ##  #                  ## r        # t    ##       #
#                                 #            b                     r          ##         r  #   b             #        #
#                               #####    #     #  ###f ##                 f     #      ##                           ##   #
#                                             #            ###  ##  ##  ##              #        ##                  #   #
# g                 r               #        t                        r                    g     #      #    ##          #
#             A   t                 #           #  #  # #                b #                            ##   #           #
#                              #    #  #        #  #  # #  ###  ####  #### #   l       b                                 #
#                                   #                           a                          ##                           ##
#   g                           #                                            g             #        ##                   #
#                               #      ##      ###f ##  ### g######  ##  ###     ##                 #       ##           #
#                               #      ##                            g     #      #          g              #        b   #
#         r                     #           f            a                                   ##                          #
#                               # f    #         ## r# #  # #  ##  ##  ##              ##     #                   l   g  #
#             r              f  ##                   # #  # # l        b         #r    #                    g#     #  t ##
#                                #    #        r ##  # #  # #                   ##                          ##     ## b  #
#               f                    f###    ##         r # #  ##  ##  ###      b                           g            #
#       f                     r#      ###                 # #     r        ##       #                                   ##
#              r      g          # t             #  ####                    #   ##  ##  ##      bl        ##           ###
#     c                                       f  #             ###  ###  ##      #      #                  #   #         #
#     f                                             b     ###    f                              g             ##         #
#                      g                            #  #        g   t  ll           ##               g ##            r ###
#                                    #####     # #  #  #  ###  ######  # # t   ##    #           ##     # g      g     # #
#                                #   # ###     # # r                   # #      #   t    #        #           #  b t     #
#                                    # ######### #             ######  # #             b ##                  ##     f    #
#                                    #  ### #l## #  # #  #  #          # #                                      f        #
#                                      l#      # # g# #  #  #  ###### r# #           f              #           r    #b  #
#                               ###         #  gt                         f ##        t         b  ##   ##      #   ##   #
#            A             g                        b                l       #               #           #     ## l      #
#                                    l     ### #  # #  #  ###  ####  #####       #      ##   ##                          #
#                    f                            # #g #                        ##       #        #      t               #
#                           r  ##              #  g              a g                              ## f                  l#
#                                     #            ###          #######   g                     l          ##    ##      #
#                                    t##  l       ###########      ####    #  ##  t      #                  #     #      #
#                               ##         r   ###########         ####  ##  ##l   # ##### ##      b  ## #### # ##  ###  #
#     ff                                   #####    #####          ####  ##  ###  ##    ####   ##  #   ######   ## ###r  #
#                      r  f     ##f         ##       ####         r####     #######   ######l  ######   ###l#   ### ##   #
#       ############################                 #####    ######### g  ##   ######## ##   ######        #    #  ## # #
#    t  ######################## ####            c   #        #########    #        ## #  ##     ##b      ##        ## # #
#       ####        ############  ###      t             b   ##########    ######  ### ## #     ##   t #   # ##        # #
#       ####        ############  ####                       ##########    #####    #  ##     # ##  #b #   #### ##   # # #
#   ##                bf  ######   ######     f #######################    l## ###    #    t ###### ## ### #### ##  ## ###
#   ##                  f ####    r############ #############  b   ####    ### ###        #  l##  ####   #      ### ## ###
#  f##                    ####     ############    ##  ###         ####        ##   #A  #### g#  ###      ##  #  g#### r##
#   ##  b      f          ####     #########                       ####    ##   ######c  ##        ###    ## ##    ###   #
# ####     l            t ######   ########      ############    ######     ####   ##   g##    ##  r##   ### ####  ##  A #
# ####                    ######    #######    r  ###########    ######     ######      ## l ####   ##      t###    g# ###
# ####                    ######    #######    A  #####          ######        r## #  # ##   #####    ####    ##    ## ###
# ####    f               ######    #######      ####            ###### ###   ##   #### ###   ##     ##########   ###    #
# ############      f     ######    #######    #####       r     ###### ###   ####   ##   ##  ###### ###g #### g   ###  ##
# ############            ######    ######     #####  t                 ### #   ##       ### tc  ### ##    ##f   ##      #
#    #########  b                    #####     ##  #        #         r ### # #           #                 #   #####b   #
#    #########        f a            #####     #l  c          ###             b #  g          #######  #### ##  ####   # #
#           ###############           #####   g#     b        ###             c###  #  #   ## #######   ### ## ### #   ###
#           ###############l          ###########           #                   ## ## #    ##                ### #     ###
#           ###############           ###    ################       r           ## ## #    ##     ##     ### ##      #  ##
#          b####   ########tA  b  t            #######  #####  #####          # ##  ##     #    c###  r#  ##  #     ##   #
#   l       ####  f########  b     l  ##          ###          ##### f      # # ##  #      #     ###   #  ##  #     ##   #
#         t      f     ####          ###         t ##          ##           #  b## ## #    ##     ##      ##A      r # ###
# #######        r     ####          ### b         ##          ##             ll## ## ##   ##       #     ## # # # t   ###
# #######                           ###     ll cb b##c         ##rr  ## ###    ###  ## ##  ##           #   ## ### #   ###
# #####                ##           ###   a   #   c###    #######    ## ### #   #    #  #     ##   #    ### ##  ####   # #
# #####    b #######   ########    #####     a#  r #################### #     ##               ##   # #   ###   #####    #
#######      #######   ########   r#####     ##    #         ########   #a  # ####       # #          #    ##    ##      #
#######      f  ####   ########    #####     ##        l   l ######## # #   ######   ##    #      #    #  #### l  l###  ##
#######         ####     l  ###    #####     ##    t        c####     # #   ####   #### ##               ######   ###    #
####              ##        ###    ####     a##  ########    ####  ####         ## #  # ##     # #    ##      ##    ##  ##
####g             ##        ####   ####  a t ################ ###  ####     ######      ##     #    #     #b ###     #  ##
##    #########   ##        ####    ### a    #######  ####### #########     ####   ##    # gb            ### ####  ##    #
## f  #########   ##   #########    ###      #####     #####  #########     #t  ## ###cf                  ## ##    ###   #
###############  f##   #########    ###       #    c   ###   b   ##     A      ##l  #    # #              ##  ##  ####  ##
#########################  #####   a ###      #        #     f   ##         ## ### g              #            ####     ##
#######                    #####     ###      #     r     c t    ## l       ## ###             #    #    # #######  ##  ##
#######   ###############l #####     ### r    #t       g         ##         ####    #  ##       ##  # #    #### ##   #   #
#######   ###############  #####t                ############   b     f   # #####  ### ##        #    ##     ##        ###
#                                   t ###     #   ##### c    r            #    #    ## #   #           ##  # #         ###
#   b##   ###############       #    ###      #   ####      #       ### ### #   ## ####  #    ####     ll   ##   #  ## ###
#    ##   ###############     t ## #####     ##    ###              ### ### ######   g# ## #   ######   ##  ## ###  ##  ##
#l#####   ###############b      ## ######  ####    ###              ##    #  ###   #    ## #  r##  #     #      ## ###   #
#                              b##   ##########l   ##               ##    #  ##    ####### ##       t ## ###### ## ####  #
##########################################################################################################################
