metadata:
  gen_time: 5.06116509437561
  timestamp: '2025-04-18T22:54:28.507207'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##     ##                     l  ##  ####                                 ##     #   ####  ############      b  ##########
##    ####  ## t   c                A####        #          t   #      f #    t  #    ##    ##########         g##########
#     ####  ##             ##        r##   gg  b# # l            ########        #           ########    ####    #########
#      ##             ##l ###        c         #   #   a#       g   a            # t                    ######           #
#         f          #########  ##         #   #    # ## #              r   ######                      #######    b     #
##      c  ##  ##  ###############        # # #     r#r   ##################     #    #####    g        #######        ###
##    ##   ##  ##  ####  ##########    ###   #    t l        l       t       l  l#   #######  t          #####    g   ####
#   ####   f        ## c   ##  #####   ##     a                                  #   #######        ##          r b   ####
#   #####                        ###  t                          g     ###########    #####        ####               ####
##   #####    ##                  ###    ##             #        #    #                        t  ######               ###
##   ##### f  ###    ##c b  ##    ###      ############# ######## ####             g      r      A#######   ###b  f l r  #
#   #####   t#####  ####    ##   ###   ##                                    g   r       ####      ######  #####         #
#   ####     #####  ######       ###   ##                                    A## ##     ######      ####   ######r   ##  #
#     ## f  ####      ####      #####    ##########################          #  ####   ########    l       ######   #### #
#      c    ###t       ##     #######                              #     l  #    ###   #########      t     ####    ######
# ##         ##   ##t         #####    ##                           #  f    #t   ###    #########    ##              #####
######            ## tcr    g  ###     ##      #######            l  #     #     ## l    #########  ####              ## #
######         c  c   ##  ##    ##            #       #     f         #####               ########l #####       ##       #
# ##          r       ##  ##  r       r      #         #                                   ######   ######     ####      #
#       ##     ##   tc   c           f##f     # t   g #                 t     l    ##                #####     ####t   ###
#     #####  #####  f          ##     ##       #       #   ###################### ####                ###  b    ##   f####
##    #####  #####         ##  ##      r   #    #       ###                      #####l   ###        r               c####
###     ##     ##          ##             # # b  #       l              l        ####    #####                  t     ####
###                           l          #f  #    #    b           ########        t     ######  t          ##        ####
#                 t c              ##   t     #   #      ##########       f######        ######    ## r    ####f      ####
#        ##  c ##      ##    ## t######        # #      #g                        l###    #####   ####     #####   l  ####
##  ##   ###  #####   t##  ##############       #      #      a            r      #####    ###   ######    ######   b  ###
##  ##  ####  #####        ########  ####             bl# r    ## #########       ######   t     ###### f  ######  r     #
#       ###   l##           ##  ##     ### a           #     #   #f        #      ######          ####b     #### f       #
#        ##           ##  c               #############     #               #      ####                              c   #
#c ##                 ###                 #############     #l              #          g                 g               #
#####         ##     ####     ##       t #             #     #   #     l   #   a b             l          ##             #
######  ##   ###   r ###      ##                  t     #    t### #########      ##           t          ####         ## #
######  ##   ####   c ##l               #       #      #                         ### t   ##              ####        #####
# ##          ####                     ##    r # #      #                        ####   ####    ##        ##         #####
#             #####       t      ##   ###     #b  #      ##########        ###########  ####   ####            ###   #####
#       ##tb   ######     f      ##   ####   #    #                ########   t  #####  ####   #####          #####  #####
#c    ####     t ######                ## # #    #               t         g     ####    ##    l####    ###   #####   ## #
###   #####        ######   ##       r ##  #    #     t ###              t       ###            f##  t #####  #### g     #
###    ######        ####  ####  ##            #       #   ########################   b                #####   ##        #
##      #####  ##     ##   #########          #     g #    g                           ###             ####        r  ####
#a        ##   ##           ##########   a   #        a#l                             #####      ###    ##     t     #####
#   ## t            t         ########        #       #              a#####           ######    ##### b    g ##g     #####
#   ##l             t          ##  ##          #######               #     #           #####  r#######   b  ####      ####
#  c      ##  ##  t  ##        f                         b          #    r  #    ###    ### g #########     #####        #
#         ##  ## c   ##          l    l #                          #        #    ####         ##########     ####        #
##           c           f ##  ##  ## l ###########################a         #  ######         ##########     ##      t  #
##           t            ###########                g                        ## #####     l    ##########        c   c  #
#       ##  ##      f    #############                                           #####           ##########     c  ##    #
#      ########  ##   r ####  ##  ######   ############# ######## ####           ####      ###    ##########      ####   #
##     ##############  ####         #### ##             #        #    #        f ###      #####    ##########    ######r #
###      ##  #############      t    ##  l                      f l    ############       ######    ######### c  ######  #
####           ##  #######      ##      c                                            b  g  ######    ####### f    ####   #
######             fc####f      ###      #  g#                                       ###    ######  b              ##    #
# ###### f## f         ##      ######  ## #t# #      #  g ##################     #  #####    #####            ##         #
#   ##########  ##           ############  #   #    # ##b#            f     ######  ######   b### t     ##   ####       t#
#     #############       c  ####  ######      #   #    #    b                      ######             ####  #####       #
#       ##  ######## f  ##    ##    r##  a a    # #t     r       ########            ####        l rg #####  #####    ## #
#        fg   ######    ###  f c   r             #              #        #                  b         #####  #####   #####
#  ##          ######  ####     t           l                  #          ##         b           ##r   #### r#####r ######
# ###    #####  #   #####       #########  ##      ##  ##  ##  ##  ##  ##          ##  ##              ## b    ##        #
#   ########            ###   ###  ##      ##      ##  ##  ##  ##  ##  ##  g       ##  ##b            g##   b  ##        #
# #####    ###            #####            ##  ##  ##  ##  ##  ##  ##  ##  ######  ##  ## r##  ######  ## t##########    #
#            ##############               b##  ##  ##  ##  ##  ##  ##  ##  ######  ##  ##  ##  ######  ##  ##########    #
# # ###        ##    c                     l   ##  ##          ##      g    b       b    f ##      ##  ##     b##  ##    #
###   ####    l                  ##   c      b ##  ##          ##       t                  ##      ##  ##      ##  ##   f#
#    b               ll      #########   ####  ##  ##  ##  ##########  ##############  ##  ########## b######  ##  ##    #
### cl  ######       #         c     ########  ##  ##  ##  ##########  ##############  ##  ##########  ######  ##  ##    #
#   ##               #f      ### #####     ##  ##      ##  ##   b                      ##  ##          ##               l#
###     ######                     ######  ##  ##      ##  ##                        f ##  ##        g ##       f        #
# ####     ######                          ##  ##  ######  ##########  ######    ########  ##########  ##############    #
# ##########   ########       c           t##  ##  ######  ##########  ######    ######## f##########  ##############f   #
#      ##         ###r        #####          t ##  ##  ##  ##   t      ##            g   l        g##      ##            #
#        t          ### c     t         f      ##  ##  ## b## t        ##r     g     A             ##f    f##            #
#####                 #############        ##  ######  ##  ##  ########## f######  ######r ##############  ##########    #
#         #               #####      # r#  ##  ######  ##  ##  ##########  ######  ######  ##############  ##########    #
###     g #              f    #####  #  #  ##  ##  ## f t      ##          ##   g  ##      ##              ##         l  #
#       la##               ######    #    l##  ##r ##          ##          ##      ##      ##         b    ##            #
# #l      ##      #                  #     ## l##  ##  ##############  ######    ####  ##############  ##  ##  ##  ##    #
# ####    #       #   l         b    # c   ## A##  ##  ##############  ######    ####  ##############  ##  ##  ##  ##    #
###       #       #   l   # # f     c#     ##  ##       a      ##       g          ##      ##   rf ##  ##g ##  ## l##    #
#     b           #       # #    #         ##  ## f            ##    g b           ##      ##      ##  ##  ##  ##  ##   t#
#                r     g    b    #       ####f ######  ##  ##  ##  ##  ##########  ##  ######  ##  ######  ##  ###########
#c              l                #       ####  ######  ##  ##  ##  ##  ##########  ##  ######  ##  ######  ##  ###########
#  #          # #                #b            ##  ll  ##  ##  ##  ##      ##f        g    ##  ##  ##  ##  ##  ## b      #
#  #  #  b    # #     #          #             ##      ##  ##  ##  ##      ##              ##  ##  ##  ##  ##  ##        #
## #  #       # #  l  #        l #      #  ##  ######  ###### l######l ######    ########  ######  ##  ##  ##  ######    #
## #                  # g   b    ## #   #t ##  ######  ######  ######  ######   b########  ######  ##  ##  ##  ######    #
## #                 t           ## #   #g ##  ##t     ##      ## t                      b ##      ##  ##      t         #
## ##  #               g      c  ## #   #  ##  ##      ##      ##                        f ##      ##  ##             f  #
## ##c #f          ###           ## #   #  ## l## f    ##      ##                ############  ##  ##  ######  ###### b  #
## ##  # g                       ## # c #  ##  ##  t t ##      ##           g    ############  ##g ##  ######  ###### f b#
## ##     # #               g    #  # # #  ##  ###### l######  ###### t######    b           f ##  ##      ##  ##        #
#####    l# #      #            ##b # # #  ##  ######  ######  ######  ######                  ##  ##b     ##fl##        #
#   #     # #      #l   # #     ##  ### #      ##      ##  ##  ##  ##      ##    ####  ###### f##########  ##########    #
# # ## #  # # rg   #    # #     ##  ##     g   ##  b   ##  ##  ##  ##     g##    ####  ######  ##########  ##########    #
# # ## #  # #      #    #b#     #   ##   ####  ######  ##l ##  ##  ##  ##########      ##      ##  ##      l             #
# # #### l# #       f   # #     #    #   ####  ######  ##  ##  ##  ##  ##########      ##      ##  ##                   A#
# # #l#                 # #     #    #     ##  ##              ##                  ##############  ## b##########  ##    #
### # #          t             l#          ##  ##    t         ##   f              ##############  ##  ##########  ##    #
##        A           b         #          ##  ##  ##f ##############  ######                          ##    l     ##  g #
##                    ###   l   # g        ##t ##  ##  ##############  ######                 f        ##          ## g  #
##gt      g t  g     g      ##  #          ##  ##  ##          ##          ##    b ##########  ##############  ######    #
##        b               l     #          ##  ##  ##          ##          ##   g  ##########  ##############  ###### f  #
##         ##############   ##    r      b ## t######  ##  ##  ##########  ######  ##    b         ##              ## f  #
#     b            c ##          b         ##  ######  ##  ##  ##########  ######  ##              ##           t  ##    #
##                 r                 #gb      b##  ## t##  ##          ##g       ####  ##########  ##################  ###
################  c                  #    t    ##  ##  ##  ##          ##        ####  ##########  ##################  ###
#  ##          #######         # #   #     ##  ##  ######  ##########  ######              ##  ##      ##                #
#              l               # #   #     ##b ##  ######  ##########  ###### A       f f  ##  ##      ##          g g   #
#  ##            b                         ##  ##      ##  ##  b       g         ########  ##  ## f##########  ######    #
# b                                        ##  ##      ##  ##     l              ########  ##  ##  ##########  ######    #
#l ##           # #         ###########  ####  ##  ## t##  ##########  ##########  A       ##                      ## l  #
## ######       # #   c         ###      ####  ##  ## r##  ########## l##########          ##                      ##    #
##    b         # #    # #####                 ## l##          ##                  ######  ##  ##########  ######  ##    #
#               # #  ###   l                t t##  ##       b  ##                g ######  ##  ##########  ######  ##    #
#                      #######             ##l ## l## g##  ##  ##  ##  ##  ######  ##      ##   g  ##         b##  ##  f #
#       A            ###  ##               ##  ##  ##  ##  ##  ##  ##  ##  ######  ##   l  ##      ## g        ##  ##  b #
#    b       # #######                     ##      ##  ##  ##  ##  ##  ##      f  b##      ##      ##g       b ##  ##g   #
#     ########  f###           #b  l  ###  ## l    ##  ## t##  ##  ##  ##          ##      ##      ##      g   ##  ##    #
##########################################################################################################################
