metadata:
  gen_time: 5.8744049072265625
  timestamp: '2025-04-18T22:46:10.237710'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##   l##    ##    ## t  ##    ##    ##    ##    ##f   ##  t #                    a  ##   ####   ##                       #
##    ##    ##    ##    ##   r##    ##l   ##    ##    ## f  # ##  ##                ##   ####   ##             t  ##  ## #
##    ##    ##    ##   t##    ##    ##    ##    ##    ##    ############## ###A### #### ###### #### ### ###a##############
##    ##    ##    ##    ##    ##    ##r   ##    ##    ##    ############## ### ### #### ###### #### ### ### ##############
#                                         t                                                         c  r                 #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #         t                 a    r                           #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##f#                     a                                      #
#                                                                                    a           r           g         a #
#  ##    ##    ##   b##    ##    ##    ##    ##    ##    ##        t                    a        a                       #
#  ##    ##    ##    ##b   ## t  ##    ##  t ##  a ##    ##  # #### #### ### ### #### ### ## ### #### ### ### ####r#### ##
# t##  a ##    ##g   ##    ##    ##   b##    ##    ##    ## t# #### #### ### ### ####r### ## ### #### ### ### #### #### ##
# l                                                              t   ##                                   rf   ##  a     #
## ## ## ## ## ## ##t## ## ## ## ## ## ## ## ##g## ## ## ## #        ##                                        ##  a     #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #  a     ##                a  r  rt   g       a    ##        #
#          b                         l      at   b   g  l                     a  g                              g        #
##    ##a   ##    ##  b ##    ##    ##    ##    ##  f  #    #        ## a             t                t       ##        #
##    ##   b##    ##    ##    ##    ##    ##    ##    ##b   #   a    ##                                        ##      a #
##    ##    ##a   ##g   ##    ##    ##    ##    ##    ##    #        ##              f        c     aa         ##      b #
##    ##    ##    ##    ##    ##    ##    ##    ##    ##    #   f f     aa                      rat   t     f            #
##    ##    ##    ##    ##    ##a  A##    ##  b ##    ##   g#        ##                                        ##     a  #
##t   ##    ##    ##    ##    ##    ##    ##    ##   A##    #        ##        a  f                 a        g ##        #
##    ##    ##    ##    ##    ##    ##    ##    ##    ##    # r   g     l           a a  t       f                 A     #
##    ##    ##    ##    ##    ##    ##    ##    ##    ##    #  c     ##a     a                 a               ##        #
##    ##a   ##  c ##    ##    ##    ##    ##    ##    ##    #   a    #### #### ### #### ###### #### ###a#### ####        #
##    ##    ##    ##    ##    ##    ##  b ##   b##    ##    # ga     #### #### ### #### ###### #### ### #### ####    a   #
##    ##    ##    ##    ##    ##  r ##    ##    ##   a##   a#       a## r  ##       ## a     a  ##  a    ##    ##        #
##  a ##    ##    ##  a ##    ##b   ##    ##    ##    ##    #   t          ##       ##        a ## af    ##t g  t        #
##    ##    ##    ##    ##    ##    ##    ##    ##  b ##    #        ##             ##   a      ##             ##t       #
##    ##    ##    ##    ##    ##    ##    ##    ##    ##  b #rr a a  ##l a ##     g ##          ##       ##  ra##        #
##    ##    ##    ##    ##    ##    ##    ##    ##    ##    #              ##                        b  a##              #
##    ##    ##a   ##    ##    ##    ##    ##a   ##    ##    #              ##  a        g      t    a  c ## a      r a   #
## t  ##    ##    ##    ## rt ##  b ##    ##    ##    ##    #        ##    ##t      ##t   r     ##       ##    ##        #
##    ##    ##    ##    ##    ##    ##b   ##    ##  r ##    #    g   ##           a ##     r    ##        f    ##  t  a  #
##    ##  f ##    ##    ##    ##   t##    ##    ##    ##    #    l         ##       ##    g     ##       ##     a      b #
##    ## b  ##    ##    ##    ##    ## r  ##    ##    ##    #        ##    ##      a##   a      ##       ##    ##      ga#
##    ##    ##f   ##    ##    ##    ##    ##    ##    ## b  #        #### #### ### #### ###### #### ### #### ####   t   g#
##    ##    ##    ##    ##    ##    ##    ##    ##    ##    #   a    #### #### ### #### ###### #### ###r#### ####r       #
##    ##    ##    ##    ##    ##    ##    ##   a##    ##    #        ##a                        a     a a      ##       a#
##    ##    ##    ##    ##    ##    ##    ##    ##    ##    #                      c       f                          t  #
##  a ##    ##    ##    ##    ##    ##  f ##    ##    ##    #    f   ##                   b  a                 ## a g    #
##    ##    ##   r##    ##    ##    ##    ##    ##    ##    #  a     ##    a                                   ##        #
##    ## f  ##    ##    ##   f##    ##    ## b  ##    ##    #                                    f                       #
##    ##    ##    ##    ##    ##t   ## r  ##    ##    ##    #  b     ##  a              a            t         ##        #
##    ##   g##    ##    ##    ## b  ##  t ##    ##    ##    #        ##a      a         f       a              ##  a    f#
##    ##    ##   f##    ##    ##    ##    ##    ##    ##   t#a       ##      a    g           g    r           ##        #
#                                                                        g            a                a                 #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #  f    f##    a  a at a             f  aa        a##  a  ga #
#   # ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #        ##            a       a                   ##      a #
#   b                      g               c                      a  ##       r                                ##        #
#t ##b   ##    ##    ##    ##    ##   f##    ##    ##    ##  # #### #### ### ### #### ### ## ###a#### ### ### ####t#### ##
#  ##    ##    ##    ##    ##  a ##    ##    ## b  ##  b ##  # #### #### ### ### #### ### ## ### #### ### ### #### #### ##
#  ##c   ##    ##    ##    ##    ##    ##    ##    ##  t ##  f                                         g r  a a          #
#bb   b                                                                                          f                a      #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #   t    a       f      t                               t    #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##r## #        a      a   t            t  a  a       a           a #
#     f    b                         b             b                    t  la                   gt  t                  a #
##  b ##    ##    ##    ##    ##    ##    ##    ##    ##    ############## ### ### ####a###### #### ###a### ##############
##    ## f  ##    ##    ##  t ##    ##    ##    ##    ##    ############## ### ### #### ###### #### ### ### ##############
##    ##    ## A  ## af ##    ##    ##    ##    ##    ##    # ##  ##                ##   ####   ##                ##  ## #
## t  ##    ##    ##    ##    ##    ##    ##    ##    ##    #                       ##   ####   ##a       t     a        #
#      t #                    # # #   #       #             ####    #####     b#####  l           #####      #####    ####
#        # ###   ####      #    #   f    #           # t     ####t  #####      #####              #####      #####   #####
###     b#              ## #    #r   ######       ## #       #####  ######t    #####      ##      #####     ######  ######
##      ##              #  #          # t                     ####  ####### ########      ##      #####  ## ######  #### #
##   #                  #  #  ####                 #       ##  ###  ####### ########      ##      #####  ## ######       #
##  ### #   ####  ##    #  #   #           r  b ## #            ## ### l       #####      ##      #####         ##  ##   #
#       #         t#    #  #        #    #f     #  # t          b#  #  rf    b #####      ##  l   #####          #  #    #
#       #          #    #           # #### ###  #               ######         #####   ########   #####         ##  ##   #
#      ##       ## #    #       t      t        #  f        #       ###        ##### ########## # #####f       ###  ##   #
##  #           #       #        #    #  #      #  #  #  tl  #  ##f ####       ##### ########## # #####       ####  ##  ##
##  ## #       b#  ##         r  # g  ## ##     t  # ## ##   ## ##  #####      ###             A    ###      ####   ## ###
##  #  #  #     #  #          ## #    #  #         #     #   ## ##########     ###                  ###     ####    ## ###
##r #  #  #  ## #  #          #  # ## #  #    ##  ##  #      ## ##################              r  r#### ## ##   #  ## ###
##  #  #  #  #                   #    ## #    #t      # ## # ##  #################A                 #### ## ## ##   #  ###
##  ##t#        #### #      # ## #            #    # ##    # ##               ####                  ####     r r       ###
#   #  #             # #### #         A#      #   ##         #############    #####                #####     #####  ######
# t #     l  r   #   #         #    ## ####   ##  r#         #####################   ########## #  ##### ### #####  ######
#   ## ######    ##  #      ## # t                      #    ######      #    #              l         #       t     #####
#g     #         #   #      #        #  #             ###  # #####    ###  ######### ############ ###### #######     #####
##                          #  ##    ## ##  ########       # ##### ####       #####    r           #####    ######   #####
##  #                   #            #  #      #       #   #   r              #####       ##       #####       #         #
##  #       ##########  #        g          t   t      #          #   #       #####      ####      #####       #         #
## l#                     t      l          ## ##      #          #   ##      ################### ######      ##         #
#   # ##     #   #                      l      #       # ##       #    ########################## ###### ######          #
#          t ##  ####     #########                                                  a         r       #     r           #
#  ##        #   f         #      #                      #     ######  ############                ##### ######  #    #  #
## #   ##                                  l             ##  ###  #############   ############### ##   # #########     ###
#  #    # ######          ## ##          b###b  ###  #   #                                g            r      #          #
#  #       #                 #                       #   #    ####################################################  ##   #
#  #  ###                             ### #              # ##     f ####                                      ####     l #
#                    #      ## #          ##      r      #   ##     ####   #### f                      ####   ####     ###
#       g    f t ##  #  ### #  #       #      ######          ##lr  ###   ##  ########     c    ########  ##   ###    ## #
#                 b  #      #  #       #       #  #b    t   t  #######    #      t   #####l #####       b  #    ##  ###  #
# t## l   #  ### #   ## #   b  #       #        b        ####                               #              #     #       #
#  #      ## #   ##  #t #b         #   #              #             #     #                       r        #     #       #
#  #             #   #             #  t#      g   ###### #        l #     ##     ###### t      ######g  l ##  g  #       #
#  #       #         #       #                           ##         #   l  #######    ##########    #######t     #       #
#  #       ##  # ##          #   # ##### ##              #          #                                            #     bg#
#  #       #   #        ##  ##b###       #    #     ###  #       #################################################       #
#  ##      #   #  t     #l               #    # ##   #   #   ########                                        g   # # #####
#              # ###### #    #           ##   #         a        #r l    ###########              ###########         t  #
#   # ##f                   ###      ##                     tr          #############        r   ############# r b  #    #
#   #            # g    ##            #                      b   ##   l ##############  r      l##############     ##    #
#   #      ##    #      #         #  t       ###   #  f      b                                          ############   l #
#           t    #      #     ### #             l  #     l                       #######g     #######        #           #
#               f    #  #  #      #    ####        #  ##  #       ##    #        ########    ########        #    ##     #
##  #   ##   #       #  ## #      #               b#      ##     ####   #        ####################        #   ####    #
##  #        # ##### ## #  #       t    #    #     #             #####  #  t     ####################        #  #####   b#
##                      #   l    ###    #  ### ### #             ####################################################    #
##          t  #     #  ## ##              f                #                                             r  ########    #
##    #######  #    ### #  #      #    ###l#   #   ##  #                     #########          #########         ###    #
#   t  #    # ##        #         # ## #   #   ### #   ##      #####           ###   ############   ######        #####  #
#                    #            #                # t #      ######        ## ##   b                #####        ###### #
#     ## #    #      # ## ##      #    ######t                ################                       b  ################ #
#     #  # ## ##  #  #  #  #        a   #                   #                                              ############# #
#     #       #   #  #l #      a     r          t r  t       b####          #  ##############   ##########          #### #
#          #         #  #                                ## # ####       A   #     #          #  f#     #           #### #
####       # ## #### #  # ######     g#   #     #        #  # ####   l      #######  # ###########  ######          #### #
# #         l   #    #                # ####   ##  ##    #                      A                       #######     #### #
#         ##         f    #       ##             b            ####    ########     #####      #####     ########    #### #
##########################################################################################################################
