metadata:
  gen_time: 5.6582677364349365
  timestamp: '2025-04-18T22:58:13.429052'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##  ###     ##     ####       ####  #### ####g ####   ##          ##   #### l####f g    ###  ###       ###       ###   g #
##  ###             ##         ##    ##                                                                          ###     #
#    #                   r #f            ####  ####   ##b   ##    ##   ####  ####  ###  ###  ###  ########  ########     #
#g     f     ##          ####                        ####  ####  ####g  ##    ##   ###f ###  ###  ########  ########  g  #
#        g   ##     ##   ####            ####  ####   ##    ##    ##   ####  ####  ###  ###  ###  ########  ########     #
###            b    ##    ##                                                                                        t    #
###     f        l        ##      #   r # ###  ####   ##    ##    ##   ####   # #  ###                 ###    r     t    #
#        ##     ##       ####   ####   ## ##    ##   ####  ####  ####  g##  l #  #####  ########  ###  #############     #
#       ####    ###  ##   ##    ####   ######  ####f  ##    ##t   ##   ####  #########  ########  ###l #############g    #
# ##  b b##    ###   ##          ##                                              #####  ########  ###  #############     #
# ##           ###l              ##      ####  ####   ##   l##  ft##   ####  ####  ###f      ###  ###  ###  ###          #
# l   b         ###    r b               g##    ##   ####rg####  #### tf##bb g##   ###       ###  ###  ###  ###     g    #
#       ##  r   ##                       ####  ####   ##    ##r   ##  l####  ####  ##################  ###  ########     #
# ##    ###              ##  f        f                          ####   ##    ##   ##################  ###  ########     #
#####  ###  l  r         ##              ####  ####   ##    ##    ##   ####g ####f ##################  ###  ########     #
####   ###     ##               #  #                                            #            f    ###                    #
##      #      ###      l     #######                                           #                 ###       f            #
#  r         b ##    ##   ##  #######   c#   ##    ##   ####  ####   ##    ## lr######  ########  ###  ###  ##############
#          r  g  f   ##   ##   ## g#    ##  ####t #### t ## f g##   ####  ##   t######  ########  ###  ###  ##############
###     ##   b                          ##### f#  #      #    ####r   f#  #  #########g ########  ###  ###  ##############
#####  ###    ##        b                                                     ##        ###       g    ###   g      f    #
#####   ###   ##                   ##    ####   ##    ##   f##    ##    ##   ####     g ###            ###               #
#  #    ##                # b      ##                                            #####  ###  ########  ########  #########
#      ###        ##    ####      l      ####  l##    ##    ##    ##    ##  r#########  ###  ########  ########  #########
#      ####      #####  ####                                                     #####  ###  ########  ########  #########
#       ##b       ####   ##     ##l      ####   ##    ##   f##rr  ##t   ##   ####       ###  ###            ###     f l  #
#    g          g   #    b      ##     c        ###  ####  ####  ####  ####   ##        ###  ###       r  g ###       A  #
#    g     l  ##   f                  b  ####fb ##   f##    ##    ##    ##   ####  ###g #######################  #########
#  #        #####                      #  ##   ####  ####  ####  ####  ####   ##   ###  #######################  #########
# ###       #####      ##        #   ########   ##    ##    ##    ##g   ##  l####  ###  #######################  #########
# ###         #      #####     ####  ###  ##   ####  #### t####  ####  #### g ##t  ###                 ### t     ###     #
####                g####      ####   #  ####   ##    ##    ## c  ##    ## t  ###  ###   b             ###      f###     #
# ##    ##            #g        ##                                               #####  ### t#######################     #
#     ######     ##                      ####   ##    ##    ## t  ##       l #########  ###  #######################     #
#     ######   ####                                                              #####  ###  #######################     #
#      #  #    #####  ##  l  #     ##    ####  t##    ##r   ##    ##    ##   ####A      ###       fg    c         b l    #
#    f           ##   ##   ####   b##                 ###  ####  ####  ####   ##        ###                         f    #
#                c         ####  g       ####   ##  f ##    ##    ##  gr##   ####       ###                f             #
##     ##    ##         a   ##                                    ###  ####   ##    t   ###     g                        #
###   ###   ####       ##   ##  b##      ####   ##r   ##    ##  r ##    ##   ####   A  l###       f                      #
##  ####    ##########c ###   ######                                             #        ####  ##      # # # ### g ##   #
## r        ##########c ###   ######                                          ## ###  ##  ##########   #########  l #### #
##          ##########  ###        c        #    # # # # #    # # # # #         ##   b          ##  l  ############ ##   #
## t#####         t             l    t r                                      ##  ########## ##### ### ## # # ##### ######
##  #####                            ####     # c#         #  #      f c#       # ########## ##### ### ##           ######
##c #####t ####       c  #####       ####l##   ##    l l    ##           ## # ##   # #r#      # #   ##b  f  #t g##  b   t#
##  #####  #### c#####   #####     c             # # # # #    # # # # #                       #       t     b      f  ## #
##  #####  ####  #####  t#####                                                #    #      g  t     #####  #f# r        r #
#   #####  ####   c      #####                             #          #      #    f#          #    #####         # # #   #
# c #####  ####c r       #####c   ##    # ##   ## # # #     ## # # #   # ## # ##      #             ##      l  t         #
##  #####   lc         t #####    ##    # ## # ##c# # # # # ## # # # # # ## #  #                   ####  ## # #      #  ##
##  ##### r        g     #####    ## f  ##  #    # # #c#      # #         c  #      #r     #        ##            #      #
##  #####                  g                                             ##             #  f       #########             #
##  #####c   clc        c         c                  #            # # # # c        #            #  #########           ###
##  #####   ##############  ####  ######        #  c             #        # #       g   # #    r       ##       # ##     #
##  #####c  ##############  ####  ######                      # # # c   #             #         #l   #####            #  #
##  #####   ##############  ####  ######       ##           ##              #       #             #    ##         l      #
##t #####   ##############  #### c######              c  #   A      # # #             l         f    g#####  # ##        #
##  #####    c              #### c######       ## #c#   # # ##     # # #    #   c  #  #     ##l        ##              r #
##gc#####       c        f        ####### ## # ## # # # # # ##       # #    #            #      # #   ####   #           #
##  #####                   c     ####### ## # ## # # # # # ##      c# #    #      #  b     g         f#  gl     ## # #  #
##  #####c ##########r #######g   ####### ## # ## # # # # # ##     # # #    #                #  #        ## #  #   r  r  #
#   #####  ##########  #######    #######   #   c#l    #     t    #          #         #     #    f    ##      #         #
#  f#####  ##########  #######    #######      ##            #                      ##         r      ######f     t    # #
#   #####t ##########b #######    #######     #        #                            ff     # #        ###### ##        # #
#c  #####  ##########  #######    #######       #           ##                    #        b        # ##  #  ## ## ## # ##
#          ##########  #######    #######          # # #    c       #                 ##            # ## ## ###g####### ##
#     c                g       c       g                    #      #                        r         #  ##     ####    ##
#                     g             t       # #    #   #    g                                   #           #    ##     ##
#####           t    #################### ##l  ## #   #c    ##   #          #                        #       g  ##  #  ###
#####    c    t      #################### ## # ## #     #   ##       #      #     ##               #       ###          ##
#####       c               c   c        #    #t       #                                 # #  #   f       ####  ####  ####
#####  #####  t  g     t                       ##            #       #               # #  r               #      #      ##
##### c#####  ########      c       c    #  #     g    #    cc                       b  r  #    # #      #  ### ## #######
#####  #####  ########  #########            # ##           ##              #       #                  #   ##      #######
#####  #####g ########  #########        #  #c    g                                   # #            l #  # #    # # # # #
#####  #####  ########  #########  c r    ## # ##           ##                        g      #           ##    g   b     #
#####  #####  ########A #########  c     #           #c# #  c   #   #        #          #l #  A                #       # #
#####  #####  ########  #########c ####    # # ## #     #   ##      c#                                              #  # #
#    f #####  ########  ########  t####  f## # ## # #c# # # ## # #f#c#                 #     g  #     ##b  #   #b## # # ##
#   # ###             a       r  ### #              ######     #######      ##                                     ##    #
#                f                            ############ g   #######      ##### ##      ##                     r ##    #
#     #    #      f#  #       #    #      l   ############    r#######      ##### ##    f ##             l         ##    #
########  ##      ##  ##      ##  #######  l  ############   b   #####      ##### ##      ##                       ##    #
#          # ###l  #  #   ### #              r############       #####      ##### ##     b##                      l##    #
#          #              r   #l         ###  ################                r   ##      ##t                      ##    #
#  #   l   #          f       #     lf#  ###  ################  r                 ##   l  ##                       ##   t#
#  #       #   ############   #       #  ###  ######  ##########     c      ##### ##     g##    l  g               ##    #
# l#a #    #   #  #    #  # l #    #  #  ###########b ##########            ##### ##      ##  l                    ##   l#
#     #      b                     #     ###########  ##########      ########### ##      ##                     r ##    #
#     #     t         f            # g   ###########  ########    ##  ########### ##      ##  l   b      f         ##    #
###   #  #         f            #  #   ############# l   #####    ##  ########### ##      ##  g                   t##    #
#        #  #                #  #        ###########     #####    ##  #####     f ##      ##  g    g   t           ##    #
##       ## #   ##      ##   # ##       ###rlf#########  ##### c  ##  #####       ##    g ##                       ##    #
#####    #      #    f   #      #    ######   #########  ##### f f##  ##### c     ##      ##                       ##    #
#           ##  #        #  ##                ######### f c       ##  #####       ##      ##                       ##    #
# #   l      #  #        #  # a        #      #########      f r  ##l ########### ##      ##                       ##    #
# #     #       #  #  #t #       #     #  r                  #################### ##      ## f                     ##    #
###  #####      #  ####  #      #####  ##     f      f       #############        ##      ##     A                 ##    #
#           f   #        #       t     #             l r     #############        ##     f##              t  g     ##    #
# #             #        #             # ###  t     ######################        ##tA    ##                       ##    #
###  #####a  f  #  ####  #      #####  #####        ######################    t   ##      ##                   l   ##    #
# #     #       #l #  #  #    l  #     # ###     g  ######################    l c ##      ##                       ##    #
# #          #  #   g  f #  #          # ##################         tr            ##      ##                       ##    #
#           ##  #        #  ##           ##################     g             r   ##      ##                       ##    #
#####    #      #        #      #    #### r################          t  c         ##      ##t   t   g              ##    #
## r    a## #   ##      ##   # ##  f    #  ################    r                  ##      ##    r                  ##    #
#        #  #                #  #          ################b           b          ##      ##                       ## b  #
###   #  #                      #  #   ##        ##########c           l    b A   ##      ##                      g##g   #
#     #                    g       #     l       ##########  ###       r A   f    ##      ##                       ##    #
#     #        rf          f       #             ##########  ###               b  ##      ##                       ##    #
#  #  #    #  l#  #r   #  #   #    #  #          ##########            #####      ##      ##          g     t      ##    #
#  #       #  g############   # a     #       g  ##########            #####      ##      ##                       ##    #
#  #       #              g   #       #  ################## c rb      b#####      ##      ##    r   b              ##    #
#    c     #                  # f       l##################            #####      ##l   l ##          t            ##    #
#    g     # ###   #  #  g### #              ##############          f #####      ##  g                            ##    #
########  ##      ##  ##      ##  #######    ############### ########  #####  g  g##      ##  l     t              ##    #
#     #    #       #  #       #    #  g      ############### ########  ##### ###  ##  f   ##                       ##    #
#                    r       f             r ############### ########  ##### #### ##      ##                       ##    #
#   # ###                     r  ### #       ###############         t ###     l  ##      ##              f        ##    #
##########################################################################################################################
