metadata:
  gen_time: 6.5929200649261475
  timestamp: '2025-04-18T22:52:12.203676'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
################################   ####                      bb       ###      r  ##  ########l ##       #    ####    #  #
################################    ##                              # ##    #              r           #            r   f#
#   #######  #######  #######         ##  f        r       r        ##      ##            a        l  ## #      g     #  #
#    ######t  #####   ######      g   ##         b                  ##      ##                 t      ## ###      ##  ####
##                        ##   #       #                            #       ##                        ## ###      ##  ####
#######  ###  #####  ###  ###### #           b     l r             g      # # r              r         #   #            ##
#######  ###############  ###### ##           ####  #  #g ####           ##     ##      a         ##     g    ##         #
#        ###############          ##t#        t##   ####   ##         # ##     ####    ######    ####      #  ##     l  ##
#a       ###############r       # ## ##        g    ####             ## ## # b######  ########  ######   ###    g       ##
###                       ### #### # ###             ##         t   ### # ##  ###### l########  ######   ###  b         ##
##  ##   ###########  ##br###  ###    ###     ###          ###     ###    ##   ####    ######    ####    #               #
##bb   ###########   #######   #       ### g ###            ###   ###    A    lr          g                       ##     #
##   ############# ######### Ag#                    #  #gg                                               #  ##    ##     #
###  ###########   #########  ##       ###   ###    ####    ###   ###f    l    ##       f     r    ##   ##  ##        ## #
################ ###############        ###   ###   ####   ###   ###          ####     ######     ####  ##       g    ## #
##########l      # g   #########r                   #  #                 g    #####   ########   #####                   #
##### b         #           ####   ###  ###                      ###  ###      ####   ########   ####                    #
#                                # ##    ###       t    f    b  ###    ## #     ## b   ######     ##     ##   g  ##  ##  #
# ##   #######  #  #######l      ##       ###                  ###  g    ## g  l        ####g            ##      ##  ##  #
# ##  gt###### g#  ######        ##g                           r          #              ##                              #
#####   ##  ##  #  ##  ## g   ##   ##                                  ## #       ##            ##     g     ##          #
##########g  #  #  #   #########g ####                               t####       ####          ####      ##  ##  ##  ##  #
###########  #  #  # b##########                                            #    #####        #####    # ##      ##  ##  #
# #########  #######  #########                ###    g   ###               ##   ######      ######   ##            f    #
#                                      t        ###      ###               A###   ######    ######   ###     ##          #
#  ##        #######        ##                   ###    ###         t       ###    #####    #####    ### ##  ##    ##    #
#  ##      lb #####    r    ##  r  #       ###  l     g       ###       #   ###     ###      ###     ### ##        ##  ###
#  ##  ##  #  #####  #  ##  ##gf# ##        ###   r          ###        ## ###r                       ##               ###
#  ##  #####  #   #  #####r ##  # ##                ####                ##t#                    a                        #
#  ##     l                        #                 ##                 #                       l         r  ##          #
# ###      t   l r          ###               ###          ###       r        ##                    ##    l  ##          #
######  ##  ###   ###g ##  #####       ###     ###   ##   ###     ###        ####     ##    ##     ####l##       ##    b #
######  ##   ##  f##   ##  #####  f     ###     ###   r  ###     ###        #####    ####  ####    #######       ##   ## #
#####   ###  ##   ## r###   ####         ### r     t            ###   f    b#####    ####b ####    #####              ## #
##### f###################  ####  g                    r                    #####    ####  ####    #####  A      g       #
###         g   g             ##                      t           r          ####     ##    ##     ####            g     #
###f   b                              ###       r          r   b   ###        ##                    ##r ### ###   ##   ###
###  #########  # l#########  ##     #b###      ####  l ####      ##  #                     f           ##   ##   ##   ###
###  #########     #########  ##     ##          ##      ##          ##                                 ##   ### ####b####
###     #######b  #######     ###    ##                  bg          ##    ###                       g## #               #
####      l                          ##        l ##    r ##  l        #r    ###   r ###     r###   f ###                 #
######    f ######### fr   #####       ###      ####  f ####      ### #     ###    #####    #####    ### #      ##       #
###############                       ###                        r ###      ###   ######    ######   #####  ##  ##   ##  #
####                                             r               g          ##   ######      ######   ####  ##       ##r #
####    ######## ########    ###                            r               #    #####       b#####    #                 #
################################  b      ###                 f  ###  g  t  g     ####          ####    b        f        #
################################        ###     ###      ###     ###              ##            ##          f##   g      #
##########    #####   t#########       ###     ###   ##  r###     ###                    ##                  ##          #
##########                                    ###          ###                       g  #### b                           #
##########  #  ###  # g#########g g#                 ##                 #       ## l   ######     ##                  b b#
#   ##   #  #########  #   ##  g# ##                ####                ## #   ####   ######## b ####   ## #### ###   ####
#           #########      ##   # ##     t  ###              ###        ## #  #####   ########   #####  #   ##   ## f ## #
######      #########     ### ##   #A      ###  b             ###rf f   #     ####  b  ######t    ####  #  g##   ### ### #
#                                             f  ###t   ###                    ##          f       ##                    #
# ####### ### ### ###########                   ###      ###                                  l         #                #
# ####### ###g### ###########                  ###        ###                                           ###      A       #
# ####### ###                 f                              g     gg          ####    ######    ####   ###       ##   b #
#r            ###b        ###b A   ###      g                 f  t  g ####    ######  ########  ######  # l       ##     #
#                                # ##              b    r              ##     ######  ########  ######                   #
# ### ########### ####### ###r f ##                                      ##t   ####    ######    ####   #   ##           #
# ### ########### ####### ###  b #        ###      g           ###        #     ## l              ##    #   ##  ##    ## #
#t###   t b   ### ###t    ###    # ##    ###                    ###   A## # #                          #        ##    ## #
# ####### ### ### ##############  ####  ###           g          ###  ####  ##  t         r        r  ###                #
# #######     ### ##############                    # r#  lb             b  ##                 g     b###             b  #
# ##########      ##############    g   ###   ###   ####   ###   ###        ##            f   f fA    ###     a ##      ##
#                         ###          ###   ###    ####    ###   ### r     #          f    l          #    ##  ##  ##  ##
# ### ### ### ### ####### ### r        rb           #  #             f      g     ##  ########  ## g   r    ##      ##   #
# ###b### ### ### ####### ###          ###   ###          g ###   ###       #      ##        ####  #    t ##    ## #### ##
# ### ### ### ### ####### ###   ###   ###f    ###          ###     ###    ##        ##        ##   #r    ##    ##  t   ###
# ### ### ### ###   r      tf l ##   ###   t         ##           b ### # ###      t ##########    ##   ##    ##      ## #
##### ####### ### ####### ######  ## ##  r          ####             ## ## ###       #########b     ##  #  t  #   t      #
##### ####### ### ####### ###### ### #         ##   ####   ##         # ##   ## ### ##       ### #####  #     #       #  #
##### #######  ##  ###### ###### ##   g       ####  #  #  ####      t    ##    g   gt       ####  a r  ##     ##      ## #
#                             r  #               r    r g              r  #             #####gr##    ##        ##      ###
# ### ####### ####### #######          #    g                   t   #  f       ##########       ##l  #  ########## #######
# ###t####### ####### #######         ##                     b      ##       ###          b      ##  #  ##               #
# ### ####### ####### #######         ##   c    b                   ##     r                      ## #   ##              #
# ### ### ###     ### ### ###       ##            t         l       #  #          l                ###    ##      g      #
##### ### ####### ####### ###      ####                              ####   #   ###### ######r b    ##     ##            #
##### ### ####### ####### ###              #  # c##    #c   c   #   ######  #  ##     b     ##g      ##     # ### #  ## ##
##### ### ####### ####### ###         ######  #  b  l  #######  #   #       #  #           #### ############# ### #     f#
#                                  g  #  t    #              #  #   #    t  #  #          ##                        #    #
######### #######  ###### ######## c  #   f   # ##        #     #   #     # # ##      #######                     r ### ##
######### #######  ###### ######   cf #     b #  # l     l#######f  ####  #  ##      ##  g  #      f ######## ### ##### ##
######### #######  ###### ######c#    #       #  #   t    t            #  # ##       #        b     ##            b      #
#             g       ###c       #c   ######  #  #              l      #  # #        #   f  #    ####    f               #
##### ########### ###########    #    c    #  #  #             t  ######c ###    f  g##   t ######                ##### ##
##### ###########b###########    #         #  #  ######     ####  #cc     c #         ##    g##          ###  ###        #
##### ########### ###########    #         #  #       #    g#  #  #         # ## ########f    ##  g   ####    #          #
#     ###                 ###    #c##      ####       #    t#  # c# ##c t######         ##     ########       ##     ## ##
# ### ### ### ########### ######    #              c  #r    #  ##   l#   #A  ##          ###############      f## ####   #
# ### ### ### ########### ###### #  #b               b#  #### f  l#  #  c#    ##          ##           ##       # #####t #
# ### ### ### ########### ###### #### g ####  #########  #        ####   #   b #### #######             ##### ###     ##f#
# ###  gt ### ###     ###               #c #  #     c l  #        c      ###    ##      #### ### ############ ####f    ###
#l################### ### ######   bbt  #  #b #    t     #         f   c  c     ##     ##     l   ##        l    ##     ##
# ################### ### ########     c## #  #  l       #   c               ## ###   ##       r   ##     b  l    ##     #
# ################### ### ###### #     c   # ##          #########     b   #  ### ##  #      #########g     #########a  ##
#           r             ###    #         #                     #  b      #                                          ####
# ####### ########### #######   ##         #              c      # ##      #     # ########### ##############         r  #
# ####### ########### #######        t     #  ####       ######  #  #      #    ##                          ####         #
# ####### ########### ######      r ########  #  #            #  #  #      ##   #  f            b g  f     t   ###########
# ###            l r b       g b   f#         #c #       #  b # c#c #      ##   #  c ##    c #       ##      c       g   #
##### ### ######## # ########t      # c     tc## #g c    ######  ## # c######   #    ##      #       ##                  #
##### ### ######## # ########   #####l         c # ##            c  #       # bc#                                        #
##### ### ######## # ########   #    b           #  #b        rc    ## # f  #   #          r       c                     #
#                               #       c ####   #  #         b       r#    #   ##                                ########
# ### ### ####### ### #######   #     g      #   #  #c   r    t        #    ##r  ############       l    f        ##     #
# ### ### ###     ### #######   #   #### l# c#   # c#  #### ############     #    tc   f    ### ####################     #
# ### ### ### ### ### #######   # a #  #  #  #####  #     c            c  c  ##                            l             #
# ### ### ### ### ###r###           # c#  #ff       ## #ct      c     r       #########  r  l      ##c                   #
# ### ####### ### ####### ######    #  ####    c         l##################          #################       ############
# ###l####### ### ####### #######   #                  #  #         a            c   g                ######### l  g    ##
# ###   #####t### ####### ###########                  ## #    t                       g                                 #
#b                                         c    ####     c#  f                                           r       t      f#
#####                 ####### r l#             c#  #      ################     r r         ###########        ##         #
##### ###             #######   ##              #  # ##           f r    #  ################         ##       ##         #
##### ### ### ### ### #######                t  ## #  #                  # b                 f        ####    tb       f #
#     ### ###   a ### ###            f####         #  #     c            #                              ##  g    b       #
#  f b### ###         ###       #        #   g    c#  #             c ## #   c          f##             ####             #
#   t                 ###       #  f  #t #  c  #####  #               #  #               ##              br###           #
##########################################################################################################################
