metadata:
  gen_time: 4.372225999832153
  timestamp: '2025-04-18T22:46:21.432678'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#           r        c                        t              #   #                                        g            ###
#  # t          #   #       f   #         #                  # # #    ######              b      ###      ##          ####
#         #            l        c             c #            # # #          t                   b                     t  #
#            l                t      c f    c   c     #      # # #         g   #g  b  ################                   #
#    # t        c   c                 c                    b # # #  ####g      #  l gt                                   #
#       c         #f         c                     #     cc  # #     ##        #            t       l            f       #
#            c                              #  #             # #    ####                                     ####       g#
#                                 c                        #   # #                                g    l      ##      g  #
#   r#a      c  #    c #           f             r             # #                         ###g              ###   l     #
#                           c      l   #           #  c      # # # #                                          ##         #
#      c                          #                          # # # #                      g                  ####   ######
#       c       c       f            c                         # # #                               g                     #
#                   #     c c            #   f           f     # # #                       ####        ###################
#   A  f#                      c         tf      #              b#      b                      l                       t #
#                         l#                 t       #           #      #####                             ##########     #
#      t  r l                 r c          c                     # #                        ####  ####                g  #
##       t       # c   #    r  c c  f        #    c             t# #       #######           ##    ##       ##   #####   #
#      A     ft l                         c  t      c       #    # #                        ####  ####         g         #
#   c                                   f   c c #                # #      b     ####                                ######
#    b    #                              #      t                # #     f       ##      g                               #
#   c                              r        c       f       t    # #   ######   ###          #########  ##############  ##
#      lc     f    c#   c    #            r                      #    g          ##   ####                              l#
# #                    #            f                            #              ####   ##                          #######
#      c    t  # c                               t  #              f                  ####               ####            #
#   c             #                           #   fc      c             ##             r       g          ##             #
#                r  c                              c               b         f    t       A             l####         ####
#  c#            c        c         c                          #################################                         #
#         #                    #             t # c                         g                   g    a      ####     #### #
# f     f       c        c     f f     # l      c                ####  ####       ##########                ##       ##  #
#               l          #            f   c            c        ##    ##                          t       ###      ### #
#   c  r l                 # f                                   ####  ####           t                     ##       ##  #
#     c           t     r  f           #fc               c        l                 ####                    ###      ## l#
#         #        t           #            fcc#                            lg       ##             r      g##       ##  #
#  g# f                  c    b                                                     ####              t    g###      ##A #
# t   c  cc        c                c            c                                                      ta  ##       ### #
#      A          #                           #     c                                 #### l         g      ###  l   ##  #
#              #                         f          #                g   g             ##                   ##       ### #
# #                    #   cc                            cf         ##      ####      ####                  ##       ##  #
#                   #  c     #      c  r         l          c #              ##        ##           tt      ##       ### #
#r l         l              r         r            l    c     #        t    ####      ####                 ####      ##  #
#r        #    t                         #                    #           g                          r         l     ### #
#                 c                        g    #          t  #               ####################                   ##  #
#c        g                                                 #               b                         ##########     ##  #
## f    c        #     #   c        t        #                                          g  ####                      ##t #
#                                c t                            l         l    g            ##    t             t    ##  #
#                          # t  A                    #                #               t    ####         ####   ####  ##  #
#       #                 ra    c           t  a #       c            #                             t    ##    g     ##  #
#       c           #   c                #                            #        g             #####       ###         ##  #
#                             t                                 ####l                                 b  ##          ##  #
#   f             A          l    #  c b           t          f                 b                        ##  g      ###b #
#                   a           c      #          c#     r                                               ##          ### #
#    #         r#      #          c     c                                                      ##### g   ##        g ##  #
#   f    r      l                   f          cc          #t                                            ##          ##  #
# c r       c      c                        #  #               f     ##     g   ############      ####   ## #        ## ##
#c                #                 f              #  r                              g             ##    ## #    r   ## ##
#    #      g r               c               c              f                    ##############  ####   ##          ## ##
# c                l                                  #       t                            l             ##          ## ##
#         #       c    r                  cc    #          c          #####         l    ###########    b###         ## ##
#  #          c #   #           #        r#              f       f       g                               ##          ##  #
#            f                    l                                              # #                     ##          ##  #
# #      ##  ##   ##   ##  ##    ##  ##  ##  ##   ##  ## f## ##  #     #    #  # # #            # #      ##  # #     ##  #
# #      ##  ## # ## # ##  ##    ##  ##  ##  ## # ##  ## ###  #  #     #    #  # # #            # #      ##  # #     ##  #
# #      ##  ## # ## # ##  ##    ##  ##  ##   # # ##  ## ###                                              f              #
#         #     #    #      #         g         #  #   #     ##  #     #    #  # # #            # #      ##  # #     ##  #
# f       f  g  c           f        b       b                #  #     #    #  # # #            # #      ##  # #     ##  #
##        # r   #    #      #       #   #       #  #   #                                                       l        A#
###      ## ### #### # ##  ##    ## ### ###  ## # ##  ## ### ##  #     #    #  # # #     #      # # #    ##  # #     ##  #
###      ## ### #### # ##  ##    ## ### ###  ## # ##  ## ###  #  #     #    #  # # #     #      # # #    ##  # #     ##  #
###      ##        #   ##           #   #    #  #        #    b                          a      f l c                    #
#           b                                b        g    r  #  #     #    #  # # #     #      # # #    ##  # # #   ##  #
###      ##        #   ##        f  #   #    #  #      f #    #  #     #    #  # # #     #      # # #    ##  # # #   ##  #
###      ## ### #### # ##  ##    ## ### ###  ## # ## ### ###  g                    f            b                        #
###      ## ### #### # ##  ##    ## ### ###  ## # ## ### ### ##  #     #    #  # # #     #      # # #    ##  # # #   ##  #
#        #  ##   ##  #  g  #         ##  ##  g  #    #   ##  ##  #     #    #  # # #     #      # # #    ##  # # #   ##  #
#                    t                                                             r                     l            r  #
#        #  ##   ##  #     #         ##  ##     #    #   ##  ##  #     #    #  # # #  #  #      # # # #  ##  # # #   ##  #
###      ## ### #### # ##  ##    ## ### ###  ## # ## ### ### ##  #     #    #  # # #  #  #      # # # #  ##  # # #   ##  #
###      ## ### #### # ##  ##    ## ### ###  ## # ## ### ###                     r                             f l       #
##t      #    #   ##   #    #    ##  b  #    #    #  ##    g ##  #     #    #  # # #  #  #      # # # #  ##  # ####  ##  #
#r                                                            #  #     #    #  # # #  #  #      # # # #  ##  # ####  ##  #
##       #    #   ##   #    #    ##     #t   #    #  ##                      A        l                          tr      #
###      ## ### #### # ##  ##    ## ### ###  ## # ## ### ### ##  # #   #    #  # # #  ## #      # # # #  ##  # ####  ##  #
###      ## ### #### # ##  ##    ## ### ###  ## # ## ### ### ##  # #   #    #  # # #  ## #      # # # #  ##  # ####  ##  #
# #      a#   #    t #  #  f#    #  ##f ##      #     ##   #                                      f          r    l      #
#                                        b                 b ##  # #   #    #  # # #  ## #      # ### #  ##  # ####  ### #
#r#       #   # c    #  #  b#    #  ##  ##      #     ##   # ##  # #   #    #  # # #  ## #      # ### #  ##  # ####  ### #
###     ### ### #### # ##  ##    ## ### ###  ## # ## ### ###                                                          rb #
###     ### ### #### # ##  ##    ## ### ###  ## # ## ### ### ##  # #   #    #  # # #  ## # #    # ### #  ##  # ####  #####
###      ##   #      #     #        ##  ##f  ##   ##  ##   # ##  # #   #    #  # # #  ## # #    # ### #  ##  # ####  #####
#                 b     l                                  b                                    r                        #
#               c                t        t       l       g                        f   a                  g              #
###      ##   #    g #     #        ##  ##   ##   ## t##   #  #  # #   #    #  # # #  ## # #    # ### #  ##  # ####  #####
###     ### ### #### # ##  ##    ## ### ###  ## # ## ### ###  #  # #   #    #  # # #  ## # #    # ### #  ##  # ####  #####
###     ### ### #### # ##  ##    ## ### ###  ## # ## ###  ##       r   c       t       l r                               #
# #      b#   #  f   #  #   #    #  ##  ##      #     ##  t# ##  # #   # #  #  # # #  #### #    # ### #  ##  # #### ######
#                          f                              b   #  # #   # #  #  # # #  #### #    # ### #  ##  # #### ######
# #       #   #    r #  #   #    #  ##  ##      #     ##   #       g                                f        f    a      #
### #   ### ### #### ####  ## #  ## ### ###  ## # ## ### ### ##  # ##  # #  #  # # #  #### #    # #####  ##  #############
### #   ### ### #### ####  ## #  ## ### ###  ## # ## ### ###  #  # ##  # #  #  # # #  #### #    # #####  ##  #############
##  #   ##   g#   ##  ##    #    ##     # A  #  f #  ##                     a                                           a#
#                  f                                          #  # ## ## #  #  # # #  #### #    # #####  ##  #############
##  #   ##  t #   ##  ##    #    ##     #    #t   #  ##       #  # ## ## #  #  # # #  #### #    # #####  ##  #############
### #   ### ### #### ####  ## #  ## ### ###  ## # ## ### ###        l                                                    #
### #   ### ### #### ####  ## #  ## ### ###  ## # ## ### ### ##  # ##### #  # ## # #  #### #    # #####  ##  #############
#   #   ##r ##   ##  ##    #b #  l  t##  ##     #    #   ##  ##  # ##### #  # ## # #  #### #    # #####  ##  #############
#                r              t                                a     b         c f       g                             #
#   #   ##  ##   ##  ##    #  #      ##  ##     #    #   ##  ##  # ####### ## ## #### #### ## # # #####  ##  #############
### ##  ### ### #### ####  ## # ### ### ###  ## # ## ### ### ##  # ####### ## ## #### #### ## # # #####  ##  #############
### ##  ### ### #### ####  ## # ### ### ###  ## # ## ### ###                            lf    r                          #
###  #   ##      f #  f##     #     #   #    #b #    #   #   ##  # ####### ## ## #### ####### ### #####  ##  #############
#   g           t                b                           ##  # ####### ## ## #### ####### ### #####  ##  #############
###  #  g##        #   ##     #  t  #   #    #  #    #   #       l                          a         b   c             f#
### ## #### ### #### ####  ## # ### ### ###  ## # ## ###  ##  # ########## ## ## #### ########### #####  ### #############
### ## #### ### #### ####  ## # ### ### ###  ## # ## ###  ##  # ########## ## ##  ### ########### #####  ### #############
##     #  #     #    ##     # f  l  #   #       #  #   #                 g  l   l   c           b     c    g             #
#                 g    b   t                          f      ## ##################### ####################################
##     # l#     #    ##     #       #   #   # g #l #   #  c   # ##################### ####################################
### ## #### ### #### ##### ## ##### ### ### ### #### ### ###  f                     l                                    #
### ## #### ### #### ##### ## ##### ### ### ### #### ### ### #############################################################
###  g   ##  ##   ##   ##b ##    ##  ##  ##  ##   ##  ##  ## #############################################################
##########################################################################################################################
