metadata:
  gen_time: 1.0971078872680664
  timestamp: '2025-04-11T22:26:40.247373'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '

---
####################################################
# #####  ###############     ########     ##       #
#  ###   ###############    #########             ##
#         #############    ##########             ##
#                         ###########      ##      #
##                       ############     ####     #
##                      #############     #####    #
##     ##############   #############     ######   #
##    ################  #############     #######  #
#    #################  #############      ####### #
#   ##################   ###########        ###### #
#   ##################    #########          ####  #
#    ################      #######                 #
##                                    ####         #
###                                  ######        #
###                                 ########       #
##                  ###########    ##########      #
#      ####        #############  ############     #
#     ######      ##############  #############    #
#    #######     ###############  ##############   #
#   ########    ################   #############   #
#  #########   #################    ###########    #
# ##########   #################                  ##
############   #################                 ###
###########     ################                 ###
#                ###############   ##             ##
#                 ##############  ####             #
#  #####           #############  #####     ####   #
# #######           ############  ######   ######  #
# #######            ###########  ######  ######## #
# ######              ##########  ######  ######## #
# #####      ######    #########  ######  ######## #
# ####      ########    #######    ####   ######## #
#  ##       ########                      ######## #
#            ######                        ####### #
#                        ####               #####  #
#########               ######                     #
##########       ###    ######         ###         #
##########      #####   ######        #####        #
# #######       #####    #####        #####   ##   #
#  #####         ####     ####        ####   ####  #
#                 ##       ##          ##    ##### #
#                                            ##### #
#        #######      ###                     #### #
#       #########    #####           ####      ##  #
#      ##########   ######          ######         #
####   ##########   #####           ######         #
#####  ##########    ###             #####         #
#####   #########                     ####   #######
#####    ########                      ##   ########
#####     #######         ##     ##         ########
####################################################
