metadata:
  gen_time: 7.83859395980835
  timestamp: '2025-04-18T22:59:32.594392'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
####################   # #          # # c ###################                 b     #    t  #   #          t#a      #    #
#  c          c    #   # #     c    # #   #                a        a l             #       #   #           #       # a  #
#          ct      #   # #t         # # t #c  bc     c   c a        a    r          #  b    #   #           #       #    #
###########        #   # #c        a# #   #     c  # ########   #############   #########   #   #####   #   #   #####   f#
# lt   lca#   c    ##  # # a a      # #  ##     A  #            #                   #               #   #    t  #   #    #
#         #       t #cA# #    c     # #  #         # c          #                   #               #   #       #   #    #
#        c#  f      #  # #          # #  #a        #            #               b   #               #   #       #   #    #
#   c     #  t  c####  # #  f    f  # #  ####      #       t ####   #########   #   #   #   #####   #   #####   #   #    #
# b       #### ###c   f# #          # #     ########      c                 #   #     t #   #               #   #     f  #
#                   A  c   a c        t         ac                          #   #  r    #r  #          f    #   #     A  #
#         a              fcc     c          t                               #   #       #   #       r       #   #        #
############## ###### ## ############ ############## ################   #   #   #   #########   #####   #############    #
#                a c     r  # a c#     a#  c   #   c  a t t             #   #   #  t        #   #   #   #   #  f         #
## ###########  ## #   # # ## # ## ## ### ## ### ###### # ###    r      #   #   #           #f  #   #   #   #    r       #
##        b l   b                                   t       #           #   #   #t      t   #   #   #   #   #            #
##                 b  r   c                                 #   #####   ##################### f #   #   #   #   ##########
##c   c ############ ### ###### ####### ### #### ##### c    #       #              c#               #                    #
#       #    cb    #   #      c c   c #   #   cc     #              #             b #            l  #      r             #
#       # ##### ################# ### ################             l#               #      r    tr  #         b          #
####        t         f       t            r   c          ###       #      f        #               #                    #
####                 c                             a      ###       #     A     b   #               #          r         #
#       ################# ############# ####### ######      c       #               #               #               t    #
#   c t #          #   #f             #  c#   b      #     c        #      tbf      #               #            t       #
##      # ########## ###################### ##########      #    l  #               #     r f       #                    #
##             c         c         b   c f    c c           #   #####   #####################   #   #   #   #   ##########
##  c                             c         l     l   b     #           # g #   #  b        #   #   # r #   #            #
## ####### #### ###### ###### ########### ###################      t    # f #b  #     f     #   #   #   #   #     g      #
#        b   b#     a#      #   a#      #      #               l a      #   #   #           #   #   # r #   #            #
################################## ##################################   #   #   #   #########   #####   #############    #
#                t c   lt    b     lf   a       c      c          t      r  #   #       #   #               #   #        #
#b  la             c                  r            c       b b             t#   #       #   #     g         #   #        #
#         #     ##     # #      t   # #     ########            r           #   #       #   #               #   #        #
#         # f    ####  # #         a# #  #### c    #        f####   #########   #   #  b#   #####   #  r#####   #   #    #
#    c    #c c      #  # #          # #  #         #            #          a        #               # Af#       #   #    #
#  c     c#         #  # #          # #  #   b  a  #      ac    #            r      #            b  #   #       #   #    #
#    a  l #        ##bt# #          #c#  ##       c#    a       # a          r      #               #   #       #   #    #
######### #  c     #   #a#          #   l #        ##########  t#############   #########   #   #####   #   #   #####    #
# g  c    b        #   # #          #a#   #                                         #       #   #         f #       #    #
#                  #   # #a         ###  t#          fc    r                        #   a   #   #           #       #    #
####  ### ##########   # #          # #  r###################                   b   #       #   #  r        #       #  f #
#  ##  ##     f#  #       ###### ###  ## ### ### #       ##  ###            ###  #####   ###  ###########    ###   #######
#   ##     #   # ####       l# #  f      # #     ###    ##  ####  t    g                 ###  ###########    ###         #
#    ## l###       #           #       ### ###  ##          ####                         ###t ###########    ###         #
###            ##             ##   ##       #      #         ###                ###    t ###  ###########         ##     #
##  ## ##   ####  ## f        #          ## ####   ##   f    ###t ############  ###      ###  ###########         ##     #
### #  ##   ##     #   ## #t  ##         ##    ## ##              ############  ###  b        ###########         ##     #
# ###  #  #  #######    # #  r ##      # # r  ### ###      ##     ############  ###           ###########     c  t       #
# ##      #   #  ##g   ##      ##    # #            #  ##    ##   ############  ###  ####     ###########  #####         #
#             # ##    ###   ##  # #  #   ##             #### ## l     t         ###c ####    c             #####  ###### #
# ##    ##   ## #     #  t  #   ### ##   #     #   ##      # ##    g            ### c####      b           #####  ###### #
# #      ##  #  ##    ##   r#  ##   #  #       #   #    ## ####  ###########                ###            #####  ###### #
###r         ##      ##  ## ##    r#####   ##         ###   ###  ########### f         Ac   ###       t          t       #
##    ##      #  f        #  #    ##  #                #    g    ###########               t              r              #
###          ##        ## #  #     # ##f##   ##  ##              ###########    t                         ########       #
##  r ##      ##      ##             ## ##  ####                        g       ###   ########   ###      ########    c  #
## ##        ###       # ## f  #   ###  #      #    #          t                ###   ########   ###           f         #
#  ##   ## ###g#     #####     #   #             #  ##     #########              t  r########   ###                     #
##  #      #   #   # #  ## ## ##  f     ###      ## g   ## #########                  ######## g                   #######
#####  ##f ###    #### ##     #       ### #     ##       # #  ######    ############  ########                     #######
#   ##  #  r ###  #    #f   r## ###    #                   ##           ############             b b##########     #######
### #         #        r      ###            #### ##  ##                 b                          ########## g lA#######
#       ## #  ##  ####       ### r  ###  #   ## #  ##  #### #             c                  ####b l##########     #######
#     #  ###  ##### ###   ####        #  ##  #           ## ###   ##                t      t ####f  ##########           #
##    #                    ##    ##       ##       ##        ##   ##                         ####         r       b      #
##  #   #   ##    ##      ##      #   ### ####      ## ##    ##   ##        ##############        l   c                 t#
##  ### ###  #  ###  # ##       ###   # ### #g   #####g ## ####b            ##############         ######      c       l #
##                    ##        b#  #f# ##      ##       # ####             ##############  ###    ######                #
#     ##       ##   t ###  r    ##  #           #  ## ## #   ##   ######    ##############  ###    ######t ###############
#      ##     ##     ##     #####     ##  ## #     #  #      ##   ######               c    ###    ######  ###############
# # ## #      ###     #g##    ##   ##f##b  #####          b# ##   ######                  g                ###############
# ###         # # ### ###           # r   ##    cf ####    #      ######             t                                   #
###       ##    ###          ###    #        r  # ## ##   ## f    ######c    ###############  ####                       #
#   l   b        #####   ###r##           ## #### ##    #    #    ######     ############### t####    ####               #
#  ###    ##    ## #r    ##       f #### ##  ##   #  ####    #   b######     ###############          ####   t           #
#  ##     #   #### ## ##       ## ###  #r#   #   ##g # #     #    ###### a   ###############           r              ####
#  #      #        ##           ### # ##     ##      # ##  r##                   t       r                            ####
#      #g ## ##  ###l #####   l###    ##         ##    ##   ##          r               t          ##            t       #
#  # # #   #  #   #     ##     #             t   #   ###     #  #############  ##################  ##  #######           #
# ## ### # #  ##          fr       A## ##### ##  ##  ##    ###  #############  ##################  ##  #######    ########
# ## ##  # ## ####         #  ##  ###  #  ## #   ##   ##   ###  #############  ##################f ##             ########
##f   ####  tc  ####     lt##             l   ####     #####      ##   f       f       l##  ##        ##   ##### ### #####
# cf ######      #  a      ###    b            ## a t a ####      ##                        l   ## f  ##   ##### ### #####
#   ########       t       ####        ###               ##       ##    r               ##  ##  ##    ##   ##   a        #
#  ##########     l   ##    ####      #####t         c            ##           f f      ##  ##  ##    ##   ##           l#
# ############   t   #### l  #### r   ######      ###             ##             f      ##  ################### ## #######
# #############   l  #####    ####    ######  b  #####    ###     ##    g               ##  ################### ## #######
# ##############      ####  b  ####l   ####      ######  ####     ##l r                 ##  ##     ##     ##     f     ###
# ###############      ##       ####    a c       #####  #### ## ######## ####################   lr##     ##bg         ###
# ###############   c            ####        ##    ###    ### ## ######## ####################     ##     ##   b     g ###
#  #############     a            ####a     ####           ## ##   l ##          ## t##     ##    g## g   ##     t     ###
#                l        ##  f b  ####     #### f           ###     ##          ##  ##     ##   g   b    ##           ###
#                 g   b  ####t b    ####     ##    ###       ###     ##  l  f        ##            ##     ##     g     ###
##  f            ###    c#####      a####   a  a  #####f      ##     ##        t ##l ##  t  ##     ##     ##           ###
###         gt  ##### a  #####        ####t      #######    # #########   f   t  ##  ##     ##  f  ##    t##           ###
####           t#####  r  ###          ####      ########  g# #########          ##  ##   t ##l    ##               t    #
#####   c       #######     t           ####     #########          f##          ##      c  ##            ##       gf  ###
######    ##t   ########b    f           ####     ########      g f  ##          ##  ##   g ##     ##   b ##           ###
#######l #### f  #######         f b  a   ####     ###### a          ## g        ##  ## t   ##     ##     ##        t  ###
#######  #####    #####     l          A  c####        c   t ##### ######## ###########     ##     ##     ##           ###
#######  #####                   r          ####       f  b  ##### ######## #############f######################## #######
#######  #####         f       a            ####     c       b##       ##      lg    #### ######################## #######
#######  #####    #####   b                ####     c       a ##       ##            ##    tb g  ##  ## r##  ##      b   #
#######  ####    #######   f     l        ####     ######     ##       ##r           ##  b  f    ##  ##  ## g##         f#
######   g##    ######## fb         f    ####     ########    ##     l ##            ##     r        ##      ##          #
#####        t b#######               l ####    a#########    ##       ## g          ##          ##      ##  ##    r  t  #
####            ######   f###          ####      ########l  # ##       ##     r  l   ##  r  t    ##f ##  ##  ##          #
###             #####    #####        #### bft   #######   f# ## g b   ##     g r    ##         l##  ##  ##  ##          #
##   c          a###     #####       ####   l     #####  l   b##   r   ##            ##  b       ##  ##  ## r##          #
#          c             ####       ####     ##    ###   a    ############# ## ########## ## ##################### #### ##
#                         ##       ####   g ####           f  ############# ## ########## ## ##################### #### ##
#  #############                  ####   c  ####           ##    ##                       f         ##                   #
# ###############       b      gg####        ##gl  ###    ###    ##     r    b  b                   ##           r       #
# ###############      ##       ####c  t          #####  ####    ############ ##### ###b####### ############## ## ##### ##
# ##############      ####     ####  t ####   bb ######  ####    ############ #####b### ####### ############## ## ##### ##
# #############     f#####    ####    ######     #####   t###  t ##  ##  ##                               ##             #
# ############       ####   g####     ######l     ###     f l    ##  ##  ##                               ##             #
#  ##########     l   ##   t####      #####    a       a             ##c ##                               ##### ## #### ##
#   ########               ####        ###               ##     g##  ##  ##  f g   r  l      t   f        ##### ## #### ##
#    ######    f ##g       ### f               ##       ####     ##  ##             b                f    ##         ##  #
##    ####      ####       ##c       c        ####     #####     ##    g ##                   r     g     ##         ##l #
##########################################################################################################################
