metadata:
  gen_time: 9.398997068405151
  timestamp: '2025-04-18T22:57:19.304007'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#    # #   # #      ##  g              # #       # #    ##   ###                          #  #      #      g            r#
#  t # #   # #       ##   r            # #       # #     ##     #   #       #     #      #    #    #         #   #     # #
#    # #   # #   r    ##   r           # #       # #    t ##     # #       #       #    #    #      #       #    #    #  #
#   ## ## ## ## t      ##              # #      ## ##g     ##     #       #     l  #   #      #      #       #  #    #  f#
## ##   # #   ##        ##             # # r   ##   ##      #          A  #       #   # b      #     #   r  #   #    #   #
## #    # #    ## r   l  ##            # #    ##     ##                   #       #   #   l     #   #       #   #t   #   #
## #    # #     ##       t##    f      # #   ##       ##                   #      #    #         #   #      #  t#  r #   #
## #    # #      ##  t     ##         ## ## ##         ##        tlb        # f    #    # b      #    #  t  #   #    #   #
## #    # #       ##  l     ##       ##   # #           ##         g ####   r#  r   #    #      #    #   r  #  #     #   #
## #    # #      l ##       g#      ##    # #t           ##        #     #    #     #     #    #     #c     #  #     #   #
## #    # #         ##         #   ##    ## ## t          ## t    #  c   t#    #    #    #     # t    #     #r #     #   #
## #    # #       t  ##        #####    ##   ##b           ###    #      #      #t  # f   #   l#     #      #  #     #   #
## #    # #      r    ##               ##     ##            # #    #    #       #   #      #   #    # b     #  #     #   #
## #    # #            ##  l   #####  ##       ##          t   #    #    #      #    #     #   #   #        #  #      #  #
## #    # # f           # #### #   ####         ##              #    #    ###    #    #    #   #    #       #  #     #   #
## # r  # #                r      at     t       ##r         b   #    #      #    #    #  t #  #     #      #   #     #  #
## #   ## ##            # #### #   ####         A ##              #    #      #    # l  #   #  #  l   # a   #    #       #
## ## ##   ## ###########   r  ##t##  ##           ##   f    #   a #    #     #   #    #   #    #      #   #      #     ##
#   #                             #    ##           ## g      #     #  c #   #   #   r#    #     #      #  #       #     #
#   # #    ##############       # #     ##           ##        #    #    #  #    #     #    #     #     #  #        # #  #
#   # #  a##t           ##      #r#l f   ##           ##        #  #    #   #    #    #      #     #   #   #    r    #   #
## ##g## ##              ##       #       ##           ##      #r b#   #    #    #     #      #     #   # A #            #
## #     #   r            ##   ## ##       ##           ##    #     #   #   #    #      #     #  l  #   # l  #           #
## #   # #                 ## ##  f##     g ##    a      ##  #  t  #     #  #     #      #    #     #  #      # #######  #
## ## ## ##        t        # #     ##       ##           ##     ##      #   #     #      #    #    #  #       #        ##
#   # #  a##                # #      ##l     g##           ##   #      a #    #   #      g #  #     #   #                #
#   # #    ##        b      # #       ##       ##           #  # l        #    ###          ##      #    #               #
#   # #     ##             ## ##       ##       ##                       #  a                  t     #    #t          r  #
#   # #      ##         r ##   ##   l   ##       ##              ########          r                  #    #             #
#   # #       ##         ##     ##       ##       ##     t          r        ######################  #    #              #
#   # #        ##       ##       ##      g##       ##########       r       #                      ##t   #        #      #
#   # #         ##     ##         ## t     ##                 ## #####     #             b      l r       #      # #    ##
#   #g#          ##   ##           ##       ##     ##########         #    #     ###########               #    #   #   ##
# r #l#           ## ##            f##    t  ### ###              a    #   #    #         tc############    #   #    # # #
#     #   g b     r# #               ##        l                      #   #    #                        #   #  #l     #  #
#   # #            #A#       g        ##     #######         ##      #    #     #     #                  #  #  #         #
#   # #            # #            A    #######     ##########  #    #    #     #     # #   ##     t     #   #  #         #
#   # #            # #         r                 a              #    #    #   #     #   # #  #    l    #    #   #       ##
#  ## ##          ## ##r               #######     ##########    #    #    #  g#    #    #    #        #    #    ####   ##
####   ############   ##################   f #######             #   c#   #     #   #        #          #    #       #   #
#        ## a         #     ######     #           ##                                                 l #       #   #   r#
##                 l        ##  ##      r                   #                     t      l              #       #   #    #
#              g                                       f                     l            f             #       #   #    #
#a     ##       t  ##                    ##        a ##      ####   #########   #   #####   #   #   #####   #####   #    #
#      ##         #####             b  #####         ##             #           #   #   #   #   #    tl     #            #
#b## a            #####        f       #####       r     a##        #           #   #   #   #   #           #            #
#####  r   ##   r   ##                  ##       ##  r   ####       # f        l#   #   #   #   #           #            #
#####f    ####      c   g   ## b##        a     ####     ####   #####################   #############   #####   #####    #
# #    a   ##             ##########   a         ##        #        #       #   #   #ft #       #   #       #       #    #
#      a           ##     ##########     ##                         #       #   #   #   #    f  #   #       #       #    #
#     r##         ####     ##    ##     ####   l     ## a           #       #   #   #   #       # b #       #       #t   #
#    #####f ##     ##      b             ##     ## a#####    ########   # r #   #   #   #   ##### b #####   #########    #
#    #####  ##                                  ##  #####               #      l# l             #   #           #        #
#     ##    a                ####         b           ##                #    g  #           c   #   #       A   #        #
#         f  f        ##     ####     ##     g                          #       #  g            #   #       l   #        #
#           a      a ####     ##     ####                    ####   #   #   #   #   #   #   #   #   #   #############    #
# b g                 ##      ##l     ##        f                   #   #   #  r#   #   #   # b #       #   #   #   #    #
#      a   ##     #          ####f         #     ##   r             #   #   #  r#   #   #   #   #   g   #   #   #   #    #
#        #####  ####          ##          ####  #####       g       #   #   #   #   #   #   #   #       #   #   #   #    #
#      ###### l ####   ##  a         ##   ####b  ######         #####   #####   #########   #   #   #####   #   #   #    #
#      ######   ####   ##            ##   ####   ######         #       #   #         r     #           #    g           #
#   r    #####  ####          ##          ####  #####     a  g b#       #   #               #       rr  #                #
# g a  g   ##  a  #     a    ####    tg    #     ##a            #  r    #   #               #  r        #                #
#                  g  #  f    ##      ##       b           b #### g #####   #########   #####   #####   #####   #####    #
#     g              ####     ##     ####                 a     #   #                 l #      t    #       #   #        #
#       r             ##   a ####     ##       g                #   #              l    #           #       #   #        #
#     ##            br  a    ####  a   a              ##        #   #     t             #           #       #c t#        #
#    #####  ##                       f          ##  #####       #   #####################   ################# l #   #    #
#g f #####  ##l    ##b    g             f##     ##  #####                   #       #                   # g     #   #    #
#  a   ##         ####     ##   a##   f ####   f t   ##    ar               #       #                   #       #   #    #
#   f        g     ##     ##########    r##                          l    f #       #                   #       #   #    #
# #        ##            A##########         b  b##        # ############   #   #########################   #   ##########
#####b    ####              ##  ##              ####     ####       #                            t  #       #            #
#####      ##    fa ##              t   ##       ##      ####     l #  r           r                #       #            #
# ##        t     #####                #####              ##        #                            l  #       #            #
#      ##   r     #####     a          #####      a  ##         #####   #   #   #   #########   #   #   #########   #    #
#   l  ##          ##   b   a         r  ##      f   ##             b   #   #   #   #  rl       #               #   #    #
#b                                 a                               t    #   #   #   #     b     #             l #   #    #
##           t              ##  ##                          #           #   #   #   #           #               #   #    #
#      b ##   a       #     ######g    #           ##    a       l      #   #   #   #           #               #   #    #
#   ### f## ###   ##    #    #    # ####       a    ## ### ###              b####      ##      ##                        #
#     #     #   # a#    ##                 t     ## #        #    f            ##      ##    tg##     lg      b          #
#       ## ## ###    b   ## c          ## ##      ###    ##g #         l       ##      ##      ##                        #
# ## ## # t#  ##        ###             # ##     ###       # #             f           ##                               f#
# #  #     ##     ## #  #  a  ### ##      #  ## ##     # g  a#                         ##     g            t             #
# r              #####    ###   #  ## ###       ## ## ##  ##                          b##       l           b l   t    l #
###l     ##  ## ##  ##g    ##     ###  ##  ##   #  ## ##a  ###                                      f b       ########   #
###bt##  ##   # #   g## b ##   ## #     #  #    l     #      #                 t     g                        ########   #
#    #   #       t    ##  #   ###  tt ###    f##     ###   ###                                                           #
#       ## ###    ### #   ##     l    # ##     # ##   l#        ########### g                     l  g  r                #
#   #  ##  ##     ##     ##     ###       r   ## ##      #      ##  ##   ##   r         ## ######################## ######
##########     #         #  g  ###    ##   # ###       ####     ##  ##   ##             ##     ##  ##   ##       ##    ###
## #     #r  # ##   ##         # ##   ##   ### ### ##   #l  a   ##  ## g ##             ##     ##  ##   ##       ##    ###
#      ### # #  # a ### #                          #            ##                      #########  ##   ##       ##    ###
#          # #### #     ## ## #   c ##             ##   ###     ##          l  b                   ##   ##      g##t   ###
# ## ##   ##  #   #    ##  ## #      a        ##     g  ##      ##          b           l                        ##      #
#  #     ###    ###g    #     b ####       f  #   ###   #  t    ##          f                                    ##      #
#        # ##   #     ### ##l## #  #   # ####    ## #   ##b                        a               g             ##    b #
###  ##     #  ## ###  #c ##  #   ## ###a ##      # #    ###      l          l                 l          l    bg## g    #
##   #   ## # ##  ##      #   #a   ###     ##    ##   ## # #    t                                          f     ##      #
###       ### #   #       ##        ## ##  #    ##     #                               ###  ####### ############ ##  f   #
#####a            ## a# #     ####    l ##    ###   ## #    #                          ###  ##   ##   ##  ##     t       #
#      g  ## ##  ##   #t#    ## ##   ## ##   ###     #        l f                   b   g   ##   ##   ##  ##             #
###   #    g #  ##        # ###         l#  ##            ##            A b                      ##   ##        b        #
### ####  g ##  ##        # #      #   ### ##  l  ##   #####      l                              ##   ##            t    #
# # #  ## g #   r  #r       ###  g #  ##   ###g    #   ##  g ##   l                              ##   ############# #### #
#   ## #     f  ## #      ### #r             #    ##    # #  ##         g                        ##              ##   ## #
#   ## #  ##    f         #      ###    ##     ## #           #                  ## ###############             g##   ####
## ##  ##  #    ###  ##          ##     #    ###       ##     # a             b  ##    ##    ##         g##      ##      #
## #       # a    #a         ##         ##    #     ## #    # #     l    f       ##    ##    ##         t##      ##      #
#  #   ##  #  ##    ## #   ###                ##     ###      #            f     ##   g##    ##    l     ##      ##      #
# ##        ###   #### # g  #    ##      #    ### l  ##      ##                  ##f g ##                ##      ##      #
#    ## ###    l   #   ##        ##    l ##   # #    #       ##              ######    ##         l      ##      ##      #
## # ##  ## ## ##  ## ##   ##   r      # #      #b   # ###    # b          l ##        ##                ##  l   ##      #
######      #### t ##       ##r  ##g  ## ##   ###    ###t#  # #           g  ##        ##              g ##      ##      #
#   ##   ##        #     #####    ##   ###b                ## #    f         ##        ##               l##    l ##      #
#         #    ##      #     #     ### ##   ##   ###     b ####              ## g g    ##    g                   #########
####  ### ##    b  ### # ### #  #                  ####t   # ##              ##      l ##                     A     f   ##
## #    ###          ### # ###  ##    ## ##fg  ##   #        ##              ##        ##   c      A  f      g          ##
#     ####   #####                     # ###r#####  ###  r## ##              ##        ##       f                       ##
##########################################################################################################################
