metadata:
  gen_time: 10.12844204902649
  timestamp: '2025-04-18T22:51:18.729736'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#f    r   r                     ##         b     b        ## ##    r l    ####      tg   ##                              #
#       l      t                 # #  #  #        #  #  # #   ##         ##  ##         ## ##############  ###############
#                               ## ## #  #   r    #  # ## ##   ## ##### ##    ## ##### ##  ######### ####  #### ##########
###   ##       ##     ##       ###       a  r             ###  f                                                         #
#  ##   l       ##         A #    g        ##  ##                                 c    c              ##    ##     f   f #
#               ###        g    ##      ##  #  #  ##t a   ## c #########        #########  ## ##### r ## ## ##   ##### ###
#                ###     r    # #   l####   #  #   ####    # ###       ##  c   ##       ###########   ## ## ##   ##### ###
#    ##        g   ##           # ## ##              ## ## #       c  c ########                 ## ####  r #### ##      #
#   ###             #   #  #     b#r     #    r t #      #    c         ########t r g     c      ## ####    #### ## t    #
#   l                    g      ###a##   ## #  #  #   ## # #    b      ##      ##c   l     ###   ## g            ##  b####
#           t               #  r# ###  #  ###  ###  #  ### # c       l##        ##    c    ###   ##  ##      ##  ##  t####
#                              ## # cr #   ##  ##   #   b# ## g########## ###############   #######  ## #### ##l ####### #
#                  l    ##        #       ##    ##      ##    ##     l                  ##  ####### b## #### ##  ####### #
#                       ###    ##  #       #    #       #  ####                       c l##    l     ##     b##          #
#g   #     ## ##     #   ####   #####   ## # ## #b##   ######                      c c       ##                      ##  #
#g   #       #     #       ## t     ##       ##       ##        cr            tc             ##            t         ##  #
#      t                #   #  ##    ##   ##    ##   ##    ###     g     c        f    c  #  ##                      ##  #
#    #                      ## ###l# #                # # #####     # ##############  r c### ####            t   b #### ##
#  ##  f        #            ##    ###l#### #### #### ###     ##   ##        c   c ##   ## # ####                  #### ##
# #      r      ##  r         #    ##  ##t  #  #   ##  ##      #  ##          t     ##  #t #       f        f           ##
#       r    #   #              glb ##  ## t# ##  ##  ##   g A  c #     t##c ##      #     #                            ##
##                                # #          a       # #     #l #   c ##    ##     #  #  #                    l       ##
#  g                      # t   # #  at  ##########      # # ###  #c   ##      ##   b#  ####                            ##
#           ###            #    #     r    ##  ##          # ### ##    #        #    ## ####   ########      ########g  ##
#    # r#  r ##t           #        ## ##          ## ##        ### g      ##c       ###   #   #### ###      ### ####   ##
#    ##       ##   t          #  t ##  ##a   ## b  ##  ##     c## #    #   ##   #   t# ##      ##r                 ##  t #
#    ##     l  #  ###       # ##     r #  t  ##r    #       #     #    #l  ##   #    #         ##       b      l   ##    #
#              ##  ##          #   ##   t ##    ##     ##   #  #  ##   ##  ## c##   ##  #  ##  ##      ##  ##      ##  ###
#        #     ##   ##             ####              ####      #   ##  ###b## ###c ##   #gb##   #   ## ## t## ##   #t  ###
# g #    #     ##    ##      ### r # ##   ########   ## #  a#            ######            ##  ##   ## ##  ## ##   ##  ###
#   ##         ##     ###     #t           ##  ##       t      #c   #  # ###### #  #    #  ##  ##   ## ##  ## ## b ##  ###
#    ##   #    #        ##     #       ##   g   r  ## r     # c#r  ##  ### ##              ##   #   ## ##  ## ##   #   ###
#     ##     l      ##         #  g                         #  #c ##  t##  ##l ##   ##  # c##  ##   t  ##  ##      ##  ###
#     ####   ##  t #  ##               ##          ##          #  #  r #   ##   #    #  #      ##      r        l  ##    #
#        ##  ###           g    ##  ##  ##       t##  ##  ##   ## #    #   ## r # f  # ##      ##             b   b##    #
# r       ##                   ##  ##     l  b         ##  ##t  ###  c  g  ##      f ###   #t  #### ###      ###l####   ##
#         ##           #       #   #   ## # ###### ##   #   #### ##    #        #    ## ####   ########      ########   ##
# b                            ##  ##   # # #### # #   ##  #####  #    ##      ##    #c ####       g                    ##
#         #     f    l            ##   ##  a ##    ##   ##     #  #     ##   l##  brc#     #t                           ##
#   rr   g##                    # #     ##   ##  a##     # #      #      #   ##    c   f   #                            ##
#  f       #  ##               #### ### #          # ### #### c#  ##c   A           ##  #  #                     r      ##
# g     r     ##   ###         #    # # ##        ## # #   g# ##  c## b            ##  r## # ####          a       #### ##
#         ##   ##   ##     #   # #### ###          ### #### ### r   ###### #########     ### ####           l      #### ##
#  lg                #      f    #    ##   #    #   ##   r#  #          b                c#  ##                  t   ##  #
#           #  #   g ##          ##   #  r##    ##   #   ##                                  ##                      ##  #
#              #     ##r         ###  t   ## ## ##      ###       c          c      gt       ##       t   t        t ##  #
#            #           g            ##   ######   ##       ## g     b c           c  l ##          ## t    ##          #
#              r    t           b## ####  ###  ###  #### ##   ##   c     b              ##c ## ####  ## #### ##  ####### #
#               ##      r    ## ##l #     #      #     #  ##   ######### ################   ## ####  ## #### ##  ####### #
#    l         l ## l      #  # ## ## ##  # #### #  ## ## ##      f   ##        ##         ###   ##  ##      ##  ##   ####
#            g                # #   ###        #     ###   #           ##      ##          ###   ## t            ##   ####
# b   t  #    #            #                #  #                        ########    t b     r    ## ####    #### ##      #
#r       #    #g                           ##  ##                     c ########             l   ## ####    #### ##      #
#     ##   ##   ##                 ###      ####  l b ###  a ###       ##      ##     cc###########   ## ## ##   ##### ###
#     ##   f #         #      #      ## #  ######  #  #      g #########        #########  ## #####g  ## ## ##   ##### ###
# l    ##             a  r    # #  ######  #    #  ######  #   f       c g      c g                   ##    ##           #
#       ###  g     #            # ##   ##  a       ##   ## #            t rl         t  c                                #
## l      ###        #         ## #  ###     ##     ###  # ##  ## ##### #     ##c##### ##  #########g####  #### ##########
#  #   #    ##       ##        #  ## # # ## #### ## # # ##  # ##         ##  ##   f f   ## ##############  ###############
#      #     ##      ##   #    #       # ##      ## #    ra ###           ####    l      ##          f                   #
#       #   ##                              t   b             l ###   g       #   ##        # # # ##### #### ##### # # # #
#  #r   #f                 #    gf  A                      b #   ##  r                      # # #       ####       #t# # #
# ##           rf          #   ######  ####  #  ##########   #                        ##  a # # # ##########  ###### # # #
# ##                        #    #  t  #  #  #  #        #            f #           #####  r# # #       t          # # # #
# #     bf                  #    #     #  #  #  #        # r      #   ####l  ##     #####   #   # # ######### ## # #A  # #
###              ##          g#  #  #  #  ####  ####  ####   #  ####  ####   ## r b  ##     ### # #              # # # # #
##  b            ##        #       l#     #  #     #  #  #  t#  ####   ##                   # c # ##### ####  ####c#   # #
#               ##  #    ##   #  f  #     #  #     #  #  #       ##                      f# # ###g##### #  #  #### ### # #
#  b    ##   #  ##             ###  #  #  #  ####### l#  #b      ##                    l###       ##    #  #    ##       #
#       ##   # l##  f            #  #  #        #        #                  ##     ##   ### # ###### ####  ## # ###### # #
#       ##  b   ## l f    l l    #  #  #    b   #        #  l##l     ##     ##g  #####   ## # #         #  #         # # #
#       ##    l  ##     b        #  ####r ####  #  ####  #   ##     ####  rr     #####      # # # #######  ## #### # # # #
# b      #    g   #    f               #     r        #  #   #       ##      l    ##       ######      ##  ##      ### # #
#                 ##                b  # g#  r        #  #                               ######## # ## ##  ## ## # ### # #
#        ## f     ##       ##  ###  #  #  #############  #       ##         t##         f##    ## #   r        # # ##l   #
#       l##       ##      #### A    #  #   r #  #     #  #       ##    ##   #####  ##       #####   ######### ## ##### # #
#       ##         #  #             #  #     # b#     #  #            ####   ####  ##                       # ## #####   #
#       ##    ##                 #######  ####  #  #### g#             ##b     #  r        ##c## #####b r## # ##### ## # #
#      ##     ##     l              #        #  #r       #  g    ##r                        # ## #         t#    r# ## # #
##     g      ##         b     ttr  #        #  #        #   #  #####    b          ##  bg       # ### #g## # ### #    # #
##             #               ############  #  ####### l#   #  f######   ##  ##    ##   ##          l # ## #   # # ## # #
##                                        f    l# r   #  #         #####  ##  ##        ###     f  # # # ## #t# #   f  # #
## r              r      g           l   t      #     #  #           ##                  ##                   ######## # #
###            #        ##   #  r#######  # t#######  ####    ##                              ##       #    #       ##   #
# ##        #   l         ##     #    r   #     #        # b #####   g     ##      ##      ## ## ## #### ## #### ## ##  ##
# ##      ##             f  f    #        #     #        #   #####       #####   #####     rc       ####  t ####      t  #
# ##      g     t              ###  #############  ####  #     ##        #####   ####      ########### # ## # ############
# ##    ##   l r          l  #   #        #        #  #  #                ##   a  #        ########### # r  # ############
#  #    ##                   ##  #        #        #  #  #           ## a            b            ##   #b## #   ##   ## ##
#    #  ##                   ##  #  ####  #######  #  # f######    #####      ##           # ####### # # ##   # #  #### ##
#    # g ## b        g       #      #  #   g    #     #  #   ##    #####      ##           # ####### # # ##  t#   ##### ##
#         ###                  r    #  #        #     #  #     f     ##  r                 # ##   ##   # ##      #   ## ##
#     #     ###l              #  ####  #g ####  ####  ####                ##      #        #### ###### #       ##  #### ##
#      #      ##              #  #r #     # l   #  #           ##       f#####   #### l    #### ###### # #    ##  #####A##
#      #                         #  #     #     #  #         #####       #####   #####              ## #     #           #
#            #                 ###  #######  #  #  ####  #########         ##      ##      ## ## ## ## #    ## # ##t##  ##
#        g   ##   b           #  #           #           l    ##           a                # ##                         #
#   r r      ##               #  #         l #                 l   l ##                l ## # ######## # ## # ######## # #
#r      b  t ##                  ####  #  #  #######  ####         #####  ## f##b       ### #      # #f# ## # # #  t   # #
#             r    b    ##      b   t  #  #   t    #     #   #   ######   ##  ##    ##   ## # ## # #   # ## #   # # ## #b#
#              # l         # f         # g#     lb #     #   #  ##### a             ## b    #    # ###                   #
#     #        ##            ##  #  ##########  #  ####t ####f   ##                         # ## #     # b  #     # ## # #
#          r   ##            ## t#  #  #r     r #     #  # r           ## f    #           ## ## ## ## # ## # ##### ## ###
#             g##             g  #  # r#        #     #  #            ####   ####  ##         ##### ##             ###   #
#     r        ##     g  #  #    #  #  #  ##########  ####       ##    ##   #####  ##      # ###### ##########   #    ####
#               #        ##  ##  #  #  #        #     f   b      ##     b   g##          ##c   ## # #         b# # ##    #
#       bg     l  ## f   ##      #  #  #        #                                        ######## # ## ##  ## ##c# #######
##                  r     #    ######  ####l ####l ####  #####       ##           ##       ######      ## r##    t #######
##              ##          #    #b #  #  #  t  #     #      ##    f####         #####        # # #######  ####### # # # #
#                 #       b      #  #  #  #     #     #      ##      ##     ##   #####   ## # #    l    #  #b        # # #
#     ##      ##          f   r  #  # b#  #  ####  #  ####    a             ##     ##   ### #r###### ####  #### ###### # #
#             ##                       #     #     #  A  #       ##                     ###       ##    #  #    ##       #
#   ##        ##                       #  b  #a    #    t#       ##  A                    # #####                    ### #
# r ##                         ###  #### l####  ####  ########  ####   ##                       # #####      ###       # #
##                               #        #     #            #  ####  ####   ##      ##     #####                  #  ## #
#         #          #   ##      #        # l   #              g  #   ####   ##     #####       # # ###  #  #  #c# #   # #
#          ##        #   ###    b####  ####l    #  #### A#              #          r#####   # # #                    # # #
#  ##f            #       ##    l      #     #  # l#     #   #                     l  ##    # # ##  ######## # # ### # # #
#           l   f       f  #           #     #  #  #    b#   #   ##                               r    f#### c    f# # # #
#    r  ##                 ##        b #  b  #  #  #     #      ###           #   ##                               # #t# #
##########################################################################################################################
