metadata:
  gen_time: 7.37245512008667
  timestamp: '2025-04-18T22:58:20.878340'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#             ##b  # r  f  ### ##    ## #######     l   ####   ##         ###   #  ##  ##  ##   aa    a    l a   A       #
#  b                                                      ##  ####      #####  b   ##  ##  ##                    r      l#
#######       ######           ##    ## ##### t  ##           ####      ####       ##  ##  ##  ##  ##l ##############    #
####################### f      ##  b  # ######  #####   rA     ##   ##   ##        ##  ##  ##  ##  ##l ##############  l #
#   ###################      b ##    g# ######  #######     c       ##        ##               ##  ##  ##  ##  ##  l c   #
#                                              b  #####            ####       ## a             ##  ## l##r ## a##   A    #
#   ###    ## r     b############    ## ##### f     ##   t##   ##  ####   ##     ########a ##  ##  ##  ##  ##  ######    #
#######   ####     g ######rl####  l ## ##### ##       rr ##   ##   ####  ##     ########  ##  ##  ##  ##  ##  ######    #
#######   ####       ####    ##########  ########               b   ####       ## c     a  ##  ##  ##  ##a     ##aa##    #
#######   ####       ####    ##########  #########  ##  b           f##  t    ###  t       ##  ##  ##a ##     b## r##    #
####      ####r      ####    ################ ##########  ##  ##             ####  ######  ##########  ##  ######  ## ####
####      ##### g    ####        ############   ##################           ####  ######  ##########  ##  ######  ## ####
# ##      #####     g#           ############    r##  ##############  ##       ##  ##  ##      ##  ##        a     ##  a #
#       t ###    l   #l    g     #############          ##  ##  ##########         ##  ##a  a  ##  ##   r     a    ##    #
######### ###      ### b         #############           r  f     #########      ####  ##  ##  ##  ##   #  ######r ##    #
#########                                    ##   ## b    r         ##  ###   ##t####  ##  ##  ##  ##   #  ######  ##    #
#####         l#######            #######    ##   ## l   ##              ###  ## a    r##  ##  ##              ##  ##    #
#####g  ####   #######          l ########   #           ##  ##     r l  ###           ##  ##  ##     a##      ##  ##  t #
#####   ####   #######  g        l######## b #               ##   f##   ###      ####  ##  ##########  ## ###t ##  ## a  #
# ###b   r #  b#####              ######  f         ##      t      ##  t###     l####  ##  ##########  ## ###  ##  ##    #
#                                                  ###   l             #####       ##      ##   l      ##  ##  ##        #
# ###  b                               g gf      ######    ##  ##      #####      t##      ##        b ##  ##  ##        #
#####      ##  #####        r   ######## ####    ######    ##  ##     #######      ######  ##############  ##  ###########
#####       g  ##### cg         ########    #b    ######            ######### r #  ######  ############## t##  ###########
#####         t c ##   ###      ########    #     #######          ########    ##r    t        ##      ##  a       ##    #
#####b  #   b     ##   #################    #       #####    ##  c####  ##   f ##          fa  ##      ##  l       ##    #
#####   #     ########################      ##       ##     ####  ###           #########  ######a ##  ##############    #
##### ################################ r    ####      l    #####   ##            ########  ######  ##  ##############a   #
##### #################      #########      ####          ####    l     ##  fl     ##  ##l         ##    a   t     a     #
##### #################       g             ###         #####           ##         ## a##          ##                   l#
#####  ################    b                    r  b    #####      ##        ##    ##  ##  ###### r########## a###########
#####  ##############    ###########      ###          ####    t  ####      ####   ##  ## l######  ##########  ###########
#####  ########                                 ##     ###       r####    ######   g   ##a     ##  ##  ##tt    ##  ##   a#
#      ########    ### c  #######      ###### ######  ####    t    ##     #######    a ##      ##  ##  ##     a##  ##  a #
######################    #######      ##################               l  ##########t ######  ######  ##  ##  ##  ## b  #
###              c         ######      #########  ######    ##     g    f    ##  #### a###### a######  ##a ##  ##  ##    #
###     ########          b##   b      ###   ##     #  f  b ##    ##         f         ##     t##  ## t    ##a ##        #
###   ########### ###########       l  ###   ##       f    ####r  ##    ##             ##      ##  ##      ##  ##        #
#     ########### #######              ###   #           ######t ####  ####r ##  ####  ######  ##  ##  ##  ######  ##   a#
#     ##                       r      g###      r   ##  f####    ##########  ##  ####  ######  ##  ##  ##  ######  ##    #
#      g                g             g###    b     ##    ##    t  ######                 a    ##  t   ##          ##  t #
################  c              #########     ##         ##      l  ##              r    a    ##  al  ##  a   f ra##    #
###########  ###         l       ######### ##  ##        ####  ## r             #   a a       r##      ##  c       ##    #
###########              g      l######### ##      ##  ############           ### a l       a  ##      ##          ##    #
###########                    b  ######## ##      ##  #############          ####         ##t                          ##
###########    ## ###############   ######  # ##        ############   r r     ### # ##### ###  ##              ##  ### ##
##     ####    ## ########r    #### ######  #####    b    ########    ##  ##    ####     # #     ###r  #          b   ####
##     ########## ########     #### ## b    #####  l##      ####r     ##  ##   b####     # #    t# #    #       #     ####
##     ########## ###  ###     ####         ###     ##t      ##      r         ###t####### ###   # #### ##  ##  ####    ##
##        c        l   ### ### ####          #   t      ##   ##           t    #   ##       #       ##       #       ##  #
##          r  l  #    ### ### ####    ###              ##l ####   ##     ##     #f####### ### # ##########   #  ###### ##
##                # rb  r# ###         ######        f      #####  ##     ###    ###  ###    # #      b   ###         ####
##                #      # ### #    l  ######   f    lr  l   ####        ####    ##   # #    # #          # #    # #  ####
##  l             # c ####     #       ######     ##          ##        ######   #  ### ###### ############ ###### #### ##
##      g   r     ### ####     #       ######   ######             ##   ######            ##     ##           ##f  r ##  #
##g  f   f        ### ####   l ##      ##   r ########## f      r  ##     ##  f  #       ########## ##  #######      ## ##
##########        r   r r      ##  l   ##  #######  ####     ##  t####           #    ##    ###     #      ###   ###  # ##
#t     c##              #########      ##  ######    ##    #####  ####           # #  #t#   # # r         r      # #    ##
#       ##     ## ### # ###            ##  ## ###          #####   ##     ##   ### #### ##### ###     #####  ### # #    ##
#       ##   l ## ### # ###                ## ##         f  ##    l      ####  ###  r   ##     #                 #      ##
#       ##    l##             ## ############       ##                 ######   ## #### ######      ##   ## ####     ## ##
#              ##g       A    ##   ######   b       ##        t    f   ####             #  ###    #    ##   ##     #  ####
#        c    l##r  r         ##   ######      ## b       ##   ##   t   ##       ###  ###r                            ####
####                     g    ##r  ######     ####        ##   ##                  #  ###  # #  #                A      ##
#### l   c     ## ######## #####   ######   g ######     ####  b             ##  # #f # ####f#### ###### #### #### #  # ##
####               ####### #####   ###################  #####              r ##  ###  #      ##                    #  ####
####  #####        ####### #####   #############  ##########  a        ##   r  f     #  # b  ####                        #
##    #####  c     ####### ###     ######### ##     ######      f    ######         ##  #    #     ##  ##        ##  ## t#
##    #####       r####### ###     #########          ##   t    ##  #########       ##  #    #     ##  ##        ## r##  #
##  r #####    #   ####            ######### f              r #########  ######     #####    #     ##  ##       b##  ##  #
##b   ##### ##     ####    ################# # ## #### ###     ##     # #########   ##### ####     ##  ##        ##  ##  #
##t   ##       ##     #    ###########           b#### ### b     a bt       g  ##r              t  ##  ##    c   ##  ##  #
##    ##      ###     #    #####         b###     #### ####################           t      l     ##  ##        ##  ##  #
##            ### #   #       ##  ###########     ####                a####      ## ###### ####    ##  ##        ##  ##  #
##  #### r    ### #   #           #####  f     t  ####t  ###########f  ####                   ###  ##  ##        ##  ##  #
## ####### r          #### b     c#####   l       ####  ###  ##############    g              ###  ##  ##        ##  ##  #
## #######    r       ####        #####g          #### ####  ##############b                  ###  ##  ##        ##  ##  #
## #                              #####  b     g  #### g     ###     ######             g     ###  ##  ##        ##  ##  #
## #       r      c r       g  l  ############ab  ####   ####### b  f##     t  ##             ###  ##  ## r      ##  ##  #
#               l     g### ###################a   ##     #######               ######### ########  ##  ##f       ##  ##  #
## #### #      ## ###  ##  ##  ###############   a##    r####### ##  ##        ###g            ##b ##  ##        ##l ##  #
##      # c    ## #######  ##  ###############    ##  ########## ######        ###          g  ##  ##  ##b   f   ##  ##  #
#r fg      l   ## #######  ##              ###    ##  ########## ######ag      ###      b      ## f##  ##   b    ## c##  #
## ############## ###      ##            g ###    ##  ####  a  b ######        ###     t       ##  ## f##        ##  ##  #
#  ############## ###   r           l      ###    ##bg####      g######  f  ######       ##    ##  ##  ##        ##  ##  #
#  ###########    ###  ### ###################    ## a####   l#########     ######       ##    #   ##  ##        ##  ##  #
#  ###            ###  ### #######   #########    ##  ####    ######        ####         ##    #   ##  ##        ##  ##  #
# r###            ###  ##            b       #    ##b                a  t   ####a#               f ##  ##        ##  ##  #
#  #######  l   c                          l # a   #  ####    # At          ####l#             #  l##  ##        ##  ##  #
#  ############## ######## cc                     t#  ####    #      a   aaa####       ####    #   ##  ##        ##g ##  #
#  ###  ######  l ##  ####      l         c  ####  #  ##  t   ###  ### ########  #  ####  #    ##  ##  ##        ##  ##  #
#  ###  ##  ##    f   ####     b             #######  ##      ### g### ########  #  ####  #        ##  ##        ##  ##  #
#  #### ## lb         ####   c b             #######  ##  ### ######## ########  #  ####           ##l ##     f  ##  ##  #
#  #### ##                                  ##a        #t ### ######## ###########  ####  #     g  ##  ##        ##  ##  #
#######     ##### ######## ########### rl   ##         #  ### ########   #########     #b #  ####  ##  ##        ##  ##  #
#     # b   ##### #######  ###########      ## a     t #c ### ########b  #########  #  #  #  ####  ##  ##        ##  ##  #
#     #   f ####    #####      r##############  t r    #  ###t####################  # f####  #     ##  ##        ##  ##  #
#     #     ####    #####       ####################  ##  ###a#################a # g#l      l#     ##  ##        ##  ##  #
#   l ###   #####   #####       #####     ##########  ##      ### g############     #        #   r ##  ##  g     ##  ## l#
#    l###   #####   #####      ####       #######  #  ##      ###  ############     #   ######  b  ##  ##        ##  ##  #
#    r###   #####    ####b r   ####                                b  a     #### ####   ##         ##  ##g     g ##  ##  #
#     ###   ##       ####    gb           ####     #  ####    #        a  t #### r #######         ##  ##       g##  ##  #
#     ###   ##    r  ####     g           ###                               ####   #######      # f##  ##        ##  ##  #
# r g r  g  ##    t  ##################   ###     ##  ####    ######     f t#### #####g         #  ##  ##c       ##r ##  #
#          g##     g  r   b   f ###########       ## a#### a  #########     #####   ##             ##  ## b      ##  ##  #
#    r             ####          f#######   ##    ##  ####   aa  ######     #####   ##b         A  ##  ##        ##  ##  #
#            l   l ####           ####### ####    ##  ####       ######   l    ## ####    r        ##  ##        ##  ##  #
#                  ####    l g    ###     ####    ##  ########## ######        ##   b#          t  ##  ##        ## c##  #
#              bl  ##    r    A    ##     ####    ##  ########## ######A    b  ##    #             ##  ##     t  ## b##  #
#         ra # ###### l   #####    ##     ####    ##     #######r##     a     t##    #        l    ##  ##     c  ## b##  #
#r   r         ######b    #####  ####     ####    ##     #######t    ##    aa r##    #             ##  ##        ##  ##  #
#    r  #    ########     #####  ####     ####    ####   #######    g##        ##    #            b##  ## l      ##  ##  #
#    l    #######c        #####  ####     ###   l ####   A   ### b   ## ###          #         t   ##  ##        ##  ##  #
# ##  # ###         t            ####     ###     #### ####  ########## ###          #     ####    ##  ##     f  ##  ##  #
# ##    ###         #########    #### g   ### g   #### ####  ########## ###    a  ####        #    ##  ##        ##  ##  #
# #     ###         #########    ####     ###    a####   ###########    ### a     #        #  #    ##  ##        ##  ##  #
#               ##########       #       ####f    ####          a    g #### t     #       t# b#    ##  ##  g     ##  ##  #
# ## b          ##########       #       ####     #### ####################       #        #  #    ##  ##        ##  ##  #
# ########      ##########    b  #####   ####     #### ###                     ##     t    #  #   f##  ##        ##  ##g #
# ########################       ################ #### ###  b  ##     ########### #        ####    ##  ##    g   ##  ##  #
##########################################################################################################################
