metadata:
  gen_time: 5.459424018859863
  timestamp: '2025-04-18T22:53:44.748717'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
####      t ####    ###       ### # ###             b### # ######   l   ####     ##        ####  ##   ##       b   ##### #
####   ##   ###     #####       # # ### # ######## # ### # #  ##      ### ##      ###   #######  ##   ## b######   ##### #
#### ###### ###      ####       #         #      #    l    # ####    ###     #    ###r   ######       ##  ######   ##### #
#  # ###### ####      ####  ##  ### # # # # #### # #b# # ### #  ##           ##  ##A##     ####       ##  ######   ##### #
#    ##  ##  #####     ########     #   # # #### # #   #         ##  ###      ####   ##   r       t   ##  ######   ##### #
#          b  #####     ####### ### ### #          # ### ### #    #####        ##    f##     f        ##                 #
## l         l  #####     ##  # #     # #r# #### # # #    r# #     ##     ##f ####     ##  ###### l   ##         r       #
##   ## l ##     ####           # # # # # # #### # # # # # # ##          ######  ###   ##  ######                ##      #
#    ##  #####    ##   r       ## # # # #        r # # # # ## ##   ##   ##  ##    ### l ##                       ## g    #
#        #####             ##     #     # ######## #     #     ## #### ## r             ##                l      ##    f##
###        ##         lc #####  # ### # # ######## # # ### # f ##f#### ##         ###  ##  #########             ##g    ##
###               ##     #####        # #          # #        ##   ##   ##     b   #####  g#########       t     ##     ##
#      ##        #####  b ##   ## # # # ####b## #### # # # #### t       ##b          ##           l       ## g ####   ####
#      ##   ##   #####      l   # #        # ## #        # # #t        b ## cg     t                      ##   ####   ####
#  g     f  ##     ##           # # # ####b# ## # #### # # #              #  ## ##                 #####  ##        f ####
#  ##       r              ## l #     #             f#     #        A      ######## # ## ###       #####  ##          ####
# ####                     ##   ### # # ## ###### ## # # ### # ## ## ##    ######## ########   #########  ##       #######
# ####     ##      ##                        ##              ###########    ## ## # ########   #########  ## l     #######
#  ##    r ##      ##          ###### # ## # ## # ## #a#################    t     c  ## ## #   #########  ##  g    #######
#     b           ####  ##  ##   f         # ## #             ## ## ## ##     t            #   #########        ##########
#                 ##################### ## # ## # ## ########           ###   l    r f     #   #########        ##########
#   ##            r ###########   f              b             l         ###  l    f           ###    g   g             l#
# ####    c      r    ## g##  ## ### ##### # ## #  #### ### ###     l              ##          ###         f       l  A  #
# #####     ##  ##   l             r       # ## #r           #           ###      ####   ##l   ###  l    #######         #
########  ########             # # # # ### # ## # ### # # # ##  l  f      ###           ###  #####       #######         #
########  #########  ##  ##               b           b                  ####     ####  ###  #####       #######         #
###  ##    ## r##############  ### #f# ##### ## ##### # #b####  t        ###       ##    ##  #####       #######         #
##          l    ##############  #   #                #   #  ##      t    ###        b       #####    ##########         #
##                f##  ##f ##### ### #### ## #####b#### ### #        f      ###          ##  #####    #####       ########
#     ##  ## r  b            ##r        # #t     # #                         ####       ###  #####    #####      f########
#   #########            al r  # ###### # #      # # ###### #               l  ### t   ##   t#####             ###########
#   #########            ##      #    # # #      # # #    #   #   ##  f r##      l    ## ft  ##    t    A      ###########
#    ##  #####          ####  ## # ##r# # #      # # # ## # # ##b#### b ####   ###   ##      ##           b f  ###########
#         #####     b ######  #           #      #      r   g ## ####           ###t ##      ##              #############
#         ##### r##   ####     # #### # # # b    # # # #### ###   ## b  ####        l ##  #  ##   ########   #####       #
#  ##       ##   ##    ##           r   # #      # #         ##          ##     ###    ####  ##   ######## l #####       #
#  ##                          # # #### # #      # # #### # ##                   ###    ##   ##   ########  l#####  f    #
#      ##                      # #    # # #      # #    # # ###                    ##  ####  ##       ####   #####    l ##
#      ##   ##  ##             #   #  #  g#      #   #  #   ###              b      ####  #  ##     f ####   #####      ##
# r         ##r ##   ##    ##  ### # b##  #      # # #  # ### ## # # # # ## ## ##    ##      ##  #########   #####       #
#    t ##    ######    ##      #   #  ### ###  ### # #  # f                      #              ###          f   ### l   #
#     f     ########           ##  #  ###  ##  ### # #  #  ##                              #### ### ############ ### #####
##           ##  ##           # ####### #   #### # # #######   ##   ##        f            #### ### ############ ### #####
##    ##                ##    #    A #              a #r        #   #                      #### ### ############ ### #####
#    ###                ###       #  #        l       #  #                       r              ### ###     l### ###     #
#     ###              ###     # ####### # # ## # # ####### #                 ##      b     ### ### ###      ### ### ### #
#     ###              ###     ###  #  ##############  # t###      ##r r       #            ### ### ###      ### ###b### #
#      ### f ##  ##   ###      ###  #  ##############     ###       #                       ### ###f###      ### ###     #
###    ###   ######   ###    ### # ## ## #b# ## # # ##### # #   #                      ##   ###f### t            ### ### #
###     #   ########   #     ##           f          #          ##g    ## c  f          #   ####### ###    bb### ####### #
##        g  ##  ##           #                      #  #  l            # f                 ####### ###      ### ####### #
#                  g   f        #  ##  ##     ## #r##   A  #                         #      ####### ###     l### ####### #
#             t                ###   #  #####  #####  #    ####                 ##   ##             ###      ###         #
#          t   ##   t          ####  #  #####  #####  #  #####       b           #         #### #######      ####### #####
#  ##     ##   ##   ##     ##   # ####### #A#### # ####### #           b                   #### #######      ####### #####
# #####   ##  ####  ##   #####               ##                     r   ##    #      #     #### ####### f    ####### #####
#  ####       ####     g ####f               ##      #          ##  ##  #     ##    ##          ###           l  ###     #
#    #        f##         #     #   #####   #### # ####    #  t  # t#                   ##      ###   g          ###     #
#t       ## r        ##    a   ####     ##     #####     ####                   b        #      ###     t        ###     #
#        ##          ##        ####  #  ##### f#####  #  ####c        b      #    ##            ###              ###  t  #
#        ##          ## l       # #######   #### # ####### #              b  ##    #  t   r     ###    f         ###     #
#        ##          ##    f               l ##      #  #f       c ##                t ##       ###              ###     #
#    #         ##     r   #           #   f  ##      #  #l     f   #   b r              #       ###              ###     #
#  ####       ####       ####      #  #      ##    l           ##      ##   ##     c            ###      tr    g ###     #
# #####   ##  ####  ##   #####     #  #      ##    f #l #       #       #    #             #### #######      ####### #####
#  ##     ##   ##   ##     ##      #  #      ##      #  #  l                               #### #######      ####### #####
#              ## a     l         r#  #      ##             g       b         r            #### #######      ####### #####
#                               #             ## # ## ###  #                f        t              ###     b###         #
#       r                  r f ###   #  #####  #####  #   ###                  f           t####### ###  b   ### ####### #
##           ##  ##      t    #####  #  #####  ##### b#  ####                             # ####### ###      ### ####### #
###     #   ########   #     ##f# ####### # #### # ####### #f                            ## ####### ###      ### ####### #
###    ###   ######   ###    ##             r##    c #  #                ##                 ### ### t            ### ### #
#      ###   ##  ##   ###        b #r #     r## b    #r #      #    ##    #                 ### ### ###      ### ### ### #
#     ###              ###         #  #     g##      #r #     ##    #              ##   ##  ### ###b###      ### ### ### #
#     ###        r     ###         #  #      ##      #  #                           #    # g### ### ###      ### ### ### #
#    ###                ###        #  #      ##      #  #    t          l     ##             l  ### ###      ### ###  g  #
##    ##           r    ##    #  l #  #      ## f    #  #     ##             g #           #### ### ############ ### #####
##           ##  #  t         #    #  #      ##      #  # b    #                  b        #### ### ############ ### #####
#       ff  ########           tt  #  #    l ##      #  #   f        ##    ##        ##    #### ### ############ ### #####
#      ##    ######    ##c f       #  #      ## b    #  #             #    #          #       b ###   ll         ###     #
# ##   ##      ##      ##   ##  b         ##    ##     #     ################################                          ###
# ## # #### ###################    ##             lg   ##    # #f#l# # # #r## # # # # # # ###  g               l       ###
# ## # #### ###################    #  # ### #### ### #  #        b   g            l b      ##                          ###
# ##   ##   #      ##  ##   ## # #             #   # #b## # # f                            ####  r                 l #####
#         b   r                  # #    ##  ####  ##    # #          b l     fl            #######                ########
# ##   ##   #   g  ##  ##   ##  ##  g   ###     g###      ##                               ####### # #   ## ##### ########
# ## # #### #########  #### #####   ##    # #### #   t##   # f            r g              ##  ### # #   ## ##### ###  ###
# ## # #### #########  #### ###     ###      ##    b ###      # # # # # # #  # # #g# # # # #  l    # #   ## r####       ##
# g                            ###  # #              # #  ## #### ### # ###### ##### #######       # #       ####    l  ##
#  b          b               g ##    ## #  ####  # ##    ## #### ### # ###### ##### #######       # #       #####      ##
#        r                      b     #####      #####  #    # #   #     # ##   # #   # # #        # #   ## ######       #
#  g                               #      #      #      #   g  f   g                               # #   ## ######       #
#                         b     #  #       g          r #  #                         A        r    #            ##  g    #
#    r t         r  t          b##          #  #          ## # #  f#     # ##   # #   # # #        #            #     g  #
#      r                         #          ####      ##  #  #### ### # ###### ##### ######        #            ##       #
#  b                        r   ##  # # ### #### ### ###  ## #### ### # ###### ##### ######        ###      ######t      #
#        b    t    t             # ## # # ###b ### #t# ## #   # # # # # # #b # # # # # # #         ###   ## ######       #
# ## # #### #########  #### ### ## # g#   ##    ##   #  # ##          lt                           ###   ## ######       #
# ## # #### #########  #### ### #         #      #         #   g                 gl                ###   ##   ###f       #
# #g   #g   #      ##   ##   ## #    ##              ##    #                                     b ###   ##   ###        #
#       f                f      #    ##              ##    #  f                                    ###   ##   ### g      #
# #    #    #      ##   ##   ## #    b    #      #         #    l                           b    t ###   ##   ###        #
# ## # #### #########  #### ### ## #  #   ##    ##   #g # ##               g                       ####  ######### f     #
# ## # #### #########  #### ###  # ## # # ###  ### # #f## #  r# # # # # # #  # # # # # # #       b ####  #########       #
#    #  ##   ##  ##    #  #   # ##  ### ### #### ### ###  ## ######## ######## ##### ######    A   ####     ######       #
#      g                      a  #  ##  t   ####      ##  #  ######## ######## ##### ######    g   #       b    ## g     #
#    #  ##   ##  ##    #t #   # ##       t  #  #          ## # # # #   # # ##   # #   # # #        #            #   f    #
# ## # #### ######  #  #### ### #  #  f                 #  #        b                              #            ##      r#
# ## # #### ###### ##  #### ###           #      #                                   a        b    #### ##########  r l  #
# #  #      #      ##    ##  ## tt    #####      #####       # # # # # #r# ## # # #   # # #  Ag    #### ##########   f  t#
#               t  r        r   ##    ##f#  ####  # ##    ## ###############################       ####      #####      ##
# #  #      #      ##    ##  #####    #              #    ##################################       ####      ####       ##
# ## # #### #########  #### ###      ##  t   ##      #        # # # # # # #  # # # #l#b# # #       ####  ##  ####       ##
# ## # #### #########  #### #####    #    # #### #b    #   ##                       f      ##  ### ##################  ###
# ##   #    #      ##   ##  ##  ## g    ### r    ###      ##   g         b r        f     g####### #######################
#    b                           ###        #### g##    ###                                #######                ########
# ##   #    #      #    ##  ##r# # ## # #      #r    # ## # #                f    r        ####                l    l#####
#### # #### #####      #### ###    #  # ### #### ### # b#      g         l                 ##                          ###
#### # #### ####  ###  #### ###    ##                  ##    # # # # # # # ## # # # # # # ###      g                   ###
###  #   ##  ##  ##      ##  ##f    #  t  ##    ##    g#     ################################                          ###
##########################################################################################################################
