metadata:
  gen_time: 0.8432803153991699
  timestamp: '2025-04-11T22:06:39.104887'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
####################################################
##    ##     ##    ##  #####  ##           #########
##    ##     ##    ##  #####  ##  #######  #########
##    ##           ##  #####      #######  #########
##    ##           ##  #####      #######  #########
#     ##           ##  #####      #######  #########
#     ##           ##  #####               #########
#     ##    ###    ##  #####               #########
#     ##    ###    ##  #####       ######  #########
#           ###    ##              ######  #########
#           ###                    ######  #########
####                         ###   ######  #########
####             #####  ##   ###   ######  #########
####      ####   #####  ##   ###   ######  #########
#         ####   #####       ###           #########
#         ####               ###                   #
# ###     ####               ###    #####          #
# ###                        ###    #####  #########
#                  ####             #####  #########
#                  ####                    #########
################   ####    ##              #########
################   ####    ##    ##        #########
################   ####          ##        #########
#                                          #########
#                           ##             #########
#    ###     ######         ##    ##  ##   #########
#    ###     ######               ##  ##   #########
#                                 ##  ##   #########
#                                 ##  ##   #########
#  ##########                         ##   #########
#  ##########    #####       ##       ##   #########
#                #####  ###  ##       ##           #
#                       ###           ##           #
#                                     ##           #
#####                         ##                  ##
#####             #####       ##                  ##
#                 #####            ##     ######   #
#         ####           ###       ##     ######   #
#         ####           ###              ######   #
#         ####           ###   ##         ######   #
#         ####   ####    ###   ##                  #
########         ####    ###   ##                 ##
########                 ###   ##        #####    ##
########                 ###   ##        #####    ##
########          ##           ##                  #
########  #####   ##           ##  ##              #
########  #####   ##           ##  ##         ##   #
#                       ###        ##   ##    ##   #
#                       ###             ##    ##  ##
#          #######      ###             ##    ##  ##
#########  #######                            ##  ##
####################################################
