metadata:
  gen_time: 1.6578419208526611
  timestamp: '2025-04-11T22:25:27.859663'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |##      ###|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |##      ###|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
####################################################
#         ########              #########          #
#         ########  #########       #####        ###
# ######  ########  #########                  #####
# ######  ###                                  #####
# ######                             ##  ####  #####
#                             #####  ##  ####      #
#                ###     ##########  ##  ####      #
##########       ###     ##########  ##  ####      #
##########       ###    ###########  ##  #####     #
##########       ###    ###########  ##  #####     #
#                ###    ###########  ##   ####  ####
#                ###    ###########  ##   ####  ####
#############                        ##         ####
#############                                   ####
#              ###       ###   ####        ##   ####
#              ###    ######   ####   ##   ##   ####
# ####    ##   ###  ########  #####   ##   ##      #
# ####    ##   ###  ########  #####                #
# ###     ###  ###            #####            #####
# ###     ###  ###            #####     ###   ######
# ##     ####  ###            #####     ###   ######
#        ####  ###  ########  ######    ###   ###  #
#        ####  ###  ########  ######               #
#        ####  ###            ######               #
#              ###            ######   ####    #####
##             ###   ####              #############
#############        ####              #############
#############        ####  ####        #############
#############  ###   ####  ####       ##############
#############  ###   ####             ##############
#######         ###  ####                 #####    #
#               ###          ##                    #
#               ###          ##                  ###
# ###  ##      #####         ##               ######
# ###  ####    #####         ##       ###     ######
# ###  #####   #####  ####   ##       ###     ######
# ###  #####   #####  ####   ##       ###     ######
#                     ####   ##       ###     ######
#                     ##    ###       ###     ######
#                           ###  ##   ###         ##
####  #####                      ##   ###          #
####  #####  #########           ##   ###    ##    #
####     ##  ############        ##   ###    ##    #
###          ############        ##          ##    #
###                 ######                   ##   ##
####                  ####  ##          ##       ###
####    #####               ##        ####       ###
####    #####               ##    ##  ####         #
####    #####   ######      ##    ##  ####         #
####            ######            ##  ####   #######
####################################################
