metadata:
  gen_time: 3.775144100189209
  timestamp: '2025-04-18T22:58:01.385523'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#               #  # ###        ##    ##     #    l    #     #     ###    ##     ########          ######  ###############
#                 #   #    g     # #   #    ##        ###          ###  rr  g  ########## l g ###########  ###############
#     g    l    ##     #####f  b  ###      ### r     #####           l         #### t####     ###########        l       #
#            ##t#       ###        ##  #    ## f               g                 ##  #### t      #####         a         #
# g   #      ###         #          # ##     #    # l            l    ######f    ## r####        #####       t   f       #
##f   ##     ##           #####       ##          ##                  ######     ##  ####        #####      A         r  #
##    ###    # b           ###        ##  #  #    ###                 ######         ####        #####          #######  #
##    #          #####   f  #          # ##  ##   ## #       #        ###     ##  #####          #####          #######  #
##    # f #  g    ###          lg       ###  ###  #  ##      #       b###     ## ###### ###########     ##################
##        ##       #     b               ##  ##      ### #####     ######             # ###########     ##################
##   r    # #      b#####                g#  #  b    ##   ####     ######             # ###########           ##     #####
##          ##       ###                             #     #      r######               ###########           ##     #####
##          ###       #                   f                      r  b llb              ############   r     g ##r  b #####
##          ## #       #####             #                 #               ##         ###########                    #####
##        # #  ##       ###             ###       g   g    ##             g        ##############      l           g #####
##        # #  ##       ###             ###                ##               ##     ##################   t b      g   #####
##          #  #      r#####             #                 # ##          b    b    ##################     t          #####
##          # #r      #          f                           ##                    ##################       t        #####
##                   ###                 tf          #b    # ##            f       ####        ########        g     #####
##        # #       #####r                #  #       ##l  ####### t                ####        ########         ##########
##   t    ##       #                b    ##  ##      ### ########   ##             ####        ########         ##########
##    #   #       ###                   ###  ###  #  ##      ####   ##       ##########        ########     t       ######
##    #   g      #####  r   #         f# ##  ##   ## # f     ###### #     l  ##########        ########             ######
##    # #    #             ###      g ##  #  #    ###        #####           #######           ###  ###             ######
## l  #      ##           #####       ##          ##         ##### # #       #######r          ###b ###           ########
#     #      ###         #          # ##     #    #                  ###############        ######  ###       ## f########
#            ## #       ###        ##  #    ##                     #################      t ######  ###       ##  ########
#            #  ##     #####      ###     l###f      #####     t   ############             ######  ###       ##  ########
#             g ###   #          # ##  #    ##      t ###                  ####                     ###       ##  ########
#               ## # ###        ##  # ##     #         #  g  ##            ####                     ###       ##  #####  #
#   #     # #       #    a  #   #     #     # # # #  gg   #l      f#  #   ######                    #           ##    #  #
# ##### # # ####### #a##### ### # ### # ##### #l# # #######        #r #   #      #   b        t     #    #####  ##    # f#
#   #          a  # # # # c       #   # #     #  r   a#            ####   #rt    ###         t    #### ###   #######  #  #
# # # # #    ##  ##   #   ##### ##### # # ##### # #####a# ###      ####t  ##       ###  ###########       g        # ##  #
# #   #                         #     # #     #     #   #          #  #    #         ####                          # ##  #
# #######       #c# ### ### ### #l##  # ### # # ####### # ###      #  #    #   g     ####      c        r   ######## f# ##
# #   #       #   # #   #   #  a  # #   # # #     #     #  a         ##        #######  #  ########### ######  #        ##
### ##### ######### ####### # #r ## # # # ### # # # ### # #f  ##   ###      # ##        # ##     ## g   #      #        ##
#           #     #     # # # #         a #   #     # #   #       #    ###  #             ##     ##     #      # ###  ####
######### ### ### ####### ### #   ### # # ##### # # # # #r#     f        ##    ########      #######    #c       #      ##
# #   #   # #                     # #           # #       #      r               #  #          #   #   ####      #      ##
# # # ### # # ##### #a##### #   # #   ### ### # ###f# # # #   #     ### t        #             #     #    #### # # # #####
# r #                   #a  #   # # #     #   #   # # #       #### #  ##### ######  ###  f    r#   #         rAg   #     #
# ### ### ##### #   ####### ##  # # # #a# ##### # # # # ###             #            b  #  #   #  f#               #     #
#   #   # #     #     # #a# #   #         #   # # # # #   #                  t             ##### ##### #  a        #     #
### ### # ##### # ###c# # # #   ##### # # # ### # # ### # #                   t      f  g        #f    ##### # # # # #####
#     # #   #   # #             #  t  # #   #           # #           #    #### # #              #                       #
# ### ### ### ### # ### ### ##  # ### # # # ### ### # # # #     ####   A  ##      ####          f#                       #
# #     #   ab#       #   #l    #     # # c       # #   #                                     ######## ##### #        g t#
# # # #####   # ### ### #####   ##### # # ### # ### # # # ### ##    r    #######      g    ####    #      #  # #     r   #
# # #       # # #     # # # #       #     #   #  a#          ####        #  l  ###         ###     #      #    # #       #
# ######### ####### ### # # #   ##### # # ### # #########c#                                    #####     ##      # # g   #
#b#       #     c   #   #       #a    #     #   # #       #     #     g #          ####### t    #  #     #     t f # #####
### ###r### ####### #a  ### ##  ### # # # # # ### # ##### ###   ##   f ##            #          #  # # ###     b     #   #
#             #   #      f  #a  #a  #   # #b        #        r                             b    # t#     #   b       #   #
### ### ##### # # # # # ### ### # ####### # ##### #########      ##   ##             ##        ##  #     ### # #   # #b  #
#     #   # A # #b  # # #     # #   #     # #   # f     #    g             r    t     #        #   #     # r   # #   #   #
# # ##### # # # # ##### # # # # ### # ##### # # ### #######    l  #####          f    #        #         #     # #     r #
# #   #   # #   #       #g# #c  #   #     # # #     #                 # l   g         #        #     #  g##    #   # ### #
# #   #   # #   # c     # # #   #   #  a  # # #   a #                                       gb #     #    #    #       ###
#   ###   ###               ###  l      ###   ###   ###  l   #                     # #  l#   #l#       # #       r   #   #
#   ### c ###            l  ###         ### l ###   ###                 #           #     # # # lt     f  #             ##
#   ###   ### l         tf  ###         ###   ###   ###      # #           #t          # # #     # # # # # # # # # # # # #
# g ###  t###############   ### l ###   ###   ###   ###         # # # #  r  #   #   # # #         #                      #
#   ###  c###############   ###   ###   ###   ###   ###      a# # # # #   # # # # # #             #       #              #
#   ###   ###############   ###   ###   ###   ###   ###                            # # # #   #   #   #   # # # #       # #
#c t###             t             ###                     g  # # # # #l# # # # # # #   #     #     # #   #   # # #       #
#   ###f           lc        bg  l###         c     f                               #             #     # #           # ##
#   ###      l                   f###                  t    g                   # # #         #   #     #            t# ##
#   ###########################   ###b  ###   ###lb #########  # #   #     #t# # # #a#     #         # #a#     #   # #   #
#   ###########################   ###   ###   ###   ########## # # # # # #   # # # #       # #       #   # # # # # #    a#
#   ###########################   ###   ###   ###   #########                       #         #  f      #               ##
#f  ###        l###               ###   ###   ###                         # # #   # #             #  l                  ##
#   ### l       ###               ###   ###   ###            #   # # # #   # # #       #   # #       #   #   # # #      a#
#   ###    g    ###    a          ###   ###  l###                                         #       #     #               ##
#   #########   ###   #########   #########   ###   ###   t       # # # # #    a    #     #       #                     ##
#   #########   ###   #########   ######### f ###   ###      #     # # #   # # #       #   # #     #     #     # # #   # #
# gg#########   ###   #########   #########   ###  f###f  ct              #       # #     #   #   #       #           #  #
#                           ###         ###   ###   ###     l           # #       #       #l      #     # #             ##
#         t                 ### c r     ###   ###   ###            # # # #     #   #   # # # #l#   # # #     #   # #   # #
#                           ###         ### t ###   ###            # # # #     #     # # # # #     # # #     # # # # #   #
#  A###   ###########################   #########   ########        # #   #       #           #   #       #             ##
#   ###   ###########################   #########   ######### # # # # #   #       #       #       #         Aa          ##
#   ### t ###########################   #########c  ########## # # #   # #       # #         #     #     #   # # # #     #
#   ###             c ###                     ###              # # #   #     #   # #   #     #   # # #   #   # # # #   # #
#   ###        c      ###        g       f    ###          g              #               #  g#         # #  b           #
#   ###               ###              l      ###              f# #   #   #       # #     #   #   #     #             # ##
#   ###              g###              t      ###            #   #           #         # #       #   #   # # # # # #     #
#   ###  r            ###                  r  ###               #   #     #  a                #   l                      #
#   ###            l  ###                     ###          c # #         #   # #   # #   #   #t#         # # l      a#   #
## alt    #a   # #    # ## # #  # # ## #    # #    #     a  ##      #     r       g                     t   g  # # ### ###
## ######## #### # #### ##    g     ## #### # #### ######## ##      #  #       #    #            #    #       #  #      ##
#            a        l ## ###  ### ##          f     a             #           #  ###          ###  #           #       #
## ############### #### ## ###  ### ## #### # ############# #       #     #         #    #  #    #     f   #     #       #
#         aa     #                      a   #        c    #lr  g    #    #              #    #   l          #    #     lf#
# ##             # # #########  ######### # #   a         ###       #                 l     l                   l#   g   #
#                # # ######### b######### # # a             ## #    #f #          #                #    g     #  #    # ##
#  l             # #      b               # #       t       #  #    #   # #    #  #                #  #    # #   #    #  #
# ##             # # # ##### #  # ##### #a# #        l    ###  #    #     #     # # #         l  # # #     #     #    #  #
#  #       g     #     #     #  #     #     #    g      b #         #     #          #          #          #     #l      #
#  #     ##    a ### ### ### #### ### ### ###      ##    f#         #l#   #                                #   # #       #
#  #     ##     c  #              a       #    a   ##     #  #   #     #  #l           #   f  #           g#  #    g#   ##
#  #     ##        #   ### ##### #### ### #        ##     #      #    l   #  #          # ## #     g   r#  #        #    #
#  ###    l        #          ##        # #b            ###      # #      #   # #   #     ##     #   # #   #      # #    #
#    #         l   #         g## b g    # #   a b       #           #  #        #  l #    ##    #    #        #  #       #
# ala#             # #   g    ##    A   # #     lA     l#           #  #        #    #    ##    #    #      b #  #       #
#  ###           a # #        ##        # #     f       ###      # #      #   # #   #     ##     #  g# #   #      # #    #
#  #     ##      g # # ### ########## ### #        ##     #      #        # f#          # ## #          #  #        #    #
#  #     ##        #                      #        ##     #  #   #     #  #            #      #        l   #  #     #   ##
#  #    a##   l  ### # # # #g#### ### ###b###      ##     #        b# #   #                   g      f     #   # #       #
#  #             #     # b   #  #r    #    g#             #         #     #          #          #  c       #     #       #
####    r    gt  # # # ### # #  # ##### # #l#            t###  #    #     #     # # #            # #A#     #     #   t# g#
##        r   f  # #     a  l             # #   b           #  #    #   # # g  #  #                #  #    # #   #  r #  #
##      a        # #b #### ###  ######### # #     g         ## #    #  #         r#  g             #          #  #    # ##
####      a   g f#b#  #### ###  ######### # #       t     ###       #    l                                       # A     #
#  #     b       #   br                     #    g        #         #    #              #    #    r    t   l#g   #       #
## ############### #### ## ###  ###a## #### ############### #       #     #         #    #  #    #         #     #     c #
#                   a   ## ###  ### ##           l                  #l          #  ###  gf      ###  #           #       #
## ######## #### # #### ##   l      ## #### # # ## ######## ##     g#  #       #    #            #    #    b  #  #      ##
##        #    # #    # ## # #l # # ## #    # #          g  ### ###   #         l                              # # ### ###
##########################################################################################################################
