metadata:
  gen_time: 3.4907000064849854
  timestamp: '2025-04-18T22:55:36.688199'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#   #  #### # # #         #                                                          # # ##       b r ###      ###       #
#  ###A###  l #     r    ### ## ##      l  ###     #  ##        f###l# ###   #  #  #   #       gr     ###      ###       #
# #### l#   # #         ####    ### #       #         ###                 ## ##  ### # #       A ########      ######## b#
# #### #    # #      l #####                                                         #       g   ########      ########  #
# ###  l  # #  #      #####  r   ###         ###      #####    ###                   #   b###    ########     r########  #
#      #    #  #     #####  l     #                                                  #    #           ###      ###b      #
#         #      # #  ###    f     ###     ###          ###  # #####  #          ### # ## # ### g t   ###      ###       #
#      #      #    #   #                                                           #f ####    #  ########   r  ########  #
#   #  #       #   # ##           #    # ####g#           ###### #   l #### # #### ##  ## ### #  ########      ########  #
#      #  #        # ##          ###r#                                               #    # l    ########    b ########  #
#  ##  #  #        # # #rb      #####  ###  ##### l      #  #####    ### ## ### r    #    #  l b      ###      ###     b #
#  ##     # #  #   #   ##      #####    #    #####      ### #### #  ####   ####      #    #           ###b t   ###       #
# ###     #   #    #   ###    #####f  l       #####                              ### ###     c   ######## t    ########  #
#  #      # # ##   a ######  #####             #####  # #####  #   ##        #   #     #    t##  ########      ########  #
# #         # ##     ##### ## ###l l            ###     ####    ###### l      ####     ###       ########   b  ########  #
# #         # ###     ###  ##    f               #                               #       #       ###  r             ###  #
#  #t     # # ##       #   ## #  l      #      tg      # #     #  ### #      # # ### ### ###  #  ###        br      ###  #
#  ##     #   #    l     # #  #     r  ###     b                                   #       #  #  ###  ###      ### t###  #
#  ###    #    ##  #     # # #        #####      #  #####  l #####  #####  #####   ### ### ####  ###r ###      ###  ### f#
# ###  #  #    l## #     # #  # #    #######    ###                                  l #         ###  ###    r ###  ### g#
#      #  #      # #       # ##       #######  #####l##  f## ###      #  ###           #  t l    ###  ###      ###  ###  #
#   ## #        c    ##  #   #### ##     ### ##                                   ###            ###  ###      ###  ###  #
#    # #                     ###   ##    ##  ###        ######  l      ##### ###g #       f ##   ###  ############  ###  #
#   #  #  #    b   # ###      #    #l#l  #   ####                                 # ####        l###  ############  ###  #
#  ### #  #          ### #          ###       ####                                  #  #        b###  ############  ###  #
# ####    # #    # #     ##    #      #  #     ###  f   # ##  ##                 ## #  #                                t#
# #### #  # #   ## #   #####  #                 #   g#  ##  ####    # #                ###                               #
# ###  #  # # ##   #    ###  #      #            # ##  ##  r ###                 l ##    #       ###  ############  ###b #
#      #  l   ###            ##                 # #### #      #   ##     ###             ###     ###  ############ r###  #
#    # #  #   ###       c  # #                     ####     f  ###### # ##### # ###  ##          ###  ############  ###  #
#    # #  #   ###          #  #                 # # ### l      #####                             ###  ###      ###  ###  #
#   ## #  # # ###          #                        ###        ##                     ####ft     ###  ###      ###  ###  #
#    # #      ###          #  # #               # # ## #      #          ###          ##         ########   b  ########g #
#      #    # ##A# #     ##                         #  ##    ### ## ### ###   # # # # ####       ########      ########r #
# # #  #  # #      # r   ###                    # # l ####   ####  #####                 #       ########      ########  #
#   #     # # g    # ## ###                           ### ## ###    #####  #### # # # #  ####              f  b          #
#  ### #  #              #     #         A      ##     #      #      ### #  ##    #  ##                              g   #
#  r#  #  #        #  ###g   a#t#              ## #     # ##        r #g              # r                                #
# ##   #           #  ###    ###  #           ##  #     # ##  f                                               ll         #
#      #           g  ## #   ####                 # #  #  ##  #  f     ######         ####       A                     l #
#      #  #   ag # # ##l   # ####                 #   #       ##      #   ##   # A#  ###                                 #
#  #   #  #     ## #       #  ###                ##   ##      ###    ###     #  #f# # ####b      ########      ########  #
#    #    # #  ### #     ###                        # ##      ####  #####    #      #    #  g  l ########      ########  #
# ###     #   #  #       ###  #                   # # ##      ### ##                # #  ###     ########      ########  #
#  #      #   ##         ###  #                   # # ## #     #  ###                 #          ###  ###      ###r ###  #
# #         # ###     #   ## # #                 #  # #          #####                #          ###  ###      ###  ###  #
# #         # ###f   ##  # #                        #  #   #     #####  r     ##  #              ###  ############  ###  #
#  #      # # ##     ##  #    ###              ####              ####        #    #     tb    f  ###  ############  ###  #
# ###     #   #    #          #####           #####   a##  #      ## # #    ### #         ###    ###  ############  ###  #
# ####    # #  #   #    #      #####        r#####     b##              #  #### #     r   #                              #
# ###g #  #   cc#  #   #  f     #####    #  #####   g l  #           #                    #                     l        #
#    # #  #     #  #             ###  #    # ###l              ##  rlr#  ### # #   #             ###  ############  ###l #
#   #  #       #   #  #           #           #           #            ####        #   t         ###g ############  ###g #
#      #      ##   # # #           # ##      #           #       ##    ### # #     g             ###  ############  ###  #
#         #   ##   #   ##    c     # #    l###          ###      ###  # #          #             ###  ###      ###  ### f#
#    # #    # ###  g # ###f       #     l     #        #####  ##### #   r# #      g#  # #        ###g ###      ###  ###  #
#  #        #  ##      ####g  lf ##        f ###      #####    ###  #       ###       # # r      ###  ### g    ###  ###  #
# ## # #    #          #####    ####     g    ###     ####          #    #  #### ###b   g      g ###r ###      ###  ###  #
# #  #      # ##      a ####   ####         # ####  # ###       l## # #     ###          g       ###  ###      ###  ###  #
#   ## #      ##         ### ## ## ###     ###    #   ##         ##       c ##  ## ### ### ###t  ###   r            ###  #
#      #    # # #         #  ##    ####   #####  ## # #         # # #     # #   #   #    f #     ###     r      b   ###  #
#   ## l                ## f ##   ##    f      g ##   ##            g            ###  ## ### ##  ########      ########  #
#   ## t           t   b##   ##   ##             ##   ##        t     b           #   #  #       ########      ########  #
#  l##                  ##g  ##   ##  lA         ##   ##           bg        c  #  ### ###       ########     r########  #
#   #######   #######   ##   ##   #######   #######   ##   ##   #################l     #              ###b     ###       #
#   #######   #######   ## f ##   #######   #######   ## b ##   ################ ### ### #    #       ###  l   ###       #
#   ##        ##       f                     t     f  ##   ##t  ##    b   ##     #      ## c  #  ########      ########  #
#   ## g      ##             g                 f f    ##   ##   ##  c     ##c   ## # # #   ## #  ########bg   r########  #
#   ##        ##                       f l            ##   ##   ##        ##       ##  #  ####t  ########      ########  #
#   #################   ###########################  f#######   ##   #######       # # # # ## #       ###  g   ###       #
#   #################   ###########################   #######   ##   #######         ##A #    #       ###   l  ###       #
#      t           ##             ##  lc    ##                  ##        ##         # ### ## #  ########      ########  #
#         g        ##      t      ##        ##  t        l      ##    g  l##    b   f  #         ########      ########  #
#                  ## l           ##    t  b##               b  ##        ##           # g       ########      ########  #
######   #######   ## b ############   #################   #######   #######f           f      g   b  ###   r  ###       #
###### f ####### l ##   ############   #################   #######   #######      l    #       r   b  ###      ###       #
#            l##b       ##                       ##        ##                     ##      ##         b##  ##  ##    r    #
#       t  l  ##        ##  f                    ##        ##                     ##r     ##        f ##b ##  ##         #
#             ##        ##                  g    ##   c    ##          c          ###### r##  ######  ##  ##  ##  ########
#   ##   ##   ############   ##   ##   ###########################   #######      ######  ##  ######  ##  ##  ##  ########
#   ##   ##   ############   ##   ##f  ###########################   #######              ##  ##  ##      ##      ##     #
#   ##   ##                  ##   ##                                      ##   g          ##  ##  ##      ##      ##     #
#   ##   ##                  ##   ##                    l            bg tt##      ##  ##  ##  ##  ##  ##  ######  ##    r#
#   ##   ##              f   ##   ##f     c  g                    f       ##      ##  ##  ##  ## g##  ##  ######  ##     #
###########f  ############   ##   ##   ######################   ##   #######      ##  ##  ##  ##      ##      ##     b   #
###########   ############   ##   ##   ######################   ## l #######    r ##  ##  ##  ##      ##      ##      b  #
#                       ##   ##  l##        ##             l    ##        ##   l########  ##  ##  ######  ##  ##  ########
#                     A ##   ##   ##      l ##                  ##     g  ##    ########  ##  ##  ######  ##  ##  ########
#                       ##  r##   ##        ##            f     ##   f    ##    f         ##  ## t##      ##  ##        c#
#        b              ##   ##   ## f     r##                 f##        ##              ##  ##  ##      ##  ##         #
#    t                 l##   ##   ##        ##       b          ##        ## c    ######  ##  ##  ##l ##############     #
# g                     ##   ##   ##      b ##               f  ##        ##      ######  ##  ##  ##  ##############     #
#                       ##   ##   ##        ## g                ##      t ##       t  ##      ##  ##               A   c #
#  t                 l  ##   ##   ##   b    ##                 g##        ##  g       ##b     ##  ##   r   c             #
#                       ##   ##   ##     b  ##                 t##        ##  t   ##################################     #
###########   ############ ft##   ##   ######################   ##   #######      ##################################     #
###########t  ############   ##   ##   ######################  t##   #######   b  ##                                b    #
#  r##   ##                l ##   ##                            t         ##      ##                   b b           t   #
#   ##   ##                 l##   ##       f                       t      ##      ##                                 cg  #
#   ##   ## t                ##   ##   t                           c      ##g     ##                   r                 #
#   ##   ## t ############   ##   ##   ###########################  l#######      ##################################     #
#   ##   ##   ############   ##   ##   ###########################   #######      ##################################     #
#      t      ##f       ##            g          ##        ##    g                    ##      ##  ##                   r #
#             ##  l   b ##        l              ##     c  ##                g        ##  g   ##  ##        r            #
# g           ##        ##                       ##     l  ##             f       ######  ##  ##  ##  ##############     #
######   #######   ##   ############c  #################   #######  f#######      ######  ##  ##  ##  ##############     #
######   #######   ##   ############   #################   #######   #######              ##  ##  ##      ##  ##         #
#       g          ##             ##  t     ##                  ##        ##              ##  ##  ##      ##  ##         #
#              g g ##     l      t##     t  ##          g     f ##      b ##    ########  ##  ##  ######  ##  ##  ########
#b g          g    ##t            ##        ##   f         l    ##        ##    ########  ##  ##  ######  ##  ##  ########
#a  #################   ###########################   #######   ##   #######t     ##  ##  ##  ##      ##      ##   r     #
#   #################   ###########################   #######   ##   #######  b   ##  ##  ##  ##      ##      ##       b #
#   ##  t     ##  b          l             b  b       ##   ##   ##        ##g     ##  ##  ##  ##  ##  ##  ######  ##     #
#   ##      l ##               c        c     l     l ##   ##   ##        ##    r ##  ##  ##  ##  ##  ##  ######  ##     #
# t ##        ##                               tr     ##   ##   ##     t  ##              ##  ##  ##     r##      ##     #
#   #######   #######   ##   ##   #######   #######   ##   ##   ################     a    ##  ##  ##     l##      ##     #
#   #######   #######   ##   ##   #######   #######   ##l  ##   ################  ######  ##  ######  ##  ##  ##  ########
#g  ##                  ##   ##   ##             ##   ##       l                  ######  ## c######  ##  ##  ##  ########
#   ##    t      l   l  ##   ##   ##         t   ##   ##  t f             b  b    ##ct    ##   r      ##  ##  ##         #
#   ##                  ##   ## g ##             ##   ##        t                 ##      ##          ##  ##  ## t       #
##########################################################################################################################
