metadata:
  gen_time: 4.634533882141113
  timestamp: '2025-04-18T22:54:51.060312'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#g    A  ##      #####    ##            ###  ##    ###        ###  t   ##  ###############################################
##      ####     #####         ##        ##     #######  ## t#### t        ###############################################
####    #####   #####        r ##r    t        ############ ##### # ll                g f         g   f b  bf   r  r     #
#####     ###   ####l     g          ##   t      ##  ###### ##### ##  ##   ############ # ######### ### # ### ### ##  ####
#####      ###   ## r     ##       ######r             ## t #  ## ##  ##   ############ # ######### ### # ### ### #   ####
####       ###          #####    ##########t                    l #   b         l   f                           b    f   #
####      #####         #######b ####  #####           f                    ##### ### # # ######### ### # ###  #   # # ###
###       ######  ##      #####   ##     #####  ##     ##   #               ##### ### # # ######### ### # ###      # # ###
##    ## tl #########       ##    ##  l   ##########  ##### ###   #           b   l              b              l        #
##    ##      #######        r             l############### ##### ###       ### # # # # # ########  ### # ###  #       ###
#               ####   ##                     ##  #########  #### #####   l ### # # # # # ########  ### # ### #   ## #####
#         ##    r ##   ##    ##         ##          ######r    ##  #####  #         l         f      b      f         f  #
##   ##   ##               #####      ##### r  t t   #####           ###### ### # # # # # ##### ##  ##  #  ##     # ### ##
### r##                  g #####  ##  #####    ##    ####   t         ##### ### # # # # # ##### ##  ##  #  ##     # ### ##
###t        r    ##         ###   ##   ##     ###      ##           b   ##                      t                        #
#             b  ##   ##    g##    f l        ####f         ##        t    #### # # # # # ##### #   ##      # #  ## ### ##
#       ##   ##       ###                    #####         ####            #### # # # # # ##### #   ##      #    ##     ##
#     #####  ##b     ######      ##     ##   ###### l##l ########                                                        #
#     #####        ########## b  ##     ###    ####  ##  ########## l b    ############  ######## #### ###### ############
#     #####  ##      ######      ##     ##   ######  ##  ########b         ############  ######## #### ###### ############
#       ##   ##       ###                    #####         ####                       f        lt           g            #
#b               ##   ##     ##       r       ####      t   ##             ##### ####### ############# ####### ###########
###l             ##   A     ###   ##   ##     ###      ## r           g ## ##### ####### ############# #######  ##########
###  ##                    #####  ##t #####    ## t  ####     l  g    ####             g                      b       g  #
##   ##   ##               #####      #####   l   t  #####    l      ########### ##################### ################ ##
#  r      ##      ##   ##    ##         ##          ######     ##  #####   ##### ##################### ################ ##
#               ####   ##                     ##  #########  ##########  l     a                     f                   #
##    ##      #######                       #########################  t  b###################### ##################### ##
##    ##    #########  f l  ##    ##      ##########  #########  ##     f  ###################### ##################### ##
###       ######  ##    t  ####   ##b    #####  ##t    ##  ##             r           f            f            b        #
####      #####   t     #######  ####  #####     b                          ########### ######### ## ############ ##### ##
####       ###          #####    ##########      fg    l    bt   ##      r ############ ######### ## ############ ##### ##
#####     f###   ##       ##  b    ######              ##  ##  #####  ##                                t   f        b   #
#####   r ###   ####                 ##        t ##  ###############  ##   ############################### ### #  ####  ##
####t   #####   #####          ##              #################### g      ############################### ###    ####  ##
##      ####     #####      r  ##       r##  ##########  ##  #####           l l                            b        l   #
#        ##      #####    ##         b  ###  ####   ##  g  t  ###   l  ##  ### # ######################### #####  ####  ##
#f    ###         ###   g###         ###        f #  #            #  #  #  #             # ##  #  #     ##   ###  #  #   #
#  ###### ####### ###    ### ####### #######      #  # g    ####  #  #  #      #   #     #     #  ## #  #  #   #  #  #   #
# ####### ####### ###    ### ####### #######l##   #  #      #  #  ####  ########   #######a    #     #  #  #   #  #  #   #
# #######l#######f###    ###l#######t#######  #   #  #      #  #    b                          #     #  #  #  b#  #  #   #
#         ###    f###    ###     ###          #a  ## #b     ## #   r       f                   #     ####  #####  ## #  ##
# ### ### ### #######    ####### ### ### ###  #     g#       g #        b   f       ############                     #  ##
# ### ### ### ####### f  ####### ### ### ### ##      # f  f    #  ##### l g #####   #                 g    g         #  ##
# ### ### ### #######    ####### ### ### ###      g  #######   #      #     #   #   #  #         b ################  #  ##
# ### ###g###     ###rt f###     ### ### ###               #   ## #   # ##  # b #   #  ###### g        b         b#  #  ##
##### ### ####### ###    ### ####### ### ####      a       #  g   #   #  #  #   #####       #      #      #      b# ##  ##
##### ### ####### ###   l### ####### ### ####              #      #   #  #  #               #      #  #####  r    #      #
##### ### ####### ###    ### ####### ### ####       ########      #   #  ## #   b  f        #      #  #      ######      #
#  ff ###                        ### ###l     b    r#             #   #     # f      # ######      ## #      #           #
#t    ### ###    c               ### ### t                    #####l  #     #  Ag    # b            ag#      #           #
#f    ### ### t                g ### ###            #      b      #   #     #        ########      ## #      #     l   f #
##### ### ####### ###    ### ####### ### ####       ########      #   #f ## #          b    #      #  #      ######      #
##### ### ####### ###  r ### ####### ### ####              #      #   #  #  #    a          #      #  #####       #   g  #
##### ### ####### ###    ### ####### ### ####              #      #   #  # a#   #####      f#      #  r   #       # ## A##
#                 ###    ###     ### ###f###               #f  ## #   # ##  #   #   #b ######   f  #              #  #A ##
#f### ### ### #######l   ####### ### ### ###         #######   #  #  a#     #   #   # a#           ################  #  ##
# ### ### ### #######    ####### ### ### ### ##      #   b     #  #####b    #####   #          f                     #  ##
# ### ### ### #######    ####### ### ### ### b#      #    c    #  l                 ############ g  g  l             #  ##
#         ###     ### l  ###  r  ###          #   ## #     l## #                               #     #### f#####  ## #  ##
# ####### ####### ###   t### ####### #######  #   #  #      #  #                             r #    f#  #  #   #  #  #   #
# ####### ####### ###    ### ####### ####### ##   #  #      #  #  ####  ########rg #######  a  #  g  #t #  #   #  #  #   #
# ####### ####### ### t  ### ####### #######      #  #      ####  #  #  #      #   #     #     #  ## #  #  #   #  #  #   #
#     ###         ###    ##  lr      ###          #  #          l #  #  #  #       #     # ##  #  #  #  ## # ###  #  #b  #
# #######  ##########       ### #      # g  #        #   #                g # #      ###     t                    f      #
#                     t    #### #      #   g             #      # #                # # ## ##     ##########       ########
# ######## ###### ### ###  #### #                               # ##        g     ##    #####     #########       ########
# ######## ####g# ### ##   ##   #    #                  ## r             # #            #####    ##########       ########
# ####     ####      A#######   #  #                   ##   #   # ##    ## ##     ##     ## ##  ##     c         c       #
# #####    ####       ####### # #  #                   ##  l#   # #                #         ####             c          #
#l       ###### # ########### ###  # r #   bl                           ## ##      f          ##    ####             #####
#        ######## ########### ###         l       g               r      # #                 ####   ####   ### ###   #####
#   a    ####     ######      ###            f   l          l            A           # ##           ####   ### ### c #####
#######t #####  ########      ####      ###   r     #      b#                        #####   ####  #####             #####
#######  ###### ####      ########               #  #  ###                 # #       #####    ##    ####          r  #####
############### #####    ########                      ######    # #    l ## ##       ## ##  ####  #####  ###   ###  #####
######################   ########                        ####   ## ##                     ####  ########  ###   ###  #####
# ####          ###### t ########  #    ###     g     #######             ##r##  r         ##    ## ####  ###  r###  #####
#  ###  a##     #####    ####           # #A   #  #   ###   #   ## ##      # #     #      ####      ####  ###   ###  #####
## ###a ####    ############## f #                #   ###   #    # #              ##    ###  ##     ####  ###   ### c#####
## ### ######t  ##### #########  #  b # #  #            #   #                          ###    ###     g c ###   ###      #
## ### #######  #####  #########           #      ##                     # #      ##  ##       ####       ###   ###      #
## ### ######## #####   #########                    #    ##            ## ##     b# ##          #####f   ###   ### cA ###
## ### ######## #####l        b            l                                     g   ##       l    ###   c###   ###    ###
##  ## ########  #### ####  ###########                        #        ## ##         ##    ##      ##    ###   ###    ###
##  ##  #######  t### ####   ### #  r        ###   #           #         #b#         t ##  #####   ###  c ###   ###    ###
#        ######       a        t   #   f  ## #####             #                       l####  ###   ##    ### r ###    ###
###       ##### #####                                           #  b  g       # #   #    ##         ##c   ### c ###    ###
####       #### #####  ##    ####          ##          #   ####        # #   ## ##      ####  ### t ##    ###   ###    ###
######                 ###   ####    #####                 ####       ## ##         #   ####   ###  ##    ###  g###    ###
######  ###### ####    #### l        #####  #  g   ##    ###### #            ## ##       ## l ####       cg          c   #
###### ####### #####   #####    #    # #### #b   g ## #   #           ## ##   # #       ###   ###                        #
###### #######  #####  ##   t   #      ####     ##  #                  # #                     ###   r            g   r g#
######  ######   ##### ##     # #  #     ##  #  ###              # #                    ####                    f        #
######   #####  g #######    ## #    l    #  ## ###          ##### ##                    ##    ###  ##    ### g ###    ###
#### #    ####gt   ######  r### #  #         #####           ##                                 ### ##    ###   ###    ###
####       ###        ###  ####  ########l    ####   #          ## ##                         g  g  ##    ###   ### c  ###
# ##   #######  b#### ###  ####     ######          ##           # #            A        l      ### ##    ###   ###f   ###
#  #    ######    ### ###  #### ##########     ########     # b                  b  l# # # # r ###  ##  g ###   ###c   ###
#  b     #####g    ## ###  #### ####  ####                  #               # #     g# ### ##       ##    ###   ###    ###
#    #    ####  #####      #### l g   ##   g     #              ###################### ### ##  ###  ##    ###   ###    ###
#    ##    ###b######       # #               #  ########  #    r                    # # # #    ### ##    ###   ###    ###
#f  b###    ##b###    #######      #  ###     #           t  ##            t       r           ####       ###   ###      #
# #######  b # ### ## #######    g ######     #  l           ## #####################    g l   ###        ###   ### f g  #
# #######      ### ## #######  l   ####   g #### #             g#####################           ### ####  ###   ###  #####
# #######      ###### a            ####     #### #               ##    ##  ##  ##                 ######  ###   ###  #####
# #######  ##########     #####    #### #        #            ##          c r        ##            #####  ###   ###  #####
# #######   #########     ####        ###        # ##  #   #     ##    ##   #  ##   ##   b  gg##    ####  ###  g###  #####
#     b    tt#####        ##    b            #           #      ######################       ####  #####  ### c ###  #####
#####  ######################### #   #       #         f        #######################      ####   ####             #####
# ###  ########### #############     ####    #                ####################### ##       #    ####             #####
#  ##  ########### ###        ##                        g     #######################  ##    # ##   ####   ### ###   #####
#       #####      ##### t    ##  ###    ##          g   #       ##    ##  ##  ##  b#  ##   ##  ##  ####   ### ###   #####
####  # ######  t  #####  ######  ###           #####    #  g                           ## ##    ## #### f   cc      #####
##### # #######           ######  ###         l          #    #  ##    ##  ##  ##   #   ## ##     ##  cc    c            #
#####      a                 b    ###   f l          #  r##   # ###################### ##   ##    ##                     #
######            #####           ### r  #            t     ### ########################    ##   ##b#######       ########
#      ##   ### l #####  #        ##     ###           g r  ###                      ###     ## ##g #######      c########
# ########   ## f     # ##  #####    #   g   ##          ######             l        #       ## ##  #######     f ########
#  ########  t#b  t ###### ######    #                      ### #####################   ### ##   ##                      #
##########################################################################################################################
