metadata:
  gen_time: 6.5062549114227295
  timestamp: '2025-04-18T22:48:29.647628'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#                          rf       #            ############## ## At##################### ##### #########################
## ###### ############# ## #####               ##    gg         ## #######################       ######             ######
##  #####l############# ## #####  ##      b   ### ##### ####### ##  ##########   #####  ##  #### #####  ############ #####
###   ### #############l##    ## # #      #     # ##### ####### #       #####  ## ###  # #  #### ###               t  ####
#                    g                  t ##      ###      #### r#       ###      ##             ## # b               ####
#######  ####    gr #########   ## A      ###   t ##        ###  #      # ##   g   #              # #                 ####
########  ###       ###########  #        ##      # #g     # ##  #   f  # ##      ##    c        ## # g        t   a b## #
######### ###  g    ###########           #       # #      # ##  #    t   ###  ## ###  ###  ## # ##                   c# #
#                 r                               # #        ##         # ###    ####  ###    ## ## #     t           ## #
## #######          #############      #     #    #        # ##  #  ### # ###  #####   ###  #### ## ### ####### ## ####  #
##   #######        ##############     ##   ###   # ##  ## # ##  # #  b # ###   ###     ##   ### ## ### #######   ##### ##
####   ######    t  ############ #     ### ###### # ##  g ## ##  # # ## # ###                       ### #######  ####   ##
#          r         f        f        ##         # ##  # ##     # # ## # ###                       ### #######  ###  # ##
#    b                      a    # g   #        #   ##    ##  #    # ## # ###                    t   ## ### g #  ##      #
######## ####  a gl ############ ##                        b          g   ##                         ## ##  #    ##     a#
########   ##    a f############ ###       #####        t                  #      g                  ##          ##      #
##########          ############ ## #       ###                    g      ##                 g    b  ## #   g    ###  #  #
#              a     rg          #  ##     tr#  # # ##  # #   #  # # ## # ##     tg                  ## #        ###    ##
############             #######    ##  #####   # # ##     #  #    # ## # ##   r## #   ###  #### #   ##  t       ###  # ##
############       f#### #######    ##   ###        ##    ##  #    # b     #   #   #                 ##  #  #    ###  # ##
#############       ####  ######    #     #         ##    ##  #    #           # # #   ###  #### #   ##  #    #  ##   # ##
#               f           t              #####     #    #   #            #   # # #   ###  #### #   ##  #  # #  #    # ##
######### #### ######## #   ####            ###      #        #  #         #   # #      ##  #    #       #  # #         b#
######### ####  ####### ###   ##             #       #        #  #         #   # #     # #    ## #   ##     # #          #
######### ####  ####### ##### ##  ####               #           #    f        #                            # #          #
#           g                      ###  g  a #    c  #        #  # #      g#                c c          b    #          #
#   g              ##########  ## ##   #########     #        #  # # #  # r#           g                      #          #
#                   # # #g# ####        # #   # # #  #           # # #  g ##                                  #  ##   # ##
#         r                   #    r#  f     l    #  #        #  # # #  # ##                                  #  ##   #  #
#                             #                   #  #        #  # # #  # ##     #     ###  # ## #   ##  #    #  ##   # ##
# # # # # # # #   #  # # # # #### #### # # # # #  #  #        #  # # #  # ##     #     ###  # ## #   ##  #    #  ##   # ##
#################        #####  ###  # # ### # #                                                                         #
################### #### #####       # # ### # #  #  #        #  # # #  # ##     #     ###  # ## #   ##  #    #  ##     ##
## # # # #r# # # #   # #      ###  #   # #   # #  #  #        #  # # #  # ##     #     ###  # ## #   ##  #    #  ##     ##
#                                         t                      f r                                     l              t#
#                             #     #        g             ####          ##     ##     ##     ##          ####    f  b   #
## # # # # # # # # # # # # # #### #### #g# # # #   c  ##    ##    c   t      g      t                      ##    ##      #
##############################  ###  ############# g #### a       #                 #                 # l       ####  t###
##############################   ##  ##############  ####        ####         t     #              b####        ####  ####
# # # # # # # # #    # # # # ###  ## # # # # # #### gb##         ######  ga                       ######         ##   ####
#                f                             r#     ##     r     ######a            g         ######       l   ##     ##
#    b                 f                  l     ba   ####          g ######     a             ######            ####     #
#                  f# #   # # ####### # # # # #       ##    b          ####  ##    # #   g##  ####l     l   g    ## b    #
# #r# # # # # # # #############  #  ############             b          l#   ##  #######  ##   #          b   tl         #
#  ###  ###            ###   a       ###### b     ## b     ##                   b#######                    ##a      ##  #
#  ###  ###       c    ###      #    ######    # #####     ##  ##b   ##   g        # #         r  ##    ##  ##     ##### #
#l ###  ###c #############      #a    ####     #  ####         ##  ######            t          ######  ## r       ####  #
#  ###  ###  #############   g l##    #t   c  ##    #    ll        #######          b          #######       r      #gl  #
#br###c ###  #############   cg ##  b ####    ##           ##       #  ##      ##l      ##      ##  #       ##          l#
# c###  ###                     ################a          ##  ##             #####   #####             ##  ## g         #
#  ###  ###    g                ################        a t    ##              ####   ####              ## b  a         t#
#f                                            ##g          t              ## b   #   l #     ##      t                   #
# c###  ################## g                 l   #             a        #####     t         #####    ga                # #
#  ###  ##################  c   b    ######     ####     #        ##    #####           b   ##### g  ##        #     #####
#  ###      g     ###   r c           ####tca  l####   ####       ##     ##      t          t ##     ##   ta  ####   #####
#                                                ##   t####                   b ##     ##                l    ####a   ## #
# c########  ########c #########      #### l            ##                a    ##### #####                     ##        #
#c ########  ########  #########   f  ####              ##       ##   ##       ##### #####       ##   ##       ##        #
#                                               ##t    ####    #####  ##         ##   ##         ##  #####l   ####     ###
#  ###b f      A  ###            c    f##    l  ###   ###   ####         ####   ###            ##    ##    ##         ####
#  ###           a###    f             ##       ##   #####l #####       ####   ####        ##                r        ####
#  ###  ###  ########  ###f     l      ##            #####   ######     ###    ###       ####                          ###
#  ###  ###  ########  ###         l   ##        l    ###l     ######  ####   ####       #####  ##  ##   ##   ##  ##     #
#  ###  ###g ########  ###      ####   ##   ####       ##        ###########  ###        f####  ##  ##   ##   ##  ##  f  #
#  cb   ###            ###      ########  ######       ###         #########   ##         ###                         ## #
#    c  ###            ###       ####### ######  ##   ####f  ##      ##  ##         ##   ###            c             ## #
######c ##################  a   b######  ###### ####  #####  ##                     ##  ####           ## A  ##  ##t     #
######  ##################     g####### r###########   ####      ##           ##        #####          ##    ##  ##   r  #
######  ##################fc a  ##################     ##        ##    ##   #####         ###      ##             l      #
#f           ###g    f    aca   ################                     ####   ######         ###     ##                ##  #
#   ba  c    ###  r        l    ################   f                 #####   ######        #####  ####   ##  ##    ##### #
#b ########  ###  ########       b  ###  ###           ##     ##      ####     ####        l##########   ##  ##    ##### #
#  ########  ###  ########           ##     c   #      ##    ###       ####     ##            ######             g  ##   #
#  #                                            #  ##      ######       ###         l           ###                      #
#g   #       ###  ###    c rc     ############     ##      #######      ####        ##           ##    ##      g##       #
#  ###c      ###  ###       f a ################            ######       ####  ##  ###     ##     l    ##     #####      #
######  ########  ##############################              ##         ####  ## l####    ##                 #####      #
###### g########  ####################   t######       ##   l           #### fl     ####       ##       l      ##        #
######  ########  ################## cr     ####      ####    r       #####          ####      ##    ##  ##            ###
#    g  ###            ###  c   ####        ####      ######          #####     ##    #####        #########         #####
#  l    ###  a     c   ###  a    ###   ##   ###         ######      b  ###      ##     ######      #########       #######
#  ##################  ###       ##    ##    ##A  ##      ######        ##               ######     ##  ###    ##  #######
#  ################## c###c                       ##        ####                           ####          ##    ##   ##  ##
#  ##################  ###b   r r##   ####   ##              ##     ## A      ##   f ##     ##              f            #
# c     ###c ###           cr    ###  ####  ###                   ######     ####f   ##           ##         f       f   #
#       ###  ### c a         c   ###c ####  ###     ##           #######     #####        l   t l ###   ##    ##   ##    #
#  ###  ###  ### c############## b##   ##   ##      ## #     ##  #####      ######       ##  ##  ####   ##  #####  ##  ###
#  ### c###r ###  ##############  ##   ##   ##  #   ## ###   ##   ##      # ####       # ##  ##  ###      f #####      ###
#  ###                                          # # ## ##  # ##   ##        ####         ##  ##  ##       #  #         ###
#  ###l #        c   f    c     ####   ##   ##  g g### ##  # ##   ##        #####      # #   ##  ##       # #####      ###
# c###cc  #a   l   flr    a  r  l###  t##   ##  # #### ### # ##    #      # ####       # #    #  ##       # ####       ###
#  ###   ##   c                  ###   ##   ##  # #### ###   ##    #      #   ##       # ##   #  ##       # ####       ###
#  ###  ###     l  f r         f ##    ##    #  # ###      # ##   #       # #          #  #  #    #       #  ##g  #    r##
#  ###a ###    c       r         ##   ####   #  # #### ### #  #   ##      # ##         #  #  ##  #        #  ###  #    #g#
#  ### t### a   a     c   f r   ###   ####  f#    a##g b## #  #   ##      #   #        #  #  ## A #       # ###a# #    ###
#               t##                         ##  #  ### ### #  #   ##      # ####       # #g  ##  #l       #  ####      ###
#            ##  ##    l      l             #      ### ##  # ##   ##      #  ####      # ##  ##  ##       # ##### #     ##
#            ##   #                             #   #  #   # ##   ##      #  ####      # #r  ##  ###      #  ####        #
#            ##   ##       b      b  f      b   # ##g#     # ##   ##      #   ###   #  # ##  ##  ###      #  ####        #
#            ##   ##    l                 ##    # ####  #  g #    ##      # #####   #  # ##  ##  ###      #  ####        #
#   t        ##   ##     t                          ## ### # ##   #       # #####   #  # ##  ##   ##      #   #f#        #
#b           ##                         A   ####     # ### # ##    #      # #####   #  # ##  ##  ###      # ##g## #      #
#             #         c        lr            #   # # ##  # ##   ##      # #####   #    ##  ##   ##      # #r#b  #      #
#  ##                    r  ###     ####       l#  ##f ##  # ##   ##      # #####   #    ##  ##  ###A     # ####  #      #
# ##              r          ###  t  ### #     r#    # ##  # ##   ##      # #####   #    ##  ##  ###         #### #    # #
####                          ##    f    ##     #   #  #   # ##         #   #l      #    ##  ##  ###      #   ### #    ###
######## g g #####    ######    ##  ########b   # # ## # # #  #   #    ##   ##      #  # ##  ##  ###      # l#### #      #
#########   #######    ####          #######      #    # # ###b   #    ## # ##      #    ### ##  ###      # ####  #    ###
#########   #######     ##         f  #####   b #  ### # # ####   #    ##   ##      #    ######  ###      # ####  #    ###
#########    #####               r     ###      g  ####     ###   ##   ##   ###     #    ######  g##      # ####  b    ###
########                f    ###                #   ####r  ####   #    ##   ###     ##   #####   ###      g ####  # #  ###
#######             ####    #####   r r         # # #####  ####   ##   ## # ###     ##   ######  ###      # ####   #r  ###
######     ##      ######  ######    g   ##     #    ####  ####   ##   ## # ##      ## # ######  ###      # ###   ###  ###
# ### l   ####     ######  #####   f    ####    #    ####  ####   ##   ## # ##      ##   ######  ###    # # ##r#  ###  ###
#         #####     ####    ###    ##   #####   # ## ####  ####    #   ##   ##      ## # #####   ###   ##   ##### ###   ##
#         #####   f               ####   ####   #     #### ###    #r#  ##   ##      ##   ######  ###   ## # ##### ##r  ###
#     t    ###                    #### A  ##ft  ## # ####f ###    g#r  ##   ## #    #### ######  ###   ## r ##### ### ####
#                      ##          ##           ###r####   #### # ###  ##   #####   #### b#####   ##   ## # #####  #######
#  ##                 ####                 g    #########  ##########  ###  ####    #### #######  ##   ###b ###### #######
# ####    ##    ###   ####l b l##               ########l############ ##### ###   # ####  ####### #   ##### #######a######
##########################################################################################################################
