metadata:
  gen_time: 11.323343992233276
  timestamp: '2025-04-18T22:49:40.493532'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#tg  #             #         ##    #####   ##   ########### #   ##############      c   ## ##          ## ##    c r   ## #
#  #            f  #          ##  #######  t##   ######       c############### #####  # ## ## ##### ##### ##### # ### ## #
#                 ##   g       ##  #######   ##   #                                  ## ## ## ##### ##### ##### # ### ## #
#  #    ########   #  #    ##   ##  #        ####                           ## ##      f   ## ##t   ##       ##   r## ## #
#  #     #######      ##    ##   ##          ####                            #### ######## ##### ## ## ## #####b# ### ## #
# ##t     #     b     #  #   ##   ##     r   ##             #################g### ######## ##### ## ## ## ##### # ### ## #
###                   #  ##a ###   ##        ##  b                           #             ##  c ## ## ## ##  t    l     #
##  #    A         #####  ##        #           #############b#### ########## ### ## ##### ## ## ## ##### #  ## # ### ####
#   ##     ##      t#    l ##    ########        #                   ######## ### ## ##### ## ## ## ##### # ### # ### ####
#   #       ##           #    g  ########   ####      ############## ########     ##b##c   ##    ## #  ## b  ## #        #
#   #        #######  #####  r#  ###  ###l  ###                     ########## ## ######## ## ## ## # g## # ### #  ## ####
#   ##        ######  #########  ###   ##   ###  g                   ######### ## ######## ## ## ## #  ## # ### #  ## ####
# l  #   ###   ###    ####### #  ###    #   ###                     ##########    ##     l    ## rt       #  ## #   c ## #
#######   ##    #          ##    ####           #            #######f######### ##f## ## ## ## ## ## # ### #  ## #  ## ## #
########  ##                #        l   ###   ##  b######f#  #######g#######  ##r## ##r## ## ## ## # ### #  ## #  ## ## #
###      ###        g  #######           ###    #         ####g#####a######### ## #  ## ##    ## ## #  ## #  ##    ## ## #
###   l              b  #######          ###                          ####f### ## #  ## ## ## ## ## #  ## #  ## #  ## ## #
###     t    #######          ########              # ###        ##    ####  #          ## ## ## ## #  ## #  ## #  ## ## #
###     b               #######          ###b                         ####b#                     ##    ##             l  #
###      ###   r       #######           ###    #   #     ####   ####  #### #         f          ##    ##    r           #
########  ##                #         l  ###   ##                     ####   #    ##     #                #     # ##     #
#######   ##  l #          ## r  ####           #   #####t############ ### #     ###     #              c                #
#    #   ###   ###    ####### #  ###    #   ###              #########      ## # #   g c #  t                            #
#   ##        ######b #########  ###   ##   ###     # ####      #######      # #    #    #                               #
#   #        #######  #####   #  ###  ###   ###              ###t######             #    # ## ## ## # ### # ### # ### #  #
#   #       ##           #       ######## c ####   g# ###b#####f##########       #####   # ## ##      ###           # ####
#   ##     ##       #      ##    ########        #  a##########  ###### ##              ## #                             #
##  #       t      ##### l##        #           ############### ######r ####                                             #
###                 r #  ##  ###   ##        ##c    ###########  ###### #####   ##########                               #
# ##      #           #  #   ##   ##         ##b l         ####  #####   ##### A##     ### #                             #
#  #     #######      ##    ##   ##          ####   ####### ###  ####f#         #       ## ## ## ## # ###       # ### ####
#  #    ########   #  #    ##   ##  #       f####   #######  ## ###### ####### ##  g    ## ## ## ## # ##        # ### ####
#  #              ##         l ##  #######   ##   #   #####  ## ###    #######  # f      # ## #     # ##        # ##f   ##
#  ##          f   #          ##  #######   ##   #####g####  ## ####   #######  # g      # #  f       ### g b   #       g#
#   ##  g          #         ##    #####   ##t  #######l###  g#  ###   #######  #r       #             A                 #
# #     # #  ## # ##    #  ###   #    #                #                        #                                        #
#   #######  ##  t##       #  #############################  ## ####   #######  ##                  # ##  f   b          #
#     ##             ##      ##############################  ## ####   #######  ########## ## ## #  # ### # ### # ### ####
##     ##  ## r     r    ##  #         #  ##         ##  #      ## g#          ###########  # #       ### # g## #  ## ####
#    b###      ## ###    f#  # ##     g   ## ##    # ##      ## ##         ##b                    ##                     #
#     # ##     ##   #   ### ## ## #      ### #      ####      # ###     f#b##                     ##    b             ## #
## # ## ##            ####  #  ## ##  b   ## #       ##       # ##   b  ## ##  ###########  ###      r##### g####  #######
## ####    ####  ###        ## ##     r   ## r  t    ##        r##    l    ##   ##########################################
## #    #### ##  ##  ##     ########               # ## #               ######  ##                 #####                 #
#### ## # #   #   ##   r      ######   #####      ## ## ##      #####   ######  #  b                                     #
# ## ##         ###### ####      #           r   rr                f   l     #  #   f    #                             b #
#  # t##        #    ### ##   # #                          l        r      # #  # f   t  ###         ####      ###       #
## ##### ### # ## ## ##      ###         ######     f        ######f l      ##  #        ######    #####        ####    ##
##       ##l #    ##       g ##   g# #     f                          # #gbl # ##       ################      g ##########
##    ####   ##   #b       #  #    #f# ###########        ########### # #    # ##       #################      ###########
#  ## ## #   ###t #        #  #    #l# ########### r####  ########### #b#    #####     #####             r               #
#  ##  r   #t#g# ##  g#   ## ##   ##   ##      #     ##     #      ##   ##   #############    f   r                     r#
##         #     #    #    ###         ## ##    #    ##    #    ## ##                                                    #
##g   ##  ##     ##   ## # #   rr ##   ## #      #   ##   #      #g##   ##              ####                             #
#    g    #      ##      #  l            r#       #      #     l #          f ########   #######      ####          ######
#  ##        ###l       ##    ####### #####    ##############    ##### ##############   c##############################  #
#   #       ###    ### ##     #######b#f       ##############        # ##############  t ##  g    r                      #
### #    b           # b        g              ##          ##                 #######    # b                           A #
# ###   ##       f  ## g ##   ###              ## #   f  # ##              ###   ####    #                     #         #
# ##    l#           ##  ##        b #   # ##  ###        ###  ##b#   #           ###    #        g      ##    #####     #
#   f    ##       ## # f      ###### #   # #   ##          ##   # #   # ######                                       c   #
# ####          b  #     ###      g# #   #b  l ##          ##     #   #g#     ############################################
#   ##     ##   ## ##      #     l   #   #     ##          ##     #   #                                                  #
#  ##    ###     #g  r               ##  #     ##    a     ##     #   #       ############################################
#  #      #   ## #      t    #           # A   ##    g     ##  l l# r  f                                                 #
#      ####  l    l #### ##  ##  f #### l        l                   ####    # ###########################################
# t  #   #  ## b    b ## ##  ###             #####  ####  #####          r   #   r          t                          t #
#f # #   t  f#   ###         ##     ####                       l    ####   # #     rr                f    b              #
#  # ## g### ## ##    #     ###  #                   g             r     b#  #                        A                  #
# #  ##### #    #  #####  ### ##########       #      r     #       ##########    A                                     t#
# ##         ##    ##f #   #t ##########      ##    f       ##      ##########                       r             r     #
#   ####   ##           #             ##      #       #           #r          b                                          #
#    ####   #          #  #          r         b      #          #    ##   ###                                           #
#   g   #   ##                      g         #        #         #   #  ###                                              #
#           #####          #     #  ## ##g    ##        ##      #   #                            g                       #
#        #     ##          #       ##   ## b   ## ##      #  ###   #       l #  t                    f                   #
#l              #       g   #     ## t   ##  b  b  ##g##   ##      #        #                                            #
#               ##                #    r  ## ##        ##           #       #        f                      t            #
# # f         #g #  l        #                ##        ##   ## ##   #  l   #          A       t                         #
#                            ##    #######     ## ##     ## ##   ##   ###    #  g          b       f  f     fc           #
#          #                 ##   #       ###      ##     r       ##     ##            f        b   t      l f           #
#          ###    #   #      ##tr            #  l   ##    b        ##      #  ############################## #############
#    # b    ###     ##  r    ##    ##         #      ## ##          ## ##   #            c    r                          #
#            ##              ##     ##r       #          ##             ##   ############# #### ############ #############
#     #       ##             #g  #   ##        #     g    ## ##b         ##           b                        r      c  #
#     ##         #          g    ##   ## ##     ###           ##          ##t ######### ## #### ############ ### ###### ##
#     ##             # l     #   ###      ##       #######     ##          ##       r                   f                #
# ##  ##     #        #           l##   l  ##             #     ##l##                r      ####  #####   ####    g      #
###   ##       #    l               ## ##   ## ## f   r    ##    l  ## ## b            ##     ##  #####  ##### b   ##   ##
###  f ##     f##         #   #         ##  g   ## ##    l   ###        ## ##      t   ##  t       ###   ####f   #####  ##
# ##     l   #  ## #          ##         ##         ## ##       ####        ###  ##         f      ## l   ##     #####  r#
#               ##         #  ####       l## ##         ## ##       ####     #######         ##                   ###    #
# g #                      ##   #######       ## ## l       ##          ###   #######      ######                  ##    #
#       #                  ##          ###        ## ##      ##            ## ##  #####  ##########          ##        g##
#     g  #         #   f    ##            ####        ## ##   ## ##          ##    ########## g######  ##  ######   r   ##
#        r      #  #        ####  #b          ####        ##      ##   b   b  #      ######   l  ##################  a   #
##   #          ##  #  ##     ### g#             b####     ## r    ## ##               ##          ##########  ######    #
##      ##      ##  #  ###         #        r   t     #     ## ##      ##        ##          ##      ##  ##   l  ######  #
#       #####   ##      ##    g   l#f              g   ###      ##r lb  ## ##    ##        #####  l            g   ####t #
#    ##   ####  ##       ##        #     t      ## ##     #      ## ## r    ##  ####  ##   #####             t      ##   #
#               ##          ##   g #   b       ##   ##    t####      ##         ####  ##    ##      f     ##      la##   #
##              ##     ##         #        ## ##     #     t   #      ## ##l     ##g                ##    ##             #
##    #         ##     ##       #      ## ##         b          #  at     ## #                     ####        a##   l   #
#             b ##    ##           ##r##      tl     #          #     g        f r           ##  ######       #####  ##  #
##              #   l  g          ##                 ##         #             ##        ##   ##  #### g   f   #####l ##  #
###                       #       #   l   ##          ##   t     #  ##        ###  ##  ####  a    ##  f  t  g  ### f     #
####                      ##  g             #####      ##         ##  ###     #############       ##   r ##    ###       #
# ##  #  ##               ####    #     #        #      ## ##            ##    #############            ####  #####      #
#     ##  ##                ##l f #     #   t   rb#b        ## ##          #     ##  ##  #####        ######  ######  ## #
# f   ##  ###          #     #    #     #         #   ##        ## ##t      ##         f  ####   ##   #####     ######## #
#l         ###        l      ##          #l  r   #   #  ##          ## ##                  ##    ##  #####       r########
#     # l    ##           #  ##f         #       #  # r   ##  ##       A##      ## g##               #####g         ######
#             ##  ##        g##         # l      #  #       ##  ####     ## ## #########     g     g  ###  t  ##     ### #
# l     bg       #### ##b    ##         #     r  # r#              g#      t # #########    ##        ###   #####     ## #
#         ##                 ##   ###    #       #   #     l        t####        ##  ##   ####   t   ###    #####        #
#      # l##            #     ##     #    #  l    #  l#r       ####      ####             #####    #####     ##          #
#      g  ##            #  f   ## g   ##   ##      #   ##     # b  #         #             ####  t ###### g             ##
#         ##b     ###     ##    #   t  l#    ####t  #    #####      ##          ## a      A#####    ######    t   ##   ###
#         ##      ##  ##                 #       #   ##          f    #######  ####    ##   #####     ####        ###  ###
#        f##     ##               #t     #        #    ##                    #######   ##   #####      ##        ####   ##
##########################################################################################################################
