metadata:
  gen_time: 5.884500980377197
  timestamp: '2025-04-18T22:46:27.395865'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#      ###    # a  #####    ####   ###########   # ####   f     #       # g     #   #      t    #       #                #
####   ###    l    ##### #######   ###       #     #####        #       #   g   #   #           #       #            b   #
###   #####        #      t    #   #               #t           #       #       #   #           #       #g          g    #
###  r               b                f       g        b        #####f  #   #   #   #   #########   #####lf ##############
####    #####    r            a                  r              #   #       #   #           # A #       b f #   #A       #
################## ############ ##### # ######## #####  #####   #   #       #   #           #   #     t     #   #        #
##########g    f g            r     f r       lf   ######## r   #  f#       #   #    t      #   #           #   #f       #
# b######f       #############################       t          #   #   #################ff #   #####   #####   #   ######
#   #####   A     ######################################   f                        #       #           #   g   #   #    #
#   #####  l      ############# a##  ### g##   g ###  #######              f        #       #           #       # l #    #
# b #  ###     g  ###      ###       b     a   t     a                              #       #           #       # l #  g #
#                 #         ##   r   r                   ############   #  f#############   #########   #   #   #   #    #
#                           ##     ##########################           #       #       #   #   f          g#      f     #
# #       b                         ###     b##  ####  ####          r  #       # g     #   #               #            #
# ###t        ########       #      ##                  f  r         b  #       #       #   #             r #    t       #
# ###################        ##    ###                          #####################   #   #####   #   #   #########    #
# ###################        ##########  l                         tt   #   t   #                   #   #   #   #        #
# ########t      r ###       ################################    b      #       #                 b #   #   #   #        #
# ######             g       ###a ###     ###  ###                      #       #  l          t     #   #   #   #        #
# ###       ft       r       #    t    l  a      t  #########   #####   #   #####   #########   #   #   #####a  ##########
#g#                     a                            ###    #   #   #           #       #       #   #   #                #
#        l      t                    r               ##         #   #           #       #       #   #   #   r        t   #
#    ####################################f     r  f  ##       f #   #           #       #   g   #  f#   #  r          gg #
#  b  ##########   r##############################  ###a     ####  f#####   #################   #####   #   #########    #
#     #########   a  #########   #######################                     tb                     #           #       g#
#    a#########      #####           f    ######          b                            g            #   t       #        #
# #  #######  #      #   f f                       ##########                                       #           #        #
# ########b   b                             l       #########                   t     r        g    #  b    f t #        #
#a######     a                ####  #               ####                    b f                     #           #        #
####             ###### b   f  ##   ######          ###   ###  g                    r               #           #        #
#      g  #    #    #b#    #  fg     #        #      #t  #          #      #            ######            #  f   #       #
##########     #   #   #    #        #       #        #   ###g    t #      #                              #      #       #
#     t        #  #    #     #        #     #         #       l     #      #            # ####            #      #    t  #
#             #   #   #l    #        l#     #        #              ##    ########### # #    ### ###########    ##  t    #
#       ######    #   #    #       # #     #          #  f    l      ##   ##            r          l   t  ##  g##        #
#      #          #   #    #      # #     #            #    #         ##  ## l                Af          ##  ##         #
#     #           #   #    #     #         #         l#t   #           ##### t                     g      ## ##        t #
#      #  b       #  #    #      #         #      ####      ########      #                                # b    # #### #
#       #        #    #   #     b #       l#     #        g #      #########     #### # ######## ####     #### ####      #
#####  #     ####    #    #        #       #    #       #                 ###   ##### # ######## #####  g###t            #
#b   ##     #       #    #         #       #    #      # #                ####  #####          r #####  ####             #
# l  f f   #       #    # bb  t   #    c  b#    #     #   #  ####### ################   #######  ############# ######### #
#           #       #  #           #      t#    #     #  a # ####### ##################   ##  ################ ######### #
####     f #        #  #            #       #    #    #     #  #####    ###         #            #         ###    #####  #
#   ####### t      #    #          #         #    #    #   #   #####                #   b      g #               r#####  #
#        t          #    ##      ##      #    #    # b#    #   #####r               #            #   f            #####  #
#       t            #     #    #      #  #t   #    ##    #    #####   l###    a    # g    l     #  t      ###    #####t #
# ####       ####     #     #  #      #   f#    #        #   ###########################  ##  ############################
#     #          # f   #   #    #  l   #   f#    #      #     #######################  ########  #########################
#      #   #      #    #  #      #      #    #    #   f#    #      f      #### g#####        t   #####  ####             #
##    #     #    # g    t #       #    #      #   #    # f #              ###   ##### ######### ######   ###             #
# #t  #    #    #     f#   #r      #    #    #   #     #    #      #########r    #### ######### #####l l  ## ######     t#
#  #  #    #     #    #   b ##     #    #   #r   #     #  t ########      #                                #      ########
#  #  #l   #     #    #      g#    #   #  f#   f  #    #    # t       g#####               r     g   g    #####     t    #
#  #  #   #   f #    #         #   #   #    #      #    #             ##  ##            g    r   l        ##  ##         #
#  #  #    #    b#f  #       t #   #    #    #      #    #           ##   ##                              ##   ##        #
#  #   #    #   #    #   t    #    # l   #    #  ff  #    #  bl t   ##    #### ###### ###    ## ############    ##       #
#c #    #    ###     #       #  g  #     #     #     #     #        #     f#     g      ######f           #      #       #
#   # t  #           #   t  #      #     #     #    #       #       #    f #                          t   #      # t     #
#   #    #            #      #     # t   #    #      #              #      #   b        ######       r    #      #    f  #
#b#  ### ###   b          ##     ##   ## ##### ##  #  ##  ##               ##    r ##  ##  ##  ##      ##  ##      ##    #
###    ###  r b#  ## ##   ##      #            ## ## r#r   #      l      g ##      ##  ##  ##  ##      ##  ##      ##    #
#   ## #   ### #  ##    t##      ## ##    ##   #  ## ##   ## ########  ######  ######  ##  ##  ######  ##  ##  ##  ##    #
### # a##  ##    ##  ##   # ##  ##  #l    #   #####  #  # ## ########  ######  ######  ##  ##  ######  ##  ##  ##  ##    #
#      ##  #     #   ###    ##  #        ## ###  #      ###  f     ##  ##r     ##          ##  ##          ##l ## r      #
##      #              ###  #   # ##     #   #  ## ##    ###       ##  ##      ##       f  ##  ##          ##  ##        #
## #  b    ##      ##    #b       #             #  ##   ## #   ##  ##  ##  ######  ##########  ##  ##l ##  ##  ###########
## ###    ##a                 ##  #           #       # ##     ##  ##  ##  ######  ##########  ##  ##  ##  ##  ###########
#   #         ## ## f    ###  ##     # ##    ##   ##  ###   g l##  ## A                    ##      ##  ##  ##            #
# ###   ##    # f##   ##   ## #   ######      ## ##       b##  ##  ##r     l               ##      ##  ##  ##            #
# ##  ####             #    ### ###   ##         #             ##################  ##  ##  ##############  ##  ######    #
###  b #   ##       ## ## ####  # # ###        ### ####  b  # b##################  ##  ##  ##############  ##  ######    #
### ## ##  ##       #   # ## ##          ## #   #    ##  ####  ##              ##  ##  ##  ##  ##  ##  ##  ##  ##  ##    #
##  #         # ##a     ###  t     # # #### #  ## f   #    #   ##    b        l##  ##  ##  ##  ##  ##  ##  ##  ##  ##l   #
##        b ### ##               a # ###    ##  ##   ##  ###   ######  ######  ##  ##  ######  ##  ##  ##c ##  ##  ##    #
##          ### ##        r       b# ###    ##  ##   ##  ###   ######  ###### A##  ##  ######  ##c ##f ##  ##  ##  ##    #
##  #         ####      ###  b   t ### #### #  ##     #    #   ## f    ##          ##  f   ##                 t    ##    #
### ## ##  ##       #   # ## ##          ## #   #t   ##  ####  ##      ##          ##      ##             l        ##  g #
###    #   ##       ## ## ####  # # ###     f  ### ####     #  ###### l##b ######g ##############  ##################    #
# ##  ####b            #    ### ###   ##  t   l  #      r      ######  ##  ######  ##############  ##################    #
# ###   ##   b#  ##   ##   ## #   ######      ## ##        ##          ##  ##                a   g         ##            #
#             ## ##  g   ###  ##     # ##    ##   ##  ###              ##  ##       l        t       t     ##            #
## ###    ##                  ##  # l         #t      #f##   ########  ##########  ##  ######  ###########################
####       ##      ##    #        #t        t   #  ##   ## # ########  ##########  ##  ######  ###########################
##      #              ###  #   # ##     #   #  ## ##    ###       ##  ##  ##      ##  ##      ##          ##            #
#   fb ##  #     #   ### f  ##  #        ## ### t# t    ###      f ##  ##  ##      ## r##      ##         b##            #
### #g ##  ##    ##  ##t  # ##  ##  #     #   #####  #  # ##   ######  ##  ######  ##l ##  ######  ##  ##  ##  ##  ##l   #
#   ## #   ### #  ##   A ##      ## ##    ##   #  ## ##   ##   ######  ##  ######  ##  ##  ######  ##  ##  ##  ##  ##f  b#
# #  # # #     # t## ##   ##l     #            ## ##  #    #    f              ##  ##  ##          ##  ##      ##  ##   l#
# #  ### ###              ##b    ##   ## ##### ##  ## #   ##                   ##  ##  ##       f  ##  ##      ##  ##    #
# ## # ## ## ## ## ## ## #      l g # ## ## ## ## ## ## # ##    ##   ##                        b       f       ##   ##   #
# ## # ## ##  # ## ## ## #  r       # ## ## ## #  ## ## # ##    ##   ##                                      b ##   ##  r#
# ## #     #  #  # ## ## #   g      # ## ## #  #     #  # ##    ##   ##         b             b     l          ##   ##   #
# ## #  #  #  #  # g#  #f#          # #  #  #  #  #  #  # ##t   ##   ############   ##############   ############   ##   #
# ## #  ## ## ## #  #  # ## ##  ## ## #  #  # ## ## ##  # ##t   ##   ############   ##############b  ############   ##   #
# ## ## ## ##f## ## # ## ##  #  #  ##f## # ## ## ## ## ##g##  r    r ##f  ##f    r                r       ##  r## r      #
# ## ## #  #  ## ##g# ##  #  #  #  #  ## # ## ##  #  # ## ##         ##   ##            l           r     ##   ##        #
# #  #  #  #  #  #  #b    #  #  #  #  #  #  #  #  #  #  #  #         ##   ##                             r##   ##        #
#t#  #b #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #    #######   ##  f##   ##          ##   ##   ##   #######   #
# ## ## ##c## ## ## ##t## ## #### ## ## ## ## ## ## ##l## ##    #######   ##   ##   ##  r       ##  g##   ##l  #######   #
#       r                    f                     r            ##   ##        ##   ##          ##   ##       b##   ##   #
#              r                 t                              ##   ##        ##   ##          ##   ##        ##   ##   #
# ## # ######### #### ############### # ####################  l ##   ##        ##   ##          ##   ##        ##  t##   #
#### # #########    f t  ###      ###         ###############   ##   ##   ##   ########################   ##   ##   ## f #
#          g                       r                         f  ##   ##   ##   ########################   ##   ##   ##   #
# gt                                                         b            ##                              ##             #
#### # #########         ###      ###    t    ###############     l       ##                              ##A            #
# ## # ############## ############### # ####################              ##   A     b                 f  ##             #
#              r      t                             a           #######   ############          ############   #######   #
#                             g                                 #######   ############          ############   #######   #
# ## #  ## ## ## ## #  ## ## #### ##  # ## ## ## ##  # ## ##         ##          f  ##          ##             ##        #
# #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #         ##        f    ##    b     ##           rt##        #
# #  #  #  #  #  #  #  #  #  #t #  #  #  #  #  # t#  #  #  #         ##      t      ##          ##             ##r       #
# ## #  #  #  ## ## # ##  #  #  # r#t ## # ## ##  #  # ## ##    ##   ############   ##          ##   ############   ##   #
# ## #  ## ## ## ## # ## ##  #  #  ## ## # ## ## ## ## ## ##    ##   ############   ##          ##   ############   ##   #
# ## #  ## ## ## #  #  # ## ##  ## ## #  #  # ## ## ##  # ##    ##        ##        ##          ##f       ##     r  ##  l#
# ## #  #  #  #  #  #  # #     t  r # #  #  #  #  #  #  # ##    ##        ##        ## r        ##        ##        ##   #
# ## #  #  #t # c# ## ## #          # ## ## #  #r #Ar#  # ##    ##        ##        ##          ##        ##     f  ##   #
# ## # ## ##  # ## ## ## #          # ## ##r## #  ##f## # ##    ##b       ##        ##          ##        ##        ##   #
# ## # ## ## ## ## ## ## #   f      #r## ##               ##   l##        ##       b##          ##        ##        ##  b#
##########################################################################################################################
