metadata:
  gen_time: 5.1862571239471436
  timestamp: '2025-04-18T22:49:58.331066'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
## # #              a           # # # # ##############  #####   #######           ##      ##                  ##      ## #
## # # ############ ###########     # # #############    ###    ######      ##    ##                             r    ## #
## # #     a    g                 #   # ############             ####      ####        l  ##                  ##         #
#      ####### ####  ############       # #########        r  c          l######  ##      ##          f      l##      ## #
###### ####### ##### ############### ####        cr   ####                ####### ##      ##                  ##      ## #
#            b                            g          ######       #####    ###### ##      ##      f           ##    fl## #
###### #####   #############    # ## ######          #######     #######    ####  ##      ##         l       g##      ## #
#  r                              ## #######         ########g   ######## g       ############# ########## ############# #
##     ####### ###############  ##       ####        #########   l#######         ############# ########## ############# #
#              A       b        ## ###########       #########     #####l                  ##      ####           ##     #
##### ##   ### ################ ##       ######   r   #######                     l   ##   ##      ####      ## l ##     #
#                      g        ## #############                           ##         #######      ####      #######     #
####      #    ###################       ######## r           c     ### g ####b       #######      ####      #######   f #
###### ## ###  ###################################          ### r  #####  #####           b##l r    ###           ##     #
#      b     t             g   a      r A##########        #####   #####  #####       ##   ### #### ##### #####   ## t   #
###### ## ##   ############# ###### # # ############      #######  #####   ###        ######## #### ##### ##########     #
#                      r         a       ############     #######  #####              #######    ##    ##    #######     #
######    # #   ######## ### ###### ##  # ###########     #######   ####    c   #          ##    ##  g ##    ##   ##     #
#                         r          b    c#########       #####     ##        ##  r  ##   ##    ##    ##    ##   ## f   #
########     #  ######## ### ###### #####                                      ##   t ##   ##    ##    ##    ##l  ##     #
#                                              l      ##  l               ##    ################################# ########
#########  #    ######## ### ############   ##    c  ####    r  ####     ####    ################################ ########
#           ##  ######## ### ############  ####      #####     ###### A  #####                 ##     c  ##   ##t        #
###########                               ######      ####     ####### b  #####        g  ##   ##        ##   ##         #
#           ## ########################## #######      ##b  c   ######     ##### #### ########### ######### ######## #####
########### ##         g                  #######                ####       ######### ########### ######### ######## #####
#           ## ##########################  #####    g       ## c  ## l       ####    l       g               r           #
##############             b                 c     #####   ####           g   ###                            r           #
############## #############   ##########         #######  ####              c  #       l                                #
#                     a              ####  ###    #######   ##        ##      g                                          #
############## ############## ###### ##    ###    #######f  ##l       ##         ######### #################### ##########
#                           r   g a  ##a#   l     #######  ####     g          ########### ####################r##########
################################# #####            #####   #### g             ###                       ##     g        g#
################################# #######  #####            ## g  ##r   c   l####               ##    l ##               #
#                a    a         g         #######      g        l####  c    #####   f           ##      ##        g     l#
### ##### ######## #### ################# #######r     ##       ######     #####      l         ##      ##               #
#                                         ######   c  ####     #######    #####           l     ##      ##        f      #
### #####################################  ####      #####     ######    #####                  ##      ##   f           #
### #####################################   ##       ####       ####     ####                   ####  ####               #
#                                                     ##                 l##   g#               ####  ####               #
#########################################            g                         ##               ##    l ##               #
#########################################  #########       #####     ##        ##          r    ##   rt ##           r   #
###                                       ###########     #######   ####  f    c#   g           ##      ##       f       #
### ########## ###### ############ ## ###############  l  #######  #####                        ########## l         r   #
###          r                   t  b    ###########      #######  #####t  ### c  g             ##########               #
### ### ############# ############ ################        #####   #####  ##### c               ##      ## l       c     #
### ### ############# ############       #########          ###    #####  #####                 ##  r   ##               #
#                  ##   ##       # # # # ########                   ###   ####  g                                  t     #
### ### ##########t## #b## # # # # # # # #######         g                 ##g   tc            g## t    ##               #
#     g            ## # ## # # # # # #   ######      c#######                                   ##      ##             t #
#####################   ##          a#########       #########     #####  g          r       l  ##    l ##       A       #
#############################################        #########    #######                       ## #######        r   f  #
#                b           b           ###         ########    ########           f           ## #######               #
# ################ ################### ####      g   #######     #######   g####                ##      ##          l    #
#      A  ######## ################### ##         l  ######       #####  l ######               ##      ##               #
# ####### ##  A        r                           r  ####    g         c #######               ##      ##               #
#         ## #####  ################## ##c#########  f            l       ######      f       g ##      ##  f         t  #
# ####### ##           r        r        ###########             ####      ####                 ##      ##               #
# ####### ## #####  ###  ############################    ###    ######      ##                  ##      ## f             #
#       a           ### ##############################  #####  g#######                         ##########         c     #
#    r          l  ##   #####    ###     ###########       ###  f    g###########  ### ##  # #      ####   #       #     #
#   g        #         ######   ######## ##########       ######       ##########  r## ## #r l     #r##### #       #     #
# g         ###       ####### ########## #########       ########       ########## ### ##### #      ###### #       #     #
# b f      #####       ###### ######  #  ########        ########        ############# ##### #       ####  t       #     #
#           ####       ## l#  ####       #######         ########         ############ ##### #   #  #####  #       #     #
#           ##   r          g  ##       #######           ######           ##########  ##### #   ###g####  #       #     #
#                   ##         ##       ###### g l ###     ####     ###     #########  #####      #f#####  #       #     #
#                   ##   ##   ####      r####     #####            ##### t   ########  ######   #   ##     #       #     #
#    ##      ##          ##   ### g      ###      #####          t #####      ######## ######   ### ## ##  #       #     #
#   ####   #####             ####    ##  ##        ###    ######   f###  gg           ###r###   ### #  ##          #     #
#    ####  ####   ##         #####  ###### f f           ########   l          g#####  # #####  ### # ###          #     #
#     ###   # g  ####       #####  b ####               ##########f             g####    #####   ##  ###           #     #
#     ##          ###      #####       ##    ######  f ############    ######          #######   ######  #         #     #
#             ##   ###      ###   ##        ########   ############   ########       ##########  ######                  #
#A    ## r   ####  ##   ##   ##  #####     t########   ############   ########      ############ ####    #               #
#     ##    #####      ####       ####    l  ######  l  ##########     ######                   #####  ### #       #     #
#b          r##### b    ##   ##     #          t         ########     b   t                      #### ###  #       #     #
#              ##       ##  #####r         t  t           ##  ##      t    f  t                   ####     #       #     #
#  r                         ####        #                f         t       f f ### ####              #### #       #     #
#                              #         #      lc  ## l            ##                               ##### # #     #     #
#                     ##           r     #        g####            ####         #r  ####### # ####    #### ##f     #     #
#                     ##              ##           #####          #####                              ##### ###   # #     #
#                 b                   ##    #### t ######        ######   ####                        #### ###   #       #
#                          r         ####  ######  #######     b#######  ######                        ### ###   # #     #
#                ##  r              ####   ######   #######   g#######  g######                       #### ###   #       #
#          b    #####                ###    ####     #######  #######     ####                         ###  ##   # ##   ##
#                ####                ####             ##############  f                               ####l###   #  #   ##
#                  #            ##    ##               ############                                  ######r##   ####   ##
#      l       #      ##        ##    ##     #######    ##########    #######t                      ###########  ####   ##
#            ####    ###       ####         #########    ########   b#########              ###################  ####   ##
#            ####    ####       ##     l    #########    ########    #########c            #################### #####   ##
#             ####    ##   ##         f      #######    ##########   t####### t    # ####   ## ########### ####  ####   ##
#      ##      ###    ##  #####              g         ############      b                                        ##g   ##
#      ###      #          ####             t         ##############             ##################     ##       ####   ##
#     ####A                 ##              ####     #######  #######     ####  l###################   #### #####g###   ##
#      ####                 ##  b     ##   ######   #######    #######   ######                                  ####   ##
#      ####   #                      ###   ######b #######      #######  ######                                 ######  ##
#       ##   ###    b                 ###   ####  l######        ######   ####                                   ###### ##
#       ##  #####                 ##  ###    t     #####    r     #####                                                ###
#  ##       ####                  ##   ###  g   b  ####       l    ####         #### #### ####### ########## #####l###  ##
#  ##         #              ##        ###          ##         A    ##     f                                        ##b###
#                           ####      ####                                      ####r#### ####  ###f    #### ##### #### ##
#               ##      ##   ##        ##t l              ##  ##      t       t                                          #
#      ##       ##      ##  r           #         f     g########          t   l     #### #     ####    ############ ## ##
#     ####     #### b  ####     rf           ######     ##########     ######                                            #
#      ###      ##   #####         ##  f    ########   ############   ######## g #######  #############   #b########b#####
#       ###          #####        b##  ## t ########   ############   ########                                        ####
#l      ###           #####            ##    ######g   ############    ######                    #####################f###
#   ##   #    ##       ###            ###           bf  ##########         fl                                          ###
#  ####       ##       ###            ####   l           ########        c          #         ##    ##      #   # # #  ###
#   ###           ##b   #              ####   f    ###    ######  l ###                     #  ##    # # #            ####
#b   #           ###          A##      #####      #####            #####                                 # ####  f##   ###
#                 ###         ###        ####  b  #####        fb  #####     #      ####      # # ##        ###  #l#  ####
#                 ####         ###       #####    t###t    ####     ###             ####              #   # ###l      l###
#    b    ##    b  ##    ##    ##       #######  f       b######           #  #                    #   #        l#### ####
#        #####         b####        ##  ########         ########         ### #      ######   ##    #   #  ####   ########
#         ####     ##    ##    br   ##   ########b       ########        ####  #     ########  ####     ##    ###   ######
#     #    #    g #####         b   b    #########       ########       ######       ########  ####         # ##### ######
#    ####        t ####     ##      ##   ##########      r######       ###########  #########    ####  ###     ####   ####
#   ###### r         #    ######    ## r ###########       ####       ############ ###########  #####   ######  ##### ####
##########################################################################################################################
