metadata:
  gen_time: 10.19597315788269
  timestamp: '2025-04-18T22:51:08.521041'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#    ##      ###     #  ##  ##              ##     ##  ####   #######     ##       ######    ######       ##     ####### #
#             ##                     ##                 ##     #####    b####       ####      ####       ####     #####  #
##       ##                     ##  ####                                ######       ##    t   ## b     ######           #
####    ####              ##    ##  ####   ## r   ##                   ########               l        ########          #
####fg  ####       t##   ####        #    #####   ##                   ########   f                    ########      f   #
# #   l   #       #####   ##               #####   f     ##    ###   g  ######     f    ######       b  ######    t ###  #
#     f           #####         ##           ##        #####  #####       g      ###  r########  r###       c     f##### #
#     ## t         ##         ######            t  ##  #####  ######    b       #####r ########  #####            ###### #
#   #####                     ######               ##   ##    #######           #####   ######   #####       r   ####### #
# ######                  #    #  #t      ##                   #######          ####lr   #### r   ####          #######  #
# ####      ##          ####             ####  ##        f     f#######        c ##  t            t##          #######   #
# ##      ######        ####      t  ##  ####  ## f       f##    #######            r          g        r  t  #######    #
#        ########        ##        f ##    #               ##     ######             ##        ##t            ######     #
#         ##  ##         ##     ##                 t ##     #      ####   b######  f####  ##  ####   ######    ####      #
#    l                  ####   ###            ##    #####                 ########  ####t ##  ####  ######## b       g   #
#      #           ##   ####   ####     ##   ####    #####                ######## l ##   ##   ##   ########g            #
#    ####t    ##  ####   ##     ##    #####  ####   tf ##    l###    ##    ######  f                 ######    ##    ### #
#    ####     ##   ##         l  t    ##### f ##             #####  ####                   f      r          f####  ######
#     #                        f       ##     ##             #####  #####           ####      ###  f         #####  ######
##                          ##                              #####    ####   ###    ######    ######g   ###   ####    #####
###        f##      ##    ######c ##                      #######    ####l  ###    ######    ######   r###   ####    #####
###        #####    ##    ######f ##   ##   ##     ##     ########  #####        f  ####      #### r         #####  ######
##         #####           #  #        ##  ####    ##       ######  ####                       g   b   r  b t ####r ######
#            ##                         t  ####               ###    ##    ######                f   ######    ##    ### #
#            f         a           # l   t  #            #     b r    g   ########   ##   ##   ##   ########           A #
#                   ff     ##    ####               ##  ####              ########  ####  ##  ####  ######## gb          #
#  #                  #   ###f   ####          ##   ##  ####       ####    ######   ####  ##  ####   ######l   ####  b   #
# ####  ##  l ##    ####   ###   r#    t      ###        ##       ######             ##        ##   A         ###### f   #
# ####  ##  #####   ####   ###          ##    g###               #######  t                              b    #######    #
#  ##    f  #####    ##     # b        #####   ###  f     f  r  #######          ##                ##          #######   #
#           f##    t ##         ##      #####   #       f      #######         A####     ####     ####          ####### b#
#      ##           ####       #####      ##             ##   #######           #####   ######   #####           #######t#
#      ##            ##   ##    ######   r          ##   ##  r######     r      #####  ########  #####            ###### #
#  ##                     ##  t   #####           #####       ##### l            ###   ########   ###              ##### #
# t##           #                   ##            #####        ###      ######          ######          ######      ###  #
#      ##b    ####                           ##    ##       #  g   b   ########                   f    ########          #
#      ##   ###### t       #               #####            #  t       ########                        ########      t   #
#           ####       l ####   ##   t     #####                        ######       ## r     r##  f    ######           #
#            #       b   ####   ###         ##                 #####     ####       #### b    ####       ####     #####  #
###                       #    ####   ##          ##   ##  ## #######     ##       #####  t  ######f      ##     ####### #
#               f t       g                 a#      r       #    #  #    #     #                #              lg       f#
#    l   t            f                g    l##   l      r #     # ##    #     # ##             #       f            #  ##
#        t      r     fr     t               # #     t    #      #    c  #     #  #  #########  #  ###########       #  ##
# c       r      ####                           #          #  ####       #  ####  #  #    r  #  #  #         # t     #  ##
#          l   g #  #  l                      t  # #        # #     f#####  #     #  #       #  #  # ## b    #  #### #  ##
# l              g         a                      ##          #    f #      #  t  ## # ##    ####f #  #   t  #f #  # #####
#                   #                         #  b #    t   # #   t  # #    #       g#  #     t    #  #      #  #g #     #
#    ####           #### #####      g  l     #     ##     f # #f     # ######   ######  #          #  #      #  ## #     #
#g   #  #             #   #  # f   f##      #   #           ###      #          #       #####      #  ###### #     # # ###
#      c    a          # #      t    #    r  # #            #        #   r  f   #   t       #f #####       # ####### #   #
#        A              #            #        #      g      #        #t##  ######           #  #        ## #         #   #
#   l    ##    ####        f         #  # #                 #gg      #  #  #             g  ## # b      #  #         #####
#         #    # g#       f #        # # # #                #        #  #  # ##                #        #  #            g#
#         #    g   f   ##   ###       c     #           f   # g#######  #  #  #   ##############        #f #             #
#         # #           #     #l             #                 #        #  #  #   #                     #l #  #######   l#
#         #  #          ##       r  #####     #                # ##     #  ####   # ## l                ## #  #     #    #
#    t    #######     l # #          #  #      #             # #  # c   #    b    #  # t   ####   t        #  # ##  #   g#
#   #        t #           # #      #           #         a    #  #     #         #  # ##  #  #       ######  #  #  #    #
## # #         l#           # #    # l           # # # #      ##  #  ####         #  #  #  #  # ##    #       #  #  #    #
#     # #        # # #         #  #               #r  # #         #  #            #  #  #  ## #  #   b#   f l #  # ##    #
# c    ##         # # #     # #    #  c            r     #        ## #            ## #  #     #  #    #####   ## #       #
#       #              # l  ##      #           t         #         r#               #  #######  #        #l     #       #
## #    #   t   r # # #     #        # #f# # # #   # #     # #       #################           #        #      #  ######
#   #  a##        ## #      #  g      # # # #g# # # # # g  g######     r  r         f            # g      ###### #  #    #
## #              #         ##                         #         #                 #  t          #  # ##       # ## #    #
# #    t    t     #         #        t                  #        # ##       g   ####      g g g  #  #  #       #    # ####
#             ##  ##     t  #  #      ###### ########    #    ## #  #  #######  #  f             ## #  # ##    ###### #  #
# #           #   # #       #######    #  #   #  #  #     # # #  #  #  #     #  #       f           #  #  #           #  #
###           #      #            #   #    # #      #    l #  # ##  ## #  l  #  #    g  #####     l ####  # g####     #  #
# #  f     l  ##      #                #    #      ##         #    g   #     #  #       #   #    g      a #     #b    #  #
# ##                   # #              # l t       # t    #  ##########     #  #         # #         f   #  #  #  ## #  #
#                       # # #      f     #       l  #      ##                ##f# g   ##### #             #  #  #  #b #  #
#           ## ##          # #          ######      ## g                        #     #     # ##  #########f #  #  # ##  #
#   ##      #   #         l   #f       g    #    a  #        ######      ########     #     #  #  #    f     ## #  #     #
#   #  r   ## r #              #          r  #      #  #          #      #            ####  #  #  #         t   #  # f   #
#  ##           ## t      ##    #        g    #     #######    ## #  f   # ##            #  #  #  #      ########  #     #
# #             # #    g   #f  #######       #####l       #    #  #      #  #     l    f #  #  ####    t #         #  # ##
##  #  t        g c#f      #      #  #          #              #t##      #  #            #  #            # ##     g#  #  #
##### t   ##      c #      ##        #           #     f       #         #  ############ #  #        gg  #  #  #####  #  #
#      r   #         #     # #      ##            #  ll   l  t ###########A c  l       # ####   ##########  # g#      ## #
#    ##             ##       ##          a     ##    ##      # ##  #a    ##   ##    #       ###  ###  # a #    ####  #####
#### ## ## ########### ##### ##### ## ## ######## ##### #####  ### #  ## #     ##   ##  ##   ## ###       ##    #   b##  #
#### ## ## ########### ##### ##### ## ## ######## ##### #######  #     # #   b     ####t###  ##  ##    g #####           #
#    ## ##          ## ## ##    g  ## ## ##    ##       ##   ##   ###  #    ##      ##  ##    ## #   #a ###              #
# ## ## ############## ## ## ######## ######## ##### ## ##   #    #####    ###  ##   # ####   ##l    #  ##a  r         ###
# ##  #l############## ## ## ######## ######## ##### ##t##   #       ##     ### ###  #  ##   ####   #   ##  ##  ##    ####
# ##  gr      ##          ##    ##       ## ##       ##      ##  ###   ##    ## ##       a    r#  a##    ## ### #    ### #
# ## ##  #### ## ## ## ############## ## ## ######## ##### l ##    ### ###   ##  #     ###  ##    ####f     ##  #    ##  #
# ## ##  #### ## ## ## ############## ## ## ######## #####  b###       ##  ##    #   #######        ##a  t##          #  #
#    ##  # ##    ## ## ##    ##       ##    ##    ## ##       ###       #       ##   ###  ##t  ##   g##  ### ##       #  #
# ## ### # ## ## ##### ##### ######## ## ##r## ## ## ## ##    ##    ##  #      #### rg#         #    ## a #  ###  ##  A  #
# ## ### # ## ## ##### ##### ######## ## ## ## ## ## ## ##    ##           ##  ##        ### #  #  ##  #      ##   ##  # #
#    ##  #    ##   b## ##             ## ##    ##    ## ##     ##             ##     #  g#####     ##  #      ###  ##  # #
# ## ##  # ## ##  #### ## ##### ## ## ##### ## ## ##### #####  ## t###  ##        #  #     #      ##      ##  ##    tl   #
# ## ##  # ## ##  #### ##f##### ## ## ##### ## ## ##### ##### ##     ##       ##  #     ##    rr##    ### t    #  ###    #
#        #r##       ##       ## ## ##    ## ## ##    ##       ##         ##  ##       #      #  # a   #####         #  ###
# ## ### ######  ##### #  ## ######## ## ######## ## ## ##   #      ##  ##   ## t   #####  ###  #   ##  ###   ###      ###
# ## ### ######  ##### #  ##b######## ## ######## ## ## ##        ########    ##  # # #### ##   ##  #     ##r ####       #
#                   ## ## ## b  ##    ## ##       ## ##t##g       ###  t ##   #####    #   ##               ##  ####  ## #
#                  g## ## ##          ## ##   f   ## ## ##   ##  ##         ##  ####gt  b##    ##                 ##  ## #
#      r            ## ## ##    ##    ## ##       ## ## ##   ####   c   ##        ####  f      ####  ##  ##           ## #
#                   #  ## ##    ##    ## ##       ## ## ##     ##    ##        ##  g###         ##   ###     #   ###  ## #
# ## ## ## ## ## ####  ## ## ##### ## ## ######## ## ## ##  l   ##r  #####    #####  ###  ##  # ##    ####   #     #   ###
# ## ## ## ##    ###   ## ## ##### ## ## ########r## ## ##      ##     ###   ### g   #  ####  #       ## ##  l      #    #
# t     ## ## l      #  l  f ##    ##  t ## ## ##g   ##      #  ###     #   ###          ##    ##   ##       g ##   #   ##
#### ## ##    ## ### # ## ##### ## ## ##### ## ## ##### ########  #   # ## ###    ##    ###    ###      gt##    ##      ##
#### ## ##  #    ### # ## ####     ##l##### ## ## ##### #####         # t# ##      #    #  #    ###       ###   ## g   ###
# A  ## ##    ##     # ## ##   b    b    ##    ##    ## ##   r#  #          #    # #  g    ##   ##  ##    ##     ##r  ####
#### ##### ##t## ##### #####t######## ## ## ## ## ## ## ##    #  ###           ###  ##      # g ##      ##       g ## ## #
#### ##### ## ## ##### #####    A        ## ## ## ## ## ##             ##    t  r   ###   # #    ##     #    ##    ##  # #
#    ## ## ##    ## ## ##    ##       ##    ##    ## ##   t  ### ## l# #  ##       ###    # ##     ###      ##   ##      #
# ##### ##### ## ## ## ########          ## ######## #####   ####### #     ###   ## r#   ##  #   g ###   a##rA r ##a##  ##
# ##### ##### ## ## ## ######## ####     ## ######## #####     ###   ##  # ##    ##     ####l#  #g  #     ##    ##  #    #
#l##          ##          ##g          t ##     g    ##    r           ### ###  ####    ##   ## #l ##  a##  ##       g ###
#### ## ######## ##### ## ##   ###### ## ## ## ##### ## ##             t   t #  ##   # #      #    ###  #   ###  ##   ####
#### ##b#####    ###   ## ##b######## #  ## ## ##### ## ##     ##     ###     ##    ####           ##    ag   # #####    #
#    ## ##           # ## ##             ##    ##       ##         r#######   ##   ###     #     ##    #   ##   ##     ###
#### ## ## ###   ##### ##### ##### ## ##r## ##### ##### #####g     ###f  #    ###  ##     ## #   ##    #   #####         #
#### ## ## ### ####### ##### #####l## ## ## ##### ##### #####  ##  #       ###  #   #    ### ##  ###  #      ###         #
#    ##     b          g     ##       t        ##    ##      #   ##     ## ###  A   #   ###  ###   #  #         #    #  ##
##########################################################################################################################
