metadata:
  gen_time: 9.12247610092163
  timestamp: '2025-04-18T22:47:28.008922'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
###   #  ###        ###  #   ##   t  ##           ## ###       ### l ##      g f    f#     #   b       #                ##
# ###   ## ##  ##  ## ##   ###t##   ###       ##                           #                     f  b  #    #  r         #
#  ##   ##            ##b  ##   ##        ##  ##        l     ####        ##               #########   #    #   ##########
# ##         ###### l       # tt##        ##            g     #           ## ##   ##      t#     #######    #######     ##
#     ###   ##f##b## t ###     #### ###                                   ##      ##    t     t                          #
#       #    # ## #    #             ##            l                              #   #   #####             g      l ### #
#     ###    #    #    ###bg         ### #### ###   ##   ##              #####      # #    ###### ####### ########## ### #
#      #  # ##g   ## #  #A      ##        ##   ##   ##   ##  #         # #####  ##### #        ##   #####  #####   #     #
# ###     # ##    ## #     #### ##        ##   ### #### #### ##  ###     #l          g         ##       ####      t##    #
# ## r      #      #        ##                               ##  ###           #                ##       ##      l##     #
###      ##          ##      ##                     t    g   #    ##f         ##   #    #       ##                ##     #
#     ## l              ##rg   #g#### #### #### #### #### ####      r                   #   #####        ##t       ##### #
#  ####                  ####     ##   ##   ##   ##   ##   ##           ####      ####       ##########################  #
#   ##          f         ##      ##   ##   ##g  ##   ##   ##              ####   ####     ###     ###        ###     ## #
#####          ##          ##### #### #### #### #### #### ###  #  c        ####  b##   t   ####        ##  ##        ### #
# ##   ##   ## r  ##   ##  g## # #### #### #### #### #### ###  #              ###          c  #        ##  ##        #   #
#       #   #     l#   #          ##   ##   ##   ##   ##   ##      f          ###        #         ##### g c#####      l #
# # ##     ###    ###     ##b#    ## A ##   ##   ##   ##   ## g f                             #   ## ### b  ### ##   #   #
### ###  g##g  r    ## t ### ### #### ####f#### #### #### ########     #      #               ##  ## l #    #   ##  ##g  #
#   # ##   #      # #   ## #         bg                       # ## #   ## ff  #               ##  ##   #    #   ##  ##   #
###       ## # t  # ##       ##                               #    #                          ##   #   ##  ##   #g  ##   #
###        ### g  ###  l     ## ##        ##   ### #### ####              #            ##  ####    #    #  #    #   A### #
#         ###      ###          ##      f ##   ##   ##   ##    #       f#                  #######              # ###### #
#g     #                #            ### #### ###   ##   ##  # #                   ####          ###    #  #    ###  l   #
#  ## ##    ########    ## ##  f     ##  f                     ### #   ## ## #    ##                                     #
#     ## #   ##  ##   # ##     #### ###        g                     #     g     l##   ##   f                    ##g     #
###  ##  ##r         ##  ##  ## ##        ##    t         l l   t  # #        #        ###   g  ##f               ##     #
# #  #    ##   ##   ##    #  #  ##        ##  ##            t        ###            #    # ######         g     fl ##### #
# #  #######        ####### l# #### ###       ##                                        ##  ##           #####        ## #
# ## b##                ##  ##       ##           ## ###                   #     # #  g ##  ##     ## ##   ######     ## #
#       ###        #####     ##   #######          #######l           ## f      ##         ########## ####################
#    r   ###r    ######       g####b   ### # ## # ###    ####  b   t  ##        ##         #b########  ###################
#        ##    ######          #    ## #   #    #   # ##l   #         ##        ##                         ###############
#       ###    ####        ##    ####  # ####  #### #  ####           ##        ##  b          ####### ### ###############
#  b##  #### f  #        ##### ###    ##            ##    ###         ##   g   r##              ###########t##############
#   ##   ##              #####     #  #    ######   g#  #             ##        ##         ###b###l#######################
#               b         ##  l # a#### ##        ## ####  #          ##        ##                                 #######
#            ##    ##          ## ##       ##  ##       ## ## ##########   t    ##########                        #b######
#  ##        ##g  #####        r     ####   ####   #### r     ##  ##       l        ##  ##                               #
# #####  b         ######       ###   #   # #  # #  t#  t###  ##  ## t   b          ##  ##                          ######
# #####   t  l g     #####      #   #   ###      ###   #   #  ##  ##                ##  ##            ##############f#####
#   ##         ##      ##         #####  ##########  #####     f  ##    ######## t  ##                         #b####t####
#        ##   ###              ####      #   ##   #      ####g    ##    ##    ##    ##   b                        ####t###
#      b ##   ####         #    # g #g#### # ## # #### #   #      ##    ##    ##    ##                 ###################
#              ### r    g ###      ## #    # ## #g   #r##         ##    ##  b ##    ##                  ##################
# #  ##    c   ##         ###  ###g   # ####    #### #    ###     ## g  ##    ##    ##     #####b####### ##   ####   #####
#########                ###  l #  #  #   t# ## #    #  #  #      ##    ##    ##    ## t                              ####
###########          ##   ##    # ## ## #  #   r#  # ## ## #    t ########    ########     #####r####### ###########   ###
#  ##  ######       ###        ##       #          #       ##                                     ###################l####
#        #####      ####      ##   ###    ###  ###    ###   #        b                                               #####
#          ##   ##   ##       ## #  #  # ##      ## #  #  # #                         l                     #b#####g######
#b   ##       l ##               #  # ##    ####   t## #  #                                                             ##
#   ####                       ###    #   #      #   #    ###                            b                               #
#   ####  ##             ##   #    ## # ###r     ### # ##                b                         ###########t###########
#    ##   ##r  ##      #####  ## ###    #   ####   #    ### #          f                  f#####  ############  ##########
#    l        #####    #####   # #   #t # #      # #  #   # #                     g                                      #
#  l     r     ######   ##     #   ######l#      # #### #   #          g                                        ##########
##         g    r####          #####l #t    ####     #t #####  l                                             A         #l#
#   l         l b  #         t # r###   #####  #####   ###  # r                                                         ##
#           ##              ## #  #   ###      l   ###l  #  #                       t                            #########
# ### ## ## ########### ### ###   #                   # l       r  ###  ####  ######### f#  ####                         #
#     ##              ###      #              t     ##       ####  ###  ##     ############ ##   r     ##  ##         ## #
# ######### # #### #### ####### #               b  #         #  #  ###  ##     ####  #########      #      t t #      ####
#   f       #    ###        ##  #                         #  #     ###   #   #####    ###        r  #          #         #
# ##### ### # #### #### ### ## #               t       #   # #    ###    # f #####f     g  r   ###  ############  ###    #
###  c###             ###      #             #   #      # b  #  #####  ### r #####  ###    ##      #####    #####      ###
# # ### ### ## ### #### ### ##  #        #    #   #          #  #####  ###  ###     ###     l    # ###        ### # f    #
#          A##   ###        ##  #       #     #         # A     #### r r           ###      #    #c###        ### # t  # #
# # ########## ### #### #######  #      #      #     #   #     #####            # ####      ##     #####    #####     ## #
###            l f      ##       #       #     #      #  #   ########  ########## #####  #   # t                 f    #  #
# # ## ####### # # # ##### ###  #               #         #  ############ b###### ########    ##                    ###  #
#    ###t      # # #                       #    r               #########  ###### ########  l b  #  #          #  #   b r#
# #### ##### # # # # ## ## # #       #      #   #        t      #########  #####f    ####f  r #         ####         #   #
###          # #   # ## ## # #      #       #    #   #         ####        #####      ###    ###   t                ###  #
# #### ### # # # ###       # #      #        #   #    ##          l       #### f b##  ####   ############  ############  #
#    ###   # # # ### ##### ###  t    #          #       ##             l  ####   r##  ####tf ############  ############  #
# #### ### # # # #          #        #          t         ##   ####b f g   #####    b ###    ###                    ###  #
# #      r     # # # ## ## ###f       #              b      #   #########g #####     ####     #         ####         #   #
# # ##  ## ### # # # ## ## # #                                  #########  ###############      b#  #          #  #    l #
#       ##    g g          # #    #                          ############  ###############   ###        r        f  ###  #
#g##### #######  ### ## ## # #  ##     #       #             ########  ################  #   #                  c  g  #  #
###           ##     ## t      #      #         #          #   #####      b     ######      ##     #####    #####     ## #
# ### # # ### ######### #### ##       #         #           #   ####              t###      #    # ###        ### #  b # #
#     # #          l       ###         #         #           #  #####  ###  ###g    #####        # ###        ### #     g#
# # # # # # # ###### ####### ##    #                         #  #####  ###   #####  ####   ## r    #####    #####      ###
# # # # # #g#      ###              ##           #          ##    ###    #   #####             ###  ############f ### r  #
### # #   # # # #### ##########       #       #   #    t     #g    ###   #  ######           t   c  #          #         #
##  f # ### # # g                        b     #  #          #  #  ###  ##  r  ####g ###### ##      #          #t     ####
### ### ### # # # ## # ## ## ##       #        #   #   #  #A ####  ###  ##     ############ ##         ##  ##         ## #
# # ### #     # #    # ## ## ##        # #      #  #    ##         ###  ####  #########  ##                         #### #
#  ####     l   ####    g      #### # r    ##           #####    ####   ##    ##f  ####   b ##    #rl ##   ### #### #### #
# t ##           ##      b     #####      ### #          ###     ###    ##   g## r  ###     ### #    ####f#### ###   ##  #
#          ##                  ####### ## ### #           ##    ## #    ##    ##    # ##   #### ####l#### ###   ##   ##  #
#        #####             ##     ####    ### #         # ##t         ###      ###         ###gg ##   ##   ##   ##r  ##  #
##       #####b          #####  # ####### ####           ###           ##      ##           ## g ##   ##   ##   ### #### #
###       ##     l   #   ####   # ####### ###### ##### ##### #         #   ##   #         #      ### ###   ##   ### #### #
###                ####   # r   # #######   ####      ###### ###       #        #  t    #### # b ### #### ###   ##   ##  #
####          ##   ####         g####### ### ###############  ###### ###   ##   ### ## ### # #   ##   ### ####l###   ##  #
###    l     ####   ##t        ########      ################  ##  #r ### b##  ###  #                          #### ###  #
#             ##              f #######       ###############  ## l   f## t##  ##      ##   ### #### ###   ##t  ### #### #
#                         ##     g#####     g# ######   ####   ##     ###  ##  ###                            f ##   ### #
#  ##     ##              ##       ###       # #####  ## ## #  ##     ##  l     ##    g##  ###   ##   ### #### ###   ##  #
#  ##   #####          r  l   #       #      #       t        ##      ###  ##  ###                    ##   ### #### ###  #
# ####  #####    t  ##        #  # ## #     t# ####        g  ##       ##      ##       ##  ### #### ###   ##   ### #### #
# ####   ##         ##   ##      # ## #  r   # ##### ##### ## ##c l   ###      ###      ##  ##   ###f###   ##   ##   ### #
#   #                   ####     # ## #    l # #####      #####         ##    ##         #####   ##  l### #### ###   ##  #
#        t   ##        b ##      # ## #      # ###############          ##    ##         g##### ###   ### #### #### ### r#
#      t     ##    t##            ####        ################         ##      ##         #                              #
#      t          #####   f   #  ######      ################ l            t                                             #
#                 #####       ########## ######        ######    A#    ##      ##    #b              ###   ### ###   ##  #
##     ##c         ##           ######## ###### ####### #####     ##   #        #   ##     #### ###   ##   ### #### ###  #
###   ####                    t                                  #### r        t   #### t  #### ###g  ##   ##  a### ###  #
###   ####    #            ##       l                              ##              ##       ##   ###f#### ###   ##   ##  #
####   ##   ####     ##    ### ##############################      ##         t    ##               A#### #### ### g ##  #
####l     A ####  l#####  ####         l   b    r              t  ###              ###     #### ##    ##   ### ###   ##  #
# #          ##    #####   ##                  r            a#  b ##                ##r   ##### ### r ##  f##   ### #### #
#  f         ##     ##         ###############################    ##   b            ##                                   #
#l       #           b    r               b                  ##    ##  # ##  ####  ##    ## ##   ##  #### ###   ##   ##a #
#      ####               ##  #      g                    f  ###  f#####  #  #  #####   ### ##   ### ###   ### ###   ##  #
# ##   ####      ##       ##  #               l               ######     l          ###    #### ###   ##  g### ###   ##  #
##########################################################################################################################
