metadata:
  gen_time: 7.736026048660278
  timestamp: '2025-04-18T22:53:56.115714'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##   ###  c                  #### #  ###t######     g      l   #        #     #     #                             r### ###
#   ####         l            #      g   ###t   ##### #  #  #  #      r #     #     #      ## #### #### #### #### #### ###
# r  ##   c##           ##   c # ##  ###    ### ##### ##### #  #  ####  ####  #  #  ####                      ### ###   ##
#         #####        ### l   # ####### #####  b#### ####        #  #  # r      #         #   ##   ##   ##f  ##   ##   ##
#       l  ######       ###   #   #####  b####  l###   ### g      #  #  #        #r        ##g###   ##   ##   ##   ### ###
#            #####   g  ###  ##   #####   ##### ####   ###     ####  #############  ######### ###b  ### #### ###   ### ###
#   ##         ##   ##   # c  ## ####### ####   ##### ##### #t #  #    g#           #  l       ### #### #### #### ###   ##
#  ####  ##        g##         #   #####    r#     ##     f #  #  #A    #           #                         ### ###   ##
#   ##   ##        ####          ##      ###### ###   #####    #  #  #######  # r#  ####   ## ###   ##   ## c ##   ### ###
#         c     tl  ##   ##    # ####### #####   #### ##### #         c    #  #  #         ## ###   ##   ## r ##   ### ###
#            ##          ###      #####   ####   ###   ###  l              #  #  #    r  r #   ##   ##   ## r ## f ##   ##
#     ## g  ####        ###     t #####   ####   ###   ###     #######  ####  #######  ##### l ###l#### #### #### ###    #
#    #####   ##     ##  ###       ###### ###### ##### ##### #  #                    #      ## #### #### #### #### ###    #
##    ####         r##   ###   # ####### ###### #####g##### #  #                    #               ##   ##   ##   ##    #
###    r#                ###   # ##   ## # r ## #  ## #  ## #  #                    #          ##  b##   ##  t##   ##    #
###     #ct              ###        f l                        #                    #      #   ##   ##f  ##t  ##   ##    #
##    ####          ##   ###   ## #   # ##   # ##  # ## f# ##  #                    #      ## ### r ##   ##   ##   ##  # #
#   f#####   ## c   ##  ###    ## ##### #####  ### # ##### ##  #                    #      ## #### #### #### #### ###  # #
#   b ##    ####        ###    #        #####  ### # ##### ##  #######  ####  #######  #####   ### #### #### #### ###    #
#       b    ## a        ###   # ##### ###### #### g ####  ##              #  #  #         #  l##   ##   ##   ##   ##    #
#                   ##   ##b    ######r######b####   #### ###              #  #  #         ## ### r ## l ##   ##   ##    #
#  r##   ##        ####         #####  ##### ##### #####l####  #  #  #######  #  #  ####g  ## ###   ##   ##l  ## f ## c  #
#  ####  ##         ##c         ##### #####  ##### ##### #### t#  #     #           #      #   ### ###   ##   ###  ##    #
#   ##         ##a  ##   #   f# ##### ##### ######f####   ###  #  #     #           #      #   ### #### #### ####  ##    #
#            #####      ###  ## ####   #### ###### ####   ###  ####  #############  ######### ###   ###  ### ###   ##  # #
#          ######       ###   # ####   ###   ####   #### ####     #  #  #        #         ## ###   ## b      ## l ##  # #
# r       #####        ###     #####   ### A ####   ####  ###     #  #  #        #         #   ##   ##   ##   ##   ##    #
#  c ##    ##           ##r    #####  t###   ####   ##### ###  #  ####  ####  #  #  ####   #lf ### ###   ##gf ###  ##  b #
#  r####  b                 c ####### ##### ###### ###### ###  #        #     #     #    t ## #### #### #### ####  ##  # #
##   ###         g           ####     ##f   ## a   ##   # ##   #        #     #     #      ## ###   ### #### ###   ##  # #
#  ###  ##     t               r                                                                ## ###     #           # #
#       ##                 b  ####  ####################### f                                       c# ##  ######  ## ## #
#      r##  ############# ########  #######################        a                                 #  #                #
#####   #   #                  ###b                 b        af ########################   ######    #c #bb              #
##  ##  #   #   #      ##                                       ########################        # r  #  #####     # ######
## t    #   #   ## l   ##    #                 t      #######   ########################     #g      #     l#     #      #
##  ##  ##  #   ##     ##   b# #   f      l   r       ####### a                           t  #########      #     #      #
###  #  ##  ##  ##     ## t  t #                r     #######                                 g             #     #      #
# ##    ##  ## ### ####### ####      r  ########      ##r        a  r     a  a                 r            #r  t ########
#  #    ##   ### ###        ###  f      ########   #####     ######   ###   t  ### b ########      #### f   #   r        #
#  #    ##    ##  ###     t   #         ########   #####  f #######   ###      ###f a###### #         #     #         #  #
##     ####   ## A  ##        #                    #####    #######   ###a     ###   ###### #   ## #  #     #     f   ####
##     #l   tb##   f##        ######        g      #####       r      ###  a   ###       f  #   #  #  #     ####    t   f#
#       lt#  ###c   ##  b  r########   f           #####              ###    f ###     a    #   #  #  # g      #         #
#   g# ##### # ## ##### ## ####               l    #####   ##         ###      ###        f ##### r####         g        #
#    #                b  ###                  ##########   ##  b a ab ###  a  b###   l r  a               ################
#c b                      ###  ########       ##########   ## a       ###      ###a  b               g   b#             ##
#  ### #   # #### ######### ###########                    ##         ###      ###         ###   #######  #             ##
####   #  ## r               ##                 r    b     ########   ###      ###   ######  #   #     #  #             ##
####      ##     t           ##          #### ##         ##########   ###      ###   ######  #   #     #c ##########    ##
#  ### ####   l      g   #########       #######    r    ##########a  ###      ###   ######  #   #f ## #  A        #    ##
#       ##            b  #     ###                     ######                   A   a        # g #f #  #        #  #    ##
#   ##  ##r   ## #### ## #     ###                     ######             a        b         #   #  #  # ##     ####     #
####### ##r   #   ##   ###     ###             f       ######          a             f       #   #  #f # f#              #
###     # r   #   ##    ##    # ## b              ###b ######   ########################     #####  ####t #            ###
#   #         #   ##   ##   c # ##                ###  ###### a ########################                  # f      g   # #
#   ###########   ##  ##     c#        g          ###  ######   ######################## a                #      ####  # #
#l #### ###r      ##  ##     #               ########  ######    a  f    ar  a      a      ##          ####      #  #  # #
####              ##l  #     # ##  ######   b########  ######                               #   #####  #         #  #  # #
#####            ###   #     # ##  ######    ########  ######                a     b        #  c#   #  #     g   #  #  # #
#  g#      # # r  #  c     # c#    ## ###          ### ##     #     b  #    #   #    ##     ###            #    # # # A  #
#                             # ####  ##    l       ##  ####    b      #    #   #    ##     ###         t####g  #   #    #
## f# c    c           c      #  #   ##    ## ### l  ##  ##   #  l  b  #    #   #    ##       #  ###### ####             #
### ####### # ###       r          ##   # ###  ## ##   ##   b #        #    #  ##    ##     # #  #  a   ## #   gl        #
###   c     # #         b  c  ##   ## # #     #    # # ##f  # #        #      l#     ##    f  #      #f  #      t   l#####
# # ### c  c# #         g     # b  ####  #### #####  ####     #        #    #  #     ## ###     ######   #           #####
#          l# #               #    ##########  ##########     #     r  #    #  #######    #     ##   # t  A   #    #     #
#### f      # #               #     ####################      #        #    #  #######    #     ##            #        a #
#  #      r # #c           c###      ##### ###### #####                #    ##########    #   t         l        g    t  #
## ###        # ###                   ####        ####        #    #####    ###     ##    ###        #  #          A     #
##   #    r ### #    b  b          #l  ### l      ###A b#  g  #  r #####   ####     #######        ###  #    #      ##   #
#### #####  #   # #                ##   ##        ##  g##     #     l  # b #        #######          ##   lc # ##        #
#  #        # ### #                ##   g#        #    ##    g#        #   #       t####              #      l  #        #
#  ###               g            ##  #     #####    # b##   b         #   #####  g ####        #             g ###b     #
#    b                   #        ##  ##   ######   ##  ##   l#     t  #########    ####l       #  g           a         #
####    c #  c         f #    g#  ##   ##  ######  ## t ##  # #        ##   ####       #  #   c    ##                    #
#         #                    #   ##   ##  ####  ##   ##   # #        ##   #       #  #  #  #  #  #         l t     a r #
# ##   r  #   c   f     f l    t   ###   ##      ##   ###              ## r #       ####  # ###    #                ## ###
#c     ####      fc      ####   f  ##     ##    ##     ##     #             #       ####### #####                   #### #
#                        #     #   #        t f   r  r b#   # # g           #l      #######  ####            #c     b##  #
#  #####  #    c     c   #c#########                   t#######r  #### ######       ###      #####      l    #           #
#  #   l  #         ##   # #     ##  ##      ##      ##  ##  #####           l      ###    ####### g    ##        ##     #
#  #    b                # # ##     ##      ####      ##             r              ###     ## ###              #        #
#   r  lc               c# # #      #       #  #b      #                    ###     ####### ##        l   # #      #     #
#        b     c ###c    # # #l     #  #   ##  ##   #t #       #####        ###     #####   ##               c #   #     #
#     ct ## #      #     # #   #    #  #####t   #####  #    ####  ##        ###     #####  ###  ####       a # #         #
#c          #      #   # # #   ##  ##   ###l     ###   ##  #####  ##  ### #####     #####    #######    ##         #     #
#   g       #      #   # #         # l   #        #     #    ###  ##  #      ##     #####  #####        ###            # #
# # #########    ###     # c                                 l    ##  #  rb  #### #######      f        ##           # # #
### ########    ## c   ###     # l     #  b   t     #       #     ##  #      #### #######    # ###  c   ##       #  ##   #
###     ###    g   #####   ####   #   #       #     # f   t    ##  ##  ## l    ##  ##  ##    ########## ## #######  ## # #
###     ###        ############ # # # ####### # # # ##### ############################ ################ ## #######  ## # #
#    b  ###    b   ############   # # #   # #   # #   #   #  ######################### ################ ## #######  ## # #
#       ### f  ##  ####      r ##r# ### ### ### # ### # ###   ##  ##   ##      ##  b##  ## ############ ## #####    f    #
#  b    ###    ##  #### t    g  # # #   #     # #   #       l                                  ##        r #####       l #
###     ###    ##               # # # # # ####### #b#######   ##  ##  b##      ##   ##  #   g  ##          #####     # ###
###g    ###g   ##                     #     b #   #   #      ########################## # #    ##           ####     # ###
###     #### #### #####  #####  ### ### ##### # # # # #####  ########################## # #   r##           ######  ## ###
###    t#### #### #####  #####  #f    # # #     #   # #   #  ##  ##  ##b ##  ##  ##  ##   #   l     t       ######  ## ###
###     #### ###   ####  ##### f#  l### # # ### # # ### ###                           b                        ###  #    #
###     #### ###   ####g        # #   # #   # # # # #   # #  ## g##  ##  ##  ##  ##  ##   #             f      ###  #    #
###  r  #### ###     ##       t## ### ### # # ### # # # # #  ###################   #### # #              f     ###  #    #
##########           ##          b#       #      f# # # #    ################### # #### # #     g r#### ## ##  ###  #    #
#######    #      ###########   ### ###t# ### ##### # # ######     ##  ##t     #          #l f g   #### ## ##  ###  #    #
######  ####    c ###########   #     # # #   #       # t                           r     g l      #### ## #######  #g   #
######  ####      ############# #     # # #   #       #      #     ##  ##      #   ##     #    f   #### ## #######  #    #
######  #### ########      #### ### ### # ### # ### # # ########## ############# ###### # #####    #### ##  ####r        #
######  #### ########f            #       # b #  l# # # #    ##### #############  ##### # #####    #### ##  ####         #
############ ########  ######  ## ### ### # # ### # # # # #   ##   #    ##    ##    ##  #  ####A   #### ##  ####    f    #
############ ########  ######## # #g# # #   #   # # #   # #                                ############ ##  ######  ######
######       ################## # # ### # # ###a# # ### ###   ##   #    ##    ##    ##  #  ############ ##  ######  ######
######       ################## #     # # #     #   # #   #f ##### ############### #### # ############# ##########  l   f#
######       ################## ### ### ##### #f# # # ## ##  ##### ############### #### # ############# ##########       #
######       #########                #       #   #   #      ##  #    ##   ##   ##   ##   ############# ########## ##### #
##t t        #########    ##### # # # # # ####### # #### ##      g            t g   f   g  ############ ########## #####l#
##   f     t #############      #f# #   #     # # # #        ##  #    ##   ##   ##   ##  ############## #########   g    #
#            ############  ######   ### ### ### # ### #b ##  ##### #################################### #########        #
#            ####         #####   # # #   # #   # #   #t  #  #####  ################################### ###########    g #
#            ####         ##### # # # ####### # # # ##### #####  ##   ##  ####  ##   ##  ############## ###########   ## #
#          ######r  c  ######## # #   #       #     #            gf                        ############   #########   ## #
##########################################################################################################################
