metadata:
  gen_time: 5.460165023803711
  timestamp: '2025-04-18T22:58:56.167549'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
####### # b ####  ########## #    ##   ##     r     c   b b   ##       A  ################################################
# #####     ####   #########          ###                     ##             ##      bb  r                               #
#  ####l    ####    #### ###   ##### ####          cl         ##            c## r l       g                      g       #
#    l     #######       ###   ##### ####        ###        f                ##                     r   l                #
## ######  #######       ###   ##### ##          ###                c   l    ##               g          b               #
## ###### ########  ########    ####    #r         #               r    c   t##      r     b                       t     #
##   #### ########   #######     ###    #          #            tc                 r                   c                 #
##   ## t            b######  ######  ###          #               b        c    #########################################
##  ###   ####g    #########  ###### t###          ###           t           f   #########################################
##  ###   #####   ##########  #####   ###c         ###         c   t         f                                           #
##         #####  ##########  ###########            #       c                                    f            b         #
##       l  ##### ###         ####### ######         #       b                 c #########################################
##       ############       g ##   ##  #####         #       l     ## ### ################################################
##   #    ######################  ###   #  #         ### cc        ##  ##                  r                             #
##  ##l    t ### ##############            # t       ###           ##  ##             l     b                         r  #
## ###     g ### ######### ##   g g t ###  #c      l ###           ##  ##                                                #
## ###           ####      ###   ###  ###  #         ###   c     t ##  ##f b          r    bb   t                        #
##      ###############    ####  ### b######         #             #######################################################
##   t   ##############    ####  ###    l###         #                          f#########################################
##        ###           t  ######### r               #    t                                          t                   #
##         ##      t################ ####          ###                      c                     r             A     b  #
## ######   #   #   #####################   fc     ###                 f                                                 #
## #######      ##     #######       ####     f    # b               f           #########################################
#  ########     ### ##  #######    #####      c   b#                             #########################################
#  ########     ###### t #######  #######          #               b         ##    f                                     #
#   #######     ######    ######   g             ###        g   f            ##           l     lt                  l    #
#    #####   ## ######     ### #             c   ###                         ##                 f           f  t         #
#########    ## ##############    ## f  t  t      f           ## A    c t    ##      l      b      t    A                #
###############  #############    ##   ##     r           t   ##             ##               l    t   g                 #
###############   ############    ##   ##t                    ##    b   c ################################################
#           f##      ######  ###         l   t        ###        ###   l           # # #                g   f   ##       #
#                 t  #####     #  f  A   #l           ###        ###l       t   #  # # #  #######  #######  ##      ###  #
#    ####           ###               ## #        g    ##      f ##             #                               ##     b #
#       #                     #####   ####    #      t                     #    #     t                                  #
#   ##                ##      #####    f#     #         ###    ###         #     ######  #### a##  ##  ##  ###a ##  ##  ##
#  ###                ### #  #####  #        ###### #   ###    ###   # ######                                           ##
#                     ### #  #####               ## #    ##    ##    # ##                                               ##
#     #          f    ### #  #####       ##    # ##      ##    ##      ## #    ## # a# #  ##  # #  #  #  #  #  #  #  #  ##
#  l#         ####     ## #          #  l##b # # ##     ##      ##     ## # #  ## #  # #      # #  #  #  #  #  #  #  #  ##
##g      l             ##      b             #   ##  ##            ##  ##A  #     #  # #      # #                        #
### ##                                 g     #    # ##     #  #     ## #    #     #  # #  ##  # # b                   b  #
### ##               #   #  #              #      # #####        ##### #      #                    # # #  #  #  # # #  # #
# ###                    #      f  #    #      #  #########    #########  #                        # # #  #  # a# # #  # #
# # r   ###g t           #         #              ## ######    ###### ##           ######  ##  ##                        #
#    #              ####   #####   #      #            ############            #               a   a       b       b     #
##   #              ##        ##                                                                   # #  #  #  #  #  #### #
##   #  ##               l       # ##                       g                     #  #######  ###  # #  #  #  #  #       #
#    f                       t b             ###        ###    ###        ###     #                                 #### #
# #    g         #              ###  f                                                                                   #
#    ##                              #    #        #       #  #       #        #     ###  ##  ######  ##  ###  ###b      #
##   ##             #   #       g   t#                    b#  # l    l           ##     f                           ##  ##
##    #    #    #      ##         t  ###  ##  #    #                  #    #  ##     b                                   #
##     f     # ## t      f l ##      ###      #    #    l   l         #    #     ## a####  ##  #a # #  ## b##  ###  ##  ##
## ####      #  ###       ## #            ### #                            # ###  f            #  # #                    #
#######      #   ##              ##l        # #   ##########  ##########   # #                 # a# #  ##                #
#    ##      #   ##        ##    ###    #   #   #                        #   #     ##  #  #b#              # # #  ###  ###
#         A      ##   #    ###    ##  # #                                              #  # #              # # #         #
#      g   #     #    #          t##   r        #   g#  ##      ##  #    #         ##  #  # #  ##  ######  # # #  ###    #
#     ## f   ###g###               #    #b           ##            ##                                                  ###
#     ##     ###      ###             #               #####    #####                      t                              #
#    # #    #        # ##  ###   #     # ##   ########              ########   ##### # ## #  #             #             #
#      #    ######## #  #c       #     #       #####                  #####    l  #r r  l                  #             #
# ######           # ## #        #     #       ####     ##  ##  ##     ####   t   ####### #  #             #             #
# #       ####     #    #        #  #### #t      ##   ##############   ## f     # ####### #  #             #             #
# # ##    #  #     #    #   ######  #    ##   r       ##############           ##      #r                  l             #
# #  #  l #  #     #r   #   #       #    ##r           ####    ####     b   l  ############ ##             #             #
# #r # ## #  #  ####    #   # ##    ######## t  ##      ##      ##      ##    ############# ##             #             #
# #  #  # ## #  #       #   #  #         #####  ##      ##      ##      ##  ####   #     #                 #             #
# #  #  #    #  #       #   #  #          ####   g     r               fl   #### ##  ######### #  #        #             #
###  ## #    #  # g     #   #  #    r     ###         t          t           ### ## ########## #  #A       #             #
#       #  A #  #       #   #  #        b  ##     r l l##        ##       g  ##              #                           #
#########    ####       #####  ########          ##  #####     r#####  ##       r############### ## #      #             #
#                                     #          ## ######l     ##### ###        ############### ## #      #             #
#     #   g                           #     ##  ### #######    ###### ####  ##                 # f# t                    #
#     ########################        #    ########  ######    ######  ########b ####################  #   #             #
###    l               rr    #  #######    ########  ######    ######  ########  ####################  #   #             #
# #                          #  #        l  ## l###########  f ###########  ##                      #  b                 #
# #       ######             ## #        l       #########      #########  fc    ##    #### # ####### ##   #    #        #
# # ##    #    #               f#     ###        ##  #####      #####  ##        ###     ## # ####### ##   #    #        #
# #  #   l#  # #  ###############     #    ##          ##        ##        r ##                     # f#   a    #        #
# #  #    #### #  # r                 # # ###    r                           ### ########################  # #  #   #  # #
# #  #         #  # ##   #  #         #   ####    g                         ####                       ##  # #  #   #  # #
# ####         #  #  #   ####     #####f #####  ##  l   ##      ##      ##  ####  r   #     #af#  #  #  #  #        #    #
#      lg#######  #  #            #      ###   t##     f##    t ##   r  ##  t ############################ ### ##   # ## #
#        #        # ##            #      ##            ####    ####     t      ########################### ### ##   # ## #
# ##     # ##     #           l   #   t  ##           ##############           #   #    a#  #           g#  #b #c      # #
#  #     #  #     #################      #       ##  r##############   ##        ### # ###        # #############   # ## #
## #     #  #                          ##      ####     ##  ##  ##    l####      ### # ##     # ### #############   # ## #
#  #     #  #            #             #       #####                  #####                                     #   r l# #
#  #     #  ##############       g  ## # ##   ########              ########   ##################### ############ # ######
#     ###    ##  f ####    ##    ###                b     g            f         ###  ### #  #######   ### ###### #     ##
#     ###    ##    ####    ##    ###          ######    ##########    ######   f                                # #   bt##
# ##         ##    ####f   ##         ##      ######    ##########    ######   r #    # # # #        #     ###  # #      #
# ##  l            ####               ## ##   ######  ##############l ###### f #### l   ##  #  ######## ##  ### # #     ##
# ##  g            ####b              ## ##         lb##############          b#####   l######   ###  # # # ###  ##  r  ##
# #  c   ########################      # ## l  fg     ##############f          ############### ## ##  #   #  ######     ##
# ##   b ########################     ##      ##   g##################    ##         b      ##          ### #   ###     ##
# ##        r f    ####               ##      ##    ##################    ##                                     ##    l##
# #        f       ####                #      ##    ##################r   ##                                 ####t#### ###
# ##        g  l   ####               ## ####### A  ##################    #######                                     ####
# ##      ##       ####       ##l     ## #######    ##################    ####### #     b   #  # # # # #######  ##########
#  #      ## ################ ##      #  #######    ##################l   #######                                        #
# ##r  r  ## ################g##      ## #######  ######################  #######  #                          ###     ## #
# ##      ##       rf         ##      ## #####    ######################    #####  #                           ##        #
# ##          ##          ## l     g  ## #####    ######################    #####  #r       #  #                #### #   #
# ##      l   ##          ##        b ## #####f   ######################    #####  #    # # #   ## #            #### # # #
# ##      ##               l c##f     ## #####    ######################  b ###### #          r      ##       #    # # # #
# ##  l   ## ################ ##      ## #######  ######################  ######## #   ##   #  # #         #   ##  #  ## #
#  #      ## ################ ##      #  #######    ##################    #######  #### ###        # #  #  ##      ##### #
# ##      ##       ####b      ##      ## #######    ##################    #######           #  #l# # #   # ##     ########
# ##r   b      l   ####               ## #######    ##################   l####### # b       #  ##  #  ## #  ##        ####
# #c          r    ####    f        f  #      ##g f ##################   b##      #   l     #  ##### ###     #### #### ###
# ##      l        ####  l t          ##      ##    ##################                                           ##     ##
# ##     ########################     ##  l   ##  b ##################lrt ##b  b #         f##    ###########   ###     ##
# #      ########################      # ##           ##############       b   ############    ## ##      ## ######     ##
# ##     c         ####               ## ## t         ##############                                                    ##
# ##               ####               ##f##  f######  ##############  ######   ###           ### ###              #   b ##
# ##         ##   g####    ##         ##      ######   t##########    ######     # # ##  f#          ## #   #    c#      #
#g    ### l  ## r  ####    ##    ###  f       ######    ##########l   ######      ##   #  # #         # #     ##  #     ##
#   g ###    ##    ####    ##    ###   g      r          tr           f          ###  ### #  #######   ### ###### #  c  ##
##########################################################################################################################
