metadata:
  gen_time: 9.960838794708252
  timestamp: '2025-04-18T22:46:45.753093'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  ###c###    c ##g## ## ##t## ## ##      ### ###  # #          g              t                           # #  # #     ##
## ### ##### ## ## ##        g ## ## ## ##### ### ## #                      g    tc                 r        #  # #     ##
## ### ##### ## ## ## r        ## ## ## ##### ### ## #            tt         g     b       c                 #  # #     ##
##  b  ##    ## ## ##          ## ## ##    ##     ## #          ########            l                        #  # #     ##
## ##c ##    ##    ## ###  ### ##    ##    ##  ## ## #l       A #      #            ############             #  # #     ##
## ##  ## t  ## ## ## ###  ### ## ## ##    ##  ## ## #   r      #      #  b         #          #      l      #  # #     ##
##           ## ## ## ###  ###l## ##t##           ## #g         # ###  #            #         t#             #  # #     ##
## ############ ##     A          ## ############ ## #              ####       c               #               t# #     ##
## ############A## ############## ## ############ ## #                        t      #####  t  #                # #     ##
#               ## ############## ## g bg          # #      ###a                         #     #    t  #        # #     ##
#   ##    ##    ## ######  ###### ##    ##    ##   # #      # #b                         #     #       #        # #      #
#   ##    ##       ######  ######       ##    ##   # #      # #   b        g         g   #######       #   ###  # #      #
#   ## ## ## ##### ##     #  rb## ## ## ## ## ##   # #      # #  l            l      t               # # t # #  # #      #
#   ## ## ## ##### ##     #    ## ## ## ## ## ##  t# #      # #         c             f              # #   # #  # #   r  #
# ##  r##t   ##### ##     #    ## ## ##    ##c r## # #      # #                                      # #   # #  #        #
# ##         ##### ## ### #### ## ## ##         ## # ## ##### ## #   ######################     ###### ##### ###  ########
# ##   #########   ## ### #### ##    ########   ##             b             #                                 g        g#
# #    #########   ##          ##g   ########    # # ## ##### ## # ########### ######### ## # ### #### ##### #    ########
# ##   c  t c   ## ## ##  # ## ## ##            ## # #      # #                                      #g#   ###  # #      #
##### ## #  ##b ## ## ##  # ##g## ##  ##  #### ### # #           g                                   #l#       t         #
######## #  ##  ## ## ##  # ## ## ##  ##  ######## # #                  g                            # #                 #
#               ## ## ##    ## ## ##               # #                                       t       #        g       g  #
###  ##  #######      ##  # ##       ####### ##  # # #  #### ### ##     ######## ## ###### ### ####### #####    ##########
###  ##  #######      ##  # ##       ####### ##  #        #   bl                    t  #                      l    #     #
###      #######            g        #######   t # # #  ###  ###     ######### ###  #    ####     ###  ###      #    #####
#rt####  # c    ##  ##### ###### ### f    ## ####  # #                                                ##       f         #
#  ####  #      ##  ##### ###### ###      ## ####  # #                                   g             g                 #
##   ##  # #### ##      # ##     ### #### ## ##    # #        l                                                          #
##   ##  # #### ##      # ##     ### #### ## ##    # #  ###  ### # ###   ####     # ######    #######    ###### ##########
##   ##    ####                  c c #### b  ##    b     #                                                         a    ##
#    ##    #### ## ###### ######## # ####    ##    #    ##   ###  # ##          ##  ###  #   #####        ###    #   #####
##  #    # #### ## ###### ######## # #### ###g  #  #           l                                                         #
##  #    #r####             f  g     #### ###   #  #                                   t                 g               #
#   #      ####      ##       #t     ####       #  #                   b            t                   t               t#
#l   r   # ##  ###  ###    g  ## # #   ##t###   #  #                                                              ###    #
#        # ##  ###  ###       ## # #   ## ###   #  #                                              r               # #    #
##  #    # ##   f               t      ## ###   #  #                                           t                  # #    #
##  #         #### ######  ## #### #  # c       #  #                                                           l    #    #
#   #         #### ###### ### #### #  #    ##   #  #                                        A                g   l  # t  #
#   #     ###                         t##       #       ##   ###                    t  g                            #    #
#     t   ###    # # ## # ##  #b##     ### #       r    #               #                  #                      # #    #
#   ###   ###    # # #### ### #t##     ### rt # #       #                                                  g      # # flc#
#                t     a       g                                                                                       # #
#                  g                         ##              ###            a##            #       ### #              ## #
#                  g                  l  r    # #  #    ##   # t              ##                  ##   ################  #
#        tg      a     f           a                                           ##                r                       #
#               f                  g          # #  #    ##   #       ####       #              ###     ## #############  #
#         t   a    a                         ##              # #                           #        ####         t    ## #
#                              gt            #                                                             l f   l     # #
#                                       b    #               # ###        ##             ##        #####         t     # #
#                   a                        #              ##   ##        ##           ##        ##  g##              # #
#                     c                      #             ##     ##        ##        t## b      ##     ##      b      # #
#                                            #            ##       ##        ##       ##        ##       ##            # #
#                   a   r                    #          b##         ##        ##  t  ##f       ##         ##           # #
#                                           l#r         ##           ##        ##   ##        ##           ##    b     # #
##  ###  #### #### ###### ### #### #  ###### # r       ##       b     ## f   t  ## ##        ##           r ##         # #
#r  r      l            g                    #        ##               ##        ###     r  ##    t         A##        # #
#      a           r                   t     #       ##  b           f  ##        #r       ##    a            ##       # #
# g          a              a                #      ##                   ##               ##                   ##      # #
#                                   b        #     ##                     ##        t    ##         a           ##     # #
#  g     fg                                  #l   ##    a    a             ##           ##                      r##      #
#                                            #   ##                f        ##         ##        t                ##   # #
#            l               f               ## ##                           ##       ##                           ## ## #
#   t    t       a                            # #               l    t       l##     ##                             # #  #
#       r                                     # #                            r ##  r##a                f t       l  # #  #
#       l                           r    b    # #   r    b  f          b        #####                 a       b     # # r#
#      r                              f      f# #                t     lb             b                             # #  #
#                             t              ## ##                              #####                              ## ## #
#                             l        a    ##   ################################bf ################################  l###
### ### # ###     # # # # ### ###t## ### ### # #                                                      ##                 #
##    # # # # # ### # # # #       ##       # # # # ### # # # # #    #      ##         ####         ##r##          g      #
### # #   # # #  ## #     # # # # ## # # # #                                                          ##              b  #
#c# # ### #   #  g#l### ### # # # ## # # # ### ### #   # l # ### # #       ##         ####     ################# ## ######
#     ### #t### # # ### ### # ### ##b###r# ### ### # # ### # ###   #t      ##  ####   ####     ################# ## ######
# ### #   # ### # # #   #   #  #  ##     #   #                           ####  ####   ####        ###    b  ##          ##
# ### # # #   # # # # # # # # ### ## ### # # # # # #l# #   #b# # ###     ####  ####     l    r    ##        ##  g       ##
# #   #b# #r# # #   # # # #t#   # ##   # # # # # #   # # # # # #   # r   ##    ####            t  ##        ##t         ##
# # # #   # # # ### #g# # # # # # ## # # # # # # # ###a# # #   # # #     ##    ####    ##         ##        ## f        ##
### # # ### #   ### # # #   # ### ## ### #   # # # ###   # ### # # ##    ##    ####    ##         ##        ##          ##
##    # ### ###r#       ### #  #     l#  # ###                                                                          ##
### ### #   ### # # ### ### # ### ## ### # ### ### #t# ###  t# ### ####  ######## r                  # #####  ##  ########
#   ### # # #r  # #       # # # # ## # # # #       # #   #   # ### # ##  ########        t    t      # ###### ### ########
# # #   # # #   # # # # # # # # #t## # #r# # # # # # # # # # #   #t#     ########      A    rb             ##            #
# # # # # # # # # # # # # # # # #l## #   # # #                     #     #####       ###                  f##    ##      #
# ### # # # # # # #   # # # # # ###### # # # # # r # # # # #g# # ###     #####       ###        l  t       ##    ##t t   #
#  #  # # # # # # # ### # # # # t   #  # # # # ### # # # # # # #  #      #####       ### f  b            r ##    ##   g  #
# ### #   # # # # # ### #f    # # #### #     # ### # # # # #   # ###     #####l      ###    l  ###         ##    ##g     #
#t# # # ### # #       # # ### # # ## # # ### #c# b     # # ### #l# # #########t  lr          r ###     l   ##    ## l    #
#   # # ### # # ### # #         # ## #  r                                                                      #### f l  #
# # # # #t   g      # # # ### ###    ### #####r#               # # # ###        l     #### #A ####    ########  ###   t  #
# #   #   ## r       ####  c                  ####             #  ## ###               ### #     ####        ##  ##      #
###   #   f#f        ##############     ## #                      ## ####      f         # #  ## ####t#      ##  ##  b   #
# #  l#   r##    A       f r      # #####l # #                    ##   ## r       b      #       #### #      ##  ## b  l #
#    #     ##  r  t  #            # ########    #### ########     ##   #####       #     ##                 f######## ####
##   #     ##       #         a  ##          r    ## ####### #  ###    #####       ##    ##      ###  ##f    ######## ####
##  #f      #      t##    r  c   ##     f       # ##         #   ###   #####       ##     #           ##     ##        g #
#   ##     #        ##  b       ### #      A      ##         #         ##                 #      ###         ##          #
#  ###     #        ##         f# l #l  c  g      ## l     f#    ##  #   g                     #####  ##     ##          #
#  #       #       a## l       ## f ##             #        #   ###  ###            #       ##  ##### ##     ##### ### ###
#  # # l   #   f    ##         #    #  f           #         # t ##  #######          ### # ### ##            #### ### ###
#  ###      #    l  ##        ##    #        #      #l     l##   ##  #######                    ##l   ##      #g         #
#  ##      ##       ##        #     # t      #              ##   ##  ####### #                  ##    ##                t#
#  ##      ##        #       ##     ##        r  f  #t     ##########t   ###                    ##                  b l  #
#r  #       ######## #       #      ## f             #                   ####        #                ##                t#
#  b#     #          #      ##      ##     #       #      ##             #####       ###              ## b    #          #
#   #    ##        #        # f     ##    g# g     #      ##    b        #####       ###             ######## ##  ########
#   #    #         ##      ##       #     ##       #      ##             ########                    ########  #  ########
#  a#   ##        ###      #      c #l     #       ##     ##         ##  ########                          ##f           #
#  c#   #       r ###      ##   l   #      #        # ###            ##  ########                          ##     ##     #
#   #  ##         ##        ####### #      # f ga                        ##    ##                          ##     ##  b  #
#   #  #          ##a          #### #####  #              #              ##    ####    ##             ###########  ### ###
#   # ##          ##        ##           ###  #      #     #        c    ##    ####    ##              ###########  ## ###
#   # #           ##   g    ##   l             ###         #             ##    #### t   r          # #           ##  l   #
#   # #           ##         ######               ###  ##          ##    ####  ####                # ###         ##      #
#   #  #          ################# ######### ##                 ###     ####  ####   ####         #  ##         ## b    #
# g #b #    f a l #########    ##    r ######      ###     g  ## #         ##  ####   ####     ###               ##    l #
#   #  #          ##   c       ##          ##  ### g  #   ##  #r # r       ##         ####     ###  ####   ########## ####
#   #                       r ##############   ###         ## ####        g##         ####           ##### ########## ####
#f ##   #         ###         #####       #######        #      ####       ##        l####   f     #    r     ##        ##
####                                 A          ##       ##   l     #      ##  l      ####         ## r   ##  ##        ##
##########################################################################################################################
