metadata:
  gen_time: 1.0963709354400635
  timestamp: '2025-04-11T22:26:43.715414'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|          |

      |   ####   |

      |  ######  |

      | ######## |

      | ######## |

      |  ######  |

      |   ####   |

      |          |

      '

---
####################################################
# ###    ######      #####    ##     ####      ##  #
#       #######     #######         ######         #
#      ########    #########       ########        #
#     #########   ###########     ##########       #
##   ##########  #############    ##########       #
##  ###########  #############     ########      ###
#   ###########   ###########                   ####
#   ###########                                 ####
#    #########                  ####    ##      ####
#                              ######  ####     ####
##                            #######  #####    ####
###         ##########       ########  #####    ####
###        ############     #########  #####    ####
###       #############    ##########  #####    ####
###      #############    ###########  ####     ####
##       ############    ############   ##      ####
#        ###########    #############           ####
#        ##########    ##############           ####
#   ##   #########     ##############    ####   ####
#  ####   #######      ##############   ######  ####
# #####                #############    ######  ####
######                 ############      #####   ###
#####    ####          ###########        ###      #
#       ######         ##########                  #
#       #######        #########               ### #
#       ########       ########               ######
#####   ########        ######    ######     #######
######  ########   ##    ####    ########    ##### #
######  ########  ####           ########     ###  #
######  #######   #####          ########          #
######   #####    #####          ########          #
######    ###     #####    ##    ########          #
######            ####    ####   ########          #
######             ##     ####   ########          #
######   ####             ####    ######           #
#####   ######            ####     ####            #
#       ######             ##                      #
#        #####                           ###########
#   ##    ####       ###                ############
#  ####    ##       #####               ############
# #####             ######       ##     ############
#######             ######      ####    ############
#######             ######      ####     ######### #
#######             ######       ##       #######  #
#######             #####                  #####   #
#######              ###                    ###    #
#######                         ######             #
#######                        ########            #
#######                   ##   ########   ##       #
#######   ##      ####   ####  ########  ####      #
####################################################
