metadata:
  gen_time: 10.445311307907104
  timestamp: '2025-04-18T22:50:58.245460'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#       ## ##c   ##r     t  ## ##  t    ## ##t        ##    ## ##                                                        #
##### #### #### #### ####  ### #  # # #### #### #### #### #### #### ####                                                 #
##  # #  # #  # #  # #  #    # #  #   #  # #  #g#  # #  # #  # #  # #  #                                             gg  #
##t   #  # #  #    # #r #    # #  #r  #t # #  # #  # #  # #  # #  #    #       f          f        r                   f #
####  ## # # ##  ### ##    # # # ##   ## # # ## # ## # ## ## # # ##t ###                                                 #
###                c                                                  ##       g                   l                     #
# #                 t                                                 #                                   g              #
# ## # # # # # # # ### # # # # # # # # # # # # # # ### ### # # # # # ##                                              t   #
# ## ### ### ### ##  # # # # ### ### ### ### ### ### # # ### ### ### ##                        t       l A     A         #
# #               r c              c           A       c              ##                         g                       #
#                                      t            c      r    g t  r                                                   #
###                           l                                       # ##################################################
#                                             t                       # ##################################################
# #          t          l t                          c                #                         l     f                  #
### tt                                             t                  ##t                                                #
##              c            a               c                         #                                                 #
###                                          r                 c      ##                                                 #
#### # ## # ## # ## # ## #### #### # # #### ## # # ## # ## #### #### ###                                                 #
#    #  # #  # #  # # c#    #    # # #    #t#  #g#  # #  #    #    # #  t       f                                        #
#  # #  #f#  # #  # #  # # r# #  #a#g# #  # #  # #  # #  # #  # #  # #                                                   #
#### #### #### #### #### #### #### ### #### #### #### #### #### #### ### l                                               #
#       #    #    #    #   r#    #   #    #    #    #    #    #    # #               g    l                              #
#  # #  # #  # #  # #  # #  # #  # # # #  # #  # #  # #  # #  # #  # #                                                f  #
#### #### #### #### #### #### #### ### #### #### #### ####r#### #### ###    f  r  g                                      #
###                     a      b                                      ##          l                l                     #
##                                                       c             #                                                 #
###   t     c r     r           r     c  c                            ## f                                               #
#                    t                      t          c              #                                                  #
# # c                                               r              r  # r              t                                 #
###    t       r           a                                          ##                    r                    r       #
#                             g                    t              t                   r             r                f   #
# #                                     t l                       l   ##        g                 l                      #
# ## ### ### ### ### ### ### ### ### ###  ## ### ### ### ### ### ### ##                                                  #
# #### ##  ### ### ### ### ### ### ### ### ### ### ### ### ### ### ####   l                          f                   #
# #       f                                                           #                 A                                #
###   c                    g                                g         ##                              g                  #
##### #### ## # #### #### #### # ## # # ## # ## # ## # ## #### #### # ##                 l                r  l           #
##    #l   #b #    #    #    # #  # # #  # #  # #  # #  #    #    # #  #                                  f     l    l   #
##  # #  # #  # #  # # c# #l # #  # # #  # #  # #  # #  # #  # #  # #  #            b      r          b                  #
##### #### #### #### #### #### ####t# #### #### #### #### #### #### ####       l                                         #
#       ##t##    ##         ## ##       ## ##         ##    ##g##                                                        #
#   #########  #### # # ### ## #        ## ## ####  # ## #  #########                                               r    #
#   ##  ###    #### # # ### ## # #  ##      # #### ## #  #    #####g  ##                                                 #
#          ###    g # # ### ## # ## ### ## #    ## ##  #          b#####    g                                            #
#   ## c########### g   ### ## # ## ### ## #####      ## #    #########    l              l     t                    b   #
# # ###################     ##A  ## ###  b ####### ## ## # #########                                                     #
# # ####################### t  # bg    ###     ### ##      ####                                                          #
# g ###########################################     f ####     #########                         A                    f  #
####    ################################################################                                                 #
#### ###    ########  ########     #############################gf    ##                g                                #
#### ### ###         #         #### b         g                 #####                                       r            #
#  # ### ### ####### # ####### #### # ########## #######################                               g                 #
#        ### ####### # ####### #### # ########## ################    ###                                     t           #
#  # ###                                   gba                a   ###                r l                                 #
## # ###  ##  ###### # ####### #### # ######## # ############## # ######                     b                t      b   #
## # ###  ##  ###### # ####### #### # ######## # ############## # ######              f                                  #
#g                                           g f              r         f               t                     g          #
#                              b               a                   b                           t                         #
#    b   g           l b                 g      f                      g               g                                 #
#  a     b    g                             b                          a                               g                 #
# ######################################################################                                        t        #
# ######################################################################                                          t      #
# ########################################################################     ##   ### ## #####          ##      # g   ##
# #######################################################################      ## #### ### #      #        #      #      #
#########################################################################   b  ## ####  ##a       ####            #      #
########################################################################   ##         t ##     #g           f     ##     #
#                         g                      f      b     t         #               ##  #  ######                    #
#        g       g                 f                    g                       #### t      #   tb   f ###    #########  #
#       A    b                                 r                g               b   g ##### # ####  l                    #
#       g                               g                               ####     r    ##### # #        ###     # #  ###  #
#                        fg      l    g                                       ####            # #### f      r  a f       #
#    # #       #   #   # ## # #  # # ######### # # ### ## ##############     at    b  ##   l  # #       r   ###########  #
#    # #       #   #   # ## # #  # # ######### # # ### ## ##############   t####    # ##      # # ##  #     ###########  #
#    # #       #   #   # ## # #  # # ######### # # ### ## ##############           t# ##  ##l # # ##  #     ##   b##     #
#    # #       #   #   # ## # #  # # ######### # # ### ## ##############            #         # # ##  #   # ## ## ## ##  #
#    f         #   #   # ## # #  # # #########A# # ### ## ############## # #   r    ####      # l     #   # ## ## ## ##  #
#              #   #   # ## # #  # # ######### # # ### ## ############# ## # #          f ##  #           #    ##    ##  #
#              #   #   # ## # #  # # ######### # # ### ## #############    # #   f####        #    r     ##      A       #
#    # #           #   # ## # #  # # ######### # # ### ## ################## #                #   ##          #########  #
#    # #       #         ## # #      ###    ##   # ### ## #########               #####   f   ##      #                r #
#    # #       #   #   #  # #                 ##   ### ## ######### ####### f     #####  #        ##  ##      ########   #
#    # #       #   #   # #    #      ###    ######   r ##     ##### ####### #     ##     #######   #     fgr  ########   #
#    # #       #   #   # ## # # ## # #################   #####              #     ## ##   f        # ####                #
#    # #       #   #   # ## # # ## # ################################### ## #g ## ## #    ######## # #     ###############
#    # #       #   #   # ## # # ## # ################################### ## #   # ## #    ######## #        A      l     #
#                                                               b    g  ### #     ##      ##  #          ####      b    t#
#                                     g           b  g                   ##b##          # ##  br                         #
#                                                           b                   l      #  ###        ######### #         #
#      b                                       g        a               ####################         b       # #         #
#                                                  g         g          ####################                   ## b    r #
#              r          l                  a                  f      b#     #               l  f###                   ##
#                                     gg    a       g          g     g  # #    #  ############         #      f##   ##   #
#                  a                                b                   ##      # ############         #     g ##        #
#    # #       #   #   # ## # # ## # ####################################        ###             ##### #     # ##   l   t#
#    # #       #   #   # ## # # ## # ###################################   r      ## ##              # #     # ##       ##
#              #   #   # ## # # ## # ################################### f  #     ## #                 #     #       #  ##
#    # #       #   #   # ## # # ## # ########################################        #      ###              #   l   #  ##
#    # #               # ## # # ## # ###################################        ######               bg            t #   #
#              #   #     ## # # ## # ########################################                ###### b    t           # ###
#    # #       #   #   #  # # # ## # ###################################          ####                   ###       # # ###
#    # ##      #   #   # #b   # ## # ########################################## l       ##########    #    at  #   # #   #
#    # ##      #   #   # ## # r    # ##########################################          b       #   ##  ##    #  ## #g  #
#    # ##              # ## # # ##   ###################################     ##   ##########         gl   #    #    t#   #
#       a      #   #     ## b # ## #    ####  #################            # ###  ##########                      l  ##r #
#    # ###     # # #   #    #   ## #####                                    ### # ##                # #           #      #
#    # ####      # #   # ## # #  # #########  ##                             ##  ### ##             # #####       #####  #
#    # #### #  #   #     ## # ###  #################   ##  ##############    ##   ## ## #     ###   #   r   a            #
#    # #### #  # #     #  # # #####   ########################  ########        b ## ## ###    t    #######   ######     #
#      #### #  # # # # # #r   #######    ##  ####     ######    f    ###   ####t     ##                               ## #
#    #    # #  # # # # # ## # g                                                l ###### # # ######### ### #########      #
#    # ###a g  # # #   # ## #####         ##   #######     #     #    ##        l###### # # ######### ### #########ll    #
#    # #### #    r g g   ## ##### #           ####      # #   ##      ##      g       #   #   #     #  ##  # r         ###
#    # #### # ## # #  ##    ##### #         ##            # # #      ###    a     #    #   #   #     # ## #    #         #
#        ##   ## # ##### #  ##### # # # # #f                #   ##  ###   ###### ######## ########    ####      #      ###
#  # # ##      g # ##### ##             # ####            #    ### ###    ###### ######## ########     ##    f   #       #
#  # # ####   ##   ##### ## #####      #  ##      ###   #####  ##      #               #f      #      l##         #      #
#    # ###### ####       ## #####  ###f         ####   #####  #    ##         ## #      #       #           ## #### #### #
# ##   ###### ##########  g #      ####   #  #       # ###   #### ######                 #       #   l###    # #### #### #
# ####        #############  ####  #### ##f gf###      ### ###### ######         ##    t  #       #              #    tl #
# ###########  ####################     ############  ##   #####  ######a #    t r      #####      #   ##  al     #   ####
##########################################################################################################################
