metadata:
  gen_time: 6.26596999168396
  timestamp: '2025-04-11T22:08:25.061363'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
######################################################################################################
######           ##              ####  #######  ####    ########  ##   ######    ####  #########  ####
#                     ##         ####  #######  ####    ########       ######          #########     #
#                     ##         ####  #######  ####                                   #########     #
#####    ########         ####   ####  #######  ####                                   #########  ####
#####    ########         ####         #######  ####  #########  ###########           #########  ####
#                         ####                  ####  #########  ###########  ##       #########  ####
#                         ####   ###            ####  #########  ###########  ##       #########  ####
#       ##  ####          ####   ###      ###   ####  #########  ###########           #########  ####
######  ##  ####  ###     ####   ###      ###         #########                        #########  ####
######  ##  ####  ###            ###                  #########                #####   #########     #
######  ##        ###            ###                  #########     ####       #####   #########     #
######                                      ###       #########     ####   ##  #####   #########     #
######                                      ###       #########     ####   ##  #####               ###
######                                ##              #########                #####               ###
#                                     ##                                       #####    #########    #
#       ##########   #########   ##   ##  #########                            #####    #########    #
#  ##   ##########   #########   ##   ##  #########    ##  ####     ####       #####    #########    #
#  ##                #########            #########    ##  ####     ####                #########   ##
#  ##                                     #########                 ####                            ##
#                                                                   ####                            ##
#        #####                 ##                        ########   ####      ###    ####      ###  ##
#        #####     ##          ##           ##########   ########             ###    ####  ##  ###  ##
####               ##              ##       ##########                        ###          ##  ###   #
####                               ##  ##                                     ###              ###   #
####                   ###             ##                       #####               ##         ###   #
####         ####      ###                  ############        #####               ##         ###   #
#     ####   ####      ###   ###            ############                            ##               #
#     ####             ###   ###            ############                ###         ##  ####         #
####  ####                          ##                                  ###             ####  ########
####                                ##                       ###  ####                  ####  ########
#                        ##                  ##          ##  ###  ####             ##         ########
#                   ##   ##     ##       ##  ##          ##               ##       ##                #
#      #####        ##          ##       ##  ##    ####  ##               ##                         #
#  ##  #####   ###  ##          ##  ###  ##        ####  ##                               ##         #
#  ##  #####   ###  ##  ##      ##  ###  ##              ##  ##                   #####   ##         #
#  ##  #####   ###  ##  ##      ##  ###                  ##  ##     #####         #####              #
#  ##          ###  ##  ##  ##      ###                  ##  ##     #####                       ##   #
#              ###      ##  ##                           ##                  ##          ####   ##   #
#              ###      ##                               ##                  ##  #####   ####        #
#  #####       ###      ##          ##       ####              ###  ######   ##  #####   ####        #
#  #####                            ##  ##   ####  ####        ###  ######   ##  #####   ####        #
#         ##                            ##         ####   ##   ###               #####   ####        #
#         ##                                       ####   ##                             ####   ######
#                     ##                    ####   ####   ##           ##                ####   ######
#                ##   ##          ###       ####                 ##    ##      ##                    #
###     ##  ###  ##               ###  ##                        ##            ##   ##               #
###     ##  ###               ##  ###  ##            ###                       ##   ##           #####
###     ##                    ##            ######   ###    ##                 ##   ##  ##       #####
###               ###                       ######          ##         #####   ##       ##       #####
#                 ###                       ######                     #####            ##       #####
#    #####   ##   ###   ##        ##        ######  #####       ##     #####                     #####
#    #####   ##   ###   ##        ##  ##    ######  #####       ##               ####            #####
#    #####        ###       ####      ##    ######  #####       ##               ####    ###         #
###  #####        ###       ####            ######  #####  ###         ##                ###         #
###                                         ######  #####  ###         ##                ###         #
#                      ##              ##                  ###         ##           ###  ###         #
#          ##          ##          ##  ##                         ##   ##      ##   ###  ###       ###
##         ##   ###                ##  ##                         ##   ##  ##  ##   ###            ###
##  #####       ###           ###  ##                     ######  ##   ##  ##  ##   ###            ###
##  #####       ###           ###  ##          ##  #####  ######  ##       ##       ###       ##   ###
#                             ###      ####    ##  #####  ######  ##                ###       ##     #
#                        ###  ###      ####    ##                 ##                          ##     #
# #########              ###  ###      ####                       ##    ##                    ##  ####
# #########              ###  ###      ####           ##########  ##    ##         ######     ##  ####
# #########              ###  ###      ####       ##  ##########        ##         ######     ##  ####
#               ##            ###      ####       ##  ##########        ##   ##    ######     ##  ####
#               ##  ##        ###  ##  ####  ###      ##########  ###   ##   ##    ######     ##  ####
#    #########  ##  ##  ###   ###  ##  ####  ###      ##########  ###        ##    ######            #
#    #########  ##  ##  ###        ##        ###      ##########  ###        ##                      #
#    #########  ##      ###        ##                 ##########             ##                 ######
#    #########  ##      ###  ##    ##                                        ##        ###  ##  ######
#    #########  ##           ##         ####   ####               ##  #####  ##        ###  ##  ######
#    #########  ##           ##         ####   ####      ##       ##  #####  ##        ###  ##       #
#    #########  ##                ###                    ##           #####            ###           #
#    #########  ##                ###                                                            #####
#               ##          ###         #####     ##            ##               ##              #####
##                          ###         #####     ##   ######   ##               ##              #####
##    ######         ###            ##  #####          ######                    ##  ###             #
##    ######   ##    ###            ##  #####                            ######  ##  ###  ##         #
##             ##    ###  #######   ##           ####                    ######      ###  ##   ####  #
##             ##    ###  #######                ####              ####  ######      ###       ####  #
##     ###     ##    ###                                           ####              ###             #
#      ###                                              ###  ##                      ###             #
#      ###                               #####          ###  ##                      ###    ######   #
#####       ##            ##             #####      ##       ##         ###########  ###    ######   #
#####       ##            ##             #####  ##  ##       ##  ##     ###########  ###             #
#####  ##   ##    ##      ##             #####  ##           ##  ##     ###########                  #
#####  ##   ##    ##      ##         ##  #####  ##           ##  ##                                  #
#####       ##    ##      ##         ##  #####  ##           ##  ##                    ######        #
#####       ##    ##      ##         ##  #####  ##   ##          ##     ##         ##  ######  ###   #
#####       ##    ##          #####  ##  #####  ##   ##          ##     ##         ##          ###   #
#####   ##  ##    ##          #####  ##  #####  ##   ##          ##     ##   ##    ##                #
#####   ##                    #####  ##  #####  ##               ##          ##                      #
#       ##             ##     #####             ##           ##  ##                         ####     #
#                      ##     #####             ##           ##                             ####  ####
#            #######   ##     #####      ##     ##   ####             #######     #####     ####  ####
###          #######   ##     #####      ##     ##   ####        ##   #######     #####     ####  ####
###  ######  #######          #####             ##               ##   #######     #####     ####  ####
###  ######                   #####                         ###  ##   #######     #####           ####
###  ######              ##   #####       ##            ##  ###  ##   #######     #####           ####
######################################################################################################
