metadata:
  gen_time: 7.993751049041748
  timestamp: '2025-04-18T22:51:49.967932'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#                        ##    ##    #               ####  #t   ##  f          ####  l                                l  #
#                         f    ## # ## ##  ####### ####f#  #   ####         ###     #    ##     ##########               #
###              g                # #            # #  # #  #  ##  ##               ###    #######        #################
###      c                 bt #   ###            ###  # #  # ##    ###    r # ##r ####   ###             b               #
##  b g       ####            #######  #  ########## ## # ## ##   g ###           ###    ###      r                      #
##             ##     #t                                      ##    ###     ####   ###   b###  r       #########         #
##              r     ## t     # #### # ## #########f########  ##   ##       ##             #       f  ##      ##        #
#                     #####    #    # #  # #  ###  # #  ###    ##   ###     ####   ###        f    ######       ######## #
#    ##     ##      b    ##    # #  # #  # #  # #  # #  # # tr##     f##    #### a l#        #######                   ###
#     ##    ##    f       ##   ###  # #  ###       # #  # ### ##       #     ## g     #  t#              t         b    ##
#      ##g  ##                 # #### #####   # #### #  # ##   ## b      #          ##    #  f     l             c       #
#t     ##   ## g                 ##   ##          ## #    ###   ##t      ##         ###l ##     t                        #
#     ##    ##                 # #### ####  ######## #  ###     ##       ##           ####  r                            #
#     ##     #               #####  # #  #    ###    #  ###      ## # #  #  gl         ##  b           f l           #####
#      ##           f         ####  # #b                # #       # # ##              #### ###########################   #
# #     ###        l           # #  ###    #### #  ### f# ###  l  # # ##              ####             b                 #
# ###  b  ##      ## g   ##t   # # #######      #  # #### ##    l## # #  #             ##              t                 #
#  ###            ##     ##             ## #### #f #      ###   ##             g      ####                         #######
#   ###           ##     #     ### #######   A# #  # #### #     ##       ##         ###  ##           #####l    f ##     #
#                ## b   ##     ###  ###    #  # #  # #  # #    ##        #       t ###    ## c ########  g##      #      #
#                ##     ##       #  # #  # #### #  # #  # #   ##       #  l  ##    ####   ###  ##          #   r###      #
#                       ##     # #  # #  # ##   #  # #  # # b ##      ##    ####    ###    r#####          #    ###     r#
#                        #     ###  # #  # #### # g# #  # #    ##   ###     ####  t###    #r               #    #g       #
# ##                           # #### ####    #g#### #  # #    ##   ##       ##         gl              g ##    #       ##
###                          #   ##        #  #      #  # #   ##    ###     ####   ###b   #               #     #      ###
##t          ##    ##        ### ## ### ## #  # #### #  # #  ##     ###           ###    ##          ##   #    ##      # #
##           ##    ##    t    ####  ###  # #  # #  #    # #  ##     ##      ####  ####   ##          ##   ###  #     ### #
#         t   #    ##          ###  # #  # # f# #    #### ##  ##  #          ##    ###    #               ###  #    l### #
#             ##   ##          # #  # #  # # t###  # ##        ## #       g ####  ###    ##                 #  ##    #   #
#              ##  ##          # #### #### ######### #### ##    #              ####            t            #   ##   #   #
##        ## #   ##    # ##        #    ## f           ##    #### #  ### ####################  #######t       ##### #  # #
## ### ##### ######r## # #####                                         # #                 #    ######        #####      #
#   ##                       ## b                   #        ########### # ##############      t #####        #####      #
### ##### # #### # ##### ##### #r                  ##        ###########   #############  # g     ###     f    ###       #
#       # #    ###    ## g                     g    a            c     r                    ##           ##      b    ## #
######### ###### ####c#########               ##   b       ####### ##### ## ###################         ####         ### #
#  ##            l           ##ff  #   #       #  b        #                               ####   ##    ####    ##   ### #
## ## ### ###f####### ###### ##   ##   ##         ##         ########### # ##########l## ######  ####    ##    ####  ### #
#       ###   ##      ##             f            #                               t   ##   ####  #####  f     #####  ### #
######### ###  # ####### ######                              #### ###### # ######## ##########   ######     g######   ## #
#            r         f    ##  ##           ##  t     f        l      l t       f         ##    ####### t  #######    # #
# ####### ###  #####g###### ##   #   #        #  c##    ##   ##################     ########     #######    #######  f   #
#      A# #   ##   ###               ##         t  #    #                 l r                     #####      #####       #
######### ###### ### #### # ###     t                         ############# ### A  ########            r    r    b       #
#   ##                    #                                ##                 b    tb           b        ##       g      #
### ## ###### #########r# # # #                             ############### ### ########### g           b##              #
#           ###         # # # #            #  a a            ############## ### ###########              ft          b   #
### ######### ####### #g# #   #            ##   f                               f                 ##### g    #####       #
#                     # # ### #                              ###############################     #######    #######   g  #
# ## ## ## ##c# ### # # # ### #r         b              ##   ################################    #######    #######    # #
# ## ## ## ## #     # #   #c  #      #        t          #                                 ###   ######      ######   ## #
#c            #f# # # ###   # #t    ##                       ### ########## ## # ##############  #####        #####  ### #
#### ######## # # # # ### #t#l#         ##                    cc          g  r             ####  ####    ##    ####  ### #
#    ##     f     #f# r   #   #          #        ##  f#  l  ##################################  t##    ####t   ##   ### #
####### ### # ### # # # # # #      #              #   b## l   #################################     r   ####     f  f### #
#           #       # #t# # # # b  ##                       #           l        r      r   ##        b  ##           ## #
##### # # # # # # ### #r# #f# #           #        t        ############# ######### #######       ###       r  ###       #
###   # # # # # # ### # # ##  #          ##                  ############ ######### #######      #####        #####      #
### # # #   #   # #     #  # l                ##    t      A   ##                      b   #    ######        #####      #
#   # # # ### ### # #f###c###A#   #f       b  #    #r        # ## ################# ###### ##  #######        ##### #  # #
# r  ###  ### ###  ####  #                                     ##  ##   ##   ######   ####  c  #   t#    g  ####### #### #
###  ###  #    r   #  c       r                             t  ##g            ####    #####    #  g #t      ####### #### #
###  #            l      #   ##  ##     ##        ##     ##           b       ##       #### t  #    #c    c ###        t #
#       c #  g     #   ###   ## ####    ##        ##    ####   b   f##  ##             ####    # l  #       ###g         #
#    #  ###      ###   ### f    ####    t        gl     ####  ##  ##########    b       ###    #b   #       ##   c       #
#  ###  ###  ##  ###   #         ##              l       ##  #################  ##      ### c  ##   #       ## g       c #
#  ###  #    ##t #               ##      ##  ##  ##r     ##  #######  ##  ####  ##     r ###t  l## ###########   c       #
#  #   r          g    #    ## l        ############         g ####        ##              ## c     ##########    A  ### #
#       #        #     ###  ##       g   ##########              ##             t        b  ##f      ########### ## #### #
#  #  ###  ##    ###   ###       t##    b  #    #     A ##     g   A ##          ##  ##      ## #     ########## ## ###  #
####  ###  ##    ###     #        ##                    ##   ##      ##   ##     ##  ##         ##        g          c c #
####    #          #                        l                ####         ####           l      c# ######## #### ## #  f #
#  #                     #            ##        f  a##       ####        #####                c                     ## # #
#       #    ##    #     ###        #####b       r #####     ##          ####        ##  g #     # ########            # #
#  #    ###  ##    ###   ###  #     #####   b      #####             ##   ##       ######  ## c ##  t c   ##     c c     #
#  ###  ###        ###     #  #     #####          #####         ##  ##   ##     ########## ##  #          #             #
#  ###  #            #             f#####          #####g    #   ##            ############  ## #g         #        # ####
#  # a                     #          ##            ##       ##     g          ######  ##     # #          # c     ##    #
#       #    f       #    t###  b  t         g     l         ##          ##     ####          # #          #       #    c#
#  #    ###  ##      ###   ###  l ##                    ##   #     ##    ##       ##         ## ##        ## ##    #     #
#  ###  ###  ##  ##  ###     #    ##r      #    #       ##         ###               f      ##   #     t ###  ##   #   ###
#  ###   t#   t  ##    #                 ##########               ####                     ##    # c     ###   ###########
#  #              g          #          ############   f   b    #######    r  ##      ##   #     #       ### g   c #######
#         #            #     ##  ##      ##  ##  ##      ##     #########     ####  #####    c   #c    f ###c l t   ######
#  #      ###          ###   ##  ##                   t  ##      ##########  #####  #####  #################         ##  #
#  ###    ###  ##     f###      ####                    #### #     ##  ##########    ##          #################       #
#  ###   f#    ##        #      ####    ##        ##    #### ##          ######                   ########################
#  #   tA          ##            ##     ##        ##     ##  ##        b   ##           g  ###    #####                  #
#         #        ##    #                       t     b     #      ##            ##  ##  #l ##c c####     ############# #
#  #      ###           g###            g r             a   t#    ######   b  g #### ######   #c f ###    ## c   #########
#   ## ## ######            #  ######   #   #   # ag         # ## #     f  # #######      # #           #  #           # #
#   c   # ######            #        f  #a  #   #####a     a # ## #        # ####### ###### ### ##### # #  # # ##### ### #
#       # #    b # #####   ## #         #   #   #t  ######   # ###         # ####### ######       #   #l     #   #       #
####    b     #     ####   ####        ##  ##          a  # ## ####  f  r  #         ###### ##   ######  ### #############
#     #                ##            b #   # a  ##        f ## ####        # ### ### ###### #     l      gg              #
#     ##   #           ###            ## b #     #        g  # ### l        ###     t       #    ####### ##### ## #### # #
#     ##  ##             t b     g    #    #     ##ac    b   # ##          ####l                  #g               # #r  #
#         #####      #      bf        #    #      #      ##### ##g#        ###  b        l  #     # # ## ##### #   # # ###
#   #        ##                       #    # a    ########   # ## #    b   ##f#             f     # #          #         #
#            ###      #  t            #    #               l #                #             #     # # ## ##### #   ###   #
#              t  ##  #               #    ##  b  #          # #  #        ## #                   # #          #     #   #
#        f            ###f   b       ##     #        r########   ## # #  #                  ##    # #### ##### #   # ### #
# # #                ###      #a     #      #####     #a   #    ### # #    # ### ####  ## #         # #      # #   #     #
# ########   ## ######    b # #      #t        g#   #      # # ###    # ## #    ######   ## ##   ## # ##   ### #   ##### #
#  #t   ##    #  #######    #  #############    #          # # ## # # # ## #      ######### #       #      #   #       # #
#  #     #    #  #          #                   # #  #########        # ##   # ### #### ### ##    #####    # # ##   #### #
#          ## #### r     #             #   a      #          # #        ## #  g     ##                                g  #
#    ###  g##   b c   g  #            ##f         #   #      # #      # ##  # b     ##      #    ######  ### # ##    # ###
#     ### ###        #         a      #       ### #######    # # f    # ##  #       ##      #         #r   # #     #   # #
#      c             #g   #         a #     #   b       ###  #        # ##  #       ### ### ##    ### #    # # ##  ### # #
# f b      #         #    #f   ##           #             ####        # ##       b  ####t    b   f#        #             #
#             #    # #    #   # ######   f  #               ##t     f  ###      ## ######## ###  ## ###    # # #t ## ##  #
#                  l    ####                #     ######    ##        #### ####  r######### #c#   #   #      #       # # #
#                   ##    ##      # b   ######### #  ar######        r#### ################ # # # ###f#    # # ##  # # # #
#        #          g#     #      #                      #     #      #### ##############    A# # #   #    # #     #f#  l#
#    f   ##  c       #   r        #    ##                #   # #      ####   ##########   # # # ##### #  ##### ###   # #c#
###                 r                       ###          #   # #      ###  ## ######## ## # #bc  b# # # c    # # #       #
###     t                      ## ####    #   ####### ######## #      ##                    ##### # # ###  ### # # ##### #
#             #             ## #          #                 ## #g      #                    #                          # #
# c       ###   ### #     # ## # t l      #            #    ###       ##                    #   l    g            g  t #f#
##########################################################################################################################
