metadata:
  gen_time: 2.5392820835113525
  timestamp: '2025-04-18T22:50:11.262122'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#     l                 f #  #######rb #########      #########   #######                                 ##b  ##  #     #
#                           g#######   #########   r  #########   #######     #                    ##l ### ## ##  ##  ## #
# g                   g   #  ####### g #########      #########   #######            A          t   ##   #       ###t##  #
#                      r  #  #######      crc                     #######        #  #                # #  ##   #   ###   #
#    f             g      # r#######         f             f      #######                            #  ###       # ##   #
#           ga            #  #######    c                 tl f    #######        c            a   ##  # ##t       # #  ###
# ########## ## #######g###  #######                             b####### b                b        #  ##             ## #
# ########## ## ####### ###  #######           ##    ##           #######              b    #  f A# ####  b  #           #
# ##   ##       g            #######          f##    ## f     r f #######                         # ####  l ###    #### ##
# ##   ##        a lr     r  #######  ###      ##    ##f     ###  #######                          ##  #    #            #
# ##                         #######  ### b                  ###  #######f         #          b   ##       l# #     b  ###
# ##   ##                    #######   a                          #######        t        #       #    #  t ###    #    ##
# ##   ##                    ####### f    g################    b  #######  #                 #         ## b  #   l##     #
########### ## ## ### ### #  #######   g   ################       #######             #                 ##   #   ##      #
########### ## ## ### ### #  #######       ################    r  #######                         ######### ### ##########
# t##l          g            #######       ################       ####### l                                             b#
#                            #######  r          f  r    c r      #######                                             r  #
####### ########## ## #####  #######          g             fa    #######         b               ## #### ####### #### ###
####### ########## ## #####        f rc########################  f               c                        f              #
###       ##  ##          #            ########################   f               #                          #           #
###       ##  ##      b  g###########  ########################  ##########                               #######  f     #
#         ##  #### #### #############  ########################  ##########                         ### ###     ### ###  #
###       ##  #### #### #############                   f  g     ##########   #      #             ##       t       l ## #
###     l ##  ##     ##  ############  g      r        g         ##########       #          f    ##                   ###
#             ##     ##  ##                        l   f               g                #         #                     ##
###     l ##  ##r    ##  ##            #########      ######### f b                                                      #
###  r    ## t##    g##  ##  ###    f  #########    b #########       ###            c                   # ## ####       #
### ##### ######## ######## g###rf     #########      #########       ### r            #          ########  g    ##### ###
### ##### ######## ########bf###                    r c  c       f    ###      #      t           ####     f         # ###
# g   ##r       ##    ##  #g ###g         g        c      c       fg  ###                t           ##     # #     ##   #
#     ##        ##    ##           #####                      #####                   #               ##   ## ##   ##    #
#     ##        ##    ## g#        #####   f      f           #####                                    ##  #   #  ##     #
#     ##        ##    ##  ####### r#####       ###  ###   A   #####  ######              f             ##  #   #  ##l    #
#     ##        ##    ##  #######  #####  ###g ###  ###  ###  #####  ######           #f              ##   ## ##g l##    #
## ########################       r#####  ###  ###  ###  ### a#####                                  ##     ###     ##t  #
##t########################        #####  ###  ###  ###  ###  ##### g          #                  ####               #####
#          ##    ##  ##  ###       #####  ###  ###  ###  ###  #####      f#        g   #          ########       #########
#     g    ##    ##  ##  ###              ### b###  ###  ###          b   #                     t        #########       #
## ############# ## ### ###      f   r    ###  ###  ###  ###        f   c              f            l           t        #
## ############# ## ### ###           A   ###  r      r  ###          b                 #  f      #                     ##
#      ##     ##           ######         ### g          ###         ######       #  r            ##                   ###
#      ##     ##      l    ######       r                            ######   #      #             ##A                ## #
#      ##     ##           ######  ##   c                    r   ##  ######                         ### ###     ### ###  #
#      ## b   ##           ######  ##   ##   b              ##   ##  ######               c             f #######        #
# ## #### ############# #########  ##   ##                  ## c ##  ######       #                          #         l #
# ## #### ############# #########  ##   ##                  ##   ##  ######      fl     c                                #
# ##              ##                    ##               f  ##             b               t      ## #### ####### #### ###
# ##         ##   ##                    ##   ###      ### r ##  g r  c   b t                  b                      b   #
# ##         ##   ##    r       f      g##   ### r    ### c ##               t         f                   b     t       #
# ##  lt     ##   ##       ###      t   ##   ###l   g ###   ##          ###                       ######### ### ##########
########## ###################   ####   ##   ###      ###   ##   ####   ###           #                 ##   #   ##      #
########## ###################r  ####   ##  f###      ###   ##   ####   ####  a              #         ##    #    ##     #
#     ## l    ##  t    ##               ##   ###      ###   ## g                          #       #    #    ###    #     #
#     ##      ##       ##           b    A   ###  f   ###                          #              ##        #            #
#             ##       ##   #######           r  g                 #######                         ##  #    # #    #     #
#     ##                    #######   r                            #######        c        f        ####    ###l  l## # ##
#     ##l     ##       ## l #######    ###  ##    ##    ##  ###    #######    l             #    f# ####     #     ##    #
#     ##      ##       ##   #######   r###  ##    ##    ##  ###    #######                         ##             ##t  # #
#     ##      ##       ##   #######    ### r##          ##  ###    #######      t                 ##  # #  b        #   ##
#    r  l     ##       ##r  #######    ###  ##          ## r###    #######   c                     l ## # #      ## # f  #
#      #           b                   ###  ##         b## f###    c             #  #           c    ###t          ##    #
#     ##      ##       ##                                                                       b   ## ### ## ## ###  #  #
#     ##      ##       ##               f                      c              #          l         ##  ### ##  #  ##  ## #
#     ##      ##       ##  f#################   b    rr  #################               g                ##             #
#     ##  g  r##            #################  ########  #################   r  a a  ##  fr     t##    ##  r     a  #    #
#    l       t         ##   #################  ########  ################# ###a##### ## ##  # ########  # ### ####  # ####
#     ##      ## r l   ##                      ########  Ar             r  ### ##### ## ## ## ########    ### ####l   ####
#     ##      ##       ##                  g                                   ##       ## ##       ## #  ##    ##r      #
#     ##      ##### #######              r                  r               ##### ##### ## ## ## ## ## #  ##  #### #  ####
#     ##     g##### #######     g            ###      ###      b     g      ##### ##### ## ## ## ##    ## ##f #### #  ####
#     ##### ####    l      ################  ###   c  ###  ################    ##    ## ## ##  f ##   f## ##       b  ## #
#     ##### ####           ################c         f     ################### ## ######## ## ## ## #  ##l### # ##### ## #
#     ##    l ## f         ################       ##      c################### ## ######## ## ## ## #  ## ### # ##### ## #
# fa  ##      ###### ## ###################      r##  t    ################     a ## ##       ## ## ##    ##       ##    #
#g    ##      ###### ## ###################       ##       ################### ##### ## ## ## ## ##### #####  #f##### ####
#     ##   r  ##    g      ################      c##r      ################### ##### ## ## ## ## ##### #####    #####  ###
#     ##      ##     r b   ################                ################  a ##    ## ## ##    ##ct  ##t   ## ##     # #
### ####### ####          r################r               ################ ##f##### ######## ##a##### ##############    #
### ####### ############## ################                ################ ## ##### ######## ## ##### ############## #  #
#             ############ ################                ################ ##  br##      r l ##             ## ##       #
#             ##      ##   ################ g              ################ ## #####  ##### ####### ##### ## ## ## ## # ##
#             ##      ##   r   f      g         ######    f          f      ## #####        ####### ##### ## ## ## ## # ##
#             ##   lg ##             f         g######                         ##              rr   ## ## ##    ## ## r  #
#             ##      ##    ###                 ######               f ### ###### ########### ## ##### ## ##### ##t## ####
## ## ############# ####    ###   ###           ######           ###   ### ###### ########### ## ##### ## ##### ## ## ####
## ## ############# ####        b ###g ####     ######     ####  ###                                   ## ## ##          #
#   r      ##         ##          ###  ####   b            ####  ###       ### #####   #    #  #### ######## ## ## ## ## #
#          ##         ##g         ###  ####                ####  ###       ### #######  ###         ######## ## ## ## ## #
#          ##  g         f    g   ###  ####  ############  ####  ###        r     ## ## ##       ##    r     ## ## ##    #
#                     ##     r  r g          ############                  ### ##### ## ## ##a##f## ##### ######## ## ####
#          ##         ##         f   l    fc ############                  ### ##### ## ## ## ## ## ##### ######## ## ####
#          ##               ###############  ############ a###############                             A  ##       ##    #
#          ##   t     ##    ###############  ############  ###############        ##       ##  a    ##    ##f      ##  t #
#          ##         ##    ###############  ############  ############### ### ##### ##t##t## ## ## ##### ######## ## ####
#          ##        g      ###############  ############  ############### ### ##### ## ## ## ## ## ##### ######## ## ####
#          ## r       ##    ###############  ############r ###############                  r ## ##     t    ## ## ##    #
#         g##         ##         r     r  f                        r       ### ##    ######## ##### ######## ## ## ##### #
# ## ## ####### ### #######    b                r           r       f      ##  ##### ######## ##### ######## ## ## ##### #
# ## ## ####### ### ###############  #######       g    b #######  ########r       t       a  ##a##    ## ## ##    ta    #
#         ##        r      ########  #######           r  #######  ##############b########### ## ##### ## ##### ## #######
#         ##         A                      r  ###  ###           r      f ###### ########### ## ##### ## ##### ## #######
#         ##                     f             ###  ###                        ##    #   f  a       ## ## ##             #
#         ##    g   g      #########       g   ### f###    b      ######### ## #####   ##  ######## ##### ## #   #    ####
#                          #########           ###  ###           ######### ## #####  ### ######### ##### ##t#  ## ## ####
#       l ##               #########                g         g   ######### ##                                           #
#         ##gl             #########   #####        b     #####  f############ ##    ######## ## #####  ## ########## ## #
#         ####### ### ## ###########   ##### c r       f  #####   ############ ##       ##### ## #####   #  ######### ## #
#         ####### ### ##f###########   #####   ########   #####   #########    ## t  ## ## ##    ##    #  f  ## ##    ## #
#         ##               ######### g #####   ######## c #####   ######### ##                                          ##
#       r ##               #########   #####   ########   #####   ######### ##  ###  ##              #  #### ## ##### # ##
# ### ######      b r      ######### r ##### r           f#####   #########       ##          #  #        ##       ##   c#
# ### ######      b     r  ######### g #####   r          #####   ######### ## #   #### #  #  #           #####t##### #  #
#     ##            a      #########   #####     ####     #####   ######### ## ##  #### #  #  ####   #     #### ##### ## #
#   A ##  ##               #########   #####     ####   f #####   ######### ## ##    ## #  #     ##          r        ## #
#     ##  ##               #########   #####     ####     #####   ######### ##### #####f#  ## #  ##  # #  ## ##### #######
# ### ########## ## ################   #####     ####     #####   ######### ##### ##### #  ## ##       ##    ##### #######
# ### ########## ## ################       g     ####             #########f   ## t     ##  #             ##    ##       #
#  ##   ##r  l     l     ###########     f       ####    r       g############ ##### ## ##    ####  #  ## ######## ## ####
#  ##   ##               ###########           f  f    c          ############ ##### ## ## #  ##### #    r######## ## ####
#  ##  g##               ###########             t      b         #########          ##          ##  r #         r ##    #
##########################################################################################################################
