metadata:
  gen_time: 6.466976165771484
  timestamp: '2025-04-18T22:48:36.194806'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
### # #  # ####### #a  # # # ###### ### #####  ####        ####        ####  ####       ##  ####          ####  ##   r   #
###     #   ######  # #    f #####   #   ###  f ###         ##  l      ### t  ###   a   ##  ####  ######  ####  ##       #
### #        #####     # # # ####         #     l# #r                 # #   l  # ###    ##  ####  ######  ####c ##    ####
# # #       # ###            ###           l     t  #            r   ##          ###    ##  ####  ######  ####  ##    ####
#       #      #f        #   ##                     ##    t     l   ###         #                 ######                 #
#   #           #        #                #      #  ###            #### #            l            ######                 #
#                        #                ##    ### ####l         ####  ##      ###############   ######   ###############
#   #                    #                ###  ####  ####        ####   ###  # ################          a ###############
#   #       #            #                #  ## ###   ####    t ####    ## ##  ################a           ###############
#   #   #                #   #            # ###        #### t  ####     #  ##  ##   r           g##    ##                #
#           #                ##              ## #       ###  b####         ##   #                ##    ##                #
#   #   #   #                ##                 ##    #      ####          #    f  t             ##    ##    A       gt  #
#                            ##              #  ##    #      ###            #   ###      g       ##    ##      t       ###
#                            ##             #   ###    #     ##            #     ##    tf   g    ## f  ##              ###
#                        b   l#            #l         #  b   #             l#l  ###  #####         f  t         #####  ###
#           #                 #             #                              # #   ##  #####                      #####  ###
#       #   #                ##              #        ##     #             #    ###    a         ##    ##           g  ###
#       g                    ##             ##        ###                  #     ##   g          ##    ##              ###
#       #   #                ##              ##       ###    #             ##   # a            r ##    ##     l          #
#           #                ##               #        ###                 #   ##                ##  a ##               a#
#   #   #                #   #               # #        ##   #                 ##                ##    ##    t     f     #
#   #       #            #    f             ##           #   #             ##  # ##############         r  ########## ####
#   #   #                #                  ###              #             ##    ##############            ########   ####
#       #                #                 ### #             #              #    ##############   ######   ######## ######
#           #            #                 ##   #        #                   #  #              rg ######              t  #
#                        #   #             # #          ##   #                 #    a             ######  f g            #
#   #       #                #               ##        ###                      ####   f##  ####  ######  ####  #    l####
#   #                        #               ###      ####   #             #     ###    ##  ####  ######  ####  #     ####
#       #   #                #               t####     ###                 #   t        ##  ####  ######  ####  #        #
#   #       #            #   #                 ###      ##   #             g           r##  ####          #### f#      l #
#   #       #                              r #          #                   #    # ####         ##  ##  ##         #### ##
#   #   #   #                              ###          #                   ## ###  # #    ####     c      ####A   # #  ##
#       #   #                              ###                              ## ###### ##  #  ##            ## #   ## # ###
#       #   #                                # f  t    ##                 A #    # #  ##    t ##  #    #  ##      ##    ##
#   #   #   #                                #    #    ##                   #r              f ## ##    ## ## l    a      #
#   #       #                               ##    #    ##                   ##  l        #       ##             #l  c    #
#   #       #                               ##    #    ##                   ##    #  # # #       #      #       # # #  # #
#   #   #                                   ##    #    ##                   ##      ## # ##  #af            #  #  #    f #
#   #   #                                   ##    #    ##                   ##   # ##  ###   #####  ##  #####          ###
#   #   #   #                               #     #    #                     #                # ##      ## #            ##
#   #   #   #                              ######     ####   #             ###     ####   l#    l##    ##    t      ###  #
#   #   #                                  ########   ####   #             ###     ## ##   # r                    #  ##  #
#   #   #                                  #            #                          #       ##  ###    #####   #       # l#
#   #   #   #                              #l    g      ##                        r      t ##    #   A ##    ##          #
#   #   #   #                              #            ##                 l   #           #                  #          #
#   #   #   #    A                         #           g##                     #    #      ##     ##  ###  r ##      #   #
#   #   #   #            t   f             #            ##                       # ##      ##      ###       ##      ## ##
#   #   #                                  #            #                        # ## ## # #  #     ##     #    # ## ## ##
#   #   #                                  ########   ####   #             ###   #c #### # ## ## a        ## ## # ####  ##
#   #   #   #                              ########   ####   #             ###   ## ## ###                      ### ######
#   #   #   #                               #     #    #                     #             ### # t  ##   a#  ##        # #
#   #   #                                   ##    #    ##                   ##       ## ## ## b     ##  ##   ## ## ##    #
#   #   #                                   ##    #    ##                   ##          ##  #     #         ##  ##       #
#   #       #                               ##    #    ##                   ##    t  l           ##         #    #       #
#   #       #                               ##  r #    ##                   ##  t        #  #    ##     #   ##  ##       #
#   #   #   #                                #    #    ##                   #    #         l               ##    r    f ##
#       #   #                                #  r      ##f                  #r   #         #  #  ##  # ## l## #  f      ##
#       #   #                              ###        l##                   ## #### ## ##  #    ##      ##    #  ## ## ###
#   #   #   #                              ###l        ##g                  ## ## # #  ###      #        #      ###  ### #
#   #   #   #                                #         ##                   #       #f## #    #     ##     ##   # #      #
#   #   a                        A         rg                              ### #    ##      #      #####     #### # ######
#                                           #######   ####   #             #      #### #  #        #####t         # ######
#                                               b        #                 # # #  ##   # ##  l   f ####  t    ###     ####
#                                           ######    ####   #             # #   ##         #      ####    ## ### #   ####
#   #   #   #            #                  ######                               ## t  # ###  # #  ####  ###      ##   ###
#           #                              f   g      # ##   #             ### # ##      ##     ############ # #####   ###
#                        b                   ######   # ##   #                 #     # ##      ############  # ######   ##
#       f                                               #    #             # #    #  # ##   g  ##        ##    ######  ###
#       #   #            #                   ######   # #    #             # #   #     #       ##  t     ##            ###
#   #   #                #                   g   ##   # #    #             # # ##              ##        ##        #gt ###
#   #                                      # ###  #   # #    #               # ##  #   ##      ## g                   ####
#                                          # #### #   ###    #             # # #     # #                 #        ########
#                                            ## #      g                   # # #          # ######   #####   #### ########
#                        #                 #### ##    #      #             #      #  ## ### #####  #######   ###  ########
#   #   #   #            #                 c    ##    #l#    #             ###          #   ##### #    ###  ##   ###  ## #
#   #   #   #            #                      ##    # #    #             ###              ####            ##  f  r  #  #
#                        #                 #### ##    # ##   #             #                                             #
#                   A                        ## ##       g                 # # ## ### g  r ###       f      ###      ### #
#                                          # ## ###   ##### ## ###### #### #g#                               ###  g r### #
#   #                                      # ##       #l#   ##     ##        # ## ###l   a###                ###  tl ### #
#   #   #                #                 #     #### # #b  ################ # ## ##     ####                ####     ## #
#       #   #            #                 ########## #   ################## # #####     ####     t          ####   l ####
## b   l    f            b                 bc    b      #    ##    A c   # # # #####    ###### r    t     af######    ####
###                           ########### # ## ######## ######### # ## # #     ####  b  ######      ##      ######     ###
#  #       ##     ## b       ##    #  #   #  t     ##f# ######### # ## # ##### ####    #######b     ##l     #######    ###
## ######################## ##    ## #### # ###### ##             # ####       ####    ############################    ###
## t      f     b         b##    ##  c #  # ###### ######## ##### # #### # # # ####   ###   ##################   ###   ###
##                        ##    ##     ## #        ##    ##       l   ## # # #####    ###    ################  t ###    ##
#         b               #    ##    ##   # ######### ##### ############ # #                                     ####   ##
########               r  #   ##    ##  t # b      ##     # #        ###   #######   ####  l ###    f    ####    ####   ##
#    #             fb            #            ###  ####                                                                  #
#     #         # #           l #              # t ##      ##a  a          #         #####  ###  #  ##  #  ###  #####  ###
#     #        # r #    f       #             rt          ####   #   tf   ####  t##b ###    ###     ##     #           ###
#      #       #   #             #g                        ##   ####      ######  ####   #### #   #### # ##  # ## # ####t#
#          #  #     #   #                                    l  ####        #####                                        #
#         #      #     #   # #           r   ##      #           ##   ##      ###  c#      #    #  #  #  #    #   c  #   #
#   tf    #       #    #  #   ##        #  ######   ###   ##          ## r      #   #      #    #  #  #  #    #  b g #  a#
#          #          #   #     #         #######   ###   ##                     f  #      #    #  #  #  #    #      #   #
#c                    #    #               ##  #     #         t g##                #      #    #  #  #  #    #      #   #
#                #     #   #      #                  r            ##   ##      ##  t#      #    #  #  #  #    #      #g  #
#     # #       #      #    #      #              f              ####  ##      ##   #      #    #  #  #  #t   #      #   #
#    #   ##   b #      r#    l     #             ##  ##          ####               #      #    #  #  #  #  c #      #f  #
#    #     #     #                  # #       g##########   ##    ## c     #        #      #   c# t#  #  #    #      #   #
#l    #          #                     #       ##########   ##    ##     ####b                                       #l  #
#    f     #      #        ##          #  ##        #r           ####f  r####    #   ## #   ##   ###### ###  ### #  ### ##
#           #             #  ##         # ##    ##  #  #      g  ####    ####    ###  #####  ###  #c      ##   ####   ####
#                   #          # #       l     ##########   ##    ## r  t####    ###  ##### c###  #    #  ###  #####  ####
#     #       #    #              #          f ##########   ##    ##       #     # #### # #### ##   ####### #### # #### ##
#t   #  l      #             #    #              ##  ##          ####                                                    #
#c   #         #   #          #    #                    g        ####  ##      ##  r#       #   #  #  #  #   #       #   #
#     #     #   #   ##        l  f #      g      a           cl  l## t ##      ###                                 #### ##
#        #   #  #     #      l      #      ##  #     #            ##             #   t#####  ###       #  ### t##     ####
#       # A  #   #       #          #     #######   ###   ##          rrb      f ###  #####  ###  #    #  ###  #####  ####
#b            #    f#   #            #     ######   ###   ##          ##       c## #### # ####t############ #### # #### ##
#       #     #    #    #         l          ##      #         t ##   ##      ###    #     #    #c #b #  #    #     #    #
#        #     #   #     #               a             g        ####        #####    #   f #       #  #  #    #          #
#    c   #      l   #    #            #         tl        c##   #### f    ######                                     ##t##
##     b  #    #    #     #    #     #                    ####   #  r    c####                                        ####
#         #     #    #          #r   #         #   ##      ##           f  #     ###  #####  ###  #    #  ###  #####  ####
#     l  #      #A   #  t       #     #b      ###  ####                                                                 ##
##########################################################################################################################
