metadata:
  gen_time: 10.19729471206665
  timestamp: '2025-04-18T22:50:08.606776'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
###                                                        ##    r         r      t                  b               #   #
#          ## ## ## ## ## ## #### ## ## ## ## ## ##   t                                    r      l    c       ####t #   #
# #   t    #  #  #  #  #  #     #  #  #  #  #b    #        #   b l      r             l         b       c   r  #  #  #  ##
###g       #  #  #  #  #  # t#  #  #  #  #  #  #  #        ##                                  b          A    #     #  ##
### ## ## ## ## ## ## ##  # ##  ## #  ## ## ## ## ## ## ## ##  r   a                                      f   l#  #  #   #
#   #  #  ## ## ## ## ##  # ##  ## #  ## ## ## ## ##  #  # #                 t            a                    #  ####  ##
# # #  #  ## ## ## ## ## ## ##  ## ## ## ## ## ## ## g#  # #                ### ##                  f          #    l   ##
### ## #  #  ## ## #  #     ##  ##     #  # ## ##  #  # ## ##                 f  #     t                       #   l     #
### ## #  #  ##t## #A #     ##  ##     #  # ## ##  #  # ## ##b         c    #f   #      b               g      #f        #
###  # ## ## ## #  ## #     ##  ##     # ##  # ## ## ## #  ##             ra######      f  r                   ######    #
###  # ## ## ## #  ## ## ## ##  ## ## ## ##  # ## ## ##b#  ##                     rc            c                f  #    #
### ## #  ##b## #  ## ##  # #    # #  ## ##  # ## ##  # ## ##    # ##                 l                             #    #
### ## #  #  #c #c #  ##  # #    # #  ##  #  #f #  #  # ## ##    #  #                                               #### #
#   ## #  #  #  #  #  ## ## ##  ## ## ##  #  #  #  #  # ## #     #  #   g  #####  b  f r        l           c  l       # #
# #  # ## ## ## ## ## ## ## ##  ## ## ## ## ## ## ##f## #  #     ####      #   #   r               c b                b# #
# #  # c               # ## ##  ## ## #                 #  #              c#   #              a    r                   # #
# #  #                 # r#  #  #  #  #                c#  #f        gb    ## ##                     l           b     ###
# #  #                 # l#t #  #  #  #                 #  #c l        l   g      r              r    g      f      a    #
# #  #                 ## ## #  # ## ##                 # c#                                                             #
# ## #                 ## ## #  # ## ##                 # ##                  ## ##                    l       fg        #
# ## ## ## ## ## ## ## ## ## #  # ## ## ## ## ## ## ## ## ##            r r   #   #                     b    f           #
# ## ##  #  # t#  #  #c## #  #  #  # ## #  #  #  #  #  ## ##                  #   #                        l    a l      #
#l## ##  #  #  #  #    ## #  #  # A# ## #  #  #  #  #  ## ##                  ## ##                  c               l   #
# g# ## ##  ## #  #  #  # ## #### ## #  #  # g# ##  ## ## #  ## ##         c     ar       ##################            l#
#  #  # ##  ## ## ## #  # ## #### ## #  # ## ## ##  ## #  #  #   #       f r              #                #     b   l g #
## #  # ##  ## ## ## ## #  #  ##  #  # ## ## ## ##  ## #  # ## b #                      f #                #             #
## # ## ##  ## ## ## ##b#  #  ##t #  # ## ## ## ##  ## ## # #  f #   r            b       #                ########  g   #
## # ## ##r ## #  ## ## ## ## ## ## ## ##c##  # ##  ## ## # #    #                    l   #  ## ##            t  r#      #
## # t# ##  #  #  ## #  ## ##l## ## ##  # ##  #  #  ## #  # #    #######           cr     #  #   #b  r l          #      #
#  #  #  #  #  #  #  #  #  #  ##  #  #t #  #  #  #  # A#  #      c     #           l      # c#   #  l           r #      #
#  #  #  #  #  #  #  #  #  #  ##  #  #  #  #  #  #  #  #  #                               ####   # f           A  ########
# ## ## ## ## ## ## ## ## ## #### ## ## ## ## ## ## ## ## ##  f        #       t               a ####                    #
#                b                                                     #####         r          a   #            A       #
#  t                             t  c    t                      b      r   # g       r              #          c         #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #               c                       ## ##               c#
##  #  #  #  #  #  #  #  #  #    #  #  #  # c# r#  #  #  #  #              #    r   b               l   #                #
##  # c#  # g#  #  #  #  #  #    #  #  #g #  #  #  #  #  #  #              #####         f         b    #  f             #
##  #  ## # ## ##  #  # ##  #    #  ## #  #  ## ## # ##  #  #g        b        #b      r                ## ##    t c     #
##  #  ## # ## ## ## ##g## ##    ## ## ## ## ## ## # ##  #  #cf              f #       f          f         #            #
#   #  ## # ## ## ## ## ## ##    ## ## ## ## ## ##g# ##  #    l  c  b   ## ##  # c                          #      b     #
##  #  #  #  #  #  #  #  #  #    #  #  #  #  #     #  #  #  #      b  f   r #  #                         g  #            #
##  #  #  #  #c #  #  # t#  #    #  #  #  #  #  #  #  #  #  #           #   #  #                            ## ##        #
## ## ## ## ##  # ## ## ## ## ## ## ## ## ## ## ## ## ## ## #f         b#####  #####  a                         #        #
#             t                       f           g f                              #    l      l  b g           #     l  #
#                                                                                                              c#       b#
### ## ## ## ## ## ## ## ## ##  ## ## ## ## ## ## ## ## ## ## r                    #              ll            ######   #
# #  #  #  #  #  #  #  #  #  #  #  #  #  # t# t#  # t#  #  #                       ####      b   r                   #   #
# #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #                         b#      ## ##f f                #   #
# #  # t#  #r #  #  #  #  #  #t #  #  #  #  #  #  #  #t #  #        f l               #      #   #             b  f l#####
# #  #  #  #  #  #t #  #  #  #  #  #  #  #  #  #  #  #  #  #         l                #####  #   #                   f  ##
# ## ## ## ## ## ## ## ## ## #### ## ## ## ## ## ## ## ## ##     t              f         #l #   #                      ##
#                          c                      t                      A    g           #  #   ####                   ##
#   t                           t    b         g                ## ##                c    #  #      #                   b#
#############################################################   #   #     t               ####      #                    #
##g  ####          ####  ############  ####          ####   #   #   #                          b    ## ##   b            #
#                              l                            t   #   #                               f t #                #
##   #  #          #  #  #   ####   #  #  #          #  #   #r  # r # t  g            g                 #        c       #
######  ############  ####   #  #   ####  ############  ##### g #####      ## ##                      g #########        #
#                                    g                        f            #   #                     l          #        #
# # # #  ## #   #   # ### ####  #############################   gf         #   #   a    g                            r   #
# #   #     #       #   #  g        #                   #b#  l#                ##   g#     #####   ###  ###     # ##     #
# # # #   # #   #   # # ##### # ### ###c ## # # # # ##### #   ##g      ####  ar ##   ##      ####  ####      b ## l#     #
#   # #         #     # l     #    f# #c  # # # # #            #    ####a ###        #     l          #   a #  #   ##    #
# # # #   # #   #   # # # ##  # ### # ##### ### ### # ### ###  ##     c    r##      b##         ##    ##    #  # g ##    #
# # b     b #       #   # #   #   # #       #l# #   # # #t#l  l##       ## r    #     #a##     a      # a  t   # # ##    #
# # # #   # #   #   # # ###   # ### ### # ### # ### ### ### c  ##               #  #########   #### l #  #  a ## #       #
# #   #   #     #   # #   r   #       # # #       #      t#  #a      ###    ##  b   ##   a##t  ##    ##  ###  #  ###     #
# # # #   # #   #   # #####  ## # #####c# ##### ### ### ###  #        #  a   l      ##          ##a  ##  ###a #  # ####  #
# # #       #      l# #     #   #       #    t  # #  A# #            ##  ##       ####  ##  ##r #   ##   a    #  #       #
# # # #  ## #   #  ## # ### ##### ### ### # ##### # ### ###       a  #  #####      #     #####  #lb ##      ###       a###
# # # #   #     #   # #   #       # #   # # # #     #   #t  a      g       #l  #####     # # #  ##r    ##  ###  b  #a  ###
# # # #   # #   # ### # ####### # # ####### # ####### # # ###a    ##    ## ##  ga###  ####      a#   a ##  # ##a   ###   #
#           #   #c  f #   # # # #     # #           # #      # a   ##    #  #           #      ###      #        ##  #####
# # # #   # #   ### # # #b# # ##### ### # ######### ##### # r####  ## ####### #   a ##ba      ###   ##      a   r   t    #
#           #   #   # t #         l     #     #   # #     #f  b#    # ### t#  ##  #####        b     a          ### a  ###
# # # #  ## #   # # ### #### ## #  ###### # # ### ### ### ###      ## #    ## ##         a        c   ##t     l         a#
#   # #   # #     #                     # # # #l   c#  t#          #  ##    #                  ###l # ##  ##  #########  #
# # # # ### #   ### # ### ##### # ### ########### ### #######  # a##   #       ##   ###  #     a##  # ##  f    ### ## ####
#     #         #   # #A  # #   c   #                    t#    ## #    # # g   ## ba##   ####  ##     ##      ##        ##
# # # # ### # # # #                   ### # #######  ## ###    ## #    #####   #    ##  ## ##  ###    l#      a    r    ##
# # # # #   # # # b                   #   #       #   # #     ###      ##      ##    # a         #   #####     a       ###
# # # # # # # # ### # # # #       # # # ### # ### # ##  # #   #      # ##      ##    # ##   ###     ##        #     #  # #
# #     #   # #           #       #   #   # #   #t      l #        # # ##a   ###       ##   ###r a   # ##    ## #   # r# #
# # # # # # # # #  #### # #      ##   # # # # # # # ## ## #c   a####   ##  ###         gag###       ####   # ## #   #### #
#   # # # # # #       #           # #     #     # # b     #     ####    #   a  t###  ##   ###         ###  #a   ## g#### #
# # # # # ### # # ### #  ###    ###r# # ### # ### # #######  ####    #  ##      ###    r                   ######        #
# # b   t # #   # r     #      b#b#   #       # # # #            a   ##  #          ##      a##   ######    ##         g #
# # # # # # # # ### # #   ##    # #   # # # # # # # # # # #### ###   ## l g  ##     ##     ###   b  ######  ## ######    #
# #   # #     t # # #c#  f#  b#       # # #       # #l# #    ##  b  a## a        ####      ###          ##    a### ##  ###
# # # # ### # ### ##### ###   # ##  # # ### ##### # # ### ###   a     #g  ###    ## #   b# #   #  ###g      a###         #
#         # # #          t#     #   # # #         # #     r  ##  b  r ##a   #### ##      # #   #  a    ##              t #
# # # # ### # # # #    ##c#   ###  #### ### ### ### # ### # ##    #####   r    ####  a####   ### aa l #####    a##   a#  #
#   #     #  c# # # #     #t  # #        r# # # # # # #      #    a#####         l      # b  ##              #####    ####
# # # # ########### ### ###  ## #  #### ##### # # ### # # ####    ##     a #####   ##  a   ####             l  # #   ## ##
#   # # #     #     # #               #     #   b      r     ##         ## ## ##a  a       ##        ##a  #             ##
### # # # ##### ### # # # ### ###  #### ### # # # ### # #######     ##  ##a##    #####   #  ##f  #        #  a      ######
#           #   #   #     #   #                                     ##b###  # l  #####  a# a#    ##     #              #a#
# # # # ##### ### ### ##  ### # #   ### ## #### ### # #######       #  # # ##   a#          #    ##l##  #g               #
# #  c# #f  # #c    # #   # # #     #   #     # #  l        l  ##   #  #   ##    # ####  a  # a t##a##A ##         ##   a#
### ### ### #b### ######  # #### ## #######f# ### ##### # #r    #####              ## ###        ## ##   #    #  a       #
#   #             # #         #  l          # #   # #   # #        #  a  # #####   ##         #   #  ##  #  #######  a   #
### ### # #####c# # # ##### ######### ### ### ### # #####t#### ### ##  ###  b#    ## b   ######        a  g ##  #    ##  #
#   #   #    f#l# t                                          #######   ####  ##    #      #  # a    ####  a ##  ##       #
### ### ### #                                             #####      g #    b##  ###     a          #########    #       #
#     # g   # #   #       # #                                    ####### #####  l###   ##   b       #    ##      # a  ## #
# # ####### ### ### # # ### ##### # # ##### # # # #########      ### ### ##           ##  a#   ###  #    ##   #  # #     #
#       #   #    g# # #           # # #            b#          # # b    r##    ##         ######        ###   # ## ####  #
# # ### #####l#  ###### ###########   # ##### ####### ### # c  # #               a # c    #        a    # ##    ##   ##  #
# # # # #   #             c #     #       #       #   #   #  # #  #   ###    ###   # a# ### ##  ##     a        ##  ##   #
# # # ### # ### #  ##b### #  ## ###   ########### # ### #b#  # ####     ###  a##      ####  ######          #####    #   #
# #t  # # #   f           #t              #     # # #   # #   a####  ## # ## a##    a ##       # ##    a##  ##      ##  ##
# #f# # ##### ##     ### l### ##  ### ###   # # # # ### # ###       #####      #         aa        a         ##      #####
#       #   #   #         #l      #   # #     #    t#b       ##   r # a ###    #### ##  ##         ##    ######        # #
### #   # ### # #    ##  #######  # ### ####  ### #   ### #  #####b #   ###     #a###            #### ####      b### ra  #
# c # #                                             c #c  #      ####  f#     ###        g       ## # ##    b            #
# ### # # ######### ### ##### ##### # ####### ##### ##### #  #                ###     a#    #b        ##        ##      ##
#  r# #           #t  # # #   bf#   # #           #       #  #    ##     l  ###      a ########  r    ## a  ##          ##
# ######### # ### ###   # #t# # # ##### # ##### ### ##### #  ##  ##               ##   ###   #      ###     ##   ##  #   #
#     r                                               #   #  ## a       a #   #####  #          ########  ####  a##  #   #
#       b # # #           # # # b     # #   #   #     #   #t ##    ##   ###   ####  f#a   ##    ##                #a##   #
##########################################################################################################################
