metadata:
  gen_time: 8.874072074890137
  timestamp: '2025-04-18T22:52:05.494947'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# ##      #     ### ###                                         ##   ##l  ##                 ##   ## gr## b      g       #
# ####   l## #####   ##                                  l      ##   ##   ##           l     ##   ##   ##            l   #
#  ####   #           ##  c   b         t  ##         g         #    #    ##            r    ##    #    #                #
#    ###  #          ###               #   ##  #   g l         ### ### #####         g       ### ### #####  g            #
#     ##  ##     ## ##   ###           ##   #                  ### ### ## ##               b ##  ### #####   tg   A t    #
#    ##   ### ####r      ##       ##   ## r     tb      r      #          ##                 ##   t      #   t    g      #
#    ##         t            b    ##   ##     r                #          ##                 ##      rb  #               #
# l  ###                     g    ##   ##       ################          #  ############### ##         b############## ##
#    ####                   ##    ##    #       ################   bg     # ###################          ############## ##
#    ## ## ## ## ###         ##    ##      a       g  #        #          # gr               ##          #        #      #
#  ###   ###      ### ###    ### l  #          l  l   ##    A  #    fb    #                  ##       f  #       ##      #
# ##     ##        ####l       ##                g    ##      ##                             ##       l  ##      ##      #
# #      ##        #            ##             l      ##    l ##          ##t                ##      l   ##      ##      #
# #     b##   #########          ##               b   ##    b #                               #           #      ##      #
# #           ###     ###  t     ##                g  ##b    ##### ### #   ##################### ### #######     ##      #
# r       t   #        ##         ##     g            ##     ##### ### # ####################### ### #######    t##      #
#             #      l ##       b  ##    b       l     # f   #       f        b                   #        #   r         #
#            ###      l g                       ######## ######        #   r          t          ##       ## ###### ### ##
# ### ###    ######       r  f       t          ######## ######        #                         ##          ######     ##
# ##   ### ###     # ##   b                            #      #        #               t         ##       #      #       #
#  r   ##   ###### ######     f                   #   #     #  #    #  #      ########### ##  ##  #       #####   #  #  ##
#       ## ## ###   ##                        # ###g#     #        ##  # ####     #    #   ## #   #   ##    #   # # ### ##
#       ## ## ##     ####       b       b     ###   ####  #  ####g ###      ### # # ##   #   a#  ##  g # #  # ###     A g#
#       ##### ##a    ####                 t   ##  ###     ####  ## #   # # ###  #   #  ###  ###      # #   ##  #### ##   #
#  t  ### ##   ##     #     r                   # # t #l   A   ###   #     # #### ### ##    #     ## #   #  ####    #    #
#     ### ##    ###     r                           ###  ###     # ###    ##      #  b   #### #  ##  c   #####   #  #    #
#     ##   #                                    # ###      ####    #   #     b #  # ######  ###      ##      # ### ##    #
#      ## ##    #### r  #                         #   ## r###   #  # #     ###g#### #  #   ###    #b #       #      ##   #
#          #    #### g  #              #        # # l #   # # c### # #   # #   #    #  #     #c#  #  #    #### #  # #    #
#       A  #l    #                     ##         ### #  b#    #     # #     ###      #####  #    ## ##      ###g # #    #
#  ##      # r  ##                  lr ##       # #      ## ##       #    #      ##    f  # ## #         ## ###   #   a  #
#   ###g ###    ###                    ##         f ###   #  #b #  ###   ####     #   ## ##    # ##  #   #  # ### ## ##  #
#   #### ##   r  ### ## ####           ##       # ###    b#  ####             #       #  #   ###  #      # ##   #    #   #
#A   # # ##       ## ## ###            ##       #  ###   ##   #    #   #   ####   #  ### #   # l  #  #     #    #    #   #
# l ## #####     ##   #                ##       # ## #   #### # ## #       #  a   #  #      ## # ##  #    ## ##   ## ##  #
# ###   ## #     #    # #    ##        ##       #    # # # #    #    #   ### #       #    # #    ### ##       #####  #   #
# #     ##       #    # #    ##         #   #   # ## #   #   # ##    #   #      ###c#####     #  #   #   #######    ##g  #
# b     ##t  # A #    #       #             ##  #    #   # ### #   ### # #     ###  #         ## # # #   #   # # ##      #
# f l t      ######   #       ##             #r # #  # # #     #     # #       # # ## ## #  ####   #     #   #      ###  #
# #              ######       ##         l r    c ####   # #   ###  ##      t##       #  #     #  ## ##    ### ###    #  #
# #  ####   # ##   t###       ##                # ##       #####    #             ##  #  #  ##    #  #    ##   #   ## #  #
# #t ####     ##     #        ## r          b      # # #  ###    #     #       t#    ### #  #    ##  #       ### ###     #
#  ##########     ##    ##  ###a ###  ##  ## t### g# #   ##rt#####  #  #  # ##   #########  #### ##  ##  ##############  #
#  ###########    ###   ###### t ###          ###    # # #r  #####  #  #  #    ##       b         b             b        #
#  #############     #  ######  #####        ####    # #    ######  #  #     #### ########  #### ##  ##   #############  #
#  #  ####   #####   ## ##      ####### #########    t   #########  #     ##  ##  ########  #### ##  ##   #############  #
#  #  ####   ## g#    # ##     ######## ######### #      ########g  #     ##a                                  l         #
#  #  #####  ##   ##  # ##  #######  ## #####  ## ## #   ####### a  #  #  ##   # #########  #### ##  ##  ##############  #
#  #  ######  #   ##    ##  #######  ## #####c ## ## #   #######    #  #         #########  #### ##  ##  ##############  #
#  #g #######  #  ##  a     ######   ## #####b  # ## #    g  ###b   #  #  ##   # b            t                    b     #
#  #  ######## ##  ##      #######  ### ######  # ## #       ####   #  #  ##       #######  #### ##  ##  ##############  #
#  #   #######          ##########  ### ######  # ## # # ##         #  #  #       ########  #### ##  ##  ##############  #
#  ### ##               ##########  ### ######  # ## # # #                                                           g   #
#  ### ##   l  # #   #  ####  a     ### ######  g      # #  #  ##        #  ###  #########  #### ##  ##  ##############  #
#  ### ###  ####     ## ###     b    ## #######        # ####  ##   #      ####g #########  #### ##  ##  ##############  #
#   ##      #####b      ###   ###### ## ######### ##   # ####       #      ###                    b            t         #
#   ##     #####        #### l###### ## ######### ##   # ###   r    #      ###  #### #####  #### ##  ##  ##############  #
#   ##   #######  #     ####l ###### ## ######### ##   # ###  ##    #  #   ###   #   #####  #### ##  ##  ##############  #
#  ###   #####    ##     ##   ###### ## ######### ##   # f    ##    #  #   ####          t   f    b         l            #
#  ###   ####    ####    ##  ####### #  ##g ##### ##   #     ####   b  #   ####    #######  #### ##  ##  ########### ##  #
#  ###   ####  ######   ###  ####### #      ##### ##   # ##  ####   b  #    ###   ########  #### ##  ##  ###########     #
#   ##  ##### a#####a   ###  ####### ##    ###### ##   # ##   ###      # #  ##a   a    t         l   l           b       #
#  c##  #####   ####r   ###       ## ## ########       # ##   ###      # #  ##      ######  #### #   #   ############    #
#  ### r #####  ##### f ####         ## ########       # ##  ####   #  #          ########  #### #   #   ##############  #
#        #####  ####### ####  #####  ## ######### ##   # ########   #  #                                             g   #
#       #####   ####### ####   ##### ##    ###### #    # ########      # #     g                                   b  t  #
#  ###  ##### r######## ####   #####         g### #  b # ########      #       # #########  #### #   #   ##############  #
#  ### a ## gag###   ## ##### b#####          ### #  # # ####   #      #      #g #########  #### #   #   ##############  #
#  ###   ##     ##g  ##  ###########  #    #  ### ## # #   ##  a#      #    # #              b                    ta     #
#        ##  ##      ##     a  g   #a ###### a#    l           ##   #  #      lb #########  #### #   #    #############  #
#      a########## # ##            #          #  b        #######   #  #         #########  #### #   #    #############  #
#  ### ###########   ##   ### g#####g         #####  ###  #######   #  #  #  ####                                        #
#  ### #############      ###t  ####  ######  ####   ###b  ######   #  # #   ##   ########   ### #   #    #############  #
#      ################  l###   ####  #a   #  ####   ###   ######   #  #        ##########   ### #   #    #############  #
#    r ####       ######  ###b #####          #####  ###  ######       #  ##    #  A A                                   #
#   ## #       f  ######  r #g ####    a##  c  ####  #    ######         a####  # ########   ### #   #   ##############  #
#  g## #    ##c              g ####  ########  #### f      #######gr##            ########   ### #   #   ##############  #
#    # #  #############  ##    ##    ########   g##    ##  #############                      l                l         #
#   f# #  #############  ##  ####    ########    ####  ##  #############  ###  ###########   ### #   #   #########  ###  #
#  ### #  ############   #   ####r ############  ####   #   ############ l################   ### #   #   #########  ###  #
#  ### #r   ##r     ## b #  #####  ############  #####  #  g##  a                    b g                                 #
#  ### #    ##      ##  ##  ####  l####    ####ab #### b##       a  ##       ######### ###   ### #       #########  ##   #
#      ###  ## ###########  #### b#####    #####  ####  ##############  #### rb  #####       ### #       ########## ###  #
#      ###  ## ###########     #  ##### ########  #     ##############  ####                                             #
#  ### ###  ##   ##########          r    a            ##########   ##  ##################   ### #       ##############  #
#  ### ###     a #####  ######                   r  ######  #####       #######  #########   ### #       ##############  #
#  ###  ##   r #######  ######  ###### ###########a ######  #######r  t ##  ###        b                                 #
#  ###   #  #  #######          ###### g##  ######          #######  #      ###  ##### ###   ### #       ##############  #
#      #####      r       ################ ######                #####  ##############       ###         ##############  #
##     #####  g######                   g                        #####  ##################   ###         ##############  #
##     #####   ######                                           g#####  ##################         ####c ############## t#
##                      #######              c########  #######  #####  ##################         ####  ##############  #
##                      #######               ########  #######  #####  ##################         ####  ##############  #
##  ##   ###########    #######     ######    ########  #######  #####  ##################         ####  ##############  #
##  ##   ###########    #######    g######    ########  #######  #####f        t                   ####  ##############  #
##       ###########   t                                       r       b     a                     ####       tg         #
#        ###########                                                                    g                 g     g        #
#r                    #####        ##################  ##################           t         fgfa         ############# #
#                 t   #####        ##################  ##################   ######         #######    g    ############# #
######                #####                            ################## b ######  ####  t#######         ############# #
######   ####         ##### g      a      f t     g    ##################   ######  ####   #######         b             #
######   ####        b#####    g       t                       r             r      ####   #######                  r    #
######                #####    ##   ########  ###  g                 g                   a          ########             #
######   g           g#####    ##   ########  ###  ### r             b                              ########    ####     #
#       ########### r #####    ##   ########g ###  ###                  ##################          ########    ####     #
#       ###########   #####         ########  ###  ###      ######      ##################  #####   ########b            #
###     ###########   #####                   ###  ###      ######  g t                 a   #####   ########             #
###     ###########             b             ###   t   a   f        a         t                    ########  ########   #
#       ###########            #####                g               ##############                  ########  ########   #
#               b              #####             ct   #######    t  ##############   ######a        ########  ########  ##
# ##                           a      b               #######    g  ##############   ######         ########  ########  ##
# ##     b  a                                 t    A                                  a     r                a########  ##
#            g     c    #############             ag l             b                                           a        ##
#               #####   #############               ##################    ##################  #########                 ##
######    g###  #####   #############               ##################  l ##################  #########                 ##
######  g  ### g#####                  ########        r        g                         b a #########    #####    b   ##
######          #####    g         t   ########          t          t   aa                         g t     #####        ##
######t     a   ##### g##########                ##     ######       ####   ##       ###        b          #####         #
######  b       #####  ##########   g            ##     ######       ####   ##       ###   ############b   #####g a      #
######          #####  ##########   a ##                                    ##  ###  ###   ############    #####   #######
##########################################################################################################################
