metadata:
  gen_time: 10.316881895065308
  timestamp: '2025-04-18T22:48:03.697090'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##### ### ## ##### #### ### ## ####a### ##a## ## ## ## #### #### #### ###      ##   ###  ###############  ###   ## gl   ##
#  a  gb   a                    ### ### ## ## ## ## ## ###  g##   ### ###      ##   ###  ###############  ###   ##      ##
#             f      a          ##a     g            a  ##   ##a  ##   ##           ###  ###############  ### f         ##
# ### ### ## ## ### ########## ###            t     a f ##   ## t ##f  #                 ###############             r   #
# ### ### ## ## ### ########## ###     c                ##                f        l     ###############                 #
# ##g          l          ##    ##                           ##   ##a  #  ######         ###############         ######  #
# ##                     a      ##f                   t ##   ##   ##   #f ######    ##   ###############   ## g  ######  #
#    b          a      t  ##                     a  t  t##    f   f       ###### l  ##      r b            ##   l###### g#
# ##A             a  f    ##   a##        a                  ##   ##   #  ###### f  ##                     ##   r######  #
####### #### ### #### ## ###   b##            a   f     ##   ##   ##   #  ######    ##  ##   #######   ##  ##    ######  #
####### #### ### #### ## ###             b  a      afa  ## a ##   ##   #  ######    ##l ##   #######   ##  ##  l ######  #
###   a           ##      ##b   ##                         t ##           ######    ##  ##   ####### f ##  ##    ######  #
#                 ##      ##    ##  b g a   t  a     fa ##g   af a##  c#tl######    ##  ##g  #######   ##  ##    ######  #
###         b     ##            ##  a                  f##   ##  a##   #  ######         l   #######             ######  #
###               ##  b  b##  a          a    a g a     ##   ##    l   # b   ###      l      #######             ###     #
###g     l               f##   a##                         t      ##     l   ###     f     g #######         f   ###     #
## A       ca     ##            ##                  g   ##   ##   ##   #     ###  ####       #######       ####  ###  g  #
#  f    b      b  ## t   f##    ##                      ##  a##   ##   #   r ###  ####       #######       ####  ###     #
###           r   ##      ##    ##a        t            ##   ##b  ##   # r   ###  ####       ##   ##   r   ####  ###     #
###                       ##     a                          a         r  #######  ####  #######   #######  #### f#########
###               ##      ##    ## a     a              ##  b##   ##   #########  ####  #######   #######  ####  #########
###   b           ##b     ### ############ ## ## #### ################################  #######   #######  ###############
#         a     a         ### ############ ## ## #### ################################  #######   #######  ###############
###               ##      ## a   ##   ##     c    a           ##    ##  #######    b    #######   #######r   r    ########
### a  c         a##     a## a r   a                  A                 #######b  t           f b     g  l        ########
###     a      a  ##      ##     ##   ##                      ##    ##                              fg              f    #
#### #### ## ### #### ## #### ################## #### #### #############         f#####  lb     g         #####          #
#### #### ## ### #### ## #### ################## #### #### ##############         #####                   #####  t      ##
#    t##           a       a      ##   ##   l     ##t  ##      ##    ## #  b###   #####                   #####   ###   ##
#    b##                    t           t         ##   ##a            a #   ###   #####  r      b       l #####   ###   ##
#  r              r               ##   ##         ##   ##   b  ##    ## #       f ##### r       g  r      #####         ##
#     ##                    a     ##   ##   f          ##    t ## b  ## #         #####       #####  r    #####         ##
#a    ##               a             a ##         ##                 ##  f  g   r #####       #####       #####        l #
#     ##              a    t      ##          a   ##   ##      ##l   ##   r       #####l    #########     #####   t  r   #
#     ##                         f##   ##     a   ##   ##      ## b           #########     #########     #########  r   #
#     ##     a      t  f     f    ## a ##                      ##    ##  ###  #########        b       b  #########  ### #
#         r                                       ##   ##    a ### ##### ###  #########      ll       f   #########  ### #
#a a  ##f a                      b##   ##         ## b ##   f b### #####  ##  #########                   ######### b### #
#            c##            r   ######### ## ### ###   #      c   ###f###   #   # # ## ##t# #   #   ### # #        r     #
#        a                b     ######### ## ### ### #####       ## ### ##  ##  r   a          ##  ##b### ##       ##### #
#  a     r    ##    t           ##  ##             #    #  g        ##b #   r#     t         g #    #  ## #         #    #
#             ##                ##  ##     c       # ## ##  t ##  ###   ###  ##  #g#   l # #  ##  ###   ###  ##    ## ## #
#                  f          f ##  ##   b        g# ##  ####    a     ## #b ##  ###     ###l ##  # ##          ####  ## #
#             ##                ##  ###### #########a     #    t###  ###    ##  ##     A   ##  ##r   ###  ###     #      #
#  g b        ##                    ###### #########   ## ###     #         #   #  ##   ##  #   #         #     ### ##   #
#             ##                ##  ##           ##f        ## ####   a    ## r    ##   ##      ##        #### ##        #
#  b          ##                ##  ##           ## ##   #####  ##             #    ## ##  a #            f##  ### #   ###
#    b        ##                ##  ##          f##  t  ## #   r         ##    #             #    ##             # ##  f #
### ### ############ ## ##########               ##   #### ##g##  f   # ###   ##             ##   ### #      ## ## ####  #
### ### ############ ## ##########  ##              t##    ## ##      #a#   #                   #   # #      ## ##   b## #
###  ##   t     ##     f   ##   ##  ##     l     ## g## ##  # #      ##     ###    ##  t##b   ###f    ## r    # #  ## ## #
###  ##         ##         ##   ##  ##           ## br  ##    #  ##    g     #      #   #      #          ##  #  t ##    #
###  ##       b ##        g##           f     b  ## ## ##   # #    r # f  a  ##    ## # ##    ##       #   f    #   ## ###
#############################  f##  ##           ##    #    # ##   ###       ##  ###  #  ###  ##    b  ###   ## #  t     #
#############################   ##  ##           ##    #    # ##   ###   f   ##  ###  #  ###  ##       ###   ## #  g #   #
#   A  ##   ## g    ##  c  ##       ##    r      ##### ##f  ###      #     a ##    ## # ##   f##  f  b #   r  ###   ## ###
#      ##   ##      ##    c##   ##               ###r   ##    #  ##          #      #   #      # b        ##  #g   ##    #
#      ##   ##      ##     ##   ##  ##           ##c ## ##  ###      ##     ###    ##   ##    ###     ##      ###  ##b## #
#        A          ## g   ##   ##  ##           ##  ##    ## ##      # #   #            t  g   #   # #      ## ##    ## #
# g    ##   ##      ##     ##   ##  ##           ##   #### ## ##      # ###   ##             ##   ### #      ## ## ####  #
#      ##   ##      ##     ##   ##  ##           ##     ## #        t    ##    # l           #f   ## r       b   # ##    #
#      ##   ##### ###### ############### ## ##########  g#####  ##             #   a##f##    #             ##  #####   ###
# g    ##   ##### ###### ############### ## ########       g## ####t       ##  t   ##   ##    t ##l       #### ##        #
#   t  ##   ##   r        t    ##                      ## ###     #         #   #  ##   ##  #  a#         #     ### ##   #
#    f ##   ##                 ##          f              #     ###  ###    ##f ##         ##  ##    ###  ###     #      #
#  r   ##   ##   f             ##                    ##  ####          ## #  ##  ###     ###  ##  # ##          ####  ## #
#      ######### ##### ####################### ##### ##g##    ##  # #   ###  ##g # #     # #  ##  ###   # #  ##    ## ## #
#      ######### ##### ####################### #####    #a t  r  g# ##  #ff  #     g           #    #b ## #         #    #
#      ##                ##      ##   ##      b      #####     r ## ### ##  ##                 ##  ##  ## ##       ##### #
#      ##     r          ##  a   ##   ##            a  #          ### ###  f#   # # ## ## # #   #  t### ###  r       #   #
######  ##   ###    ##  ## #                 f           ##   ##       #a ### #  #   ##   #        r                 #   #
#  ##    #     #       ### ###   ###    ###              ##    ##      #  ##  #  #    #   #            ##        b   #   #
#   ##  ### ##   ##    # #        ########    #########  ##     ##    f#  ##  #  #     #                                ##
#   #   #   #                     ########    #########  ##      ##    ## ## ##  #  a   #          b                   # #
##      # ###  ##   # #    #     ###   r###               ## #######    #   ## A ##         #  f                   #     #
#   ##    # c ##   ####f ###                                   cg  ##    ####     ##        #           A          #     #
#l###   ### ###   ##    ## ## # ####    ####  ##     ##             ### ############# #  #######    b           #######  #
#  #   ##   ##   #####  #  #  # ############  ##     ##   #############  f   ##   c         #                      #g    #
#g  f  #  ###       #   ##    ##              ##     ##               ##      ##            #        # l  #        #     #
#          #     #      ##    ##############  ##     ##l       ##      ############## #  #  #        #    #        #  #g #
#     ##        ##  ##          ############  #########         ##      ##a     ##t       # #    l   # ## #        # # rg#
#  #  ###        ## #   ##  b     ##  l ##b   #########       c  ########        ##        f   #   ########## t #        #
#  ##   ###  ##   ###    # t ##                  f       ###################      #  a#         #   # # g# #   #         #
#             #  ###  ##l##   ##  ##    ##      r           t              ##     #   #    l #      g #  #        #    g #
#  ##                  ###   ###################     ####t                #### ## #   #      #        # f#        #      #
#  g#               #####   ##              ####     ####          #### ### f  g###   #  # g #        #  #        #   #  #
#                  l  #     #   ############  ##     ##    ### #####             ##   #   #  #  r  A  #  #        #  #   #
# ###  f     ##   ##   a        ############  ##     ##   ##   b                  ##  #      #  #              #  #      #
# #          #    #     ##    ## r##    ##    ##     ##  f#        r al    # ######## #      #b #           l  #  #      #
# ## ## #        ## ###  #    #               ##     ##  g#     ####### ####    ##  ####  #         ########      l  #  ##
###  #  #    ###  ### #    # ###  ## r  ##                # ## ##        ##    ## a  ##   #                   r      #   #
##   ##      #           #####    ##########              ### r    t      ######      #   # #       #      #       # #   #
###   #     ## #         #  ## ## ######## #  ##     ##    ##  ac         g####    # ## ######     ##      ##  r  ###### #
####        #  ## ##   f    l# #       r      ##f    ##     ##      g# #####  ######     # #        ########        # #  #
#  #    ## ##  ## ######g  # ############### l##     ##  t   #########   ##  g  #   g      #   ######      ######   #    #
#      a   ##         ###  # g  ############  ##  f  ##f   a ########     #  ##            #        ##    ##        #    #
###        #  ## ###     c                  ####     ###### ##      #######  ######## # #  #   #    #      #    #   #  # #
# #    ###      c#    ## ##  #  # ######## #####     ####         b            g       #        #              #        ##
# g           #########f        ############                                                         f                   #
#              ###   ##           ##    ##           A           ########### ##########            #        #           f#
#                     ##                   g  #########  #  ## ### a  ######    r######  ########   # #  # #   ########  #
#         ##     g    ##          ## l  ##    #########  ####        ##   b##   ##                    #  #               #
#          ##  g      ##      t ############                   t    ##      ##  #    ##  #      #     #  #     #      #  #
#     ##   ###        ##       t############  r   l                 #g      ### #   ##    #      # #    b   # #      #   #
#      ##   ##        ##a                   ####     ####          l#   #   # ###  ##  #           #        #           ##
#            #     l t##    r b ################     #####             ## g   ##   #         r     # #    # #            #
# ff         ##f      ##          ##  t ##    ##  g  ##  ### ##g    #  # f    #    #   #         l    #  #              ##
#  ##        ##       ##                      ##     ##       ####### r       #    ##   b  ###               l    ###    #
#  ##                       ###  l##    ##    ##    l##   f       ##   #t     ##    ## #           #        #           ##
#  ##                        ###############g ##     ##            ##### g    r##########        g  #      #           ###
#   #              ##         ##############             ## ### #######         ##    ##       b#             l#g       ##
#   ##             ##                                        ##       ###########                #  ########  #          #
#   ## t           ##           ################     ####     ##     ##################                                  #
##  ##    l    #    ##         #####    ########     ############   ##                         #   g            #  g     #
##             ##l  ###       g             f                   ##  #         g     r         f #              #         #
##bf           ###               ###    ###                      ##l#     # # #### ##l#                                  #
#               ##l         ##    ########    ##     ##  #### #######a   ##  c ##                          r    r        #
#     f             ##       ##   ########t   ##     ## g    a  t  ##   ##     ##                ##############       b  #
#                   ##  ##   ##  ###    ###   ##     ##              #  #     #### ####    #                  l     #    #
#            ###    ##  ###  ##            f  ##     ##  ########### ## #    ##     ##  #   #                      #f  # #
##########################################################################################################################
