metadata:
  gen_time: 1.7320458889007568
  timestamp: '2025-04-11T22:25:35.093561'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |##      ###|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |##      ###|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
####################################################
#  ###              ###     ###   ##          ##   #
#  ##              ####     ###                    #
#  ##              ####                            #
#  ##              ####                            #
#                   ###            #####   #########
#         ##  ##    ###  ###       #####   #########
###   ##  ##  ##    ###  ###       #####   #########
###   ##            ###  ###   ##  #####   #########
###                 ###  ###   ##  #####           #
#          ###       ##        ##  #####           #
#          ###       ##                            #
#          ###                                    ##
#          ###  ###        #####  ##    ############
# ###           ######     #####  ##    ############
# ###           ######     #####  ##             ###
#                          #####  ###              #
#                                 ###              #
###     ##       #####            ###     #######  #
######  #######  ############     ###     #######  #
######  #######  ############             ######## #
#####   ######   ############             ######## #
#####   ######   ############                      #
###     ######   ############   ###                #
#       ######  #############   ###   #########    #
#      ######   #############  ####   #########    #
###    ######   #############  ####                #
###    ######   ####                               #
###                                                #
###                         #########              #
###   ############     ##   ########################
###   ############     ##       ####################
#     #####            ##                 ##########
#                      ###                    ######
#                      ###   ##  ####              #
#    ##   ####         ###   ##  ####              #
##   ##   ####               ##                  ###
###       ##      ##         ##         #######  ###
###               ####       ##     ##  #######  ###
###               ####       ##     ##  #######  ###
###               ####       ##                  ###
###         ####        ##   ##                    #
#         ######        ###  ##  ###     ####      #
#         ####    ###   ###      ###     ####  #####
########          ###   ###      ###     ####  #####
########          ###   ###      ###              ##
#                       ###                        #
#                                      ###  ####   #
################               ######  ###  ####   #
##################            #######       ####   #
##################  ##        #######       ####   #
####################################################
