metadata:
  gen_time: 12.292142868041992
  timestamp: '2025-04-18T22:51:41.893455'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#####b       ###        ####### ###  r        #####       l   ######     #     #      ##   #      #    # ###          ## #
#   ###    ########   ####          #     l####   # #       ###          #  r ##  b   ### ##      ##   #   # ########### #
#     # ####     #### # bb          ###      b      #########      t    ##    #         # #        #   #   l  b    l     #
#   l   #######     # # ##l     r     # #######l      ###               ##    #       # # #        ##  #          a     ##
#   ### #    #####             A ######             ###  b               #    #       ### #        ##  #      l### l     #
#  b g        b    ## #                 lb###l        # #                ##   #A  r   ##           #   #                 #
##           #####    ################# r            f                   ##   #  ##   ##           #        ######      t#
###     b f    ########                        A                         ##   #   l   #        ##            bc         l#
#       ##l         ################      ######lg                        #   #       #              l b   l     t t l   #
#                       ##  ####  ##########   ####   #     b             #   #  l #  #   b             ###    #####     #
#                                    ####  b          #    l                  #    #  #  t    ########       ########### #
#### #      b    A           r    ####             b         l            r   #    ## #         ##   #########       ### #
#        b                 ########                          a       ####  #       ## ##            f      t  l     l  ###
#### ## #### ###############     f####        ############                 #        # ##  f       c   ###### #    #      #
#          r ##  ###   ##           ######         ####                    #        # #      l     l   ##         #    ###
#######                                  ###########b                      #  l     # #                        r  #      #
# #      b       ########                  ###   l ####                    #        # #         # #           l   #    ###
#   # ###t ##########          #       #####         ##########l                  t # #      #  # # t           # #      #
# ###   #####                  #  b      #####          ###         A    l          # #      #  # #  #          # #      #
#########          ##          # l           ###     ####         ##########        # #  # # #  # #  #    l     # ## #  b#
#     #######    r           # #    ##########     ###      f    l     l      cl l       # # #b####  #         f# ## #l  #
#     t                      # #                     ###############                     # #   #f##  ##     #     b# #   #
#    l#######                # #                       ###                    bb  ###    #   # # ##  ##     #      # #   #
#  #####        #     l      # #  t#########      ######  t                              #   # # ##  ##     #      #     #
## #            #   r  # #                  t     l  l # ########   c                    # # # # ##  ##        # # #     #
##                 b   # #                                 ###     # #                 g # #r# # ##   #        # # ## #  #
#      bf                      ###########   ####      ##      t   # #    # #  #         # # ### ##   #        ### ## #  #
##   ###########                       #######                   l #      # #  #    # #t # # ##   #   #     b  ##   # #  #
######         # ######                      ####      ##          #      # #  ##   # #  # # ##   ##  #        ##   ###  #
#    # #########      # ########                   #  t            ## #     lb  #   # #  #    #   ##  #        #    ##   #
#      t###    ########   ###                      #              f## #         ## ## #  #    ##  #   #        #    ##   #
#   b####        ###  #####                        #               #            ## #  #  ##   ##  #   #        #    ## t #
#     c ##### ####      #####                b     #t    b         #l      # #   # #  #  ##   ##      #        #     #   #
#         ###  #####        #######                                #       # #   #### #   #   ##      ## # #   ##    ##  #
#       ###        # ########     g                   t     #     ##    b  # #    # # #   #  b # g    ##l# #   ##  A ##  #
#                    ###    ###              b              #     #        # #    # #l## ##    ## #   ##   #    #    #   #
#              l #####        ##############   a     l      ## #  #         l     # # ## ##  # ## #   ## ####   ##   #   #
#      ##  l       #####    ###  ####  a              #     ## #                  # # ##  #  # #  f    # ##     ##   #   #
# b   r        #####   # ####        b      r       l #     #                     # #  #  ## # #    t  ####a##   #   #   #
##           ####  # ###                 b            #    ##                 b   # #  ## ## # #          #      ##  ##  #
## #   b     b                       ##       #  t   l#  t ##      #        l   # # #  ## ## # #        # #### f  #   #  #
#  ###       ##                       l     t #  t         #       #            # # #  #   # # #        #  #      #   #  #
#    ####      t          #  #       ##l      # t        # #       #              t    #   # # #        #  #t#    #   ## #
######       ##     #     #  #         A   l  #  b l #   # #       #                                    ## #      #   ## #
#    #### b     t   #     #  #                      r#   # ##              ####                         ## # #    #   #  #
#       ###  ##     #     #  ##  # #                        #               ft######  #####          f   # # # l  ##  #  #
#                         # b##  # #  #########             ##          #        #######                 ### #    ##  #  #
###########               #  ##  # #          ##########    ##         t#         t           # # # # t  ## b     #   #  #
##            #######     # l #  # #  ## r   f              t#          ## #   ####           # # # #    ##       #      #
##################   f    #   ## # #                         ##     l   ## #                  # #   #    ##       #      #
#  ###     ##      b    b #   ## # #            # # # #      ##   # #   #b                  # # #   #     #       #      #
#      b             # #  #   #    ##           # # # #      #    # #   #                   # # #   #     #       #      #
#     ######            ###              ######## ###########            b #######          ##    #########        ###  ##
#     ##########      #####    ##     b       ### #######################     b    l        ##    #########        ###  ##
#     ##########      #######  ##             ### #######################                   ###############        ###  ##
#     ##########         ####  ######   t     ###       #################   t               ###############   ##  t#######
#       t                ####  ######         ###  r    #################                   ##   f  ###l      ##   #######
#     g   r        f     ############         ###########################                   ##      ###       ##   #######
##########         l     ############         ###########################              l            ###       ##   #######
##########  l          ##############      t  ###########################                                 b        #######
#################### b ##############a        #########################                                  t               #
#      #############   ##############            ######################   l      f             ##            ########### #
#      #############       ############# t       ######################    b     ########      ##            ########### #
# f    lf    b  c          #############         ######################          ########      ##   ##       ########### #
#       t          c       #####                t######################          ########      ##   ##       ########### #
#   ##   t                 #####                   #################             ########      ## c  f       #############
#   ##    l #########      #####     b   b         ##  #############             ########      ##t     t     ##l     #####
#   ## l    #########      ##### l                 ##  #############       ###   ########   t  ####b         ##      ##c #
#   ##c     #####          #####         ############  ###############     ###      ##### l    ####          ##          #
#    r      #####    g     #####  l ##   ############  ####     ######     ###      #####      ####          ##  c   ##  #
#           ###  l   f    b#####    ##c     r      l   ####     ######     ###      ##              b        ####    #####
#  #####    ###            #####    l                  ####l    ######              ##                       ####    #####
#  #####    ###     ##   g   ###           g       ########A        ##          l   ##       ###          f          #####
#                   ## t     ##### #######b        ########         #######         ##       ###      t           b  #####
#                   ##       ##### #######  ###  l ##########       #######         ##       ###                     c   #
#          ###########       #####      ##  ###t   ##########       #########       ##       ###                         #
#          #######################      #######    #####  ###       #########       ##       ########                    #
#               l#################  l   #######    #####  ###       #########       ##       ########                    #
# ###            ####  ##########################    ###  ###              ##b      ##          #####                    #
#A###t    c       b##  ##########################    ###  ###              ##       ##          #####        c           #
# ###b             ##                ############         ### l        ##  ##    #####                                   #
# ######           ##    l   t       ############         #####        ##  ##r   #####    g          r                   #
# ######           ##       t        ###############      #####        ##  ##    #####      t    #######    r  l         #
# ######       b   ##  l  l  ###     ###############   g         ##    ##  ##    #####   c       #######         b  ######
# ##########                 ###     ####### A  ####    lc       ##    ##        #####           #######l           ######
#     ######tl               ###          ##    ########         ##    ##                   c b b####### l          ######
#     ######                      c       ##    ########      ###########           l            #######            ######
#       ####       b    l           ###         ########      ###########    ######              #######            ######
#c      #### #############          ###         #### b             ###### f  ######              #######              ####
#    b  #### #############                      ####               ######    ######             b####### a            ####
#       ###   ############l         c           ####                   ############                              ##l  ####
#       ### l ############        l#####        ####        ##         ################                          ##   ####
#       #########                  #####    ########     b  ##  b    ##################                   #####  ## ######
# ## ## # ################  ### # ###     #  #      t    l         #      gl         #  # ####   ###### # #####  ## ######
#  l t    ##            #     l # t #  #  #  ##### ###### l        ############ ######     t # b     #t #                #
#  l      ## f  b             l #   #  #  #                          l                 l     #      f#  #           ##   #
#         ##            ## ######   #### ######### ################################# ### ## ## # ## ##  #                #
# ##  # ####                        #### ######### ################################# ### ## ## # ## ##  #               l#
#     #   ################ ##       #     t      #          #l       t     g   #  t# # #             #  #g   #t          #
#    f#   ##                        #            #         c#                  #   #   #             # l#    #           #
#    t#   ### ######                #            #          #t   ####          #   #   #             #  #t   #         c #
#     #   ##  #                     #            #          #    #  #              # ###### ## # ## ###########  ## ######
#  l      ##  #              a      #            #          #    #  #              # ###### ## # ## ###########   # ######
# ##      #####                  ####    t       #          #  ###  #              #                          # #        #
#         ##     l             g #               #          #   a   # tl      t  t #           # ##  ######   #          #
#         ##                     #               #          #       #b       ###   #           #  #  #t       #       #  #
#         #########              #               #          #     l #        # l   #           #  #  #        #       #  #
#         ##                     #               #          t                # c   # ###### ## #### ########### ### ######
#    ##   ###                    #               #                      f   f#     # ###### ## #### ########### ### ######
#    l    ##                     #               #     ###### ##### ######   #     # #  b #  #             b      #      #
#         ##                     #       t       #          #            #   #     #      #  #         b          #      #
# ## ## ################## ### ###               #r         #            #   #     # t    #  #       #  t   t     # #### #
# ##               ##         f                  #          #  f         #   #     ###########       #       t  b      # #
# ##               ##                            #          #            #   #     ###########      b#  #######        # #
# ### #  #######   ##                       ######  t     l #            #   #    b#    #    #                         # #
# ##   l           ####### ####             #             # #    #           #     #    #    #            f            # #
######### #        ##   l     #             #       t     # #t   #       l   #     #    #    #  a            #         # #
#                  ###      f #      b      #         t   #c#    #                 #    #t   #      ########### ### ######
#          ##########         #          t  #             #      #                 #   l            ########### ### ######
#        #         ##  b      #             #             #      #    ##### #####  #                     #        #      #
##########################################################################################################################
