metadata:
  gen_time: 9.39988398551941
  timestamp: '2025-04-18T22:56:38.240258'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#               #    #         ###         #                   ########## ## ###    ## #### #####          bt  ##   b    #
#       ca      t  # # #### l              # ######## ## ## ##########  # ## ##  ##b## #### #####              ##        #
#       ########## # #             #g                               g     ## #   ##            ##          g   ##        #
##  #              #    t  l        ####  ## ## ################ #####  # ## #   ##            ##              ##  l     #
##  # ####    #        ##             r    #### #  ##########  # #  ##### ##    ### b        c             rc  ##        #
##  #          #         ## #######   #                                   ##      f    r      b##  l          f## ########
#               #    l     #           #   #    #b ##########  #g#  ######## #####    b        ##      l       ## ########
###     #       #        r       #     #  ## ## ################ ########### #####       b     ##   g      t   ##   ##   #
#     # #                         #   #   #                        l   f           c           ##              ##   ##   #
#     # #      t           t   f      #    # ####################### ####### ###  #     f      ##          c   ##   ##   #
#     #  #                            #t   ######################### ####### ### ##          r ##r   c    l    ##   ##   #
#     #f  #####             #       #b# #                                          # ################# ### ######  ##### #
#     #        #             #######  #  # # ## #################### #######   ##### ################# ### ######  ##### #
#     #    #  a #     ###   l        l#   ## ## #  ##  ##b ##  ##  #   ##  #   ##       ##     l    c   rc         ##  f #
#     #   #              #        #        # ##                 l                       ##                         ## t  #
##  # #  l#  f #   #      #       #     ###  ## #  ##  ##g ##  ##  #  l##  #   ##       ####### #### ## # # ####   ## # ##
#                                          # ## #################### ####### ######  f  ####### #### ##   # ####   #  # ##
#               #               #     b  l # ##r#################### ####### ######     ##                               #
#    g       b                              g # ##              f                       ## f     r  r    b            ## #
##       b                                    # ## ## #### #### ## #  ## ##  # ## ### ############# # ######### #     ## #
#        g        #                    #   # ##    #   ##   ##   # #   # #   # #r  ## #############   ######### #        #
#      #                  #                     ## #   ##   ##   # #   # # l # #    t l      ##   f     ##c              #
#                                  #       # ## ## ## ####g#### ## #  ## ## A# ## #    t     ##         ##          b  c #
#                 g           r       #       # ##      r        t #  ## ##  # ## #       gt ##    r    ## c    c     lb #
#    #                          #             # ####################  #   #  # #   #######r######### ############  #### ##
##            #                          b # ## ####################  #   #  # #   ####### #######   ############  ###  ##
#                     l     l   r  g       #### #  ##  ##g ##  ##  #  ## ##  # ## #            t    ##     ##            #
#     #  #                                   ##        c   l     b           #          c          l##     ##           l#
#                                 #   r    # ## #  ##  ##  ##  ##  # ######  ######                 ##     ## r        l #
#  #           b      #     b              # ## ########## ## #### # ######  ######                 ##                   #
#                #        #             #    ##               g  b                                  ##  l  ##          g #
#          #                                 # ## #       ##  #      ##   #########         l       ##     ##t      f f  #
#             #                             ##  ###       ##  #      ##   #f       ##### ######## ###############   # ####
#  b   #                      g b          ##    ##       t#  #  g   ##   #   #    ##### ######## ###############  ## ####
#                #            #         t  #     ## ########  #      r#  ##   ##t         l   f               ##        f#
#           r                              #     ##  ###      #   # ###  ##  r##                    c      bf ##         #
#                        #   g             ## ####     ##b    #  ## ### ######### #                   l       ##         #
#                g                             ###      #######  ##   #r            l                         ##         #
#          b   g                               rf#                #  ##        g  b## ###### ############# ######   ##g###
#          #       g                       l    ##        r       #  #      r ####### ######c#############r######  b## ###
# #             #            #      g    #      ##             ####  #       ##       c ##            ##     ##      f   #
#                         #      r       A ######## ##        ##     #       ##     g   ##            ##     ##b     r   #
# g                    #        #                    ##   t   ##     ############## b   ##g        f  ##     ##          #
#        #                      A  t       f          #########       ####         ############ ######### #######  #######
#                #                         #### ###############   #####  ##       ############# ######### #######  #######
#                              #           ####         t     #   # ###b ##       #               tc f    ##           ###
#    l                                        ##       #          # g ## ##   # ##           fb b     a   ##           ###
## r#  l     #        A         t          l  ##       ##   #######    # #   ##                bc         ##          t###
#l       b            #        #              ##   f   ## b #    t        ##t##    ######### ############ ## ####      ###
#                 #           b            ####  t     ##   #   #   g  ## ###### ########### ############ ## ####      ###
#   ##         ##                           #################   ##   t            ###  ##b     ##   ##       ##        ###
#  #   c         #                        a       #####         ##   b #    r     ###  ##      ##   ##  t    ##       f###
#      #   A #                                        ##A       ##    l# f    # ##### b             ##b      ## #   ######
#       # t #          ###   #########       g   ## b  ##r      ##  ####    g##    ##  ##r t   ##   ##       ## #   ######
#r    t    A           ###   #########    f#######     ## ## ###### #        ###   ##  ##     c##   ##       ##         ##
#          f    b      ###   #########  g    ############ ##   b  t ##      ##b## ###  ##b     ##   ##       ## b     f ##
#       #   #          ###   ###   ### f      ## ######## r   #  ###  ###  ##      ### #################  ## ## #  #######
#        # #           ###   ###   ###        ## #            a    #   #  #####    ### #################  ## ## #  #######
#        # #ga      g  ###   ###   ###       ###      ###  t## ## ##  ## b#  ###  #  t         la##          #  #     ## #
#       at#            #########   ###       ###       ##  ##  ## #l      # ## ## #     ##  ##   ##        l #  #     ## #
#    A                 #########   ###b      ###       ##  ##  #      ##       a###b    ##  ##   ##   g      #  #     ## #
#   ##         ##      #########   ###f  t   ###       ## f   ##    ###   #  ## #    l  ##  ##   ##          #  #     ## #
#  #  #       #  # t   ### f ###     g      #####     ###     #  ##r      #             ################# ## #  #  ##### #
#     t            r   ###   ###            #############        ##    ##      ##       ################# ## #  #  ##### #
#  #             #     ###   ###             ###########    f##     ####      ##g                   l  ##                #
# #               # ######   ###   ########  ###    ####         ## ##         # ##     ##             ##          ##r   #
# b                 ######   ###   ########  ##       ###a###  ###   ###         #  f   ##         t ff##b         ##    #
#                   ######   ###   ########  ##           ##   ##    # #f            b  ################### ## ######### #
# #       A       #         l                 #    ########        #t    ## ## ##    g  ################### ## ######### #
##   gat        b  #                          #     #####    #    ##  #  #  #  ##   b          ##     ##            ## r #
#      #     #                                #t    ##### ## ###   ###   t  ##          ##     ##     ##            ##   #
##    #   a   #    ############# g ###        #t    ###   ##  #       t ##              ######### ######## ### ###########
#     #       #    #############   ### l      ##    #         ####          ##a   #     ######### ######## ### ###########
# #r   #     #  t # ############   ###        ##                ##      ##  ##    # l   ##    ##         ft             ##
# #       a b     #    ###         ###        ###        #  ## f   ##g   ##             ##    ##                 ##     ##
##                 #   ###        a###        ###########       ## ##         ###      t##  l ##g                ##     ##
#   #  #     #  #      ###         ###    l   #    ###### ##  ####  t    ##    ##       ##    ######## ### ###############
#    ##       ## a     ###   ##############             #  #  #      ##      ###      c ##ab  ######## ### ###############
###    a          ##   ###   ##############      b  b         g      #     # ## l       ##    ##  ##         ##     ##   #
#  #      #      #     ###   ################          b g ##   g       ####     #      ##    ##  ##         ##     ##  f#
#   g #  r#   #        r                   ########        ##    ###  ###    ##  ##               #       #              #
#    #  r      #  r           l                 #########     #  ##    #     ##  ##   g           #       #     b        #
#                    r                                  #t #####      ## #       #                #    l  #              #
##                 #          b     f  f     ######          #     ####  ## ###    ############   #####   #####   #      #
#     #       #                 l          ##############  ### ## f  #   #### #  ##   #                           #      #
#     a#     #            a      t         #####f      ##   #   #  f     # ## # ##    #     r              l      #      #
#                                         a       t             ## #        #   ###   #        t                  #     l#
#                                a     a    ##         l  #t    ####          ### #   #####   #   #########g  #   ########
#                              l            ##          l #  ##   ## # ##     ##      #f  #   #   #     t     #          #
#                                   lb             fb     ##  #    # ###  f #         #   #   #   #l          # t        #
#                      ### f ###################       ##     ##   #  ##   ##         #   #   #   #           #          #
#                      ###   ############################ ##           #    ##        #   #####   #####g  #########      #
#            A         ###   ##############  ######       # g   ####  ## ## ##  ## b              #           #          #
###            f  ##   ###  l   l  ###                  #        ##   #   #     t           g     #           #          #
# t##  l        ##     ###         ###l   r     #########               a ### ##  #            t  #        b g#    f     #
#    ##a      ##       ###         ###     ########       g     a####       # #l  #   f           #           # f        #
# r    ##   ##      ############   ###g g  ##            #### ##   ##  ##     ##  #               #           #          #
#        ###     f  ############   ###  r  b             # ##  t      b #  ##     l## f   g ##############             f #
#                   ############   ###                  #   #   ### ### ##  #b  l  ##       #########           ##########
#     #       #                      l t      #   l######       ##  ##   # ##      ##   f #####  ####           ##########
#  #   #     #   #     l           a     f    ###########  ##              # g     ## b   ##### f########         ########
###r     l        ##          r               ###       a     ##    ###    #   a   ##     #####  ########        t## r   #
#    #         #    ######   ###   ########   ##t        l ## ##g##   #    ##  ## #############          b               #
#   #    #b#    #   ######   ###   ########   ##    #    ### t     b ##    #####  #############                   ########
#           #       ######   ###   ########   #     ###  #       ##   ##  ## # # ## ###########              l  ##########
###     #   #     ##   ###   ###r   f         #     ###### ##   ##   ###g ##     #  ###########        ######l  ##########
#  ##    # #    ##     ###   ###              #     ###### ##    #   #    g#                    r      ######  l##########
#    #   # #   #       ###  l###              #    #######             f##b#  ## f t   r        l     l######   ##########
##        #        #   #########   ###   a g ##            ###t #    ####  a                     ##             ##########
# g  #         #       #########   ###       ##t     b##   # #####t  ##     #   ##            f  ##    r       t##  ######
#     #       #        #########   ###       ###    #### #       ## f    ####                   t##             ##  ######
#b    #       #        ###   ###   ###       #### ###### # ## f####  ##f ## ##  ###  ######## ###########  t    ##  ######
#   f  #   c #         ###   ###   ###      ##### ######## ##   #   ##           ##  ######## ###########       ##  ######
#      #  b  #         ###   ###   ###      #####   f ###### #### #### ##      f        ##### ###########     b ##  ######
#       # # #          ###   #########       ###       ##  # # #  ## #####f  t     b    #####     #######              ###
#   #           #      ###   #########  g  b ###       ##  r f    #  #   #    l ## ##########     #######              ###
#  #       f     #     ###   #########       ###  t    ##         ##             # ########       #######    r         ###
#  # b           #            aa r           ###      #### ## #a       ##       ##  r######  l    #####   lb     t########
# #               #                           ## #     r ###  #       ### ## ## #    ######  r    #####   l      f########
#                                             ## #######           ##     ## ## ##   ####         ########################
##########################################################################################################################
