metadata:
  gen_time: 7.4618330001831055
  timestamp: '2025-04-18T22:54:03.659696'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# t #           #   #  t#   #         c #           #                c        ag                                         #
#   #           #t  #   #   #           #           #      b            a                  a          a                  #
#   #        f  #   #g  #   #          c#     cf    #           b                           a  b      a        a         #
#   # l #####   #   #  f#   #   #   #####  r#   #   #####                           g               a              a     #
# l #   #       #       #   #   #       #   #   #   #          r                                      l                f #
#   #  t#       #       #   #   #      l#   #   #   #                    r                         g                     #
#g  #   #       #       #  f#   #       #   #f  #   #                   g                            l            l      #
# b #   #########   #####   #####   ##### b #########   #####                                a                      a    #
#         b     #           #                       r                                                                    #
#        t      #           #               t  gl            b  b   r          a      f      r                  a        #
#               #           #                      f                                                    a     g          #
#####   #   #####   #####   #   #   #   #############   #               a                          a                b    #
#     c #           #  l#       #   #       #   #   #   #                                  a  b                  a       #
#       # l   c     #   #       #   #     l #   #   #  r#             g  b   A                 a       b                 #
#       #           #g  #     A #   #  c    #   #   #   #            a              t               r                   b#
#   #   #   ######### f #################   #r  #   #   #####t                               a                           #
# b #   #       #                                   #   c     r         l  r             l                               #
#   #   #       #         r    t                    #                  g                                   g             #
#   #   #       #    g           t               cfb#  b                       a       lb                    a           #
#####   #####  t#####  t#####   #########   #########   #   t                    g    l                               b  #
#           #   #       #      t# l   b  c  #   #r  #   #           a                         l     r               A    #
#           #   #       #       #           #  f#   #   #                              b                                 #
#      t    # t #      l#     g #           # f #  c#   #    t                                                    a      #
#####   ######### rf######### fc#   #   #   #   #   #   #####                        g    a                              #
#       #        lgg#  t#   #   #   #   #   #  l  b #    c              g         a          g          t       g        #
#    l  #   #       #   #   #   #  t#   #   #t      #                              l              l l     l              #
#       #  l#       #   #   #   #   #   #  c#     l #                c                      a       c       r       a  a #
#####   #   #   #####   #   #   #########   #   #############                                         g             l    #
#           #       #l    t             #      l                                                                         #
#           #       #       b          l#             t                 aa                                b   b     l    #
#           #       #  b    t           #                 r l       a  g                     r      ca                 a #
#########   ######### r #####   #   #   #############   #####                      a               c            a        #
#   #           #       #       #   #   #   #                            a           a                  a t a          g #
#   #   g       #       #       #   #   #   #                          a          b    g           A                     #
# f #           # b     #       #   #   #   #                                       g             l                      #
#   #   ##### r #   #   #################   #   #   #########       r                                                    #
#           #   #   #             f             #                l             b         a                               #
#           #   #   #           #b              #g                                                                       #
# l         #   #   #           #     l       f #        f                                                   bc          #
#       t   #f  #   #           #   t           #                                                             a          #
#  #####     ###   #           #l ##  #############  # ##        r###r###     ###         ###         ###  f        f    #
#   #    g    ##   # #### ##  ###              g  ## #  ##   #### ### ### ########### ####### ########### ### ########  ##
#  ##  # # #  #            #       r               ###   ##  #### ### ### ########### ####### ########### ### ########  ##
#          r              ### ### ## # # ### ########     ## #### ### ### ########### ####### ########### ### ########  ##
#  ## ## ###  #### # #### #            #      #            ##     ###     r               r   ###         ###            #
#        # l         #               #     # ## r   l       # ### ### ##  ### ####### ##  ### ### #### ## ####### ###    #
#   t          l # # ##              #    ##      g           ### ### ##  ### ####### ##  ### ###g#### ## ####### ###    #
#  ## ## ###  ####    ##      g           #   t ##          #  ## ### ##  ##  ####### ##  ### ### #### ## ####### ###    #
#  #   #              l##               t #     r## ##   ####     ###             ###  c          ###         ###        #
#          t            #          #    g ##      # #    #  g ### ### ##  ### ### ### ## ####   ###### ## ####### ####  ##
#  #                      #     g  #       #    ###          g### ### ##  ### ### ### ## #### # ###### ## ####### ####  ##
#  #   # ###  #### #  ### ### ###  #       t # #              ### ### ##  ### ### ### ## #### #   #### ## ####### ####  ##
#  #  ##           # #          #  #    #### # ##        l   g### ### ##      ###g###         ### ###  b     b###        #
#  #  #            # ##        ##      ##       ##            ### ### ##  ### ##########  ### ### ###  ## ### ### ####  ##
#  #  #               #r       #     r # g   l   ##         b ### ### ##  ### ##########  ### ### ###  ## ### ### ####  ##
#  #  ##              #        #  l  # #          #           ### ### ##  ### ##########  ### ### ###  ## ### ### ####  ##
#  #   #           # ##        ##    #       l      #             r                              c###r    ###     g      #
#  #     #         # #         ##      #   # ###### ##   ####         f    l     t   f        b   ###     ###            #
#  #     ###  # ## #            #      #####   ##    #   ##   b                    ggf            ###     ###      f     #
#             r #    l   g  # ##  #l    #                                        b                ###     ###b  r        #
#  #           ### # ########   r ## # ##### ###### ##   ####        A                    l     a ###     ###       br   #
#  ##  t      ##     # l                     #       #       f    r f  g       ff                 ###  g   ##     c l   g#
#   #      #             l                   ###### ##      t                    lc        bb r   ###      ##       b    #
#     #    #                # ######   #####     ##  l   #                                        ###    r ##   r        #
#   l ##   #       # ########     ##   #          r      #  # ### ### ##  ### ########### ### ### ###  ### ## ### ####  ##
#      #   #   g   #   l##       ##          f  l        #  # ### ### ##  ### ########### ### ### ###  ### ## ### ####  ##
#        # #  #    #             #                       #  # ### ### ##  ### ########### ### ### ###  ### ## ### ####  ##
#        ###  ##     #           #                       #  # ### ### ##      ### ###         ### ###         ###        #
#   c     ##   ##    ##          ##        g            ## g#r####### ##  ### ### ########### ######## ## # ##### ####  ##
#   # ## ##     ##    ##          ##         ###### #   ##  # ####### ##  ### ### ########### ######## ## # ##### ####  ##
#  ##     g      #     ##   ########    #### ##     ##  #   # ####### ##  ##  ### ########### ######## ## # ##### ####  ##
#  ##### #### #### l    ######         ##                         ###             ###             ###     f   ###        #
#                                      ##### ###### ##  ##### ####### ##  #   ########### ####### #### ## ###########b   #
#  ##### #  r #### # ############            g#               ####### ##  # # ########### ####### #### ## ###########    #
#  A     ## #          ##      ##### # ##### ###### ##  ##### ####### ##  # # ########### ####### #### ## ###########  br#
# ######  ###                      r #               #    #    c  ###  l       r        b     ###    g  b ###            #
#         # #   ## # ################# ##### r   ## ### ######### ### ### ########### ####### ######## ## ### ######## ###
#         # #  ##       ##      #         ###   #     #      #### ### ### ########### #######l######## ##c### ######## ###
#         # #  #            ######   g   ## ### ##   ############ ### ### ########### ####### ######## ## ###g######## ###
#        ## #  #     ########    ##      #  # #  ## ##        r   ### ###bb  g### b       ###          ##                #
#     #  #           ######## b  ##### ### a        #  #    ###    l ##      l###     ########  # # #          #   #     #
#  ##l   #b    ##          ##    ##b         ##     #    ## ####      ##### # #    g            # # #        b # ###     #
# t##                  t                      tb         ##    #            # # #        #####  # # #  ##### ### #       #
# ####                ##r    ####      #             r  ###### ########     # # #           l     # #  #   # l   # ###   #
# #      # ##  ### #  ##               # ########## #      #    ########      # #               ### #  #   ###   # #     #
# ##  ## ###r   ##   ##        t       ### g##    ######  ##           #      # #                 l #  #         # #     #
# ##  ##   #    ##       t                  ## r  #   ##  ##    #### t ####   #                     #      ##### # #     #
# ##b  #   #    ## # ######        ### #### ####  #  ##   ##    #  #b  t      #       rt #          #      #    t        #
# #      b ## #  ###  #  #          #  #  ### ## ##      br#    #  #                     #       ####      #r          ###
# ##        #   g  #  ## ##  ####  ##  #  #      #        ##    # t#f          l l  ##                     #             #
# ##        ###  b    l#  #  ####  #           ###   #    ##    #          ####          ### #####         #   b        ##
# ##   #    ###r       #     ####        a     ###   ##   ##                          r      #          #  #    ## r     #
# ##        #          ##    ####    #           #   #    ##    fb     b   ########          #          #            b   #
# #   ##    ##    #  ###     #  #      ##  #    ##   ###   #              ##         r    ####          #l           t   #
###   ## f  ##   ### #        t         #####   ##   ###   ##             ## ###    t          t       ##      ##  b # ###
##    #     ##   #       ###      ###       #   ##     #    # b           ## #           g                               #
#   #     A  #   ##    r ####    ####  a   ##   #       a#     l   ########  #                r        #####   ##r   # # #
#   #  b ##  ##  #          #    #          #  ##  ##    # t       #         #     r      # #    ### #               #  b#
##  ## r     ##         ##          ##         ##  lg   ##  #     l# ######  #      ###   # #l       # c          b  #   #
##  #        ###     ## ##r  b## b  ## ##    b###a       #  #      # #       #   # ##     # #        #               #   #
#            r    #   ####    ##    ## #   #                       # #       #   # ##     # #        #               #   #
#l        ##      #  ###     ####      ##  #   l  ##               # ######  #     g###   # #        #        f      #   #
##   ### ##       ## #                  # ##       ######   #  A   #   l     #          g # #    ### #        r      #  g#
###  ### b        ## ##   ####  ####   ## ##          ###  ##      ########  #            t            #####   ##    ### #
# # b  ##   ##       ##l    ##  ##     ##       ##b  ##A   #     b        ## #                            t              #
# ###                ##                ##                ###              ## ### t      b    bb        ##  r   ##b   #####
# # ###   #b r     # ##  ###      ###  ## #        #   ### #    r         ##              ####          #             b  #
# #       #  g ##### #   ##   ## b ##   #######    #       #               ########   b      #       b  #                #
#        ##     ##   ##                ###  ##     ##                                        #  A       #  #    ##       #
#      # ##     ##        ###    ###     t  ##     ## #         #          ####          ### #####         #      t     ##
#  ### #     #t ##                          ## r#     # ###     #  #              b ##                     #             #
###### r   ###  ##   ####r    b  rg  # ###  ##  ###  b  #####   #  #                     #     t ####      #          ####
# #      #####  #     ##   ########    #b    #  #####   la #    #  #          #          #          #      #             #
#         #     #     ##               #     #     #            ####   ####   #            b        #      ##### # #  #  #
# rt      ##    #     # g####    ####  #     #    ##             b     #  t   # #        r   r      #  #      r  # #  #  #
####       #  b #    ##  ####    ####  ##    #    #       ###   ########      # #t   b  t       ### #  #   ###   # #     #
# #    r ####  ## ## ## ##    ##    ## ## ## ##  ####      # # ########     # # #                 # #  #   #     # ####  #
#     ####     ## #     ##    ##    ##  r ## ##     ####       #            # # #        #####  # # #  ##### ### #       #
#             ##  # ##  ##  ######  ##  ####  ##         a   ###      ##### # #           r     # #l           # ###     #
#      ####    # b# #   ##  ######  ##   #t#  #    ####      ##      ##       ###     ########  # #            #   #     #
##########################################################################################################################
