metadata:
  gen_time: 5.695631980895996
  timestamp: '2025-04-18T22:55:25.526111'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
### ## #      #           l     ## ##                       ##                     a                   ##                #
# # #            ## ##   f         g     ##      r          ##                 a                 c b   ##     r          #
#                 # #     # #   ## ##     #                 ##        b                                ##             c  #
#          # #           ## ##   # #                 c      ##        b            b      Ac           ##      l  c      #
#         ## ##     g                                       ##             l     a                   l ##        b       #
#                        ## ##        b                r                      b      g                      A     t    l #
#   # #   ## ##           # #               ############### ## #######################################r## ################
#  ## ##   #r#                     tg       ############### ## ####################################### ## ################
#  t  b     r                                                                 b                                    r     #
#  ## ##              # #     f                             ##           b                  b          ##                #
#   # #t          b  ## ##            # #                   ##                    r  l             b   ##   r    r       #
#                  l        t  # #   ## ## gb r  b          ##                                         ##g       b l     #
#                    ## ## t  ## ##                         ##          a                              ##r             l #
#        r            # #            ## ##                  ## a             r                         ##        l       #
#                    r        ## ##   # #                   ##                  b   a                  ##                #
#         # #                  # #      tr                  ##       g                                 ##                #
#        ## ##          # #                  r              ##    c                                    ##                #
#                # #   ## ##          r                 rf  ##                        t                ##                #
## #     ## ##  ## ##              f                        ##              rl                         ##                #
## ##     # #          ## ##        # #          c          ##                l                        ##         b      #
#          tf   ## ##   # #  r     ## ##                b   ##                                         ##                #
## ##            # #   f     f             #                 f                                          r    r           #
## #     r             r l   r     ## ##  ################# ## ####################################### ## ################
#          # #               b      # #     ############### ## ####################################### ## ################
#         ## ##                   g     b ##                                        a                            r       #
#                        g                 #           g    ##                        r                ##                #
#        g## ##         f    t                              ##                t                      l ##                #
#          # #     # #    # #      g         r           g  ##  f        b                bl           ##                #
#          rcr    ## ##  ## ##            # l               ##                     r                   ##       r        #
#                                 # #    ##                 ##    l      a                            a##                #
#       #  ### r        ####  l                  ####    ###      ###t  ###    t#######    ###    b #####   a            #
#         t ##   ##     ####     ##      #       t##    ###        # t ###      a  t  l         b    ###      #####      #
#  ##    t   r l#####    ##    #####    ####            ###    t       ###t                                  #######  b###
#  ##       r    #####         #####    ####           ###    ##     t###f            ###     ###      r     #######  ####
#         ##       ##        g  ##f      #              ##    ##    t  ##   ##       #####   #####    ####    #####   ####
#         ##             l       f       l    ##  ##     l               f   ##br    #####   #####   ######            ###
###                                   #     ##########        r              ###  t  ####     ###   t#######            ##
####          ## c ##     #          ###    ############          ## r   l   ####     ##        b     ######   ##        #
####  cf## t  ##   ##   ####    ##  r###c    ##  #  ####  f  #   ###         #####              g   f  ####   ####    b  #
# #     ###            #####c   ## l###               #    ####   ###        ######        ##     ##          ##### f    #
#      ###              ##          ###                    #### f ###        #######      ####  r####         #####     ##
#   g  l##    r##                r   #       a   c          ##   ###  t   ## ########     #####  ####          ###      ##
#           t######f           ##c    f   ##        ##      ##   ###     #############    #####   ##     ##             ##
#  ##        ########     ##   ##         ##        ###g   rf     ###  g  ## ##########    ###          ####             #
#  ##         #  #####  #####                      #### g         ###        ###########                ####    ######   #
#    t             ##   #####      ##           c   ##f  ##        #        r############       ##  A    ##    ########  #
#       ##           l   ##      #####   ##  c##         ##   ##    t  l   ###############     ####f           ########  #
#     #####               l      #####   ##  #####            ##  lfr     #################   ######   t      b ######   #
###t  ####     ##   ##          f ##          #####  A                     ## #############   ####### g   ##             #
####   #     #####  ##                  c       ##                            f###########    ########   ####      g     #
###          #####        ##          ##  l           ##     ##     ## b      b           b   ######### t#####    ##     #
#            r##         #####      ######c          #####   ##  A######           a          #########  ######  ####    #
#        ##    l    ##   #####  f   #######      ##  #####        #######l        g          t ########  ######  #####  ##
#      #####        ##  t ##   l##   # t##c      ##    ##         c#  ##         ####           #######   ####    ####  ##
#      #####                 cl ##            g c        b    ##   a       ###  ######    ###    #####             ##    #
#l  g   ##      ##   l           c                          #####          ###  ######   #####    ###                    #
#               ##  ## f   A                 ##   ##   t    #####      ##    #   ####    ######g        ####    b        #
#t ##               ##                ##   #####  ##      c  ##    t   ##t   #           ######        ######     ###    #
# t## r          g            ##c     ##   #####        #                   t             ####         ######    #####   #
#     l  ##     #  c         ####      g    ##         ####       ##      f       f b  t            r  #####t    #####   #
#       ####  ####           ####    t                 #####     #####         ###b           f         ###       ###    #
#  ##    ##   ####      g     ##    ##          f        ##     a #####       #####             ##      f          l  l  #
# ###      a   ##             f    ####    ##      ##               ##        #####f     r     ####r       b           ###
#  ###         ##      ##           ##     ###  t  ##         ##               ###       t     #####   ##    #####    ####
#  ###   gg#        lgf###                ####          ##    ###                      ###r     ####  ####  #######   ####
#   #    ####         ####              f ###           ##   ####     ##         t   r#####      ##   ####  #######    ###
# l      ####        r ##                  ##   ##  ##       ###   l #####            ######  b        ##    #####   b   #
# f       ##     #               ##          b  ##  ##        ##   g  ######          #######              c    tt       #
#  l #    ##   ####     c       #####                    ##             #####   t   b b######      t                 #####
#  ####cg####  ####              #####     ##   c       #### g    ##      ###   ###     ####        ###    ##       ######
#  ####  ####   ##                 ##  r  r##   ##       ##     #####   g   #  #####  r            #####  ####      ######
#   ##    ##  f ##           ##     l    c    f ##l    l        #####          ######            t #####t #####     ######
#   ## f  ##   ####   ##   ######         g   g                  ##             ######   #####     #####  ######    ######
#    t   ####   ###  ###   ######    f  ##  ##              ##         t ##      #####  #######r    ###  t#######    #####
#  ####           #### # #  ####   #           r   #### f####   #######   ####  ####                #                    #
#  ####      c    a##      b       #     ####r     ####         #######         ####     t          #                    #
#c #### #####     ####  ##  ####l  #                            r    l      r        g              #                r   #
#  #### ########  ####  ##  ####      #      f                    r    f   g                      l #           # ##     #
#  #### #########a##          ## #    #         ###############         ###############             ## ##   f t #  #     #
# c#### ##########################              ###############         ###############                 #       #  #     #
#  ####     ###################### #######     r###############         ###############                 #       ####     #
#  ####     ##### # # # ##r#  t# #   #      ###################  #####  ###############       ## ##     #                #
#    c   #######            t                #          r        #####   r             ###    #   #     #l               #
#################a  #   ##   #   ### ##                                                  #    #   # r   #############    #
####           ##                ##  #  r             gf                                      #   #                 #    #
####        c       a        t            ####    ##############       ##############    #    #   #           r     #    #
#           ####   #    ##    #   ## #### #       ##############       ##############  b ######   #          ## ##  #    #
#     ##   c####    g #    #       # b#        l  ##############   #   ##############r            #       l  #   #  #  c #
#    c####  #####  #      f   #  #        ##   # f##############       ##############             #  l       #   #  #    #
#     ####b ####                          #   ##  ##############       ##############r  ######    ####      r## ##  #    #
#     a    A    #  # #   f  # #  #  r  #  #                                         b   #    #       #              # r  #
#  #         # c                  ###  # ##    t                                                     #              #    #
#  ##       ##     #          #   f    #  #         g            #####  f  g        g   #    #       #              #    #
#   #  ###  #    #b             # l    #        ###############  #####  ############### ######       #              #    #
#   #  # # a#                  a    #  #     t  ###############      g  ###############              ## ##          #    #
#          r  r      ##    ##       # l         ###############         ###############                  #          #### #
#          c a  #  #          # f#  #         #################   f     ############### r   l          l #             # #
#t     ###      #  #          #  #  #          l              f               r     g                   l#  tb         # #
##  ## l   ##  #     ##    ##       #  #       f                              tr                         #             # #
################              a     #  #    #      ####         #######     g   ####   f                 ## ##         # #
#####   #   #### #              #         ###      ####  ####   ####### l ####  ####                         # l       ###
##c            # b #      A   #                 #            ### t  ###    ##  ###      ## bt ###   l  ##      ###########
#      ###                                      #          l ###    ###         ##      ##   ####      ##      ###########
#f r  #####c    #  # #      # #  # t       t   l##            #      #                  #########      ###           #####
#  ##g  #   ##b                      ###        #  b    ##                    b          ########     ###### ####     ####
#  ##   #   ##  #t #  a       #  #   c#     #         #####      #           ##      l  b####### r    #####   ###      ###
#     #####   c       #    #                ##        #####   t####     A  ######       f #####    lb ##       ### l     #
#      ###         #    ##    #ag   ####    #     ##   ##      ####       ########   f     ####       ##  t              #
##             #                                  ## g          ## t       ##  ##           ##        ## ##### ## ########
#####  c#   #####                #                          b   ##    ##            l                 ## ##### ##  #######
###### ##########   #   ##   #   #                             ####   ##             l                ##     #  ##     ###
## a##     ##  #                               ###          c   ##  b      ##g     t      f           ######### ##########
#  c   ###      # # #a# ## # #A# #       l      ###    ##       ##         ##    #          ##        ######### ##########
#       l       ####### ########## ##   #       ##   #####     ####   ##         #         ####      r##     t           #
#   t           ####### ########## #    #b##   #   b ####      ####   ##                  #####                ###       #
#   #  # #  #   # ##          ## #      #             #         #          ## r          #######      #####b  ###      ###
#   #t ###  #     ####  ##  ####        #       ##       b    l           #####          ########     ###### #### b   ####
#  ##       ##    ####  ##  ####   #          # ##          #     r        ######       #########  l   ###   r ##    #####
#  #        r#c    ##        ##    #          # #        f####    ##         #####           ####      ##      ###########
#   b         c fl#### #### ####   ##         # #    ##   ####  #####          ##          f  ###      ##      ###########
##########################################################################################################################
