metadata:
  gen_time: 11.009307146072388
  timestamp: '2025-04-18T22:47:39.100467'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
########  ###    ###     ### #        #           #    #   #  ## t        # # #       #                                 ##
#########  ##    ##       ## # # ######           # #### # ## #    a      #   #    #  #      a## #########################
##   ##### ##    ##    f#      #   ##               ##   #            r#  #   #     # # #   aa############################
#          ##### ###g l ###  t # ######           ###### #             #      #   r      # #       A                     #
#          #####    ### ####                                  #    a   #      #            #  ## ###################### ##
#                 # ### ####             #   r #            t#    l#a  # #########    #    #  ## #  ##  ##  ##############
#                                 b      #     #                #c  #    a    #        #   a  ##             #       ##fr#
#  f      ###              b f   t   ### ### ### ###           #  a           #  #        a   ## #  ##  ##  ## ## ##g## ##
#t        ## t  #########  #    t    #  #  # #  #  #          g         a #   #  a#       #    #                        ##
###       ##   #############   ### # # ### ### ### # # ###   ###      # f #   # r          #   # ############# #   # ## ##
########  ##   #############   #   #                ##   #    la   b # a  #g#a# #   ####    a ## ## b##  ##  # ## ## ## ##
############   ############# # # # # ###  f   b  ###   # # #   #       g##########               #   r         ## ## ##r##
#  ######### f ##  f#######  ##  ##  #    #   #    #   #  ##  ###a ###a  # # # #    #  #      #####      ##  # ## #   # ##
#    ############            # #   #      #   #    # # # # #   # a         #   #   t#  #      #####  ######### ## #   # ##
#   l  ########                #   ## t             ##  ##                 #   # #############                  # ## ## ##
#            g  #########      # # # ###  #####f ### # # #          #f    b#        #  #       ################ #       ##
#t                             gb#   #             #   #     #       #b    #  a     #  #      ################# ##########
########g     t ############t  ### ### # t       # ### ###      f         g      #   r #a   #  ##        l         #######
############################   #  #   ##         ##   #  #               t  c    #     #     # ## ##g## ## #### #        #
####################  l    #   # ### # #         # # ### #       #         #g  #####   #  a     #f#   # #   ##   # ## ## #
####################         b       #          f  #  f         ###  #  a   #    #     #   # a    #   # #   ##   # ## #  #
#                            g g     #    b        #             #    # a        #     #    #a ## ## ## ## #### ## ## # b#
#  ####      ##   ###    f#####               f t         ###         a     ########   #      ###g## ##            ## ## #
#  ####      ##   ##      ##                              a#        A            #          ## ## ## ## ## #### ## ## ## #
#   ###    r ###  ##      ###f###     r            b    ### #          #c    b   #   #                                   #
#   ###     ########      ##    f                         #    #        # #         ###         # #   # #   ##   # #   # #
#   ###     ########    f g####               t           ### ###         #t   ###   #         ## ## ## ## ####r## ##a##f#
####################      ###      #          f      #      #  #      # a #      a         #  ###       b      g         #
######################   g### ###f #     A           #  ### #        ##              ####   #  ### ######### ###  ####  ##
######l                       #    b   #         #    g   #           #####   #        a                               ###
### b     #        ######     # ####   #         #   #### ###    ######   g    #   #    #     ####           a           #
#        ##   t   b###### #     ##     #   # #   #     ##   # #       ##          g #    #    #  # ## ## ## ## #### ## ###
#    lb  ###   ########   #   # ## #   #   # #   #   #### # ####      #   #            t           ## #   # #   ##   # # #
#    A   ##############l ##   #    #                 #    ##               #    ar    ####    #a # ## #   # #   ##   #   #
#         #################   # #  #                 #  # # ##  a ###        a#     ac      # #### ## ## ## ## ####     ##
#         #################    ##  ### ### r   ###b###  ##  ## a   A        a  #      #      #     ##f                f###
#         ####  ### f #####   # #    #f#         # #    # # #         a              ##       ################ ###  ######
#  b       ###        g  ### ##   f  ###         # #      #     aa #      #           ######  ####### ############ #######
#          ###  l   f   l#### # #    # #         # #    # # #     #        #    l  ####    l                   #        r#
#       b  ###       b   ####  ##  ### ###     ### ###  ##  #                         ##g     ## #############    ########
#          ###            ### # #  # b               #  # # #  #### a    b            #      a## #  ##  ###  #  # #  ##b #
#b       b#####    g t    #   #    #                 #    ##                #####             ##                #        #
#         ##############      # ####   #   # #   #  r#### #    #     #                        ##f#  ##  ###  #    #  ## f#
#        ###################   ###     #   # #   #     ###  # ###     #        a#      #      ## ############# ## ########
#        #######     #######  # ####  g#         #   #### ###a #   #  ar    #   l#  #   #  #  ##                         #
#r   l  ########              #   f    #         #        #        #     af  #      #       # ##r## ### ## ###### ## ## ##
#       ########   t  ###   # ###  #  f             f#  ### ####               f              ## #   #####################
#      ##################l  #      #  g              #      # ###     ###       r ### ###   r  # #             #         #
#      ###################  ###                           ### ####### ####### ####### ###            ##              f   #
## #########    ###    ###g   #               g           #   ####### ####### ####### ###                ## #    #      b#
############ft   ##    ###### ###                       ### # ####### ####### ####### ###   ###########   # #     #      #
#   ###  ###     ##### #####                  b            #          r           ###               l     # #   ##########
#  b###   ###   ###### ########                           ################### ###########        ######   # #   ##########
#    ##   ###            ###         #             #         ################ ###########  t###       #   # #         #  #
#    ###   ##f  ######     t         #             #         ################ ###########        ##       #    ###       #
#    ###   ###########         # ### # #         # # ### #        ### ###         ###            ##c      #             ##
#     ###  ###########  r      #  #   ##         ##   #  #    ### ### ####### ####### ######     ##       ##             #
#     ###                 b    ###  ## #         # ###  ##    ### ### ####### ####### #######     f             ##### ####
#  ######   ###   #####   r      #   #             #   #    f ### ### ####### ####### ####### # ####    ####        # ####
# #####################b b     # # # ###  #####  ### # # #    ### ###                       # # ####l               f    #
# ######## ############        ##  ##              l##  ##   #### #######r####### #######  l# #                          #
#  ##g ##      ### t###      # # # #      #   #      # #   # #### #######t####### #######     ######     f ##    ####### #
#           g   ##         # ##g #  f#    #   #    # b##  ## #### ####### ####### #######                   #          # #
#      # ###  c ##   ##    # # # # # ###         ### # # # #                  ###     ###     ##                #####    #
#     ## #### ####  b##    #   #   #   f            ##  l#    ### ########### ##############       #####        #####    #
# t   ## #### #####  ##    #   ### #   ### ### ### # # ###    ### ########### ##############               #  l ##      ##
#    ###        ###  ##    #   b     #  #  # #  #  #          ### ########### #########################    #    ## ##    #
#    ###         ###########         ### ### ### ###          ### ###    b### l             b              #    ## #    ##
#    ### ###     ###########             #     #        bb   g### ### #######r########### r           g l  #    ## #     #
#    ### ###  ######   #####             #     #           f  ### ### ####### ###########r                 # #     ##    #
#    ### ###  ######      ##                                  ### ### ####### ###########  l   #     ##    # #           #
#    ### ##       ##       #   # ######           ###### #   l### ###             ###        # #   # ##    # ##    ##    #
# # ####          #  lt    #   #   ##   t           ##   #    ### ###t          g ###        #f#  ## ##    #  r          #
# # ####          ##g b     ## # ######           ###### # ## ### ###          r  ###        A #      b    ##########   ##
#   ###          ###       #     #    #    b      #    #      ### ###     t       ###  g     #a#        f                #
#        #   ##          #    ##   ####    #### #   # ## ## ## ## ###   ##  #  #t  #                       ##            #
#            ###  gl     t ## #   ##          #  ## #   ####   #  #### # # ##  ##  ##                   #####           ##
#                c   #      # ##       ###  #### ###   ######   ##   ###   #  #     ##   ##             ## ## ##         #
#                            ##  ###     #  ##  #                  # # # # # ###         ##                   ##         #
#   g    t       g            #  ##   f    ##   #       g          ##b   #  ##    r      ##         l      ##  #   #     #
#            b               ###           #     t                   ### ###   #     ##  ##                ##          r #
#  ##     t                  #      # # ##                     b      #    #  ##     ##  #                ###            #
#  ##   #                A   # ## ### # #               #  #        ## ### ###        #        b          ###            #
#  ##  g#  #                 # ## #bl   ##  ##l#       ##  ##       #        #  #             ###       # ##         f  ##
#     b            l  ## ####  #     ##  #  ####  ###  ##  ##t ###   ### ### ###           b  ##           #            ##
#            ##    l ##  #######      # ## l#f## ###   #    #   ###   #        #   f         ##    g      ##             #
##           ##       #    ##      #     ## #  ####           l  ####  ### ### ##                  b      #   A      r   #
## ###      c         #       ##   ###  g#           g b             #    #                               ##             #
##             g      #       #     lf       ##       #      #       ### ###t###  r        ####         g  #            ##
#            ct#      #  #   ##    ##       ##       g##    ##         #     #              ##r         # ##            ##
#      t      r       # ##   ## #   #  ##    # #      ##     #         ### ### ## t         l             ###            #
#   ##  ##  #       g # ##      #  ## ##  t    #        #### #           #l#                         A    ###            #
#   ###     #    #    # ##      ##  #####  ##        b ######            ###           ##               g a##            #
#   ###            l# # ## ##   ## ###   f  ## l                         #              ##                 ##  #   #     #
#   ##              # # ##       # #       ####  #     ######   ###      # ###          ##       l         b  ##l        #
#  l f            ### #   t  ### ### #  #### r####  #   ####     ###      l  #          ##   r b   l    ## ## ##         #
#        l            #        ###   #    #    ### ##g   ##       ##         ###g##     #t    #  l      #####       a   ##
#    #       #               #     ###  # ##  ### ###t         ### ## ###            ## #     ########     ##       r    #
#      b### ### g      #  ## #   ####  ##g        ##            ##  t        ###       f# ##         #    ##         ##  #
# ###   ###   c       ##    b##      f #  #      ##t            f##          #       #  #  #    #    #   f##         ##  #
#       #             ##  #####   ####   g#      #               t#      # ### t rl  #  #  #    ######    ##         ##  #
#t  # ###              b ###  ## ## ##    ##             t          g    # #     #   #  # ##          l   ##         ##  #
#    b# ##        b     t###   ###  l#     ##             l  f          l###     #   #  #                                #
#  ##   ##              ####   #       # #####     #            #    t   # #     #####  #g    ##########    t            #
##          ## c ####  l####      ##   #     r  # ##            ##f#   ### ### ##l      #     #         ####         #####
##      g   ##          ###  l    ##        ##f # ##        g   ##f#  r#     #    #     #  f            ####  f      #####
##    #     ##g        ###g        # ##     ## #   #           b#    ### ### ###  #######   ###########                  #
##  t           ##      b#    # #      r    #  #   A                 #    #               t   f       #              g   #
#               ## g     #   ####   ## ## g    #                  tf## ###  ## ##           #         #                  #
##  ##  ##      ## t     #  #  ##   #  ##     ##     r                    f    # ##         #  l   ####      r           #
#   #   ###              #  #   #g  ##        #         ####         ### ### ###  #      ####      #                     #
#####     # t ###    ##  # ##                 g          ##  r      #    l      # #      #g      f #            f r      #
#####b    ###     ####     #    ###    ##                           ## ### ### #  # ##   #         #    ####         #####
#####     #   ##  #    ##    # ## ### ##     ###                      #    #b  #  #  #   # t       #    ####        b#####
#####             ## ####    #### # #        ##         #  #         ### ###   #  #  #   #         #  ##                 #
#####   ##     #        #     l     #  #   #           ##  ##       #       ##    #  #   #   #######  #      t   b       #
## ##   ##    b         #        ##    #   #           ##  ## t    b # # # # ###  #  #   #   #        #   ##l        ##  #
#       ###     #    #### #       #   ##  ##            #  #         # #  ##      #  #   #   #    g   #   ##      b  ##  #
#       #            ###     # #  ##  #      #####  #          #  #### #   ###  # ####   #####  t  ## #   ##  r      ##  #
#      b#    #        ##     g #     ## ##      #   ##        ##   ##   ##  #  #                   #  #   ##         ##  #
##########################################################################################################################
