metadata:
  gen_time: 18.3679518699646
  timestamp: '2025-04-18T22:57:09.825020'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#      #     l ##     rg ###        #  #   b#           ##     ##    ##        ##    c  ##      #    ####        ###     #
#    ###  b ##  # ####     ###   ##      l  #g      ##  r#    ### ##  #    ##  ## #  ## g    ####   b r##       ##     ###
#                 r #  ##   #l   ####      ##     #### ### # ##   ## ##   r    #r #  ## g ##  #         # #r     # ###  b#
# g    ## # b ##                 # #       ##      # ###   ###  ###   ## #    ###         t#  ### t  #  # #     ## #    ##
#       # #    ##     #     f               ##              ##  #        ##   #f   ##  ##l      ### ##  ###  ####  ###  ##
# #    l###    #    ####   ##  l     ###   f #    #g ########  r##    g g## l ##  r         ##      # ff    ## g  f  #   #
# ##     ## #        #    b #  ########   ## ##        ##  #   ##       ##    ## ##  ##   ###   ## ## ##         ## ## # #
#  #    ##g #b ####  ## ##    ## ##      ### ### #     t# ##   #         #  # #  ##      tg#       ## ##  ### #  #  ## ###
# ##     #g##  l##  l##       #   ##   t##       #        #    ##    #####  ###  #  ###   ##      ##      #   ##       ###
#  ##     l ##       #       ##   #     #f    b####               #    ##    ##  ## ##   ##  ##    # #### ##  ####  ## r #
# ###       #   ##                ## fb        ##           ##  ###  ###  r      ####  g    t     ## ## #        #       #
### ## ##  ##   #           #### ##    # t## #g    ###   a          r #    ##      ##       #  ##  ###      ##      #    #
##      #  ##               ##   #   # #       # ### ## #     #### ## ##  t##    ###   ##r# #l #    ## ##        #####a  #
## ###  ##      #### # ## f  ## ##  ##   #  ## ### # ## # ###### ###      ##     ##   ##  ###     ###  #      ##   #    g#
#        #   ##t ##  ###    ##### f  ##  ##f ###   #      ## #         l#####          #   ##  t  a                  ### #
#      ###        ##  ## ####  ##         g      b ##    r#  ##      #### b        ######     ##     ###  ##  ##   ####  #
#          ## ##  #####   ##  ##     # ##  ##  r#  ##     l  ###  f   ##  ##   ## ### #    ## #  # ### ## b   #          #
##       ####   f    #     ## # f ######   ## ###   #       ## ## ##   r  #     # #     #   #    ###        l##    ##g ###
####     ##f  ##b ##b##    #    b  ##      #  #    ##   gb   # ## # l        #f   ## f  ##        ###  ### ####     b  f##
# #            f      t           ##       # ###    ##   r ###  #        ##  ###  ##        ###  ## # ##   ## ##   # #####
#        ##   ##    ## # ##          f b     #    ##### #  #      ###     ##  #      #    ### ##  # ###  ###     ### #   #
#  ### ###    #    f   ####  ## #         #          g#####  ###  # #         ##   ###    # # ##    ##    #      ##      #
# #  ###          ##  ##        #         ##   ##  #####     # #      ###     ##f             #   r   f b ##    ##       #
# ## ##   ## #    #   ####t #####  # #        ##   f     ##       ##  # ####     #    # ##f   # ###    ######         #  #
###          #          #  A l##  ##### ##  ####  #### # #      #b #     #       ##   ###       ##  g b  #  #     ##  #  #
# #     r##  ## ##     b   ####       #  ##       #    ####     #    #   ##   ##r###  ##   ###  #   ##     ##   ####     #
#         #l  # ##          ##   ## ###       f        ##     # ##   #  g### ###  b       ## #           ###  ####   #  ##
#     t   ##    #  # ##           ####         ##   ##    #   ###   r##      # # l ##  ####     ###     ##    g      #   #
##        g#  #### #  #        f#### ##      ###          #   ##      #  ##b##   # #l    #  b     #   #  # ###  l## ##   #
##      ## # ##  #             ###   #        #b f#  ###t ##    b ##    ##  #  ### f    b       # # ########     # f#   b#
###   #      ## ##   #        g#   #       ## ##  #   ##  ####   ##  l####     ##  # #  ##  ### # ###  #  ## ##     #    #
##    #b        f## ##  ### #  f ### ##  #  #  ## #  ##   #       # c l    ##        ##  #### #   ##  ## ##  ##    b     #
#          ##       ##   ## #    #   ########   # #  ###   l##  ###    ##  ##    ## ###  b# # ###        #           ## ##
#### ##  ####  ##   #   ##    ##       ##   l  ##  g## #    ##  ##     #  t#  ## ####          #      ##      f## ####  ##
#  ###          #t  ##   #    #    ##     ## ###  ###      ##              ## ## # ## ## #        #    #  ## ### l##f    #
##       ##    ##   ###    ##      # f    #  ##   #       ### #t   t      ##        ###  ###      # ## #   # ##   #    # #
##   ### #      ##       ###          # #     ##    b## ### # #####    # ##               #       ###l   ###           ###
#  ### # ##         ## ###    ##      # #b ##l##  ####  ##       ##l ### # tt###  ##   ## ##     ##    r ##   ##  ###  ###
## ##    ####  #    ####       ##       ## #      ##  r     t     #   t  #    ######        t            #     ## ##    ##
## #   f## #b  ## #   ### ## #####  ###  #    r ## ## ####l      ##  ## ##             #    ### #       ## ##      ##  ###
#  ##  ##      ######## #    ##  #    #  #f      # #g ##      ##r##     #  f c   g##  ## #  ##  ###      ###        ##  ##
#  ## ##           # #       #g   t# ##  ## # #    ##   A      #    #   ##  r###     r## ##   g   ## #            ####  ##
#  #   t     ##           ##f      ###   #### ##  ##    ## ### #    #   ##    ## r   ##  ## ####     #   ## ab     #   ###
# ##          #   f           ##     #  ## ## ###      t## t##  g#      #   ###      ##  #  ##    ##     ##        ### ###
#### ##  # ## ##              ## #          ### #f###        ##  #     a##   #r       ## ##  ## ###      #  # ##    ##   #
#    a#  ###     ## # #l##     # #   ##         ###b#  #  ## #   ##        f     t   #####      #        r  #      ##  ###
# ###b# ##          ### #   #    ##              ## ## #   ####      # ## #  ##  ###         ##                    # ar  #
# #    g## ### ##  ##   ##  #  ###  #    # ## ## #  ##     ##    b t ###  ##      ##t    ### l    ## # # A        f     ##
# ####   b # # ##      ##           #    ###  #  l#       t  l       ##   ####     #       #      #  # #  f##  ##  ##    #
#  ##      # ###  ## #### ###  r g  ##   ##       ### ###   g               #     ##         ## # ##   ##       #  ##  ###
# ##    ##f        # ##   #        A #    ##     f# ###      # t   l      ### ### ## ## #  ###  #  #   ###r   # ##       #
#  # ##  #    f##### b## ## #       ##   ### g    # #       ##   #      A ##  # #    ## #  # #  ## #        #####    ### #
#   b#   #r ##   ##  #####   f      ##  ## b         #   ####    #   # #          #     #       f  # #   #l   ####     f #
#    ##  ##        l #  #### ##          # #####   ###           # ### ###   ###### ### ######   ### ### #           ### #
#         #   ##          ## ##     # ## # ## ## # #        #    #a#     # t #   a  # #      #   #     # #    #        # #
#      ## ##   ## # g ##   ###   #### #    #     ### #      #      #     #####      # #      #####     #      #      # # #
#    ###   ### ## #  ##    ##   ## #  # ##  f    #   #             #    gl###                 ###      #             # g #
#### g       ###  ## ###        #  b  ###    #   #####      #####  #               g    f              #  #####      #####
##         ####   #### #    ##               ##                                  ###   ###       g            l   f      #
### ### ##       ## ##   #####     ##    g##     #          ########     b       #    f  #             ########          #
#   ##  #            f   ##        #       ###                                   #  l    #  b                            #
###  #### ## ##     g  #    ##   g            b         l     ####       g    l  #      b#               ####     b   f  #
#         #  #       l##    ###       #### l  ## #        a                  ### #       # ###      r                    #
#  ##l   ###     #  # #         ## ##  ##      #g ##        ###                 g        g       b          ###        ###
# b        #     #  # ##        #  ##   ##     ##  #  c #         ######                           ######         #g   #b#
#  ##     ##       ##  # # #             #     ##  ###  #                   l                             Ab      #  ### #
#   #     #      ###  ##f####b   ## g #  ##   ##     #                                        c      b    f          #   #
#     ##l## ######   l##    #    ##  l#   ##  #      #                        #####  g  #####                        #   #
#      #  ### ##     ##r          #      f    #  ### #         # #       c    #            b#           f# #f       t# ###
#       f ##   ## ##  #    ##    ## #   #     ## # # #         # #            #             #            # #         #   #
#          ##       l                      #       #                          #             #                          # #
#          ##           l                  ###   a ###                    l   #             #     l  g            g  ### #
#      r   ##                              ###        t           ####  a        #   fa  #          f####b           l   #
#          ##                       t        #    ####     ##     #              #      l#              #     ##   b #####
#      ###### l                              #                    # ####     ### #b      # ###     #### # rr   l         #
#      ##   b              t       l         #########         r  # #               # #        l      # #    l      l#####
#      ##      f                             #####       l          # f       g     # #               #   b       b      #
#      t       t                                          ###       #       ####    # #   g####       #  l    ###        #
#     t        l       g                            # #             #       #     ### ### b   #       #             # #  #
#            t               r                      # #             #       #     #    g#     #       #             # #  #
#                          t         #############r   #              fc ##  #     #     #     #  ##                 #  g #
#         r             f            ##             ### ####                #     #   g #     #                #### ###  #
#                    t               ##             #   #  f       t        #     #######     #       A        b  #   #f #
#                                    #############  #   #       ## #   ##   #           c     #   ##   # ##   l   #   #  #
#                                     g   ##   ##   # ###          #       b#     b           #      g #  a       ### #  #
#                                         ##   ##   # #       ######        #                b#        ######       # #  #
#                    b  ##              t ##        # #       ######        #              c  #     r  ######       # #  #
#                t      ##               l     r b  # ###t         #        #                 #        #          ### #  #
#                a      ##  t                       #   #       ##b# g ##   #           t     #   ##   # ##       #   #  #
# r          l    r     ##                   ##     #   #                   #     #######     #                   #   #  #
#                     r ##t                  ##a    ### ####                #     #     #     #                #### ###  #
#                 r     ##                   ##       #                 ##  #     #     #     #  ##                 #    #
#                       ##              t  t #####  # #             #       #     #     #     #     A #  g          # #  #
#                       ##                          # #  l          #       #     ### ###     #       # g       c   # #  #
#              r        ##                         g      ###       #       ####    # #    ####       #       ### f      #
#  r      ##            ##                  r                   l   #       l       # #               #                  #
#         ##   r        ##                    f   ####            # #  g          c # #               # #     b      #####
# b    f  ##  ## #################################        g       # ####     ### #       # ###     #### #                #
#t       t##  ##      l       l##     ##        ######     ##     #       bg  l  #       #            g #     ##     #####
# r       ##A ##           l   ##     ##        ##                ####           #       #           ####    b           #
#             ##    l                 ##        ## ###                     b  #  l r       t#        b        g a  c ### #
#             ##                      ##t        l #                 f        #      b b    #                          # #
#        ###############################           # # f       # #            #             #            # #         # # #
#f       ##         ##  l    ##   ##              ## #         # #            #             #            # #  l      # ###
#        ##         ##       ##   ##                 #                        #####   g #####    a                 l #   #
#       l                         ## b               # b                                l                            #   #
# l                               ##               ###  #                                                         #  ### #
#   t                             ##           a   #    #         ######         b                 ######         #    # #
#     tr                    l     ##     r     ll ##        ###                       b                   t ###       a###
#                                 ##             b    b                 A    ### #     bg# ###                    t      #
#   g          r t                ##                          #### b         g   #       #  b            ####            #
#        ##                       ##           t                                 #  f    #     l      b           g     a#
# t      ##                       ##       g                ########             #       #   r    f    ########         l#
##       ######## #### #############            l   b                            ###   ###         ff                    #
##             ##   ##   r##                      ####      #####  #                                   #  #####      #####
#####          ##   ##    ##                         #             #      ###    l            ###    l #        g    #   #
#####          ##   ##   f####### ### ########    ## #      #    f #  l  #####      # #      #####     #      #     f# ###
#              ##   ##         ##  ##       ##     #     c  #    # #        f#      # #     l#         # #    #          #
#              ##   ##         ##  ##       ##     ### l         # ### ###   ###### ### # ####   ### ### #         l ### #
#        l ######   ##         ##  ##  t    ##       #   #### l  #   # #          #     #  f       # #   #    ####     l #
##########################################################################################################################
