metadata:
  gen_time: 12.725439071655273
  timestamp: '2025-04-18T22:53:18.097528'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# #    ####          ###              ##             #   ##     #                 #     ##f               ##t## ## ## ## #
#   ## #  #         ## ###f     ##  t###           trr#             #         #                              ## ## ## ## #
#   ## ## #       ####       #####  # ##                           ##   t     ##           t# ##g## ## ##g## ## ## ## #  #
#ll  ###    # #####    ##    ##  r ##  #     g    bt       ##  ##   b  ## ##      ##  ##                  ## ## ## ## # t#
# ## #      ###  #      ##   #   ####                  ##   #  #       #   #       # t#   ### ## ## ## ## ## ## ## ## #  #
# ## ## ## ##      t    g       ## ##             #     #             A                   # # ## ## ## ## ## ##  # ## #  #
#    ##    #   ##l    ##   ##t  #   #    l     f ###                                        # ## ## ## ## ##l##g         #
#   ##   t ##  ##     ##        #       g       #####      ##    t                    ##    # ## ## ## ## ## ##r## ## ## #
# r  # ##  ##     ##   ## #l ##  t                     #    #    ##      #      ##    #    ## ## ## ## ## ## ##r## ## ## #
#### ####      ####  # #  #  #g   #    ##### g         ##         #  ##  #  ##  #         ### ## ## ## ## ## ##    ## ## #
##        # # r#     ### ##      g##    ###   #####                   #     #               # ## ## ## ##l## ##g## ## ## #
## ##  #### #  ##   ##   #  ##   ####    #     ###            ##                   ##       # ## ## ## ## ## ## ## ## ## #
## #   ## # #   #   #  ###  #    ### #       f  #         ##   #         t         #   ##   # ## ## ## ## ## ##  # ## ## #
#  #   #  ### ###   g  ##  ###l   #  ##          #####    #        #           #g       #   # ## ## ## ## ## ##t #    ## #
####r         #r       #   #f     g  ### #####    ###  #          ##   #   #   ##          ## ## ## ## ## ## ##  #  # ## #
# #  ##    ##    #        ## ###     ##   ###      #   #     ##       ##A  ##       ##     ## ##b## ## ## ## ##    ## ## #
#         ## f  ## ##  ## #   ##     #     #     f  tlt     f #           f         #            ## ## ## ## ##t # ## ## #
#   ##### ##   r  f#    # # ###  #  b                  #      #  A    ##   ##       ##     ## ## ## ## ## ## ##    ## ## #
# #   ##   ##         # #   #    #            r        #          ##   #   #   ##      l   ## ## ## ## ## ##             #
#####    g     ##     #l        ##     #     #####        #        #           #       t#   # ## ## ## ## ## ## ## ## ## #
#  ####   #   ##   #    #####   #      ##     ###         ##   #               f   #   ##   # ## ## ## ## ## ## ## ## ## #
## f ##   ## ##    # # f# ##           ###     #          f   ##                   ##t      # ## ## ## ## ##l## ## ## ## #
##    #   ## ## ##   ##         ##     ##t#     #####                 #     #               # ##t## ## ## ## ## ## ## ## #
##   ## # #  #  #    ##      t  ##    l#  ##     ###   ##         #  ##  #At##  #         ### ## ## ## ## ## ## ## ## ## #
#     #####  # ### g #  ###  gg  r        ###     #    #    #    ##f     #      ##    #    ## ## ## ## ## ## ## ## ## ##f#
# r   #  ## ## #     ## ##      #      l  ## #     ####    ##                         ##    # ## ## ## ## ## ## ## ## ## #
#  ##   ##  ##      ##     t#   ##        #t ##     ###                            t        # ## ## ## ## ## ## ## ##r## #
# ##    ###g         #    ###  ##            ###     #  #                         t       #  ### ## ## ## ##  #      ### #
#  #      #      g   #   ## ## ###        #  ## #     ###  b#  #       #   #       #  #   ##  f               # ######## #
#  ##   ###                  #   #   #    ## #  ##         ##  ##      ## ##      ##  ##    ##### ###### ###### #        #
#           ##      #g  ## ###      ###   ###   ###        f       ##         ##   t  c               f         # ### ## #
##l  ###  ###      ##    # #   ##  ##### f##  r ## #                #         #     c       ######## ####### #### ##c    #
##   ##            ##      # ###          #    b#  ##    ##     #                 #f    ##                        ##     #
##    ##  ##     g##    #     #                    ###     r      f ##       ##   ftc g  b t# ########## ##### ## ###### #
## ###### ##          ##### r ##                   ## ###    ## t  #####   #####    ##    ##b                            #
#  # #  #    ## ##       ##f   #  gr  r#     #     #  ###  ##### g #####   #####   #####  #########g## # ##### ##  ####  #
##   ##      ####   ## ###  ## ##     ###   ###       #    #####     ##     ##     #####                                 #
##   ##   ##    #   ## ##   ##       ##### #####      #     ###                 t   ###     ######    ## ####b ##  ##### #
#  # #    ##   ## #    #   ##  #                      #    b ##     b           l   ##           c  r           ff       #
#  #   f  # l   #####  ##  ##  ##       l                              ## ##                ##t# ## #### ##### ##### ### #
#         #   # #  #  ##   #  ##    #       f         ###        ##  #########  ##        ##   #       r     t c     f   #
#  ### ##   l##       #    ## ##   ###    #####  #    #####      ##  ######### l##      #### # #  #     ##c###### ########
#####  #      ###  ##       #    ######    ###   ##l  #####           ##   ##    gtt    #### # #    t  f      r          #
#               l     #         #           #  f ###  ######       f       b    g      ##### # # #   b                b  #
#    l    f           ### ##    #           f    ##   # ######                   t   ######  # #c############ ####b#######
# ######                #  #    ##   t    g t    # g      ######   b ## c   ##     ######c r     ########### ##### #######
#   ####   ######f     r#######                f            #####  #####   #####f #####              l             ## b  #
#   ####   ######             ####g           t              ####  #####   #####  ####    l  # # #### ###### ########    #
#   ####   t                  ###   r         l   #           ##     ##     ##     ##       b# # ###  ###### ######## ####
#####          f       r  #######  b         l   ### At##     ##                   ##     ##   #   l     f             r #
##    # l                 ####                  ##### ###    ####                b####    ## # #####  ###### ###### # ## #
####  # f    #### #####   ####                         ###  g######   ## t ##   ######   ### # ###### ######  ##### #    #
##    ###### ####  ####      #####                     ###    #####  ###   ###  #####    ##### ##                   # # ##
## #    #    ####  ####      #####       b     ##### ####       ##   #### ####   ##       ##   ## ### ###### ######## #  #
####    ###     ####   f####      #    ########### f  ###             ### ###      b    c ####### #      f            # ##
#r #r   #   ###      #  ####      #    ###########    ####            #######            ###      # ## ##  # ## ## ## #l##
#  ###  # # ###  ##  #            #b   ###########    ######    ## b #########   ##    ############ ## ## ## ## ## ## #  #
#  #    ###      ##  #            #l   ###########    ######  ####   #########   ####  #####  #####l## ##g## ## ## ## # ##
#  # #  #        ##  # t f       ##  g ###########    ####    #####   g#####    #####    #### ##           b             #
#  ###  #     ##### ##           ##    ###########    ##       ####      #      ####       ## ##                         #
#       ### #g###f A##           ##                   #    t   ###b              ###        # ##     c             t     #
#  #      t   ###  ###           ##  l                #         ##               ##         # ##                 b       #
#  #    # ###g###  ###           ##   ####     ####   #                          t          # ##   l         l           #
#  # #  #     ########           ##   ####     ####   ##       f ###              g #    l#     # # # # # # # # # # # # ##
#  # #  #        ##  #t          ## r ####     ####   ##f         ##   #          f###   ###      # #l  # # # # #  b#f#  #
#  # #  ###A     ##  #            #   ####     #### g ##      #    #   ##         ##### #####   l # #   #  b#   #   # #  #
#  ###    # ###  ##  #                ####  #  ####    # r#   ##       ###                      # # # # #r  #   # # # # ##
#  #    # # ###      #  ####          ####  #g ####   b# ##   ###      ##                       # # # # # #g#r# # # # # ##
#### t  ###    l####f   ####     r          #           ###   ## #     #               t    r   #   # # # # # # # # #   ##
##      #   t####  ####      #####       g  #      f     ##   #  ##                  b   # f  b #   # # # #   # # # #   ##
## #  ###### ####  ####      ########       #       ###   #      ###           t         ##     # # # #   #   #   # # # ##
####  #      #### #####   ####    ###       #     b ###        b ## #        #           ###    # # # #   # # #   # # # ##
##f   #                   ####    ###       #       ###     b    #  ##g      ##   r   #  ## # b # # # # # # # #r# # #l#l##
#####                     ####### ###  r    #     r ###     t       ###      ###  b   ## #r ##    # gb# # # # # # #   #  #
#   ####f                     ###              b            g l     ##       ## #     ###   ###   #  l# # # # # #a#   #  #
#   ####   ######  r          ####    g                             #        #  ##   l##    ##  # # # # # # # # # # # # ##
#  f####   ######       #######   #########   #########      f          l       ###   #   l #   #b# # # # # # # # # # # ##
# ######                #  #    ###########  b#########     r                   ##              # # #   #   #   #   # # ##
#           t         ### ##    # #########   #########           #####         #       g l     #   #  g#   #   #   #   ##
#                     #         # #########   #########            ###      g    b           ####   # # # # # # # # #   ##
#       ###############       #        ##   ###########  #f         #      l       c    f     ### # # # # # # # # # # # ##
# ########################### #            l########### ###          #####                     ##g# #   #   #  g#   # # ##
#b                            ###      g     ############### #####l   ###   ##### #####         # # #   #   #   #   #l# ##
####### ### ####### ### ######g           l  r            lf   ##      #b r  ###  r###          # # # # # # # # # # # # ##
#              t                # # ### ### b                f #              #     #g l  f     #   # # #g# # # # # #   ##
# ########## ##   ############ #g #         #                 r                #####    #####   #   # # #  f#   # # #   ##
#  ##   a ##   g   ##     ##  ### ### ### ###                         #####     ###      ###    # #l# # #   #   # # # # ##
#  ##     ## ### # ##l   g##    ##         #           #      #####    ###       #        #     # # #   # # # # #   # # ##
#         ##b##  # ##         # # # ### ###           ###r     ###      #       t          ######f# #   # # # # #   # # ##
#  ##t       ## ##l       ##  ##  ##  # r#        A   ####r     #                           ### # # # # # # # # # # # # ##
#  ##     ##### #####     ##  # # # # # ###                 #    #####          #####        #  #   # # # # # # # #b#   ##
#         #g        #           #   #     ##     ###        ##    ###            ### t          #   # # #   #   # # #r  ##
#  ##     #       A #     ##  ###  ## ### #     #####       ###   r#              #             # # # # #   #   # # # # ##
#  ##     ###########     ##  #          f  ##  ######      ##      #####          #####        # # # # # # #r# # # # # ##
#####  t                  ##### ### ### ### ##   #####      # b##    ###     b      ###       ###   # # # # # # # # #   ##
#         ###########    a                # ##lt  ###                ###    # ##     # ## #   ##### l     #   ##     # # #
#####r    #         #     #####c#         ###                ##    #   #   ## ####  ## ## ##      #  #  # # #       ## # #
##### c   #         #     #####     ###             l r      #     ### f         #  ##    ###   ###  ###### # ###        #
#                             # #   #             b ####        ##  #     # ##     ##    ## ###          ## # ##         #
#####     #      t  #     ####  #   #        ##    ####   #      #  ##    ###    ###   ###   #     ###    ###     ##     #
#####l    #         #     ####  #           ####   ####   ## ### ##            ### t    #          ##         ##  ##  g  #
#       t                     ###   #       #####   #### ##  ##      ##fb###     g  ##  ##    #   ##   #  ##  #   #      #
##### l   #    t    #     #####     #       #####r   #####   #      ##    ##  ##   ###     #####   # #######  #          #
#####     #         #a    #####r        c   ####         r  ######  #   ###  # ### #   #     #     ###  ##      ##       #
#         ###########         ###        r    l           ###   ##  ##   #  t#   #   # ##  ### ###       ###### ##       #
#####l                                                 # ## # ###        ##  f       ###   ##    #         ##l   ## ###  #
#  ##     ########  #     ##  # ### ### ### #          #  # # ##          #    #  ##  ##    l      ## #  t  #### #  #    #
#  ##     #  aa    l#     ##  #   #      #  ##      g  #      #   ###    ## #  ########  ##  ###   #  #  ## # ## ##    ###
#         #         #    g    ### ### ###  ####       f#           ##  t  ###  #  ##  ##        g  ## # l   # ## #  #    #
#  ##     ##### #####     ##    #   #  #   #####      #         #                    ###   ##    #       # ##    ## ###  #
#  ##        ## ##        ##  # ### ##  ### #####    ###   ###  ##   ### #  #    #   # ##  ### ###       ###### ##       #
#         ## ## ## ##             #   #  #  #####   ##### ## #  ###### # #b##  ### #   #     #     ###  ##      ##       #
#  ##     ## ##### ##     ##  ### ### ###l#  ###    ####  ## ##   #     g  ## ##   ###     #####   # #######  #          #
#  ##     ##    l  ##    f##   #    #   #  #         ####  #  #     ###    #        ##  ##    #   ##   #  ##  #   #      #
############### ############### ### ### # #        g l #####    ##    ###     b###      #          ##         ##  ##     #
#            g                   #   A    #    f         #           g ##  ##  g ###   ###   #     ###    # #     ##     #
####### ###l####### ### #########  ## ### ## b   ##### ### ######  ##        #     ##    ## ###          ## # ##       g #
#                              #                ####### #  # ## ##  #         t  #  ##g   ###   ###  ###### # ###        #
# ########################### # ### ### ###     ####### #        #### #    ## ####  ##  # ##      # r#  # ###       ## # #
#       ###############         #r        #      #####     ##      #  #     ####     # ## #   #####       #   ##     # # #
##########################################################################################################################
