metadata:
  gen_time: 7.680643081665039
  timestamp: '2025-04-18T22:55:57.220944'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#               ###   #        l     r   ######## l ########r    ################################  t  ##         #########
# #             b              b                                                                                         #
# ##            ###      #  f#        #  ## ######  ##   ###f             #######  #   #        f      ######## ##########
# ###     ###   f###  b  ## ## l r    ##  b  r             #   g           ####### ###                       b#          #
##  ##  l###     r       ## ##        ## #                   ########      f###### ###       ###########      #        g##
###              ###     # b #    #   # ###  l             #        ##                          b  b  #       #        ###
##     b ### r    ###            ##     ####       #r        r       #### #       ###########    b    #       # b     ####
## ###    ###      ###           ##      ################    #                                      ######################
# ###g     ###            ###     #      ###########          ############### ################ ########       ############
#                  b     ###             ##               b                 r                       #           l      ###
# ###           ###                                    c###### #########  ######  ######  ################         t    ##
####        t    ###     ###          ###t        ############    r    ####################      r  ############         #
###    ###      f ###     ###     #  ###         #############            #       #r   #l           #############        #
#       ###                      ## b    #       #####################      ## ####  #    #######################       ##
##       ###              ###    ##  ### ##       #######    #  g         ##   #  # #  #            #    #######       ###
## #      ###  ###       ###     #    #########                      f    #  #      # #             #              #######
#t##            ### #      b      r     r###### ############  ############# ##          ############# ### ################
###       ###l   ## ##                                                                 #############  t A         l#     #
### ###    ###  b # ###       ###           ##  ###                     a   ##     t#     g               r    #######   #
##r###      ###    r ###       ###       # ####   #####################     ##      ##     ######## #### #######   #### ##
#    r   f                      ### f   b# ####                       #### b##      ##  ####    t                  #### ##
####     g           ###               ### #####          g   t      A   #####      #####                         ##### ##
##                   ###               ###  ####################g           #      t #           f# #### #############  ##
#  ##      c                    ###                           b###############       ########### ##    a              f ##
## ###      ###      ###       ###       #  ################                ###    # #  g    t        #  ########  ###b ##
##   ##    ###    #g###       ###             g##############    t   b      ####  ## #               #   #####    #  ## ##
##   c    ###    ## ##             l           ###  #########    l   ############### ########           ###    t###   # ##
#             f ### #       f            # #  a###   #######        ################ #########         ##   #   ###     ##
##        ###  ###       ###    l#    ####### b###    ######     b  ################ ######### b       ## ##    ##   #####
###      ###      b       ###    ##  ###b# #######    #########t ################### ###########    ## ## ##g   #   ### ##
#       ###                      ##      # #######   ####  #  ####  #f                       #   #        ##       #### ##
###    ###        ### f l ###     #  ###    ####### #####  #        #                        #   t        ## ###  ####   #
####             ###     ###          ###   ####### ####   # r                               #               ##   ####   #
# ###   b       ###                         ##   ab  ###       ### ################# ########### #    #    ##l      ##   #
#                        ###                ##b       #  ## ###### ##r                       ### #  #               ##   #
#   #r     ###            ###     # r       ##   b  t              #                          ## #  #     #         ##   #
## ###f   ###     f###        bf ##         ##   t                              t    r                    #       l ##   #
###b     ###      ###    r       ##    ##   ##      # ############################## ########### #  #  # #          ##   #
###     g     f  ###     #   #    #   #     ## f   ##  ############################# ########### #     # #   ##     ##   #
##  ##   ###             ## ##        ##    ##     #    ###f     ##  ############### ########  #       #      #     ##   #
# ###     ###    ###    r## ##        ##    ##     #             ##  #########       ########  #              #     ##   #
# ##f           ###      #   # b      #     ##    #################  ######            ######  # #    # ########    ##   #
# #           r                    f     r  ##   ###             # f ######        f   ######           g     ###   ##   #
#          r    ###   #              l   #####   ###  #######    #    ####       r     #####         # #####  ###      ###
#t ###                    # #           f                  #  # # # # ##   #ag    g       b      f  ab                 b##
# g#                      # #b        b    t t           # #  # # # # ## # # ####### ######## ## #     ############# #####
#  # #  g           l     # #                   f        # #  # # #l# ## # #                                ####     #####
#  ###                    ###       b                    # #t # # # #    # # ####### ######## ## #    #####             g#
#    #                      #                            ### b# #                        r                     #  ########
#  # #   f                # #      g ## ##########       #    # # # # ##   ######### ######## ## #  ######               #
#  ###        f         r # #       r#b   t      #     f # #  # # # # ############## ######## ## #  #####   #  ###########
#    l  l          ######## ##       #           #       #r#  # # # # #         ##                                       #
#r    b          t     #     #      c#   b       #       #    ### #f# #A# # # # ## # # # # #l  # #   #     # # # # # # # #
# b                ######## ##       #   c       #       # #      #   # #g# # # ## # # # # #   # #       # # # # # # # # #
#      ###      b         # #        #############       # # g    # #f# # # # # ## # # # # #   # #       # # # # #       #
#        #                # #    l                       # #      # #     # # # ## # # # #     a #     ###     aa#########
#  g   # #              b # #                            ###      # # # #g#c# #f## # # # #### ## #    #############      #
#      # #       t        # #   g l                      #        # #       # # ## # # # ##    b              A   # # # ##
#      # #        r       ###               fg           # #b     # # # # # # # ## # # # ## #  b f  A # # # # # # # # #r##
#      # #t                                              # #      # # # # #g# # ## # # # ## #       # # # # # #g# # # #r##
# ## f # #                                 g             # #      # # #g# # # # ## # # # ## #       # # # # # # # # # # ##
#  #   # #                           t             f     # #      # # #     # # ## # #   ## #           # # # #   # # # ##
#  #   # #         t                                     # #l           #####   ##   ######      #  #####     ###       ##
#l #  g# #           l                                   ###     ################# # ###### #  # #  ###########   ########
# g#   # #                                                                                                               #
# ##   # #                                g               bf  l   ################### ## # ###  # #  ############### #####
#      ###   g       ###     t f                                           ########## ## # ###  # #   ############## #####
#      # #           #b#       ###   f       l  lg                ######## ##            b                         c     #
########  ##  ##            ####  #################      #####      r         # ## ## ## ## ## ## #  #  ##a## ## ##r## ###
#         ##  ##  ########  ####  #################  ##  #####               ## ## ## ## ## ## ## #  # t## ## ## ## ##a###
#         ##  ##  ########  ####     g               ##         ############ ## ## ## ## ## ## ## #  #  ## ## ## ## ## ###
#          # g##  ########  ####  r                  ##         ############ ##r## ## ## ## ## ## #  ##r## ## ## ## ## ###
##      c ##  ##  ########  ######  f  r     b       ##         ############    ## ## ## ## ## ## #     ## ## ## ## ## ###
##f       ##     f#####     ######f             r######     ################ ##f## ## ## ## ## ## ## ## ## ## ## ## ## ###
#         ##      #####   g ###       #####      ######     ################ ## ## ## ## ## ## ## ## ## ## ##t##b## ## ###
#         ##      ########  ### b     #####      ######     ################ ## ## ## ## ## ## ## ## ## ## ## ## ## ## ###
#######   ##    ##########        #########   r  ##         ################a## ## ## ## ## ## ## ## ## ## ## ## ## ## ###
#######   ##    ######  b         #########  l   ##        g####  g r           ## ## ## ## ## ## ## ##b## ## ## ## ## ###
#######   ##    ######      l     #########  ######  ########### b          t## ## ## ## ## ## ## ## ## ## ## ## ## ## ###
#       r       ######      ###############  ######  ###########      ####   ## ## ## ## ##l## ## ##t## ## ## ## ## ## ###
#               ###### g    ###############  #### l     l      l      ####   ## ## ## ## ## ##a## ## ## ## ## ## ## ## ###
#     l    f    ######      ##  g g     c    ####          g      ########  b## ## ## ## ## ## ## ##    ## ## ## ## ## ###
## ###################  l b ##               ####            r    ######   r ## ## ##f##b## ## ## ##b## ## ## ## ## ## ###
######################  ##                 ######    ###     ###########     ## ## ## ## ## ## ## ##l## ## ## ## ## ## ###
#     l      l    f###  ##          ###    ######l   ###     ########      r ## ## ## ## ##    ## ## ## ## ## ## ## ## ###
#                  ###  ##          ### a  ###### c  ###  ###########        ## ## ## ## ## ## ## ## ## ##  #  # ## ## ###
#     #########    ###  ##        #####  ########         ###########   ##   ## ## ## ## ## ## ## ## ## ##r A       ## ###
#  l  #########    ###  ##        #####  ########         ###########  l##   ## ## ## ## ## ## ## ## ## ##       ## ## ###
#     #########    ###       r#########  ########   #############            ## ##g##  # ## ## ##f## ## ##b## ## ## ## ###
#  b  #########         g l   #########  ########   #############         t  ## ## ##a   ## ## ## ## ## ## ## ## ##f## ###
###############               ##       b ########   l        r           cr  ## ## ##    ## ## ## ## ## ## ##g##    ## ###
###############    #############    l a  ########                   ####     ## ## ##a # ## ## ## ##    ## ## ## ## ## ###
#  r              l#############         ########  ####  #####      ####     ## ## ##  # ## ## ## ## #  ## ## ## ## ## ###
#                  #############     ############  ####  #####      ####  ## ## ## ##    ## #  ## ## ## ## ## ## ##t## ###
##########         #############     ######    b   ####  #####            ## ## ## ## ## ##   t## ## ## ## ## ## ## ## ###
##########         #############     ######b       ####  #####            ## ##b## ## ## ## ## ## ## ## ## ## ## ## ## ###
########     f  b  ######  #####r              ######## r#####   ##b  r   ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ###
########           ######  #####g             l########  #####   ##  #######a## ## ## ## ## ## ## ## ## ## ## ## ## ## ###
######## b  r              #####    ##         ########  #####   ##  ####### ## ## ##  # ## ## ## ## ## ## ## ## ## ## ###
########   ### l######  b  #####g   ##   ###           l #####  l##  #######    r    t         bt                 #      #
########   ###  ######  f  #####    ##   ###                    r##  #########       A            #              l     ###
########        ######            r ##   ###  #######            ##  ####### #                              r        l # #
#     f#   #  ############# b    c                  #   # #####          b                                               #
#         l#  ################## #  ## # ########   #   # ######           g         ##           r         t ##         #
#      #   #  ################## #  ## # #########  # l # ##################   #      #  ##               ##  #      #   #
######## #### ####                     # ######### ## #  c #################  ##         #   g        b    #         ##  #
########   ## ####   ####      g    l  # ######### ##       ###  t  b                r                                   #
########   ## ### l ##  ##  ####                  A               g            gA       g                                #
########   ## f     #    ####  # #  ## # ######### ## # ########### ##########                 ##   ##           f     ###
########   ##       #                         f                              #                  #   #                    #
######## #### ################## #  ## # ####           b             ########                 ##   ##          l      ###
######   ####   ##### fg                    ###### ## # ####################               l      r                      #
#      c                ######## #  ## r            b    b            #   b  l                          g                #
#      f      ## #     ######### #  ## # ######### ## g                      t##         #                 #         ##  #
#      ######  #      l######l       # g           f  # ####          #        #      #  ##               ##  #      #   #
#     #######    #  #####       f# ##### ##  f             ##    ##     ###          ##                       ##         #
#     ####### r   #    #l       ##   ### ###                ######    ######                         A                   #
#l    #######   # ####### f     # t l ## ###   g   b                         #   f                                     # #
#     ###########     l###r   g # r   ##  ######## ## # #########  ######   ##                 f  #b        l          ###
###################    ###     g#    ###   #        b g g                 ##t     #g        g    g                #      #
##########################################################################################################################
