metadata:
  gen_time: 9.042778015136719
  timestamp: '2025-04-18T22:57:28.425825'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#          ####   #r                # #  g  ####   ## l    ###  ##      #### b### b  r   ##l  ##  f##################### #
#####  #   #  #   # ####              #      ##   a      #####          ####  ###  b  r       ##   tb   ################ #
###    #   #  #        #c      b #### ###                ####  f         ##    ##                       ######     ##### #
#####         #    l   #        l  ##   #          ## l   ##    f   ##        l  #########         b      ####     ##### #
#   #   A          g   #   l      ### # #  ##      ##     ##       ####         l#########   f       t b            g    #
#   ### ### g  r               l #    ##   ##     ####           ######   ##  ## r    ##      l        ## ####           #
#  c     c b                     #    # #         #####        ######     ##  ##      ##    c          ## ####           #
#                  r          #         #     f    ####        ####                      b    g ######### ####         ta#
#    #    #    g    g     ##  #   f     ##  ##    r##        t  ##  l                           #########  ###  l        #
#    #    #                       f      #  ##            ## g  ##   ##            r            #########  ###           #
#            #             c      r   l f           g     ## f      ####        #  b            #########  ###    r      #
#    #    #  #      #   # f #                       ##             l#####       ####       r    #########l ###           #
#    #    #         #   #   #     ###     ## a ##   ##               ####  ##  #####    ###     ##############         ###
# r        c  g      g            #      ####  ##  ####  ##  ##      ##    ##  ###      ###     ##############     l  g###
#     a     c             c #c    #      ####b     ##############f    f         ##   t  ###############  l################
#            #              #  #### ##   ##    a     ##############f             #      ###############   ################
#  ### l     #     g           #f     f        ##      ##  ##  ######            ######################   ################
# #                         #  #              ####      f        ####   ##  ##  ##########  ###########  c##########     #
#### ### ##       l         #  #            ######         t      ##    ##ab##  ##########  ###########      #######     #
#c   #                      a             ######        ##  ##           t        ########  ###########      #######   ###
## ###      l    ###              c   #   #####        ########                   ########  ###########      #######   ###
#  t             #   r      #b#       #    ####   ##  #########    ## f     l b## ########  ###########                ###
#### #     ### ### #  A     # #       ###  ##     ##  ########a    ##     ##   ## ########  ###  ######      t           #
#    #     #  #    #              #                     ####       g    #####         #### l###  ######  l f             #
## ###     # ### # ###       r    #   #b#                ##   g         #####         ####  ###l ######   ######  r      #
#                ##  #                # #       b ##     ##l  ##    ##   ##    g ######### t###  ####tb   ######         #
#        g       #   ###                        ####bf    l   ###   ##           ######### ####          t######         #
#          ###     #  f#      #          #  ##  #####        #####         l     ######### ####  ####  ############      #
#          #       #   ###    #          #  ##   #####  ##   #####         l f             l     ####  ############      #
#      b   # ### f   #   #            r          #####  ##l    ##  g ##   t                      A               ##   tt #
#          # ###  c  #   #    b    c     t      #####                ##      t   tl  t           ####  ####      ##      #
#          #       # # ###    #                 ####                       ##       r       lfr  ####  ############      #
#   f   t l###     #   #      #                   ##   ## a  ##  ##      ######  ########## ###  ####  ############     b#
#                # # ###                   ##   b      ##  #########     ######  ########## ###  ####   r ######     l   #
#                ##  #                # # ####             #########      #### f #########g ###  ####     ######         #
## ###     # ### # ###        c   #   # # ####     ##rl    b##  ##       f###    t l  ####l ###  ###### l ######r     l r#
#    #     #  #    #              #        ##     ###             b ll     ##         ####  ###  ######   l          b  g#
# ## #     ### ### # l      # #       ###    f    ####               ##   b### f  ########  ###  ######                  #
# #  gl         b#         r# #   l   #          #####        ##     ##   ####    ########  ###########              c ###
##c###           ###                  #    ##  #####        #####         ### b   ########  ###########    b #######   ###
#   g#l               g                 f  ##  #### tt     b#####      l ####   # ########  ###########      #######   ###
###  ### ##           b     #  #    fb          ##    f##    ##    ##  #####    ########## b###########      #######     #
#         b  f              #  #                       ##     l    ##  #####     #########  ###########   ##########     #
## ###  g  f #    f            #l                 l         b           ##       ######################   ################
#            #              #  #### ##   l ##  ##             ##       g    f   t#l g   ###############   ################
#                    l      #     #      ##########           ##         f     ###r    b############### r ################
#            f           r  b     #      ############  ##       g  ## b        ###      ### t   ##############         ###
#    #    #  f      #   #   #     ###    ## A##  ##########        ##    a      ####    ###     ##############b       t###
#    #    #  #c     #   # b #            #  c  l   #########      ####     ##   ####         t  #########  ###      g g  #
#      b     #r      f         c                     ##  ##### f######     ##  ##     b  bt   g #########  ###          g#
#    # c  #                                   ##    t     ##########    t      ##          g   r#########  ###           #
#    # f  #               ##  #         #    ####t      l   ######  f           #               #########  ###     a t l #
#    g    #  f                # f   c   ##   ####   b ## A    ###         ##    #      c  l     ######### ####   t t     #
#                        g       #    # ##    ####    ###      ##   ##  ####   ##   g ##      r     rt ## ####           #
#   ### ###                      #    ##    b #####  ####          ##########  ##     ## r  l          ## ####        r  #
#   #                  #         #### #        ###########        a##########   g#########  r             ####           #
#####         #        #     r     ###  #        #########    ##     ##  ##      #########     tc       lb####     ##### #
###    #   #  #       l#         #### ###     g    ##  ##   ####                         c              ###### r   ##### #
##### r#   #  #   # ####     c r   g  #                     #####                             ##   t   b################ #
#          ####   #  #   f          # #c      l     tg  c    ####   ##t   ##   gl        ##   ##   ### ################# #
###########       #################   ###   ##  ##     l #         #     g   #  l        #b #   ##       r##l##   ### #  #
#####      r      #################r  ###   ##  ##       ############ ## #####    g    ###### # ####      ## ## ####     #
##### c           #################   ###   ##  ##       ############ ## #####r   #  # ###### # ####    # ## ## #### t   #
##### l           ############        ###   ##  #rg    f f#     #                 ####     rt #  ##          ##          #
#####        b    ############        ###   ##  #  g      ##g  ## r       l   ###b     ## ##   # ##     #     ######    f#
########   ##     ##########          ###   ## g##A   l   ## g ##             ###  ###### ##   a###         # ######    ##
########r  ##         ######          ###   ##  ##             ##                 ####### ##     ##                   #g##
########   ##         ######    tt#######   ##l ##         #   #              #  ###     b       ##        ##   ####  # ##
########   ##         ######c l   #######   ##  ##       g ########## ##      #   ## #### ##     ### #                # ##
#############     ##########   l  ###      g##  ##         ########## ## ###  #   ## #### ##     ### #     #             #
#############     ##########      ###       ##  ##    r             # r   ##  ### ##         l    r                   t  #
#############     ##########l     ###  A    #   #           ##     ##     ##     ######## ########## ##     #   ##  ######
##########l       ##########      ###    ############## ###        ##     ##     f####### ########## ######   #  ## ######
##########      ############a     ### c  ##############  ## ###### ##     ##      ##     g   r     #  ##                 #
##########    r ############    ##### ct         #  r    ##     ## ##### ###   l ### ##    #####    # ## ##      # #    ##
##########      ######     tt   #########  ##  l##l      ##  r  ##  r  #  ### ### ## ##              ### #    a#         #
# f  t          ######t         #########  ##   ##       ##   r ##     ##  tg ##  ##              b   ## #f    f##       #
#          r t  ######          #########  ##   ##       ##     ##  lf ##   g ##  #####  ####f        ##        ##    a  #
##########################      #############   ##       #      #      #     f#   #####         a        g            t  #
##########################      ########## ##    #      ### #####################           t  #########    #######    ###
##############################    b  r     ##  g #      ### #####################  ##     #                 #aa          #
##############################     b t    r##    ##     #             #   #  l     ##f#   #  ######  ##   f # ##     #####
#######  ##  t   ##         ##t             #    ##     #        f    ##  # l      ## ##  #    f     ##     # #     rt   #
#######  ##  b   ##   c     ##    t      ################       r     ##  #        ##     #  #####  g##     # # f    ##  #
###      ##    c ##              ####### ######      ####             ##  #  f   g #####  #              ## # ##     ##  #
###      ##          ###         #######   A      r g   #             ## f         #####  #     #######r  # #        ##  #
#####    #####       ###  A      #######r#              #t            ## #  #####r   #    #     #######     ####   l   g #
#####    #####       ###      c  ####### #            l##             ## #  #####     #        ###  g          g     ### #
#####  t #######     ###  b           t  #             ##             ##               #    bg# ## ###    ########       #
##   t   #######   #####         r     b #             #       f    f ##           #    #       ## # b r   c             #
##       #######   #########             ###############################         # #  ##### ######        ######### g    #
##              t  #########     ###     ########################  ## ## #  ###### # l####  ######                     ###
##                 #########    l###      #                 g      ##         ## #                  #           f        #
## #######b        ######        ###     ##                        ##         ## #     # #          #########a    ###    #
## #######b        ######   tb   ######  ##                g       ##         ##                        g          t     #
## #######   t  l  ###### t      ######  ##                        ##    r    ##              #########  t     #       ###
## ####### ##############  ############  ##            r       g   #     g    #       ##                 #######  ##     #
## ####### ##############  ############  #################### ####### ## #  #                ##########          l       #
#     l      ############  ############      ###############  ####### ## #  #                r   t         g             #
#r      bl   ##    c   ################r l                r                   ##   # ## a        #########################
#   b        ##        ################             l           l    l        ##   # #     ###   #########################
#      ##    ## l      ################    f                                                                             #
#  l   ##  b ##        ##############l   ##### #####  ## ### ### ##  ######### ### #      a     b      #    # t   #   #  #
#            ##        ##############    ##### #####  ##  ##  ##  #   ######## ### #       # #  #         ###    #########
#c           ##        ##############        r #      ##  ##  ##  #         #           #### ## #### ####   ###   ########
#    t   c               l ########## # #      ##     ##  ##  ##  # lg     ##                ##  #       ##     #  #     #
#             b            ########   # #    l ##     ##  ##  ##  #        ##g      # #      ##l#     ## ## ##    #  f ###
##   b        b            ######## # # #      ##     #   ##  ##  #        ##       g       ####g     ## ## ## ###       #
##     l l     g         ########## # # #      ##     #   ##   #  #        #           #     ##    ## ## ##    ## f  #####
##            ######     ########## # # #      ##     ##  ## ###### ##########            #  ##     # ## ########        #
##         t  ######     ########   # #        ##     ##  ## ###### ##########    ##### #######     # ## ########    #####
##   t        ######     ######## ### #        ##  l  ##  ##  l         #          ####  ######g    #r   a            t  #
## #######    ###c     l ######   ### ##     f ## f   ##  ##    b       ##       l #   #    #  r    #              ##### #
## #######    ###        ###### ##### ## ####  ##   l ##  ##            ##        #     #    #   f f a     ####          #
## #####      ########   ###### ##### ##  ########### ##  ##            #        #       #l   #          a       f#####  #
## #####      ######## l ###### ##### ###        fb## ############# ########## ##         #    #    r #   g      l       #
## #####      l  #####   ###### ##### ###        g ##         ##### ########## ##      ############## #   #    rr    a   #
#   ####l   c  b #####   #####  ##    ###          ##             #          #      t  ############## ##  #    ##### f   #
#   ####         #####   ##### ###   r###          ##     t      ##        r ## r      ##             f   #            # #
#     ############## A   ##### b       c           ##    f       ##          ##        ## ########### ##  #  #######   # #
##########################################################################################################################
