metadata:
  gen_time: 8.145340919494629
  timestamp: '2025-04-18T22:49:20.501386'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#######        f      #            # ##########   #a# # ########## #    ####       ####b  ##   #    ## ##    l##  ## ## ##
#          #             #           a                                                                                   #
#       l ##    #        #  A     r####                                               # # ##    #####   # ####### ##g#####
#        l     ##       l       ##                                                                                       #
##              #      ### ####l#  #### ### # # # # # # #f    ###       ## ##  #  #   #r##### ## #        ##b## ## # # ###
##                      # A#  g #    ag     # # # t   #a#            #  ## ##        ##### #g #  ##   ### #####          #
##  f            b         g       #  #     # # ####  #r# # # ### ##     #    ######  ##   ####   #   ### ##     # # #####
## ## f #     ################   lt## #    a# # ##      # # f   # ## b  l  c# #                  #### #   ## ### # #######
##      # ##   #  #   #          # ## ####  # #### # #### # ##### ######### # # ### ## ## ### ## #### ##   # ##### #   ###
#        t           t     f     #                              #c####  t## ### #   ## #f #########  l##  ##### ## # # ###
###  ####  # ###### ####        ## ## # # #a############### # # # #### ###  #   # # ## #   # ###       ## ###      ### ###
# # b    tg#  #     #l #                                                                                     g       #   #
#     b  g #     l        b        ##a######## ## # # ## ######## ####      ## ## #### ## ## # # #   # ####### ## ###### #
# ##                           t                                        ### ######## cc##### # #   r   ########## t      #
#      ### ##  ###    ##         # #######a###### # # ######c#################f   ## # ##   ## # ##l## ##     ###### ##  #
#     f    #    #      # ######### ###     ###### ###l######     ####       ## ## ## # ## ## #      ## ## ### ## ### f   #
#       #   g                      # # ###      # ### #   ###### #b#      cb                 # #######    ### ##      #  #
####    #    t           # t               #   ## ### # #          #     #  #        #   #  ##  #        ### f#### ## #  #
#             ##  #  #   #   #     ###### ##   ## ##       ######### ###   ## #             ## ##    #    ##    ##  # ## #
#      ##l##  #   # ##       # ### ###### #  ######      #########   ###  ### #   #   #  ##           f ##  b # ## ##### #
# ##   #g #   #   #                   g##                                                         A        ## #       ## #
#  # g #  #                 ##     # ####                            ###### #### ###### #### ## #   #f  ## bg ###   # ## #
#      # t               #  r# ##  #                                                    ####    # ### # ## ######## # ## #
#g                   #   #         ######                              g ## ##   # #######    # #     # ##            ## #
##        r     ##   #         #  l   ara            ###### #       # ##### ## ###    # ## #  # # # ###     # ## #### ## #
## ###                      f  ##   ### #    l              # # #####   ###    ### # ## #  # ## ###      ## ###########  #
#              t # ####   ##        a   # # # ##c##### ## # # #     #####    ###   #    #   f##   # # ## ##   ### ## ### #
# l#  a          #        #        #### ##### ## #   # ## ########## #### ## #l##### #     ####f# # #  # #   ##      ### #
#  #         ### #        #                                                                     ### # ###### ###   ###   #
#t #  #####   #  ##  b t  #  #t #  ######## # ##a# # #a#  # ######## ## ###### ##    # #   ##     g## ### ## ### ####### #
#  #     #      b#        #  # ### ######## # ## # # #g#  # ########c## #      ## ###########  ####b#   #    ##   ### ## #
#  ## #                  ## ##        g     #    #####           a   ## #      ## ####         #### # b #    ##   ### ## #
#  #  #        ### #             # ### ######### ##### #########a### ## ###### #       # l ## # #   # ### ## ### ####    #
#  ## #           l      ## ##       #          r##a##   ### # # #   ##    #     ##  # # # ## #   # # ###### ###   ###   #
#  #    t#       #      t #  # ### # # # # # # #g##### # # # # # # # #### ## #  ### f#     ##     # # b# #   ##      ##  #
#  #  #####   #  ##       #  #  #    #              #### #     # #  #####               #         # # ## ##   ##   # ##  #
#  #        t### #    l   #        ### # ###b# ######### # ### # # ##  t###      #      #  #      #      ## #### # ####  #
#  #   f g       #        #            # #a# # ##     ## # # # #    # ####     ###    # #       # # ###     # ## # #  #  #
#   g   f        # ####   ##       ###       # ## # # ## #   #a# # ##        #   #    ###     # #     # ##           c#  #
## ###                         ##    b # #####a## # # ##r# ### #      ##     ###        # #     # # # # ##  #### #  # #  #
##             a##   #         #   ##### #     ## # #a##     # # # # ##   # ####    #     #   #     #   ##  b ##    # ## #
#g           t       #   #             # # #a# ##     ## # # # #     #   ##   ##      #A       A### ### ### # #       ## #
#      #                 #   # ##  ### # # # # ## ###a## # #   # # #     ####     ## #                r ###   #  # ##### #
#  #   #  #                 ##       # # #   #           #     # # #     #       ###      #     # #  #    #      #  # ## #
# ##f  #b #   #   #c      b        #    a##### ######### # #   #   # #      #                #  #    # ####   ## # ## #  #
#      ## ##  #   # ##       # ### ####  ##        #             # #        g     #  #       # #### ##  #b# # ##      #  #
#          t  ##  #  #   #   #    f######## ##############    #  # # #   #                ## #      ## ## # # ## # #b    #
####    # f l            #    r                  a #    a              ##     l    #    #    # #f## ## ##     ## # # ##  #
#      t#          f               ## ############ # ##### #  ##   #   ##   # #        ## #  # #       #### ####     r   #
#          #    #      # #########       ##           ab      a  r                 #   ## #  # # #   # #### ## #   ####  #
#      ### ##  ###    ##         #  # # ### ### ####### ##    #  r           r    #  #         # ##  ####c           #   #
# ##                               #### a       ##   ##          # #     #        # ##     # ###       ## # #      ### # #
#          #    f   g              ######## ###### # #####    ## # #     ##               #  ######   ##  # ## b # # # # #
# #t   l   #  #t    #  #                r    a a      a       a    #                ## ##   # ## ## # ##     #A# # #  b# #
###  ####  # ###### ####     g  ## #### ###     ##### # ##    #  # #                 #         b ## # #   #  # # #   ### #
#t                               # #### #    #  ## #  #  #    #  # #     #      ### #      ####   #   ### #      #  t### #
##    b # ##   #  #   #          # #a   ###  # ### #  # ##    #b   #  #        #    #  ##     #  ## # ### # ## r     g   #
## ##   #     ################ f   #b##a#          #a         # ## #                             ##       #  #   # # # # #
##                     l    g      a a  #c#  a######### # # # #      ####  ##  ########   ###### ## # #####      # # # t #
## A          f f       #  #    #  # ## #     # ####### #a# #r# #### #####f######f### # # ##    ### #   # # ## #     ### #
##              #      ### #### #    a# #r# # # ##   ## # # # # #          ####       # # ## ### ##    ## # ## #    r##  #
#              ##          r    ##  ### ### ### ####   b            ### ####      b#           # ## #  ##      #    b##  #
#         ##    #        #                            #########     ######## ####### #### ###### ## #  ## # ## # # ##### #
#        b #      l      #                            #########         l                                   gf     gfg   #
#######               #            #################  ######### f   ##### ## ##   # #   ##  #### ## #  ## # ## # # ##### #
#          f           ###        t#################  #########   f ##### ## ## #   #   ## ###   ## #  ## # ## # # ##### #
#     g  g        g    ###          g          b           ####                                  r                  b    #
###########  ##################                    A       ####     ##############################  #  ## # ## # # ####  #
###########r ##################         ###   ###  ##  b            ##############################  #  ## # ## # # ##### #
###########  ##################    rt   ###f g###  ##            f    rb    r                       r                    #
#            ###  b r                   ###g  ### f##     t         #### #### #####  #############  #   # # ## # # ##### #
#            ###                   ########   ###  ##   #####       #### #### ##### ##############  #   # # ## # # ##### #
######r #############  ###  ###############   ###  ##   #####    r                                                   a   #
######  #############  ###  ###############   ###  ##b              ##############################  #   # # ## # # ##### #
######  #############  ###  #######       t   #######            ## ##############################  #   # # ## # # ##### #
#       ###            ###                    #######            ##                                          b           #
#       ### f     r    ###           f       g##         ##      ## ##############################  #     # ## # # ##### #
######  ##################  ########  ###### f##         ##   ##### ##############################  #     # ## # # ##### #
######  ##################  ################   #              #####                                 b                    #
######  ##################  #######       b   ##   ##         ##    ##############################  #     # ## # # ##### #
#  ###  ###                     rA     r      ##   ##   ########    ##############################  #     # ## # # ##### #
#  ###  ###             f            ##    #####   #    ########                         r                   l f         #
#  ###  ###  ###  #############      ##  f #####   ##   ########    ######### ############ #######        # ## # # ##### #
#  ###  ###  ###  #############      ##  #######   ##   ########   r######### ############ #######        # ## # # ##### #
#t ###  ###  ###  #############    r  #  #######   ## b ########            g     lg          b              r g      r  #
#  ###  ###  ###           c###      ##  #######   ##        g      ################ ##### #### ##        # ## # # ##### #
# r###  ###  ###t           ###      ##            ##               ################ ##### #### ##        # ## # # ##### #
#  ###  ########  ###  ###  #######  ##             t        ####### ### # # ####        f                # ## # #   ### #
# c###  ########f ###  ###  #######  ##                      ####### l # #   #  # l                         #  #   ###a  #
#  ###  ########  ###  ###  #######                ##        #######   # # ###  ###                       ###  ###   #   #
#     t ###  ###  ### t### r###  l                 ##  #############                  # #           # #     l       a    #
#       ###  ###  ###  ###  ###    ######  ##      ##  #############      t     # #   # #           # #t  # #            #
#  ###  ###  ###  ###  ###  ###    ######  ##    lt##b ############### ###      # #                       # # l    ### ###
#  ###  ###  ###  ###  ###  ### r    f     ##      ##  #############  #  #     g  t l ###           ###  t         #     #
#  ###  ###  ###  ###  ### r###             #  f#################### ### ### #          #         g #          # ### ### #
#  ###            ###  ### c   f           ##   ####################         #          #           #          #      l  #
#  ###            ###  ###                 ##   #################### # ### # #### ### ###           ### ### #### # ### # #
######  #############  ###################### r #######    b        ##  #  #  t#g #   #    ##   ##    #   #  #   #  #  ###
###### t############# f######################   #######              # ### # #### # # # #           # # # # #### # ### # #
######  #############  ######################   #######b  g        #            ##  #   #           #   #  ##            #
#  ###     r ###b    ff     ###    ##########   #######            #            # # # # ### ##### ### # # # #            #
#  ###       ###            ###    ##########   #######    t       #  # #         #   #        #     ##   #     t   # #  #
# g###  ########  #############c   ##########  b#######   #####    #  ###       ### ### # ### # ###   ## l###       ###  #
# g###  ########  ############# f   r           #######   #####    # ## #               #  #  #  #  #  #            # ## #
#  ###  ########t #############      b  f      t          #####  ### #         a# ### ### ### # ### ### ### #         l# #
#       ### t     ###     r tt  r        ####                    #### ###   #   #  #  #               #  #  #   #   ### ##
#   f   ###       ###t  g         c  f   ####  ###          b    ###    #   #   ### ### ### ##### ### # # ###   #   #    #
######  ########  ###  ########    ##########  ###     ##     ######### #   g          r      #    l                # ####
######  ########  ###  ########    ########## r        ##     ######  #                       #                       #  #
######  ########  ###  ########    ##########          ##  g  ######  ###       # g      g    #             #       ###  #
#       ###       ###  ###  ###        t       t       ##   ########        #   #                           # g #        #
#       ###       ###  ###  ###                    g   ##   ########  # #   #                                   #   # #  #
#  ###  ########  ### f###  ###    ################         ######## l# #                      t                    # #  #
#  ###  ########  ###  ###  ###    ################        b########          lr                                       r #
#  ###  ########  ###t ###  ###    ################  f##############         ###                   b         ###   f     #
#  ###       ###         A  ###   r################   ##############         l #             g#  t  g        #           #
#  ###       ###            ###            r          ##############   c    l  ###            #            ###         r #
#  ###       ###            ###    l  g               ##############             #       g    # r          #             #
#  ### r     ###            ###     ##r               ###############   t     f  ### #### ##     ## #### ###      l     ##
# r###       ###    f   r   ###g    ##      ################                       # #l       #        # #              ##
##########################################################################################################################
