metadata:
  gen_time: 4.357304096221924
  timestamp: '2025-04-18T22:58:25.316852'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#  #   ##   ##   ##t  ##   ##   ##   ### #### ###   ##   ###g ###     ##        ##                  ##        ##     ### #
#r    g##   ##t  ### #### #### ####       ### #### ###   ###   #    ######            #        #            ######    #  #
####  #### #### #### #### #### ####t##    ##   ### ###  g##        #########        ####  ##  #### t      #########      #
##### #### #### ###   ##   ##   ##   ##  ###   ##   ### ###f        ##  #####       ####  ##  ####      b#####  ##       #
# ##   ##   ##   ## b ##  r##   ##   ##  ###   ##r            ##          ##         ##        ##         ##          ## #
#                                              ## l ##  b###  ##                 #   ## g      ##   #             t   ## #
# ### ###   ##  r##b  ### ###   ### ###   ### ###   ##   ###                   #### t   b        r ####     c            #
# ### #### #### ###   ##                  ### ###   ##                        r####   t  #  #      ####                  #
####   ### #### #### ### t ### ###   ##   ##   ##r  ### ###  g          ##       #     ########     #   t r ## g      f  #
####   ##   ##   ### #### #### ###   ### ### b ### #### ###       ##   ####        r   ########            ####   ##     #
# ### ###   ##   ##   ### ###   ##   ### #### #### ###   ###     ###    ##              ##  ##              ##    ###    #
# ### #### ###   ##   ##                  ### ###   ##  t###  t  ####        r          ##  ##        t  r       ####    #
# ## t ### ###g  ##  b##   ### #### ###       b##   ##   ##       ##      r                                       ##     #
# ##   ##g  ### ###  A##   ### #### #### ###   ### #### ###                 ##                         c##               #
# ### ###   ### ###   ### ###   ##   ### ###   ### #### ####          #   #####                        #####   #         #
#  ## ###   ##   ##   ### ###   ##   ##   ## r ##   ##   ###  #     ####  #####             t          #####t ####     # #
#t     ### ###   ##  A##   ##   ### ###   ### ### t ##   ##  ###    ####   ##   g                r       ##   ####b   ####
# #    ### ###g  ##   ## b ### #### #### #### ###   ### ###  ###     ## t      r     ##        ##              ##     ####
# ### ###   ### #### #### #### ###   ### ###   ##   ### #### ##                 ##   ##   ## t ##   ##                 ###
# ### ###   ### #### #### ###   ## f ##        ##   ##   ###  t       gb      #####      ####      #####           b     #
#  #   ### ###   ##   ##  r##  r##   ##   ##   ##   ##   ##       ##      #   #####    r  ##       #####   #     b##     #
#      ### ###   ##   ##   ##   ##   ##   ##   ### ###   ##      ####   ####   ##         t b        ##   ####   ####    #
# #   b##   ##   ##t  ### ###   ##   ### #### #### ###   ##       ###  #####          ##      ##          #####  ###     #
# # # ###   ##   ### #### #### ###   ### #### ###   ##   ##  #  b ##    ##            ##      ##       b    ##t   ##    ##
#     ###   ##   ### ###   ###r#### ###   ##   ##   ##f  ### #                                      c                    #
# #    ##rt ##   ##   ##   ##   ### ###f t##   ### #### ####                        t                                  r #
#      ##   ### ###   ##   ##  f##   ### ###   ### #### ###                     ##    ##      ##    ##                t  #
###    ##   ###t#### #### ###a  ## b ### ###   ##   ## t      ## b   ##   ##   ####  ####    #### A####   ##   ##     ## #
###    ### ###   ### #### #### #### ###   ##   ##   ##   ###  ###    ##  ####t ####   ##      ##   ####  ####  ##    ### #
# #   #### ###   ##   ##   ### #### ###   ##   ##   ##   ### ####         ##    ##                  ##    ##         #####
#     ###   ##   ##   ##   ##t  ##   ### ###   ##   ### ###   ##          ##  t                          f##          ## #
###    ##   ### ####g###   ##   ##   ### #### ###   ### ###   ##    ##                                b         ##    ## #
####   ### #### ####l#### #### ###       b### ###b  ##   ##         ##          ##      #    #      ##          ##       #
# ##   ### ###   ##   ### #### ###   ## g ## t ##   ##   ##             bc    #####   ####  ####   #####r           l    #
# ##   ##   ## tt##   ##b  ##g  ##   ##   ##   ### #### ###   t     t     ##l #####   ####  ####   #####  ##    r      b #
#              b#### ###   ##   ##   ##   ### ####b#### ####  ##          ##   ##      ##    ##      ##   ##    l     ## #
####   ### #### #### #### ###   ##   ##   ### ###   ##   ### #####                    r##    ##                     ######
#####  ### ###   ##   ### ###   ##   ##   ##   ##t  ##   ##   ####                                                 r#### #
# ##   ##   ##   ##   ##   ### #### #### ###   ### #### ###     #     ##  ##                              ##  ##r    #   #
#      ##   ### ### t ##   ### #### #### ###  b### #### ###         ##########        ##      ##      f ##########       #
###    ##   ### ###tt ### ###   ##   ##   ##   ##   ##   ## g    r #############b    c##      ##      #############      #
###    ### ###   ###  ### ###   ##   ##   ### ###r  ##   ###   ##   ##  ##  #####     f              #####  ##  ##  b##  #
# ##   ### ###   ###   #   ##   ### #### #### #### ###b  ##    ##             ## b                    ##             ##  #
#      ##   ##  ###    #   ### #### #### ###   ### #### ### r     t                  ##        ##                        #
###            t###    #   ### ###   ##   ##   ##g  ###g###g         ##             ###   ##   ###             ##     r  #
##               ### #  # ###   ##   ##   ### ###   ##               ###    #   ##  ####  ##  ####  ##r  #    ###        #
#  ## ###   ##   ### ## # ###   ### #### #### ###   ##   ###        ###   ####  ##   ##       r##   ## b####   ###c      #
# ### ###b  ##   ##   #        #### #### ###   ### ###   ###        ###   ####                          ####   ###       #
####   ### ###b  ##   ##   ### ###   ##   ##  a### ###   ##   ##     #     ##  t       g            l    ##  r  #     ## #
####   ### #### ###t  ##   ##   ##   ##   ## t ##   ##   ##  #####                                                  ######
#      ##   ###t#### ###   ##  r### ###   ##   ##   ### #### #####      t            ##        ##                   ######
# ### ###   ## l ### #### ###   ### #### ###   ### #### ####   #      r            #####      #####                   #  #
##### ###  b##   ##   ### #### ###   ### ###  b### ###   ##              ##       r#####      #####        ##            #
####   ##   ##   ##   ##   ### ###   ##   ##   ##   ##   ##             #####       ##          ##       #####           #
#      ##  A### ###b  ##   ##   ##   ##  b### ###   ### ###      ##     c######  t                     ######      ##    #
# ### #### #### ###   ### ###b b###b#### #### #### ####t###     ####       ####       t   ##        r  ####       ####   #
# ### #### ###   ### #### ###   ### #### ###   ### ###   ###   t ##          #                          #          ##    #
# ##   ##   ##   ### ###  g### ###   ##   ##   ##   ##   ### #                    #       t c      #                    ##
####   ##   ### ###   ##   ### ###   ##   ### ###   ### ###  ##  f    b##       ####              ####       ##        ###
####   ### ###  ###   ##   ##   ###  ### #### #### #### ###  #        #####     ####    ##  ##    ####     #####        ##
####  #g ##t## ##         ## t    ##       #  # ## ##     ###  r   b       ###############b     ############# tt      ####
#   A       #    c         #     ##  c           # #       f      g               #### f      t #############         ####
####      # #    g                           fl  # #      ###         l    t   g  ####       t  ## c      g##        a####
#  ##    ## ##    ## ##t               ## ##    ## ##    ##     c              l  ####   l     c##     c r ##           ##
#       ## g       # #   ##        ##   # #  t      ##       r r###################### r        ##lgb g    ####         ##
# b##   #        t # #   # f        #   # #          #   ##  g b######################           b    b    ####         ##
#  #          #l  ## ##         t      ## ##   #          #    c########        b   l  c          t     g  ####### #### ##
#  b          ##              ##              ##                    g###     g   b           b             ####### #### ##
#       b                         g                          g       ###l       f cA        c                    # #### ##
#     ##            ##   A              ##            ##       #########     t    g      ####     f l       ar## b  c    #
# ##   ##  ##   #    ##    ##    ##    ##    #   ##  ##   ##  t######### lgag     c      ####      #############  f      #
### f       #   ##    ##    #    #    ##    ##l  #         ##      ##### c###       r    #### b c  ################t     #
#                l   c ##lc          ##   c                   f    #####  ###   gl ########c       ################      #
###  ##         ##      ##          ##      ##        l##  #################### cb ########      t       ##########      #
# #  #    ##    #                  b         #    ##f   #  # ##################   c##        g  c  ##    ########## b    #
#          ##                #  #                ##       b  ####f     ##########  ##     c        ##c   ###### lf      l#
#           ##   g # #      ##  ##      # #     ##        b  ####      ##########  ##        t     ##    ######       # ##
#  # t            ## ## ##          ## ## ##   g          #   #### ######################## ######### l  ######cc c   # ##
#l##                  # #            #b#                  ## f#### ########################A###################g  f   # ##
#        ##t l g      # #     c      # #           ##        ###    b######################   c   ###########     g   # ##
#     g   ##  ## ##  ## ## #      # ## ##  ## ##  ##         ###    b######################       ###########f     r t# ##
#  #           # #   #   # ##    ##g#   #   # #        b  #  tc      ###################### l   b #############  l  t # ##
####   b  ##   # #          #    #   f      # #   ##      ###bf               #############       #############       # ##
#          #  ##g##             A          ## ##l #              t   ###lb    #####  a     f     c#############     ### ##
####              ##    ## l     r  ##    ##              ###        ###   l  #####               #############   l ### ##
#  ##  #           ##    ##        ##    ##           #  ##       r  ##############    ###          b########t      ### ##
#      ##g    #     ##       c          ##     #    f## t    ###################### gg ### l         ########       ### ##
#  ## g     b##      ##    t ####   l  ##      ##t       ##  ########################  ##########    ########   t        #
#  #      g  #                ##                #         #  ########################  ##########    ##########l     r   #
#    l        b b##      ## g      ##  c  b##      tt  t     ########################b ########################  ll     l#
#       ##        #     ##  r       ##     #        ##f        ######################  ########################  b       #
#    #b  ##  #        f                    tb   #  ##tb #      ######################  ##########################  ####  #
##  ##l   t  ##             #    #r            ##       ##  #  ######################       #######       ####### c####  #
#####         t   ##   ##  ##    ##  ##   ##        f    ####g ######################    rc #######       #######  ####  #
#       ##   t    #   ##   g          ##   #        ##        r######################       ####          #######  #### g#
#####    #               t               l          #    ####  ##b     ##############       #### g        #######  #### ##
##  #c      g ##    l      # #  # #      t    ##   l     #l #t ##               cb  c l   g   ## lc       ####### g#### ##
#             # l    #    ## #### ##    #  b gb#               ####    ####     t     fg   r  ##c  l   ##########  ####  #
#       # # b      t##                  ## g      c# #       ######                     f r      t     ##########  ####  #
#  #   ##g##     #        ## #### ##        #     ## ##   #  ######    ###############  ####           ##########    ## ##
####            ##         #    # #     b   ##c       c   #########    ###############  ####    l      ##########    ## ##
#              ##          # #g # #          ##              ####      ########################## t    ##########c   ## ##
####  r##     t           ##g#### ##    l            ##   #######        b#######################t     ##########    ## ##
#  #  ##       ##             ##   l         ##       ##  #  ####      c  ######################### c  ##########    ## ##
#           #  #    ##     t   g        ##    #  #               c    l   #########################    ################ ##
#         l##   l    #   ##        ##   #    g   ##       g    r   cc  t  #########################          ########## ##
##                       #    ##    #             t         # t##  f                                          ######### ##
###               b       c  ####    c             t    c  ##a ##           t#    ######      ##      ##rc    ######### ##
# ##  ##    #          r           b             #    ##  ## c   r  t        ###  ######  ### ##t     ##         ######  #
#  #   #    ## ##g  ## ##            ## ##   ## ##    #   #          ##### ############## ### ##   f c## t   ### ######  #
#            # #     # #    ##  ##    # #   A # #  t b       #       ##### ##############   #  #  r l ##f c  ###    c## g#
#           t# #     # # b   ####     # #     # #            #    l  #####   #############  ## #      ##     ######  ## ##
#           ## ##   ## ##     ##  g  ## ##   ## ##c                  ##### #     #########  ##        #############  ## ##
# #     ##      ##                          ##   g  ##   c #           ### #####  ########  ####     l#############  ## ##
###    ##               t     ##             l  g    ##t  a##  ## ####  ##           ##### f####     g########lc     ## ##
##              ##  ##     l c##   r    ##  ##         b    #  ## ##### ## ##      # #####tl####        ######       ## ##
#   c          ##    ##  ##     a  ##  ##  b ##              ####    ## ## #########  ##########      #  #####    r  tc  #
#    ## l  #   t      l g#          #             #    ##    ####  bb## ##   ########  #########   c     #####   b  c    #
#     ##  ##c  ##          t              g  ##   ##  ##     ####    ## #### ########  ######       tg    #######   f##  #
#             ##                 b            ##  b         t####     g ####     ####  ######     g    rt #######   b##  #
##########################################################################################################################
