metadata:
  gen_time: 4.0776591300964355
  timestamp: '2025-04-18T22:50:41.198938'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
##     # #   ## #  c  ###    #  ##             #                g   #       #                  ##   ###  ## ####   ###   #
###               #   ##r    #   #   #                             #####rt  #     A##          ##     #      ##    ###  ##
####  # ##                 l###     ##   ##                            ##   ##  #  ## #    ##                ##      #  ##
#     # ## f                ###          #       ##                 ## #        #          ##         #                  #
#                 f       r ###                   #    #             # ####   #             #    ##   ###    r       #   #
##     l      b           l                           ##                     ##t    #            ##   ###f    b      ### #
##            #       #     #      ##          #                   ######     ##### #    ## #           #            ### #
#             #         l      b   #     #     ##    l           #                     ###  ###    c   A    g        #   #
#r            #             #            ##           ##       ###       #   t #        ### ###         #     ##         #
#      #      #      #t   ###                         #    ##    ####                 # ###   #    ##   ###   ##     #   #
#   ##  f     #l     t    l          ##                    #                g                      ##   ###        ###   #
#  ###            r   # #      ##     #        l              ##   # l         ## b        #  #           #        ###   #
#  ###             ##   #t     #                        cl    #              c #           ####                      #   #
#    ##    r            #                       ##            #           #   l g          ####      ##   #              #
# #  ## b                 c #       g       ##   #        #               #####       ##   #  #  r   ##   ###  ## r  #   #
#    ##  #                  #  #     r      #  A         ##                           ## l        b       ###  ##  ###   #
#       ##           b   #  ####  ##                                #          ##   ####   #  #  ##   g b   #      ###   #
##   ####### # #             ##    #            ##          r               r  ##     #########  ##         g      #     #
##  g     #    ##            ##     r ##         #      ##  #        #####    ## t   A#########      ##     #            #
#   Ag                  l      #       #     b l        #          ###      ####      #    #  #   f  ##     ###    #     #
# # b    r             r                                   l       ###    ######               b            ###  ###   ###
#  t      l#      ###             ##           ##                  #  g   ##     #        ##  #     a     f #    ###   ###
#                 ####      f      #g        A  #           g              #     ##  ##  ######  ## g  ##     g  #     # #
#  b     #              #  t              #                        #         t    t  ##  ######  ##    ##   #      r     #
#  #             b #  # # r           #   ##  f                   ##        #     #####  ###  #   r         ###  #     # #
#  #     #       ###    #  #          ##g              g      #####     # ###     ####   #                  ###  ###   ###
#  #    l    #######    # r  #                      ##        ##          #    #g ###   ##    #    t    ##   g#  ###   ###
#  ##   #########            ##                     #          #              ### # #         ###  ##   ##         #     #
#  ##   #            t       ##         ##            r  f   ###              #               ###  ##         #r       f #
#   # ###       f   f   # ##          l  #         l    #   #  # #      t   #                   #           ###    #     #
#     ###                                 t             ##  #  #### ##      ####        g#      #           ###    #f    #
#  ##   #    #    t   g       c                            c        ##      ####       ####   ###  ##         #          #
# b##   #    #f    ## g#        f      ##                    ##      #      ###     #  ###    ###  ##   ##b     b  #     #
######       #         #     l          #             lg                    ##                #         ##    #  ###   ###
#####      b     t     # l#    #                     l r##       b          ##                              ###  ###   ###
#r   b  #f             #  ###       ##          ##       #   ####           ##          ## #  #   b         ###  #     # #
## f      ###             ###       #            #           ##          #####  # #        ####  ##    ##   #            #
###                    b  # #           b                             #############     #r ####  ##    ##        #     # #
#              r     #   f  ##                        ##                        #          #  #             #    ###   ###
#          b       ####    ####     ##       ##        #                             ##                     ###  ###   ###
#      # ##  #### l#####             #   ##  #            l               #                # f#      ##     ### l  #     #
# #### l #  t#      ####      #           #                 #      ###                     ####      ##     #            #
#        #          #     l                           l ##  #    r  l#     g       #   l   ####  ##                #     #
#     #             #r      r                   b        #   r             # #       r  l  #  #  ##         #      ###  b#
# #  ##   f                #b              ##                ##      #     #    ## #        g             ###  ##  ###   #
#    ##   ##  lr     #                ##    #                #       #g  ###    #     l    #  #      ## b ###  ##    #   #
#       ####        ##  #   #        l #                #    #   g # ##  ###    #     ###  ####      ##   #              #
#    #         ##      f          #                     ##       #   ###             ###a  ####                      #   #
#  #   l #     ##         #       ##        ##         r        r##      #       ##        #  #           #   a    ###   #
#  ###         ##      rr #             #    #               #  ##                #     ###f       ##   ###        ###   #
##     f  A    ##        ##     r      ## l            #                                  #   #    ##   ###   ##     #   #
## #  #        #           b                       #   ##    a f       ##      #        g   ###         #     ##  b      #
##                             ##  #               ##          r    ##      #  #####  ##    ###   b                  #b  #
##                            ##   ##   g##  ##                #    ## #    #  ###   ##     #          a#            ### #
# b l                         #           #   #              ###f#  ##          #                ##   ###            ### #
#     ##                      #l          t        f                 #              #     # #    ##   ###A      f    #   #
#                 r#          #     c        l        g              #            # ###   ###         #                  #
#        f   b                #      ##            ##      l                         ##  ####f               ##      #  ##
#                             #      #   f         #    #    ##     #          ##  #####  #    ##   f #      ##    ###  ##
#  #                  #        g         ##             ##   #      ###   #     #   ###  ##   f##   ###  ## ####   ###   #
###    # ###    b             #   ##  g    #    #  f    ##     #   #   #        #   #   #    ####    ##     ###    ##   ##
#cr     ###                               ########             a# #    #        #    # #   # ### b    #  #         #    ##
###       g   ###               A         ########          f    #   b #        #     #    ##l#       #  ##   ##   #    ##
##             ###                          ####          t            #        #          ###           ##        #     #
#             c ###       c  g ##     ##      f     ## b   ##         #          # r       ##   l     #  ## #  #        ##
##                   r    ##   ###    ###          ###    ####### r  #            #    ###  #            #  ## #   ###  ##
###          g          # ## # ###   ###            ###   ###    #  b #          #    #    # # ##     #     ###    ###   #
####   r          l         ## ##   f###   ##  ##   ###    ##     #    ##########    #b       ###     #  #   ###   ###   #
#  ##     #    #        ##  ## ##   ###   ########   ###   ##    #          t         #    # #### #g  #   #  ###   ###  ##
##        ##   ##     gg# ##         ##   f######    ##   f     #                      #     ####  #  #  ##   #    #   ###
##   c    ###  ##         ###                ##                  #         f          #    ######   # #  ## # #         ##
#    #     ##  #       c     l                                    #   r              #                 # ## ##          ##
##   ## c   #         #                                            #       ##       #      #l#  ##        # ###     #   ##
###  ##              ##           ##   t                ##          #        #     #                   ###   #     #     #
#    # ##      #     ##   b      #####   ##  ##  ## t #####         #    #   b#    #     b                     #    #   ##
#      ###     ##     #           ####   ##      ##b  ####   #      #     #  #     #      #   r  ###    #    # #         #
#            f ##                r  #           f      #      #      #    # b#    #r     #    b   ##    # #             ##
##           ##               # f                              # #    #    ##    #    # #  #  lc   # #    #        # # ###
## # #    c ####                        ##  f     ##            # #    #        #   b#g#   ##  l          #   #    ##   ##
#    ##                       #     b  r##f       ##               #    #      #    #      ###       ####    ###   #    r#
#### ###        r      ###                                  r       #    #    #    #       ####       ##### ####        ##
###  f###g    ###       ###  f   #                        #   r      #    #  #    # b   r  #####   b   ##### ### # #     #
#              ###       ###    ####       ##  ##       #### #       #     ##     #       #######     r ### A # #       ##
##              ###             ####      ########      ####  # #    # f    #     #    #   #######    c  #  #    # # #  ##
## #       g       b c        #  ##   ##   ##  ##   ##  r##    # #   r#   #  #   #    # # br#######         # #     #    #
#            f        ###   c     f   ##         f  ##            #    #  #  #  #    #                             #     #
####                   ###           ####      r   ####            #  #    ##    #  #                               ##  ##
###               r             ##   ####          ####   ##    a   ##           b##b                              ###   #
## b      ###g         r        ###   #              #   ###  #                    r     #                          ##  ##
#      b ###    ###     b      ####r                     #####                            ####   #######     b ####  #l###
#        ###    ###             ##           ##           ## # #                        # ##### # #######     l ####  ####
##        ###                        ##b  r ####     ##       #               r          #                             ###
###    c                     b g     ##      ## r    ##      g      ##            ##       #####    #######      b####  ##
####                   ###        fr         ##           f        #  #     #    #  #       ###    # #######           # #
#                     ###    g #            ####         g  #     #    #  #  #  #    #       ## #     #######       ###  #
## #                          ##    ##      ####      ##    #l # # b  #   #  #   #    # #            # #######       #  ##
##              ###               ######     ##     ######    # #    #    r##     #    # #b             ###            ###
#              ###       ###      #######          #######   #     b #     ##    l#       #      #       #  ####  l    ###
# #   ###     ###       ###        #  ##      r     ##  #            #    #  #  a #                        ###### b b   ##
# ## ###   g           ###                  ####           t        #    #    #    #         f             #######       #
# ## ##               c       #             ####                   #    #      #    #                   #   #######      #
##   #      ####    a  c       ##      ##          ##  b   ##   # #    #        #    # #      al      #      #######     #
###          #  #             #####    ##         b## t  ####  # #    # l  ##    #    # #            #      #r######   tt#
#        a     ##              ####                      #### #      #       #    #      #              #    # ##### #   #
#     ####     ##   r #         #          ##  ##          # #      # lr  # r#     #   b  ##               ##   #### ##  #
#      ##      #     ##          f   ##   ########   ##             #    #    #    #       ##b   r      ##       ### # ###
###  ##t             ##             ####   ######   ####  g         #     #  #     #       ###         t #        #    ###
##   ##     #         #         f    ##      ##      ##            #     g ##       #      #### t                     ####
#    #     ##  #                        g     b                   #                  #     ####  r rg        #        ## #
##        ###  ##         ##    #                          #     #           r        #    ######   t   l    #        #  #
#         ##f  ##       # ## # ####    ##  ##  ##  ## r  ####   #   l                  #   #######   r      g           ##
# ###     #    #    c       ## ####  ################## r####    #                  r #    ########              ##     ##
####           g   b    ##  ##  ##   ##################   ##      #    ##########    #     #########l            #       #
###                     # ##          ##  ##r   ##  ##           #          g    #    #   t##########  a  g      # l#    #
##           g            ###                                ####    #            #    #### ##########   l       # ##    #
#               ###         g                                        g#          #           ##########   t              #
##            f###               #r                       #           b#  g     #             ##########        l  ##### #
###        r  ###               #### r        l      f  ####     #     #        #     #     r  ##########        #  ######
#       ###                     #####     ##    ##     #####    #      #      l #      #        ##########      ### ######
###      ###        g         #   ##    ############    ##     #r  #   #r       #   #   #        ##########    #####t#####
##########################################################################################################################
