metadata:
  gen_time: 12.693287372589111
  timestamp: '2025-04-18T22:55:49.460207'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#    ############   ########                             ###   # ##     r            ##f ar   #    #######      #   ######
##   ############   ########                        #ag# ####  # #                    ##    ### ##########   #### ########
## a ############g  ########               A     #g #### ##    # #                     ##  t                    g        #
##   ############    l        ### # #######a#  #b####### # ## r# #f                    l##            r                  #
#    ############ r                                   ## #  #  # # r        g            # #### ##########  #     ########
# g            l               #      ##  ###### ## ## # #  #  # #             r           #### ##########    ############
#                      b      t#  #        ##### #     # #  #  # #       l                   r                           #
#  ########         ############  # #### #    a#  ###### #  #  # #                         ###  ##########   #############
#  ########t ### r  ############  ##f###   ##  ##   ### ##l # b# #                         #     ##   ##      ##         #
#  ########g ###    ###########g      ##c  ######   ##a        # #                       t     #### #### #  #### ###  ####
#  ########  ###f   ###########    ### ############## ###     ## ##                    tr     ###        #               #
#  ########  ###    ##########               #        #  #    #   ## #####################    #        r                 #
#f ########r l      ##########  l #    #### #  # ####    #g                          fr     ##  ## #####    ### #   ######
# r########  f      ########## a  # # ###  ##  ##  #####      #   ## ################## ##       #   ##                 ##
#  ########     r   f              A               #   #  ### ## ##                         #####   ####    #      #######
#  ######## r##f   rl      t                 #### t#   #   ##  # #         t                        #                    #
#  ########  ##t    b            #  #   #  #    #  #   #      c# #                          ###   #### #      #   ########
#  ########g ##               #   ###    ###    ###    ###     # # f                 b      ##   ###   #    #     #  ### #
#  ########       g###        ########################    #    # #         b    l                # #            #l# r# # #
#                  ###      rl##   ####    a      a  ####  a#  # #           f              # #  # #r           # # l# # #
#       t       g l###             ###    f   cbl    ####   #  # #      l            l        #    #         #    #  # # #
#   #########t     ###  ###    ####### #### ###############    # #                         ##r   ###        ##  ##       #
##  #########      ###  ###                    f###    ###     # #                          #    ####           #   ##  ##
##  #########      ###  ###g  f  #  #   #l # t  #  #   #t #    # #           b              #     g                    f #
##  #########  g   ###b ###  #####  #   #  ######  #   #  ##   # #                         #     ## ## #      #####   ## #
#                       ###  ###### #l  #  ##  ##  #     ###  ## ##           rb                  # #  #      #          #
#   t                                          ##   ###  # l  #   ## ################## ##          #  #     ##         ##
#  ######   ########              # l######g#  # ## ###  #              f                     # ## ### #    ### #  #    ##
#  ######f  ########  #########   #  #       ##      ##       # c #  ################## ##           #                   #
#  ######   ########  ######### g      ######## ###           ## ##                               #### #                 #
#           ########  ######### ##       l #### # tt##           #                         ## #g ###   #             ##  #
#           ########  ########## g## ### a ##   #   ###        # #    b  c          g      ## #  # #         #    #  #   #
#           ########  ##########  # ###### ## a   ###### #t #  # #                  b      ##g# g# #         #       #   #
#t                 c  ##########  # # a    ## # ##             # #             A              #  # #r        #           #
# ####     f  r       ##########         # ## # ### ## # #  #  # #             t          #r###  # #                A#   #
# ####  ########## r  ##########  # ## t## #    ####  ## # b#  # #  r                    ##   # ## ##        #      ## ###
# #### f##########    ########### # ## ###       ####    # ## f# #        c            f##  #g#                          #
# ####  lc              b        ## ## # t    #  #  ###        # #                  c  ##   # # ## ###             ### ###
# ####  g        l          t  #### #         #     #  # ####  # #                  c ##    # #    ###                 ###
# ####             ####t      r ### #  ###    #  ####  # ###   # ##                  ##    c# #    # #             #  #f##
#  b  #             Arf  #  t                 l               ## ##    #       ##  a #g                    #  l  ##      #
##                            ##       ###      g ###       # #g ##  t ## ####      ##   #                       ##      #
###             A            ####r    #####    t #####     ## ##  #    #### ##  ###  ## ##           t     #     ##      #
#                            bl###   #######     ######   ### #####l##l  t     ##    #  #            t  r  ##    ##      #
#       t g#     g  #         t###  #########g #########r ###   a#  ##       # #       t## ### ####                      #
#     b   ##        ##         ###  ####################  ####      #  #     #b##f  ##      ##   #### ## ## #  b  #      #
#              ##fft           ###  #################### a######   ### #       ##  a  t # #  b     ## ## ## ####  ##     #
#     #                  #     ###  ####################r ###        #b  #####        ##############g    #t     ####     #
#     ##  r             ##   b ###  ####################  ####   ##    ###  ## ##   ####   #   g####     r         #######
#       r   ##    ##           ###   #################    #####  ###   #     ###     # ###    f    ##### ## ##########   #
#     l      #    #        r   ##     ################ a bt#   t         ##       ####   #             g        ###r     #
#                 b                       a g             g  l  ###   a  ## ##    #l#             ###   ####  ###     t  #
#       t                         a    b  f     a       r    t    #      #  #          ### r        #####   #            #
#              t               f    ##      f##       ##  r   g #### ##f    b  a     a #b#       ##        b##       f   #
#      ##    fc        ##          ####  a  ####   aa#### f    a#  ### a f  ##    ###    a    tt ##        ##            #
#       #              #          ######    ####    ######    # # ###       #  t   ##  ## l      ###       ########b     #
##         ##      ##         #  ########   #### f ########   #   #b    ## ##  ##     ##      f  ###  f###################
##          #  ##  #          #  #########   ##  a#########   ##    #  r l #          #a   ## #   #####      ##   f   r###
#              ##                 ########    a  b########a g  # ## ###    ####a  #   a    ##  ###   ###              ## #
#            bb      b        t    ######  g       ######a t  ## ##      #  ##   ##   #####          ##             b #  #
#        f b g                     ######rl        ######     ##  ####   ####     ##    ##           ##              ##  #
#       r      ##                 ########        ########t    # g #       #   #####     ##           #              #   #
##          #  ##  #          #  ######### t ##   #########   ##   ## ###      #      g   #         g ##            #  ###
##   r     ##      ##         #  ######## g ####   ########  ##  # #####    #     ##    ###           #             #    #
#       #              #          ######a a ####    ######    #  #          #  ##  #    ##  r         # a          ##   r#
#      ## f      t     ##         a####     ####t  f ####     #      f  ## ##   #  ## #  ##           #            ##    #
#                             l   f ##       ## gl    ##      ##        # g##       # #################            ##    #
#                                          la                  #             b     ##              #### ############     #
#                         r     f    aa      f           t   # ##     g   ##b##    #      b       r                   #  #
#            #    #            ##  a  ################   r ###           b####                                        ####
#           ##    ##           ###a  ##################   ###### #  ###     ##     ### ## ##### # ### ###      ####    g #
#     ##     f          ##     ###  ####################  ###    #    #  l###t     #   #  #g # ##   #####  f  b########  #
#     #                  #     ###  ####################  ####   ##     # ##           ##      ##    ### #     ##    #  ##
#              ##   r          ###  ####################  ##### ## b ## # #       ##  a        ##   ##   #     ##g      g#
#         ##        ##    b    ### a####################a ####  #    # a      #b   #  A   #    ######    #f    ##   ##   #
#          #        #          ###  #########  #########  #####         t  ## #### ##l# # #    ###### ####     ##        #
#                r             ### l #######  a #######   ##### a ###   ##  #  #a   ### # #    ##  #  ######  t###   #####
###                          #### A   #####      ##### a   ## ##   ##       ## ## ####  ###    ##     r     ####     ###t#
##                      r     ##      a###        ###       #  #    ##  ##  ## ##       ##   t ##             f  ##      #
#     #                  #        g a       b            r       ## #   ##  #   ####    #      ##    f          b        #
##b   f ####  ##rl   ##   g# f       ####          ####     c                       t      ##     #       #      ## #    #
######  ## l   ##    #   ######             ####  c   t         ########                   #      ##r    ##      ## ##  r#
#  r##         #   ####      ## ###        ######f       ### ## ########                   #             #       #   #c  #
#         ##   ##      r     #######       ######     f #####   #####                  r         fa       g      ### #   #
# ##  ### ##   g#    ###t   ## #####        #### t      #####a      ###                     ####               # c #  g  #
###f  #####     #  ###         ####                      ####    ##   #      l                ##  ##          ##      ## #
#     #        ##      g       ###     ###        ###     ######r##   #t            g       #  #   ## ##  ###  ##    #####
#     #    ##  #    #######    ##  t  #####      #####     ##    ##   #                     #### # ##  ## ##        ##  ##
##    ######   #  #### l##     #      #####      #####      #        r###                  ## #  # #       ##  ##   ## ###
##    ###      ## ##                   ###        ###                   #             b    ##    ###c##        ##r   # # #
###  ##     ##  # ##   ##  ###   l    b    t ##      r                  ###             g   ##  ##                ## #   #
###   # ##  ##  # ##   ##  ###ll         t   ## l  c                      #  f  g            ## #  c      ## ##        ###
##    ###  b##  #     ##  ##   #        At   ##             #             #        f       # #     #  #g ###  #        # #
###l ##      ##         r ## ###                            #     r       ###                     t## #  #          #    #
#fr   #  ######        b#### ##        ####      ####             r         #   ##### g     ##     ##    #####  ##  ###  #
# ##### #####t# f ## t###    ##     g ######    ######    ac       f        ### #####  r   ###          ## ##        #   #
#  #### # g      t          g##       #######  #######                          #####          # ##  ####   ##    ####   #
# ##    #                    ## ##    ####### ########  c ##                      ###      #   #     #       #      #    #
#    cf  #   ##  ###  #   g    ####    ###### #######    ####                    t#######             g    # #  ## ##   ##
## r   ###   ##  ###  #   #    ####     #####  #####     ####     g      f        #######   #       #      ### ### #    ##
##     ###   ##  ###  #   #    ####     #####  #####     ####                     #######   #       #f     ### ### #    ##
#    l   #   ##  ###  # g      ####    ##############    ####                                              # #  ## ##   ##
# ##    ##          r        ## ##    ################    ##                               #   #    c#       #      #    #
#  #### #  t                 ##       #######  #######           #######                      f# ##  ####   ##    ####   #
# ##### ##### #   ##  ###    ##       ######    ######        ## #######              r    ###          ## ##        #   #
#    b#  ######         #### ##        ####      ####  cg        #######                    ##     ##    #####  ##  ###  #
###r ##      ##r    f     ## ###      c   l   c             #      ###   ##    ###   ##### r       ## # f#          #    #
##    ###   ##  #     ##  ## b #          t  ##             #      ###   ##    ###   #     #f#     #  #  ###  #        # #
###   # ##  ##  # ##r  ##  ###               ##                    ###   ##    ###   #       ## # f       ## ##        ###
###  ##     ##  # ##   ##  ###               ##                    ###   ##    ###   #   g# ##  ##              r ## #   #
##    ###      ## ##                   ###        ###       c           r##          #### ###    ### ## g      ##    # # #
##    ######   #  ####  ##    g#      #####      #####     c#               ###           ### #  # #       ##  ##   ## ###
#     #   b##  #    #######    ##     #####   c  #####     ##               ###     g ##    # ## # ##  ## ##     g  ##  ##
#l    #        ## l            ###     ###        ###     ###           b   ###       ##    #  #   ## ##  ###  ##    #####
### l #####     #  ###  g      #### a                 l  ####               ############   b# ##  ##     r    ##      ## #
# ##  ### ##  t #    ###    ## #####   g    ####        #####  f            ############    ####               #   #     #
#         ##   ##         t  #######    f  ###### f     #####                         #####                      ### # f #
#   ##         #t  ####      ## ###        ######    g   ###                  ##      ######             #    c  #   # f #
######A ##     ## g  #   ######             ####  t        c                  ####       #        ##     ##      ## ##   #
##      ####g ##     ##    #         ####          ####t                      #### g   ### ##     #     c        ####    #
##########################################################################################################################
