metadata:
  gen_time: 5.844725847244263
  timestamp: '2025-04-18T22:48:23.061410'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
###tb          ##               ##             ###############  #########                ######### t        ##           #
###            ##   f          g#####              ###########  ##############  ###      #########      g    r           #
###                             #####   f      r   ########### ############### r###      #########           ff f     b  #
# f   f  t  g   tf         f   a g                 ########### ###############  ######   ###########b        r  cb       #
#  t             t    b                            ##########  #######################g r      #####        r   g r  ### #
#               t    f  t                        ###########  ########################     g   #####  t              ### #
#                        ############### t       ########### #########################        g#########       ###   ### #
###       ####           ###############         ####        ###############      ####         #########    t  ###   ### #
###   t r ####           ####################       # g    g ###    ########      ####      ############       r   r ### #
###       ####           ######################        b  g  ###    ########      ####  ta g############ g      b  r ### #
###    f g########   ##################                   ######   t########      ####      ##### r  ###      ##f r  #####
###     ##########   ##################g ########## b     ######    ########                #####    ###      ##   l #####
### t   ##########   #####g ###########  ####       b     ###### # #########          g     #######           ####   #####
###     ##################  ###########  ####   ###       ###### # #########          g r   #######        r  ####   #####
##########################  #################   ###                g      g            g              ######  ############
##########################  ######  ###############                    t    t         b   t      t  g ######  ############
########################### ######  ###############            t                         ##                 c ############
########################### ######  ###############       f   #######   ########         ##                  g############
###########################  f####  ############              #######   ######## A    #########    #####              g  #
###########################   ####  ###          ####################   ##########    #########    #####b                #
########################  #   #### ####          #################### ############   r#########        r             g   #
########################  #     ## ####          #################### ####       f    #########      g                t  #
##########   ###########  #     ## ################################## #### t          #########                 g        #
##########   ###  ######g #     ## ################################## #### r          ######   fc            f     r     #
##########   ###  ######  #     ## ###        ####################### ######          ######   f  a                      #
#  ######## ####    #####       ## ###  g     ## f################### ######    ############                     a  f ####
#  ######## #### g  ######      ## ###        ## f###############     ########  ############   ## g       t    f      ####
## ######## ######    f####     ## ###        ## a        #######   ##########    ##########   ## t       r   b       ####
##  ####### ######     ####    t## ###    r   ##          ###############  ###g  r##########   ##                     ####
### ####### ######       ##  ##### ###  r     #####     r ###############        l##########   ##      g  g      ###  ####
##     #### ###### f     ##  ##### ########## ##### b     ############### r#################  b##       r       t###     #
##     #### ######       ##  ##### ########## #####     g ##################################   ##a    g        g ###     #
### ####### ####    l    ##  ##### ####  #### ##### f     #######  r   ##########################       r        ###  g  #
### ####### ####    ##   ##  ##### ####  #### ####### tg  #######      #########b     ###########            c           #
#   ####### ####    ##       ####  #### #####  ######     #######    ###########      ###########       t b b        r ###
#      #  #    ### #####  #  ##   ####  #      ##     t#    #     # #########   #  #      #     #  # ##f     ## #     #  #
#   ####  #     f      #  #  b    #     #          #   #    #   f #         #   ## # ##r g####  #  #  #         # t## #  #
#   #     #  t    l   a#  #       #     #    g     #   ######r    #     #   #     a#  #   r  #  ## #  #         #  #  #  #
#     rf  #            #  #    ## #  ####   ####   #      A       #######   #      #  #      #     #  #   #######  #  #  #
# # #######   t# ##    ####    #  #  #      #  #a  #                        #     t## #      #     ## #   # A      ####  #
#t#     b     a#  #         g  #  ## #     c#  #   #   l   a     a      t   #       r #   aa # ##     #   #              #
#     #     a  #  #            #     #      #  #   ##########################    l    # ##   #  #     #####              #
###   #######  ##a# ##   a######     #      ## #          b       r           r    a  #  #   #  # ##                g    #
#    r      #     #  #t   #  g       #         #            t t  #        a   a       #  # g #  #  #   t              # ##
#a  l       #     #  #f   #          #       g #                 #######       ########  #####  #  #      ta   a      #  #
#   # ###   #  ####  ######     ######   #######g    ##########a       #       #       f        #  #                 a   #
#   #   #   #  #      a      a  #        #                    #        # ##a   #           r    #  #        ##############
#   #   #   #  #       #        #a     a #   c       #        #        #  #c   #  a            l#  #     t a#            #
#   #   #   #  #########   a ####        #           #        #        #  #    #  # ##### #######  #           bf #   aa #
#   #   #   #     t      f   #      f    # b      #### g t ## #    g   # a#    #  #     a    c     #r a ###########      #
#   #   #   #  #########     ####        #           # t   a  #        #  #    #  ###############  #              #      #
#   #   # a #  #       #   a    #        #           #    t   #        #  #    #         f      #  #    a   #      f     #
#   #t  #   # c#                #        #         a #b       #  r     # ##    #   a      l   g #  #        ##############
# f #####   #  #### t######     ######   #######     ##########        #     c #         a      #  #                     #
#          g#     #  #    #          #  b      #                 ####### a     ########  ##### a#  #     l           b#  #
#           #     #  #    #        t #r      f #f                #                    #  #   #  #  #                cr####
###   #######  #  # ##    ######  f  #      ## #      f     l         g               #  #   #  # ##                  a  #
# #   #    c   # l#            #     #      #  #  c##########################         # ##  c#  #     #####r             #
# #           f#  #            #  ## #      #  #g t#               f        #     g   #      # ## a   #   #              #
# #########    ####    ####  t #  #l #      #  #   #a         f      gl     #      ## #      #     ## #   # b      ####  #
#         #  t         #  #    ## #  ####   #### r #       af     #######  t#      #  #      #   a #  #   ####### A#  #  #
#   #     #            #  #       #  r  #          #   ######     #     #f  #      #  # f    #  ##r#  #         #  #  #  #
#   ####  #a      t    # A#       #     #          #   # t  #     #         #   ##b# ##a  ####     # f# g     a #  ## #  #
#      #  #    #########  #####   ####  #a     ##  #   #    #     # ###### ##   #  #      #     # a# ##   c  ## #     #  #
# ##  #### c######     a  f   ###     ## ####              ###############   ##        ## l ## ############   r   l      #
#     #### a######      a     ####    #                                f##   ##      g ## l ##         t  #  g           #
#a fa  f    ######  ##           #          A              #      t     ##   ##        ##l  ##            #              #
#a          ######  ##t  #####  f   ####### #t            ##     g       #   ##        ##   #  l          ##    r     g  #
#    f     a        ##  b#####  #####    ####             ##          A  #   ##        ##   #     g       ##  t          #
#         t   g       a  ##### ##        c                 #             ##  ##    t   ##  ##             #              #
# bt   #####  ###     a  #####                             #             ##  ##      b ##  ##             #              #
###   a#####  ###        #####                             ##  l       g ##  ##        ##  ##          l ##              #
###    ##### a###  a     ###### #############      b       ##            ##  ##   g    ##  ##            ##              #
###    #####   g  t###a  #####   ##                        #             ##  ##        ##  ##             #              #
###t  a#####       ###   b       ##      #   #####################        #  #          #  #        #######   #  ## #### #
###    #####a     a###          ##########  ################################## # ### ####  ################   #  ## #### #
###    #####  f    ###  #########      ###  #g                      ##  ###### # ### ####  ###  ##                       #
###c     a r       ###  #########   b    #b #          g            ##                        t ##                   r   #
###    c   r       ###  ######  #             ## #############                     t             #      ###   #  ## #### #
### g          ta  ###          #  t     #   ###  ################# # ######## # ### ####  ################   #  ##   ## #
### t##########    ### a a t    ##       ##b  ##                ### #  ####### # ### ####  ###########        b       ## #
###r ##########f   ###     ###  ##       ## # ##                                                              g   t   ## #
###r ##########    ###g f  ###   ##       #   ##             g            g    t                                  t   ## #
###  ##########    ###  ga ###t  ##      ##   #          l       t    b                                                # #
###  ##########    ###      gl   ###     ##  ######################  ### ####  # ### ####  ###  ###########   #  ## #### #
###  ########## t  ###f   a t #    #############################  ##  ##  ##  ##  ##  ##      #   ##  #####   #  ## #### #
###  ##########    ###  ##### #  #  ##            r            t  ## r##  ##  ##  ##  ##   #  ##  ##          g          #
###  ##########    ###  ##### ####  ##  #                ##      g #  ##  ##  ##  ##  ##   #  ##  #                      #
###  ##########  a            ###   ##  ##   ########### ##        #  #   #   #   ##   #   #   #  #           #  ## #### #
###   t     g       a           ## f##  ## l ##############        ############# ######### ########   g       #  ## #### #
### bf  ra        #####    l     ####   r#            r  ##        ############# ######### ########                      #
###           f   #####           ########  #       t                                            #                       #
###  b#####  ###      c  ##########    ##   #   l        #   r  g   ##                         t##  g t  A           r   #
###   #####  ### t   a   #####        c     ####################### ##                          ## ########  ##  ## #### #
###         t         a            f       #################### l############### ######### #  #######  ####  ##  ## #### #
### a   b                   f ####  ########                     ##     ##  #### #########  #      ##         #   l      #
###       ############    a     #####                  ##      l ##     ##     #      #     ##     ##   g    ##          #
###       ############a    b  f   ####                 ##        ##     ##     ##    ## l   ##     ## b      ##          #
#              a        ######   ##  ##  ####          ##        #      ##     ##    ##     ##   l  #        ##  l       #
#               g       ##########    #  #  g          ##        #      #      #     b#      #      #        ##          #
# #############         ######f t    ##  #             ##          ###### ###########################        ##          #
# #############    a     f           ##  #             ##         ######  ###########################        ##      g   #
# #############         g  b      ########  c          ##         #                                #         ##          #
# ############# a  ######         #          #######    #         ##                              ##  l      #    # #### #
# ############# a  ###### a       ##         ################## #                       g         ## ######  ### ## #### #
# #############    ######         ##        #         #######            ##############################  ##  ###A        #
# #############    ######       t  #       ##t      l          ##     ##########################     ##                  #
# #############    ######     ######   #####               g   ##    a   #                  # t  b   ##                  #
#t#############     g                  #      r               rt#     t t##            g   ##        #                   #
# #############       a    ###         #                                                             #           a       #
# #############        c   ###        ##  ####### t       ##                               g#       ##     #         ### #
# #############   b      b ###       ##   #  ######### ## #####                            #######  ## ### # ### ## #### #
# #############  a         r  t  r   ##   #        ##b ## ## ## ############ ############# ##############  # ##t ##      #
# #############   #####           ###### ##  ##    ##  ##    ##           b                            ##t   ##  ##    # #
# #############  a#####       #   #          ##t   ##  ##    ##                g         l         f   ##    ##  ##    # #
# a       a    a              #t  #    t  b  ##    ##  ## l  ## ############ ############## ########## ##    ##  ##    # #
#    b                        #   #          ##    ##  ##    ## #########  #   ########  ##  ############    ##  ##    # #
# ###########  a #####  a f   ## ##          ## l  ##  ##    ##          b ##           A##            ##    ##  ##    # #
#  ##########    #####      ga            ##  #    ##  ##    ##            ##            ##            ##    ##  ##    # #
#a        a   b  #####   g####       ######## #     #t #     #             #          g   #             #g    #  #     # #
##########################################################################################################################
