metadata:
  gen_time: 8.173654079437256
  timestamp: '2025-04-18T22:46:35.681193'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
# ##   ##  t A###     t##   #     ##        ##      ##      ##t      ##      ##      #                 b ###   ### ##  # #
#                            c         fA           ##   f  ##   #   ##      ## a  # # t  ######  c #a#      ##### #  #  #
## #   ##     ###      #### #  #g          c a  ##  ##      ##f  #   ##      ## t    #      ##      #      ##   #        #
## #######################   #####            ##### ##      ##   #   ##      ## #           ##           # ##         f  #
##                           #######    l   ####### ##     b##   #   ##      ## ##  #  ## ###### ##  #  ####           A #
## #   ##############    ## ##  ####        ####  # ##      ##   #   ##  t   ## #  ##   # ##  ## # l ##  #########  A ####
# l       ##   ##     #   #      ##    ##    ##     ##      ##  t#   ##      ## ## ###  l #    #    ### ##########   ## ##
#                           #    c     ##   b       ##r     ##   #   ##      ##t##b#      #    #      # ##         ##  A##
# ######################### ###       ####       ## ##      ##   #   ##      ## ####  b               ####         ##   ##
##f#######################   ##   ##  ####  ##   ## ##  f   ##   #   ##      ##   a               a   l        g   ##   ##
##                           #    ##   ##   ##    # ##      ##   #   ## f  f ##  ##    c #      #      ##f     b   ##   ##
## #######################  f    t        b         ##      ##   #   ##      ##  #                      #          ##   ##
### ####################### #           g           ## t    ##   #   ## r   r##  #                b     #   # f         ##
### ####################### ##   ##          ##   # ##      ##   #   ##b     ##  ###                  ### ##### ####    ##
##f  #######################    ####        ####  # ##l     ##   #   ##      ##  #         # f#         # ####    ## #####
##   #######################l   ####  ####  ####    ##      ##   #   ##      ## l##           b        ##    ######f## ###
### #####     ##############     ##   ####   ##     ##      ##   #   ##      ##      l     #  #     l               ##   #
#   ##           ########### #  g##          ##   # ##      ##   # b ##      ##                          t    ##    ##   #
###   ###l f  ##  c  ##    # #                    # ## f    ##   #   ##     l##          ###  ###              ##   #    #
### #                         b                     ##      ##   #   ##      ##                           #######   ##   #
##   ################ #    ##               l       ##    f ##   #   ##      ##                      a    ########  ##   #
##f  ################   #####                       ##      ## t #   ##      ##f    #        t      t#       ##t #r ##   #
###b################# # ##### ##f    ##g ##     ##  ##  b   ##   #   ##      ##  #  #      #  #    b #  #        ## ##   #
### ################# # #########  ####  ####  #### ##      ##   #   ##      ##                 t               ### #    #
### #r t############# # #########  ##########  #### ##      ##   #   ## f    ##                                 g##g##   #
#          f              ######     ######     ###t##      ##   #   ## l    ##              b   a b       t        #    #
## ##   ############ f####            ####       ## ##   f  ##   #   ##      ##           ##  ##                ###  #   #
## ############################                  ## ## t    ## r #   ##      ## t#         #  #  l     c#         #  #   #
## ###########################    ##        ##    # ##      ##l t#   ##      ##  ####      # g#     r####       # #  ## t#
## ## b ############  ####        ##        ##      ##      ##   #   ##      ##  ####                ####       #t#  ##  #
#              a     #      #   g####      ####     ##      ##   #   ##      ##   ###                ###        ###  ##  #
### #   ############ ########   ##### c    #####c   ##    r ##   # b ##  b   ##   ###             g  ###  ##     ######  #
### ################ ########  #####     b  #####   ## t    ## b #   ##  f   ##        la #a              ##  #          #
### ################ ########  ####    ##f   ####   ##      ##   # f ##      ##    f  c   c     g   #   c ##  #   ##    l#
##   ############### ########   ###   ####   ###    ##      ##   #   ##      ##   f       #      t  #  b  ##  #   ##     #
##   ############### ##    ##   ##    ####    ##  gt##      ##   # r ##      ##         c #     #####   f ##  ######     #
### ###########                ###f    ##     ###   ##b   r ##   #   ##      ##       g   ###a###  r   #####  ####       #
###   ###t    #      ##  c # ######    ## f  ###### ##      ##  f#   ##      ##   l           a        ##### g#### c c   #
#f  ##      c   ############ ######b  ####   ###### ##   r r##   #   ##      ## ####       b      t           ####       #
### #####    f##############  ######  #### c######  ##      ##   #   ##      ##    #l    a                    ####    ####
##   #######################    ####b  ##  A####   f##      ##   #   ##      ##    #           ################       ####
##  r#######################   g ##    ##c   ##t    ##      ##   #   ##      ## ####   t   b r ################       ####
### ####################### ##                    # ##      ##   #   ##    A ## r              ###########################
### ####################### ###           c      ## ##      ##r  #f  ## f    ##  tt            ###########################
##  ######################   ##    ##      ##    ## ##      ##   #   ##      ##  b  g          ########    ####      #####
##  ######################       ######  ######     ##      ##f  #   ##      ## #######################    #### b   c#####
#  #######################   c   ######  ######     ##b     ##   # l ## b    ##     ##         c   f     b ####f f   ### #
#  ######################## ###   ###      ###   ## ##      ##r  #   ##      ## #g a##               ## a  ####      ### #
# ##   ##   ###t #######    ###   ##     l  ##   ## ##      ##   #   ##      ## #  c##r a            #######         ### #
#     ffc ## b #     ##  ##   b  f                f ##      ## r #   ##      ## ######t              #      g #      ### #
## #  b## ## # ## ###  #### #          ## g         ##      ##  f#   ##      ##   g  #### #####    a #        #      ### #
## ###### ## # ## ### ####      ##     ##     ##    ##      ##   #   ##   t  ## c    ###a #####      #  #######          #
## ###### ##   ## ### ####t t #####  b      f#####  ##      ##   #t  ##      ##   f  ###  #          #  #######          #
## #  r##      ##   c  #### # #######      #######  ##      ##   #   ##      ##      ###r #          #     ####    t    c#
#            l gf        ##    #######    #######   ##      ##   #   ##      ## ########  #          # f a ####   r      #
# ##   ##    b###      ##   #    #####    #####     ##  f   ##   #  t##      ##     ####  #       t  ########    a     ###
##      ###  ###    f          #                #   ##      ##   #   ##    b ##     ####  #          ##   rb#            #
#r      ###  # ##  #           ##              ##   ##      ##   #   ##g     ##         ## ###     ##### # ###      # ####
#       ###  # ##             ##                ##  ##      ##   #   ##     f##         #      ###    t    l    ###g   # #
#       ###    ##             #   ## ##  ## ##   #  ##      ##   #   ##   t  ##  #  ##      t  # #      r     ### #      #
##   #   ##   ###             ## l   #  g #b    ##  ##    f ##   #   ##    r ## ##   #             ## #  ##         g    #
##   #   ##            ###     #   ### ## ###   #   ##      ##   #   ##  l   ## #   ##      ##     ## #   #         #    #
# g    f #    r         ###  # #    #  ##  #    # # ##   b  ##   #   ##      ## ##   ## ## ###           ##b#      ##b ###
#        # ##      ##   #    #   ## ##    ##r##l  # ##     l##   #   ##      ## #     # #  #   # #       ## #      #     #
#        g ##           #        ## ### #### ##     ##      ##  r#   ##l     ##    ## ### ############      ## ## ## ## ##
#          #    #       #             #  #          ##      ##   #   ##      ##  ###   ##    ##   # ##         ## #  #  ##
#   a           #       #  # # ##  ## #### ##  ## # ##    r ##   #   ##      ## ##r#      ####  ###  #        ##        ##
#    #       #  ##  ######   # ##g ##      ##  ## # ##      ##   #   ##      ## #  ##  ##  #    #      #                 #
#        ##t##              #### l##  ####  ##f ### ##      ##   #   ##   r  ## ##      #  ##     ###f ### #  ##        ##
##       g     #g           #     #   #  #   #     r##      ##   #   ##      ##  #   ## #   # ### # #   ## # ##          #
#              #      #     ##    g            ll # ##      ##   #   ##      ##  #      b # # ##    ##     #### ##   ##  #
#        ##           #      ### g##    f   ##  ### ##      ##   #   ##      ##     ## ## # ###      ##         t#   #####
# ##   ####    #      #  #    #    ##      ##    #  ##      ##b  #   ##      ##     g ##                                 #
####   ####   ##      ##            #      #r      f##      ##A  #   ##      ##       ##                                 #
########### #    ###    t          ##  ##  ##       ##      ##   #   ##      ##   ##############  ####   g               #
#  ###      t     ##       f #   r                # ##    b ##   # l ##      ##   ##############  ####                t  #
#  ##       ##  t###r            ##  #    #  ##    #       #           #       #                                     f   #
#           ##    ##  #a ##  # l  # a##  ##  #    #    ##   #   r     #   ##                           b   r             #
# #      ## ##      b #g ##  b  f##          ##      ##  #       l       #  ##  ####  ########## l####       r  g       g#
# #  #  ##  ## f     f#   #   ##  ##       f##  ## ##       #       l #       ######  ##########  ####     f             #
# #  #     ##             # # #   #  ##  ##  #   #           #     l #                ##                                 #
# #  ##  #  #  # #  ##       r##    l           ##           #       #                ##        g              f         #
#     #    f#  # #                    ####       g            #l    #        f  ########  ##  ######  ####################
#           #    t       ### #  a# ##  ##  ## #   #    ##                 ##    ########  ##  ######  ####################
#   #       #           #### ## ####        #### ##   #  #               #  #     ##      ##      ##                     #
#   ###     #          ##    #  #  # ##  ## #  #  #              #      l     b   ##      ## tt   ##                     #
#                    # ##       # ## ###### ## #    r #      #       #      #     ##  ##########  ########################
#              b   ######    #    #  # ## #  #    #    #    #      t  #    # r    ##  ##########  ########################
#        l         ######       ####        ####            #   r     #                   ##   b     t                t  #
#                    # ##       ##    f  r    ##         # #   #   #   # #                ##                     a       #
#   ###     #          ##              ##g              #     #    r#     #               ##      b                      #
#   #       #           #### #  ####  #### #####  #  A  #     #     #     #     ######################                   #
#           #            ### #### ## b#  #  ## ####   r  #     #   #     #      ######################                   #
#     # l   #  # #          g ##   ##      ##   ##       #     #   #     #  t                 g       ###########  #######
# #  ##  #  #f # #  ##               l      f             #     # #     #                              ##########  #######
# #  #  g  ##             # # #   ##   ##  b##   #        #     # #     #       ######################          f        #
# #  #  ##  ##   r    #   #   # g r    ##        # #       # #   #   # #       #######################          r        #
# #  g   ## ##        #  ##   ##   ##  ##  ## # ##  ## g      #  #  #        #            l        l  ############ #######
#           ##    ##  #  ##      ###        ###     ##        #  #l #        ##            b               ###           #
#  ##       ##   ###    f    #  ## f   ##    g##  ##       # #   #   # #    l  #                      #### ### ### ###   #
#  ###           f##            #  ### ## ###  # tr       #     # #     #       g                     #### ### ### ###   #
########### #    ###    g b  #     ##  r   ##     #       #     # #     #       ########################## ### ### ###   #
####   #### f ##      ##   l #  g   r             #      #     #   #     #      ###################### ### ### ###  b    #
# ##   ####    #      #  # g #    b ## ## ##      #  t   #     #  f#     #          g                  ### ### ###########
#        ##       b   #              b ##               #     #     #     # A      l                   ### ### ###########
#              #      #     # ##      ####      ##      #     #     #  g  #  c        r              l ### ### ###########
##   a      l  #            ####  ###  ##  ###  ###      # #   #   #   # #      ######################   g ###           #
#        ## ## f     g      #     ##        ##    r         #         #         ###################### ###############   #
#    #       #  ##  ######              l   c          #    #         #    #                           ###############   #
#               #       # g# ##    ## #### ##g   ##   #      #       #      #                         g###############   #
#          #    #       #    ###g   ###  ###    ###              #                  t            f                       #
#      t   ##           #    # ## ####    #### ## #   #  #               #  #   ########################## ### ###g#######
#   g    # ##      ##   #        l##        ##         ##       l         ##    ##########################         #######
#        #              ###  f##  #          #  ##            #     #    r      f               fg    #### ### ### #######
##  r#   ##f       b   ### g          #  #                   #       #           r      f  g               ### ### ###   #
##f  #f  ##   ###            ###      ####  r   ###  t       #       #           t      g             #### ### #######   #
#       ###    ##          g   ### # ##  ## # ###  ##       #         #       ##        f t           #### ### #######   #
#       ###  # ##                  ###r   ###        ##  #              t#  ##                        ####r### #######f  #
#       ###  # ##  #                                   ##   #         #   ##            t                  ###           #
##      ###  ###         gf  # #c##  g ##  r ## # ##       #           #       #######################     ###      r    #
##########################################################################################################################
