metadata:
  gen_time: 10.562798261642456
  timestamp: '2025-04-18T22:57:39.072277'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 120
  height: 120
  root:
    _target_: mettagrid.map.scenes.auto.Auto
    config:
      num_agents: 10
      objects: {}
      room_objects:
        mine:
        - uniform
        - 0.0005
        - 0.01
        generator:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        altar:
        - lognormal
        - 0.0001
        - 0.01
        - 0.03
        armory:
        - uniform
        - 0.0005
        - 0.01
        lasery:
        - uniform
        - 0.0005
        - 0.01
        lab:
        - uniform
        - 0.0005
        - 0.01
        factory:
        - uniform
        - 0.0005
        - 0.01
        temple:
        - uniform
        - 0.0005
        - 0.01
      layout:
        grid: 1
        bsp: 1
      grid:
        rows:
        - uniform
        - 2
        - 4
        columns:
        - uniform
        - 2
        - 4
      bsp:
        area_count:
        - uniform
        - 3
        - 15
      room_symmetry:
        none: 10
        horizontal: 3
        vertical: 3
        x4: 3
      content:
      - scene:
          _target_: mettagrid.map.scenes.random_scene_from_dir.RandomSceneFromDir
          dir: /scenes/dcss/wfc
        weight: 20
      - scene: /scenes/wfc/blob
      - scene: /scenes/wfc/blob2
      - scene: /scenes/wfc/blob3
      - scene: /scenes/wfc/blocks
      - scene: /scenes/wfc/dungeons
      - scene: /scenes/wfc/mazelike1
      - scene: /scenes/wfc/mazelike2
      - scene: /scenes/wfc/simple
      - scene:
          _target_: mettagrid.map.scenes.maze.MazeKruskal
          room_size:
          - uniform
          - 1
          - 3
          wall_size:
          - uniform
          - 1
          - 3
        weight: 3

---
##########################################################################################################################
#### ### ### ### ### #         r ###        t                  b                                       ###   ##t  ###    #
#### ### ### ### ###                                                              #   ####  ####f ########  ####  ####   #
##            gb  ## #    b   b###       l         t                                                               ##  ###
#             b   ####        #####    #                                ###  ###g ### ################################ ###
##                ####  #     g        ##                              ############## ################################ ###
##                  ##  ##        r    ###                                 #c    #    ## # ## #   # #  # # # # ## # ##   #
##l               ##    ### #####      ##                       l      ####   #####              l                       #
##                ## t g##   ###       #             l                                            #      #   #           #
##                ## #  #     #c r         c                              l   #   #  # #          #b  t  #          # #  #
#                 ####   t                                             ###### #####          #              ll#         b#
##  b    r        ####   f                g  l        t                #        ##         #     f              # l      #
##   b              ##    #####     #                                  #############  # #                        l # #  ##
##         A      ## #     ###     ### b          g            g            ##            f    # # #    # # #            #
##  f             ##        #t    ##### #####                          ############  #  #  #                    #  #  #  #
### #### #### ## ###t                    ###             g               ###cr###                r   ##                  #
### ####l#### ## ###       r              #          b           A              # f  #  #     # #        g # #     #  #  #
#    ##                    ##### #####     ##      f                a    # #  # #              l     ##                  #
#    ##                     ###   ###       #    f          f     f      ###  ###    #  #t #                   b#  #  #  #
#    ##           r    #     #     #    #                         t    ############            # # #b   # # #            #
#    ##                ##     #####     ##                                        ##  # #             f            # #  ##
#                      ###     ###      ###                 g          ### #### ###       l#       bl           #        #
#    ##                ## #     #      t##                                    # #            # f              # l        #
#    ##        r       #  ##     #####  #          g      g             r###  ###    # #  t       #      #          # #  #
# r  ##                   ###     ###        #### ################ #### ###########           #   #      #l  #           #
#  r                      ## #     #         #### ################ ####   t      g                     l   f r   f       #
#    ##                   #  ##               ##   r     ##         ##             b  ## # ## # # # #  # # # # ## # ##   #
#    ##                      ###        ##### ##g                   ## ############## #########################   #### ###
#b   ##  r                   ##          ###  ##         ##                      #### ########################  ###### ###
#    ##         g            #      f     #  #### ################ ##### #  # #  # ##  ##    ##    ##t ##          ##  ###
#                                    #####   #### ################ ####l #### ####    ####f ####  #### ###   ###  ####   #
#    ##                             b ###    ##              g           ##            ###   ##   ###  ###   ##   ###    #
#######              g        #####   b#                               # ########## A ###   b##            ##            #
#######          f             ###      #######    f                          ### g  ## ##   #              ##############
##   ##                  ba     #        ###l##                  t       #    # #A  ##      a#                           #
#  l                    #        #####    #  ##               b g    ### ###### #####        #                           #
##   ##                 ##        ### r     #### ####### ## ####### ###    ##     ##       ###      #              b     #
#######                 ###      t #     b  #### ####### ## ####### ########## #### b      # ## #####              f #####
#######                 ##          #####    ##                          r   # #           #  # #               ##  ##  b#
##   ##      f b        #         b  ###     ##                      ##      # #      #  # #    #####  ## ###########    #
#                                     #                               b####### ####  ##  ##               r              #
##   ##                                ##### ##                    t ##  ##      ### #    ##       ##  ## ##       a     #
##   ##                                 ###  ##   a       b          ## ###### ##### #a  ###      ##             #####   #
#           l                            #            b                        ##    #  ##    # ###      ## ## ####  ##  #
##   ##        r                          #####                      ### ##########  # ##  # ##              ##       ## #
##   ##     b          #                   ####      tg              ### #  ###  ##  # #   ###                         ###
#                  r  ###        t          ###                      ###g#  # # l#   # #   # #                       #  ##
##   ##             t#####   #     b#####         #     #     #  #r    #             # #   # #          ##    b ##      ##
##   ###### ##### ###        ##      ###          #     #     # b#     #     #         ##      ##     #   #           #  #
##     ###a##      # ### #    ##   f   ##    ###  #  #  #  # ##  ####  #  #######     ##        ##     ## #            ###
#   f# ##l  #a###### #   ##             # # #     #  #     #  tgf  f      # f   g    ##           #b    ###            l##
####  f#      ## ##  # ###  ##      cb ## ###f    #  #  g  #  f    f      #         ##    ####### ##     ##             ##
###    ##a  ###      ####t          ## #  ##   ##########  #  # t####  #  ####  #####    ##     b  ##   ##      ###### g##
##   #      ##   t   ##     ####r   ## ##               #  #  #  #  #  #  #  # l         #       r  ##  ###    ##   #   ##
###  ###g##  ##   ##     ##  ##    ##  ## f #       g g #  #  #  #  #  #  # l#           # f       ###    ##   #   ## ####
#        #    #   ##   ###          # ##  #########  ####  #### f#  #######  #  #        ## ########    # l##  #   #  # ##
#     t     # ##  a  ####    ####   ###   #    #        #     #        #  #  #  #                    #  #   ## #      # ##
#          t# r   #  ## ##     ##   ##  r## #  #        #     # f      #  #  #  #  ## #### ##    r   ## #    ##   #   # ##
#     #  a  ### # #a               ##     ###  #  ####l #  #  #  #######  #  ####f   ##     ##    r   ###     ##        ##
#  t ##         #              ##          ##     #  #  #  #        #     #         ##       ##  r######       ##      # #
### ### # ## ####       # # ## ##                 #  #  #  #        #     #        ##         #####             #   r    #
#   #   #  #   #  # # ### #       r      ### ###  #  #  ####  # g#######  #######    b    r r                            #
#t ## ###f #      ### ##  ##  ## #######   #         #  #     #  #     #  #        ##      t#####################        #
#   a #   ##   ##   ###   ### #ab# ## ## # #r t      #  #     #  #   g #  #         ## #######                           #
#r #### # #b    #    ###    #    g       #   ###  # r####  ##########  # l#  #  #    ###                                 #
#    #  # ####  ##  ## ##     ###   ##   ## g     #     #     t  #  #        #  #  ####  l   b        #############  #   #
#       ### ## b## ##       ####    f#   ##       #   t # f      #  #        #t #g          ## ### #####               ###
## ##   ##   #   ###        ##       # #  ##r###  #############  #  ##########  ########## ##   ##    r         r        #
#  ###        a####       t  ##f##     #####   #     #     #     #g #  #     #  #       #### t  l   ######################
#    #t ##t t####         ##### ##   ### #  l  #     #     #     #  #  # b   #  #  #   ## ## ########   ##   ##          #
#      ### b##  t ## ##    ##                  ####  ####  #  ####  #  ####  #  #  ##  #       l #                   #####
## ## f# # f       #  ##  ##         #      #  #              #              #      ## #   l  ##                  #####  #
####   # #  ####   #####  #         ##      #  #      l       #              # t     ##      ##   #################      #
#          ## ## r## # ##         f ## b f ##  ####  #  #  #  ####  ####  ####### g   ##     ###   #          #          #
### ##     #   #     r  ###  fa        #   ##  #     #  #  #  #  # r#A #     #  #      ##    # #  ## ###########         #
##  #              g          ##    ## ## a    #     #  #  #  #  #  #  #     #  #       ##  t# # ##      r A   ##       b#
###            ## #   ##   ##a #    ##         #  ####  ####  #l ####  #  ####  # t    ###   # # ###      t     ##    # ##
#            ###  ###          ## #  ##  ##       g  #     #     #           #         #     # # # ##            ##  ##  #
###                   ##   #   ####  #####        A  #     #     #           #t     g  # #   # # #  ##            ####   #
# ##         ## b ##  ##   # # # ##a    #      #######  #### f####  #  ####  #  ###    # #  ## # #   #                   #
#    ###r     #   # ###### #   #      ###            #     #        #     #  #     ### # #  ## # #   #  t##### ###########
##  ####  l# ##  ##   ##   ##  ## #   ####  #        #  r  #        #     #  #       c###          r              f###   #
######r#####                      ##### ########  #  ###################r ####  ###   ###     t     c              ###   #
#    # ##             r f           g## # f  l    #      r   r      #            l    ###                    c     ###   #
#       #                           l#         t  #              g  #   f             ###  r####################   ###   #
#         l  #        f       t #                 #                r#                 ###   ####################   ###   #
# t ##       ##       ##       ##       ##          t        b   b#########      ##   ###   ####################   ### c #
#    ##    #######  ######  #######  a ##              t####### r #########   g  ##         t                 f          #
#    ##     ##   #   #### t #   ##     ##    #########  #######   #########      ##                     t        f    l  #
# #  ##     ##  f   #####       ##     ##  # #########  #######   #########      ##t    r       t    t  t                #
# #  ##     ##   ## ##t ## ##   ##     ##  # #########  ####### r          r ##  ########   ###              ###   #######
# #  ## b   ##   #   #  #   #   ##     ##  # #########  #######     a        ##  ########   ###           c  ###   #######
###  ####   ##       #  #       ##   ####  ##r          #######r      ##     l     ###### f ###              ###   #######
#     #### ###  ##  ##  ##  ##  ### ####      r  r      #######       ##        g           ###a       t     ### r       #
# #      #   ####f           ####   #      # ##g      r #######       ##  #########         ###          r  f###    c    #
###      t    ##    ##  ##    ##           ####         #######  g        #########         ###        cA    ###         #
#  l          ##    #   f#    ##         A   ##         g                  l          ###   ####################   ### g #
#       f ##  ####r #    #  ####  ##         ##  ##          b    ####                ###   ####################   ###   #
#          #   ##   ##  ##   ##   #       g  ##  ## t   f         ####  ###########t  ###   ####################   ###   #
#   ##     #  ###            ###  #     ## l ##  ##   ####        ####  ###########   ###   ###              ###   ###   #
#    ###   ## ##              ## ##   ###    ##  ##   ####        ####  ###########   ###   ###    f         ###   ###   #
#   ##    f#  ###            ###  #     ##   ## t## t ####        ####  ###########   ###   ###     c        ###   ###   #
#          #   ##   ##  ##   ##   #          ##  ##   ####       r####g ###########   #########      f       #########   #
#   f     ##  ####  #  b #  ####  ##         ##  ##  r####  g##   ####  ###########c  #########  t           #########   #
#      t   f  ##    #    #  r ##                      ####   ##   ####g ###########   #########           c  #########   #
# #           ##    ##  ##    ##           ##         #### b ##   ####  ###########   ###                       g  ###   #
# #      #   ####            ####   #      #          ####   ##                       ###                          ### c #
# f   #### ###  ##  ##f ##  ##  ### ####  r  tl                    t                  ###                          ###   #
###  ####   ##       #  #       ##   ####  ##         a                t     ##       #########   f A  rc   a#########  t#
#   r##     ##   #   #  #   #t  ##     ##  #  ###  ###    #################  ##       #########              #########   #
# #  ## f   ##   ## ##  ##r##   ##     ##g # ####  ###    #################  ## t     #########           r  #########   #
###  ##     ##      ######   r  ##f    ##  ######  ###    #################  ##   t  a     b###              ###         #
#    ##     ##   #   ####   #   ##     ##    ####  ### g  #################           t     ###              ### f       #
#    ##    #######  ######  #######    ##    ####  ### f  #################                 ###              ###         #
#   ##       ##     f ##       ##       ##                           l                #########              #########   #
#            #              f  t#                          b         r        #####   #########              #########  f#
#       #  t                         #         ####  l  #####             a   #####   #########           f  #########   #
#    # ##        r                   ## #      ####     #####                 #####                                      #
## ### #####              r      r##### #####  ####              ##########r  #####     c                                #
##  ####   # ##  ##   ##   ## r#  #   ####  #  ####         a    ##########t  #####                       cf          f  #
#    ###      #   # ###### #   #      ###      ####   ###                      t                    t       r l          #
##########################################################################################################################
