metadata:
  gen_time: 0.8951029777526855
  timestamp: '2025-04-11T22:06:33.516559'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
####################################################
######       ###   ##    ###       ##         ######
######             ##    ###                  ######
######             ##    ###                  ######
######   ######    ##          #############  ######
######   ######                #############       #
######                         #############       #
#                   ####                           #
#        #########  ####                         ###
#        #########  ####    ###############      ###
######   #########  ####    ###############      ###
######   #########  ####    ###############      ###
#        #########  ####                     ##  ###
#                   ####                     ##  ###
#                   ####    #####    #####   ##  ###
#                   ####    #####    #####       ###
#              ##   ####             #####       ###
####    ##     ##                                  #
####    ##     ##                                  #
####    ##     ##  ####  ######             ########
####    ##         ####  ######   ###       ########
####               ####  ######   ###       ########
####               ####                     ########
#             ##                            ########
#             ##            ##  ###  ####   ########
#######       ##            ##  ###  ####   ########
#######            ##       ##  ###         ########
#                  ##           ###                #
#           #####               ###  ###           #
#    ####   #####               ###  ###  ####     #
###  ####                            ###  ####     #
###                                  ###        ####
#                                               ####
#     #############   #############             ####
####  #############   #############    #######  ####
####  #############   #############    #######  ####
####  #############   #############    #######  ####
####  #############   #############    #######  ####
####  #############                    #######  ####
#     #############                    #######  ####
#     #############              ####  #######  ####
#     #############              ####  #######  ####
#     #############              ####  #######     #
##    #############        ###   ####  #######     #
##    #############  ##    ###   ####              #
#     #############  ##          ####              #
#     #############  ##                     ###    #
#     #############  ##                     ###    #
#     #############  ##        #####        ###    #
# ##                           #####        ###    #
# ##                      ###  #####        ###    #
####################################################
