metadata:
  gen_time: 7.706843137741089
  timestamp: '2025-04-11T22:30:44.011649'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
######################################################################################################
#    ##  ###   #######      #####                 ##  ##    ########         ##  ##    ####       ####
#    ##  ###   #######  ##  #####  ##  ##         ##  ##                     ##  ##    ####       ####
##   ##  ###   #######  ##  #####  ##  ##  ##     ##  ##                ###  ##  ##    ####  ###  ####
##       ###   #######      #####      ##  ##     ##           #######  ###  ##  ##          ###  ####
#        ###   #######                 ##  ##     ##      ##   #######  ###  ##              ###  ####
#        ###   #######                 ##  ##             ##   #######  ###  ##              ###  ####
#        ###                   ##          ##                  #######  ###  ##                   ####
#####    ###              ###  ##                              #######  ###  ##                   ####
#####          ########   ###  ##                              #######  ###  ##                   ####
#####          ########   ###  ##     #####  ####       ##              ###  ##                   ####
#####      ##             ###         #####  ####       ##              ###              #####       #
#          ##             ###         #####  ####   ##  ##                               #####       #
#                         ###  #####         ####   ##  ##   ##   ##                ###  #####       #
#     ###      ######          #####                ##  ##   ##   ##           ##   ###              #
#     ###      ######          #####  ####          ##  ##   ##   ##           ##   ###            ###
####                           #####  ####    ####  ##  ##   ##   ##  ######   ##   ###       ##   ###
####                                  ####    ####  ##  ##   ##       ######   ##             ##     #
####        ######    ###             ####    ####  ##  ##   ##                ##        ##          #
####        ######    ###             ####    ####  ##       ##  ##            ##  ###   ##          #
#                     ###    ####             ####  ##       ##  ##      ###   ##  ###         ##    #
#     ##              ###    ####                   ##       ##          ###   ##  ###         ##   ##
#     ##                           ###              ##                   ###   ##  ###         ##   ##
#     ##                           ###  #####       ##  ##          ###  ###   ##  ###         ##    #
#         ##       ###  ##         ###  #####       ##  ##          ###        ##  ###         ##    #
#         ##       ###  ##              #####  ##       ##      ##             ##              ##  ###
#         ##       ###  ##              #####  ##       ##  ##  ##             ##                  ###
#  ####            ###                                      ##                      ########         #
#  ####            ###      ########               ##                  ##           ########         #
#                           ########        ####   ##             ##   ##                        #####
#                           ########   ##   ####                  ##   ##    ##                  #####
#      ###         ##                  ##               ###   ##  ##   ##    ##        ####          #
#      ###         ##                                   ###   ##  ##         ##   ##   ####          #
#      ###   ####      ###########             #####          ##             ##   ##   ####          #
#      ###   ####      ###########   ##        #####                    ##        ##              ####
#            ####                    ##                                 ##                        ####
#                                    ##               ##         ##     ##               ######   ####
#   ####                             ##    #######    ##         ##             ######   ######   ####
##  ####  ##    #####            ##  ##    #######    ##     ##  ##             ######   ######   ####
##        ##    #####            ##  ##                      ##  ##             ######            ####
##        ##                     ##                                                               ####
#   ##    ##               ####  ##       ##          ##                 ###                  ##  ####
#   ##          ########   ####       ##  ##   #####  ##        ###      ###  ###  ##         ##  ####
#   ##          ########              ##  ##   #####  ##        ###      ###  ###  ##         ##     #
#   ##                                ##  ##          ##    ##  ###      ###                         #
#   ##                                ##              ##    ##  ###                      ##          #
#   ##   ###       #################  ##          ##  ##    ##       ##          ##  ##  ##    ###   #
#   ##   ###  ##   #################              ##  ##    ##       ##          ##  ##  ##    ###   #
#   ##        ##                                  ##        ##  ##          ##   ##  ##  ##    ###  ##
#   ##                                                      ##  ##          ##   ##  ##        ###  ##
#                    ########                               ##                   ##  ##             ##
#              ###   ########        ######   #########               ###            ##             ##
########       ###   ########        ######   #########               ###            ##              #
########  ###  ###   ########    ##           #########  ####                                        #
########  ###  ###   ########    ##           #########  ####                                        #
########  ###  ###                   #####               ####                             ############
########  ###                        #####               ####            ###############  ############
########  ###           #######                ####      ####   ###  ##  ###############  ############
#               ####    #######                ####      ####   ###  ##  ###############  ############
#               ####                      ###  ####                  ##  ###############             #
#    ####   ##  ####                      ###  ####                  ##  ###############             #
#    ####   ##  ####  ####                                 ######    ##  ###############       #######
#    ####       ####  ####                                 ######        ###############       #######
#    ####       ####                    ####     ########                ###############       #######
#                               ###     ####     ########          ###   ###############             #
#                               ###                                ###   ###############             #
#              ###              ###                          ###   ###   ###############        #### #
#              ###              ###         ########         ###         ###############        #### #
#              ###                          ########                     ###############             #
#######        ###   #####  ##                         ####              ###############             #
#######  ##    ###   #####  ##         ##              ####              ###############             #
#######  ##    ###   #####             ##   ###                #####     ###############             #
#              ###   #####             ##   ###   ##           #####                                ##
#                                      ##   ###   ##     ####                                ##     ##
#                            ##  ###   ##   ###   ##     ####                 ##             ##      #
#                            ##  ###   ##   ###                  ####         ##      ##             #
###    #####                                                     ####  #####          ##         ### #
###    #####             ##                       #############        #####          ##  ##     ### #
#                        ##                       #############                       ##  ##         #
#                               #########         #############                 ###       ##         #
######                          #########    ##   #############      ####       ###       ##       ###
######     ##   #############                ##   #############      ####   ##  ###            ##  ###
#          ##   #############                ##                             ##                 ##  ###
#               #############                ##                                        ##      ##    #
###             #############   ########     ##  ####     ##########                   ##      ##    #
###             #############   ########     ##  ####     ##########                       ##        #
#      ####                                               ##########         ###           ##        #
#      ####                                               ##########   ####  ###                     #
#####          #####        ##########  ########          ##########   ####  ###   ##               ##
#####          #####        ##########  ########          ##########   ####  ###   ##       ######  ##
#              #####   ###                                                                  ######  ##
#                      ###                                                             ##   ######   #
###########            ###         #########                           ######          ##   ######   #
###########   #######              #########   ###                     ######               ######   #
#             #######                          ###  ##         ####                                  #
#                          #####               ###  ##  ##     ####             ##   ####            #
###                        #####      #######  ###  ##  ##                      ##   ####      #######
###     ##      ########   #####      #######  ###  ##  ##                      ##   ####  ##  #######
###     ##      ########   #####      #######  ###  ##  ##  #############       ##   ####  ##  #######
#       ##      ########   #####      #######  ###  ##  ##  #############   ##  ##         ##        #
#               ########   #####      #######       ##      #############   ##  ##         ##        #
######################################################################################################
