metadata:
  gen_time: 7.3991310596466064
  timestamp: '2025-04-11T22:08:18.731881'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
######################################################################################################
#########   ####             ##      ##            ##  #####      ##        ####  ##         ##   ####
#########   ####             ##      ##            ##             ##        ####  ##         ##      #
#########   ####       ###           ##  #######   ##                       ####  ##         ##      #
#########   ####   ##  ###       ##  ##  #######                                  ##         ##      #
#########          ##  ###       ##  ##  #######         ###                      ##   ###   ##      #
#                  ##  ###       ##  ##                  ###                ##         ###   ##  ##  #
#              ##  ##                ##           ##           #########    ##         ###   ##  ##  #
#####   #####  ##  ##                     ###     ##           #########                     ##  ##  #
#####   #####  ##                         ###             ##   #########                         ##  #
#       #####  ##       ######            ###             ##   #########           ####              #
#       #####           ######            ###   ##        ##   #########   ######  ####              #
#                       ######   #####          ##        ##               ######  ####              #
#   ##                           #####          ##        ##                       ####              #
#   ##   ######                                 ##        ##    ##  ##             ####           ## #
#   ##   ######  ##    ###                      ##    ##  ##    ##  ##             ####     ####  ## #
#   ##           ##    ###                            ##  ##    ##  ##   #######            ####     #
#   ##           ##           ######                  ##        ##       #######            ####     #
##        ###    ##           ######                                     #######                     #
##        ###    ##  ##       ######     ####                            #######                     #
##        ###    ##  ##  ##   ######     ####  ######          ##        #######             #########
##    ##  ###    ##      ##              ####  ######     ###  ##  ####  #######     ##  ##  #########
##    ##         ##      ##              ####             ###      ####  #######     ##  ##          #
##               ##      ##                                        ####  #######         ##          #
#                              #####            ##                 ####                        ##    #
#       ####                   #####            ##   ##   ##                                   ##    #
#       ####           ##      #####            ##   ##   ##  ##           ##     ###########      ###
#                      ##                            ##   ##  ##   ##      ##     ###########      ###
#                ###                     ###         ##       ##   ##      ##                        #
#          ####  ###       ########      ###         ##                    ##                        #
#          ####            ########                  ##                    ##              ####      #
######     ####            ########                  ##   ###              ##              ####   ####
######     ####    ####                              ##   ###    #####     ##    ##        ####   ####
######     ####    ####               #####          ##   ###    #####     ##    ##        ####   ####
######             ####               #####          ##   ###    #####     ##    ##  ##    ####      #
######             ####       ######  #####               ###    #####     ##        ##    ####      #
#                  ####   ##  ######           ##         ###    #####     ##        ##              #
#                         ##  ######           ##                          ##  ##                    #
#                         ##  ######           ##                              ##             ###    #
#   ######  ###########   ##  ######   ##               #######                ##  ##         ###  ###
#   ######  ###########   ##  ######   ##               #######   ########     ##  ##              ###
#           ###########       ######            ##      #######   ########     ##  ##    ###         #
#                             ######            ##      #######   ########         ##    ###         #
#                                       ##  ##  ##  ##                             ##    ###        ##
#                       ##              ##  ##  ##  ##                             ##    ###        ##
#  #######              ##              ##          ##        #####   ###  ####          ###         #
#  #######                              ##          ##  ##    #####   ###  ####          ###         #
#  #######    #######         ###       ##  ####    ##  ##    #####   ###         ##     ###  ########
#  #######    #######   ###   ###           ####    ##        #####   ###         ##          ########
#  #######              ###                 ####    ##        #####   ###  #####              ########
#  #######                                  ####    ##        #####        #####                     #
#  #######  ######                                  ##                     #####   #######           #
#           ######    ####       ######             ##                             #######  ##########
#                     ####  ###  ######     ##      ##  ###  #####                 #######  ##########
#######                     ###             ##          ###  #####                 #######  ##########
#######   #####  ###                                    ###                ####    #######  ##########
#         #####  ###              ##  ###         ##    ###                ####    #######  ##########
#                      ##         ##  ###         ##    ###        ##              #######  ##########
#                      ##         ##                    ###        ##              #######  ##########
#    #####             ##    ###  ##       ##           ###   ##       ###  #####  #######  ##########
##   #####             ##    ###  ##       ##                 ##       ###  #####  #######  ##########
##   #####  ##                    ##                          ##       ###  #####           ##########
#           ##  ##                                   ###  ##  ##                            ##########
#           ##  ##  ####                     ######  ###  ##                       ######   ##########
######      ##  ##  ####    ##############   ######  ###                           ######   ##########
######      ##  ##          ##############   ######  ###         ####                       ##########
######          ##          ##############   ######  ###    ##   ####  ##                   ##########
#               ##          ##############   ######  ###    ##   ####  ##           ###              #
#          ##               ##############   ######  ###         ####  ##           ###              #
#  ######  ##               ##############   ######  ###         ####               ###   ####       #
#  ######        ###   ##   ##############   ######                                 ###   ####       #
#                ###   ##   ##############   ######                      ###                         #
#            ##        ##   ##############             #####  ####       ###                     #####
#        ##  ##                                        #####  ####                     ######    #####
#        ##  ##                                        #####                   ###     ######        #
#        ##  ##  ######              ###########       #####        ####       ###     ######        #
#####    ##  ##  ######   ###        ###########       #####        ####  ###          ######     ####
#####    ##  ##  ######   ###                     ##                ####  ###          ######     ####
#####        ##  ######   ###  ###                ##                      ###          ######     ####
#                ######        ###                      ###               ###   #####  ######     ####
#                                     ###               ###     ######          #####  ######     ####
#       ######           ###          ###     ####              ######                            ####
#       ######           ###          ###     ####              ######   #####                    ####
#                        ###          ###     ####  ##          ######   #####                       #
#####                          #####                ##  #####   ######          #########  ####      #
#####    ##                    #####                    #####                   #########  ####    ###
#        ##        #####                                                 ####   #########  ####    ###
#        ##        #####   ##          ########                          ####   #########  ####      #
#  ###             #####   ##          ########         #########        ####              ####      #
#  ###                                                  #########                          ####      #
#  ###                                                  #########    ##         ##         ####  #####
#           ##########         #######   ###            #########    ##         ##         ####  #####
#           ##########  ##     #######   ###            #########               ##     ##  ####  #####
########                ##     #######          ##      #########           ##         ##  ####  #####
########                ##                      ##                  ##      ##         ##        #####
########                                    ##                      ##  ##  ##         ##        #####
########     ######                         ##           ######         ##                       #####
########     ######     ####  #####  ####                ######         ##                           #
########                ####  #####  ####        #####                  ##          ##########       #
#                       ####  #####  ####    ##  #####                  ##  ###     ##########       #
#                 ##    ####         ####    ##  #####        ####      ##  ###     ##########     ###
######################################################################################################
