metadata:
  gen_time: 1.6780710220336914
  timestamp: '2025-04-11T22:25:29.599034'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |##      ###|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |##      ###|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
####################################################
#   #############                 #####  ######### #
#   ##              #####                ######### #
#                  ######                ######### #
##           ###   ######        #####   ######### #
###          ###   #####       #######      ###### #
###          ##    #####    ##########             #
###                ####   ############             #
###                ####   ############   #######   #
#           #####   ###   ############   #######   #
#          ######   ###    ###########   #######   #
# ######   ######   ###    ###########             #
########   #####           ###########             #
########   #####                          ###    ###
########   #####  #######                 ###    ###
#          #####  #######  #####  ###     ###      #
#          #####  ######   #####  ######   ##      #
#          #####  ######   #####  ######       #####
#          #####  ######   ####   ######       #####
#          #####  ######  #####   ######           #
#          #####          #####   ######           #
#          #####          #####                ### #
#          #####   ##      ####           ##   ### #
####       #####   ##                  #####  #### #
####  ##  #######                      #####  ###  #
####  ##  #######       #######        ####   ###  #
#     ##  #######     #########   ###  ####   ###  #
#                     #########   ###         ###  #
####                  #########   ###         ###  #
####          ######  #########   ###         ###  #
####          ######  #########   ###         ###  #
# ##          ######  #########   ###         ###  #
# ##          ######         ##   ###  #####  #### #
# ##                                   #####  #### #
# ##                                    ####  #### #
# ##                                    ####       #
# ##                   ########  ###    ####       #
#     ####             ########  ###    ####       #
#     ####  ###        ########         ####       #
#     ####  ###           #####                    #
#     ####  ###  ##          ##                    #
#     ####  ###  ##  ###              ##   ###  ####
#      ###       ##  ###              ##   ###  ####
#      ###       ##         ###       ###  ###  ####
####             ##         ###       ###  ###     #
####             ###   ###       ##   ###          #
#        ####    ###   ###       ##  ####        ###
#        ####    ####  ###      ###  ####        ###
#  ###   #####   ####  ###      ###  ####          #
#  ###    ####   ####  ###      ###  ####  ####    #
#   ##    ####   ####   ###     ###  ####  ####    #
####################################################
