metadata:
  gen_time: 8.339397668838501
  timestamp: '2025-04-11T22:31:12.534269'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 100
  height: 100
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
######################################################################################################
##      ##  ##            ###    ###   ##            ###  #####        #####    ##    ##       #######
##      ##  ##                   ###   ##  ###            #####        #####          ##       #######
#       ##  ##  ###              ###       ###            #####        #####                         #
#       ##  ##  ###  ######      ###       ###            #####   ##   #####    ###       ###        #
#       ##      ###  ######  ##            ###            #####   ##            ###       ###        #
###     ##      ###          ##                           #####   ##            ###       ###     ####
###     ##                   ##                                             ##  ###  ##           ####
###     ##            ####                                                  ##  ###  ##              #
#       ##            ####       ##                                  ###    ##                       #
#       ##       ##         ##   ##  ##            ########          ###    ##             ###########
#           ##   ##         ##   ##  ##            ########   ####          ##    ###      ###########
#           ##   ##         ##       ##            ########   ####                ###                #
##  ####    ##                       ##                       ####                                   #
##  ####               ##            ##        ##                            ##        ###############
#                      ##                      ##                            ##  ##    ###############
#             #######  ##        ##                                   #####      ##                  #
############  #######            ##     ###            ##             #####                          #
############  #######                   ###            ##  ###                          #########    #
#             #######  ######                          ##  ###                          #########    #
#                      ######   ##                                                                   #
#########              ######   ##   ####   ######                                                   #
#########              ######        ####   ######   ####  #######  ##########                       #
#                      ######        ####   ######   ####  #######  ##########                       #
#                ###                        ######   ####  #######  ##########               ####    #
# ####  ##       ###                        ######   ####  #######  ##########  ##           ####    #
# ####  ##       ###     ##     ###                        #######  ##########  ##  ####             #
# ####           ###     ##     ###  ###                   #######              ##  ####             #
# ####                   ##     ###  ###              ###  #######              ##  ####             #
#                               ###  ###       ###    ###                           ####      ########
#               ##                   ###       ###    ###            ########       ####      ########
########    ##  ##   ###                              ###   #######  ########       ####             #
########    ##  ##   ###       ###                          #######                 ####             #
########    ##  ##   ###       ###                                                          ##########
#           ##  ##   ###       ###      ###   ###                        #######            ##########
#           ##  ##   ###  ###  ###      ###   ###   ##         ###  ###  #######  #####              #
#   ###         ##   ###  ###  ###                  ##         ###  ###           #####              #
#   ###         ##   ###  ###                             ##   ###                #####          #####
#   ###  ##     ##   ###  ###       ##                    ##                      #####    ###   #####
#   ###  ##     ##   ###  ###       ##         ##         ##          ###    ###  #####    ###   #####
#   ###         ##   ###  ###       ##         ##         ##          ###    ###  #####    ###   #####
#                    ###                       ##         ##                 ###  #####    ###       #
#          ###                                 ##             ######         ###  #####              #
#          ###                 ###             ##             ######              #####              #
#      ##              ######  ###                            ######                      ########   #
#####  ##          ##  ######  ###  ####           ####       ######  ##  ##              ########   #
#####  ##          ##  ######       ####  ######   ####       ######  ##  ##     ###      ########   #
#####      ##      ##               ####  ######              ######  ##  ##     ###      ########   #
#####      ##      ##               ####  ######              ######      ##                         #
#          ##                   ##  ####                                              ##             #
#          ##  ##               ##  ####                                       ####   ##            ##
######     ##  ##       ##  ##  ##  ####                       ###             ####   ##            ##
######     ##  ##       ##  ##  ##  ####    ##        #######  ###     #####   ####   ##    ######  ##
######     ##  ##       ##  ##  ##  ####    ##        #######          #####          ##    ######  ##
######     ##  ##   ##  ##  ##  ##  ####    ##                         #####                ######  ##
#              ##   ##  ##  ##  ##          ##                                                      ##
#                   ##  ##      ##          ##         #####                                        ##
###       ##        ##          ##          ##  #####  #####  ##                        ###         ##
###       ##    ##                          ##  #####         ##          ###########   ###     ##  ##
#               ##        ###        ##     ##  #####              ###    ###########   ###     ##  ##
#     ##                  ###  ##    ##     ##  #####  ####        ###                          ##  ##
#     ##                       ##           ##  #####  ####                                         ##
##    ##   ##        ###                    ##  #####  ####             ##        ###               ##
##         ##        ###                    ##  #####  ####         ##  ##        ###   ##           #
#          ##        ###                        #####               ##       ##         ##           #
#      ##  ##        ###                        #####                        ##         ##           #
#      ##            ###                 ##     #####       ##  ##                      ##           #
# ###  ##            ###  ######    ##   ##                 ##  ##               ##     ##  #######  #
# ###        #####   ###  ######    ##                      ##  ##               ##         #######  #
#            #####        ######             ##    #######  ##  ##  ######       ##         #######  #
#            #####        ######             ##    #######  ##  ##  ######                           #
##           #####                           ##             ##  ##  ######  ##                       #
##           #####                    ####                  ##  ##  ######  ##                       #
#     ###    #####           ###      ####        ########  ##      ######  ##  ########             #
#     ###    #####           ###      ####        ########          ######  ##  ########  ######     #
#     ###                ##  ###  ##  ####        ########          ######  ##  ########  ######     #
###   ###                ##  ###  ##  ####                  ####                ########  ######  ####
###            ##            ###                            ####                ########          ####
#              ##            ###                   ######   ####  #####         ########             #
#     #######                ###                   ######   ####  #####                              #
##    #######      #####                                    ####  #####                              #
##                 #####               ######               ####         #################           #
##                         ##########  ######                            #################           #
##   ##                    ##########  ######                                                        #
#    ##                                ######                                                  ####  #
#    ##                                                 ##  #############          ##########  ####  #
#             #####################                     ##  #############  ####    ##########  ####  #
#             #####################  ####   #########       #############  ####    ##########        #
#             #####################  ####   #########       #############  ####    ##########        #
#       ##    #####################  ####   #########                      ####    ##########        #
#       ##    #####################  ####   #########                      ####    ##########        #
#             #####################  ####                 ######           ####                      #
#             #####################  ####                 ######   ####    ####                   ####
#             #####################  ####                          ####    ####  ##  ####         ####
#   ##        #####################  ####  ##                              ####  ##  ####   ####  ####
#   ##        #####################  ####  ##  ##           ####                 ##  ####   ####  ####
#         ##  #####################  ####  ##  ##  #####    ####                     ####   ####  ####
#         ##  #####################  ####      ##  #####               #######       ####   ####  ####
#         ##  #####################  ####      ##  #####               #######  ##   ####   ####  ####
#         ##  #####################  ####          #####  #######      #######  ##   ####   ####  ####
#         ##  #####################                #####  #######      #######  ##   ####   ####     #
######################################################################################################
