metadata:
  gen_time: 0.854266881942749
  timestamp: '2025-04-11T22:06:35.326522'
config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '
resolved_config:
  _target_: mettagrid.map.mapgen.MapGen
  width: 50
  height: 50
  border_width: 1
  root:
    _target_: mettagrid.map.scenes.wfc.WFC
    pattern: '|####   ####|

      |####   ####|

      |####   ####|

      |           |

      |           |

      |####   ####|

      |####   ####|

      |####   ####|

      '

---
####################################################
#     ##     ####  ##   #############     ###      #
#     ##     ####       #############     ###      #
#     ##                                           #
#                   ##                             #
#             ##    ##    ######      #####    ### #
############  ##    ##    ######  ##  #####    ### #
############  ##    ##            ##  #####    ### #
############  ##    ##            ##  #####    ### #
############        ##  #####         #####    ### #
#                   ##  #####         #####        #
#                              ##     #####        #
# ####     #######             ##     #####        #
# ####     #######                    #####     ## #
#          #######  ##                #####     ## #
#                   ##          ##    #####        #
####                ##   ####   ##    #####        #
####     ########   ##   ####                      #
####     ########        ####                 ######
#                        ####          ####   ######
#                        ####          ####   ######
#                                             ######
#    ################                         ######
#    ################  ##########                  #
#                      ##########  #########       #
#                      ##########  #########       #
# ###                  ##########  #########  ######
# ###      #######     ##########  #########  ######
#          #######     ##########  #########       #
#          #######     ##########  #########       #
#          #######     ##########             ###  #
#          #######     ##########             ###  #
######     #######     ##########   ####           #
######     #######     ##########   ####           #
#          #######     ##########   ####       #####
#          #######                  ####  ###  #####
#                                   ####  ###      #
#                     ####      ##  ####  ###      #
##          ####      ####      ##  ####  ###      #
##  ####    ####  ##  ####      ##        ###  #####
##  ####    ####  ##  ####  ##  ##        ###  #####
##  ####    ####  ##  ####  ##  ##             #####
#   ####          ##  ####  ##  ##                 #
#   ####              ####  ##  ##    ###          #
#                           ##  ##    ###  ######  #
#              ###          ##        ###  ######  #
####      ###  ###          ##        ###  ######  #
####      ###  ###      ##  ##        ###  ######  #
####      ###           ##  ##   ###  ###          #
####      ###           ##  ##   ###  ###          #
####      ###      ###  ##  ##   ###  ###  ##      #
####################################################
